Repository jenkinsci/jenkins, pull requests merged in 2018-11, with the labels that each got.

#3648 [JENKINS-27177] Add disable plugin command and tests
  .gitignore
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/PluginWrapper.java
  core/src/main/java/hudson/cli/DisablePluginCommand.java
  core/src/main/resources/hudson/Messages.properties
  core/src/main/resources/hudson/Messages_es.properties
  core/src/main/resources/hudson/cli/Messages.properties
  core/src/main/resources/hudson/cli/Messages_es.properties
  test/src/test/java/hudson/cli/DisablePluginCommandTest.java
Labels: ready-for-merge

#3695 [JENKINS-49196] java.io.IOException: Premature EOF when shutdown CLI command is used
  core/src/main/java/jenkins/model/Jenkins.java
Labels: ready-for-merge

#3758 [JENKINS-54599] - Upgrade the Maven Jenkins Dev plugin from 9.4.5.v20170502 to 9.4.12.v20180830
  pom.xml
Labels: java11, ready-for-merge

#3718 [JENKINS-54459] Avoid Angry Jenkins when check now on Plugin Manager
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/util/Retrier.java
  core/src/main/resources/hudson/Messages.properties
  core/src/main/resources/hudson/Messages_es.properties
  core/src/main/resources/hudson/PluginManager/check.jelly
  core/src/main/resources/hudson/util/Messages.properties
  core/src/main/resources/hudson/util/Messages_es.properties
  core/src/test/java/hudson/util/RetrierTest.java
  test/src/test/java/hudson/PluginManagerCheckUpdateCenterTest.java
Labels: ready-for-merge

#3765 [JENKINS-52013] - Switch Java 11 feature branch to the default update center
  core/src/main/java/hudson/model/UpdateCenter.java
Labels: java11

#3269 [FIXED JENKINS-45235] When multiple update sites publish different versions, allow those versions to be seen
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/PluginWrapper.java
  core/src/main/java/hudson/cli/InstallPluginCommand.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/resources/hudson/PluginManager/_table.js
  core/src/main/resources/hudson/PluginManager/table.jelly
Labels: needs-review

#3767 [JENKINS-51985] - Change Java 11 support branch to use latest JDK11 images
  Dockerfile
Labels: java11

#3769 [JENKINS-54459] Fix flaky on delay test
  core/src/test/java/hudson/util/RetrierTest.java
Labels: ready-for-merge

#3768 [JENKINS-54731] Fix checkUpdateAttempts system property
  core/src/main/java/hudson/PluginManager.java
Labels: ready-for-merge

#3764 [JENKINS-45318] - Add dependancy on net.i2p.crypto to Jenkins CLI
  cli/pom.xml
Labels: ready-for-merge

#3774 Document that Jenkins.getPluginManager() is not nullable
  core/src/main/java/jenkins/model/Jenkins.java
Labels: ready-for-merge
