Repository jenkinsci/jenkins, pull requests merged in 2018-06, with the labels that each got.

#3437 Converting remaining anonymous Callable and FileCallable implementations to named classes
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/os/solaris/ZFSInstaller.java
  core/src/main/java/hudson/os/solaris/ZFSProvisioner.java
  core/src/main/java/hudson/tasks/Maven.java
  core/src/main/java/hudson/util/RemotingDiagnostics.java
  core/src/main/java/hudson/util/io/ParserConfigurator.java
  core/src/main/java/jenkins/model/Jenkins.java
Labels: needs-review

#3463 [JENKINS-51603] - Relax workDirectory requirements for a JNLPLauncher constructor
  core/src/main/java/hudson/slaves/JNLPLauncher.java
Labels: ready-for-merge

#3417 [JENKINS-51082] - Avoid attaching calling stacktrace as that is done by Channel already
  core/src/main/java/hudson/FilePath.java
Labels: ready-for-merge

#3447 [JENKINS-51355] - Print stacktraces to logs at FINE+ level when rejecting classes in ClassFilterImpl
  core/src/main/java/jenkins/security/ClassFilterImpl.java
Labels: ready-for-merge

#3474 [JENKINS-51660] Correct default URL proposed for Root URL
  core/src/main/resources/jenkins/install/SetupWizard/setupWizardConfigureInstance.jelly
Labels: ready-for-merge

#3472 Update help-quietPeriod.html
  core/src/main/resources/jenkins/model/GlobalQuietPeriodConfiguration/help-quietPeriod.html
Labels: ready-for-merge

#3460 [JENKINS-51598] - Expose PermissionGroup IDs to API
  core/src/main/java/hudson/security/PermissionGroup.java
Labels: ready-for-merge

#3370 [JENKINS-50336] Fix loading optional extensions after installing a missing dependency
  core/src/main/java/hudson/ExtensionFinder.java
  core/src/main/java/hudson/PluginManager.java
  test/src/test/java/hudson/PluginManagerTest.java
  test/src/test/resources/plugins/jenkins-50336.hpi
  test/src/test/resources/plugins/variant.hpi
Labels: ready-for-merge

#3464 [JENKINS-51608] - Improve diagnostics of errorneous cases in ClassicPluginStrategy#getShortName()
  core/src/main/java/hudson/ClassicPluginStrategy.java
Labels: ready-for-merge

#3455 [JENKINS-51541,JENKINS-51551,...] - Remoting 3.21 + Allow passing custom CommandTransport implementations to SlaveComputer from ComputerLauncher
  core/src/main/java/hudson/slaves/SlaveComputer.java
  pom.xml
Labels: ready-for-merge

#3079 [JENKINS-20998] Add Timestamp to Workspace View
  core/src/main/java/hudson/model/DirectoryBrowserSupport.java
  core/src/main/resources/hudson/model/DirectoryBrowserSupport/dir.jelly
Labels: ready-for-merge

#3354 [JENKINS-46248] - Fix potential deadlock between queue maintenance and asynchronous execution
  core/src/main/java/hudson/model/Executor.java
  core/src/main/java/jenkins/model/queue/AsynchronousExecution.java
Labels: ready-for-merge

#3482 [JENKINS-51777] Don't let tar entries escape target dir
  core/src/main/java/hudson/FilePath.java
Labels: ready-for-merge

#3487 [JENKINS-46602] - Update BCT to 2.0-alpha-3
  core/pom.xml
Labels: java10

#3491 [JENKINS-51834] - Simplify the CI for Java 10 branch
  .github/PULL_REQUEST_TEMPLATE.md
  Jenkinsfile
  test/pom.xml
Labels: java10

#3492 [JENKINS-51835] - Create a Docker image for the Java 10 branch CD flow
  Dockerfile
  docker/jenkins2.sh
Labels: java10

#3493 [JENKINS-51834] - Docker build runs smoke tests in the batch mode
  Dockerfile
Labels: java10

#3497 Update Winstone to 4.4 in order to pick Jetty 9.4.11
  war/pom.xml
Labels: ready-for-merge

#3489 [JENKINS-51889,JENKINS-51955,JENKINS-51971] - Stop using Guava’s NullOutputStream, document setChannel API
  core/src/main/java/hudson/slaves/SlaveComputer.java
  core/src/main/java/hudson/util/StreamTaskListener.java
Labels: ready-for-merge

#3495 More i18n
  core/src/main/resources/hudson/model/Job/buildTimeTrend.jelly
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/_entryForm.jelly
  core/src/main/resources/lib/hudson/queue.jelly
  core/src/main/resources/lib/layout/layout.jelly
Labels: ready-for-merge

#3188 [JENKINS-48480] Switch deprecated protocols to opt-in.
  core/src/main/java/hudson/cli/CliProtocol.java
  core/src/main/java/hudson/cli/CliProtocol2.java
  core/src/main/java/jenkins/install/SetupWizard.java
  core/src/main/java/jenkins/slaves/JnlpSlaveAgentProtocol.java
  core/src/main/java/jenkins/slaves/JnlpSlaveAgentProtocol2.java
  core/src/main/java/jenkins/slaves/JnlpSlaveAgentProtocol3.java
  pom.xml
  test/src/test/java/hudson/cli/CLIActionTest.java
  test/src/test/java/hudson/cli/ClientAuthenticationCacheTest.java
  test/src/test/java/hudson/security/CliAuthenticationTest.java
Labels: ready-for-merge

#3499 [JENKINS-51807] - Create a branch for Java 11 support and Jenkins CD
  .github/PULL_REQUEST_TEMPLATE.md
  Dockerfile
  Jenkinsfile
  core/pom.xml
  docker/jenkins2.sh
  test/pom.xml
Labels: java10

#3500 [JENKINS-51837] - Pick BCT with ASM 6.2
  core/pom.xml
Labels: java10

#3502 [JENKINS-46725] Update jnr-posix to 3.0.45
  core/pom.xml
Labels: java10

#3503 [JENKINS-52010] - Switch Java 10 support build to the experimental update center by default
  core/src/main/java/hudson/model/UpdateCenter.java
Labels: java10

#3504 [JENKINS-52019] Fix Declarative Pipeline failures on Java 10 with just a little Groovy bump
  core/pom.xml
Labels: java10, regression

#3508 [JENKINS-52028] - Update Java 11 Docker image baseline to 2.128 to pick Incrementals support
  Dockerfile
  core/pom.xml
  docker/jenkins2.sh
Labels: java10

#3507 [JENKINS-52028] - Update Java 10 Docker image baseline to 2.128 to pick Incrementals support
  Dockerfile
  docker/jenkins2.sh
Labels: java10

#3512 [JENKINS-51837] - Update BCT to 2.0-beta-2 with ASM 6.2
  core/pom.xml
Labels: java10

#3513 [JENKINS-51837] - Update BCT from 1.8 to 2.0-beta-2 with ASM 6.2
  core/pom.xml
Labels: needs-review

#3514 [JENKINS-51818,JENKINS-51841] - Update Remoting from 3.21 to 3.22
  pom.xml
Labels: ready-for-merge

#3517 [JENKINS-51994,JENKINS-46622] - Update Extras Executable WAR from 1.40 to 1.41
  war/pom.xml
Labels: java10

#3506 [JENKINS-52026] - Adding logging of called CLI commands
  core/src/main/java/hudson/cli/CLICommand.java
Labels: ready-for-merge

#3356 Add support for SHA-256/512 in update site metadata
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/java/jenkins/util/JSONSignatureValidator.java
  core/src/test/java/hudson/model/UpdateCenterTest.java
Labels: ready-for-merge

#3525 [JENKINS-52161] Improve creation-date value determination
  core/src/main/java/hudson/Util.java
  core/src/main/java/jenkins/security/apitoken/ApiTokenStats.java
  core/src/main/java/jenkins/security/apitoken/ApiTokenStore.java
  core/src/main/resources/jenkins/security/ApiTokenProperty/config.jelly
  core/src/main/resources/jenkins/security/ApiTokenProperty/config.properties
  core/src/main/resources/jenkins/security/apitoken/LegacyApiTokenAdministrativeMonitor/manage.jelly
  core/src/main/resources/jenkins/security/apitoken/LegacyApiTokenAdministrativeMonitor/manage.properties
  core/src/test/java/hudson/UtilTest.java
Labels: ready-for-merge

#3528 [JENKINS-51965] - Update Instance Identity module from 2.1 to 2.2
  war/pom.xml
Labels: java10, ready-for-merge

#3524 Revoke and revoked token
  core/src/main/resources/jenkins/security/ApiTokenProperty/config.jelly
  core/src/main/resources/jenkins/security/ApiTokenProperty/config.properties
Labels: ready-for-merge

#3523 [JENKINS-52164] Fix rename action for AbstractItems that don't define URL when including the actions taglib
  core/src/main/resources/jenkins/model/RenameAction/action.jelly
Labels: needs-review, ready-for-merge, regression

#3530 [JENKINS-52204] - Update Remoting to 3.23 to fix regressions in 2.129
  pom.xml
Labels: needs-review, regression
