Repository jenkinsci/jenkins, pull requests merged in 2018-03, with the labels that each got.

#3312 [JENKINS-49795] Fix bad serialization of ParametersAction.parameterDefinitionNames and make sure this kind of mistake produces a warning in the future
  core/src/main/java/hudson/model/ParametersAction.java
  core/src/main/java/jenkins/security/ClassFilterImpl.java
  test/src/test/java/hudson/model/ParametersAction2Test.java
Labels: ready-for-merge

#3277 [FIXED JENKINS-49319] Upgrade to PrototypeJS 1.7.3
  war/src/main/webapp/scripts/prototype.js
Labels: ready-for-merge

#3226 hudson.Util improvements
  core/src/main/java/hudson/Util.java
Labels: needs-jira-issue, needs-review

#3289 [JENKINS-22936] Move rename logic to AbstractItem
  core/src/main/java/hudson/model/AbstractItem.java
  core/src/main/java/hudson/model/Job.java
  core/src/main/java/jenkins/model/RenameAction.java
  core/src/main/resources/hudson/model/AbstractItem/confirm-rename.jelly
  core/src/main/resources/hudson/model/AbstractItem/confirm-rename.properties
  core/src/main/resources/hudson/model/Job/configure.jelly
  core/src/main/resources/hudson/model/Job/rename.properties
  core/src/main/resources/hudson/model/Job/rename_bg.properties
  core/src/main/resources/hudson/model/Job/rename_da.properties
  core/src/main/resources/hudson/model/Job/rename_de.properties
  core/src/main/resources/hudson/model/Job/rename_es.properties
  core/src/main/resources/hudson/model/Job/rename_fr.properties
  core/src/main/resources/hudson/model/Job/rename_it.properties
  core/src/main/resources/hudson/model/Job/rename_ja.properties
  core/src/main/resources/hudson/model/Job/rename_pt_BR.properties
  core/src/main/resources/hudson/model/Job/rename_ru.properties
  core/src/main/resources/hudson/model/Job/rename_sr.properties
  core/src/main/resources/hudson/model/Job/rename_sv_SE.properties
  core/src/main/resources/hudson/model/Job/rename_zh_TW.properties
  core/src/main/resources/hudson/model/Messages.properties
  core/src/main/resources/hudson/model/Messages_bg.properties
  core/src/main/resources/hudson/model/Messages_da.properties
  core/src/main/resources/hudson/model/Messages_de.properties
  core/src/main/resources/hudson/model/Messages_es.properties
  core/src/main/resources/hudson/model/Messages_it.properties
  core/src/main/resources/hudson/model/Messages_ja.properties
  core/src/main/resources/hudson/model/Messages_pt_BR.properties
  core/src/main/resources/hudson/model/Messages_ru.properties
  core/src/main/resources/hudson/model/Messages_sr.properties
  core/src/main/resources/hudson/model/Messages_zh_CN.properties
  core/src/main/resources/hudson/model/Messages_zh_TW.properties
  core/src/main/resources/jenkins/model/RenameAction/action.jelly
  test/src/test/java/hudson/model/AbstractItemTest.java
  test/src/test/java/hudson/model/JobTest.java
Labels: needs-review

#2926 [JENKINS-43581] - Create new custom tool button should be on top
  core/src/main/resources/hudson/tools/ToolInstallation/global.jelly
  core/src/main/resources/lib/form/repeatable.jelly
  core/src/main/resources/lib/form/repeatable/repeatable.js
  core/src/main/resources/lib/form/repeatableProperty.jelly
  test/src/test/java/lib/form/RepeatableTest.java
  test/src/test/resources/lib/form/RepeatableTest/testNestedRadioTopButton.jelly
  test/src/test/resources/lib/form/RepeatableTest/testNestedTopButton.jelly
  test/src/test/resources/lib/form/RepeatableTest/testNestedTopButtonInner.jelly
  test/src/test/resources/lib/form/RepeatableTest/testNestedTopButtonOuter.jelly
  test/src/test/resources/lib/form/RepeatableTest/testSimpleWithDeleteButton.jelly
  test/src/test/resources/lib/form/RepeatableTest/testSimpleWithDeleteButtonTopButton.jelly
Labels: ready-for-merge

#3094 [JENKINS-29470] - Prevent NPE in AbstractProject.checkout when agent disconnects during the build
  core/src/main/java/hudson/model/AbstractProject.java
Labels: needs-fix

#3316 [JENKINS-49642] Fix proxy view recursion
  core/src/main/java/hudson/model/ProxyView.java
Labels: ready-for-merge

#3325 Fixing serialization of InstallState
  core/src/main/java/jenkins/install/InstallState.java
  core/src/main/java/jenkins/security/ClassFilterImpl.java
Labels: ready-for-merge

#3317 [JENKINS-32599] Ignore misplaced users/config.xml file
  core/src/main/java/hudson/model/User.java
Labels: ready-for-merge

#3332 s/JENKINS-49573/JENKINS-49795/g in messages
  core/src/main/java/jenkins/security/ClassFilterImpl.java
Labels: ready-for-merge

#3211 Refactor TextFile.lines()
  core/src/main/java/hudson/util/TextFile.java
  core/src/main/java/jenkins/security/s2m/ConfigFile.java
  core/src/main/java/jenkins/util/io/LinesStream.java
Labels: ready-for-merge

#3116 [JENKINS-45387] Fix validation error displaying in setup wizard's "create first admin" form
  core/src/main/java/hudson/security/AccountCreationFailedException.java
  core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java
  core/src/main/java/jenkins/install/SetupWizard.java
  war/src/main/js/pluginSetupWizardGui.js
  war/src/main/js/templates/firstUserPanel.hbs
Labels: hacktoberfest, ready-for-merge

#3225 [JENKINS-49971] Fix a race condition in Util.loadFile()
  core/src/main/java/hudson/Util.java
Labels: ready-for-merge

#3254 [JENKINS-46652] Check Computer.BUILD permission only on heayweight tasks
  core/src/main/java/hudson/model/Node.java
  core/src/main/java/hudson/model/queue/MappingWorksheet.java
Labels: ready-for-merge

#3311 Choose more mnemonic artifactId’s for modules not consumed externally
  cli/pom.xml
  core/pom.xml
  pom.xml
  test/pom.xml
  war/pom.xml
Labels: ready-for-merge

#3228 [JENKINS-50056] - Do not copy all build numbers in case of descending search
  core/src/main/java/jenkins/model/lazy/AbstractLazyLoadRunMap.java
Labels: ready-for-merge

#3329 [JENKINS-48821] - Don't forget estimated duration of asynchronous jobs
  core/src/main/java/hudson/model/Executor.java
Labels: needs-review, ready-for-merge, regression

#3293 Allow disabling process killing on interruption
  core/src/main/java/hudson/Launcher.java
  core/src/main/java/hudson/Proc.java
Labels: ready-for-merge

#3326 [JENKINS-49906] Use more specific and less urgent message when renaming
  core/src/main/java/hudson/model/AbstractItem.java
  core/src/main/resources/hudson/model/Messages.properties
  test/src/test/java/hudson/model/AbstractItemTest.java
Labels: ready-for-merge

#3327 [JENKINS-39495] Defend against a null serialized ParametersAction.parameters
  core/src/main/java/hudson/model/ParametersAction.java
Labels: ready-for-merge

#3335 access-modifier.version=1.13
  cli/src/main/java/hudson/cli/CLI.java
  core/src/main/java/hudson/cli/DeleteBuildsCommand.java
  core/src/main/java/hudson/cli/HelpCommand.java
  core/src/main/java/hudson/cli/ListChangesCommand.java
  core/src/main/java/jenkins/model/NewViewLink.java
  core/src/main/java/jenkins/security/CustomClassFilter.java
  core/src/main/java/jenkins/security/s2m/DefaultFilePathFilter.java
  core/src/main/java/jenkins/tasks/SimpleBuildStep.java
  pom.xml
Labels: needs-review

#3336 [JENKINS-49737 ] - Update Extras Executable WAR to 1.38
  war/pom.xml
Labels: ready-for-merge

#3342 [JENKINS-49968] Revert "Merge pull request #3277 from uhafner/prototype-1.7.3"
  war/src/main/webapp/scripts/prototype.js
Labels: regression

#3346 [JENKINS-50124] restore AbstractTaskListeners serialVersionUID.
  core/src/main/java/hudson/util/AbstractTaskListener.java
Labels: ready-for-merge

#3333 [JENKINS-49994] Warn about Remoting serialization of anonymous inner classes
  cli/src/main/java/hudson/cli/Connection.java
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/console/AnnotatedLargeText.java
  core/src/main/java/hudson/console/ConsoleNote.java
  core/src/main/java/hudson/slaves/RetentionStrategy.java
  core/src/main/java/hudson/tasks/Fingerprinter.java
  core/src/main/java/hudson/util/ProcessTree.java
  core/src/main/java/jenkins/security/ClassFilterImpl.java
  core/src/main/java/jenkins/slaves/restarter/JnlpSlaveRestarterInstaller.java
  pom.xml
  test/src/test/java/jenkins/security/Security232Test.java
Labels: ready-for-merge

#3337 [JENKINS-38812] - Support insensitive autocompletion for item selection
  core/src/main/java/hudson/model/AutoCompletionCandidates.java
Labels: needs-review

#3309 Fix form action target for rekey monitor
  core/src/main/resources/jenkins/security/RekeySecretAdminMonitor/message.groovy
Labels: ready-for-merge

#3345 Add parent loggers to autocompletion
  core/src/main/java/hudson/logging/LogRecorder.java
  core/src/test/java/hudson/logging/LogRecorderTest.java
Labels: needs-review, ready-for-merge

#3338 Cleanup FindBugs in CLI + some refactoring
  cli/pom.xml
  cli/src/main/java/hudson/cli/SSHCLI.java
  core/pom.xml
  pom.xml
Labels: needs-review

#3014 [JENKINS-26143] Make choice parameter work with choices list in pipeline
  core/src/main/java/hudson/model/ChoiceParameterDefinition.java
Labels: needs-review

#3359 [JENKINS-50237/JENKINS-49618] Pick up Remoting 3.19 with automatic ProxyException; and avoid BuildException to begin with
  core/src/main/java/hudson/FilePath.java
  core/src/main/resources/jenkins/security/whitelisted-classes.txt
  pom.xml
  test/src/test/java/hudson/FilePathTest.java
  test/src/test/java/jenkins/security/s2m/DefaultFilePathFilterTest.java
Labels: needs-review, regression

#3362 [JENKINS-46386] Make SystemProperties safe to call from agent JVMs
  core/src/main/java/jenkins/util/SystemProperties.java
  test/src/test/java/jenkins/util/SystemPropertiesTest.java
  war/src/main/webapp/WEB-INF/web.xml
Labels: ready-for-merge

#3324 [JENKINS-47020] - Improve job search experience
  core/src/main/java/hudson/search/Search.java
  core/src/main/resources/hudson/search/Search/search-failed.jelly
  war/src/main/webapp/css/style.css
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge

#3372 [JENKINS-50237] - Backport: Whitelist org.apache.tools.ant.Location for serialization
  core/src/main/resources/jenkins/security/whitelisted-classes.txt
Labels: needs-review, regression

#3367 [JENKINS-50291] Customize where Async[A]PeriodicWork tasks are logged
  core/src/main/java/hudson/model/AsyncAperiodicWork.java
  core/src/main/java/hudson/model/AsyncPeriodicWork.java
  core/src/main/java/hudson/triggers/SafeTimerTask.java
  test/src/test/java/hudson/triggers/SafeTimerTaskTest.java
Labels: ready-for-merge

#2567 Minimize readResolve visibility
  core/src/main/java/hudson/ProxyConfiguration.java
  core/src/main/java/hudson/model/MyViewsProperty.java
  core/src/main/java/hudson/scm/NullChangeLogParser.java
  core/src/main/java/hudson/tasks/ArtifactArchiver.java
  core/src/main/java/jenkins/install/InstallState.java
  test/src/test/java/hudson/model/RunMapTest.java
  test/src/test/java/hudson/triggers/TriggerTest.java
  test/src/test/java/hudson/util/RobustReflectionConverterTest.java
Labels: ready-for-merge

#1111 [JENKINS-21613] f:combobox may break form.onsubmit
  war/src/main/webapp/scripts/combobox.js
Labels: ready-for-merge
