Repository jenkinsci/jenkins, pull requests merged in 2018-12, with the labels that each got.

#3792 Add missing tilde
  core/src/main/resources/jenkins/model/Jenkins/fingerprintCheck_pt_BR.properties
Labels: ready-for-merge

#3783 Bump to latest 1.50 parent pom release
  pom.xml
Labels: ready-for-merge

#3727 [JENKINS-52869] Show error messages on user creation
  core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/_entryForm.jelly
Labels: needs-review, regression

#3795 [JENKINS-55081] SEC-904 related test failing on java 11
  core/src/main/java/hudson/FilePath.java
  core/src/test/java/hudson/FilePathSEC904Test.java
Labels: java11, ready-for-merge

#3796 Improve test assertion
  test/src/test/java/hudson/tasks/MavenTest.java
Labels: ready-for-merge

#3721 [JENKINS-54325] Add support for multiple footers in SimplePageDecorator
  core/src/main/java/hudson/Functions.java
  core/src/main/java/jenkins/model/SimplePageDecorator.java
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/signup.jelly
  core/src/main/resources/jenkins/model/Jenkins/login.jelly
  core/src/test/java/hudson/UtilTest.java
Labels: ready-for-merge

#3800 Upgrade to 3.28 version of Remoting.
  pom.xml
Labels: ready-for-merge

#3804 Fixing tests which attempted to restart the Surefire booter JVM
  Jenkinsfile
  core/src/main/java/hudson/TcpSlaveAgentListener.java
  core/src/main/java/jenkins/model/Jenkins.java
  test/src/test/java/hudson/cli/DisablePluginCommandTest.java
  test/src/test/java/hudson/cli/EnablePluginCommandTest.java
  test/src/test/java/jenkins/model/JenkinsBuildsAndWorkspacesDirectoriesTest.java
Labels: ready-for-merge

#3801 Update triggerRemotely documentation
  war/src/main/webapp/help/project-config/triggerRemotely.html
Labels: ready-for-merge

#3780 [JENKINS-54933] Replace ZeroClipboard (Flash) with native JavaScript implementation
  core/src/main/resources/lib/layout/copyButton/clipboard.png
  core/src/main/resources/lib/layout/copyButton/copyButton.css
  core/src/main/resources/lib/layout/copyButton/copyButton.js
Labels: ready-for-merge

#3776 Bump ATH version to one that support Selenium 3
  essentials.yml
Labels: java11
