Repository jenkinsci/jenkins, pull requests merged in 2018-02, with the labels that each got.

#3278 Updated SSHD Module to 2.4 to bundle SSHD Core 1.7.0
  war/pom.xml
Labels: on-hold, ready-for-merge

#3286 [JENKINS-49498]: Fix poorly translated sign-up string (dutch)
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/config_nl.properties
Labels: ready-for-merge

#3290 [JENKINS-49543] - Add direct unit test for module class whitelisting
  core/src/main/java/jenkins/security/ClassFilterImpl.java
  test/src/test/java/jenkins/security/ClassFilterImplTest.java
Labels: ready-for-merge

#3265 [JENKINS-47142] Simplifying the logic of ArtifactArchiver.perform, making it friendlier to Pipeline
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/tasks/ArtifactArchiver.java
  core/src/main/resources/hudson/tasks/Messages.properties
  core/src/main/resources/hudson/tasks/Messages_bg.properties
  core/src/main/resources/hudson/tasks/Messages_da.properties
  core/src/main/resources/hudson/tasks/Messages_de.properties
  core/src/main/resources/hudson/tasks/Messages_es.properties
  core/src/main/resources/hudson/tasks/Messages_fr.properties
  core/src/main/resources/hudson/tasks/Messages_it.properties
  core/src/main/resources/hudson/tasks/Messages_ja.properties
  core/src/main/resources/hudson/tasks/Messages_nl.properties
  core/src/main/resources/hudson/tasks/Messages_pt_BR.properties
  core/src/main/resources/hudson/tasks/Messages_ru.properties
  core/src/main/resources/hudson/tasks/Messages_sr.properties
  core/src/main/resources/hudson/tasks/Messages_tr.properties
  core/src/main/resources/hudson/tasks/Messages_zh_TW.properties
Labels: ready-for-merge

#3246 [JENKINS-49044] Apply visibility filters to SecurityRealm and AuthorizationStrategy
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/index.groovy
  test/src/test/java/hudson/model/DescriptorVisibilityFilterTest.java
Labels: needs-review

#3296 [JENKINS-49565] - Update Jenkins CLI to Mina SSHD Core 1.7.0
  cli/pom.xml
Labels: ready-for-merge

#3292 [JENKINS-49387][JENKINS-49520] - Validation errors
  core/src/main/java/hudson/model/Computer.java
  core/src/main/resources/hudson/slaves/DumbSlave/configure-entries.jelly
  core/src/main/resources/jenkins/model/Jenkins/MasterComputer/configure.jelly
  core/src/main/resources/jenkins/model/MasterBuildConfiguration/config.groovy
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, regression

#3297 JenkinsFile: Use performance-optimized build mode to reduce IO a bit when Jenkins builds itself
  Jenkinsfile
Labels: needs-review

#3304 [JENKINS-49661] use "agent" for Symbol
  core/src/main/java/hudson/slaves/DumbSlave.java
Labels: ready-for-merge

#3244 [FIX JENKINS-30909] Make sure queue is persisted reliably
  core/src/main/java/hudson/model/Queue.java
  test/pom.xml
  test/src/test/java/hudson/model/QueueRestartTest.java
  test/src/test/java/hudson/model/QueueTest.java
  test/src/test/resources/hudson/model/QueueTest/load_queue_xml/config.xml
  test/src/test/resources/hudson/model/QueueTest/load_queue_xml/jobs/a/config.xml
  test/src/test/resources/hudson/model/QueueTest/load_queue_xml/jobs/b/config.xml
  test/src/test/resources/hudson/model/QueueTest/load_queue_xml/jobs/c/config.xml
  test/src/test/resources/hudson/model/QueueTest/load_queue_xml/jobs/d/config.xml
  test/src/test/resources/hudson/model/QueueTest/load_queue_xml/jobs/e/config.xml
  test/src/test/resources/hudson/model/QueueTest/load_queue_xml/jobs/f/config.xml
  test/src/test/resources/hudson/model/QueueTest/load_queue_xml/jobs/g/config.xml
  test/src/test/resources/hudson/model/QueueTest/load_queue_xml/jobs/h/config.xml
  test/src/test/resources/hudson/model/QueueTest/load_queue_xml/jobs/i/config.xml
  test/src/test/resources/hudson/model/QueueTest/load_queue_xml/jobs/j/config.xml
  test/src/test/resources/hudson/model/QueueTest/load_queue_xml/jobs/k/config.xml
  test/src/test/resources/hudson/model/QueueTest/load_queue_xml/queue.xml
Labels: needs-review

#3303 [JENKINS-49634] Wrong escaping of quotes in the Setup Wizard
  core/src/main/resources/jenkins/install/pluginSetupWizard.properties
  core/src/main/resources/jenkins/install/pluginSetupWizard_it.properties
Labels: ready-for-merge

#3281 Fixing nullability annotations on Util.escape
  core/src/main/java/hudson/Util.java
Labels: ready-for-merge

#3125 Improve sortable.js to work with BFA table
  war/src/main/webapp/scripts/sortable.js
Labels: ready-for-merge

#3238 [JENKINS-48467] - Updated UserIdCause.print() to use ModelHyperlinkNote
  core/src/main/java/hudson/model/Cause.java
  test/src/test/java/hudson/model/CauseTest.java
Labels: ready-for-merge

#2768 Add tests for REST API authenticated by token in parameter
  test/src/test/java/jenkins/security/ApiTokenPropertyTest.java
Labels: ready-for-merge

#3310 TextFileTest.tail failed on Windows when using a source checkout with Unix newlines
  core/src/test/java/hudson/util/TextFileTest.java
Labels: needs-review

#3313 [JENKINS-49543] Old versions of Tomcat also failed to serialize classes from Jenkins modules
  core/src/main/java/jenkins/security/ClassFilterImpl.java
Labels: ready-for-merge

#3288 fix missing parameter in french translation of test:bar taglib
  core/src/main/resources/lib/test/bar_fr.properties
Labels: ready-for-merge

#3315 [JENKINS-49788] - Added ConcurrentLinkedQueue to whitelisted classes.
  core/src/main/resources/jenkins/security/whitelisted-classes.txt
Labels: ready-for-merge
