Repository jenkinsci/jenkins, pull requests merged in 2019-08, with the labels that each got.

#4125 Update versions of some detached plugins that installed in some cases when upgrading Jenkins or when implied dependencies are not specified for manually managed plugins.
  pom.xml
  test-pom/pom.xml
  test/src/test/java/hudson/model/FingerprintTest.java
  test/src/test/java/hudson/model/SlaveTest.java
  war/pom.xml
Labels: ready-for-merge

#4133 [JENKINS-58548] Remove extra whitespace from scriptText
  core/src/main/resources/jenkins/model/Jenkins/_scriptText.jelly
  core/src/main/resources/lib/layout/view.jelly
  test/src/test/java/jenkins/model/JenkinsTest.java
Labels: ready-for-merge

#4137 [JENKINS-58733] Avoid a file handle leak in PeepholePermalink
  core/src/main/java/jenkins/model/PeepholePermalink.java
Labels: ready-for-merge

#4135 Support JMH benchmarks from Jenkins Test Harness
  test-pom/pom.xml
  test/.gitignore
  test/src/test/java/benchmarks/BenchmarkTest.java
  test/src/test/java/benchmarks/SampleBenchmark.java
  test/src/test/java/hudson/CustomPluginManagerTest.java
  test/src/test/java/hudson/ExtensionFinderTest.java
  test/src/test/java/hudson/util/BootFailureTest.java
Labels: internal, ready-for-merge

#4142 Test shouldn't be interactively breaking
  test/src/test/java/jenkins/triggers/TriggerTest.java
Labels: ready-for-merge

#4148 [JENKINS-58595] Add missing ${h} in rss and atom views
  core/src/main/resources/hudson/atom.jelly
  core/src/main/resources/hudson/rss20.jelly
Labels: ready-for-merge, regression-fix

#4141 Updating LICENSE section of readme.md
  README.md
Labels: internal, ready-for-merge

#4153 Disable Windows builds, ATH and Incrementals to mitigate the ongoing INFRA issue
  Jenkinsfile
Labels: skip-changelog

#4144 [JENKINS-58836] Wrong spanish argentinian translation for 'logout'
  core/src/main/resources/lib/layout/layout_es_AR.properties
Labels: ready-for-merge

#4122 [JENKINS-58571] Check if name is editable on item before doing rename.
  core/src/main/java/hudson/model/AbstractItem.java
  core/src/test/java/hudson/model/AbstractItemTest.java
  test-pom/pom.xml
Labels: ready-for-merge

#4147 [JENKINS-58892] - Remove build-pipeline-plugin from setup wizard
  core/src/main/resources/jenkins/install/platform-plugins.json
Labels: ready-for-merge

#4132 Replace Charset.forName with StandardCharsets
  core/src/main/java/hudson/TcpSlaveAgentListener.java
  core/src/main/java/hudson/security/csrf/DefaultCrumbIssuer.java
  core/src/main/java/hudson/util/HttpResponses.java
  core/src/main/java/hudson/util/WriterOutputStream.java
  core/src/main/java/hudson/util/XStream2.java
  core/src/test/java/hudson/util/AtomicFileWriterTest.java
  test/src/test/java/hudson/model/UsageStatisticsTest.java
Labels: internal, ready-for-merge

#4116 Correct package name
  core/src/main/java/hudson/os/WindowsUtil.java
Labels: skip-changelog

#4136 [JENKINS-58736] Correction of /assets throwing 500
  core/src/main/java/jenkins/model/AssetManager.java
  test/src/test/java/jenkins/model/AssetManagerTest.java
Labels: ready-for-merge

#4143 Clean up formatting
  core/src/main/java/hudson/model/User.java
Labels: skip-changelog

#4151 doQuietDown() cannot actually throw IOException
  core/src/main/java/jenkins/model/Jenkins.java
Labels: ready-for-merge

#4121 [JENKINS-58157] Fixing 'delete build' button too long
  core/src/main/resources/lib/layout/breadcrumbs.css
  war/src/main/webapp/css/layout-common.css
  war/src/main/webapp/css/responsive-grid.css
  war/src/main/webapp/css/style.css
Labels: ready-for-merge, web-ui

#4134 [JENKINS-58734] Use SHA-256 for crumbs
  core/src/main/java/hudson/security/csrf/DefaultCrumbIssuer.java
Labels: ready-for-merge

#4156 Release drafter: Order changelog entries using categories
  .github/release-drafter.yml
Labels: internal

#3770 [JENKINS-54772] Fix reported list of environment variables from agent
  core/src/main/java/hudson/slaves/SlaveComputer.java
  core/src/main/resources/jenkins/slaves/systemInfo/EnvVarsSlaveInfo/systemInfo.jelly
Labels: bug, ready-for-merge

#4158 Release Drafter: RFE is used as a changelog filter for RFEs
  .github/release-drafter.yml
Labels: skip-changelog

#4157 README: Update the plugins number and link the plugins site
  README.md
Labels: skip-changelog

#4152 [JENKINS-23349] - Project names: Add support of characters which are not convertible to UTF-8 (emojis, surrogate pairs)
  core/src/main/java/hudson/Util.java
  core/src/test/java/hudson/UtilTest.java
Labels: major-rfe, ready-for-merge

#4160 Remove JNLP terminology from GUI when referring to inbound agents in German translations.
  core/src/main/resources/hudson/slaves/Messages_de.properties
  core/src/main/resources/jenkins/model/Jenkins/EnforceSlaveAgentPortAdministrativeMonitor/message_de.properties
Labels: localization, ready-for-merge

#4154 Update Mockito from 2.22.0 to 3.0.0
  pom.xml
Labels: internal, ready-for-merge, skip-changelog

#4131 JENKINS-36720: Fixed some spotbugs findings
  core/src/main/java/hudson/ExtensionComponent.java
  core/src/main/java/hudson/cli/SetBuildDescriptionCommand.java
  core/src/main/java/hudson/model/FileParameterValue.java
  core/src/main/java/hudson/model/HealthReport.java
  core/src/main/java/hudson/model/JDK.java
  core/src/main/java/hudson/security/HudsonAuthenticationEntryPoint.java
  core/src/test/java/hudson/model/TaskActionTest.java
Labels: internal, ready-for-merge

#4165 Upgrade to 3.34 version of Remoting.
  pom.xml
Labels: ready-for-merge

#4163 Remove useless conditions
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/model/StringParameterDefinition.java
  core/src/main/java/hudson/util/ArgumentListBuilder.java
  core/src/main/java/hudson/util/SecretRewriter.java
  core/src/main/java/jenkins/widgets/HistoryPageFilter.java
Labels: internal, ready-for-merge, skip-changelog

#4162 Fix invalid condition in toEmailSafeString
  core/src/main/java/hudson/Functions.java
Labels: bug, ready-for-merge

#4174 Deprecating useless Util.getPastTimeString
  core/src/main/java/hudson/Util.java
  core/src/main/java/hudson/model/Executor.java
  core/src/main/java/hudson/model/Fingerprint.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/node_monitors/AbstractNodeMonitorDescriptor.java
  core/src/main/resources/META-INF/upgrade/Util.hint
  core/src/main/resources/hudson/Messages.properties
  core/src/main/resources/hudson/Messages_bg.properties
  core/src/main/resources/hudson/Messages_da.properties
  core/src/main/resources/hudson/Messages_de.properties
  core/src/main/resources/hudson/Messages_es.properties
  core/src/main/resources/hudson/Messages_fr.properties
  core/src/main/resources/hudson/Messages_it.properties
  core/src/main/resources/hudson/Messages_ja.properties
  core/src/main/resources/hudson/Messages_nl.properties
  core/src/main/resources/hudson/Messages_pl.properties
  core/src/main/resources/hudson/Messages_pt.properties
  core/src/main/resources/hudson/Messages_pt_BR.properties
  core/src/main/resources/hudson/Messages_ru.properties
  core/src/main/resources/hudson/Messages_sr.properties
  core/src/main/resources/hudson/Messages_tr.properties
  core/src/main/resources/hudson/Messages_zh_TW.properties
Labels: ready-for-merge, skip-changelog

#4176 JENKINS-58912/JENKINS-58938: Fix Groovy compilation error that breaks the UI.
  core/src/main/resources/hudson/triggers/SlowTriggerAdminMonitor/message.groovy
Labels: ready-for-merge, regression-fix

#4175 minor grammar improvements
  core/src/main/java/hudson/slaves/RetentionStrategy.java
Labels: ready-for-merge, skip-changelog

#4168 Fix counter which is not updated in the loop
  core/src/main/java/hudson/model/AbstractProject.java
Labels: ready-for-merge, skip-changelog

#4181 [JENKINS-59123] - Make save.png transparent
  war/src/main/webapp/images/16x16/save.png
  war/src/main/webapp/images/24x24/save.png
Labels: ready-for-merge, rfe

#4179 [JENKINS-59123] make none.gif transparent
  war/src/main/webapp/images/none.gif
Labels: ready-for-merge, rfe

#4182 make monitor.gif transparent
  war/src/main/webapp/images/24x24/monitor.gif
  war/src/main/webapp/images/48x48/monitor.gif
Labels: ready-for-merge, rfe

#4173 Format the mess codes
  core/src/main/java/hudson/model/UpdateCenter.java
Labels: ready-for-merge, skip-changelog

#4186 [JENKINS-59094] - Revert "Upgrade to 3.34 version of Remoting."
  pom.xml
Labels: regression-fix
