Repository jenkinsci/jenkins, pull requests merged in 2019-10, with the labels that each got.

#4232 Fix NPE in ProcessTree#killAll if proc is null and add a test for it
  core/src/main/java/hudson/util/ProcessTree.java
  test/src/test/java/hudson/util/ProcessTreeKillerTest.java
Labels: bug, internal, ready-for-merge

#4235 Fix formatting of ProcessTreeKillerTest.java
  test/src/test/java/hudson/util/ProcessTreeKillerTest.java
Labels: internal, ready-for-merge, skip-changelog

#4238 Spotbugs: Replaced inefficient Number constructor with static valueOf
  core/src/main/java/hudson/tasks/BatchFile.java
  core/src/main/java/hudson/tasks/Shell.java
  core/src/main/java/hudson/widgets/HistoryWidget.java
Labels: internal, ready-for-merge, skip-changelog

#4237 Spotbugs: changed order for compare instead of negating result
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/model/RunMap.java
Labels: internal, ready-for-merge, skip-changelog

#4234 Fix ProcessTreeKillerTest#doNotKillProcessWithCookie to work on Windows
  test/src/test/java/hudson/util/ProcessTreeKillerTest.java
Labels: internal, ready-for-merge, skip-changelog

#4243 Use type inference instead of specifying it
  core/src/main/java/hudson/DependencyRunner.java
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/PluginFirstClassLoader.java
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/diagnosis/OldDataMonitor.java
  core/src/main/java/hudson/logging/LogRecorder.java
  core/src/main/java/hudson/model/AbstractCIBase.java
  core/src/main/java/hudson/model/AbstractItem.java
  core/src/main/java/hudson/model/AbstractProject.java
  core/src/main/java/hudson/model/DirectoryBrowserSupport.java
  core/src/main/java/hudson/model/Node.java
  core/src/main/java/hudson/model/Queue.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/scm/SCM.java
  core/src/main/java/hudson/search/Search.java
  core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java
  core/src/main/java/hudson/slaves/DelegatingComputerLauncher.java
  core/src/main/java/hudson/triggers/SCMTrigger.java
  core/src/main/java/hudson/util/ProcessTree.java
  core/src/main/java/hudson/util/spring/DefaultRuntimeSpringConfiguration.java
  core/src/main/java/jenkins/util/xstream/XStreamDOM.java
  core/src/test/java/hudson/EnvVarsTest.java
  core/src/test/java/hudson/FilePathTest.java
  core/src/test/java/hudson/UtilTest.java
  core/src/test/java/hudson/cli/ListJobsCommandTest.java
  core/src/test/java/hudson/model/ActionableTest.java
  core/src/test/java/hudson/model/ParametersActionTest.java
  core/src/test/java/hudson/model/ViewTest.java
  core/src/test/java/hudson/scheduler/CronTabDayOfWeekLocaleTest.java
  core/src/test/java/hudson/scheduler/CronTabEventualityTest.java
  core/src/test/java/hudson/scheduler/CronTabTest.java
  core/src/test/java/hudson/search/SearchTest.java
  core/src/test/java/hudson/slaves/ChannelPingerTest.java
  core/src/test/java/hudson/util/ArgumentListBuilderTest.java
  core/src/test/java/hudson/util/ConsistentHashTest.java
  core/src/test/java/hudson/util/CopyOnWriteMapTest.java
  core/src/test/java/hudson/util/CyclicGraphDetectorTest.java
  core/src/test/java/hudson/util/PackedMapTest.java
  core/src/test/java/hudson/util/RunListTest.java
  core/src/test/java/hudson/util/XStream2Test.java
  core/src/test/java/jenkins/model/lazy/AbstractLazyLoadRunMapTest.java
  core/src/test/java/jenkins/model/lazy/SortedListTest.java
  core/src/test/java/jenkins/security/ConfidentialStoreRule.java
  core/src/test/java/jenkins/util/xstream/XStreamDOMTest.java
Labels: internal, ready-for-merge, skip-changelog

#4231 [JENKINS-59580] Fix WindowsOSProcess.getEnvironmentVariables returning null
  core/src/main/java/hudson/util/ProcessTree.java
Labels: bug, ready-for-merge

#4244 Misc cleanups
  core/src/main/java/hudson/ClassicPluginStrategy.java
  core/src/main/java/hudson/Util.java
  core/src/main/java/hudson/model/BooleanParameterDefinition.java
  core/src/main/java/hudson/model/DirectoryBrowserSupport.java
  core/src/main/java/jenkins/model/Configuration.java
  core/src/main/java/jenkins/security/FrameOptionsPageDecorator.java
  core/src/main/java/jenkins/util/AntClassLoader.java
Labels: internal, ready-for-merge, skip-changelog

#4225 [JENKINS-59152] - Reduce the default process soft-kill timeout from 2 minutes to 5 seconds
  core/src/main/java/hudson/util/ProcessTree.java
Labels: ready-for-merge, rfe

#4245 Update script-security to 1.65
  war/pom.xml
Labels: ready-for-merge, rfe, upgrade-guide-needed

#4236 Annotate ProcessTree with @CheckForNull/@Nonnull
  core/src/main/java/hudson/util/ProcessTree.java
  core/src/main/java/hudson/util/ProcessTreeRemoting.java
Labels: internal, ready-for-merge, skip-changelog

#4247 Improved null handling in AbstractProject.<init>
  core/src/main/java/hudson/model/AbstractProject.java
  core/src/main/java/jenkins/model/Jenkins.java
Labels: internal, ready-for-merge

#4250 Note that CSRF crumbs aren't really needed anymore for API clients
  core/src/main/java/hudson/security/csrf/CrumbExclusion.java
Labels: internal, ready-for-merge, skip-changelog

#4265 English: an hpi file
  core/src/main/resources/hudson/PluginManager/advanced.properties
Labels: internal, ready-for-merge, skip-changelog

#4242 Unbundle Maven Plugin and Subversion Plugin
  pom.xml
  test-pom/pom.xml
  test/src/test/java/hudson/model/AbstractProjectTest.java
  war/pom.xml
Labels: ready-for-merge, rfe, upgrade-guide-needed

#4251 minor improvements to unit tests
  core/src/test/java/hudson/PluginManagerTest.java
  core/src/test/java/hudson/util/ConsistentHashTest.java
  core/src/test/java/jenkins/model/lazy/AbstractLazyLoadRunMapTest.java
  core/src/test/java/jenkins/plugins/DetachedPluginsUtilTest.java
Labels: hacktoberfest, internal, skip-changelog

#4268 Use more common MIT license URL
  pom.xml
Labels: internal, ready-for-merge, skip-changelog

#4263 [JENKINS-59267] Increase ping frequency to prevent timeouts, and make it configurable
  cli/src/main/java/hudson/cli/CLI.java
Labels: bug

#4266 fix javadoc punctuation for Initializer.after
  core/src/main/java/hudson/init/Initializer.java
Labels: internal, ready-for-merge, skip-changelog

#4261 IntelliJ/Java: Duplicate code -> SettingsPath.getSettings
  core/src/main/java/jenkins/mvn/FilePathGlobalSettingsProvider.java
  core/src/main/java/jenkins/mvn/FilePathSettingsProvider.java
  core/src/main/java/jenkins/mvn/SettingsPathHelper.java
Labels: internal, ready-for-merge, skip-changelog

#4257 IntelliJ/Java: Duplicate code -> PluginManager.logPluginWarnings
  core/src/main/java/hudson/PluginManager.java
Labels: internal, ready-for-merge

#4260 IntelliJ/Java: Duplicate code -> View.makeSearchIndex
  core/src/main/java/hudson/model/ListView.java
  core/src/main/java/hudson/model/View.java
Labels: ready-for-merge, skip-changelog

#4258 IntelliJ/Java: Duplicate code -> Computer.resolveForCLI
  core/src/main/java/hudson/cli/ConnectNodeCommand.java
  core/src/main/java/hudson/cli/OnlineNodeCommand.java
Labels: ready-for-merge, skip-changelog

#4248 [JENKINS-36720] - Fix SpotBugs warnings for "known as null" values
  core/src/main/java/hudson/model/DownloadService.java
  core/src/main/java/jenkins/util/SystemProperties.java
Labels: hacktoberfest, internal, ready-for-merge, skip-changelog

#4277 Update documented Maven requirement: 3.5.3 -> 3.5.4
  CONTRIBUTING.md
Labels: hacktoberfest, internal, ready-for-merge, skip-changelog

#4272 Mark TarOutputStream as restricted
  core/src/main/java/hudson/org/apache/tools/tar/TarInputStream.java
  core/src/main/java/hudson/org/apache/tools/tar/TarOutputStream.java
Labels: developer, ready-for-merge

#3970 Remove browser-based metadata download
  core/src/main/java/hudson/model/DownloadService.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/java/jenkins/DailyCheck.java
  core/src/main/java/jenkins/model/DownloadSettings.java
  core/src/main/java/jenkins/telemetry/impl/SecuritySystemProperties.java
  core/src/main/resources/hudson/PluginManager/check.jelly
  core/src/main/resources/hudson/model/DownloadService/footer.jelly
  core/src/main/resources/hudson/model/UpdateCenter/PageDecoratorImpl/footer.jelly
  core/src/main/resources/jenkins/model/DownloadSettings/Warning/message.jelly
  core/src/main/resources/jenkins/model/DownloadSettings/Warning/message.properties
  core/src/main/resources/jenkins/model/DownloadSettings/Warning/message_bg.properties
  core/src/main/resources/jenkins/model/DownloadSettings/Warning/message_de.properties
  core/src/main/resources/jenkins/model/DownloadSettings/Warning/message_it.properties
  core/src/main/resources/jenkins/model/DownloadSettings/Warning/message_lt.properties
  core/src/main/resources/jenkins/model/DownloadSettings/Warning/message_sr.properties
  core/src/main/resources/jenkins/model/DownloadSettings/config.groovy
  core/src/main/resources/jenkins/model/DownloadSettings/config_de.properties
  core/src/main/resources/jenkins/model/DownloadSettings/config_it.properties
  core/src/main/resources/jenkins/model/DownloadSettings/config_ja.properties
  core/src/main/resources/jenkins/model/DownloadSettings/config_sr.properties
  core/src/main/resources/jenkins/model/DownloadSettings/help-useBrowser.html
  core/src/main/resources/jenkins/model/DownloadSettings/help-useBrowser_bg.html
  core/src/main/resources/jenkins/model/DownloadSettings/help-useBrowser_de.html
  core/src/main/resources/jenkins/model/DownloadSettings/help-useBrowser_it.html
  core/src/main/resources/jenkins/model/DownloadSettings/help-useBrowser_ja.html
  core/src/main/resources/jenkins/model/Messages.properties
  core/src/main/resources/jenkins/model/Messages_bg.properties
  core/src/main/resources/jenkins/model/Messages_de.properties
  core/src/main/resources/jenkins/model/Messages_it.properties
  test/src/test/java/hudson/model/DownloadServiceTest.java
  test/src/test/resources/hudson/model/DownloadServiceTest/testPost.jelly
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, squash-merge-me, upgrade-guide-needed

#4283 Release Drafter: Split developer and internal changes
  .github/release-drafter.yml
Labels: hacktoberfest, skip-changelog

#4278 Add a new `Functions#urlEncode(String)` method for encoding URLs in Jelly views
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/search/Search.java
  core/src/main/resources/hudson/search/Search/search-failed.jelly
  core/src/main/resources/lib/hudson/project/upstream-downstream.jelly
Labels: developer, ready-for-merge

#4239 [JENKINS-41891] Resource domain support
  core/src/main/java/hudson/model/DirectoryBrowserSupport.java
  core/src/main/java/jenkins/model/JenkinsLocationConfiguration.java
  core/src/main/java/jenkins/security/ResourceDomainConfiguration.java
  core/src/main/java/jenkins/security/ResourceDomainFilter.java
  core/src/main/java/jenkins/security/ResourceDomainRecommendation.java
  core/src/main/java/jenkins/security/ResourceDomainRootAction.java
  core/src/main/resources/hudson/model/DirectoryBrowserSupport/plaindir.jelly
  core/src/main/resources/jenkins/security/Messages.properties
  core/src/main/resources/jenkins/security/ResourceDomainConfiguration/config.jelly
  core/src/main/resources/jenkins/security/ResourceDomainConfiguration/help-url.html
  core/src/main/resources/jenkins/security/ResourceDomainRecommendation/message.groovy
  core/src/main/resources/jenkins/security/ResourceDomainRecommendation/message.properties
  test/src/test/java/jenkins/security/ResourceDomainTest.java
Labels: major-rfe, ready-for-merge, squash-merge-me, upgrade-guide-needed

#4279 [JENKINS-34226] No "pressed" style for OK button on Create Item
  war/src/main/js/widgets/add/addform.less
Labels: bug, hacktoberfest, ready-for-merge, web-ui

#4267 Replaced static test classes with mocks
  core/src/test/java/hudson/slaves/NodeListTest.java
Labels: internal, ready-for-merge, skip-changelog

#4269 [JENKINS-48375] - Make Atom the default feed type in UI and the response application type (Former RSS feeds use Atom)
  core/src/main/resources/hudson/model/Job/rssHeader.jelly
  core/src/main/resources/hudson/model/View/sidepanel.jelly
  core/src/main/resources/hudson/widgets/HistoryWidget/index.jelly
  core/src/main/resources/lib/hudson/rssBar.jelly
Labels: bug, hacktoberfest, ready-for-merge

#4256 IntelliJ/Java: Duplicate code -> ChunkedInputStream.advanceChunk
  core/src/main/java/hudson/util/ChunkedInputStream.java
Labels: ready-for-merge, skip-changelog

#4285 [JENKINS-59605] Unify the JS validation behavior and the AJAX one
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: internal, ready-for-merge, skip-changelog

#4276 [JENKINS-59684] Support "alert-info" for admin monitor in popup
  war/src/main/webapp/css/style.css
Labels: ready-for-merge, rfe, web-ui

#4288 Resolve TODO using JenkinsRule#waitOnline
  test/src/test/java/hudson/bugs/JnlpAccessWithSecuredHudsonTest.java
Labels: internal, ready-for-merge, skip-changelog

#4297 Contributing guidelines: Skip SpotBugs instead of Findbugs for quick build
  CONTRIBUTING.md
Labels: hacktoberfest, ready-for-merge, skip-changelog

#4291 Add Polish translations
  core/src/main/resources/hudson/Messages_pl.properties
  core/src/main/resources/hudson/PluginManager/advanced_pl.properties
  core/src/main/resources/hudson/PluginManager/installed_pl.properties
  core/src/main/resources/hudson/model/Messages_pl.properties
  core/src/main/resources/hudson/model/Run/delete_pl.properties
  core/src/main/resources/hudson/model/Run/logKeep_pl.properties
  core/src/main/resources/hudson/scm/Messages_pl.properties
  core/src/main/resources/jenkins/model/Jenkins/legend_pl.properties
  core/src/main/resources/lib/hudson/queue_pl.properties
Labels: localization, ready-for-merge

#4287 Modernize LoginRedirectTest
  test/src/test/java/hudson/bugs/LoginRedirectTest.java
Labels: internal, ready-for-merge, skip-changelog

#4249 [JENKINS-36720] - Fix SpotBugs warnings for "Non-null field is not initialized" values
  core/src/main/java/hudson/Launcher.java
  core/src/main/java/jenkins/security/NonSerializableSecurityContext.java
Labels: hacktoberfest, ready-for-merge

#4295 [JENKINS-59800] - Add line-height CSS property to fix the "Create Administrator Account" view headlines
  core/src/main/resources/jenkins/install/SetupWizard/setupWizardFirstUser.jelly
Labels: bug, hacktoberfest, ready-for-merge, web-ui

#4296 Contributing guidelines: Update the Java versions documentation
  CONTRIBUTING.md
Labels: hacktoberfest, ready-for-merge, skip-changelog

#4302 [JENKINS-59849] Don't fail to serve resource files with nontrivial names
  core/src/main/java/jenkins/security/ResourceDomainRootAction.java
  test/src/test/java/jenkins/security/ResourceDomainTest.java
Labels: bug

#4292 Update at-since in Javadoc, make script work on Mac OS X
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/PluginWrapper.java
  core/src/main/java/hudson/TcpSlaveAgentListener.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/java/hudson/model/View.java
  core/src/main/java/hudson/model/ViewGroup.java
  core/src/main/java/hudson/os/WindowsUtil.java
  core/src/main/java/jenkins/model/JenkinsLocationConfiguration.java
  core/src/main/java/jenkins/plugins/DetachedPluginsUtil.java
  core/src/main/java/jenkins/security/ResourceDomainConfiguration.java
  core/src/main/java/jenkins/security/ResourceDomainFilter.java
  core/src/main/java/jenkins/security/ResourceDomainRecommendation.java
  core/src/main/java/jenkins/security/ResourceDomainRootAction.java
  core/src/main/java/jenkins/security/SecurityListener.java
  core/src/main/java/jenkins/security/stapler/StaplerDispatchValidator.java
  update-since-todo.sh
Labels: internal, skip-changelog

#4259 Introduce new Run#getBuildsOverThreshold() method for getting runs above the desired execution result
  core/src/main/java/hudson/model/Job.java
  core/src/main/java/hudson/model/Run.java
Labels: developer, plugin-api-changes, ready-for-merge

#4253 Replace ACL.impersonate with ACL.as
  core/src/main/java/hudson/DependencyRunner.java
  core/src/main/java/hudson/diagnosis/OldDataMonitor.java
  core/src/main/java/hudson/model/AsyncAperiodicWork.java
  core/src/main/java/hudson/model/AsyncPeriodicWork.java
  core/src/main/java/hudson/model/DependencyGraph.java
  core/src/main/java/hudson/model/Executor.java
  core/src/main/java/hudson/model/Label.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/slaves/SlaveComputer.java
  core/src/main/java/hudson/triggers/SafeTimerTask.java
  core/src/main/java/jenkins/management/AsynchronousAdministrativeMonitor.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/security/BasicHeaderProcessor.java
  core/src/main/java/jenkins/triggers/ReverseBuildTrigger.java
Labels: internal, ready-for-merge, skip-changelog

#4300 Add java.util.concurrent.ConcurrentLinkedDeque to the class deserialization whitelist (JEP-200)
  core/src/main/resources/jenkins/security/whitelisted-classes.txt
Labels: ready-for-merge, rfe

#4303 Use actual logger to record Jenkins home and where it was found
  core/src/main/java/hudson/WebAppMain.java
Labels: ready-for-merge, rfe, skip-changelog

#4246 [JENKINS-58296] Revert "[JENKINS-53462] Submit form on Firefox as well"
  war/src/main/webapp/scripts/yui/button/button-debug.js
  war/src/main/webapp/scripts/yui/button/button-min.js
Labels: major-bug, ready-for-merge

#4155 Revert "Disable Windows builds and ATH to mitigate the ongoing INFRA issue"
  Jenkinsfile
  test/src/test/java/benchmarks/BenchmarkTest.java
Labels: ready-for-merge, skip-changelog

#4313 [JENKINS-58625] Cancel older builds of a given branch
  Jenkinsfile
Labels: internal, ready-for-merge, skip-changelog

#3894 Add telemetry for 'auto refresh' feature
  core/src/main/java/hudson/Functions.java
  core/src/main/java/jenkins/telemetry/Telemetry.java
  core/src/main/java/jenkins/telemetry/impl/AutoRefresh.java
  core/src/main/resources/jenkins/telemetry/impl/AutoRefresh/description.jelly
  core/src/main/resources/jenkins/telemetry/impl/Messages.properties
Labels: plugin-api-changes, squash-merge-me

#4316 Revert "Revert "Disable Windows builds and ATH to mitigate the ongoing INFRA issue""
  Jenkinsfile
  test/src/test/java/benchmarks/BenchmarkTest.java
Labels: skip-changelog

#4315 [JENKINS-59904] avoid NullPointerException when there are no cookies in the request
  core/src/main/java/hudson/security/SecurityRealm.java
Labels: bug, ready-for-merge

#4312 JENKINS-17459: Clicking red/yellow/green icons link to the build Console
  core/src/main/resources/hudson/model/Job/buildTimeTrend.jelly
Labels: hacktoberfest, ready-for-merge, rfe, web-ui

#4333 Update link to CLA information in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: ready-for-merge, skip-changelog

#4307 [JENKINS-59859] Make resource root URL tokens work with user names containing :
  core/src/main/java/jenkins/security/ResourceDomainRootAction.java
  test/src/test/java/jenkins/security/ResourceDomainTest.java
Labels: bug, ready-for-merge

#4299 Update the Plugin Manager Updates View with more Info about incompatible dependencies and change CSS classes
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/resources/hudson/PluginManager/_table.css
  core/src/main/resources/hudson/PluginManager/table.jelly
  core/src/main/resources/hudson/PluginManager/table.properties
  core/src/main/resources/hudson/PluginManager/table_de.properties
  war/src/main/webapp/css/style.css
Labels: hacktoberfest, needs-more-reviews, ready-for-merge, rfe, web-ui

#4113 [JENKINS-19887] - Allow time zone to be set on a per user basis
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/model/TimeZoneProperty.java
  core/src/main/resources/hudson/model/Messages.properties
  core/src/main/resources/hudson/model/TimeZoneProperty/config.jelly
  core/src/main/resources/hudson/model/TimeZoneProperty/config.properties
  core/src/main/resources/hudson/widgets/HistoryWidget/entry.jelly
  core/src/main/resources/lib/layout/layout.jelly
  test/src/test/java/hudson/model/TimeZonePropertyTest.java
Labels: major-rfe, ready-for-merge, squash-merge-me, web-ui
