Repository jenkinsci/jenkins, pull requests merged in 2019-02, with the labels that each got.

#3790 [JENKINS-55049] Avoid NumberFormatException when a symlink is used as…
  core/src/main/java/hudson/model/Run.java
  test/src/test/java/hudson/tasks/ArtifactArchiverTest.java
Labels: ready-for-merge

#3112 [JENKINS-47530] Add null check to RunParameterDefinition#getProject()…
  core/src/main/java/hudson/model/RunParameterDefinition.java
  core/src/main/java/jenkins/model/Jenkins.java
  test/src/test/java/hudson/model/RunParameterDefinitionTest.java
Labels: ready-for-merge

#3875 Test cases for JENKINS-22566
  test/src/test/java/hudson/model/ApiTest.java
Labels: ready-for-merge

#3869 JENKINS-53077 - don't process empty responseText
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, web-ui

#3865 [JENKINS-55681] - Make JAXB a detached plugin only on Java 11
  core/pom.xml
  core/src/main/java/hudson/ClassicPluginStrategy.java
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/java/jenkins/plugins/DetachedPluginsUtil.java
  core/src/main/resources/jenkins/split-plugin-cycles.txt
  core/src/main/resources/jenkins/split-plugins.txt
  core/src/test/java/hudson/ClassicPluginStrategyTest.java
  core/src/test/java/jenkins/plugins/DetachedPluginsUtilTest.java
  test/src/test/java/jenkins/install/LoadDetachedPluginsTest.java
  war/pom.xml
Labels: java11, ready-for-merge

#3877 Fix stray text in radioBlock st:documentation
  core/src/main/resources/lib/form/radioBlock.jelly
Labels: ready-for-merge

#3879 [JENKINS-55936] suppress exception for nonexistent adminwhitelist rul…
  core/src/main/resources/jenkins/security/s2m/AdminWhitelistRule/index.jelly
Labels: ready-for-merge

#3884 [JENKINS-55978] - Update SSHD Module to 2.6 to pick up the Apache MINA idle timeout custom property fix
  war/pom.xml
Labels: ready-for-merge

#3882 [JENKINS-52285] - Update to Extras Executable WAR, permit running with Java 11 without feature flags
  war/pom.xml
Labels: java11

#3881 [JENKINS-55085] - Use the main update center by default when running with Java 11
  core/src/main/java/hudson/model/UpdateCenter.java
Labels: java11, ready-for-merge

#3887 [JENKINS-55976] Upgrade to 3.29 version of Remoting.
  pom.xml
Labels: ready-for-merge

#3618 [JENKINS-53511] Improve discovery and readability of WebClient
  pom.xml
  test-pom/pom.xml
  test/src/test/java/hudson/AboutJenkinsTest.java
  test/src/test/java/hudson/TcpSlaveAgentListenerTest.java
  test/src/test/java/hudson/cli/CLITest.java
  test/src/test/java/hudson/diagnosis/HudsonHomeDiskUsageMonitorTest.java
  test/src/test/java/hudson/jobs/CreateItemTest.java
  test/src/test/java/hudson/model/AbstractItemTest.java
  test/src/test/java/hudson/model/AbstractProjectTest.java
  test/src/test/java/hudson/model/ApiTest.java
  test/src/test/java/hudson/model/AsynchPeopleTest.java
  test/src/test/java/hudson/model/ComputerTest.java
  test/src/test/java/hudson/model/DirectlyModifiableViewTest.java
  test/src/test/java/hudson/model/DirectoryBrowserSupportTest.java
  test/src/test/java/hudson/model/HudsonTest.java
  test/src/test/java/hudson/model/ItemsTest.java
  test/src/test/java/hudson/model/JobTest.java
  test/src/test/java/hudson/model/NodeTest.java
  test/src/test/java/hudson/model/ParametersTest.java
  test/src/test/java/hudson/model/PasswordParameterDefinitionTest.java
  test/src/test/java/hudson/model/ProjectTest.java
  test/src/test/java/hudson/model/QueueSEC891Test.java
  test/src/test/java/hudson/model/UserRestartSEC897Test.java
  test/src/test/java/hudson/model/ViewTest.java
  test/src/test/java/hudson/search/SearchTest.java
  test/src/test/java/hudson/security/csrf/DefaultCrumbIssuerTest.java
  test/src/test/java/hudson/tools/ZipExtractionInstallerTest.java
  test/src/test/java/hudson/util/RobustReflectionConverterTest.java
  test/src/test/java/jenkins/bugs/Jenkins19124Test.java
  test/src/test/java/jenkins/model/JenkinsTest.java
  test/src/test/java/jenkins/security/ApiTokenPropertyTest.java
  test/src/test/java/jenkins/security/RekeySecretAdminMonitorTest.java
  test/src/test/java/jenkins/security/Security177Test.java
  test/src/test/java/jenkins/security/apitoken/ApiTokenStatsTest.java
  test/src/test/java/jenkins/security/stapler/Security914Test.java
  test/src/test/java/lib/form/ExpandableTextboxTest.java
  test/src/test/java/lib/form/PasswordTest.java
  test/src/test/java/lib/form/ValidateButtonTest.java
  test/src/test/java/lib/layout/ConfirmationLinkTest.java
  test/src/test/java/lib/layout/StopButtonTest.java
Labels: ready-for-merge

#3861 [JENKINS-55050] Reduce performance impact of SEC-904 (esp. zip)
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/model/DirectoryBrowserSupport.java
  core/src/main/java/hudson/util/DirScanner.java
  core/src/main/java/jenkins/util/VirtualFile.java
  core/src/test/java/hudson/FilePathSEC904Test.java
  core/src/test/java/jenkins/util/VirtualFileSEC904Test.java
Labels: ready-for-merge

#3885 [JENKINS-55980] - Switch Java Specification Version comparison in the core to a robust implementation.
  core/pom.xml
  core/src/main/java/hudson/PluginWrapper.java
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/java/jenkins/plugins/DetachedPluginsUtil.java
  core/src/main/java/jenkins/util/java/JavaUtils.java
Labels: java11, ready-for-merge

#3876 [JENKINS-43780] Remove references to Trilead classes
  core/src/main/java/hudson/console/AnnotatedLargeText.java
  core/src/main/java/hudson/model/UsageStatistics.java
  core/src/main/java/hudson/util/ConsistentHash.java
  core/src/main/java/hudson/util/FormFieldValidator.java
  core/src/main/java/hudson/util/FormValidation.java
  core/src/main/java/hudson/util/HistoricalSecrets.java
  core/src/main/java/hudson/util/Protector.java
  core/src/main/java/hudson/util/Scrambler.java
  core/src/main/java/hudson/util/Secret.java
  core/src/main/java/hudson/util/SecretRewriter.java
  core/src/main/java/jenkins/util/JSONSignatureValidator.java
  core/src/test/java/hudson/util/SecretRewriterTest.java
  core/src/test/java/hudson/util/SecretTest.java
  test/src/test/java/hudson/model/UpdateCenterTest.java
  test/src/test/java/hudson/model/UsageStatisticsTest.java
  test/src/test/java/jenkins/security/RekeySecretAdminMonitorTest.java
Labels: ready-for-merge

#3898 JENKINS-55834 Typo in hudsonHomeIsFull, because of escaping apostrophes
  core/src/main/resources/hudson/diagnosis/HudsonHomeDiskUsageMonitor/index.properties
Labels: ready-for-merge

#3897 Add a serialVersionUID to hudson.EnvVars to avoid deserialisation errors
  core/src/main/java/hudson/EnvVars.java
Labels: ready-for-merge

#3896 [JEP-216] Bump localizer
  cli/pom.xml
  core/pom.xml
Labels: ready-for-merge

#3912 Update to jenkins-test-harness:2.47
  test-pom/pom.xml
Labels: ready-for-merge

#3905 help: clean up LogRecorder.logger
  war/src/main/webapp/help/LogRecorder/logger.html
Labels: ready-for-merge

#3907 Rely on auto unboxing
  core/src/main/java/hudson/Util.java
  core/src/main/java/hudson/model/Job.java
  core/src/main/java/hudson/model/ParametersAction.java
Labels: ready-for-merge

#3910 [FIX JENKINS-43218] Fix Fingerprint.toString()
  core/src/main/java/hudson/model/Fingerprint.java
Labels: ready-for-merge

#3906 [JENKINS-56200] LogRecorder: support turning off a log recorder
  core/src/main/java/hudson/logging/LogRecorder.java
Labels: ready-for-merge

#3902 [JENKINS-56167] Replace Trilead-ssh2 PEMParser class
  cli/src/main/java/hudson/cli/PrivateKeyProvider.java
  cli/src/test/java/hudson/cli/PrivateKeyProviderTest.java
  cli/src/test/resources/hudson/cli/dsa
  cli/src/test/resources/hudson/cli/dsa-password
  cli/src/test/resources/hudson/cli/openssh
  cli/src/test/resources/hudson/cli/openssh-broken
  cli/src/test/resources/hudson/cli/openssh-unsuported
  cli/src/test/resources/hudson/cli/rsa
  cli/src/test/resources/hudson/cli/rsa-password
Labels: ready-for-merge

#3821 spelling: dependent
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/PluginWrapper.java
  core/src/main/java/hudson/cli/DisablePluginCommand.java
  core/src/main/resources/hudson/Messages.properties
  core/src/main/resources/hudson/PluginManager/_table.js
  core/src/main/resources/hudson/PluginManager/installed.jelly
  core/src/main/resources/hudson/PluginManager/installed_bg.properties
  core/src/main/resources/hudson/PluginManager/installed_de.properties
  core/src/main/resources/hudson/PluginManager/installed_it.properties
  core/src/main/resources/hudson/PluginManager/installed_sr.properties
  core/src/main/resources/hudson/cli/Messages.properties
  test/src/test/java/hudson/PluginManagerInstalledGUITest.java
  test/src/test/java/hudson/cli/DisablePluginCommandTest.java
  war/src/main/webapp/css/style.css
Labels: ready-for-merge

#3917 Correct the Logger name for Legacy API Token monitor
  core/src/main/java/jenkins/security/apitoken/LegacyApiTokenAdministrativeMonitor.java
Labels: ready-for-merge
