Repository jenkinsci/jenkins, pull requests merged in 2019-07, with the labels that each got.

#4058 Add unit tests for hudson.cli.HexDump
  cli/src/test/java/hudson/cli/HexDumpTest.java
Labels: ready-for-merge

#4096 [JENKINS-56243] Ensure user seed saved to session
  core/src/main/java/hudson/security/TokenBasedRememberMeServices2.java
  test/src/test/java/hudson/security/TokenBasedRememberMeServices2Test.java
Labels: ready-for-merge

#4086 Adjust Deprecation tree according to Slave javadocs.
  core/src/main/java/hudson/model/Slave.java
  core/src/main/java/hudson/slaves/AbstractCloudSlave.java
Labels: ready-for-merge

#4003 [JENKINS-57223] - Java11 ClassNotFoundExceptions Telemetry
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/init/impl/InstallUncaughtExceptionHandler.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/telemetry/impl/java11/CatcherClassLoader.java
  core/src/main/java/jenkins/telemetry/impl/java11/MissingClassEvent.java
  core/src/main/java/jenkins/telemetry/impl/java11/MissingClassEvents.java
  core/src/main/java/jenkins/telemetry/impl/java11/MissingClassTelemetry.java
  core/src/main/java/jenkins/util/AntClassLoader.java
  test/src/test/java/jenkins/telemetry/MissingClassTelemetryTest.java
  test/src/test/java/jenkins/telemetry/impl/java11/MissingClassTelemetryFasterTest.java
Labels: ready-for-merge

#4026 Cleanup properties -- don't escape spaces
  core/src/main/resources/hudson/PluginManager/installed_tr.properties
  core/src/main/resources/hudson/diagnosis/HudsonHomeDiskUsageMonitor/index_da.properties
  core/src/main/resources/hudson/diagnosis/HudsonHomeDiskUsageMonitor/index_pt.properties
  core/src/main/resources/hudson/diagnosis/OldDataMonitor/manage_pt.properties
  core/src/main/resources/hudson/model/AbstractBuild/index_tr.properties
  core/src/main/resources/hudson/model/AbstractBuild/sidepanel_tr.properties
  core/src/main/resources/hudson/model/AbstractBuild/tasks_tr.properties
  core/src/main/resources/hudson/model/AbstractItem/delete_tr.properties
  core/src/main/resources/hudson/model/AbstractItem/noWorkspace_tr.properties
  core/src/main/resources/hudson/model/AbstractProject/configure-common_tr.properties
  core/src/main/resources/hudson/model/AbstractProject/main_tr.properties
  core/src/main/resources/hudson/model/AllView/noJob_tr.properties
  core/src/main/resources/hudson/model/Computer/sidepanel_tr.properties
  core/src/main/resources/hudson/model/DirectoryBrowserSupport/dir_tr.properties
  core/src/main/resources/hudson/model/Run/console_tr.properties
  core/src/main/resources/hudson/model/User/sidepanel_tr.properties
  core/src/main/resources/hudson/model/View/delete_tr.properties
  core/src/main/resources/hudson/model/View/index_tr.properties
  core/src/main/resources/hudson/model/View/newJob_tr.properties
  core/src/main/resources/hudson/node_monitors/MonitorMarkedNodeOffline/message_bg.properties
  core/src/main/resources/hudson/scm/EmptyChangeLogSet/digest_tr.properties
  core/src/main/resources/hudson/scm/SCM/project-changes_tr.properties
  core/src/main/resources/hudson/slaves/JNLPLauncher/help_bg.properties
  core/src/main/resources/hudson/tasks/Fingerprinter/FingerprintAction/index_tr.properties
  core/src/main/resources/hudson/tasks/Maven/help_bg.properties
  core/src/main/resources/hudson/triggers/SCMTrigger/AdministrativeMonitorImpl/message_bg.properties
  core/src/main/resources/hudson/triggers/SCMTrigger/AdministrativeMonitorImpl/message_pt_BR.properties
  core/src/main/resources/hudson/util/DoubleLaunchChecker/index_tr.properties
  core/src/main/resources/hudson/util/HudsonIsLoading/index_tr.properties
  core/src/main/resources/hudson/util/InsufficientPermissionDetected/index_pt_BR.properties
  core/src/main/resources/jenkins/management/Messages_tr.properties
  core/src/main/resources/jenkins/model/Jenkins/fingerprintCheck_tr.properties
  core/src/main/resources/jenkins/model/Jenkins/loginError_tr.properties
  core/src/main/resources/jenkins/model/Jenkins/login_tr.properties
  core/src/main/resources/jenkins/model/Jenkins/oops_pl.properties
  core/src/main/resources/jenkins/model/Jenkins/projectRelationship-help_tr.properties
  core/src/main/resources/jenkins/model/Jenkins/projectRelationship_tr.properties
  core/src/main/resources/jenkins/model/Jenkins/systemInfo_tr.properties
  core/src/main/resources/jenkins/model/JenkinsLocationConfiguration/config_tr.properties
  core/src/main/resources/jenkins/model/Messages_da.properties
  core/src/main/resources/lib/hudson/executors_tr.properties
  core/src/main/resources/lib/hudson/listScmBrowsers_tr.properties
  core/src/main/resources/lib/hudson/project/config-scm_tr.properties
  core/src/main/resources/lib/hudson/project/upstream-downstream_tr.properties
  core/src/main/resources/lib/hudson/queue_tr.properties
  core/src/main/resources/lib/hudson/scriptConsole_bg.properties
  core/src/main/resources/lib/hudson/scriptConsole_tr.properties
Labels: ready-for-merge

#4098 Display a warning in the Installed tab if the admin is about to disable or uninstall a detached plugin
  core/src/main/java/hudson/PluginWrapper.java
  core/src/main/resources/hudson/PluginManager/_table.js
  core/src/main/resources/hudson/PluginManager/installed.jelly
  core/src/main/resources/hudson/PluginManager/installed.properties
Labels: ready-for-merge

#4106 Fix typo
  core/src/main/resources/lib/form/optionalProperty.jelly
Labels: ready-for-merge

#4104 [JENKINS-57383] - Exception thrown when testing proxy configuration (regression in 2.168)
  core/src/main/java/hudson/ProxyConfiguration.java
Labels: ready-for-merge, regression-fix

#4099 [JENKINS-58362] Need to have only one copy of SystemCommandLanguage among detached plugins
  test/src/test/java/jenkins/install/LoadDetachedPluginsTest.java
  test/src/test/resources/jenkins/install/LoadDetachedPluginsTest/upgradeFromJenkins2WithNewerDependency/jenkins.install.InstallUtil.lastExecVersion
  test/src/test/resources/jenkins/install/LoadDetachedPluginsTest/upgradeFromJenkins2WithNewerDependency/plugins/script-security.jpi
  test/src/test/resources/jenkins/install/LoadDetachedPluginsTest/upgradeFromJenkins2WithNewerPlugin/jenkins.install.InstallUtil.lastExecVersion
  test/src/test/resources/jenkins/install/LoadDetachedPluginsTest/upgradeFromJenkins2WithNewerPlugin/plugins/command-launcher.jpi
  test/src/test/resources/jenkins/install/LoadDetachedPluginsTest/upgradeFromJenkins2WithNewerPlugin/plugins/script-security.jpi
  test/src/test/resources/jenkins/install/LoadDetachedPluginsTest/upgradeFromJenkins2WithOlderDependency/jenkins.install.InstallUtil.lastExecVersion
  test/src/test/resources/jenkins/install/LoadDetachedPluginsTest/upgradeFromJenkins2WithOlderDependency/plugins/script-security.jpi
  war/pom.xml
Labels: ready-for-merge

#4082 [JENKINS-24752] Avoid nodeprovisioner delay after consulting strategies
  core/src/main/java/hudson/slaves/NodeProvisioner.java
Labels: ready-for-merge

#4085 [JENKINS-43610] Split Trilead out from Core
  .mvn/maven.config
  core/pom.xml
  core/src/main/resources/jenkins/split-plugins.txt
  war/pom.xml
Labels: ready-for-merge

#4100 [JENKINS-58362] Also skip detached plugin installation if a *.[jh]pl file exists
  core/src/main/java/hudson/PluginManager.java
Labels: ready-for-merge

#4107 [JENKINS-55945] IllegalStateException trying to get user.
  core/src/main/java/hudson/security/HttpSessionContextIntegrationFilter2.java
Labels: ready-for-merge

#3982 [JENKINS-37862] Removing build symlink functionality
  core/src/main/java/hudson/model/PermalinkProjectAction.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/jenkins/model/PeepholePermalink.java
  core/src/test/java/jenkins/model/PeepholePermalinkTest.java
  test/src/test/java/hudson/model/AbstractProjectTest.java
  test/src/test/java/jenkins/model/JenkinsBuildsAndWorkspacesDirectoriesTest.java
  test/src/test/java/jenkins/model/PeepholePermalinkTest.java
Labels: ready-for-merge

#4089 [JENKINS-53322] Pre-work for removing dom4j fork.
  licenseCompleter.groovy
  test/src/test/java/hudson/bugs/JnlpAccessWithSecuredHudsonTest.java
Labels: ready-for-merge

#4052 update commons codec from 1.9 to 1.12
  pom.xml
Labels: ready-for-merge

#4109 [JENKINS-43610] use trilead-api 1.0.4
  core/src/main/resources/jenkins/split-plugins.txt
  war/pom.xml
Labels: ready-for-merge, skip-changelog

#4103 [JENKINS-56793] Set `screenResolution` cookie to root path
  core/src/main/resources/hudson/model/View/index.jelly
Labels: ready-for-merge, web-ui

#4111 [JENKINS-58483, JENKINS-43669] - Remove Trilead SSH dependencies for CLI and the Core
  cli/pom.xml
  core/pom.xml
  war/pom.xml
Labels: ready-for-merge

#4112 Fixing hint for Jenkins.getInstance
  core/src/main/resources/META-INF/upgrade/Jenkins.hint
Labels: ready-for-merge

#4114 Behave robustly in the face of errors from AdministrativeMonitor.isActivated
  core/src/main/java/jenkins/model/Jenkins.java
Labels: ready-for-merge

#4105 Make disk usage checker period configurable
  core/src/main/java/hudson/node_monitors/AbstractNodeMonitorDescriptor.java
Labels: ready-for-merge

#4097 [WEBSITE-634] - Add Release Drafter configuration for drafting Weekly release YAMLs
  .github/release-drafter.yml
Labels: internal, on-hold, ready-for-merge

#4118 Bump slf4j from 1.7.25 to 1.7.26
  pom.xml
Labels: ready-for-merge

#4119 Add Latest release and Docker shields to README
  README.md
Labels: ready-for-merge, skip-changelog

#4115 Remove extra space in css url()
  war/src/main/webapp/css/style.css
Labels: ready-for-merge

#4120 Omit WEB-INF/lib/jquery-detached-1.2.jar from jenkins.war
  war/pom.xml
Labels: internal, ready-for-merge

#4129 Run the Linux JDK 8 & 11 builds using ACI agents rather than Ubuntu VMs
  Jenkinsfile
  test/src/test/java/hudson/tasks/ArtifactArchiverTest.java
  test/src/test/java/jenkins/model/JenkinsBuildsAndWorkspacesDirectoriesTest.java
Labels: internal, ready-for-merge, skip-changelog

#4117 [JENKINS-58520] - Make new Jenkins version notification noticeable in administrative monitors
  core/src/filter/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message.properties
Labels: ready-for-merge, web-ui

#3802 [JENKINS-54854] Added a warning when cron trigger spent more than a threshold (30s) in its execution
  core/src/main/java/hudson/triggers/SlowTriggerAdminMonitor.java
  core/src/main/java/hudson/triggers/Trigger.java
  core/src/main/resources/hudson/triggers/Messages.properties
  core/src/main/resources/hudson/triggers/SlowTriggerAdminMonitor/message.groovy
  test/src/test/java/jenkins/triggers/TriggerTest.java
Labels: ready-for-merge

#4123 Stop using the "name" argument in the "install-plugin" CLI command
  core/src/main/java/hudson/cli/InstallPluginCommand.java
  test/src/test/java/hudson/cli/InstallPluginCommandTest.java
Labels: ready-for-merge
