Repository jenkinsci/jenkins, pull requests merged in 2019-12, with the labels that each got.

#4329 [JENKINS-57304] - Add call to oneOffExecutors.remove in Computer.removeExecutor
  core/src/main/java/hudson/model/Computer.java
Labels: bug, ready-for-merge

#4373 [JENKINS-60278] Prevent Oops when Whitelisted Commands input is empty
  core/src/main/java/jenkins/security/s2m/AdminWhitelistRule.java
Labels: bug, ready-for-merge

#4383 Fix online example/documentation for File Access Rules
  core/src/main/resources/jenkins/security/s2m/AdminWhitelistRule/index.jelly
Labels: bug, ready-for-merge

#4370 merged superfluous if with while loop
  core/src/main/java/hudson/model/AbstractItem.java
Labels: internal, ready-for-merge, skip-changelog

#4392 Adapt some tests to newer Jetty
  test-pom/pom.xml
  test/src/test/java/hudson/security/csrf/DefaultCrumbIssuerSEC1491Test.java
  test/src/test/java/hudson/security/csrf/DefaultCrumbIssuerSEC626Test.java
  test/src/test/java/jenkins/security/ResourceDomainTest.java
Labels: internal, skip-changelog

#4384 [JENKINS-60357] Use XMLUnit to fix test
  core/pom.xml
  core/src/test/java/hudson/util/CopyOnWriteListTest.java
Labels: internal, ready-for-merge, skip-changelog

#4390 Minor test code cleanup
  test/src/test/java/hudson/cli/CLITest.java
  test/src/test/java/hudson/model/BuildExecutionTest.java
  test/src/test/java/hudson/model/FreeStyleProjectTest.java
  test/src/test/java/hudson/model/ManagementLinkTest.java
  test/src/test/java/hudson/model/ParametersAction2Test.java
  test/src/test/java/hudson/scm/ChangeLogSetTest.java
  test/src/test/java/hudson/security/HudsonPrivateSecurityRealmTest.java
  test/src/test/java/hudson/security/SecurityRealmTest.java
  test/src/test/java/hudson/security/TokenBasedRememberMeServices2Test.java
  test/src/test/java/hudson/tasks/FingerprinterTest.java
  test/src/test/java/hudson/tasks/MavenTest.java
  test/src/test/java/jenkins/model/ContextMenuTest.java
  test/src/test/java/jenkins/model/JenkinsBuildsAndWorkspacesDirectoriesTest.java
  test/src/test/java/jenkins/model/JenkinsTest.java
  test/src/test/java/jenkins/model/MasterBuildConfigurationTest.java
  test/src/test/java/jenkins/model/lazy/LazyBuildMixInTest.java
  test/src/test/java/jenkins/security/FilePathSecureTest.java
Labels: internal, ready-for-merge, skip-changelog

#4264 [JENKINS-59656] check build id before interrupting from the executors widget
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/model/Executor.java
  core/src/main/resources/lib/hudson/executors.jelly
  test/src/test/java/jenkins/security/stapler/Security400Test.java
Labels: bug, plugin-api-changes, ready-for-merge, web-ui

#4388 Adding some nullability annotations related to Label
  core/src/main/java/hudson/model/Label.java
  core/src/main/java/hudson/slaves/NodeProvisioner.java
Labels: developer, ready-for-merge, skip-changelog

#4337 Replaced integer with AtomicInteger to fix spotbugs issue
  core/src/main/java/hudson/scm/AutoBrowserHolder.java
  core/src/main/java/hudson/scm/SCMDescriptor.java
  core/src/main/java/hudson/scm/SCMS.java
Labels: developer, plugin-api-changes, ready-for-merge

#4399 DNS comparisons of jenkins.io and www.jenkins.io do not pass.
  test/src/test/java/jenkins/security/Security637Test.java
Labels: skip-changelog

#4382 [JENKINS-60351] - Make it possible to disable multiple deletion attempts by setting hudson.Util.maxFileDeletionRetries to zero
  core/src/main/java/hudson/Util.java
  core/src/main/java/jenkins/util/io/PathRemover.java
Labels: bug, ready-for-merge

#4396 fixed_typos_in_bom/pom.xml
  bom/pom.xml
Labels: internal, ready-for-merge, skip-changelog

#4394 [JENKINS-59107] User is no longer logged out when authenticating another user
  core/src/main/java/jenkins/security/seed/UserSeedSecurityListener.java
  test/src/test/java/jenkins/security/seed/UserSeedSecurityListenerTest.java
Labels: ready-for-merge, regression-fix

#4398 Adapt to newer HtmlUnit
  test-pom/pom.xml
  test/src/test/java/hudson/PluginTest.java
  test/src/test/java/hudson/diagnosis/HudsonHomeDiskUsageMonitorTest.java
  test/src/test/java/jenkins/security/ResourceDomainTest.java
Labels: internal, ready-for-merge, skip-changelog

#4397 [JENKINS-60553][SECURITY-1605] Remove teamconcert with security warning from wizard
  core/src/main/resources/jenkins/install/platform-plugins.json
Labels: bug, needs-jira-issue, ready-for-merge

#4401 [JENKINS-60554] - EscapedMarkupFormatter did not properly handle a null argument
  core/src/main/java/hudson/markup/EscapedMarkupFormatter.java
  test/src/test/java/hudson/markup/MarkupFormatterTest.java
Labels: bug, ready-for-merge

#4380 Spotbugs findings (catch runtime ex. and known null)
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/scheduler/CronTabList.java
  core/src/main/java/hudson/util/DoubleLaunchChecker.java
Labels: ready-for-merge, skip-changelog

#4400 JENKINS-60513: Added transient to SCMDescriptor#generation AtomicInteger to fix warnings
  core/src/main/java/hudson/scm/SCMDescriptor.java
Labels: ready-for-merge, regression-fix

#4403 removed obsolete SpotBugs suppresses
  core/src/main/java/hudson/Launcher.java
  core/src/main/java/hudson/util/XStream2.java
  core/src/main/java/jenkins/security/ApiTokenProperty.java
  core/src/main/java/jenkins/security/apitoken/ApiTokenStore.java
Labels: internal, skip-changelog

#4371 Replace compare() implementations with call to Integer.compare or Long.compare
  core/src/main/java/hudson/model/Fingerprint.java
  core/src/main/java/hudson/model/HealthReport.java
  core/src/main/java/hudson/model/Queue.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/model/View.java
  core/src/main/java/hudson/model/queue/AbstractQueueSorterImpl.java
  core/src/main/java/hudson/util/ConsistentHash.java
  core/src/main/java/hudson/util/RunList.java
  core/src/main/java/jenkins/widgets/HistoryPageFilter.java
Labels: ready-for-merge, skip-changelog

#4378 Remove unused direct dependency commons-codec from Jenkins CLI
  cli/pom.xml
Labels: internal, ready-for-merge

#4180 [JENKINS-36720]: Fixed some Spotbugs issues
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/triggers/SlowTriggerAdminMonitor.java
  core/src/main/java/hudson/util/SecretRewriter.java
  core/src/main/java/hudson/util/TextFile.java
  core/src/main/java/hudson/util/spring/DefaultRuntimeSpringConfiguration.java
  core/src/main/java/jenkins/model/PeepholePermalink.java
  core/src/main/java/jenkins/model/RunIdMigrator.java
  core/src/main/java/jenkins/security/RekeySecretAdminMonitor.java
  core/src/main/java/jenkins/security/s2m/ConfigDirectory.java
Labels: internal, skip-changelog

#4395 [JENKINS-21311] Make the queue/cancelItem API an API.
  core/src/main/java/hudson/model/Queue.java
  core/src/main/resources/hudson/model/queue/_api.jelly
  core/src/test/java/hudson/model/QueueTest.java
  test/src/test/java/hudson/model/QueueTest.java
Labels: ready-for-merge, rfe

#4323 Switch Release Drafter to GitHub Actions
  .github/workflows/changelog.yml
Labels: hacktoberfest, internal, ready-for-merge, skip-changelog

#4406 Add Jenkins Changelog Generator to the GitHub Actions release drafter Pipeline
  .github/workflows/changelog.yml
Labels: internal

#4409 Spotbugs: remove UMAC_UNCALLABLE_METHOD_OF_ANONYMOUS_CLASS from global exclude
  src/findbugs/findbugs-excludes.xml
Labels: internal, skip-changelog
