Repository jenkinsci/jenkins, pull requests merged in 2019-11, with the labels that each got.

#4335 Exposing basics of ResourceDomainConfiguration via Java API
  core/src/main/java/jenkins/security/ResourceDomainConfiguration.java
Labels: developer

#4320 [JENKINS-59775] Ensure that PluginManager.start runs as SYSTEM
  core/src/main/java/hudson/PluginManager.java
  test/src/test/java/hudson/PluginManagerTest.java
Labels: ready-for-merge

#4331 Add note to run mvn hudson-dev:run to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: skip-changelog

#4305 Minor improvements to the logging UI
  core/src/main/resources/hudson/logging/LogRecorderManager/all.jelly
  core/src/main/resources/hudson/logging/LogRecorderManager/sidepanel.jelly
  core/src/main/resources/hudson/logging/Messages.properties
Labels: ready-for-merge, rfe, web-ui

#4343 Fix misspellings in doc for hudson.model.Cause
  core/src/main/java/hudson/model/Cause.java
Labels: ready-for-merge, skip-changelog

#4340 Upgrade to 3.36 version of Remoting.
  pom.xml
Labels: ready-for-merge, rfe

#4334 Reenable ATH in Jenkinsfile
  Jenkinsfile
Labels: skip-changelog

#4324 added CheckForNull
  core/src/main/java/hudson/model/AbstractProject.java
Labels: ready-for-merge, skip-changelog

#4332 [JENKINS-55062] Correct tests
  test/src/test/java/hudson/util/HudsonIsLoadingTest.java
  test/src/test/java/hudson/util/HudsonIsRestartingTest.java
Labels: skip-changelog, squash-merge-me

#4341 Add more data points to MultiStageTimeSeries
  core/src/main/java/hudson/model/MultiStageTimeSeries.java
Labels: rfe

#4326 Fix Jenkins renaming leftovers in Turkish localization
  core/src/main/resources/hudson/PluginManager/installed_tr.properties
  core/src/main/resources/hudson/PluginManager/sidepanel_tr.properties
  core/src/main/resources/hudson/model/AbstractItem/noWorkspace_tr.properties
  core/src/main/resources/hudson/model/AllView/noJob_tr.properties
  core/src/main/resources/hudson/model/ComputerSet/sidepanel_tr.properties
  core/src/main/resources/hudson/model/Fingerprint/index_tr.properties
  core/src/main/resources/hudson/model/Messages_tr.properties
  core/src/main/resources/hudson/model/UpdateCenter/body_tr.properties
  core/src/main/resources/hudson/model/UpdateCenter/sidepanel_tr.properties
  core/src/main/resources/hudson/security/FullControlOnceLoggedInAuthorizationStrategy/help_tr.html
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/config_tr.properties
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/help-useSecurity_tr.html
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/index_tr.properties
  core/src/main/resources/hudson/security/LegacyAuthorizationStrategy/help_tr.html
  core/src/main/resources/hudson/security/LegacySecurityRealm/help_tr.html
  core/src/main/resources/hudson/tasks/Fingerprinter/FingerprintAction/index_tr.properties
  core/src/main/resources/hudson/triggers/SCMTrigger/help_tr.html
  core/src/main/resources/hudson/triggers/TimerTrigger/help_tr.html
  core/src/main/resources/hudson/util/DoubleLaunchChecker/index_tr.properties
  core/src/main/resources/hudson/util/IncompatibleAntVersionDetected/index_tr.properties
  core/src/main/resources/jenkins/management/Messages_tr.properties
  core/src/main/resources/jenkins/model/BuildDiscarderProperty/help_tr.html
  core/src/main/resources/jenkins/model/GlobalQuietPeriodConfiguration/help-quietPeriod_tr.html
  core/src/main/resources/jenkins/model/Jenkins/manage_tr.properties
  core/src/main/resources/jenkins/model/Jenkins/projectRelationship-help_tr.properties
  war/src/main/webapp/help/system-config/master-slave/clock_tr.html
  war/src/main/webapp/help/system-config/master-slave/numExecutors_tr.html
  war/src/main/webapp/help/system-config/master-slave/usage_tr.html
Labels: localization

#4311 [JENKINS-59886] Strengthen the queue to avoid canTake and canRun implementers hanging the queue
  core/src/main/java/hudson/model/Node.java
  core/src/main/java/hudson/model/Queue.java
  core/src/main/resources/hudson/model/Messages.properties
  core/src/main/resources/hudson/model/Messages_es.properties
  test/src/test/java/hudson/model/queue/MaintainCanTakeStrengtheningTest.java
Labels: bug, ready-for-merge

#4080 IntelliJ/Java: Duplicate code -- Refactored as DOSToUnixPathHelper.validate
  core/src/main/java/hudson/util/DOSToUnixPathHelper.java
  core/src/main/java/hudson/util/FormFieldValidator.java
  core/src/main/java/hudson/util/FormValidation.java
Labels: ready-for-merge

#4347 [JENKINS-60098] - Upgrade to winstone 5.4 to take advantage of Jetty 9.4.22
  war/pom.xml
Labels: ready-for-merge, rfe

#4350 jenkins-cli.jar no longer needs to bundle remoting
  cli/pom.xml
  core/src/main/java/hudson/cli/Connection.java
Labels: bug, ready-for-merge

#4342 [JENKINS-59631] Fix styling issue in build history table
  war/src/main/webapp/css/style.css
Labels: bug, ready-for-merge, web-ui

#3983 Try to execute flyweight tasks on the master
  core/src/main/java/hudson/model/Node.java
  core/src/main/java/hudson/model/Queue.java
  test/src/test/java/hudson/model/QueueTest.java
Labels: ready-for-merge, rfe, squash-merge-me

#4346 [JENKINS-59793] Avoid hanging jobs with faulty SubTasks
  core/src/main/java/hudson/model/queue/WorkUnitContext.java
  test/src/test/java/hudson/model/queue/BuildKeepsRunningWhenFaultySubTasksTest.java
Labels: bug, ready-for-merge

#4330 Remove unused jenkins-slave.xml file from the Core
  core/src/main/resources/windows-service/jenkins-slave.xml
Labels: ready-for-merge, rfe, upgrade-guide-needed

#4298 [JENKINS-59665] - Fix sorting of the Uninstall column in the Install pane of the Plugin Manager
  core/src/main/resources/hudson/PluginManager/installed.jelly
Labels: bug, hacktoberfest, ready-for-merge, web-ui

#3991 Hide password form fields by default
  core/src/main/java/hudson/Functions.java
  core/src/main/resources/lib/form/password.jelly
  core/src/main/resources/lib/form/password/password.css
  core/src/main/resources/lib/form/password/password.js
  test/src/test/java/hudson/model/PasswordParameterDefinitionTest.java
  test/src/test/java/jenkins/security/RedactSecretJsonInErrorMessageSanitizerHtmlTest.java
  test/src/test/java/lib/form/PasswordTest.java
  test/src/test/resources/jenkins/security/RedactSecretJsonInErrorMessageSanitizerHtmlTest/TestPassword/index.jelly
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, rfe, upgrade-guide-needed, web-ui

#4349 [JENKINS-59508] Sidebar links show full label on hover
  core/src/main/resources/lib/layout/task.jelly
Labels: ready-for-merge, rfe, web-ui

#4351 Switch from maven-jenkins-dev-plugin to upstream jetty-maven-plugin
  CONTRIBUTING.md
  core/src/main/java/hudson/Main.java
  core/src/main/java/hudson/init/InitStrategy.java
  core/src/main/java/hudson/model/Slave.java
  core/src/main/java/jenkins/model/Jenkins.java
  pom.xml
  war/nbactions.xml
  war/pom.xml
Labels: internal, ready-for-merge, skip-changelog

#4322 JENKINS-6722 Show agent error status on the dashboard
  core/src/main/resources/lib/hudson/executors.jelly
  core/src/main/resources/lib/hudson/executors.properties
Labels: ready-for-merge, rfe, web-ui

#3935 JENKINS-56553 Make proxy config compatible with JCasC without workarounds on the plugin side
  core/src/main/java/hudson/ProxyConfiguration.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/resources/hudson/ProxyConfiguration/config.groovy
Labels: plugin-api-changes, ready-for-merge, rfe

#4345 Reduce log levels for successful run completion and update center polling events
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/model/UpdateSite.java
Labels: ready-for-merge, rfe

#4339 Move cloud configuration out of Configure System
  core/src/main/java/jenkins/model/GlobalCloudConfiguration.java
  core/src/main/resources/hudson/model/ComputerSet/sidepanel.jelly
  core/src/main/resources/jenkins/management/Messages.properties
  core/src/main/resources/jenkins/model/GlobalCloudConfiguration/config.groovy
  core/src/main/resources/jenkins/model/GlobalCloudConfiguration/index.groovy
  core/src/main/resources/jenkins/model/GlobalCloudConfiguration/index_da.properties
  core/src/main/resources/jenkins/model/GlobalCloudConfiguration/index_de.properties
  core/src/main/resources/jenkins/model/GlobalCloudConfiguration/index_es.properties
  core/src/main/resources/jenkins/model/GlobalCloudConfiguration/index_fr.properties
  core/src/main/resources/jenkins/model/GlobalCloudConfiguration/index_it.properties
  core/src/main/resources/jenkins/model/GlobalCloudConfiguration/index_ja.properties
  core/src/main/resources/jenkins/model/GlobalCloudConfiguration/index_pt_BR.properties
  core/src/main/resources/jenkins/model/GlobalCloudConfiguration/index_sr.properties
  core/src/main/resources/jenkins/model/GlobalCloudConfiguration/index_zh_TW.properties
  core/src/main/resources/jenkins/model/Jenkins/_cloud-note.groovy
  core/src/main/resources/jenkins/model/Jenkins/_cloud-note.properties
  core/src/main/resources/jenkins/model/Jenkins/configure.jelly
  core/src/main/resources/jenkins/model/Messages.properties
Labels: ready-for-merge, rfe

#4359 [JENKINS-60180] Disable HTTP TRACE
  war/src/main/webapp/WEB-INF/web.xml
Labels: ready-for-merge, rfe, skip-changelog

#4362 [JENKINS-60189] - Open plugin and license links on a separate tab
  core/src/main/resources/hudson/PluginManager/installed.jelly
  core/src/main/resources/hudson/PluginManager/table.jelly
  core/src/main/resources/lib/hudson/thirdPartyLicenses.jelly
Labels: ready-for-merge, rfe, web-ui

#4357 [JENKINS-60167] - Fix AtomicFileWriter performance issue on CephFS in case of Empty File creation
  core/src/main/java/hudson/util/AtomicFileWriter.java
Labels: bug, ready-for-merge

#4220 Introduce JUnit5 as testing backend for CLI tests
  cli/pom.xml
  cli/src/test/java/hudson/cli/HexDumpTest.java
  cli/src/test/java/hudson/cli/PlainCLIProtocolTest.java
  cli/src/test/java/hudson/cli/PrivateKeyProviderTest.java
Labels: developer, ready-for-merge, rfe

#4361 Try with resources instead of try finally
  core/src/main/java/hudson/model/DirectoryBrowserSupport.java
  core/src/main/java/hudson/util/ProcessTree.java
  core/src/main/java/jenkins/util/AntClassLoader.java
  core/src/test/java/hudson/FilePathTest.java
  core/src/test/java/hudson/util/io/ZipArchiverTest.java
Labels: ready-for-merge, skip-changelog

#4364 use StandardCharsets.UTF_8 instead of string
  core/src/main/java/hudson/model/Descriptor.java
  core/src/main/java/hudson/model/DownloadService.java
  core/src/main/java/jenkins/install/SetupWizard.java
  core/src/test/java/hudson/util/SecretTest.java
  core/src/test/java/hudson/util/XStream2EncodingTest.java
  core/src/test/java/jenkins/security/RSADigitalSignatureConfidentialKeyTest.java
  core/src/test/java/jenkins/util/MarkFindingOutputStreamTest.java
Labels: ready-for-merge, skip-changelog

#4363 Set the HttpOnly flag for the page auto-refresh tokens
  core/src/main/java/hudson/Functions.java
Labels: ready-for-merge, rfe

#4348 [JENKINS-60092] getPrimaryView: return null if no view is defined
  core/src/main/java/hudson/model/ViewGroupMixIn.java
Labels: bug, plugin-api-changes, ready-for-merge

#4262 Replaced deprecated getActiveInstance() with get()
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/PluginWrapper.java
  core/src/main/java/hudson/cli/CLIAction.java
  core/src/main/java/hudson/cli/CLICommand.java
  core/src/main/java/hudson/cli/CancelQuietDownCommand.java
  core/src/main/java/hudson/cli/ClearQueueCommand.java
  core/src/main/java/hudson/cli/CopyJobCommand.java
  core/src/main/java/hudson/cli/CreateJobCommand.java
  core/src/main/java/hudson/cli/CreateNodeCommand.java
  core/src/main/java/hudson/cli/CreateViewCommand.java
  core/src/main/java/hudson/cli/DeleteJobCommand.java
  core/src/main/java/hudson/cli/DeleteNodeCommand.java
  core/src/main/java/hudson/cli/DisconnectNodeCommand.java
  core/src/main/java/hudson/cli/GroovyCommand.java
  core/src/main/java/hudson/cli/GroovyshCommand.java
  core/src/main/java/hudson/cli/HelpCommand.java
  core/src/main/java/hudson/cli/ListJobsCommand.java
  core/src/main/java/hudson/cli/QuietDownCommand.java
  core/src/main/java/hudson/cli/ReloadJobCommand.java
  core/src/main/java/hudson/cli/handlers/ViewOptionHandler.java
  core/src/main/java/hudson/model/AsyncAperiodicWork.java
  core/src/main/java/hudson/model/AsyncPeriodicWork.java
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/model/Descriptor.java
  core/src/main/java/hudson/model/DownloadService.java
  core/src/main/java/hudson/model/Job.java
  core/src/main/java/hudson/model/OverallLoadStatistics.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/model/UnlabeledLoadStatistics.java
  core/src/main/java/jenkins/util/groovy/GroovyHookScript.java
  core/src/test/java/hudson/cli/ListJobsCommandTest.java
  core/src/test/java/hudson/cli/handlers/ViewOptionHandlerTest.java
  test/src/test/java/hudson/cli/CancelQuietDownCommandTest.java
  test/src/test/java/hudson/cli/ConnectNodeCommandTest.java
  test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java
  test/src/test/java/hudson/cli/OfflineNodeCommandTest.java
  test/src/test/java/hudson/cli/OnlineNodeCommandTest.java
  test/src/test/java/hudson/cli/QuietDownCommandTest.java
  test/src/test/java/hudson/model/UsageStatisticsTest.java
Labels: internal, ready-for-merge, skip-changelog

#4367 Update bundled script-security to 1.68
  war/pom.xml
Labels: ready-for-merge, rfe

#4377 Race condition in PlainCLIProtocolTest
  cli/src/test/java/hudson/cli/PlainCLIProtocolTest.java
Labels: internal, ready-for-merge, skip-changelog

#4372 Removed some redundant constructs
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/PluginWrapper.java
  core/src/main/java/hudson/model/LoadStatistics.java
  core/src/main/java/hudson/scm/EmptyChangeLogSet.java
  core/src/main/java/hudson/util/Iterators.java
  core/src/main/java/hudson/util/SecretRewriter.java
  core/src/main/java/hudson/util/jna/Advapi32.java
  core/src/main/java/jenkins/util/io/PathRemover.java
  core/src/test/java/hudson/util/ArgumentListBuilderTest.java
  core/src/test/java/hudson/util/CopyOnWriteListTest.java
Labels: ready-for-merge, skip-changelog

#4375 Jenkinsfile: Use -ntp in the Maven Build
  Jenkinsfile
Labels: internal, ready-for-merge, skip-changelog

#4366 [JENKINS-6798] Redirect on HTTP 502, 503, 504
  war/src/main/webapp/scripts/hudson-behavior.js
  war/src/main/webapp/scripts/loading.js
Labels: bug, ready-for-merge
