Repository jenkinsci/jenkins, pull requests merged in 2019-01, with the labels that each got.

#3833 Suggest ExtensionList.lookupSingleton
  core/src/main/java/jenkins/model/GlobalConfiguration.java
Labels: ready-for-merge

#3837 [JENKINS-55449] Add tool to update "@since TODO" entries
  core/src/main/java/hudson/EnvVars.java
  core/src/main/java/hudson/Util.java
  core/src/main/java/hudson/cli/DisablePluginCommand.java
  core/src/main/java/jenkins/model/SimplePageDecorator.java
  core/src/main/java/jenkins/util/xstream/SafeURLConverter.java
  update-since-todo.sh
Labels: ready-for-merge

#3016 [JENKINS-55048] Add support for plugin Java requirement metadata
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/PluginWrapper.java
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/java/jenkins/install/SetupWizard.java
  core/src/main/java/jenkins/util/java/JavaUtils.java
  core/src/main/resources/hudson/Messages.properties
  core/src/main/resources/hudson/PluginManager/_table.css
  core/src/main/resources/hudson/PluginManager/table.jelly
  core/src/main/resources/hudson/PluginManager/table.properties
  core/src/test/java/hudson/PluginWrapperTest.java
  test/src/test/java/hudson/model/UpdateSiteTest.java
  test/src/test/resources/plugins/minJavaVersion-update-center.json
Labels: java11, needs-review, ready-for-merge

#3845 [JENKINS-55448] Revert "[JENKINS-55016] Fix flakiness in UtilTest"
  core/src/main/java/hudson/Util.java
  core/src/main/java/jenkins/util/io/CompositeIOException.java
  core/src/main/java/jenkins/util/io/PathRemover.java
  core/src/test/java/hudson/RemoveWindowsDirectoryJunctionTest.java
  core/src/test/java/hudson/UtilTest.java
  core/src/test/java/jenkins/util/io/FileLockerRule.java
  core/src/test/java/jenkins/util/io/PathRemoverTest.java
Labels: ready-for-merge, regression

#3849 Minor wording change in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: ready-for-merge

#3843 Makes 'Config <item>' translatable and configurable
  core/src/main/resources/hudson/model/Job/configure.jelly
  core/src/main/resources/hudson/model/Job/configure.properties
  core/src/main/resources/hudson/model/Job/configure_pl.properties
Labels: ready-for-merge

#3817 [JENKINS-55428]: Support API creation with a hashed password
  core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java
  test/src/test/java/hudson/security/HudsonPrivateSecurityRealmTest.java
Labels: ready-for-merge

#3847 Bump to executable-war:1.44
  war/pom.xml
Labels: ready-for-merge

#3842 Give more details about the expected Java version format
  core/src/main/java/jenkins/util/java/JavaUtils.java
Labels: ready-for-merge

#3830 Bumping to frontend-m-p:1.6 for consistency
  war/pom.xml
Labels: ready-for-merge

#3825 [JENKINS-55305] Add user creation listener methods to SecurityListener
  core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java
  core/src/main/java/jenkins/security/SecurityListener.java
  test/src/test/java/hudson/security/HudsonPrivateSecurityRealmTest.java
Labels: ready-for-merge

#3728 JENKINS-53284 Fix warning message for changing workspace directories
  core/src/main/java/jenkins/model/Jenkins.java
  test/src/test/java/jenkins/model/JenkinsBuildsAndWorkspacesDirectoriesTest.java
Labels: ready-for-merge

#3860 When a node is back to normal, log as INFO instead of WARN
  core/src/main/java/hudson/node_monitors/AbstractDiskSpaceMonitor.java
Labels: ready-for-merge

#3858 English
  core/src/main/resources/jenkins/security/ApiTokenProperty/config.properties
  core/src/main/resources/jenkins/security/ApiTokenProperty/help-tokenStore.html
  core/src/main/resources/jenkins/security/apitoken/LegacyApiTokenAdministrativeMonitor/manage.properties
  war/src/main/webapp/help/user/fullName.html
Labels: ready-for-merge

#3445 Address quiet period edge case (???)
  core/src/main/java/hudson/model/Queue.java
  core/src/main/resources/hudson/model/Messages.properties
Labels: ready-for-merge

#3208 Bulk cleanup of code in hudson.cli.
  core/src/main/java/hudson/cli/BuildCommand.java
  core/src/main/java/hudson/cli/CLIAction.java
  core/src/main/java/hudson/cli/CLICommand.java
  core/src/main/java/hudson/cli/ClearQueueCommand.java
  core/src/main/java/hudson/cli/CliManagerImpl.java
  core/src/main/java/hudson/cli/ConnectNodeCommand.java
  core/src/main/java/hudson/cli/CreateNodeCommand.java
  core/src/main/java/hudson/cli/DeleteBuildsCommand.java
  core/src/main/java/hudson/cli/DeleteJobCommand.java
  core/src/main/java/hudson/cli/DeleteNodeCommand.java
  core/src/main/java/hudson/cli/DeleteViewCommand.java
  core/src/main/java/hudson/cli/DisconnectNodeCommand.java
  core/src/main/java/hudson/cli/GroovyCommand.java
  core/src/main/java/hudson/cli/GroovyshCommand.java
  core/src/main/java/hudson/cli/HelpCommand.java
  core/src/main/java/hudson/cli/InstallPluginCommand.java
  core/src/main/java/hudson/cli/InstallToolCommand.java
  core/src/main/java/hudson/cli/ListJobsCommand.java
  core/src/main/java/hudson/cli/OfflineNodeCommand.java
  core/src/main/java/hudson/cli/OnlineNodeCommand.java
  core/src/main/java/hudson/cli/ReloadConfigurationCommand.java
  core/src/main/java/hudson/cli/ReloadJobCommand.java
  core/src/main/java/hudson/cli/RemoveJobFromViewCommand.java
  core/src/main/java/hudson/cli/declarative/CLIRegisterer.java
  core/src/main/java/hudson/cli/handlers/GenericItemOptionHandler.java
  core/src/main/java/hudson/cli/handlers/NodeOptionHandler.java
Labels: ready-for-merge

#3172 Add default impl. to RootAction
  core/src/main/java/hudson/model/InvisibleAction.java
  test/src/test/java/jenkins/model/JenkinsTest.java
  test/src/test/java/jenkins/util/FullDuplexHttpServiceTest.java
  test/src/test/java/lib/form/FormTest.java
  test/src/test/java/lib/form/RowSetTest.java
Labels: needs-more-reviews

#3828 [JENKINS-55361] DescriptorExtensionList not locking correctly, leading to deadlocks
  core/src/main/java/hudson/DescriptorExtensionList.java
Labels: ready-for-merge

#3240 [JENKINS-48985] - Better diagnostics for Old Data Monitor null safety
  core/src/main/java/hudson/diagnosis/OldDataMonitor.java
  core/src/main/java/hudson/model/AdministrativeMonitor.java
  core/src/main/java/jenkins/model/Jenkins.java
Labels: ready-for-merge

#3456 Replacing text references of "slave" with "agent"
  core/src/main/java/hudson/Util.java
  core/src/main/java/hudson/slaves/ChannelPinger.java
  core/src/main/java/hudson/slaves/SlaveComputer.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/resources/hudson/model/AbstractItem/help-slaveAffinity.html
  core/src/main/resources/hudson/slaves/JNLPLauncher/main_pt_BR.properties
  core/src/main/resources/jenkins/model/Jenkins/systemInfo_bg.properties
  core/src/main/resources/jenkins/security/s2m/filepath-filter.conf
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol/description.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol/description_bg.properties
  core/src/test/java/hudson/LauncherTest.java
  core/src/test/java/hudson/model/JobTest.java
  test/src/test/java/hudson/bugs/JnlpAccessWithSecuredHudsonTest.java
  test/src/test/java/hudson/cli/UpdateNodeCommandTest.java
  test/src/test/java/hudson/model/ProjectTest.java
  test/src/test/java/hudson/model/QueueTest.java
  test/src/test/java/hudson/model/ViewTest.java
  test/src/test/java/hudson/model/labels/LabelExpressionTest.java
  test/src/test/java/hudson/slaves/EnvironmentVariableNodePropertyTest.java
  test/src/test/java/hudson/tasks/EnvVarsInConfigTasksTest.java
  test/src/test/java/hudson/util/ProcessTreeKillerTest.java
  test/src/test/java/jenkins/model/UnlabeledLoadStatisticsTest.java
  test/src/test/java/jenkins/security/Security218Test.java
  test/src/test/java/jenkins/security/s2m/AdminFilePathFilterTest.java
  test/src/test/resources/hudson/model/node.xml
  war/src/main/webapp/help/system-config/master-slave/availability_ja.html
  war/src/main/webapp/help/system-config/master-slave/clock.html
  war/src/main/webapp/help/system-config/master-slave/jnlp-tunnel.html
  war/src/main/webapp/help/system-config/master-slave/jnlpSecurity.html
  war/src/main/webapp/help/system-config/master-slave/numExecutors.html
Labels: ready-for-merge
