Repository jenkinsci/jenkins, pull requests merged in 2019-09, with the labels that each got.

#4130 [JENKINS-53322] Remove patched dom4j fork
  core/pom.xml
  test/src/test/java/jenkins/security/stapler/StaplerDispatchValidatorTest.java
Labels: ready-for-merge

#4169 Replace Apache Commons Codec Base64 implementations with standard java.util.Base64
  cli/src/main/java/hudson/cli/CLIConnectionFactory.java
  core/src/main/java/hudson/TcpSlaveAgentListener.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/security/TokenBasedRememberMeServices2.java
  core/src/main/java/hudson/util/UnbufferedBase64InputStream.java
  core/src/main/java/jenkins/model/identity/IdentityRootAction.java
  core/src/main/java/jenkins/security/RSAConfidentialKey.java
  core/src/main/java/jenkins/security/RSADigitalSignatureConfidentialKey.java
  core/src/test/java/jenkins/security/RSADigitalSignatureConfidentialKeyTest.java
  test/src/test/java/hudson/security/TokenBasedRememberMeServices2Test.java
Labels: internal, ready-for-merge

#4183 Correct a syntax error in the message in Russian
  core/src/main/resources/hudson/util/HudsonIsLoading/index_ru.properties
Labels: localization, ready-for-merge

#4185 [JENKINS-59164] - `Functions#toEmailSafeString()` was not really sanitizing the email string
  core/src/main/java/hudson/Functions.java
Labels: bug, ready-for-merge

#4184 Remove slave from french messages and correct one accent
  core/src/main/resources/hudson/model/Messages_fr.properties
Labels: localization

#4167 Update Windows Service Wrapper from 2.2.0 to 2.3.0 to pick up fixes and improvements
  core/pom.xml
  war/pom.xml
Labels: ready-for-merge, rfe

#4188 [JENKINS-59167] Correction of rootUrl in RSS/Atom feeds
  core/src/main/java/hudson/model/RSS.java
  core/src/main/resources/hudson/atom.jelly
  core/src/main/resources/hudson/rss20.jelly
  test/src/test/java/hudson/model/RSSTest.java
Labels: ready-for-merge, regression-fix

#4190 Fix annotations and remove unused imports
  core/src/main/java/hudson/DNSMultiCast.java
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/LocalPluginManager.java
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/model/AbstractItem.java
  core/src/main/java/hudson/model/BallColor.java
  core/src/main/java/hudson/model/DependencyGraph.java
  core/src/main/java/hudson/model/ItemGroupMixIn.java
  core/src/main/java/hudson/model/Items.java
  core/src/main/java/hudson/model/ViewGroupMixIn.java
  core/src/main/java/hudson/model/queue/AbstractQueueSorterImpl.java
  core/src/main/java/hudson/model/queue/QueueSorter.java
  core/src/main/java/hudson/security/csrf/DefaultCrumbIssuer.java
  core/src/main/java/hudson/tasks/BuildTrigger.java
  core/src/main/java/hudson/tasks/Fingerprinter.java
  core/src/main/java/hudson/tasks/Publisher.java
  core/src/main/java/hudson/triggers/SlowTriggerAdminMonitor.java
  core/src/main/java/hudson/triggers/Trigger.java
  core/src/main/java/hudson/util/MultipartFormDataParser.java
  core/src/main/java/hudson/util/NoOverlapCategoryAxis.java
  core/src/main/java/hudson/views/MyViewsTabBar.java
  core/src/main/java/hudson/views/ViewsTabBar.java
  core/src/main/java/jenkins/model/ParameterizedJobMixIn.java
  core/src/main/java/jenkins/slaves/DefaultJnlpSlaveReceiver.java
  core/src/main/java/jenkins/slaves/restarter/JnlpSlaveRestarterInstaller.java
  core/src/main/java/jenkins/telemetry/impl/java11/MissingClassEvent.java
  core/src/main/java/jenkins/widgets/HistoryPageFilter.java
  core/src/test/java/hudson/PluginManagerTest.java
  core/src/test/java/hudson/XmlFileTest.java
  core/src/test/java/hudson/cli/ListJobsCommandTest.java
  core/src/test/java/hudson/model/FingerprintCleanupThreadTest.java
  core/src/test/java/hudson/model/JobTest.java
  core/src/test/java/hudson/model/LoadStatisticsTest.java
  core/src/test/java/hudson/model/TaskActionTest.java
  core/src/test/java/hudson/util/AtomicFileWriterTest.java
  core/src/test/java/hudson/util/FileChannelWriterTest.java
  core/src/test/java/hudson/util/io/TarArchiverTest.java
  core/src/test/java/hudson/util/io/ZipArchiverTest.java
  core/src/test/java/jenkins/util/TimeDurationTest.java
  core/src/test/java/jenkins/util/TimerTest.java
Labels: ready-for-merge

#4193 Upgrade to 3.35 version of Remoting.
  pom.xml
Labels: ready-for-merge

#4187 Fix Fingerprinter.Recording typo in german translation
  core/src/main/resources/hudson/tasks/Messages_de.properties
Labels: localization, ready-for-merge

#4177 Fixed deprecated warnings without changing behaviour
  cli/src/main/java/hudson/cli/CLI.java
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/util/DoubleLaunchChecker.java
  core/src/main/java/jenkins/install/InstallUtil.java
  core/src/main/java/jenkins/security/s2m/AdminWhitelistRule.java
  core/src/test/java/hudson/LauncherTest.java
  core/src/test/java/hudson/PluginWrapperTest.java
  core/src/test/java/hudson/model/ListViewTest.java
  core/src/test/java/hudson/slaves/ChannelPingerTest.java
  core/src/test/java/hudson/slaves/DelegatingComputerLauncherTest.java
  core/src/test/java/hudson/slaves/NodeListTest.java
  core/src/test/java/hudson/util/AtomicFileWriterTest.java
  core/src/test/java/hudson/util/SecretRewriterTest.java
  core/src/test/java/hudson/util/TextFileTest.java
  core/src/test/java/jenkins/model/JenkinsGetRootUrlTest.java
  core/src/test/java/jenkins/model/NewViewLinkTest.java
  core/src/test/java/jenkins/model/RunIdMigratorTest.java
  core/src/test/java/jenkins/model/lazy/FakeMap.java
  core/src/test/java/jenkins/security/DefaultConfidentialStoreTest.java
  core/src/test/java/jenkins/security/apitoken/ApiTokenStatsTest.java
  core/src/test/java/jenkins/triggers/SCMTriggerItemTest.java
Labels: internal, ready-for-merge, skip-changelog

#4170 [JENKINS-59017] disable ForceSetupWizardFilter if setup complete
  core/src/main/java/jenkins/install/SetupWizard.java
Labels: bug, ready-for-merge, web-ui

#4150 [JENKINS-48578] BOM for Jenkins dependencies consumable by plugins
  bom/pom.xml
  cli/pom.xml
  core/pom.xml
  pom.xml
  test-pom/pom.xml
  war/pom.xml
Labels: major-rfe, ready-for-merge

#4203 [JENKINS-59383] Fix the DiskMonitorSpaceDescriptor toString() message when the monitor alert is not triggered
  core/src/main/java/hudson/node_monitors/DiskSpaceMonitorDescriptor.java
  core/src/main/resources/hudson/node_monitors/Messages.properties
  test/src/test/java/hudson/node_monitors/DiskSpaceMonitorDescriptorTest.java
Labels: bug, ready-for-merge

#4199 Replace internal search implementation in SortedIntList with java.util.Arrays.binarySearch
  core/src/main/java/jenkins/model/lazy/SortedIntList.java
Labels: internal, ready-for-merge

#4198 [JENKINS-59393] - Fix malformed XML in Atom and RSS 2.0 feeds and [JENKINS-59231] - Improve test coverage on the RSS feature
  core/src/main/java/hudson/model/RSS.java
  test/src/test/java/hudson/model/RSSTest.java
Labels: bug, ready-for-merge

#4138 [JENKINS-58779] LogRotator stops, if build was deleted externally
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/tasks/LogRotator.java
Labels: bug, ready-for-merge

#4200 [JENKINS-36720] - Spotbugs dodgy code
  core/src/main/java/hudson/model/AbstractProject.java
  core/src/main/java/hudson/model/Job.java
  core/src/main/java/hudson/model/View.java
  core/src/main/java/hudson/tasks/BuildStepCompatibilityLayer.java
  core/src/main/java/hudson/tools/DownloadFromUrlInstaller.java
Labels: ready-for-merge, skip-changelog

#4201 [JENKINS-36720] - Add missing null checks in `FilePath#installIfNecessaryFrom()` logging
  core/src/main/java/hudson/FilePath.java
  core/src/test/java/hudson/FilePathTest.java
Labels: internal, ready-for-merge

#4202 [JENKINS-36720] - Suppress Spotbugs DM_EXIT warnings in methods where EXIT is intended
  core/src/main/java/hudson/lifecycle/ExitLifecycle.java
  core/src/main/java/hudson/lifecycle/SolarisSMFLifecycle.java
  core/src/main/java/hudson/lifecycle/WindowsInstallerLink.java
  core/src/main/java/jenkins/model/Jenkins.java
Labels: internal, ready-for-merge, skip-changelog

#4204 [JENKINS-59406] Added missing null check and associated test
  core/src/main/java/hudson/Util.java
  core/src/test/java/hudson/UtilTest.java
Labels: ready-for-merge, regression-fix

#4205 [JENKINS-26008] Add an option to disable gzip compression for StandardArtifactManager
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/jenkins/model/StandardArtifactManager.java
  test/src/test/java/hudson/tasks/ArtifactArchiverTest.java
Labels: ready-for-merge, rfe

#4210 Remove unused imports
  core/src/main/java/hudson/scheduler/Hash.java
  core/src/main/java/hudson/util/jna/RegistryKey.java
  core/src/main/java/jenkins/util/MarkFindingOutputStream.java
  core/src/test/java/hudson/util/XStream2Test.java
  test/src/test/java/hudson/bugs/JnlpAccessWithSecuredHudsonTest.java
  test/src/test/java/hudson/cli/AddJobToViewCommandTest.java
  test/src/test/java/hudson/cli/CancelQuietDownCommandTest.java
  test/src/test/java/hudson/cli/ConnectNodeCommandTest.java
  test/src/test/java/hudson/cli/ConsoleCommandTest.java
  test/src/test/java/hudson/cli/RemoveJobFromViewCommandTest.java
  test/src/test/java/hudson/cli/RunRangeCommand2Test.java
  test/src/test/java/hudson/cli/SetBuildDescriptionCommandTest.java
  test/src/test/java/hudson/model/CauseTest.java
  test/src/test/java/hudson/model/DescriptorVisibilityFilterTest.java
  test/src/test/java/hudson/model/FileParameterValueTest.java
  test/src/test/java/hudson/model/FreeStyleProjectTest.java
  test/src/test/java/hudson/model/GetEnvironmentOutsideBuildTest.java
  test/src/test/java/hudson/model/ItemsTest.java
  test/src/test/java/hudson/model/PasswordParameterDefinitionTest.java
  test/src/test/java/hudson/model/ProjectTest.java
  test/src/test/java/hudson/model/QueueTest.java
  test/src/test/java/hudson/model/RSSTest.java
  test/src/test/java/hudson/model/UserPropertyTest.java
  test/src/test/java/hudson/model/UserTest.java
  test/src/test/java/hudson/model/ViewTest.java
  test/src/test/java/hudson/security/HudsonPrivateSecurityRealmTest.java
  test/src/test/java/hudson/security/LoginTest.java
  test/src/test/java/hudson/slaves/CloudTest.java
  test/src/test/java/hudson/slaves/EnvironmentVariableNodePropertyTest.java
  test/src/test/java/hudson/slaves/JNLPLauncherTest.java
  test/src/test/java/hudson/slaves/NodeParallelTest.java
  test/src/test/java/hudson/slaves/PingThreadTest.java
  test/src/test/java/hudson/slaves/SlaveComputerTest.java
  test/src/test/java/hudson/tools/InstallerTranslatorTest.java
  test/src/test/java/jenkins/install/SetupWizardTest.java
  test/src/test/java/jenkins/model/JenkinsTest.java
  test/src/test/java/jenkins/model/identity/IdentityRootActionTest.java
  test/src/test/java/jenkins/model/lazy/LazyBuildMixInTest.java
  test/src/test/java/jenkins/security/ApiCrumbExclusionTest.java
  test/src/test/java/jenkins/security/BasicHeaderProcessorTest.java
  test/src/test/java/jenkins/security/ClassFilterImplTest.java
  test/src/test/java/jenkins/security/LastGrantedAuthoritiesPropertyTest.java
  test/src/test/java/jenkins/security/Security857Test.java
  test/src/test/java/jenkins/security/UserDetailsCacheTest.java
  test/src/test/java/jenkins/security/seed/UserSeedPropertyTest.java
  test/src/test/java/jenkins/security/stapler/DoActionFilterTest.java
  test/src/test/java/jenkins/security/stapler/DynamicTest.java
  test/src/test/java/jenkins/slaves/RemotingVersionInfoTest.java
  test/src/test/java/jenkins/telemetry/TelemetryTest.java
  test/src/test/java/jenkins/util/JenkinsJVMRealTest.java
  test/src/test/java/lib/form/ExpandableTextboxTest.java
  test/src/test/java/lib/form/PasswordTest.java
  test/src/test/java/lib/form/RepeatableTest.java
  test/src/test/java/lib/form/ValidateButtonSEC1327Test.java
  test/src/test/java/org/kohsuke/stapler/MockStaplerRequestBuilder.java
Labels: internal, ready-for-merge, skip-changelog

#4219 JENKINS-59505 - Fix typo in plugin setup wizard
  core/src/main/resources/jenkins/install/pluginSetupWizard.properties
Labels: bug, ready-for-merge

#4213 removed powermock dependency because it was not used in cli
  cli/pom.xml
Labels: internal, ready-for-merge, skip-changelog

#4222 JENKINS-59513 - Fixed defunct hyperlink in PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready-for-merge, skip-changelog

#4218 Unignore tests that aren't failing on stable-2.190
  test/src/test/java/hudson/model/RSSTest.java
Labels: internal, skip-changelog

#4209 [JENKINS-19760], [JENKINS-31209] Stop limiting build description in build list view to 100 characters
  core/src/main/java/hudson/model/Run.java
  core/src/main/resources/hudson/widgets/HistoryWidget/entry.jelly
Labels: ready-for-merge, rfe, web-ui

#4221 Update commons-compress from 1.10 to 1.19
  core/pom.xml
Labels: ready-for-merge, rfe

#4217 Remove sites.jelly (dead code)
  core/src/main/resources/hudson/PluginManager/sites.jelly
  core/src/main/resources/hudson/PluginManager/sites_bg.properties
  core/src/main/resources/hudson/PluginManager/sites_da.properties
  core/src/main/resources/hudson/PluginManager/sites_de.properties
  core/src/main/resources/hudson/PluginManager/sites_es.properties
  core/src/main/resources/hudson/PluginManager/sites_it.properties
  core/src/main/resources/hudson/PluginManager/sites_ja.properties
  core/src/main/resources/hudson/PluginManager/sites_pt_BR.properties
  core/src/main/resources/hudson/PluginManager/sites_sr.properties
  core/src/main/resources/hudson/PluginManager/sites_zh_TW.properties
  core/src/main/resources/hudson/PluginManager/tabBar.jelly
Labels: ready-for-merge, skip-changelog

#4214 Remove redundant String.format() and merge array creation with addAll()
  core/src/main/java/hudson/Main.java
  core/src/main/java/hudson/cli/ConnectNodeCommand.java
  core/src/main/java/hudson/cli/DeleteJobCommand.java
  core/src/main/java/hudson/cli/DeleteNodeCommand.java
  core/src/main/java/hudson/cli/DeleteViewCommand.java
  core/src/main/java/hudson/cli/DisconnectNodeCommand.java
  core/src/main/java/hudson/cli/ReloadJobCommand.java
  core/src/main/java/jenkins/cli/StopBuildsCommand.java
  core/src/main/java/jenkins/model/lazy/BuildReferenceMapAdapter.java
Labels: internal, ready-for-merge, skip-changelog

#4226 Improve logging for Computer.getLogDir failures
  core/src/main/java/hudson/model/Computer.java
Labels: ready-for-merge, rfe

#4223 [JENKINS-59514] Use POST instead of RequirePOST for form submissions
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/logging/LogRecorder.java
  core/src/main/java/hudson/model/AbstractProject.java
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/model/ComputerSet.java
  core/src/main/java/hudson/model/Job.java
  core/src/main/java/hudson/model/ListView.java
  core/src/main/java/hudson/model/MyViewsProperty.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/model/TreeView.java
  core/src/main/java/hudson/model/User.java
  core/src/main/java/hudson/model/View.java
  core/src/main/java/hudson/model/labels/LabelAtom.java
  core/src/main/java/hudson/security/GlobalSecurityConfiguration.java
  core/src/main/java/jenkins/install/SetupWizard.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/tools/GlobalToolConfiguration.java
  test/src/test/java/jenkins/security/RedactSecretJsonInErrorMessageSanitizerHtmlTest.java
Labels: ready-for-merge, rfe

#4208 Update the minimum required Remoting version to 3.14
  core/src/main/java/hudson/Launcher.java
  pom.xml
Labels: major-rfe, ready-for-merge

#4228 [JENKINS-56809] LAST_COMPLETED_BUILD should be a PeepholePermalink
  core/src/main/java/hudson/model/Job.java
  core/src/main/java/hudson/model/PermalinkProjectAction.java
  test/src/test/java/jenkins/model/PeepholePermalinkTest.java
Labels: bug, ready-for-merge

#4230 Update bundled versions of Ant, PAM Authentication, Mailer, and Script Security plugins to include latest security fixes for the rare cases they're installed from bundled versions
  war/pom.xml
Labels: ready-for-merge, rfe

#4227 Introduce new hudson.TcpSlaveAgentListener.getAdvertisedHost() method
  core/src/main/java/hudson/TcpSlaveAgentListener.java
Labels: internal, ready-for-merge

#4229 Update jfreechart from 1.0.9 to 1.0.19 to pick-up recent improvements and bugfixes
  core/pom.xml
Labels: ready-for-merge, rfe

#4206 Extracted duplicate code
  cli/src/main/java/hudson/cli/PrivateKeyProvider.java
  cli/src/test/java/hudson/cli/PrivateKeyProviderTest.java
Labels: ready-for-merge, skip-changelog

#4195 [JENKINS-59283] - Use different icons for computers that are temporarily offline
  core/src/main/java/hudson/model/Computer.java
  war/images/computer-user-offline.svg
  war/src/main/webapp/images/16x16/computer-user-offline.png
  war/src/main/webapp/images/24x24/computer-user-offline.png
  war/src/main/webapp/images/32x32/computer-user-offline.png
  war/src/main/webapp/images/48x48/computer-user-offline.png
Labels: ready-for-merge, rfe, web-ui

#4171 [JENKINS-58993] do not allow save() to be called before we have loaded the config
  core/src/main/java/jenkins/model/Jenkins.java
Labels: major-bug
