Repository jenkinsci/jenkins, pull requests merged in 2019-04, with the labels that each got.

#3946 Add localization support for default token name
  core/src/main/java/jenkins/security/ApiTokenProperty.java
  core/src/main/resources/jenkins/security/Messages.properties
  core/src/main/resources/jenkins/security/Messages_zh_CN.properties
Labels: ready-for-merge

#3942 Update help-artifacts.html
  core/src/main/resources/hudson/tasks/ArtifactArchiver/help-artifacts.html
Labels: ready-for-merge

#3938 [JENKINS-50095] Add X-Remoting-Minimum-Version header in /tcpSlaveAgentListener
  core/src/main/java/hudson/TcpSlaveAgentListener.java
  core/src/main/resources/hudson/TcpSlaveAgentListener/index.jelly
Labels: ready-for-merge

#3930 Revert switching to array utils
  core/src/main/java/jenkins/util/TreeString.java
Labels: regression-fix

#3967 Add f:secretTextarea UI analogous to f:password
  core/src/main/resources/lib/form/secretTextarea.jelly
  core/src/main/resources/lib/form/secretTextarea.properties
  core/src/main/resources/lib/form/secretTextarea/secret.css
  core/src/main/resources/lib/form/secretTextarea/secret.js
  test/src/test/java/lib/form/SecretTextareaTest.java
  test/src/test/resources/lib/form/SecretTextareaTest/TestBuilder/config.jelly
Labels: ready-for-merge

#3960 JENKINS-56856 - URL Encode data before submitting it to the endpoint just incase there's bad data in it
  war/src/main/js/util/jenkins.js
Labels: web-ui

#3425 [JENKINS-56931] handle absolute paths correctly when unzipping
  core/src/main/java/hudson/FilePath.java
  test/src/test/java/hudson/FilePathTest.java
  test/src/test/resources/hudson/FilePathTest/zip_with_relative/zip-rel-one-up.zip
  test/src/test/resources/hudson/FilePathTest/zip_with_relative/zip-slip-win.zip
  test/src/test/resources/hudson/FilePathTest/zip_with_relative/zip-slip.zip
  test/src/test/resources/hudson/FilePathTest/zip_with_relative/zip-with-folder.zip
Labels: ready-for-merge

#3944 [SECURITY-904] Fold tests back into normal files
  core/src/test/java/hudson/FilePathSEC904Test.java
  core/src/test/java/hudson/FilePathTest.java
  core/src/test/java/hudson/UtilSEC904Test.java
  core/src/test/java/hudson/UtilTest.java
  core/src/test/java/jenkins/util/VirtualFileSEC904Test.java
  core/src/test/java/jenkins/util/VirtualFileTest.java
  test/src/test/java/hudson/model/DirectoryBrowserSupportSEC904Test.java
  test/src/test/java/hudson/model/DirectoryBrowserSupportTest.java
  test/src/test/resources/hudson/model/DirectoryBrowserSupportTest/insideWorkspaceStructure.bat
  test/src/test/resources/hudson/model/DirectoryBrowserSupportTest/insideWorkspaceStructure.sh
  test/src/test/resources/hudson/model/DirectoryBrowserSupportTest/outsideWorkspaceStructure.bat
  test/src/test/resources/hudson/model/DirectoryBrowserSupportTest/outsideWorkspaceStructure.sh
  test/src/test/resources/hudson/model/DirectoryBrowserSupportTest/outsideWorkspaceStructureWithJunctions.bat
Labels: ready-for-merge

#2691 [FIX JENKINS-40750] Remove cc.xml from core
  core/src/main/java/hudson/Functions.java
  core/src/main/resources/hudson/model/View/builds.jelly
  core/src/main/resources/hudson/model/View/cc.xml.jelly
Labels: ready-for-merge

#3900 [JENKINS-56166] Remove hudson.util.ssh.SFTPClient classs from core
  core/src/main/java/hudson/util/ssh/SFTPClient.java
Labels: ready-for-merge

#3971 [simple] Remove debug timeout that was forgotten
  test/src/test/java/jenkins/security/seed/UserSeedChangeListenerTest.java
Labels: ready-for-merge

#3955 [JENKINS-50504] WorkspaceList.inUse should be keyed by String not FilePath so leases survive agent reconnections
  core/src/main/java/hudson/Launcher.java
  core/src/main/java/hudson/slaves/WorkspaceList.java
  test/.gitignore
Labels: ready-for-merge

#3729 [JEP-216] Support loading localizer and webapp resources from any plugin
  core/pom.xml
  core/src/filter/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message.properties
  core/src/main/java/jenkins/MetaLocaleDrivenResourceProvider.java
  core/src/main/java/jenkins/PluginLocaleDrivenResourceProvider.java
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message.jelly
Labels: ready-for-merge

#3977 [JENKINS-56733] Add a button to copy new token
  core/src/main/resources/jenkins/security/ApiTokenProperty/config.jelly
  core/src/main/resources/jenkins/security/ApiTokenProperty/config.properties
  core/src/main/resources/jenkins/security/ApiTokenProperty/resources.css
  core/src/main/resources/jenkins/security/ApiTokenProperty/resources.js
  core/src/main/resources/lib/layout/copyButton.jelly
  core/src/main/resources/lib/layout/copyButton/copyButton.css
Labels: ready-for-merge, web-ui

#3961 Adjusted TaskListener flushing in remote code
  core/src/main/java/hudson/Launcher.java
  core/src/main/java/hudson/util/StreamCopyThread.java
  core/src/main/java/hudson/util/StreamTaskListener.java
  core/src/main/java/jenkins/util/SystemProperties.java
  test-pom/pom.xml
  test/src/test/java/hudson/util/ArgumentListBuilder2Test.java
Labels: ready-for-merge

#3948 Update commons-beanutils to latest version
  core/pom.xml
Labels: ready-for-merge

#3973 [JENKINS-55292] Remove MailCommand localization from core
  core/src/main/resources/hudson/cli/Messages.properties
  core/src/main/resources/hudson/cli/Messages_bg.properties
  core/src/main/resources/hudson/cli/Messages_de.properties
  core/src/main/resources/hudson/cli/Messages_es.properties
  core/src/main/resources/hudson/cli/Messages_it.properties
  core/src/main/resources/hudson/cli/Messages_ja.properties
  core/src/main/resources/hudson/cli/Messages_lt.properties
  core/src/main/resources/hudson/cli/Messages_pt_BR.properties
  core/src/main/resources/hudson/cli/Messages_sr.properties
  core/src/main/resources/hudson/cli/Messages_zh_TW.properties
  test-pom/pom.xml
Labels: ready-for-merge

#3925 [JENKINS-56403]: Renaming an agent retains old agent configuration
  core/src/main/java/jenkins/model/Nodes.java
  test/src/test/java/jenkins/model/NodesTest.java
Labels: ready-for-merge

#3993 Removing forgotten mention of now-deleted -remoting CLI option
  cli/src/main/resources/hudson/cli/client/Messages.properties
Labels: ready-for-merge

#2831 [JENKINS-43322] Nested views should be also searchable by name
  core/src/main/java/hudson/model/TreeView.java
  core/src/main/java/hudson/model/ViewGroup.java
  core/src/main/java/hudson/model/ViewGroupMixIn.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/test/java/hudson/model/ViewTest.java
  test/src/test/java/hudson/model/ViewTest.java
Labels: needs-more-reviews, ready-for-merge

#3990 Bump to more recent tip of ATH
  essentials.yml
Labels: ready-for-merge

#3980 [JENKINS-47896] SerializableOnlyOverRemoting
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/model/TaskListener.java
  core/src/main/java/hudson/util/ProcessTree.java
Labels: ready-for-merge

#3986 Making ConfidentialKey instances safe to keep in static fields even across JenkinsRule starts
  core/src/main/java/hudson/util/Secret.java
  core/src/main/java/jenkins/security/CryptoConfidentialKey.java
  core/src/main/java/jenkins/security/HMACConfidentialKey.java
  core/src/main/java/jenkins/security/HexStringConfidentialKey.java
  core/src/main/java/jenkins/security/RSAConfidentialKey.java
  test/src/test/java/hudson/util/SecretCompatTest.java
Labels: ready-for-merge

#3987 [JENKINS-57071] Fixing problems affecting Linux agent installer modules
  core/src/main/java/hudson/os/SU.java
  core/src/main/java/jenkins/security/ChannelConfigurator.java
Labels: ready-for-merge

#3873 [JENKINS-55829] New getter method in AbstractCIBase
  core/src/main/java/hudson/model/AbstractCIBase.java
  core/src/main/java/hudson/model/AdministrativeMonitor.java
Labels: ready-for-merge

#3984 Make ${port} be honored by `mvn -f war hudson-dev:run`
  war/pom.xml
Labels: ready-for-merge

#3985 [JENKINS-56477] Fix to allow selecting compatible-only updates for plugins
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/resources/hudson/PluginManager/_table.js
  core/src/main/resources/hudson/PluginManager/index.jelly
  core/src/main/resources/hudson/PluginManager/table.jelly
  test/src/test/java/hudson/model/UpdateSiteTest.java
Labels: ready-for-merge

#3995 Add section for agent to master configuration
  core/src/main/resources/jenkins/security/s2m/MasterKillSwitchConfiguration/config.groovy
Labels: ready-for-merge
