Repository jenkinsci/jenkins, pull requests merged in 2020-01, with the labels that each got.

#4393 [JENKINS-60449] Attempt to fix an odd case of OptionalExtension blowing up Jenkins
  core/src/main/java/hudson/ExtensionFinder.java
  core/src/main/java/hudson/PluginManager.java
  test/src/test/java/hudson/PluginManagerTest.java
  test/src/test/resources/plugins/optional-depender-0.0.2.hpi
  test/src/test/resources/plugins/variant.hpi
Labels: bug, ready-for-merge

#4254 IntelliJ/Java: Duplicate declaration -> AntClassLoader.getUrl
  core/src/main/java/jenkins/util/AntClassLoader.java
  core/src/main/java/jenkins/util/AntWithFindResourceClassLoader.java
Labels: internal, plugin-api-changes, ready-for-merge

#4212 Return error when invalid string is passed as a Run status CLI argument
  core/src/main/java/hudson/ProxyConfiguration.java
  core/src/main/java/hudson/console/ConsoleNote.java
  core/src/main/java/hudson/model/Cause.java
  core/src/main/java/hudson/model/Items.java
  core/src/main/java/hudson/model/Result.java
Labels: bug, internal, ready-for-merge

#4413 [JENKINS-60625] Prevent Jenkins page rendering from being blocked when the update center data parsing is in progress
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/java/jenkins/security/UpdateSiteWarningsMonitor.java
Labels: bug, plugin-api-changes, ready-for-merge

#4408 Fixed Spotbugs Switch related issues and added Suppresses
  core/src/main/java/hudson/Util.java
  core/src/main/java/hudson/cli/DisablePluginCommand.java
  core/src/main/java/hudson/model/Queue.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/util/jna/SHELLEXECUTEINFO.java
Labels: ready-for-merge, skip-changelog

#4417 [JENKINS-60449] Prevent endless recursion in SezpozModule.resolve
  core/src/main/java/hudson/ExtensionFinder.java
  test/src/test/java/hudson/ExtensionFinderTest.java
Labels: skip-changelog

#4419 [JENKINS-60641, JENKINS-60644] incorrectly converted AntClassLoader.loadResource to a Java 5 for-loop
  core/src/main/java/jenkins/util/AntClassLoader.java
  test/src/test/java/jenkins/util/AntClassLoaderTest.java
  test/src/test/resources/plugins/loads-resource.jpi
Labels: major-bug, ready-for-merge, regression-fix

#4415 [JENKINS-40228] Remove Enable Security checkbox in the Global Security configuration (follow-up)
  core/src/main/java/hudson/security/GlobalSecurityConfiguration.java
  core/src/main/java/hudson/security/SecurityRealm.java
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/index.groovy
  core/src/main/resources/hudson/security/Messages.properties
  essentials.yml
Labels: major-rfe, ready-for-merge

#4418 Fix typos & spelling in Javadoc and WebUI
  core/src/main/java/hudson/cli/DisablePluginCommand.java
  core/src/main/java/hudson/model/AbstractProject.java
  core/src/main/java/hudson/model/CheckPoint.java
  core/src/main/java/hudson/model/Descriptor.java
  core/src/main/java/hudson/model/Job.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/model/RunAction.java
  core/src/main/java/hudson/model/Slave.java
  core/src/main/java/hudson/model/ViewGroupMixIn.java
  core/src/main/java/hudson/os/WindowsUtil.java
  core/src/main/java/hudson/security/SecurityRealm.java
  core/src/main/java/hudson/slaves/ComputerLauncher.java
  core/src/main/java/hudson/triggers/Trigger.java
  core/src/main/java/hudson/triggers/Triggers.java
  core/src/main/java/hudson/util/ListBoxModel.java
  core/src/main/java/hudson/util/MultipartFormDataParser.java
  core/src/main/java/jenkins/model/DirectlyModifiableTopLevelItemGroup.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/model/SimplePageDecorator.java
  core/src/main/java/jenkins/org/apache/commons/validator/routines/UrlValidator.java
  core/src/main/java/jenkins/security/BasicHeaderProcessor.java
  core/src/main/java/jenkins/security/MasterToSlaveCallable.java
  core/src/main/java/jenkins/util/AntClassLoader.java
  core/src/main/java/jenkins/util/java/JavaUtils.java
  core/src/main/resources/hudson/scheduler/Messages_de.properties
  core/src/main/resources/hudson/tasks/ArtifactArchiver/help_de.html
  core/src/main/resources/hudson/tasks/Fingerprinter/help_de.html
  core/src/main/resources/hudson/util/HudsonIsLoading/index.jelly
  core/src/main/resources/hudson/util/HudsonIsRestarting/index.jelly
  core/src/main/resources/jenkins/install/SetupWizard/authenticate-security-token_de.properties
  core/src/main/resources/jenkins/model/Jenkins/login.jelly
  core/src/test/java/hudson/model/AbstractItemTest.java
  core/src/test/java/hudson/model/EnvironmentContributingActionTest.java
  core/src/test/java/hudson/model/FingerprintCleanupThreadTest.java
  core/src/test/java/jenkins/model/lazy/FakeMapBuilder.java
  test/src/test/java/hudson/cli/ConsoleCommandTest.java
  test/src/test/java/hudson/model/ApiSecurity1129Test.java
  test/src/test/java/hudson/model/BuildAuthorizationTokenTest.java
  test/src/test/java/hudson/model/ExecutorTest.java
  test/src/test/java/hudson/model/NodeTest.java
  test/src/test/java/hudson/security/HudsonPrivateSecurityRealmTest.java
  test/src/test/java/hudson/slaves/JNLPLauncherTest.java
  test/src/test/java/jenkins/install/InstallStateTest.java
Labels: bug, ready-for-merge

#4414 [JENKINS-60634] Define $WORKSPACE_TMP for (non-Pipeline) builds
  core/src/main/java/hudson/model/AbstractBuild.java
  core/src/main/resources/jenkins/model/CoreEnvironmentContributor/buildEnv.groovy
  core/src/main/resources/jenkins/model/CoreEnvironmentContributor/buildEnv.properties
  test/src/test/java/hudson/model/AbstractBuildTest.java
Labels: ready-for-merge, rfe

#4420 Fix minor issues in localization files (escaping, incomplete entries, etc.)
  cli/src/main/resources/hudson/cli/client/Messages_da.properties
  core/src/main/resources/_cli_it.properties
  core/src/main/resources/hudson/diagnosis/OldDataMonitor/manage_pt.properties
  core/src/main/resources/hudson/fsp/Messages_da.properties
  core/src/main/resources/hudson/model/AbstractItem/noWorkspace_ar.properties
  core/src/main/resources/hudson/model/AbstractItem/noWorkspace_ca.properties
  core/src/main/resources/hudson/model/AbstractItem/noWorkspace_es.properties
  core/src/main/resources/hudson/model/AbstractItem/noWorkspace_et.properties
  core/src/main/resources/hudson/model/AbstractItem/noWorkspace_ko.properties
  core/src/main/resources/hudson/model/AbstractItem/noWorkspace_lt.properties
  core/src/main/resources/hudson/model/AbstractItem/noWorkspace_lv.properties
  core/src/main/resources/hudson/model/AbstractItem/noWorkspace_pt_PT.properties
  core/src/main/resources/hudson/model/AbstractItem/noWorkspace_sk.properties
  core/src/main/resources/hudson/model/AbstractProject/wipeOutWorkspaceBlocked_fr.properties
  core/src/main/resources/hudson/model/AllView/newViewDetail_da.properties
  core/src/main/resources/hudson/model/BuildAuthorizationToken/config_ko.properties
  core/src/main/resources/hudson/model/Computer/index_cs.properties
  core/src/main/resources/hudson/model/Computer/index_he.properties
  core/src/main/resources/hudson/model/Computer/index_ja.properties
  core/src/main/resources/hudson/model/Computer/index_ko.properties
  core/src/main/resources/hudson/model/Computer/index_lv.properties
  core/src/main/resources/hudson/model/Computer/index_ru.properties
  core/src/main/resources/hudson/model/Computer/index_sk.properties
  core/src/main/resources/hudson/model/Computer/index_sv_SE.properties
  core/src/main/resources/hudson/model/Messages_bg.properties
  core/src/main/resources/hudson/model/Messages_ja.properties
  core/src/main/resources/hudson/model/Messages_zh_TW.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/index_tr.properties
  core/src/main/resources/hudson/slaves/JNLPLauncher/main_fr.properties
  core/src/main/resources/hudson/slaves/JNLPLauncher/main_ru.properties
  core/src/main/resources/hudson/util/InsufficientPermissionDetected/index_pt_BR.properties
  core/src/main/resources/hudson/win32errors.properties
  core/src/main/resources/hudson/win32errors_es.properties
  core/src/main/resources/hudson/win32errors_it.properties
  core/src/main/resources/jenkins/management/Messages_nb_NO.properties
  core/src/main/resources/jenkins/model/Jenkins/fingerprintCheck_bg.properties
  core/src/main/resources/jenkins/model/Jenkins/fingerprintCheck_cs.properties
  core/src/main/resources/jenkins/model/Jenkins/fingerprintCheck_da.properties
  core/src/main/resources/jenkins/model/Jenkins/projectRelationship-help_et.properties
  core/src/main/resources/jenkins/model/Messages_da.properties
  core/src/main/resources/jenkins/security/s2m/MasterKillSwitchWarning/message_pt_BR.properties
  core/src/main/resources/lib/form/expandableTextbox_pt_BR.properties
  core/src/main/resources/lib/hudson/buildProgressBar_ko.properties
  core/src/main/resources/lib/hudson/buildProgressBar_sk.properties
  core/src/main/resources/lib/hudson/buildProgressBar_sl.properties
  core/src/main/resources/lib/hudson/scriptConsole_ko.properties
  core/src/main/resources/lib/hudson/scriptConsole_nb_NO.properties
  war/src/realm.properties
Labels: bug, localization, ready-for-merge

#4404 [JENKINS-60579] - Allow the usage of DescriptorVisibilityFilter to filter View properties on UI.
  core/src/main/java/hudson/model/View.java
  core/src/main/resources/hudson/model/View/configure.jelly
  test/src/test/java/hudson/model/ViewDescriptorTest.java
Labels: plugin-api-changes, ready-for-merge, rfe

#4387 [JENKINS-60381] Remove old, deprecated agent protocols.
  core/src/main/java/hudson/slaves/SlaveComputer.java
  core/src/main/java/jenkins/security/ConfidentialKey.java
  core/src/main/java/jenkins/slaves/DefaultJnlpSlaveReceiver.java
  core/src/main/java/jenkins/slaves/DeprecatedAgentProtocolMonitor.java
  core/src/main/java/jenkins/slaves/EncryptedSlaveAgentJnlpFile.java
  core/src/main/java/jenkins/slaves/JnlpAgentReceiver.java
  core/src/main/java/jenkins/slaves/JnlpSlaveAgentProtocol.java
  core/src/main/java/jenkins/slaves/JnlpSlaveAgentProtocol2.java
  core/src/main/java/jenkins/slaves/JnlpSlaveAgentProtocol3.java
  core/src/main/resources/jenkins/slaves/DeprecatedAgentProtocolMonitor/message.jelly
  core/src/main/resources/jenkins/slaves/DeprecatedAgentProtocolMonitor/message.properties
  core/src/main/resources/jenkins/slaves/DeprecatedAgentProtocolMonitor/message_bg.properties
  core/src/main/resources/jenkins/slaves/DeprecatedAgentProtocolMonitor/message_it.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol/deprecationCause.jelly
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol/deprecationCause.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol/deprecationCause_bg.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol/deprecationCause_it.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol/description.jelly
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol/description.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol/description_bg.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol/description_de.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol/description_it.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol/description_sr.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol2/deprecationCause.jelly
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol2/deprecationCause.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol2/deprecationCause_bg.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol2/deprecationCause_it.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol2/description.jelly
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol2/description.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol2/description_bg.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol2/description_de.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol2/description_it.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol2/description_sr.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol3/deprecationCause.jelly
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol3/deprecationCause.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol3/deprecationCause_bg.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol3/deprecationCause_it.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol3/description.jelly
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol3/description.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol3/description_bg.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol3/description_de.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol3/description_it.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol3/description_sr.properties
  pom.xml
  test/src/test/java/jenkins/AgentProtocolTest.java
  test/src/test/java/jenkins/TestJnlpSlaveAgentProtocol.java
  test/src/test/java/jenkins/TestJnlpSlaveAgentProtocol2.java
  test/src/test/java/jenkins/TestJnlpSlaveAgentProtocol3.java
  test/src/test/java/jenkins/install/SetupWizardTest.java
  test/src/test/resources/hudson/model/QueueTest/load_queue_xml/config.xml
  test/src/test/resources/jenkins/AgentProtocolTest/config.xml
  test/src/test/resources/jenkins/AgentProtocolTest/testShouldNotDisableProtocolsForMigratedInstances/config.xml
  test/src/test/resources/jenkins/model/JenkinsBuildsAndWorkspacesDirectoriesTest/fromPreviousCustomSetup/config.xml
Labels: major-rfe, plugin-api-changes, ready-for-merge, upgrade-guide-needed

#4194 [JENKINS-59220] - Updated EnvVars to add a method that extends putAll functionality
  core/src/main/java/hudson/EnvVars.java
  core/src/test/java/hudson/EnvVarsTest.java
Labels: plugin-api-changes, ready-for-merge, rfe

#3904 [JENKINS-56152] Improve plugin manager UI wording + [JENKINS-56173] - Fix JavaScript error in Plugin Manager when optional dependency metadata cannot be retrieved
  core/src/main/resources/hudson/Messages.properties
  core/src/main/resources/hudson/PluginManager/_table.js
  core/src/main/resources/hudson/PluginManager/installed.jelly
  core/src/main/resources/hudson/PluginWrapper/PluginWrapperAdministrativeMonitor/message.jelly
  core/src/main/resources/hudson/PluginWrapper/PluginWrapperAdministrativeMonitor/message.properties
  core/src/main/resources/hudson/PluginWrapper/PluginWrapperAdministrativeMonitor/message_bg.properties
  core/src/main/resources/hudson/PluginWrapper/PluginWrapperAdministrativeMonitor/message_de.properties
  core/src/main/resources/hudson/PluginWrapper/PluginWrapperAdministrativeMonitor/message_it.properties
  core/src/main/resources/hudson/PluginWrapper/PluginWrapperAdministrativeMonitor/message_pl.properties
  core/src/test/java/hudson/PluginWrapperTest.java
  war/src/main/webapp/css/style.css
Labels: bug, ready-for-merge, web-ui

#4271 [JENKINS-42658] - Fix NPE in Agent API when the agent is offline (e.g. retrieving agent version or OS description)
  core/src/main/java/hudson/slaves/SlaveComputer.java
Labels: bug, hacktoberfest, ready-for-merge

#4421 Inlining test-pom into test and removing test-jdk8
  pom.xml
  test-jdk8/pom.xml
  test-pom/pom.xml
  test/pom.xml
Labels: internal, ready-for-merge, skip-changelog

#4379 [JENKINS-36720] - Fix Spotbugs issues (SE_COMPARATOR_SHOULD_BE_SERIALIZABLE, ES_COMPARING_STRINGS_WITH_EQ)
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/logging/LogRecorder.java
  core/src/main/java/hudson/model/Label.java
  core/src/main/java/hudson/model/TimeZoneProperty.java
  core/src/main/java/hudson/tasks/Publisher.java
  core/src/main/java/jenkins/model/IdStrategy.java
Labels: ready-for-merge, skip-changelog

#4207 [JENKINS-59412] Clarify that build history does not include pipeline stages
  core/src/main/resources/hudson/model/Computer/builds.jelly
  core/src/main/resources/hudson/model/Computer/builds.properties
  core/src/main/resources/hudson/model/User/builds.jelly
  core/src/main/resources/hudson/model/User/builds.properties
  core/src/main/resources/hudson/model/View/builds.jelly
  core/src/main/resources/hudson/model/View/builds.properties
Labels: ready-for-merge, rfe

#4412 Simplify CoreUpdateMonitor/message.properties: changelog.url → jenkins-version.properties
  core/src/filter/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_bg.properties
  core/src/filter/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_it.properties
  core/src/filter/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_ru.properties
  core/src/filter/resources/hudson/model/hudson-version.properties
  core/src/filter/resources/jenkins/model/jenkins-version.properties
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message.jelly
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_bg.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_cs.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_da.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_de.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_es.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_et.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_fi.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_fr.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_hu.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_it.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_ja.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_ko.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_lt.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_lv.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_nb_NO.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_nl.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_pl.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_pt_BR.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_pt_PT.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_ru.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_sk.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_sl.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_sv_SE.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_uk.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_zh_TW.properties
Labels: ready-for-merge, skip-changelog

#4423 Add the maintainer checklist to the pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready-for-merge, skip-changelog

#4424 Upload draft Changelog YAMLs to GitHub Release assets
  .github/workflows/changelog.yml
Labels: skip-changelog

#4426 Revert "Upload draft Changelog YAMLs to GitHub Release assets"
  .github/workflows/changelog.yml
Labels: skip-changelog

#4427 [JENKINS-60740] - Rely on GitHub Actions to generate the release draft YAMLs
  .github/release-drafter.yml
  .github/workflows/changelog.yml
Labels: skip-changelog

#4429 Release Drafter Fix: Properly inherit the parent config
  .github/release-drafter.yml
Labels: skip-changelog

#4422 [JENKINS-60716] Retain causes of a LogRotator failure for diagnosis
  core/src/main/java/hudson/tasks/LogRotator.java
  core/src/main/java/jenkins/util/io/CompositeIOException.java
Labels: bug, ready-for-merge

#4416 Spotbugs issues
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/model/TimeZoneProperty.java
  core/src/main/java/jenkins/util/HttpSessionListener.java
Labels: internal, ready-for-merge, skip-changelog

#4411 [JENKINS-60577] - Prevent the RSS feed in Computer page from returning an error 404
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/model/Job.java
  core/src/main/java/hudson/model/RSS.java
  core/src/main/java/hudson/model/User.java
  core/src/main/java/hudson/model/View.java
  test/src/test/java/hudson/model/RSSTest.java
Labels: bug, plugin-api-changes, ready-for-merge

#4430 [JENKINS-60750] Skip CONFIGURE_INSTANCE panel when root URL is set during skipFirstUser
  core/src/main/java/jenkins/model/Jenkins.java
  war/src/main/js/pluginSetupWizardGui.js
Labels: bug, ready-for-merge, web-ui

#4435 Disable native maven based tests
  test/src/test/java/hudson/tasks/BuildTriggerTest.java
  test/src/test/java/hudson/tasks/EnvVarsInConfigTasksTest.java
  test/src/test/java/hudson/tools/ToolLocationNodePropertyTest.java
  test/src/test/resources/hudson/model/hudson.tasks.Maven.MavenInstaller.json.html
  test/src/test/resources/hudson/model/hudson.tasks.Maven.MavenInstaller1.json
  test/src/test/resources/hudson/model/hudson.tasks.Maven.MavenInstaller2.json
  test/src/test/resources/hudson/model/hudson.tasks.Maven.MavenInstaller3.json
  test/src/test/resources/hudson/model/hudson.tasks.Maven.MavenInstallerResult.json
Labels: internal, ready-for-merge, skip-changelog

#4434 [JENKINS-60678] Fix java checking on ComputerLauncher for AdoptOpenJDK 11
  core/src/main/java/hudson/slaves/ComputerLauncher.java
  core/src/test/java/hudson/slaves/ComputerLauncherTest.java
Labels: bug, ready-for-merge

#4369 [JEP-222] WebSocket support
  cli/pom.xml
  cli/src/main/java/hudson/cli/CLI.java
  cli/src/main/java/hudson/cli/PlainCLIProtocol.java
  cli/src/main/resources/hudson/cli/client/Messages.properties
  cli/src/test/java/hudson/cli/PlainCLIProtocolTest.java
  core/src/main/java/hudson/cli/CLIAction.java
  core/src/main/java/hudson/cli/CLICommand.java
  core/src/main/java/hudson/model/Slave.java
  core/src/main/java/hudson/slaves/JNLPLauncher.java
  core/src/main/java/hudson/triggers/SafeTimerTask.java
  core/src/main/java/jenkins/agents/WebSocketAgents.java
  core/src/main/java/jenkins/slaves/DefaultJnlpSlaveReceiver.java
  core/src/main/java/jenkins/slaves/JnlpAgentReceiver.java
  core/src/main/java/jenkins/websocket/WebSocketEcho.java
  core/src/main/java/jenkins/websocket/WebSocketSession.java
  core/src/main/java/jenkins/websocket/WebSockets.java
  core/src/main/resources/hudson/TcpSlaveAgentListener/index.jelly
  core/src/main/resources/hudson/cli/CLIAction/example.jelly
  core/src/main/resources/hudson/slaves/JNLPLauncher/config.jelly
  core/src/main/resources/hudson/slaves/JNLPLauncher/help-webSocket.html
  core/src/main/resources/hudson/slaves/JNLPLauncher/main.jelly
  core/src/main/resources/hudson/slaves/SlaveComputer/slave-agent.jnlp.jelly
  core/src/main/resources/hudson/slaves/SlaveComputer/systemInfo.jelly
  pom.xml
  test/pom.xml
  test/src/test/java/hudson/cli/CLIActionTest.java
  test/src/test/java/hudson/cli/CLITest.java
  test/src/test/java/hudson/slaves/JNLPLauncherTest.java
  test/src/test/java/jenkins/agents/WebSocketAgentsTest.java
  war/pom.xml
Labels: major-rfe, ready-for-merge

#4440 [JENKINS-60822] cannot parse changelog.url in message property files
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_bg.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_cs.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_da.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_de.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_es.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_et.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_fi.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_fr.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_hu.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_it.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_ja.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_ko.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_lt.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_lv.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_nb_NO.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_nl.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_pl.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_pt_BR.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_pt_PT.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_ru.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_sk.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_sl.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_uk.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_zh_TW.properties
Labels: bug, ready-for-merge

#4438 Removed unnecessary semicolons and unused imports
  core/src/main/java/hudson/cli/ConnectNodeCommand.java
  core/src/main/java/hudson/cli/OnlineNodeCommand.java
  core/src/main/java/hudson/diagnosis/OldDataMonitor.java
  core/src/main/java/hudson/model/DirectoryBrowserSupport.java
  core/src/main/java/hudson/model/ListView.java
  core/src/main/java/hudson/model/User.java
  core/src/main/java/hudson/model/View.java
  core/src/main/java/hudson/slaves/DumbSlave.java
  core/src/main/java/hudson/util/FormValidation.java
  core/src/main/java/jenkins/model/JenkinsLocationConfiguration.java
  core/src/main/java/jenkins/mvn/FilePathGlobalSettingsProvider.java
  core/src/main/java/jenkins/mvn/FilePathSettingsProvider.java
  core/src/main/java/jenkins/util/AntClassLoader.java
  core/src/main/java/jenkins/util/AntWithFindResourceClassLoader.java
  core/src/test/java/hudson/slaves/NodeListTest.java
  core/src/test/java/hudson/util/io/TarArchiverTest.java
  test/src/test/java/hudson/ProcStarterTest.java
  test/src/test/java/hudson/cli/CLITest.java
  test/src/test/java/hudson/cli/ReloadConfigurationCommandTest.java
  test/src/test/java/hudson/model/FreeStyleProjectTest.java
  test/src/test/java/hudson/model/ManagementLinkTest.java
  test/src/test/java/hudson/model/UpdateCenterCustomTest.java
  test/src/test/java/hudson/model/queue/MaintainCanTakeStrengtheningTest.java
  test/src/test/java/hudson/scm/AbstractScmTagActionTest.java
  test/src/test/java/hudson/tools/ToolLocationNodePropertyTest.java
  test/src/test/java/jenkins/security/Security637Test.java
  test/src/test/java/jenkins/util/AntClassLoaderTest.java
Labels: internal, ready-for-merge, skip-changelog

#4433 [JENKINS-60725] Add an ignored place to missing class telemetry
  core/src/main/java/jenkins/telemetry/impl/java11/MissingClassTelemetry.java
Labels: bug, java11, ready-for-merge

#4444 [JENKINS-60816] Missing null check when traversing type hierarchy of interfaces
  core/src/main/java/hudson/ExtensionFinder.java
  test/src/test/java/hudson/ExtensionFinderTest.java
Labels: bug, ready-for-merge

#4441 Update access-modifier to allow plugins to use suppressions
  pom.xml
Labels: developer, ready-for-merge

#4452 [JENKINS-57888, JENKINS-60821] - Winstone 5.7: Restore java.util.logging.config.file property support and change the Jetty thread pull name
  war/pom.xml
Labels: bug, internal

#4436 Add a disabled status to the REST API for AbstractProject job types
  core/src/main/java/hudson/model/AbstractProject.java
Labels: ready-for-merge, rfe

#4454 [JENKINS-60857] Pick up Winstone with fix
  war/pom.xml
Labels: major-bug, regression-fix
