Repository jenkinsci/jenkins, pull requests merged in 2020-11, with the labels that each got.

#5030 [JENKINS-60866] Un-inline LoadStatistics
  core/src/main/resources/hudson/model/LoadStatistics/main.jelly
  core/src/main/resources/hudson/model/LoadStatistics/main.properties
  core/src/main/resources/hudson/model/LoadStatistics/resources.js
Labels: internal, ready-for-merge, web-ui

#5027 Hacktoberfest - Use StandardCharsets except deprecated Charsets from Apache Commons
  core/src/main/java/jenkins/model/RunIdMigrator.java
  core/src/main/java/jenkins/model/identity/IdentityRootAction.java
Labels: hacktoberfest-accepted, internal, ready-for-merge, skip-changelog

#5026 XMLUtils should parse via InputStream not Reader
  core/src/main/java/jenkins/util/xml/XMLUtils.java
Labels: developer, plugin-api-changes, ready-for-merge

#5033 JDK 11.0.9 / 8.0.272+ compatible FunctionsTest#printThrowable()
  core/src/test/java/hudson/FunctionsTest.java
Labels: internal, ready-for-merge, skip-changelog

#5037 [JENKINS-63899] Fix renaming items with non-latin characters and spaces
  core/src/main/java/hudson/model/AbstractItem.java
  test/src/test/java/hudson/model/JobTest.java
Labels: bug, ready-for-merge

#5038 [JENKINS-62985] Stapler 1.260 → 1.261
  bom/pom.xml
Labels: bug, ready-for-merge

#5039 Deprecating UnbufferedBase64InputStream
  core/src/main/java/hudson/util/UnbufferedBase64InputStream.java
Labels: developer, ready-for-merge

#5041 Restriction mistake on TokenUuidAndPlainValue
  core/src/main/java/jenkins/security/apitoken/TokenUuidAndPlainValue.java
Labels: bug, plugin-api-changes, ready-for-merge

#5040 [JENKINS-64037] - Remove obsolete support for live class reloading with JRebel
  bom/pom.xml
  core/pom.xml
Labels: developer, ready-for-merge

#5043 Update to 4.6 version of Remoting.
  pom.xml
Labels: ready-for-merge, rfe

#5045 Cherry pick JDK 11.0.9 / 8.0.272+ compatible FunctionsTest#printThrowable() to stable-2.249
  core/src/test/java/hudson/FunctionsTest.java
Labels: ready-for-merge, skip-changelog

#5042 Remove unused org.kohsuke.stapler:stapler-adjunct-zeroclipboard
  bom/pom.xml
  core/pom.xml
  core/src/main/resources/lib/layout/copyButton.jelly
Labels: developer, plugin-api-changes, ready-for-merge, removed

#5044 Simplified IdentityRootAction.getFingerprint
  core/src/main/java/jenkins/model/identity/IdentityRootAction.java
Labels: internal, ready-for-merge, skip-changelog

#5000 Fix combobox.js issues
  war/src/main/webapp/scripts/combobox.js
Labels: ready-for-merge, skip-changelog, web-ui

#5028 [JENKINS-60563] Replace MD5 with SHA-256 in ConsistentHash
  core/src/main/java/hudson/util/ConsistentHash.java
  core/src/test/java/hudson/util/ConsistentHashTest.java
Labels: internal, ready-for-merge

#4944 [JEP-228] Unforking XStream
  bom/pom.xml
  core/pom.xml
  core/src/main/java/hudson/diagnosis/OldDataMonitor.java
  core/src/main/java/hudson/model/AbstractItem.java
  core/src/main/java/hudson/model/ListView.java
  core/src/main/java/hudson/model/Queue.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/tasks/Maven.java
  core/src/main/java/hudson/tools/ToolInstallation.java
  core/src/main/java/hudson/util/PersistedList.java
  core/src/main/java/hudson/util/RobustCollectionConverter.java
  core/src/main/java/hudson/util/RobustMapConverter.java
  core/src/main/java/hudson/util/RobustReflectionConverter.java
  core/src/main/java/hudson/util/XStream2.java
  core/src/main/java/hudson/util/xstream/MapperDelegate.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/test/java/hudson/util/XStream2Test.java
  pom.xml
  test/pom.xml
  test/src/test/java/hudson/model/ProjectTest.java
  test/src/test/java/hudson/util/RobustReflectionConverterTest.java
  test/src/test/java/hudson/util/XStream2AnnotationTest.java
Labels: dependencies, developer, major-rfe, plugin-api-changes, ready-for-merge, removed, squash-merge-me, upgrade-guide-needed

#5046 JENKINS-64040 JENKINS-64136 Fix hidden page elements from radio blocks showing up when they shouldn't
  core/src/main/resources/lib/form/radioBlock/radioBlock.js
Labels: major-bug, ready-for-merge

#5008 [JENKINS-62446] adding CasC compatibility to Global tool > Global Maven
  core/src/main/java/jenkins/mvn/GlobalMavenConfig.java
Labels: hacktoberfest-accepted, ready-for-merge, rfe

#4929 Upgrade jQuery to 3.5.x
  war/package.json
  war/src/main/js/config-scrollspy.js
  war/src/main/js/pluginSetupWizardGui.js
  war/src/main/js/util/page.js
  war/src/main/js/widgets/config/model/ConfigRowGrouping.js
  war/src/main/js/widgets/config/model/ConfigSection.js
  war/src/main/js/widgets/config/tabbar.js
  war/src/test/js/pluginSetupWizard.spec.js
  war/src/test/js/widgets/config/scrollspy.spec.js
  war/src/test/js/widgets/config/tabbar.spec.js
  war/yarn.lock
Labels: ready-for-merge, rfe, squash-merge-me

#4294 [JENKINS-41891] Resource root url cleanup
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/java/jenkins/diagnostics/RootUrlNotSetMonitor.java
  core/src/main/java/jenkins/security/ResourceDomainConfiguration.java
  core/src/main/resources/jenkins/diagnostics/RootUrlNotSetMonitor/message.properties
  core/src/main/resources/jenkins/security/Messages.properties
  core/src/main/resources/jenkins/security/ResourceDomainConfiguration/config.jelly
  core/src/main/resources/jenkins/security/ResourceDomainConfiguration/help-url.html
  core/src/main/resources/jenkins/security/ResourceDomainRecommendation/message.groovy
  core/src/main/resources/jenkins/security/ResourceDomainRecommendation/message.properties
  core/src/test/java/jenkins/util/UrlHelperTest.java
  test/src/test/java/jenkins/security/stapler/DoActionFilterTest.java
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, rfe

#5052 Windows installer link tables to divs
  core/src/main/resources/hudson/lifecycle/WindowsInstallerLink/index.jelly
Labels: ready-for-merge, skip-changelog

#5015 [JENKINS-63977] Separate security / non-security admin monitors
  core/src/main/java/hudson/model/AdministrativeMonitor.java
  core/src/main/java/jenkins/diagnostics/SecurityIsOffMonitor.java
  core/src/main/java/jenkins/management/AdministrativeMonitorsDecorator.java
  core/src/main/java/jenkins/security/UpdateSiteWarningsMonitor.java
  core/src/main/java/jenkins/security/apitoken/ApiTokenPropertyDisabledDefaultAdministrativeMonitor.java
  core/src/main/java/jenkins/security/apitoken/ApiTokenPropertyEnabledNewLegacyAdministrativeMonitor.java
  core/src/main/java/jenkins/security/apitoken/LegacyApiTokenAdministrativeMonitor.java
  core/src/main/java/jenkins/security/csrf/CSRFAdministrativeMonitor.java
  core/src/main/java/jenkins/security/s2m/MasterKillSwitchWarning.java
  core/src/main/resources/jenkins/management/AdministrativeMonitorsDecorator/footer.jelly
  core/src/main/resources/jenkins/management/AdministrativeMonitorsDecorator/footer.properties
  core/src/main/resources/jenkins/management/AdministrativeMonitorsDecorator/resources.css
  core/src/main/resources/jenkins/management/AdministrativeMonitorsDecorator/resources.js
  core/src/main/resources/lib/layout/pageHeader.jelly
  war/src/main/less/abstracts/theme.less
  war/src/main/less/modules/page-header.less
  war/src/main/less/ui-refresh-overrides.less
  war/src/main/webapp/images/material-icons/svg-sprite-action-symbol.svg
Labels: ready-for-merge, rfe, squash-merge-me

#4274 JENKINS-1877 Add ability to specify shut down reason
  core/src/main/java/hudson/cli/QuietDownCommand.java
  core/src/main/java/jenkins/management/ShutdownLink.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/resources/jenkins/management/Messages.properties
  core/src/main/resources/jenkins/management/ShutdownLink/index.groovy
  core/src/main/resources/jenkins/model/Jenkins/_api.jelly
  core/src/main/resources/lib/layout/main-panel.jelly
  test/src/test/java/hudson/cli/CancelQuietDownCommandTest.java
  test/src/test/java/hudson/cli/QuietDownCommandTest.java
  test/src/test/java/hudson/model/QueueTest.java
Labels: plugin-api-changes, ready-for-merge, rfe, squash-merge-me, web-ui

#5064 Update the pinned version of ATH in use to a more recent version
  essentials.yml
Labels: internal, skip-changelog

#5062 Stable 2.263.1
  bom/pom.xml
  core/src/main/java/hudson/model/Executor.java
  core/src/main/java/jenkins/model/IdStrategy.java
  core/src/main/resources/lib/form/radioBlock/radioBlock.js
  core/src/test/java/hudson/FunctionsTest.java
  essentials.yml
  war/pom.xml
Labels: into-lts

#5069 Moved stylelint dependency to devDependencies
  war/package.json
Labels: ready-for-merge, skip-changelog

#5074 Updated the bundled XStream library from 1.4.13 to 1.4.14
  .github/dependabot.yml
  bom/pom.xml
Labels: dependencies, ready-for-merge, rfe

#5067 JENKINS-64252 Fix dragdrop regression
  core/src/main/resources/lib/form/dragdrop/dragdrop.js
Labels: bug, ready-for-merge, regression-fix

#5066 Remove unneeded and falsy String.trim polyfill
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: internal, ready-for-merge, skip-changelog

#5068 Removed tweak for ie < 9
  war/src/main/webapp/scripts/msie.js
  war/src/main/webapp/scripts/respond.js
Labels: internal, ready-for-merge, skip-changelog

#5058 Update which permission is needed for these actions
  core/src/main/resources/jenkins/model/Jenkins/_api.jelly
Labels: ready-for-merge, rfe, skip-changelog

#5063 Load admin monitors popup content via ajax
  core/src/main/java/jenkins/management/AdministrativeMonitorsApi.java
  core/src/main/java/jenkins/management/AdministrativeMonitorsApiData.java
  core/src/main/java/jenkins/management/AdministrativeMonitorsDecorator.java
  core/src/main/resources/jenkins/management/AdministrativeMonitorsApiData/monitorsList.jelly
  core/src/main/resources/jenkins/management/AdministrativeMonitorsApiData/monitorsList.properties
  core/src/main/resources/jenkins/management/AdministrativeMonitorsApiData/monitorsList_bg.properties
  core/src/main/resources/jenkins/management/AdministrativeMonitorsApiData/monitorsList_de.properties
  core/src/main/resources/jenkins/management/AdministrativeMonitorsApiData/monitorsList_it.properties
  core/src/main/resources/jenkins/management/AdministrativeMonitorsApiData/monitorsList_pl.properties
  core/src/main/resources/jenkins/management/AdministrativeMonitorsDecorator/footer.jelly
  core/src/main/resources/jenkins/management/AdministrativeMonitorsDecorator/resources.css
  core/src/main/resources/jenkins/management/AdministrativeMonitorsDecorator/resources.js
  test/src/test/java/jenkins/management/AdministrativeMonitorsDecoratorTest.java
Labels: bug, ready-for-merge, rfe

#5076 Removed JOnAS application server support
  war/src/main/webapp/WEB-INF/jonas-web.xml
Labels: internal, ready-for-merge, upgrade-guide-needed

#5080 [JENKINS-64289] Make welcome message localizable
  core/src/main/resources/hudson/model/AllView/noJob.groovy
Labels: ready-for-merge, skip-changelog

#5014 Hacktoberfest - ParametersDefinition add equals and hashCode
  core/src/main/java/hudson/model/BooleanParameterDefinition.java
  core/src/main/java/hudson/model/ChoiceParameterDefinition.java
  core/src/main/java/hudson/model/FileParameterDefinition.java
  core/src/main/java/hudson/model/ParameterDefinition.java
  core/src/main/java/hudson/model/PasswordParameterDefinition.java
  core/src/main/java/hudson/model/RunParameterDefinition.java
  core/src/main/java/hudson/model/StringParameterDefinition.java
  core/src/main/java/hudson/model/TextParameterDefinition.java
  core/src/test/java/hudson/model/ParameterDefinitionTest.java
Labels: hacktoberfest-accepted, ready-for-merge, rfe

#5081 Fix broken select.js widget with tabular markup
  core/src/main/resources/lib/form/select/select.js
Labels: bug, ready-for-merge

#5071 Custom workspace tr zh replace slave on agent
  war/src/main/webapp/help/project-config/custom-workspace_tr.html
  war/src/main/webapp/help/project-config/custom-workspace_zh_TW.html
Labels: ready-for-merge, skip-changelog

#5048 Deprecate FileSystemProvisioner
  core/src/main/java/hudson/FileSystemProvisioner.java
  core/src/main/java/hudson/FileSystemProvisionerDescriptor.java
  core/src/main/java/hudson/WorkspaceSnapshot.java
  core/src/main/java/hudson/fsp/WorkspaceSnapshotSCM.java
  core/src/main/java/hudson/model/AbstractBuild.java
  core/src/main/java/hudson/model/AbstractProject.java
  core/src/main/java/hudson/model/Node.java
  core/src/main/java/hudson/os/solaris/ZFSProvisioner.java
  test/src/test/java/hudson/FileSystemProvisionerTest.java
Labels: ready-for-merge, removed, rfe

#5079 Mark some more administrative monitors as security-related
  core/src/main/java/jenkins/security/QueueItemAuthenticatorMonitor.java
  core/src/main/java/jenkins/security/RekeySecretAdminMonitor.java
  core/src/main/java/jenkins/security/s2m/AdminCallableMonitor.java
Labels: ready-for-merge, rfe, skip-changelog

#5086 Fixed some stylelint issues
  war/src/main/less/base/yui-compatibility.less
  war/src/main/less/modules/content-blocks.less
  war/src/main/less/modules/page-footer.less
  war/src/main/less/modules/page-header.less
  war/src/main/less/modules/panes-and-bigtable.less
  war/src/main/less/modules/side-panel-tasks.less
  war/src/main/less/modules/side-panel-widgets.less
  war/src/main/less/modules/tabs.less
Labels: skip-changelog

#5085 Removed outdated browser workarounds
  war/src/main/less/base/style.less
Labels: ready-for-merge, skip-changelog
