Repository jenkinsci/jenkins, pull requests merged in 2020-10, with the labels that each got.

#4945 Refactoring CLIRegisterer
  core/src/main/java/hudson/cli/declarative/CLIRegisterer.java
Labels: internal, ready-for-merge, skip-changelog

#4952 Disable autocomplete of user name on login form
  core/src/main/resources/jenkins/model/Jenkins/login.jelly
Labels: ready-for-merge, rfe

#4950 [JENKINS-63795] allow MANAGE to restart and safe-restart jenkins.
  core/src/main/java/jenkins/model/Jenkins.java
  test/src/test/java/jenkins/model/JenkinsManagePermissionTest.java
Labels: ready-for-merge, rfe

#4955 [JENKINS-63828] Fix expected signature for CloudProvisioningListener#canProvision
  core/src/main/java/hudson/slaves/CloudProvisioningListener.java
  core/src/test/java/hudson/slaves/CloudProvisioningListenerTest.java
Labels: major-bug, ready-for-merge, regression-fix

#4954 Improve performance of MyView
  core/src/main/java/hudson/model/MyView.java
  test/src/test/java/hudson/model/MyViewTest.java
Labels: ready-for-merge, skip-changelog

#4953 [JENKINS-36716] Spotbugs cleanup
  core/src/main/java/hudson/model/Slave.java
  core/src/main/java/hudson/model/UpdateCenter.java
Labels: ready-for-merge, skip-changelog

#4958 org.apache.ant:ant 1.10.8 → 1.10.9
  bom/pom.xml
Labels: internal, ready-for-merge

#4027 [JENKINS-57484] Improving the scripting capacity for the API Tokens
  core/src/main/java/jenkins/install/SetupWizard.java
  core/src/main/java/jenkins/security/ApiTokenProperty.java
  core/src/main/java/jenkins/security/apitoken/ApiTokenStats.java
  core/src/main/java/jenkins/security/apitoken/ApiTokenStore.java
  core/src/main/java/jenkins/security/apitoken/TokenUuidAndPlainValue.java
  test/src/test/java/hudson/security/WhoAmITest.java
  test/src/test/java/jenkins/security/ApiTokenPropertyTest.java
  test/src/test/java/jenkins/security/apitoken/LegacyApiTokenAdministrativeMonitorTest.java
Labels: ready-for-merge, rfe

#4971 Maintainer guide - Add a Release Process section
  docs/MAINTAINERS.adoc
Labels: internal, skip-changelog

#4967 Hacktoberfest: Java 8 migration. Replace statements with lambda
  core/src/main/java/hudson/util/Iterators.java
Labels: hacktoberfest, ready-for-merge, skip-changelog

#4905 Shortlog strip console notes
  core/src/main/java/hudson/model/Run.java
  core/src/test/java/hudson/model/RunTest.java
Labels: ready-for-merge, rfe, web-ui

#4978 Don't render description pane when historyWidget.descriptionLimit is 0
  core/src/main/resources/hudson/widgets/HistoryWidget/entry.jelly
Labels: bug, ready-for-merge, web-ui

#4980 [JENKINS-63905] Agent to controller rather than agent to master
  core/src/main/resources/jenkins/security/s2m/AdminWhitelistRule/index.jelly
  core/src/main/resources/jenkins/security/s2m/MasterKillSwitchConfiguration/config.groovy
  core/src/main/resources/jenkins/security/s2m/Messages.properties
  core/src/main/resources/jenkins/security/s2m/Messages_bg.properties
Labels: bug, ready-for-merge

#4982 Bump parent pom to 1.58
  pom.xml
Labels: internal, ready-for-merge

#4984 Replace "slave" reference in Traditional Chinese document
  war/src/main/webapp/help/system-config/master-slave/availability_zh_TW.html
  war/src/main/webapp/help/system-config/master-slave/clock_zh_TW.html
  war/src/main/webapp/help/system-config/master-slave/demand/idleDelay_zh_TW.html
  war/src/main/webapp/help/system-config/master-slave/demand/inDemandDelay_zh_TW.html
  war/src/main/webapp/help/system-config/master-slave/description_zh_TW.html
  war/src/main/webapp/help/system-config/master-slave/jnlp-tunnel_zh_TW.html
  war/src/main/webapp/help/system-config/master-slave/numExecutors_zh_TW.html
  war/src/main/webapp/help/system-config/master-slave/usage_zh_TW.html
Labels: localization, ready-for-merge

#4977 Additional usages of preauth filtering
  core/src/main/java/hudson/model/AbstractProject.java
  core/src/main/java/hudson/model/User.java
  test/src/test/java/hudson/model/AbstractProjectTest.java
Labels: ready-for-merge, skip-changelog

#4957 Omit stacktraces on ClassNotFoundException in PluginStrategy classloading
  core/src/main/java/hudson/ClassicPluginStrategy.java
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/jenkins/util/AntClassLoader.java
  core/src/main/java/jenkins/util/java/ClassNotFoundNoStackTraceException.java
Labels: developer, ready-for-merge, rfe

#4960 remove specified maven-war-plugin.version to use newer version from parent project
  pom.xml
Labels: internal, ready-for-merge, rfe

#4949 [JENKINS-63798] Fix extensions footer location
  core/src/main/resources/lib/layout/layout.jelly
Labels: bug, ready-for-merge, regression-fix

#4979 Check for updates to GitHub Actions every weekday
  .github/dependabot.yml
Labels: internal, skip-changelog

#4974 Remove beta mark from APIs introduced for JEP-202
  core/src/main/java/jenkins/util/VirtualFile.java
Labels: developer, plugin-api-changes, ready-for-merge, rfe

#4970 [JENKINS-63828] It is legal to have a CloudProvisioningListener not implementing `canProvision`
  core/src/main/java/hudson/Util.java
  core/src/main/java/hudson/slaves/CloudProvisioningListener.java
  core/src/test/java/hudson/UtilTest.java
  core/src/test/java/hudson/slaves/CloudProvisioningListenerTest.java
Labels: major-bug, ready-for-merge, regression-fix

#4951 Update SSHD Module
  bom/pom.xml
Labels: ready-for-merge, rfe

#4989 Replace deprecated NullOutputStream
  core/src/main/java/hudson/ClassicPluginStrategy.java
  core/src/main/java/hudson/TcpSlaveAgentListener.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/jenkins/util/JSONSignatureValidator.java
  core/src/test/java/hudson/FilePathTest.java
  core/src/test/java/hudson/slaves/ComputerLauncherTest.java
  core/src/test/java/jenkins/RemotingJarSignatureTest.java
Labels: internal, ready-for-merge, skip-changelog

#4988 Bump slf4j-api 1.7.26 -> 1.7.30
  bom/pom.xml
Labels: developer, ready-for-merge

#4975 Upgrade winstone 5.11 to introduce Jetty LowResourceMonitor
  war/pom.xml
Labels: ready-for-merge, rfe

#4940 Fix error message
  core/src/main/java/hudson/console/ConsoleLogFilter.java
  core/src/main/java/hudson/tasks/BuildWrapper.java
Labels: ready-for-merge, skip-changelog

#4933 Fix deprecation warnings + Update ArtifactArchiver to no longer consult with environment variables injected by EnvironmentContributingActions during the build
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/cli/BuildCommand.java
  core/src/main/java/hudson/tasks/ArtifactArchiver.java
  core/src/main/java/hudson/util/IncompatibleAntVersionDetected.java
  core/src/main/java/hudson/util/IncompatibleServletVersionDetected.java
  core/src/main/java/jenkins/util/JSONSignatureValidator.java
Labels: developer, ready-for-merge

#4999 [JENKINS-63937, JENKINS-63933] - Revert "Omit stacktraces on ClassNotFoundException in PluginStrategy classloading"
  core/src/main/java/hudson/ClassicPluginStrategy.java
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/jenkins/util/AntClassLoader.java
  core/src/main/java/jenkins/util/java/ClassNotFoundNoStackTraceException.java
Labels: major-bug, ready-for-merge, regression-fix

#5001 JENKINS-63798 Fix admin monitor JS showing in footer
  war/src/main/less/modules/page-footer.less
Labels: major-bug, ready-for-merge, regression-fix, web-ui

#4997 French localization of nojob_fr.properties
  core/src/main/resources/hudson/model/AllView/noJob_fr.properties
Labels: localization, ready-for-merge

#4973 Correct self label check
  core/src/main/java/hudson/model/Label.java
  test/src/test/java/hudson/model/labels/LabelAtomTest.java
Labels: internal, ready-for-merge, skip-changelog

#4966 removed redundant if statement
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/slaves/ChannelPinger.java
  core/src/main/java/hudson/util/CharacterEncodingFilter.java
  core/src/main/java/jenkins/management/AdministrativeMonitorsDecorator.java
  core/src/main/java/jenkins/security/BasicHeaderProcessor.java
Labels: hacktoberfest-accepted, internal, ready-for-merge, skip-changelog

#4919 Do not use null value for aria-hidden HTML attribute
  core/src/main/resources/lib/layout/svgIcon.jelly
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: bug, ready-for-merge, web-ui

#5004 removed dc-license.txt
  war/src/main/webapp/dc-license.txt
Labels: internal, ready-for-merge, skip-changelog

#4992 Prevent resource leak in FileFingerprintStorage
  core/src/main/java/jenkins/fingerprints/FileFingerprintStorage.java
Labels: bug, ready-for-merge, skip-changelog

#4987 Reduce the prototype.js usage
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: internal, ready-for-merge, skip-changelog, web-ui

#4981 Simplify code for tied jobs count
  core/src/main/java/hudson/model/Label.java
Labels: ready-for-merge, skip-changelog

#4961 [JENKINS-36720] Spotbugs issues
  core/src/main/java/hudson/WebAppMain.java
  core/src/main/java/hudson/model/UpdateSite.java
Labels: ready-for-merge, skip-changelog

#5007 Improve tests for Labels
  test/src/test/java/hudson/model/labels/LabelAtomTest.java
Labels: internal, ready-for-merge, skip-changelog

#5016 [INFRA-2751] Remove tfs plugin from setup wizard
  core/src/main/resources/jenkins/install/platform-plugins.json
Labels: ready-for-merge, rfe

#5011 Hacktoberfest - Optimize allocations in LogRotator and RunList
  core/src/main/java/hudson/tasks/LogRotator.java
  core/src/main/java/hudson/util/RunList.java
Labels: hacktoberfest-accepted, internal, ready-for-merge, skip-changelog

#5012 Hacktoberfest - TcpSlaveAgentListener optimization
  core/src/main/java/hudson/TcpSlaveAgentListener.java
Labels: hacktoberfest-accepted, internal, ready-for-merge, skip-changelog

#4972 [JENKINS-49523] Excludes separator clarified
  core/src/main/resources/hudson/tasks/ArtifactArchiver/help-excludes.html
  core/src/main/resources/hudson/tasks/Fingerprinter/help-excludes.html
Labels: internal, ready-for-merge, skip-changelog

#4995 French translation of setupWizardConfigureInstance
  core/src/main/resources/jenkins/install/SetupWizard/setupWizardConfigureInstance_fr.properties
Labels: localization, ready-for-merge

#5019 [JENKINS-63958] use new winstone 5.11.1 with downgraded Jetty version 9.4.30.v20200611
  war/pom.xml
Labels: dependencies, major-bug, ready-for-merge, regression-fix

#5024 Stable 2.249.3
  core/src/main/resources/hudson/scm/SCM/project-changes.jelly
  core/src/main/resources/lib/form/radioBlock/radioBlock.js
  core/src/main/resources/lib/layout/layout.jelly
  war/src/main/less/modules/page-footer.less
Labels: into-lts

#3895 [JENKINS-56109] Change Jenkins configuration UI from tables to divs
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/index.groovy
  core/src/main/resources/hudson/tools/ToolInstallation/global.jelly
  core/src/main/resources/jenkins/management/AdministrativeMonitorsConfiguration/config.groovy
  core/src/main/resources/jenkins/model/GlobalProjectNamingStrategyConfiguration/config.groovy
  core/src/main/resources/lib/form/advanced.jelly
  core/src/main/resources/lib/form/block.jelly
  core/src/main/resources/lib/form/checkbox.jelly
  core/src/main/resources/lib/form/description.jelly
  core/src/main/resources/lib/form/descriptorList.jelly
  core/src/main/resources/lib/form/dragdrop/dragdrop.js
  core/src/main/resources/lib/form/dropdownList.jelly
  core/src/main/resources/lib/form/dropdownListBlock.jelly
  core/src/main/resources/lib/form/entry.jelly
  core/src/main/resources/lib/form/expandableTextbox.jelly
  core/src/main/resources/lib/form/form.jelly
  core/src/main/resources/lib/form/helpArea.jelly
  core/src/main/resources/lib/form/helpLink.jelly
  core/src/main/resources/lib/form/hetero-list.jelly
  core/src/main/resources/lib/form/hetero-list/hetero-list.js
  core/src/main/resources/lib/form/hetero-radio.jelly
  core/src/main/resources/lib/form/invisibleEntry.jelly
  core/src/main/resources/lib/form/nested.jelly
  core/src/main/resources/lib/form/optionalBlock.jelly
  core/src/main/resources/lib/form/radioBlock.jelly
  core/src/main/resources/lib/form/repeatableProperty.jelly
  core/src/main/resources/lib/form/rowSet.jelly
  test/src/test/java/hudson/model/ParametersTest.java
  test/src/test/java/hudson/pages/SystemConfigurationTestCase.java
  war/src/main/js/widgets/config/model/ConfigTableMetaData.js
  war/src/main/less/base/style.less
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: major-rfe, ready-for-merge, squash-merge-me, web-ui

#5031 Fix JS tests failing on master
  Jenkinsfile
  core/src/test/java/hudson/FunctionsTest.java
  war/.gitignore
  war/jest.config.json
  war/package.json
  war/src/test/js/widgets/config/freestyle-config-tabbed.html
  war/yarn.lock
Labels: skip-changelog

#5013 [JENKINS-63868] - Prevent the Build History Widget from exploding when user have Discover permissions without Read for folders
  core/src/main/java/hudson/model/Executor.java
Labels: bug, hacktoberfest-accepted, ready-for-merge

#4993 Made small changes to make the README and CONTRIBUTING files easier to follow
  CONTRIBUTING.md
  README.md
Labels: hacktoberfest-accepted, internal, ready-for-merge, skip-changelog

#5034 [JENKINS-64035] - Winstone 5.12: Update Jetty from 9.4.30.v20200611 to 9.4.33.v20201020
  war/pom.xml
Labels: ready-for-merge, rfe

#5010 [JENKINS-35452] A step towards removing more 'slave' terminology.
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/slaves/SlaveComputer.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/resources/hudson/slaves/JNLPLauncher/main.jelly
  core/src/main/resources/hudson/slaves/SlaveComputer/jenkins-agent.jnlp.jelly
  test/src/test/java/hudson/slaves/JNLPLauncherTest.java
Labels: bug, ready-for-merge

#5022 Hacktoberfest: trim the adminAddress before saving
  core/src/main/java/jenkins/model/JenkinsLocationConfiguration.java
  core/src/test/java/jenkins/model/JenkinsLocationConfigurationTest.java
Labels: ready-for-merge, skip-changelog

#4985 Update french i18n + (local) Terminology for jobs
  core/src/main/resources/hudson/model/LoadStatistics/main_fr.properties
  core/src/main/resources/hudson/model/Messages_fr.properties
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/help-slaveAgentPort_fr.html
  core/src/main/resources/hudson/slaves/DumbSlave/configure-entries_fr.properties
  core/src/main/resources/hudson/slaves/Messages_fr.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Demand/config_fr.properties
  core/src/main/resources/hudson/slaves/SimpleScheduledRetentionStrategy/config.properties
  core/src/main/resources/hudson/slaves/SimpleScheduledRetentionStrategy/config_fr.properties
  core/src/main/resources/jenkins/model/Jenkins/MasterComputer/configure_fr.properties
  core/src/main/resources/jenkins/model/MasterBuildConfiguration/config_fr.properties
  war/src/main/webapp/help/project-config/custom-workspace_fr.html
  war/src/main/webapp/help/system-config/master-slave/availability.html
  war/src/main/webapp/help/system-config/master-slave/availability_fr.html
  war/src/main/webapp/help/system-config/master-slave/usage.html
  war/src/main/webapp/help/system-config/master-slave/usage_fr.html
Labels: localization, ready-for-merge

#5029 Queue (mainly) style consistency
  core/src/main/java/hudson/model/Queue.java
Labels: internal, ready-for-merge, skip-changelog

#5035 [JENKINS-64039] improve CaseInsensitive.equals(String, String) performance
  core/src/main/java/jenkins/model/IdStrategy.java
Labels: ready-for-merge, rfe

#5005 Fixed eslint warnings of type no-mixed-spaces-and-tabs
  war/src/main/js/pluginSetupWizardGui.js
  war/src/main/js/util/page.js
  war/src/test/js/pluginSetupWizard.spec.js
Labels: internal, ready-for-merge, skip-changelog

#5006 Stylelint fixes
  war/src/main/less/base/layout-commons.less
  war/src/main/less/base/style.less
  war/src/main/less/base/yui-compatibility.less
  war/src/main/less/modules/manage-jenkins.less
  war/src/main/less/modules/panes-and-bigtable.less
  war/src/main/less/modules/side-panel-widgets.less
Labels: internal, ready-for-merge, skip-changelog

#5009 French translation of user configuration page, mainly token paragraph.
  core/src/main/resources/hudson/search/Messages_fr.properties
  core/src/main/resources/jenkins/security/ApiTokenProperty/config_fr.properties
  core/src/main/resources/jenkins/security/ApiTokenProperty/help-tokenStore_fr.html
  core/src/main/resources/jenkins/security/Messages_fr.properties
  core/src/main/resources/lib/layout/breadcrumbBar_fr.properties
Labels: hacktoberfest-accepted, localization, ready-for-merge
