Repository jenkinsci/jenkins, pull requests merged in 2020-02, with the labels that each got.

#4467 Disable failing test in UDP broadcast
  test/src/test/java/hudson/UDPBroadcastThreadTest.java
Labels: internal, skip-changelog

#4451 set locale for test, because test fails on german system
  core/src/test/java/hudson/PluginWrapperTest.java
Labels: internal, ready-for-merge, skip-changelog

#4471 [JENKINS-60884] - Fix NPE in Run API when using getPreviousBuildsOverThreshold
  core/src/main/java/hudson/model/Run.java
Labels: ready-for-merge, regression-fix

#4445 [JENKINS-59486] load icons for use while jenkins is restarting
  core/src/main/resources/hudson/PluginManager/table.jelly
  core/src/main/resources/hudson/model/UpdateCenter/body.jelly
Labels: bug, ready-for-merge

#4443 Improve log after SECURITY-626
  core/src/main/java/hudson/security/csrf/CrumbFilter.java
Labels: ready-for-merge, rfe, skip-changelog

#4459 [JENKINS-60907] add Buffered{In,Out}putStream to FilePath.TarCompression.NONE
  core/src/main/java/hudson/FilePath.java
Labels: ready-for-merge, rfe

#4462 Reduce number of calls to getItems in ListView
  core/src/main/java/hudson/model/ListView.java
Labels: ready-for-merge, rfe

#4458 Spotbugs: Check for null issue
  core/src/main/java/hudson/model/listeners/ItemListener.java
Labels: internal, ready-for-merge, skip-changelog

#4453 add job duration as tooltip to build time
  core/src/main/resources/hudson/widgets/HistoryWidget/entry.jelly
Labels: ready-for-merge, rfe, web-ui

#4442 [JENKINS-60848] Improve RSS title wording + Add more RSS tests
  core/src/main/java/hudson/logging/LogRecorderManager.java
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/model/Job.java
  core/src/main/java/hudson/model/RSS.java
  core/src/main/java/hudson/model/User.java
  core/src/main/java/hudson/model/View.java
  test/src/test/java/hudson/model/RSSTest.java
Labels: ready-for-merge, rfe

#4439 [JENKINS-60721] Annotate parameter classes
  core/src/main/java/hudson/model/ChoiceParameterDefinition.java
  core/src/main/java/hudson/model/ParameterDefinition.java
  core/src/main/java/hudson/model/ParametersDefinitionProperty.java
  core/src/test/java/hudson/model/ChoiceParameterDefinitionTest.java
Labels: bug, ready-for-merge

#4450 [JENKINS-51856] Add new milestones
  core/src/main/java/hudson/init/InitMilestone.java
  core/src/main/java/hudson/init/impl/InitialUserContent.java
  core/src/main/java/hudson/model/AperiodicWork.java
  core/src/main/java/hudson/model/ComputerSet.java
  core/src/main/java/hudson/model/PeriodicWork.java
  core/src/main/java/hudson/model/Queue.java
  core/src/main/java/hudson/model/User.java
  core/src/main/java/hudson/model/queue/QueueSorter.java
  core/src/main/java/hudson/util/DoubleLaunchChecker.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/model/Uptime.java
  test/src/test/java/hudson/init/InitMilestoneTest.java
Labels: developer, major-rfe, ready-for-merge

#4461 [JENKINS-54496] - Don't log node-monitoring errors from deleted nodes
  core/src/main/java/hudson/node_monitors/AbstractAsyncNodeMonitorDescriptor.java
Labels: ready-for-merge, rfe

#4473 [JENKINS-21837] Do not record user creating an agent
  core/src/main/java/hudson/cli/CreateNodeCommand.java
  core/src/main/java/hudson/model/ComputerSet.java
  core/src/main/java/hudson/model/Slave.java
  core/src/main/resources/hudson/model/Computer/index.jelly
  test/src/test/java/hudson/cli/CreateNodeCommandTest.java
Labels: ready-for-merge, rfe, upgrade-guide-needed

#4410 Add configuration-as-code as suggested plugin
  core/src/main/resources/jenkins/install/platform-plugins.json
Labels: ready-for-merge, rfe

#4460 [JENKINS-60913] Remove network discovery services
  core/pom.xml
  core/src/main/java/hudson/DNSMultiCast.java
  core/src/main/java/hudson/UDPBroadcastFragment.java
  core/src/main/java/hudson/UDPBroadcastThread.java
  core/src/main/java/jenkins/model/Jenkins.java
  test/src/test/java/hudson/UDPBroadcastThreadSEC1641Test.java
  test/src/test/java/hudson/UDPBroadcastThreadTest.java
  war/pom.xml
Labels: major-rfe, ready-for-merge, upgrade-guide-needed

#4385 Export whether plugin update is compatible
  core/src/main/java/hudson/model/UpdateSite.java
Labels: ready-for-merge, rfe

#4474 Enforce singleton pattern in CaseInsensitiveComparator
  core/src/main/java/hudson/util/CaseInsensitiveComparator.java
Labels: internal, ready-for-merge

#4481 Release Drafter: Do not use `regression-fix` label for the changelog, use the global template
  .github/release-drafter.yml
Labels: skip-changelog, squash-merge-me

#4456 [JENKINS-60867] Prevent creation of duplicated SetupWizard singleton instances on Jenkins startup
  core/src/main/java/jenkins/model/Jenkins.java
  test/src/test/java/jenkins/ExtensionFilterTest.java
Labels: bug, ready-for-merge

#4449 Clean up Deprecation: Channel(...)
  core/src/test/java/hudson/ChannelRule.java
Labels: internal, ready-for-merge, skip-changelog

#4476 [JENKINS-60926] - Fix agent installation as a service on Windows. (regression in 2.217)
  pom.xml
  war/pom.xml
Labels: major-bug, regression-fix

#4485 Increase timeout on test to stop flaking
  test/src/test/java/hudson/model/ViewDescriptorTest.java
Labels: internal, skip-changelog

#4484 [JENKINS-61024] Use LinkedHashMap for deterministic iterations
  core/src/test/java/hudson/util/ArgumentListBuilderTest.java
Labels: internal, ready-for-merge, skip-changelog

#4469 Add preauth filtering overload of getAllItems(), getItems() and allItems()
  core/src/main/java/hudson/model/ItemGroup.java
  core/src/main/java/hudson/model/Items.java
  core/src/main/java/jenkins/model/Jenkins.java
  test/src/test/java/hudson/model/ItemsTest.java
Labels: developer, ready-for-merge

#4482 Do not show disabled permissions in permission errors
  core/src/main/java/hudson/security/ACL.java
  test/src/test/java/hudson/cli/GetNodeCommandTest.java
Labels: ready-for-merge, rfe

#3989 Changed exception presented when AtomicFileWriter fails to write to file
  core/src/main/java/hudson/util/AtomicFileWriter.java
Labels: internal, ready-for-merge

#4494 Remove references to Azure maven cache
  Jenkinsfile
  settings-azure.xml
Labels: ready-for-merge, skip-changelog

#4493 update AdministrativeMonitor javadoc to reference alert-danger not alert-error
  core/src/main/java/hudson/model/AdministrativeMonitor.java
Labels: developer, ready-for-merge

#4502 [JENKINS-61102] Use XMLUnit to fix test
  core/src/test/java/jenkins/util/xstream/XStreamDOMTest.java
Labels: ready-for-merge, skip-changelog

#4490 Update script-security to 1.70
  war/pom.xml
Labels: ready-for-merge, rfe

#4381 Add findsecbugs plugin to spotbugs.
  cli/src/main/java/hudson/cli/CLI.java
  cli/src/main/java/hudson/cli/FullDuplexHttpStream.java
  cli/src/main/java/hudson/cli/NoCheckTrustManager.java
  cli/src/main/java/hudson/cli/SSHCLI.java
  core/src/main/java/hudson/ClassicPluginStrategy.java
  core/src/main/java/hudson/Proc.java
  core/src/main/java/hudson/Util.java
  core/src/main/java/hudson/cli/Connection.java
  core/src/main/java/hudson/console/AnnotatedLargeText.java
  core/src/main/java/hudson/console/ConsoleNote.java
  core/src/main/java/hudson/scheduler/Hash.java
  core/src/main/java/hudson/security/BasicAuthenticationFilter.java
  core/src/main/java/hudson/security/HudsonAuthenticationEntryPoint.java
  core/src/main/java/hudson/util/ConsistentHash.java
  core/src/main/java/hudson/util/DOSToUnixPathHelper.java
  core/src/main/java/hudson/util/FormFieldValidator.java
  core/src/main/java/jenkins/model/RunIdMigrator.java
  core/src/main/java/jenkins/model/identity/IdentityRootAction.java
  core/src/main/java/jenkins/slaves/JnlpSlaveAgentProtocol4.java
  pom.xml
  src/findbugs/findbugs-excludes.xml
Labels: internal, ready-for-merge

#4455 [JENKINS-60866] Un-inline JavaScript / CSS from HudsonPrivateSecurity…
  core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java
  core/src/main/resources/hudson/model/View/AsynchPeople/index.jelly
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/_entryForm.jelly
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/_entryFormPage.jelly
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/_entryFormPage/resources.css
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/addUser.jelly
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/config.jelly
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/firstUser.jelly
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/index.jelly
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/loginLink.jelly
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/sidepanel.jelly
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/signupWithFederatedIdentity.jelly
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/success.jelly
  core/src/main/resources/hudson/security/SecurityRealm/signup.jelly
  core/src/main/resources/lib/layout/hasPermission.jelly
  war/src/main/webapp/css/style.css
Labels: internal, ready-for-merge, web-ui

#4491 [JENKINS-61071] Ensure that initialization tasks run as SYSTEM
  core/src/main/java/jenkins/InitReactorRunner.java
  test/src/test/java/hudson/PluginManagerTest.java
  test/src/test/resources/plugins/require-system-in-initializer.jpi
Labels: bug, ready-for-merge

#4499 Make memory usage graph discoverable
  core/src/main/resources/jenkins/model/Jenkins/systemInfo.jelly
Labels: ready-for-merge, rfe

#4488 [JENKINS-61046] - Allow plugins to force an update of the UpdateCenter
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/model/UpdateSite.java
Labels: developer, plugin-api-changes, ready-for-merge

#4501 [JEP-223] Overall/Manage permission
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/model/Descriptor.java
  core/src/main/java/hudson/model/ManageJenkinsAction.java
  core/src/main/java/hudson/model/ManagementLink.java
  core/src/main/java/jenkins/management/CliLink.java
  core/src/main/java/jenkins/management/ConfigureLink.java
  core/src/main/java/jenkins/management/NodesLink.java
  core/src/main/java/jenkins/management/StatisticsLink.java
  core/src/main/java/jenkins/model/GlobalProjectNamingStrategyConfiguration.java
  core/src/main/java/jenkins/model/GlobalQuietPeriodConfiguration.java
  core/src/main/java/jenkins/model/GlobalSCMRetryCountConfiguration.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/resources/hudson/PluginManager/sidepanel.groovy
  core/src/main/resources/hudson/model/ComputerSet/sidepanel.jelly
  core/src/main/resources/hudson/model/Messages.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/sidepanel.jelly
  core/src/main/resources/jenkins/model/Jenkins/configure.jelly
  core/src/main/resources/jenkins/model/Jenkins/manage.jelly
  test/src/test/java/jenkins/model/JenkinsManagePermissionTest.java
Labels: major-rfe, plugin-api-changes, ready-for-merge

#4487 [JENKINS-60966] Order admin monitors in Global Configuration
  core/src/main/resources/jenkins/management/AdministrativeMonitorsConfiguration/config.groovy
Labels: ready-for-merge, rfe

#4497 Improve performance when loading tied jobs
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/model/Label.java
  test/src/test/java/hudson/model/ComputerTest.java
Labels: internal, ready-for-merge

#4504 [JENKINS-61121] Fix too many open files with resource domain
  core/src/main/java/hudson/model/DirectoryBrowserSupport.java
Labels: bug, ready-for-merge

#4505 Adding french translation for concurrent build help
  core/src/main/resources/hudson/model/AbstractProject/help-concurrentBuild_fr.html
Labels: localization, ready-for-merge

#4508 [JENKINS-36720] Spotbugs fix possible NPE
  core/src/main/java/jenkins/telemetry/impl/SecuritySystemProperties.java
  core/src/main/java/jenkins/telemetry/impl/java11/MissingClassTelemetry.java
Labels: internal, ready-for-merge, skip-changelog

#4509 Always set a crumb issuer
  core/src/main/java/hudson/security/csrf/GlobalCrumbIssuerConfiguration.java
  core/src/main/java/jenkins/install/SetupWizard.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/resources/hudson/security/csrf/GlobalCrumbIssuerConfiguration/config.groovy
  core/src/main/resources/hudson/security/csrf/GlobalCrumbIssuerConfiguration/config.properties
Labels: ready-for-merge, rfe, upgrade-guide-needed

#4510 [JENKINS-36720] Fix instances of double checked locking
  core/src/main/java/hudson/model/ViewJob.java
  core/src/main/java/jenkins/model/lazy/AbstractLazyLoadRunMap.java
Labels: internal, ready-for-merge, skip-changelog

#4496 Follow up optimizations to getAllItems() and getItems()
  core/src/main/java/hudson/model/Items.java
  core/src/main/java/jenkins/model/Jenkins.java
Labels: internal, ready-for-merge

#4511 [JENKINS-36720] Spotbugs fixes
  core/src/main/java/hudson/model/Fingerprint.java
  core/src/main/java/hudson/triggers/SCMTrigger.java
  core/src/main/java/hudson/util/Retrier.java
Labels: internal, ready-for-merge, skip-changelog

#4506 JEP-224 Minimal system read
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/diagnosis/MemoryUsageMonitor.java
  core/src/main/java/hudson/model/ManageJenkinsAction.java
  core/src/main/java/hudson/security/ACL.java
  core/src/main/java/hudson/security/AccessControlled.java
  core/src/main/java/hudson/security/GlobalSecurityConfiguration.java
  core/src/main/java/jenkins/management/ConfigureLink.java
  core/src/main/java/jenkins/management/SystemInfoLink.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/tools/GlobalToolConfiguration.java
  core/src/main/resources/hudson/model/Messages.properties
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/index.groovy
  core/src/main/resources/hudson/security/Messages.properties
  core/src/main/resources/jenkins/model/Jenkins/configure.jelly
  core/src/main/resources/jenkins/model/Jenkins/manage.jelly
  core/src/main/resources/jenkins/model/Jenkins/systemInfo.jelly
  core/src/main/resources/jenkins/tools/GlobalToolConfiguration/index.groovy
  core/src/main/resources/lib/form/checkbox.jelly
  core/src/main/resources/lib/form/dropdownList.jelly
  core/src/main/resources/lib/form/hetero-list.jelly
  core/src/main/resources/lib/form/hetero-list/hetero-list.js
  core/src/main/resources/lib/form/number.jelly
  core/src/main/resources/lib/form/password.jelly
  core/src/main/resources/lib/form/possibleReadOnlyField.jelly
  core/src/main/resources/lib/form/radio.jelly
  core/src/main/resources/lib/form/radioBlock.jelly
  core/src/main/resources/lib/form/slave-mode.jelly
  core/src/main/resources/lib/form/textarea.jelly
  core/src/main/resources/lib/form/textbox.jelly
  core/src/main/resources/lib/layout/hasAdministerOrManage.jelly
  core/src/main/resources/lib/layout/layout.jelly
  test/src/test/java/hudson/security/ACLTest.java
  test/src/test/java/jenkins/model/JenkinsSystemReadAndManagePermissionTest.java
  test/src/test/java/jenkins/model/JenkinsSystemReadPermissionTest.java
  test/src/test/resources/jenkins/model/JenkinsSystemReadAndManagePermissionTest/Config/config.jelly
  war/src/main/webapp/css/style.css
Labels: developer, major-rfe, plugin-api-changes, ready-for-merge, squash-merge-me, web-ui

#4365 [JEP-223] Deprecate permissions RUN_SCRIPTS, UPLOAD_PLUGINS, and CONFIGURE_UPDATECENTER
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/cli/GroovyCommand.java
  core/src/main/java/hudson/cli/GroovyshCommand.java
  core/src/main/java/hudson/cli/InstallPluginCommand.java
  core/src/main/java/hudson/util/RemotingDiagnostics.java
  core/src/main/java/jenkins/management/ConsoleLink.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/security/s2m/AdminWhitelistRule.java
  core/src/main/java/jenkins/security/s2m/MasterKillSwitchConfiguration.java
  core/src/main/resources/hudson/Messages.properties
  core/src/main/resources/hudson/Messages_bg.properties
  core/src/main/resources/hudson/Messages_de.properties
  core/src/main/resources/hudson/Messages_fr.properties
  core/src/main/resources/hudson/Messages_it.properties
  core/src/main/resources/hudson/Messages_ja.properties
  core/src/main/resources/hudson/Messages_pt.properties
  core/src/main/resources/hudson/Messages_pt_BR.properties
  core/src/main/resources/hudson/Messages_sr.properties
  core/src/main/resources/hudson/Messages_zh_TW.properties
  core/src/main/resources/hudson/PluginManager/advanced.jelly
  core/src/main/resources/hudson/PluginManager/tabBar.jelly
  core/src/main/resources/hudson/model/Computer/sidepanel.jelly
  core/src/main/resources/hudson/model/Messages.properties
  core/src/main/resources/hudson/model/Messages_bg.properties
  core/src/main/resources/hudson/model/Messages_de.properties
  core/src/main/resources/hudson/model/Messages_es.properties
  core/src/main/resources/hudson/model/Messages_it.properties
  core/src/main/resources/hudson/model/Messages_ja.properties
  core/src/main/resources/hudson/model/Messages_lt.properties
  core/src/main/resources/hudson/model/Messages_pt_BR.properties
  core/src/main/resources/hudson/model/Messages_sr.properties
  core/src/main/resources/hudson/model/Messages_zh_TW.properties
  core/src/main/resources/jenkins/security/s2m/AdminWhitelistRule/index.jelly
  core/src/main/resources/lib/hudson/scriptConsole.jelly
  test/src/test/java/hudson/cli/GroovyshCommandTest.java
  test/src/test/java/jenkins/model/JenkinsTest.java
Labels: ready-for-merge, rfe, squash-merge-me, upgrade-guide-needed

#4514 Update note after this was done wrong yet again
  core/src/main/resources/jenkins/split-plugins.txt
Labels: ready-for-merge, skip-changelog

#4479 Read-only extended read view
  core/src/main/resources/hudson/model/Job/configure.jelly
  war/src/main/js/config-scrollspy.less
Labels: ready-for-merge, rfe, squash-merge-me

#4515 Listen on loopback interface by default in debug mode
  war/pom.xml
Labels: developer, ready-for-merge

#4470 Removed unused deprecated Memoizer
  core/src/main/java/hudson/util/Memoizer.java
Labels: developer, ready-for-merge, removed

#4516 Allow secret to convert to itself
  core/src/main/java/hudson/util/Secret.java
Labels: internal, ready-for-merge, skip-changelog

#4468 Removed unused class stringConverter2
  core/src/main/java/hudson/util/StringConverter2.java
Labels: developer, ready-for-merge, removed

#4520 JENKINS-61201 JEP-224 System read - about jenkins
  core/src/main/java/hudson/AboutJenkins.java
  core/src/main/java/hudson/PluginWrapper.java
  core/src/main/resources/hudson/AboutJenkins/index.jelly
  core/src/main/resources/hudson/PluginWrapper/thirdPartyLicenses.jelly
Labels: ready-for-merge, rfe, web-ui

#4524 JENKINS-61205 System read - global security configuration
  core/src/main/java/hudson/security/GlobalSecurityConfiguration.java
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/index.groovy
Labels: ready-for-merge, rfe

#4527 [JENKINS-61197] Skip $WORKSPACE_TMP for root directories
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/model/AbstractBuild.java
  core/src/main/java/hudson/model/WorkspaceCleanupThread.java
  core/src/main/java/hudson/slaves/WorkspaceList.java
  core/src/main/resources/jenkins/model/CoreEnvironmentContributor/buildEnv.properties
Labels: bug, ready-for-merge
