Repository jenkinsci/jenkins, pull requests merged in 2020-07, with the labels that each got.

#4818 JENKINS-56109 Compatible JavaScript changes for tables to divs
  core/src/main/resources/lib/form/advanced/advanced.js
  core/src/main/resources/lib/form/select/select.js
  core/src/main/resources/lib/layout/layout.jelly
  essentials.yml
  war/src/main/js/widgets/config/model/ConfigTableMetaData.js
  war/src/main/webapp/scripts/behavior.js
  war/src/main/webapp/scripts/hudson-behavior.js
  war/src/main/webapp/scripts/polyfills.js
Labels: internal, ready-for-merge, web-ui

#4812 [JENKINS-61823] - Winstone 5.9.1: Fix --httpKeepAliveTimeout option which had no effect (regression in 2.235.1)
  war/pom.xml
Labels: bug, into-lts

#4827 Backporting for LTS 2.235.2
  war/src/main/less/modules/buttons.less
Labels: into-lts

#4828 Fix JavaScript typo
  core/src/main/resources/lib/form/select/select.js
Labels: ready-for-merge, skip-changelog

#4773 JENKINS-62572: Extend Downloadable API slightly
  core/src/main/java/hudson/model/DownloadService.java
Labels: developer, ready-for-merge, squash-merge-me

#4826 [JENKINS-62889] ParameterDefinition check for validity
  core/src/main/java/hudson/model/ChoiceParameterDefinition.java
  core/src/main/java/hudson/model/JobParameterDefinition.java
  core/src/main/java/hudson/model/JobParameterValue.java
  core/src/main/java/hudson/model/ParameterDefinition.java
  core/src/test/java/hudson/model/ChoiceParameterDefinitionTest.java
Labels: developer, ready-for-merge, squash-merge-me

#4824 JENKINS-41805 Cleanup workspace suffixes
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/model/WorkspaceCleanupThread.java
  core/src/main/java/hudson/slaves/WorkspaceList.java
  core/src/test/java/hudson/FilePathTest.java
Labels: developer, ready-for-merge, rfe

#4758 [JENKINS-62949] - Escape special characters from href attrib
  core/src/main/java/hudson/console/HyperlinkNote.java
  test/src/test/java/hudson/console/HyperlinkNoteTest.java
Labels: bug, ready-for-merge

#4836 Update README: Governance, Adopters and more links
  README.md
Labels: ready-for-merge, skip-changelog

#4837 Document the weekly release line in README and the Maintainer guide
  README.md
  docs/MAINTAINERS.adoc
Labels: skip-changelog

#4831 Upgrade to 4.5 version of Remoting.
  pom.xml
Labels: internal, ready-for-merge, rfe

#4838 Remove BeanBuilder.loadBeans(String)
  core/src/main/java/hudson/util/spring/BeanBuilder.java
Labels: developer, plugin-api-changes, ready-for-merge

#4822 Added English localization for "orchestration"
  core/src/main/resources/hudson/model/Messages.properties
Labels: ready-for-merge, rfe, skip-changelog

#4823 Stop supporting .NET Framework 2.0 + Update Windows Service Wrapper from 2.3.0 to 2.9.0
  core/pom.xml
  core/src/main/java/hudson/lifecycle/WindowsInstallerLink.java
  core/src/main/java/hudson/util/jna/DotNet.java
  core/src/main/resources/hudson/lifecycle/Messages.properties
  core/src/main/resources/hudson/lifecycle/Messages_bg.properties
  core/src/main/resources/hudson/lifecycle/Messages_da.properties
  core/src/main/resources/hudson/lifecycle/Messages_de.properties
  core/src/main/resources/hudson/lifecycle/Messages_es.properties
  core/src/main/resources/hudson/lifecycle/Messages_it.properties
  core/src/main/resources/hudson/lifecycle/Messages_ja.properties
  core/src/main/resources/hudson/lifecycle/Messages_pl.properties
  core/src/main/resources/hudson/lifecycle/Messages_pt_BR.properties
  core/src/main/resources/hudson/lifecycle/Messages_sr.properties
  core/src/main/resources/hudson/lifecycle/Messages_zh_TW.properties
  core/src/main/resources/windows-service/jenkins.exe.config
  war/pom.xml
Labels: major-rfe, ready-for-merge, removed

#4843 Allow theming text area handle
  war/src/main/less/base/style.less
Labels: ready-for-merge, rfe, web-ui

#4841 [JENKINS-61806] Form validation for TimeZoneProperty.timeZoneName
  core/src/main/java/hudson/model/TimeZoneProperty.java
  core/src/main/resources/hudson/model/Messages.properties
  core/src/main/resources/hudson/model/TimeZoneProperty/config.properties
  core/src/main/resources/hudson/model/TimeZoneProperty/help-timeZoneName.html
Labels: ready-for-merge, rfe

#4839 [JENKINS-63014] Stop passing extra -url to agents
  core/src/main/resources/hudson/slaves/SlaveComputer/slave-agent.jnlp.jelly
Labels: bug, ready-for-merge

#4830 An UnsatisfiedLinkError from StandardOutputSwapper.ChannelSwapper.swap need not be reported
  core/src/main/java/jenkins/slaves/StandardOutputSwapper.java
Labels: bug, ready-for-merge

#4847 Document tips and tricks for the Jenkins issue triage
  docs/MAINTAINERS.adoc
Labels: internal

#4820 JENKINS-56109 Compatible CSS changes for tables to divs
  core/src/main/resources/jenkins/security/ApiTokenProperty/resources.css
  core/src/main/resources/lib/form/section_.css
  war/src/main/js/widgets/config/tabbar.less
  war/src/main/less/base/layout-commons.less
  war/src/main/less/base/style.less
Labels: internal, ready-for-merge, rfe, web-ui

#4073 [JENKINS-59136] Enable labels/categories with `deprecated` to show a warning for plugins
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/PluginWrapper.java
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/resources/hudson/Messages.properties
  core/src/main/resources/hudson/PluginManager/PluginDeprecationMonitor/message.jelly
  core/src/main/resources/hudson/PluginManager/PluginDeprecationMonitor/message.properties
  core/src/main/resources/hudson/PluginManager/installed.jelly
  core/src/main/resources/hudson/PluginManager/installed.properties
  core/src/main/resources/hudson/PluginManager/table.jelly
  core/src/main/resources/hudson/PluginManager/table.properties
  test/src/test/java/hudson/PluginManagerTest.java
  test/src/test/resources/plugins/deprecations-update-center.json
Labels: ready-for-merge, squash-merge-me, web-ui

#4833 [JENKINS-62723] Fix behaviour of Util.isOverridden()
  core/src/main/java/hudson/Util.java
  core/src/test/java/hudson/util/IsOverriddenTest.java
Labels: bug, ready-for-merge

#4834 [JENKINS-63022] Make Fingerprint Storage Engine configurable from the config page
  core/src/main/java/jenkins/fingerprints/FileFingerprintStorage.java
  core/src/main/java/jenkins/fingerprints/FingerprintStorage.java
  core/src/main/java/jenkins/fingerprints/FingerprintStorageDescriptor.java
  core/src/main/java/jenkins/fingerprints/GlobalFingerprintConfiguration.java
  core/src/main/resources/jenkins/fingerprints/GlobalFingerprintConfiguration/config.jelly
  core/src/main/resources/jenkins/fingerprints/Messages.properties
Labels: developer, ready-for-merge, rfe, squash-merge-me

#4845 Minor refactorings either for performance or readability
  cli/src/main/java/hudson/cli/CLI.java
  cli/src/main/java/hudson/cli/FlightRecorderInputStream.java
  cli/src/main/java/hudson/cli/PlainCLIProtocol.java
  cli/src/main/java/hudson/cli/PrivateKeyProvider.java
  cli/src/main/java/hudson/util/QuotedStringTokenizer.java
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/PluginWrapper.java
  core/src/main/java/hudson/model/Actionable.java
  core/src/main/java/hudson/security/csrf/CrumbFilter.java
  core/src/main/java/hudson/util/jna/Advapi32.java
  core/src/main/java/jenkins/util/xml/FilteredFunctionContext.java
  core/src/main/java/jenkins/util/xstream/XStreamDOM.java
Labels: internal, ready-for-merge, skip-changelog

#4846 tests: minor refactorings either for performance or readability
  test/src/test/java/hudson/PluginTest.java
  test/src/test/java/hudson/console/AnnotatedLargeTextTest.java
  test/src/test/java/hudson/model/AbstractItemSecurityTest.java
  test/src/test/java/hudson/model/AbstractItemTest.java
  test/src/test/java/hudson/model/FileParameterValueTest.java
  test/src/test/java/hudson/model/FingerprintTest.java
  test/src/test/java/hudson/model/ParametersAction2Test.java
  test/src/test/java/hudson/model/QueueTest.java
  test/src/test/java/hudson/model/UsageStatisticsTest.java
  test/src/test/java/hudson/model/ViewTest.java
  test/src/test/java/hudson/model/queue/LoadPredictorTest.java
  test/src/test/java/hudson/tasks/FingerprinterTest.java
  test/src/test/java/hudson/tools/ZipExtractionInstallerTest.java
  test/src/test/java/jenkins/model/JenkinsBuildsAndWorkspacesDirectoriesTest.java
  test/src/test/java/jenkins/security/apitoken/ApiTokenStatsRestartTest.java
  test/src/test/java/jenkins/security/apitoken/ApiTokenStatsTest.java
  test/src/test/java/jenkins/security/stapler/DoActionFilterTest.java
  test/src/test/java/jenkins/telemetry/impl/java11/MissingClassTelemetryFasterTest.java
Labels: internal, ready-for-merge, skip-changelog

#4842 Theme alert-* css classes and add alert-success
  war/src/main/less/abstracts/theme.less
  war/src/main/less/base/style.less
Labels: developer, ready-for-merge, rfe, web-ui

#4840 JENKINS-25259: added sortable+initialSortDir to tables at oldDataMonitor/manage.jelly + Error column name
  core/src/main/resources/hudson/diagnosis/OldDataMonitor/manage.jelly
Labels: ready-for-merge, rfe, web-ui

#4759 add compilerArg `-Xpkginfo:always` for useIncrementalCompilation which make build fast
  pom.xml
Labels: internal, ready-for-merge, skip-changelog

#4741 [JENKINS-60866] Un-inline layouts
  core/src/main/resources/lib/layout/html.jelly
  core/src/main/resources/lib/layout/layout.jelly
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: internal, ready-for-merge, web-ui

#4748 JENKINS-61806 Remove timestamp from page footer
  core/src/main/resources/lib/layout/layout.jelly
  core/src/main/resources/lib/layout/layout_ar.properties
  core/src/main/resources/lib/layout/layout_bg.properties
  core/src/main/resources/lib/layout/layout_ca.properties
  core/src/main/resources/lib/layout/layout_cs.properties
  core/src/main/resources/lib/layout/layout_da.properties
  core/src/main/resources/lib/layout/layout_de.properties
  core/src/main/resources/lib/layout/layout_el.properties
  core/src/main/resources/lib/layout/layout_es.properties
  core/src/main/resources/lib/layout/layout_es_AR.properties
  core/src/main/resources/lib/layout/layout_et.properties
  core/src/main/resources/lib/layout/layout_fi.properties
  core/src/main/resources/lib/layout/layout_fr.properties
  core/src/main/resources/lib/layout/layout_he.properties
  core/src/main/resources/lib/layout/layout_hu.properties
  core/src/main/resources/lib/layout/layout_it.properties
  core/src/main/resources/lib/layout/layout_ja.properties
  core/src/main/resources/lib/layout/layout_ko.properties
  core/src/main/resources/lib/layout/layout_lt.properties
  core/src/main/resources/lib/layout/layout_lv.properties
  core/src/main/resources/lib/layout/layout_nb_NO.properties
  core/src/main/resources/lib/layout/layout_nl.properties
  core/src/main/resources/lib/layout/layout_pl.properties
  core/src/main/resources/lib/layout/layout_pt.properties
  core/src/main/resources/lib/layout/layout_pt_BR.properties
  core/src/main/resources/lib/layout/layout_pt_PT.properties
  core/src/main/resources/lib/layout/layout_ro.properties
  core/src/main/resources/lib/layout/layout_ru.properties
  core/src/main/resources/lib/layout/layout_sk.properties
  core/src/main/resources/lib/layout/layout_sl.properties
  core/src/main/resources/lib/layout/layout_sr.properties
  core/src/main/resources/lib/layout/layout_sv_SE.properties
  core/src/main/resources/lib/layout/layout_tr.properties
  core/src/main/resources/lib/layout/layout_uk.properties
  core/src/main/resources/lib/layout/layout_zh_TW.properties
  war/src/main/less/modules/page-footer.less
Labels: ready-for-merge, rfe, web-ui

#4835 [JENKINS-63002] Revamp tabs and bigtables
  core/src/main/java/hudson/Functions.java
  core/src/main/resources/hudson/PluginManager/installed.jelly
  core/src/main/resources/hudson/PluginManager/table.jelly
  core/src/main/resources/hudson/model/ComputerSet/index.jelly
  core/src/main/resources/hudson/views/DefaultMyViewsTabBar/myViewTabs.jelly
  core/src/main/resources/hudson/views/DefaultViewsTabBar/viewTabs.jelly
  core/src/main/resources/lib/hudson/projectView.jelly
  core/src/main/resources/lib/layout/tabBar.jelly
  core/src/main/resources/lib/layout/tabNewItem.jelly
  war/src/main/less/abstracts/theme.less
  war/src/main/less/base-styles-v2.less
  war/src/main/less/base/style.less
  war/src/main/less/modules/panes-and-bigtable.less
  war/src/main/less/modules/side-panel-widgets.less
  war/src/main/less/modules/tabs.less
  war/src/main/webapp/images/material-icons/svg-sprite-content-symbol.svg
Labels: ready-for-merge, rfe, web-ui

#4856 Add .factorypath to .gitignore
  .gitignore
Labels: internal, skip-changelog

#4800 less cleanup to reduce warnings by stylelint
  war/src/main/less/abstracts/theme.less
  war/src/main/less/base/layout-commons.less
  war/src/main/less/base/style.less
  war/src/main/less/pluginSetupWizard.less
Labels: internal, ready-for-merge, skip-changelog

#4852 Reorder configuration and delete buttons
  core/src/main/resources/lib/hudson/project/configurable.jelly
Labels: ready-for-merge, rfe, web-ui

#4699 Converting tests to junit5
  core/pom.xml
  core/src/test/java/hudson/ClassicPluginStrategyTest.java
  core/src/test/java/hudson/EnvVarsTest.java
  core/src/test/java/hudson/MarkupTextTest.java
  core/src/test/java/hudson/PluginManagerTest.java
  core/src/test/java/hudson/PluginWrapperTest.java
  core/src/test/java/hudson/ProxyConfigurationTest.java
  core/src/test/java/hudson/console/UrlAnnotatorTest.java
  core/src/test/java/hudson/slaves/ComputerLauncherTest.java
  core/src/test/java/hudson/slaves/NodeListTest.java
  core/src/test/java/hudson/triggers/SCMTriggerTest.java
  core/src/test/java/jenkins/model/labels/LabelAutoCompleteSeederTest.java
  core/src/test/java/jenkins/util/AtmostOneTaskExecutorTest.java
  core/src/test/java/jenkins/util/TimerTest.java
  core/src/test/java/jenkins/util/UrlHelperTest.java
Labels: internal, ready-for-merge

#4855 Add compact rows variant to the .bigtable class
  core/src/main/resources/lib/hudson/projectView.jelly
  war/src/main/less/modules/panes-and-bigtable.less
Labels: ready-for-merge, rfe, web-ui

#4854 Add Jenkins modules to the Core Bill of Materials
  bom/pom.xml
  war/pom.xml
Labels: developer, ready-for-merge

#4853 Make sortable table footers less prominent
  war/src/main/less/modules/panes-and-bigtable.less
Labels: ready-for-merge, rfe, web-ui

#4851 Tests: Refactoring of various things
  test/src/test/java/hudson/LauncherTest.java
  test/src/test/java/hudson/cli/ListJobsCommandTest.java
  test/src/test/java/hudson/diagnosis/OldDataMonitorTest.java
  test/src/test/java/hudson/model/AbstractItemSecurityTest.java
  test/src/test/java/hudson/model/AbstractProjectTest.java
  test/src/test/java/hudson/model/DirectoryBrowserSupportTest.java
  test/src/test/java/hudson/model/FreestyleJobPublisherTest.java
  test/src/test/java/hudson/model/ItemsTest.java
  test/src/test/java/hudson/model/LabelLoadStatisticsQueueLengthTest.java
  test/src/test/java/hudson/model/ListViewTest.java
  test/src/test/java/hudson/model/ParametersTest.java
  test/src/test/java/hudson/model/RunSEC1902Test.java
  test/src/test/java/hudson/model/queue/LoadPredictorTest.java
  test/src/test/java/hudson/security/HudsonPrivateSecurityRealmTest.java
  test/src/test/java/hudson/security/TokenBasedRememberMeServices2Test.java
  test/src/test/java/hudson/tasks/FingerprinterTest.java
  test/src/test/java/hudson/tasks/LogRotatorTest.java
  test/src/test/java/lib/form/PasswordTest.java
  test/src/test/java/lib/form/RepeatablePropertyTest.java
Labels: internal, ready-for-merge, skip-changelog

#4849 Update detached plugin versions after security release
  pom.xml
  test/pom.xml
  war/pom.xml
Labels: ready-for-merge, rfe

#4817 [JENKINS-62755] Introduce Fingerprint Cleanup in External Storage API
  core/src/main/java/hudson/model/FingerprintCleanupThread.java
  core/src/main/java/jenkins/fingerprints/FileFingerprintStorage.java
  core/src/main/java/jenkins/fingerprints/FingerprintStorage.java
  core/src/main/java/jenkins/fingerprints/GlobalFingerprintConfiguration.java
  core/src/main/resources/jenkins/fingerprints/GlobalFingerprintConfiguration/config.jelly
  test/src/test/java/hudson/model/FingerprintCleanupThreadTest.java
Labels: developer, ready-for-merge

#4860 Change to digicert tsa for signing the war
  war/pom.xml
Labels: skip-changelog

#4857 Add the Core Infrastructure Initiative Badge to README
  README.md
Labels: internal, ready-for-merge, skip-changelog

#4862 Add badges for Regular and LTS releases
  README.md
Labels: internal, skip-changelog

#4858 Make plugin manager table headers alignment consistent
  core/src/main/resources/hudson/PluginManager/installed.jelly
Labels: ready-for-merge, rfe, web-ui

#4859 Use support-log-formatter from jetty:run
  core/src/main/java/hudson/WebAppMain.java
  war/pom.xml
Labels: internal, ready-for-merge, skip-changelog

#4864 [JENKINS-63168] Prevent NPE when calling CommandInterpreter#buildEnvVarsFilterRules
  core/src/main/java/hudson/tasks/CommandInterpreter.java
  test/src/test/java/hudson/tasks/CommandInterpreterTest.java
  test/src/test/resources/hudson/tasks/CommandInterpreterTest/jobs/a/config.xml
Labels: major-bug, ready-for-merge, regression-fix

#4861 [JENKINS 63160] Fix .pane-header text and background colors
  war/src/main/less/abstracts/theme.less
  war/src/main/less/modules/panes-and-bigtable.less
Labels: bug, ready-for-merge, web-ui

#4868 Change comment position that caused parse error
  war/src/main/less/modules/panes-and-bigtable.less
Labels: internal, ready-for-merge, skip-changelog

#4875 Add new line at EOF in config.xml
  test/src/test/resources/hudson/tasks/CommandInterpreterTest/jobs/a/config.xml
Labels: skip-changelog

#4879 UsageStatisticsTest failure: java.vendor vs. java.vm.vendor
  test/src/test/java/hudson/model/UsageStatisticsTest.java
Labels: internal, ready-for-merge, skip-changelog

#4870 [JENKINS-63180] - Wrap Tabbar items instead of overflowing (regression in 2.248)
  war/src/main/less/modules/tabs.less
Labels: bug, ready-for-merge, regression-fix, web-ui

#4865 Align plugin manager filter with table
  core/src/main/resources/hudson/PluginManager/_table.css
Labels: bug, ready-for-merge, skip-changelog, web-ui

#4869 Fix typo in Lithuanian translation.
  core/src/main/resources/hudson/model/AbstractProject/sidepanel_lt.properties
Labels: bug, ready-for-merge, skip-changelog
