Repository jenkinsci/jenkins, pull requests merged in 2020-12, with the labels that each got.

#5088 Automate uploading artifacts to GitHub releases
  .github/workflows/publish-release-artifact.yml
Labels: ready-for-merge, skip-changelog

#5072 Inline icon-set lib
  core/pom.xml
  core/src/main/java/org/jenkins/ui/icon/Icon.java
  core/src/main/java/org/jenkins/ui/icon/IconSet.java
  core/src/main/java/org/jenkins/ui/icon/IconSpec.java
  core/src/main/java/org/jenkins/ui/icon/IconType.java
Labels: developer, internal, ready-for-merge, squash-merge-me

#5087 Update yarn and updated node to latest LTS (14.15.1)
  war/pom.xml
Labels: internal, ready-for-merge

#5084 Set eslint env to node to fix eslint warnings
  war/.eslintrc.js
  war/postcss.config.js
Labels: internal, ready-for-merge, skip-changelog

#5092 Added script for fixing stylelint and applied it once
  war/package.json
  war/src/main/less/abstracts/theme.less
  war/src/main/less/base-styles-v2.less
  war/src/main/less/base/layout-commons.less
  war/src/main/less/base/style.less
  war/src/main/less/base/visibility-utils.less
  war/src/main/less/base/yui-compatibility.less
  war/src/main/less/modules/buttons.less
  war/src/main/less/modules/side-panel-tasks.less
  war/src/main/less/pluginSetupWizard.less
  war/src/main/less/ui-refresh-overrides.less
Labels: ready-for-merge, skip-changelog

#5095 Replace() optimization
  core/src/main/java/hudson/util/LineEndingConversion.java
  core/src/main/java/hudson/util/MaskingClassLoader.java
  core/src/main/java/org/jenkins/ui/icon/Icon.java
Labels: ready-for-merge, skip-changelog

#5090 [JENKINS-64330] Wrong unicode codes in spanish translation and small improvements
  core/src/main/resources/hudson/PluginManager/advanced_es.properties
Labels: localization, ready-for-merge

#5100 minor optimization as suggested by todo
  test/src/test/java/hudson/cli/ReloadConfigurationCommandTest.java
Labels: ready-for-merge, skip-changelog

#5099 JENKINS-64373 Add additional help locator fallback
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: bug, ready-for-merge, regression-fix

#5101 Replaced deprecated Exception.none with assertThrows
  core/src/test/java/hudson/UtilTest.java
  core/src/test/java/jenkins/util/io/PathRemoverTest.java
  test/src/test/java/hudson/security/ACLTest.java
Labels: ready-for-merge, skip-changelog

#5070 Replace slave on agent
  war/src/main/webapp/help/system-config/master-slave/clock_pt_BR.html
  war/src/main/webapp/help/system-config/master-slave/clock_tr.html
  war/src/main/webapp/help/system-config/master-slave/demand/idleDelay_tr.html
  war/src/main/webapp/help/system-config/master-slave/demand/inDemandDelay_tr.html
  war/src/main/webapp/help/system-config/master-slave/description_pt_BR.html
  war/src/main/webapp/help/system-config/master-slave/description_tr.html
  war/src/main/webapp/help/system-config/master-slave/numExecutors_pt_BR.html
  war/src/main/webapp/help/system-config/master-slave/numExecutors_tr.html
  war/src/main/webapp/help/system-config/master-slave/usage_pt_BR.html
  war/src/main/webapp/help/system-config/master-slave/usage_tr.html
Labels: bug, ready-for-merge

#5094 [JENKINS-41729] update to new localizer plugin version
  bom/pom.xml
  cli/pom.xml
  core/pom.xml
  pom.xml
Labels: dependencies, developer, ready-for-merge

#5057 UpdateCenter2Test.installInvalidChecksum timed out
  test/src/test/java/hudson/model/UpdateCenter2Test.java
Labels: internal, ready-for-merge, skip-changelog

#5091 [JENKINS-64329] Add Tradition Chinese translation for description of environment variables
  core/src/main/resources/jenkins/model/CoreEnvironmentContributor/buildEnv_zh_TW.properties
Labels: localization, ready-for-merge, rfe

#5051 JENKINS-64196 Move PluginManager available page to client side
  core/src/main/java/hudson/PluginManager.java
  core/src/main/resources/hudson/Messages.properties
  core/src/main/resources/hudson/PluginManager/available.jelly
  core/src/main/resources/hudson/PluginManager/tabBar.jelly
  core/src/main/resources/hudson/PluginManager/table.properties
  war/package.json
  war/src/main/js/api/pluginManager.js
  war/src/main/js/plugin-manager-ui.js
  war/src/main/js/templates/plugin-manager/available.hbs
  war/src/main/less/plugin-manager-ui.less
  war/src/main/webapp/scripts/polyfills.js
  war/webpack.config.js
  war/yarn.lock
Labels: bug, major-rfe, ready-for-merge, squash-merge-me, web-ui

#5104 [JENKINS-64393] update jupiter to fix not running junit4 tests
  cli/pom.xml
  core/pom.xml
  pom.xml
Labels: internal, skip-changelog

#5102 Remove bundled cvs plugin
  test/src/test/resources/hudson/ClassicPluginStrategyTest/testDisabledDependencyClassLoader.zip
  war/pom.xml
Labels: alternative, ready-for-merge, rfe, upgrade-guide-needed

#5097 [JENKINS-53720] is fixed already with spotbugs version update
  src/findbugs/findbugs-excludes.xml
Labels: internal, ready-for-merge, skip-changelog

#5075 JENKINS-64403 Declare the page variable "divBasedFormLayout" globally, not only inside forms
  core/src/main/java/hudson/Functions.java
  core/src/main/resources/lib/form/form.jelly
Labels: developer, ready-for-merge

#5106 LTS 2.263.2
  cli/pom.xml
  core/pom.xml
  core/src/main/resources/hudson/PluginManager/advanced_es.properties
  core/src/main/resources/lib/form/select/select.js
  pom.xml
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: into-lts

#5105 [JENKINS-64390] make FieldUtils behave as it used to
  core/src/main/java/org/acegisecurity/util/FieldUtils.java
  core/src/test/java/org/acegisecurity/util/FieldUtilsTest.java
  core/src/test/java/org/acegisecurity/util/OuterClassWithPublicFinalField.java
Labels: bug, ready-for-merge

#5108 Allow all updates from Dependabot
  .github/dependabot.yml
Labels: ready-for-merge, skip-changelog

#5120 Prevent Dependabot from updating Groovy
  .github/dependabot.yml
Labels: ready-for-merge, skip-changelog

#5113 JENKINS-64332 Set freestyle description font size correctly
  war/src/main/js/widgets/config/tabbar.less
Labels: bug, ready-for-merge, web-ui

#5114 JENKINS-64426 Don't tell user's to signup if they can't
  core/src/main/resources/hudson/model/AllView/noJob.groovy
  core/src/main/resources/hudson/model/AllView/noJob.properties
Labels: bug, ready-for-merge, web-ui

#5107 Remove traces from jquery-detached from core
  test/src/test/java/jenkins/model/AssetManagerTest.java
  war/pom.xml
Labels: internal, ready-for-merge, web-ui

#5130 Add comments for why dependabot updates are excluded
  .github/dependabot.yml
Labels: ready-for-merge, skip-changelog

#5121 [JENKINS-64445] - Fix null safety for plugin categories
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/model/UpdateSite.java
Labels: bug, ready-for-merge, regression-fix

#5109 Code cleanup
  core/src/main/java/hudson/ExtensionFinder.java
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/PluginWrapper.java
  core/src/main/java/hudson/logging/LogRecorder.java
  core/src/main/java/hudson/model/AbstractProject.java
  core/src/main/java/hudson/model/Node.java
  core/src/main/java/hudson/org/apache/tools/tar/TarInputStream.java
  core/src/main/java/hudson/org/apache/tools/tar/TarOutputStream.java
  core/src/main/java/hudson/scm/SCM.java
  core/src/main/java/hudson/security/ACLContext.java
  core/src/main/java/hudson/util/FormFieldValidator.java
  core/src/main/java/hudson/util/NoClientBindProtocolSocketFactory.java
  core/src/main/java/jenkins/FilePathFilterAggregator.java
  core/src/main/java/jenkins/widgets/HistoryPageFilter.java
  core/src/main/java/org/acegisecurity/acls/sid/Sid.java
  core/src/main/java/org/jenkins/ui/icon/Icon.java
  core/src/test/java/hudson/FunctionsTest.java
  core/src/test/java/hudson/cli/ListJobsCommandTest.java
  core/src/test/java/hudson/model/MockItem.java
  core/src/test/java/hudson/util/IsOverriddenTest.java
  core/src/test/java/hudson/util/io/ZipArchiverTest.java
  core/src/test/java/jenkins/widgets/HistoryPageFilterTest.java
  test/src/test/java/hudson/ExtensionListTest.java
  test/src/test/java/hudson/XMLFileTest.java
  test/src/test/java/hudson/cli/BuildCommandTest.java
  test/src/test/java/hudson/cli/CancelQuietDownCommandTest.java
  test/src/test/java/hudson/cli/QuietDownCommandTest.java
  test/src/test/java/hudson/cli/RunRangeCommandTest.java
  test/src/test/java/hudson/cli/UpdateViewCommandTest.java
  test/src/test/java/hudson/model/NodeTest.java
  test/src/test/java/hudson/model/ParametersAction2Test.java
  test/src/test/java/hudson/model/ProjectTest.java
  test/src/test/java/hudson/model/QueueTest.java
  test/src/test/java/hudson/security/csrf/DefaultCrumbIssuerSEC1704Test.java
  test/src/test/java/hudson/slaves/NodeProvisionerTest.java
  test/src/test/java/hudson/slaves/SlaveComputerTest.java
  test/src/test/java/hudson/tasks/LogRotatorTest.java
  test/src/test/java/hudson/tasks/MavenTest.java
  test/src/test/java/hudson/tools/InstallerTranslatorTest.java
  test/src/test/java/hudson/tools/ToolLocationNodePropertyTest.java
  test/src/test/java/jenkins/model/ExtensionTypeHierarchyTest.java
  test/src/test/java/jenkins/model/TransientActionFactoryTest.java
  test/src/test/java/jenkins/tasks/SimpleBuildWrapperTest.java
  test/src/test/java/jenkins/widgets/HistoryPageFilterCaseSensitiveSearchTest.java
  test/src/test/java/lib/form/RepeatableTest.java
Labels: internal, ready-for-merge, skip-changelog

#5122 Winstone 5.13: Update Eclipse Jetty from 9.4.33.v20201020 to 9.4.35.v20201120
  war/pom.xml
Labels: ready-for-merge, rfe

#5123 Remove support for queue.txt format (replaced by XML in 2009)
  core/src/main/java/hudson/model/Queue.java
Labels: ready-for-merge, removed, rfe

#4962 Replaced deprecated Configuration with SystemProperties
  core/src/main/java/hudson/lifecycle/ExitLifecycle.java
  core/src/main/java/hudson/model/AbstractCIBase.java
  core/src/main/java/jenkins/InitReactorRunner.java
  core/src/main/java/jenkins/model/Jenkins.java
Labels: ready-for-merge, rfe, upgrade-guide-needed

#5131 [JENKINS-64465] Fix race condition on HudsonFilter#reset
  core/src/main/java/hudson/security/HudsonFilter.java
Labels: bug, ready-for-merge

#5133 Do not show an empty tooltip on svg icons
  core/src/main/resources/lib/layout/svgIcon.jelly
Labels: ready-for-merge, skip-changelog

#5135 Update frontend-maven-plugin from 1.6 to 1.11.0
  war/pom.xml
Labels: dependencies, ready-for-merge, skip-changelog

#5137 [JENKINS-64504] stuck plugin manager buttons
  war/package.json
  war/src/main/js/plugin-manager-ui.js
  war/yarn.lock
Labels: bug, regression-fix

#5111 Update stapler to 1.262
  bom/pom.xml
Labels: ready-for-merge, rfe

#5132 [JENKINS-64483] Hide collapse link if it isn't possible
  core/src/main/resources/lib/layout/pane.jelly
Labels: ready-for-merge, rfe

#4965 [JENKINS-63833] Make the groovy script source customizable
  core/src/main/java/jenkins/util/groovy/GroovyHookScript.java
Labels: ready-for-merge, rfe, squash-merge-me

#5141 Fix broken 'download Maven here' link
  CONTRIBUTING.md
Labels: skip-changelog
