Repository jenkinsci/jenkins, pull requests merged in 2020-03, with the labels that each got.

#4529 [JENKINS-61004, JENKINS-60299] - Reintroduce Build History description truncation by default, allow managing/disabling the limit via a system property
  core/src/main/java/hudson/model/Run.java
  core/src/main/resources/hudson/widgets/HistoryWidget/entry.jelly
Labels: bug, ready-for-merge

#4525 [JENKINS-55070, 59992, 60454, 61192] Correct symptom of missing instance
  core/src/main/java/hudson/security/TokenBasedRememberMeServices2.java
Labels: bug, ready-for-merge

#4478 [JENKINS-28379] Allow FingerprintFacet to block the deletion of Fingerprint
  core/src/main/java/hudson/model/Fingerprint.java
  core/src/main/java/hudson/model/FingerprintCleanupThread.java
  core/src/main/java/jenkins/model/FingerprintFacet.java
Labels: developer, ready-for-merge

#4532 JENKINS-61279 Bump version-number
  core/pom.xml
Labels: internal, ready-for-merge

#4539 [JENKINS-60857] - Update Winstone to 5.8 in the 2.204.x baseline
  war/pom.xml
Labels: major-bug, ready-for-merge, regression-fix

#4537 JENKINS-61285 Fix blank page on configure clouds if no cloud plugin installed
  core/src/main/resources/jenkins/model/GlobalCloudConfiguration/index.groovy
Labels: bug, ready-for-merge, web-ui

#4540 [JENKINS-60788] Add null check to avoid NPE
  core/src/main/java/hudson/tools/DownloadFromUrlInstaller.java
Labels: bug

#4534 Improve presentation of plugin categories
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/resources/hudson/PluginManager/_table.css
  core/src/main/resources/hudson/PluginManager/_table.js
  core/src/main/resources/hudson/PluginManager/available.jelly
  core/src/main/resources/hudson/PluginManager/table.jelly
Labels: ready-for-merge, rfe, web-ui

#4513 [JENKINS-61166] Show on 'updates' tab when a warning would be fixed
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/resources/hudson/PluginManager/table.jelly
Labels: ready-for-merge, rfe

#4389 [JENKINS-60410] Add stack trace suppression into core as a standard behavior.
  core/pom.xml
  core/src/main/java/hudson/init/impl/InstallUncaughtExceptionHandler.java
  core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/security/ExceptionTranslationFilter.java
  core/src/main/resources/jenkins/model/Jenkins/oops.jelly
  core/src/main/resources/jenkins/security/Messages.properties
  core/src/main/resources/lib/form/apply/apply.js
  pom.xml
  test/pom.xml
  test/src/test/java/jenkins/security/StackTraceSuppressionTest.java
  war/pom.xml
Labels: ready-for-merge, rfe, squash-merge-me

#4535 Show plugin release date in plugin manager
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/resources/hudson/PluginManager/_table.css
  core/src/main/resources/hudson/PluginManager/table.jelly
  core/src/main/resources/hudson/PluginManager/table.properties
Labels: ready-for-merge, rfe, web-ui

#4541 [JENKINS-61321] Fix permission check
  core/src/main/resources/hudson/model/Job/configure.jelly
Labels: major-bug, ready-for-merge, regression-fix

#4522 [JENKINS-61300] Update search box size on page resize, max width
  core/src/main/resources/lib/layout/pageHeader.jelly
  war/src/main/less/modules/page-header.less
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: bug, ready-for-merge, web-ui

#4542 [JENKINS-60409, JENKINS-60199] - Upgrade Winstone from 5.8 to 5.9 to apply Jetty 9.4.24+ regression fixes
  war/pom.xml
Labels: major-bug, ready-for-merge, regression-fix

#4544 [JENKINS-61345] - Prevent unhandled JSONException in DescriptorList#newInstanceFromRadioList() and ExtensionDescriptorList#newInstanceFromRadioList()
  core/src/main/java/hudson/DescriptorExtensionList.java
  core/src/main/java/hudson/util/DescriptorList.java
Labels: bug, ready-for-merge

#3969 [FIX JENKINS-51495] descriptorRadioList does not honor DescriptorVisibilityFilter
  core/src/main/java/hudson/DescriptorExtensionList.java
  core/src/main/java/hudson/util/DescriptorList.java
  core/src/main/resources/lib/form/descriptorRadioList.jelly
  test/src/test/java/hudson/ExtensionListTest.java
Labels: ready-for-merge, rfe, squash-merge-me

#4559 [JENKINS-61398] Don't lose SCM configuration when saving job
  core/src/main/java/hudson/DescriptorExtensionList.java
  core/src/main/java/hudson/util/DescriptorList.java
  core/src/main/resources/lib/form/descriptorRadioList.jelly
  test/src/test/java/hudson/ExtensionListTest.java
Labels: ready-for-merge, regression-fix

#4558 [JENKINS-60409, JENKINS-60199] - Upgrade Winstone from 5.8 to 5.9 to apply Jetty 9.4.24+ and regression fixes in Jenkins 2.222.x
  war/pom.xml
Labels: into-lts, major-bug

#4553 Add inline security warnings to installed plugins list
  core/src/main/java/hudson/PluginWrapper.java
  core/src/main/resources/hudson/PluginManager/installed.jelly
  core/src/main/resources/hudson/PluginManager/installed.properties
Labels: ready-for-merge, rfe

#4561 Update bundled script-security plugin
  war/pom.xml
Labels: ready-for-merge, rfe

#4548 JENKINS-60921 Typography changes
  core/src/main/resources/hudson/PluginManager/_table.css
  core/src/main/resources/hudson/PluginManager/advanced.jelly
  core/src/main/resources/hudson/model/View/newJob.jelly
  core/src/main/resources/jenkins/install/SetupWizard/setupWizardConfigureInstance.jelly
  core/src/main/resources/jenkins/install/SetupWizard/setupWizardFirstUser.jelly
  core/src/main/resources/jenkins/model/Jenkins/manage.jelly
  core/src/main/resources/jenkins/security/ApiTokenProperty/resources.css
  core/src/main/resources/lib/layout/breadcrumbs.css
  core/src/main/resources/lib/layout/layout.jelly
  war/src/main/js/widgets/add/addform.less
  war/src/main/js/widgets/config/tabbar.less
  war/src/main/less/abstracts/colors.less
  war/src/main/less/abstracts/font.less
  war/src/main/less/base-styles-v2.less
  war/src/main/less/base/layout-commons.less
  war/src/main/less/base/style.less
  war/src/main/less/base/typography.less
  war/src/main/less/modules/page-header.less
  war/src/main/less/pluginSetupWizard.less
  war/src/main/less/ui-refresh-overrides.less
Labels: ready-for-merge, rfe

#4563 Bump ssh-cli-auth
  war/pom.xml
Labels: ready-for-merge, rfe

#4566 Adding translation for New View
  core/src/main/resources/jenkins/model/Messages_fr.properties
Labels: localization

#4457 [JENKINS-60866] Un-inline restarts pages
  core/src/main/resources/hudson/lifecycle/WindowsInstallerLink/_restart.jelly
  core/src/main/resources/hudson/lifecycle/WindowsInstallerLink/index.jelly
  core/src/main/resources/hudson/util/HudsonIsLoading/index.jelly
  core/src/main/resources/hudson/util/HudsonIsRestarting/index.jelly
  war/src/main/webapp/scripts/hudson-behavior.js
  war/src/main/webapp/scripts/loading.js
Labels: internal, ready-for-merge, web-ui

#4549 JENKINS-54662 JCasC support for usage statistics
  core/src/main/java/jenkins/model/Jenkins.java
Labels: ready-for-merge, rfe

#4568 [JENKINS-61429] Fix drag & drop for existing steps in job & folders forms
  war/src/main/js/widgets/config/tabbar.js
Labels: major-bug, ready-for-merge, regression-fix

#4576 [JENKINS 61429] Backport fix reorder steps in some forms
  war/src/main/js/widgets/config/tabbar.js
Labels: into-lts, major-bug, regression-fix

#4556 Fix: Jelly 'enum' tag 'default' attribute not working
  core/src/main/resources/lib/form/enum.jelly
  test/src/test/java/lib/form/EnumTest.java
  test/src/test/resources/lib/form/EnumTest/Form/noDefault.jelly
  test/src/test/resources/lib/form/EnumTest/Form/withDefault.jelly
Labels: bug, developer, ready-for-merge

#4543 Document nullability of newInstanceFromRadioList() methods and its callers
  core/src/main/java/hudson/DescriptorExtensionList.java
  core/src/main/java/hudson/util/DescriptorList.java
  core/src/main/java/jenkins/model/Jenkins.java
Labels: developer, ready-for-merge, squash-merge-me

#4555 [JENKINS-61224] Removing the "monitor[s] text next to the bell
  core/src/main/resources/jenkins/management/AdministrativeMonitorsDecorator/footer.jelly
  core/src/main/resources/jenkins/management/AdministrativeMonitorsDecorator/footer.properties
  core/src/main/resources/jenkins/management/AdministrativeMonitorsDecorator/footer_de.properties
  core/src/main/resources/jenkins/management/AdministrativeMonitorsDecorator/resources.css
  war/src/main/less/abstracts/colors.less
  war/src/main/less/ui-refresh-overrides.less
Labels: ready-for-merge, rfe, web-ui

#4565 Change UpdateSiteWarningsMonitor blurb punctuation
  core/src/main/resources/jenkins/security/UpdateSiteWarningsMonitor/message.properties
Labels: ready-for-merge, skip-changelog

#4546 Manage Jenkins with flow layout and categories
  core/src/main/java/hudson/AboutJenkins.java
  core/src/main/java/hudson/diagnosis/OldDataMonitor.java
  core/src/main/java/hudson/lifecycle/WindowsInstallerLink.java
  core/src/main/java/hudson/model/ManagementLink.java
  core/src/main/java/hudson/security/GlobalSecurityConfiguration.java
  core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java
  core/src/main/java/jenkins/management/CliLink.java
  core/src/main/java/jenkins/management/ConfigureLink.java
  core/src/main/java/jenkins/management/ConsoleLink.java
  core/src/main/java/jenkins/management/NodesLink.java
  core/src/main/java/jenkins/management/PluginsLink.java
  core/src/main/java/jenkins/management/ReloadLink.java
  core/src/main/java/jenkins/management/ShutdownLink.java
  core/src/main/java/jenkins/management/StatisticsLink.java
  core/src/main/java/jenkins/management/SystemInfoLink.java
  core/src/main/java/jenkins/management/SystemLogLink.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/tools/GlobalToolConfiguration.java
  core/src/main/resources/hudson/model/Messages.properties
  core/src/main/resources/jenkins/model/Jenkins/manage.jelly
  test/src/test/java/hudson/model/ManagementLinkTest.java
  war/src/main/less/base-styles-v2.less
  war/src/main/less/modules/manage-jenkins.less
Labels: plugin-api-changes, ready-for-merge, rfe, web-ui

#4573 [JENKINS-61465] Make checkAnyPermission work on non-AccessControlled
  core/src/main/java/hudson/Functions.java
  test/src/test/java/hudson/security/ACLTest.java
  test/src/test/resources/hudson/security/ACLTest/EitherPermission/index.jelly
Labels: ready-for-merge, rfe

#4564 Fixed spotbugs NP_NULL_ON_SOME_PATH
  core/src/main/java/hudson/ExtensionList.java
Labels: ready-for-merge, skip-changelog

#4581 Fix empty updates list
  core/src/main/resources/hudson/PluginManager/table.jelly
Labels: bug, regression-fix, skip-changelog, web-ui

#4587 Update at-since up to and including 2.226
  core/src/main/java/hudson/EnvVars.java
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/init/InitMilestone.java
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/model/Descriptor.java
  core/src/main/java/hudson/model/Executor.java
  core/src/main/java/hudson/model/Fingerprint.java
  core/src/main/java/hudson/model/ItemGroup.java
  core/src/main/java/hudson/model/Items.java
  core/src/main/java/hudson/model/ManagementLink.java
  core/src/main/java/hudson/model/RSS.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/java/hudson/security/ACL.java
  core/src/main/java/hudson/security/AccessControlled.java
  core/src/main/java/hudson/slaves/JNLPLauncher.java
  core/src/main/java/hudson/triggers/SafeTimerTask.java
  core/src/main/java/jenkins/model/FingerprintFacet.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/telemetry/Telemetry.java
  core/src/main/java/jenkins/websocket/WebSocketSession.java
  core/src/main/java/jenkins/websocket/WebSockets.java
  update-since-todo.sh
Labels: internal, ready-for-merge

#4584 Highlight when plugins have the adopt-this-plugin label
  core/src/main/java/hudson/PluginManager.java
  core/src/main/resources/hudson/PluginManager/installed.jelly
  core/src/main/resources/hudson/PluginManager/installed.properties
  core/src/main/resources/hudson/PluginManager/table.jelly
  core/src/main/resources/hudson/PluginManager/table.properties
Labels: ready-for-merge, rfe, web-ui

#4593 Rework sectioning on /manage and /pluginsManager/advanced
  core/src/main/resources/hudson/PluginManager/advanced.jelly
  core/src/main/resources/jenkins/model/Jenkins/manage.jelly
  war/src/main/less/base/style.less
  war/src/main/less/modules/manage-jenkins.less
Labels: ready-for-merge, rfe, skip-changelog

#4589 List failed plugins on Installed tab
  core/src/main/resources/hudson/PluginManager/installed.jelly
Labels: ready-for-merge, rfe, web-ui

#4578 Add Javadoc for the categories
  core/src/main/java/hudson/model/ManagementLink.java
Labels: developer, ready-for-merge, rfe

#4594 [JENKINS-61105] Add support for cross-compilation
  pom.xml
Labels: internal, java11, ready-for-merge

#4592 Increase context menu scroll speed
  core/src/main/resources/lib/layout/breadcrumbs.js
Labels: ready-for-merge, rfe, web-ui

#4590 [JENKINS-61308] Recommend more API like verb/URL to delete items
  core/src/main/java/hudson/model/AbstractItem.java
  core/src/main/resources/hudson/model/AbstractItem/_api.jelly
Labels: ready-for-merge, rfe

#4570 [JENKINS-61457] Allow Jenkins.MANAGE to configure UsageStatistics
  core/src/main/java/hudson/model/UsageStatistics.java
  test/src/test/java/jenkins/model/JenkinsManagePermissionTest.java
Labels: ready-for-merge, rfe

#4582 Limit max width of Manage Jenkins items on very large screens
  war/src/main/less/modules/manage-jenkins.less
Labels: ready-for-merge, rfe, web-ui

#4571 [JENKINS-61456] "System Information" is accessible with Jenkins.MANAGE
  core/src/main/java/hudson/diagnosis/MemoryUsageMonitor.java
  core/src/main/java/jenkins/management/SystemInfoLink.java
  core/src/main/resources/jenkins/model/Jenkins/systemInfo.jelly
Labels: ready-for-merge, rfe

#4595 [JENKINS-61521] Ignore RemoteClassLoader$ClassLoaderProxy#fetch3 on telemetry
  core/src/main/java/jenkins/telemetry/impl/java11/MissingClassTelemetry.java
Labels: java11, ready-for-merge

#4569 [JENKINS-61455] "About Jenkins" accessible with Jenkins.MANAGE
  core/src/main/java/hudson/AboutJenkins.java
  core/src/main/java/hudson/PluginWrapper.java
  core/src/main/resources/hudson/AboutJenkins/index.jelly
  core/src/main/resources/hudson/PluginWrapper/thirdPartyLicenses.jelly
  test/src/test/java/hudson/AboutJenkinsTest.java
Labels: ready-for-merge, rfe, squash-merge-me

#4596 [JENKINS-61409] Websockets: Use AbstractByteBufferCommandTransport to transport messages
  core/src/main/java/jenkins/agents/WebSocketAgents.java
  core/src/main/java/jenkins/websocket/WebSocketSession.java
  pom.xml
  test/src/test/java/jenkins/agents/WebSocketAgentsTest.java
Labels: bug

#4601 Upgrade to 4.3 version of Remoting.
  pom.xml
Labels: bug

#4585 Remove unused CSS file
  war/src/main/webapp/css/layout-common.css
  war/src/main/webapp/css/style.css
Labels: internal, ready-for-merge, skip-changelog

#4605 Do not print random binary data during WebSocketAgentsTest
  test/src/test/java/jenkins/agents/WebSocketAgentsTest.java
Labels: internal

#4602 [JENKINS-61688] Load build discarder configuration after restart
  core/src/main/java/jenkins/model/GlobalBuildDiscarderConfiguration.java
  test/src/test/java/jenkins/model/GlobalBuildDiscarderTest.java
  test/src/test/resources/jenkins/model/GlobalBuildDiscarderTest/testLoading/jenkins.model.GlobalBuildDiscarderConfiguration.xml
  test/src/test/resources/jenkins/model/GlobalBuildDiscarderTest/testLoadingWithDiscarders/jenkins.model.GlobalBuildDiscarderConfiguration.xml
Labels: major-bug, ready-for-merge

#4554 Update .NET version checks to be more correct when Windows services when installing master and agent on platforms with modern .NET versions
  core/src/main/java/hudson/lifecycle/WindowsInstallerLink.java
  core/src/main/java/hudson/util/jna/DotNet.java
  core/src/main/java/hudson/util/jna/RegistryKey.java
Labels: ready-for-merge, rfe

#4507 Static nested classes
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/TcpSlaveAgentListener.java
  core/src/main/java/hudson/cli/CLIAction.java
  core/src/main/java/hudson/fsp/WorkspaceSnapshotSCM.java
  core/src/main/java/hudson/util/XStream2.java
  core/src/main/java/jenkins/FilePathFilterAggregator.java
  core/src/test/java/hudson/BulkChangeTest.java
  core/src/test/java/hudson/model/AbstractItemTest.java
  core/src/test/java/hudson/model/EnvironmentContributingActionTest.java
  core/src/test/java/hudson/model/FingerprintCleanupThreadTest.java
  core/src/test/java/hudson/model/LoadStatisticsTest.java
  core/src/test/java/hudson/util/CyclicGraphDetectorTest.java
  core/src/test/java/hudson/util/IsOverriddenTest.java
  core/src/test/java/hudson/util/io/TarArchiverTest.java
  core/src/test/java/jenkins/util/MarkFindingOutputStreamTest.java
  test/src/test/java/hudson/ExtensionListListenerTest.java
  test/src/test/java/hudson/model/ApiSEC1704Test.java
  test/src/test/java/hudson/model/UpdateCenterConnectionStatusTest.java
  test/src/test/java/hudson/security/SecurityRealmTest.java
  test/src/test/java/hudson/security/WhoAmITest.java
  test/src/test/java/hudson/tools/ZipExtractionInstallerTest.java
  test/src/test/java/jenkins/security/stapler/DoActionFilterTest.java
Labels: internal, ready-for-merge, skip-changelog

#4607 [JENKINS-61692] Fix proxy form validation
  core/src/main/resources/hudson/ProxyConfiguration/config.groovy
Labels: bug, ready-for-merge, regression-fix

#3941 [JENKINS-56643] Util.createSymlink: prefer Files.move(..., ATOMIC_MOVE)
  core/src/main/java/hudson/Util.java
Labels: developer, ready-for-merge

#4075 IntelliJ/Java: Duplicate code -- Refactored as AntClassLoader.storeAndConvert(...Convert<T>)
  core/src/main/java/jenkins/util/AntClassLoader.java
Labels: ready-for-merge, skip-changelog

#4603 Let ConfidentialKey & Secret do something from unit tests
  core/pom.xml
  core/src/main/java/hudson/util/HistoricalSecrets.java
  core/src/main/java/hudson/util/Secret.java
  core/src/main/java/jenkins/security/ConfidentialStore.java
  core/src/main/java/jenkins/security/DefaultConfidentialStore.java
  core/src/main/java/jenkins/security/RSAConfidentialKey.java
  core/src/test/java/hudson/util/MockSecretRule.java
  core/src/test/java/hudson/util/SecretRewriterTest.java
  core/src/test/java/hudson/util/SecretTest.java
  core/src/test/java/jenkins/security/ConfidentialStoreRule.java
  test/src/test/java/jenkins/security/RekeySecretAdminMonitorTest.java
Labels: developer, internal, ready-for-merge

#4608 Support null Secrets when converting form submissions
  core/src/main/java/hudson/util/Secret.java
Labels: bug, ready-for-merge

#4612 Use a jenkins Changelog Generator App in the release drafting flow
  .github/workflows/changelog.yml
Labels: skip-changelog

#4613 Remove checkUpdates dead code
  core/src/main/resources/hudson/PluginManager/checkUpdates.jelly
  core/src/main/resources/hudson/PluginManager/checkUpdates_bg.properties
  core/src/main/resources/hudson/PluginManager/checkUpdates_da.properties
  core/src/main/resources/hudson/PluginManager/checkUpdates_de.properties
  core/src/main/resources/hudson/PluginManager/checkUpdates_es.properties
  core/src/main/resources/hudson/PluginManager/checkUpdates_fi.properties
  core/src/main/resources/hudson/PluginManager/checkUpdates_fr.properties
  core/src/main/resources/hudson/PluginManager/checkUpdates_it.properties
  core/src/main/resources/hudson/PluginManager/checkUpdates_ja.properties
  core/src/main/resources/hudson/PluginManager/checkUpdates_lv.properties
  core/src/main/resources/hudson/PluginManager/checkUpdates_nl.properties
  core/src/main/resources/hudson/PluginManager/checkUpdates_pt_BR.properties
  core/src/main/resources/hudson/PluginManager/checkUpdates_pt_PT.properties
  core/src/main/resources/hudson/PluginManager/checkUpdates_ru.properties
  core/src/main/resources/hudson/PluginManager/checkUpdates_sk.properties
  core/src/main/resources/hudson/PluginManager/checkUpdates_sr.properties
  core/src/main/resources/hudson/PluginManager/checkUpdates_sv_SE.properties
  core/src/main/resources/hudson/PluginManager/checkUpdates_zh_TW.properties
Labels: skip-changelog
