Repository jenkinsci/jenkins, pull requests merged in 2020-04, with the labels that each got.

#4552 JENKINS-56937 JCasC support for admin monitors
  core/src/main/java/hudson/model/AbstractCIBase.java
  core/src/main/java/hudson/model/AdministrativeMonitor.java
Labels: ready-for-merge, rfe, squash-merge-me

#4599 [JENKINS-61496] update page footer
  core/src/main/resources/lib/layout/layout.jelly
  war/src/main/less/abstracts/colors.less
  war/src/main/less/base-styles-v2.less
  war/src/main/less/base/layout-commons.less
  war/src/main/less/modules/page-footer.less
Labels: ready-for-merge, rfe, squash-merge-me, web-ui

#4572 [JENKINS-61453] Jenkins.MANAGE user to access "Prepare for Shutdown"
  core/src/main/java/jenkins/management/ShutdownLink.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/resources/lib/hudson/queue.jelly
Labels: ready-for-merge, rfe

#3947 [JENKINS-5597] add option to follow symlinks during artifact archiving
  bom/pom.xml
  core/src/main/java/hudson/tasks/ArtifactArchiver.java
  core/src/main/resources/hudson/tasks/ArtifactArchiver/config.jelly
  core/src/main/resources/hudson/tasks/ArtifactArchiver/config.properties
  core/src/main/resources/hudson/tasks/ArtifactArchiver/config_de.properties
  core/src/main/resources/hudson/tasks/ArtifactArchiver/help-followSymlinks.html
  core/src/main/resources/hudson/tasks/ArtifactArchiver/help-followSymlinks_de.html
  test/src/test/java/hudson/tasks/ArtifactArchiverTest.java
  test/src/test/resources/hudson/tasks/ArtifactArchiverTest/followSymlinksEnabledForOldConfig.zip
Labels: plugin-api-changes, ready-for-merge, rfe, squash-merge-me

#4606 [JENKINS-61694] - Update Groovy Init hooks to run after all job configurations are adapted
  core/src/main/java/hudson/init/InitMilestone.java
  core/src/main/java/hudson/init/impl/GroovyInitScript.java
Labels: bug, ready-for-merge

#4616 Hyperlinks in label-related CauseOfBlockage.print
  core/src/main/java/hudson/console/ModelHyperlinkNote.java
  core/src/main/java/hudson/model/queue/CauseOfBlockage.java
Labels: ready-for-merge, rfe

#4575 [JENKINS-61467] Do not show disabled, implied permissions in errors
  core/src/main/java/hudson/security/ACL.java
  test/src/test/java/hudson/security/ACLTest.java
  test/src/test/java/jenkins/security/StackTraceSuppressionTest.java
Labels: ready-for-merge, rfe, squash-merge-me

#4577 [JENKINS-61479] Fix java.lang.ClassCastException in FingerprintCleanupThread
  core/pom.xml
  core/src/main/java/hudson/model/FingerprintCleanupThread.java
  core/src/test/java/hudson/model/FingerprintCleanupThreadTest.java
Labels: bug, ready-for-merge, squash-merge-me

#4610 [JENKINS-61478] Style improvements to alert banners
  war/src/main/less/abstracts/colors.less
  war/src/main/less/base/style.less
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, rfe, web-ui

#4619 [JENKINS-61466] Ignore war/work and war/target on frontend tests
  war/jest.config.json
Labels: bug, internal, ready-for-merge, skip-changelog

#4598 Fix various "incompatible" messages for plugin manager
  core/src/main/resources/hudson/PluginManager/table.properties
Labels: ready-for-merge, rfe, skip-changelog

#4624 Revert "Use a jenkins Changelog Generator App in the release drafting flow"
  .github/workflows/changelog.yml
Labels: skip-changelog

#4597 Hide message re disabling implied dependencies when no dependents exist
  core/src/main/java/hudson/PluginWrapper.java
  core/src/main/resources/hudson/PluginManager/_table.js
  core/src/main/resources/hudson/PluginManager/installed.jelly
Labels: ready-for-merge, rfe

#4614 Use DirectoryBrowserSupport to serve FileParameterValue
  core/src/main/java/hudson/model/FileParameterValue.java
  core/src/main/resources/hudson/model/FileParameterValue/value.jelly
  core/src/main/resources/hudson/model/FileParameterValue/value.properties
  core/src/main/resources/hudson/model/Messages.properties
Labels: ready-for-merge, rfe

#4629 JENKINS-61660 - Fix spacing between error messages in Setup Wizard (regression in 2.217)
  war/src/main/less/pluginSetupWizard.less
Labels: bug, ready-for-merge, regression-fix, web-ui

#4618 Backporting for LTS 2.222.2
  core/pom.xml
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/security/TokenBasedRememberMeServices2.java
  core/src/main/java/hudson/tools/DownloadFromUrlInstaller.java
  core/src/main/java/jenkins/model/GlobalBuildDiscarderConfiguration.java
  core/src/main/resources/hudson/ProxyConfiguration/config.groovy
  test/src/test/java/hudson/security/ACLTest.java
  test/src/test/java/jenkins/model/GlobalBuildDiscarderTest.java
  test/src/test/resources/hudson/security/ACLTest/EitherPermission/index.jelly
  test/src/test/resources/jenkins/model/GlobalBuildDiscarderTest/testLoading/jenkins.model.GlobalBuildDiscarderConfiguration.xml
  test/src/test/resources/jenkins/model/GlobalBuildDiscarderTest/testLoadingWithDiscarders/jenkins.model.GlobalBuildDiscarderConfiguration.xml
Labels: into-lts

#4518 JENKINS-61203 System read - Plugin Manager
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/jenkins/management/PluginsLink.java
  core/src/main/resources/hudson/PluginManager/_api.jelly
  core/src/main/resources/hudson/PluginManager/advanced.jelly
  core/src/main/resources/hudson/PluginManager/index.jelly
  core/src/main/resources/hudson/PluginManager/installed.jelly
  core/src/main/resources/hudson/PluginManager/sidepanel.groovy
  core/src/main/resources/hudson/PluginManager/table.jelly
  core/src/main/resources/hudson/ProxyConfiguration/config.groovy
  core/src/main/resources/hudson/model/UpdateCenter/body.jelly
  core/src/main/resources/hudson/model/UpdateCenter/index.jelly
  core/src/main/resources/hudson/model/UpdateCenter/sidepanel.jelly
  war/src/main/less/base/style.less
Labels: ready-for-merge, rfe, squash-merge-me, web-ui

#4631 Bump crypto-util from 1.1 to 1.5
  core/pom.xml
Labels: bug, ready-for-merge

#4580 Pre-filter the 'Available' plugin manager tab, allow multiple terms
  core/src/main/resources/hudson/PluginManager/_table.css
  core/src/main/resources/hudson/PluginManager/_table.js
  core/src/main/resources/hudson/PluginManager/available.jelly
  core/src/main/resources/hudson/PluginManager/installed.jelly
  core/src/main/resources/hudson/PluginManager/table.jelly
Labels: ready-for-merge, rfe, squash-merge-me, web-ui

#4633 Improve the 'noJob' view immediately after setup
  core/src/main/resources/hudson/model/AllView/noJob.groovy
  core/src/main/resources/hudson/model/AllView/noJob.jelly
  core/src/main/resources/hudson/model/AllView/noJob.properties
  war/src/main/less/base/style.less
Labels: ready-for-merge, rfe, web-ui

#4632 Fixing console annotation masking in LogTaskListener
  core/src/main/java/hudson/util/LogTaskListener.java
  test/src/test/java/hudson/util/LogTaskListenerTest.java
Labels: bug, ready-for-merge

#4617 Reduce log level on notice about optional extensions
  core/src/main/java/hudson/ExtensionFinder.java
Labels: ready-for-merge, rfe

#4636 Commons codec cleanup
  bom/pom.xml
  core/src/main/java/hudson/cli/Connection.java
  core/src/main/java/hudson/console/ConsoleNote.java
  core/src/main/java/jenkins/security/ResourceDomainConfiguration.java
Labels: internal, ready-for-merge

#4621 An agent log record with numeric params could be unformattable on the master
  core/src/main/java/hudson/slaves/SlaveComputer.java
  test/src/test/java/hudson/logging/LogRecorderManagerTest.java
Labels: bug, ready-for-merge

#4557 Make TimeZoneProperty compatible with JCasc
  core/src/main/java/hudson/model/TimeZoneProperty.java
Labels: ready-for-merge, rfe

#4586 Add section titles to Manage Jenkins context menu
  core/src/main/java/jenkins/model/ModelObjectWithContextMenu.java
  core/src/main/resources/jenkins/model/Jenkins/manage.jelly
  core/src/main/resources/lib/layout/breadcrumbs.css
  core/src/main/resources/lib/layout/breadcrumbs.js
Labels: alternative, ready-for-merge, rfe, web-ui

#4609 Set httpOnly and secure on cookies to fix spotbugs issue
  core/src/main/java/jenkins/model/Jenkins.java
Labels: internal, ready-for-merge

#4638 Removing apparently unused Slave.labels
  core/src/main/java/hudson/model/Slave.java
Labels: internal, ready-for-merge, skip-changelog

#4650 [JENKINS-61878] Improve the queue/cancelItem endpoint API documentation
  core/src/main/resources/hudson/model/queue/_api.jelly
Labels: ready-for-merge, skip-changelog

#4653 [JENKINS-61711] Fix validateExecutable to allow Git plugin global config correctly report git executable in PATH
  core/src/main/java/hudson/util/DOSToUnixPathHelper.java
  test/src/test/java/hudson/util/FormValidationTest.java
Labels: bug, ready-for-merge, regression-fix

#4472 New maintainer guide
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  docs/MAINTAINERS.adoc
Labels: internal, ready-for-merge, squash-merge-me

#4628 [JENKINS-60866] Un-inline JavaScript/Style in Job views
  core/src/main/resources/hudson/lifecycle/WindowsInstallerLink/_restart.jelly
  core/src/main/resources/hudson/model/Computer/builds.jelly
  core/src/main/resources/hudson/model/Job/_api.jelly
  core/src/main/resources/hudson/model/Job/buildTimeTrend.jelly
  core/src/main/resources/hudson/model/Job/buildTimeTrend_resources.css
  core/src/main/resources/hudson/model/Job/buildTimeTrend_resources.js
  core/src/main/resources/hudson/model/Job/configure-entries.jelly
  core/src/main/resources/hudson/model/Job/configure.jelly
  core/src/main/resources/hudson/model/Job/index.jelly
  core/src/main/resources/hudson/model/Job/newInstanceDetail.jelly
  core/src/main/resources/hudson/model/Job/permalinks.jelly
  core/src/main/resources/hudson/model/Job/requirePOST.jelly
  core/src/main/resources/hudson/model/View/builds.jelly
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/signup.jelly
  core/src/main/resources/hudson/util/HudsonIsLoading/index.jelly
  core/src/main/resources/hudson/util/HudsonIsRestarting/index.jelly
  core/src/main/resources/jenkins/model/Jenkins/login.jelly
  core/src/main/resources/lib/layout/html.jelly
  core/src/main/resources/lib/layout/layout.jelly
  war/src/main/less/base/style.less
Labels: internal, ready-for-merge, web-ui

#4651 Make the timestamp on the footer more compact
  war/src/main/less/modules/page-footer.less
Labels: ready-for-merge, rfe, web-ui

#4659 [JENKINS-61932] Fix redirect URL
  core/src/main/resources/hudson/model/AllView/noJob.properties
Labels: ready-for-merge, skip-changelog

#4658 [JENKINS-61840] Restyle buttons
  core/src/main/resources/hudson/PluginManager/check.jelly
  core/src/main/resources/hudson/model/Job/configure.jelly
  core/src/main/resources/hudson/model/ListView/newJobButtonBar.jelly
  core/src/main/resources/hudson/model/View/newJobButtonBar.jelly
  core/src/main/resources/lib/form/advanced.jelly
  core/src/main/resources/lib/form/apply.jelly
  core/src/main/resources/lib/form/submit.jelly
  core/src/main/resources/lib/layout/copyButton/copyButton.css
  core/src/main/resources/lib/layout/layout.jelly
  test/src/test/java/hudson/PluginManagerCheckUpdateCenterTest.java
  war/src/main/js/widgets/add/addform.less
  war/src/main/js/widgets/config/tabbar.less
  war/src/main/less/abstracts/colors.less
  war/src/main/less/base-styles-v2.less
  war/src/main/less/base/style.less
  war/src/main/less/modules/buttons.less
Labels: ready-for-merge, rfe, web-ui

#4657 [JENKINS-61905] Forward Groovy view permission errors to login
  core/src/main/java/hudson/security/UnwrapSecurityExceptionFilter.java
  test/src/test/java/hudson/security/AccessDeniedException2Test.java
Labels: bug, ready-for-merge

#4661 Bump parent pom to 1.55
  pom.xml
Labels: ready-for-merge, skip-changelog

#4654 Fix comment about when this is set
  core/src/main/java/hudson/Main.java
Labels: internal, ready-for-merge, skip-changelog

#4588 Sort available plugins by popularity
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/resources/hudson/PluginManager/table.jelly
Labels: ready-for-merge, rfe, web-ui

#4519 JEP-224 System read - Global tool configuration
  core/src/main/java/jenkins/tools/GlobalToolConfiguration.java
  core/src/main/resources/hudson/tools/DownloadFromUrlInstaller/config.jelly
  core/src/main/resources/hudson/tools/ToolInstallation/global.jelly
  core/src/main/resources/jenkins/tools/GlobalToolConfiguration/index.groovy
  core/src/main/resources/lib/form/repeatable.jelly
Labels: ready-for-merge, rfe, web-ui

#4533 JENKINS-61208 System read - admin monitor pattern
  core/src/main/java/hudson/model/AdministrativeMonitor.java
  core/src/main/java/jenkins/diagnostics/RootUrlNotSetMonitor.java
  core/src/main/java/jenkins/management/AdministrativeMonitorsDecorator.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/resources/jenkins/diagnostics/RootUrlNotSetMonitor/message.jelly
Labels: ready-for-merge, rfe, web-ui

#4591 Allow linking to pre-filtered plugin manager pages, link from labels/…
  core/src/main/resources/hudson/PluginManager/_table.css
  core/src/main/resources/hudson/PluginManager/_table.js
  core/src/main/resources/hudson/PluginManager/installed.jelly
  core/src/main/resources/hudson/PluginManager/table.jelly
  core/src/main/resources/hudson/PluginManager/table.properties
Labels: ready-for-merge, rfe, web-ui

#4674 Fix rendering of links in the Maintainer guide
  docs/MAINTAINERS.adoc
Labels: skip-changelog

#4672 Removed unused imports
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/UDPBroadcastThread.java
  core/src/main/java/hudson/cli/CreateNodeCommand.java
  core/src/main/java/hudson/model/AbstractCIBase.java
  core/src/main/java/hudson/model/Descriptor.java
  core/src/main/java/hudson/model/FileParameterValue.java
  core/src/main/java/hudson/model/ItemGroup.java
  core/src/main/java/hudson/model/Label.java
  core/src/main/java/hudson/model/StringParameterDefinition.java
  core/src/main/java/hudson/model/TimeZoneProperty.java
  core/src/main/java/hudson/security/ACL.java
  core/src/main/java/jenkins/install/SetupWizard.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/security/ConfidentialStore.java
  core/src/main/java/jenkins/security/ExceptionTranslationFilter.java
  core/src/main/java/jenkins/security/HMACConfidentialKey.java
Labels: internal, ready-for-merge, skip-changelog

#4622 JENKINS-61812 Fix read only password
  core/src/main/resources/lib/form/password.jelly
Labels: bug, ready-for-merge

#4641 Refactoring CLICommand.java
  core/src/main/java/hudson/cli/CLICommand.java
Labels: internal, ready-for-merge, skip-changelog, squash-merge-me

#4615 [JENKINS-61738][2] Session hijacking protection hardening
  core/src/main/java/hudson/WebAppMain.java
  test/pom.xml
  test/src/test/java/hudson/util/BootFailureTest.java
  war/src/main/webapp/WEB-INF/web.xml
Labels: ready-for-merge, rfe, squash-merge-me

#4678 Reduce code duplication in SystemProperties
  core/src/main/java/jenkins/util/SystemProperties.java
Labels: internal, ready-for-merge, skip-changelog

#4682 Restore dropdown behaviour for comboboxes
  war/src/main/less/base-styles-v2.less
  war/src/main/less/base/yui-compatibility.less
Labels: bug, ready-for-merge, regression-fix

#4666 minor test refactoring
  core/src/test/java/hudson/model/ActionableTest.java
  core/src/test/java/hudson/model/EnvironmentContributingActionTest.java
Labels: ready-for-merge, skip-changelog

#4677 Slave.numExecutors should default to 1
  core/src/main/java/hudson/model/Slave.java
Labels: developer, ready-for-merge, rfe

#4676 [JENKINS-46669] Reword SetupWizard Continue as admin button
  core/src/main/resources/jenkins/install/pluginSetupWizard.properties
Labels: ready-for-merge, rfe

#4671 Test refactoring, mainly to use hamcrest matcher instead of deprecated junit assertThat
  core/src/test/java/hudson/FilePathTest.java
  core/src/test/java/hudson/util/ArgumentListBuilderTest.java
  core/src/test/java/hudson/util/AtomicFileWriterTest.java
  core/src/test/java/hudson/util/FileChannelWriterTest.java
  core/src/test/java/jenkins/security/ClassFilterImplSanityTest.java
  core/src/test/java/jenkins/security/DefaultConfidentialStoreTest.java
  core/src/test/java/jenkins/security/apitoken/ApiTokenStatsTest.java
Labels: internal, ready-for-merge, skip-changelog

#4669 Link from cloud configuration to pre-filtered plugin manager
  core/src/main/resources/jenkins/model/GlobalCloudConfiguration/index.groovy
Labels: ready-for-merge, skip-changelog

#4667 Removed unused deprecated HudsonExceptionNote
  core/src/main/java/hudson/console/HudsonExceptionNote.java
  core/src/main/java/hudson/model/TaskListener.java
Labels: developer, ready-for-merge, removed

#4530 JENKINS-61207 System read - logs
  core/src/main/java/hudson/logging/LogRecorder.java
  core/src/main/java/hudson/logging/LogRecorderManager.java
  core/src/main/java/jenkins/management/SystemLogLink.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/resources/hudson/logging/LogRecorder/configure.jelly
  core/src/main/resources/hudson/logging/LogRecorder/configure.properties
  core/src/main/resources/hudson/logging/LogRecorder/delete.jelly
  core/src/main/resources/hudson/logging/LogRecorder/index.jelly
  core/src/main/resources/hudson/logging/LogRecorder/sidepanel.jelly
  core/src/main/resources/hudson/logging/LogRecorderManager/index.jelly
  core/src/main/resources/hudson/logging/LogRecorderManager/levels.jelly
  core/src/main/resources/hudson/logging/LogRecorderManager/sidepanel.jelly
  core/src/test/java/hudson/logging/LogRecorderTest.java
Labels: ready-for-merge, rfe, web-ui

#4675 Fix available tab sort order and support popularity outside 0..1 range
  core/src/main/java/hudson/PluginManager.java
  core/src/main/resources/hudson/PluginManager/table.jelly
Labels: bug, ready-for-merge, regression-fix

#4663 Use new icons for help
  core/src/main/resources/hudson/logging/LogRecorderManager/index.jelly
  core/src/main/resources/hudson/logging/LogRecorderManager/levels.jelly
  core/src/main/resources/jenkins/model/identity/IdentityRootAction/index.jelly
  core/src/main/resources/jenkins/security/apitoken/LegacyApiTokenAdministrativeMonitor/manage.jelly
  core/src/main/resources/lib/form/helpLink.jelly
  core/src/main/resources/lib/hudson/help.jelly
  core/src/main/resources/lib/layout/helpIcon.jelly
  war/src/main/less/base-styles-v2.less
  war/src/main/less/modules/icons.less
Labels: ready-for-merge, rfe, squash-merge-me

#4664 [JENKINS-36720] Minor spotbugs issue regarding performance improvement
  core/src/main/java/hudson/model/PaneStatusProperties.java
Labels: internal, ready-for-merge, skip-changelog

#4665 Removed superflous dependency on findbugs.annotations on test pom
  test/pom.xml
Labels: ready-for-merge, skip-changelog

#4686 Add form validation warning when signup is enabled
  core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java
  core/src/main/resources/hudson/security/Messages.properties
Labels: ready-for-merge, skip-changelog

#4668 Indicate which plugin provides an UnprotectedRootAction
  core/src/main/resources/hudson/security/LegacySecurityRealm/config.groovy
  core/src/main/resources/hudson/security/LegacySecurityRealm/config.jelly
  core/src/main/resources/hudson/security/LegacySecurityRealm/config.properties
Labels: ready-for-merge, rfe

#4687 [JENKINS-62056] Fix ExtensionComponent#compareTo
  core/src/main/java/hudson/ExtensionComponent.java
  test/src/test/java/hudson/ExtensionListTest.java
Labels: bug, ready-for-merge

#4655 [JENKINS-61841] Limit the number of exceptions stored by CompositeIOException
  core/src/main/java/jenkins/util/io/CompositeIOException.java
  core/src/test/java/jenkins/util/io/PathRemoverTest.java
Labels: ready-for-merge, rfe

#4627 [JENKINS-60866] Un-inline JavaScript/Style in LogRecorder views
  core/src/main/resources/hudson/diagnosis/OldDataMonitor/manage.jelly
  core/src/main/resources/hudson/logging/LogRecorderManager/all.jelly
  core/src/main/resources/hudson/logging/LogRecorderManager/feeds.jelly
  core/src/main/resources/hudson/logging/LogRecorderManager/index.jelly
  core/src/main/resources/hudson/logging/LogRecorderManager/levels.jelly
  core/src/main/resources/hudson/logging/LogRecorderManager/new.jelly
  core/src/main/resources/hudson/logging/LogRecorderManager/sidepanel.jelly
  core/src/main/resources/hudson/model/View/AsynchPeople/index.jelly
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/index.jelly
  war/src/main/less/base/style.less
  war/src/main/webapp/scripts/sortable.js
Labels: internal, ready-for-merge, web-ui

#4626 [JENKINS-60866] Un-inline JavaScript from ReverseProxySetupMonitor
  core/src/main/java/hudson/diagnosis/ReverseProxySetupMonitor.java
  core/src/main/resources/hudson/diagnosis/ReverseProxySetupMonitor/message.jelly
  core/src/main/resources/hudson/diagnosis/ReverseProxySetupMonitor/message.properties
  core/src/main/resources/hudson/diagnosis/ReverseProxySetupMonitor/message_fr.properties
  core/src/main/resources/hudson/diagnosis/ReverseProxySetupMonitor/resources.css
  core/src/main/resources/hudson/diagnosis/ReverseProxySetupMonitor/resources.js
  test/src/test/java/hudson/diagnosis/ReverseProxySetupMonitorTest.java
Labels: internal, ready-for-merge, web-ui

#4691 Maintainer guide: Reference the IRC channel
  docs/MAINTAINERS.adoc
Labels: skip-changelog

#4695 [JENKINS-62089] Reduces the help icon size to 20px
  war/src/main/less/base/style.less
Labels: ready-for-merge, skip-changelog

#4660 Update javax.mail to 1.6.5
  core/pom.xml
Labels: developer, ready-for-merge

#4697 Extracts essential CSS off the responsive-grid.css file
  war/src/main/less/base-styles-v2.less
  war/src/main/less/base/layout-commons.less
  war/src/main/less/base/visibility-utils.less
  war/src/main/webapp/css/responsive-grid.css
Labels: ready-for-merge, skip-changelog

#4693 Add optional layout property to suppress loading of Bootstrap 3 grid
  core/src/main/resources/lib/layout/layout.jelly
Labels: developer, ready-for-merge

#4696 [JENKINS-62065] Breadcrumbs clickable after notification bar disappears
  war/src/main/less/base/style.less
Labels: bug, ready-for-merge, regression-fix
