Repository jenkinsci/jenkins, pull requests merged in 2021-05, with the labels that each got.

#5454 Remove some types no longer needed for JEP-200 compatibility
  core/src/main/resources/jenkins/security/whitelisted-classes.txt
Labels: ready-for-merge, rfe, upgrade-guide-needed

#5452 Remove HTTP response headers for the remoting-based CLI
  core/src/main/java/hudson/Functions.java
  test/src/test/java/hudson/cli/CLITest.java
Labels: internal, ready-for-merge

#5455 [JENKINS-64294] Buffer `stdin` for `jenkins-cli.jar`
  cli/src/main/java/hudson/cli/CLI.java
  core/src/main/java/hudson/cli/CLIAction.java
  test/src/test/java/hudson/cli/CLIActionTest.java
Labels: bug, ready-for-merge

#5456 Migrate some tests from `HudsonTestCase` to `JenkinsRule`
  test/src/test/java/hudson/ExceptionTest.java
  test/src/test/java/hudson/model/DependencyGraphTest.java
  test/src/test/java/hudson/model/DownloadServiceTest.java
  test/src/test/java/hudson/model/HelpLinkTest.java
  test/src/test/java/hudson/model/ViewPropertyTest.java
  test/src/test/java/hudson/slaves/EnvironmentVariableNodePropertyTest.java
  test/src/test/java/hudson/tasks/EnvVarsInConfigTasksTest.java
  test/src/test/java/hudson/tools/ToolLocationTest.java
  test/src/test/java/lib/form/AdvancedButtonTest.java
  test/src/test/java/lib/form/ComboBoxTest.java
  test/src/test/java/lib/form/DropdownListTest.java
  test/src/test/java/lib/layout/RenderOnDemandTest.java
  test/src/test/java/scripts/BehaviorTest.java
  test/src/test/resources/hudson/ExceptionTest/RootActionImpl/ajaxError.jelly
  test/src/test/resources/lib/form/AdvancedButtonTest/RootActionImpl/testNestedOptionalBlock.jelly
  test/src/test/resources/lib/form/AdvancedButtonTest/RootActionImpl/testSectionInsideOfAdvanced.jelly
  test/src/test/resources/lib/form/DropdownListTest/RootActionImpl/test1.jelly
  test/src/test/resources/lib/layout/RenderOnDemandTest/RootActionImpl/externalScript.jelly
  test/src/test/resources/lib/layout/RenderOnDemandTest/RootActionImpl/testBehaviour.jelly
  test/src/test/resources/lib/layout/RenderOnDemandTest/RootActionImpl/testScript.jelly
  test/src/test/resources/scripts/BehaviorTest/RootActionImpl/testCssSelectors.jelly
  test/src/test/resources/scripts/BehaviorTest/RootActionImpl/testDuplicateRegistrations.jelly
  test/src/test/resources/scripts/BehaviorTest/RootActionImpl/testSelectorOrdering.jelly
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5458 removed superfluous throws in tests
  core/src/test/java/hudson/FilePathTest.java
  core/src/test/java/hudson/FunctionsTest.java
  core/src/test/java/hudson/LauncherTest.java
  core/src/test/java/hudson/model/AbstractItemTest.java
  core/src/test/java/hudson/model/FingerprintTest.java
  core/src/test/java/hudson/model/TestUserIdMapper.java
  core/src/test/java/hudson/model/UserIdMapperTest.java
  core/src/test/java/hudson/model/ViewTest.java
  core/src/test/java/hudson/model/listeners/SCMListenerTest.java
  core/src/test/java/hudson/scheduler/CronTabTest.java
  core/src/test/java/hudson/util/DescribableListTest.java
  core/src/test/java/hudson/util/GraphTest.java
  core/src/test/java/hudson/util/MultipartFormDataParserTest.java
  core/src/test/java/hudson/util/RetrierTest.java
  core/src/test/java/hudson/util/RobustReflectionConverterTest.java
  core/src/test/java/hudson/util/SecretUtilTest.java
  core/src/test/java/jenkins/model/JenkinsLocationConfigurationTest.java
  core/src/test/java/jenkins/model/lazy/AbstractLazyLoadRunMapTest.java
  core/src/test/java/jenkins/security/RedactSecretJsonInErrorMessageSanitizerTest.java
  core/src/test/java/jenkins/util/VirtualFileTest.java
  core/src/test/java/jenkins/widgets/HistoryPageFilterTest.java
  core/src/test/java/jenkins/xml/XMLUtilsTest.java
  core/src/test/java/org/acegisecurity/util/FieldUtilsTest.java
Labels: ready-for-merge, skip-changelog

#5457 Ensure there are no unused imports with Spotless rather than Checkstyle
  CONTRIBUTING.md
  pom.xml
  test/src/test/java/jenkins/widgets/HistoryPageFilterCaseSensitiveSearchTest.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5453 Suppressed Spotbugs of type PREDICTABLE_RANDOM on not security relevant randoms
  core/src/main/java/hudson/model/AperiodicWork.java
  core/src/main/java/hudson/model/PeriodicWork.java
  core/src/main/java/hudson/scheduler/Hash.java
  core/src/main/java/hudson/tasks/Fingerprinter.java
  core/src/main/java/hudson/util/DoubleLaunchChecker.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5445 Remove bundled External Monitor Job Type, LDAP, and PAM Authentication plugins
  war/pom.xml
Labels: ready-for-merge, rfe, upgrade-guide-needed

#5465 [JENKINS-59412] No reason why `User/builds` or `View/builds` should not work with Pipeline
  core/src/main/java/hudson/model/User.java
  core/src/main/resources/hudson/model/User/builds.jelly
  core/src/main/resources/hudson/model/User/builds.properties
  core/src/main/resources/hudson/model/View/builds.jelly
  core/src/main/resources/hudson/model/View/builds.properties
Labels: ready-for-merge, rfe

#5463 Migrate remaining tests from `HudsonTestCase` to `JenkinsRule`
  test/src/test/java/hudson/ClassicPluginStrategyTest.java
  test/src/test/java/hudson/HtmlEscapeTest.java
  test/src/test/java/hudson/RelativePathTest.java
  test/src/test/java/hudson/model/GetEnvironmentOutsideBuildTest.java
  test/src/test/java/jenkins/security/RekeySecretAdminMonitorTest.java
  test/src/test/java/lib/form/EnumSetTest.java
  test/src/test/java/lib/form/RepeatablePropertyTest.java
  test/src/test/java/lib/form/RepeatableTest.java
  test/src/test/java/lib/form/RowVisibilityGroupTest.java
  test/src/test/resources/hudson/HtmlEscapeTest/RootActionImpl/foo.jelly
  test/src/test/resources/hudson/HtmlEscapeTest/RootActionImpl/foo.properties
  test/src/test/resources/hudson/RelativePathTest/RootActionImpl/index.groovy
  test/src/test/resources/lib/form/EnumSetTest/RootActionImpl/test1.jelly
  test/src/test/resources/lib/form/RepeatablePropertyTest/RootActionImpl/nested.jelly
  test/src/test/resources/lib/form/RepeatablePropertyTest/RootActionImpl/noDefault.jelly
  test/src/test/resources/lib/form/RepeatablePropertyTest/RootActionImpl/withDefault.jelly
  test/src/test/resources/lib/form/RepeatableTest/RootActionImpl/defaultForField.jelly
  test/src/test/resources/lib/form/RepeatableTest/RootActionImpl/defaultForItems.jelly
  test/src/test/resources/lib/form/RepeatableTest/RootActionImpl/testDropdownList.jelly
  test/src/test/resources/lib/form/RepeatableTest/RootActionImpl/testNested.jelly
  test/src/test/resources/lib/form/RepeatableTest/RootActionImpl/testNestedRadio.jelly
  test/src/test/resources/lib/form/RepeatableTest/RootActionImpl/testNestedRadioTopButton.jelly
  test/src/test/resources/lib/form/RepeatableTest/RootActionImpl/testNestedTopButton.jelly
  test/src/test/resources/lib/form/RepeatableTest/RootActionImpl/testNestedTopButtonInner.jelly
  test/src/test/resources/lib/form/RepeatableTest/RootActionImpl/testNestedTopButtonOuter.jelly
  test/src/test/resources/lib/form/RepeatableTest/RootActionImpl/testRadio.jelly
  test/src/test/resources/lib/form/RepeatableTest/RootActionImpl/testRadioBlock.jelly
  test/src/test/resources/lib/form/RepeatableTest/RootActionImpl/testSimple.jelly
  test/src/test/resources/lib/form/RepeatableTest/RootActionImpl/testSimpleWithDeleteButton.jelly
  test/src/test/resources/lib/form/RepeatableTest/RootActionImpl/testSimpleWithDeleteButtonTopButton.jelly
  test/src/test/resources/lib/form/RowVisibilityGroupTest/RootActionImpl/test1.jelly
  test/src/test/resources/lib/form/RowVisibilityGroupTest/RootActionImpl/test2.jelly
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5467 Deprecate `Util#join(Collection, String)` in favor of `String#join(CharSequence, Iterable)`
  core/src/main/java/hudson/EnvVars.java
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/Util.java
  core/src/main/java/hudson/model/Descriptor.java
  core/src/main/java/hudson/model/Executor.java
  core/src/main/java/hudson/model/Job.java
  core/src/main/java/hudson/os/SU.java
  core/src/main/java/hudson/tasks/LogRotator.java
  core/src/main/java/hudson/util/ClasspathBuilder.java
  core/src/main/java/hudson/util/CyclicGraphDetector.java
  core/src/main/java/hudson/util/FormValidation.java
  core/src/main/java/jenkins/MissingDependencyException.java
  core/src/main/java/jenkins/model/CoreEnvironmentContributor.java
  core/src/test/java/hudson/FunctionsTest.java
  test/src/test/java/hudson/util/ArgumentListBuilder2Test.java
Labels: ready-for-merge, skip-changelog

#5471 JENKINS-65574 Reverse direction of build-progress animation
  war/src/main/less/modules/icons.less
Labels: bug, ready-for-merge

#5464 Reduce usages of `com.google.common.collect` in favor of native Java functionality
  core/src/main/java/hudson/ExtensionFinder.java
  core/src/main/java/hudson/PluginWrapper.java
  core/src/main/java/hudson/model/AbstractBuild.java
  core/src/main/java/hudson/model/DependencyGraph.java
  core/src/main/java/hudson/model/Fingerprint.java
  core/src/main/java/hudson/model/Slave.java
  core/src/main/java/hudson/model/queue/BackFiller.java
  core/src/main/java/hudson/model/queue/MappingWorksheet.java
  core/src/main/java/hudson/security/Permission.java
  core/src/main/java/hudson/security/PermissionScope.java
  core/src/main/java/hudson/tasks/Fingerprinter.java
  core/src/main/java/hudson/util/PersistedList.java
  core/src/main/java/jenkins/InitReactorRunner.java
  core/src/main/java/jenkins/agents/WebSocketAgents.java
  core/src/main/java/jenkins/model/InterruptedBuildAction.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/plugins/DetachedPluginsUtil.java
  core/src/main/java/jenkins/scm/RunWithSCM.java
  core/src/main/java/jenkins/security/ClassFilterImpl.java
  core/src/main/java/jenkins/security/s2m/CallableRejectionConfig.java
  core/src/main/java/jenkins/security/s2m/CallableWhitelistConfig.java
  core/src/main/java/jenkins/security/s2m/FilePathRuleConfig.java
Labels: ready-for-merge, skip-changelog

#5469 Ensure files end with a newline with Spotless rather than Checkstyle
  cli/src/main/java/hudson/util/QuotedStringTokenizer.java
  core/src/main/java/hudson/cli/CopyJobCommand.java
  core/src/main/java/hudson/cli/CreateJobCommand.java
  core/src/main/java/hudson/cli/GroovyCommand.java
  core/src/main/java/hudson/cli/SessionIdCommand.java
  core/src/main/java/hudson/cli/UpdateJobCommand.java
  core/src/main/java/hudson/cli/WhoAmICommand.java
  core/src/main/java/hudson/cli/handlers/package-info.java
  core/src/main/java/hudson/diagnosis/ReverseProxySetupMonitor.java
  core/src/main/java/hudson/init/package-info.java
  core/src/main/java/hudson/model/AbstractBuild.java
  core/src/main/java/hudson/model/BuildableItemWithBuildWrappers.java
  core/src/main/java/hudson/model/DownloadService.java
  core/src/main/java/hudson/model/ResourceController.java
  core/src/main/java/hudson/model/TaskAction.java
  core/src/main/java/hudson/org/apache/tools/tar/TarOutputStream.java
  core/src/main/java/hudson/slaves/CloudProvisioningListener.java
  core/src/main/java/hudson/tasks/BuildWrapperDescriptor.java
  core/src/main/java/hudson/tasks/_maven/MavenErrorNote.java
  core/src/main/java/hudson/tools/ToolPropertyDescriptor.java
  core/src/main/java/hudson/util/AWTProblem.java
  core/src/main/java/hudson/util/CompoundEnumeration.java
  core/src/main/java/hudson/util/FlushProofOutputStream.java
  core/src/main/java/hudson/util/LineEndingConversion.java
  core/src/main/java/hudson/util/PersistedList.java
  core/src/main/java/hudson/views/GlobalDefaultViewConfiguration.java
  core/src/main/java/jenkins/model/Configuration.java
  core/src/main/java/jenkins/model/MasterBuildConfiguration.java
  core/src/main/java/jenkins/security/s2m/MasterKillSwitchConfiguration.java
  core/src/test/java/hudson/util/IsOverriddenTest.java
  pom.xml
  test/src/test/java/hudson/triggers/TriggerTest.java
  test/src/test/java/jenkins/security/SpySecurityListener.java
Labels: ready-for-merge, skip-changelog

#5451 Enable `AnnotationUseStyle`, `AvoidNoArgumentSuperConstructorCall`, and `NoEnumTrailingComma` Checkstyle checks
  core/src/main/java/hudson/cli/GroovyshCommand.java
  core/src/main/java/hudson/cli/declarative/CLIMethod.java
  core/src/main/java/hudson/cli/declarative/CLIResolver.java
  core/src/main/java/hudson/cli/declarative/MethodBinder.java
  core/src/main/java/hudson/cli/declarative/OptionHandlerExtension.java
  core/src/main/java/hudson/model/Actionable.java
  core/src/main/java/hudson/model/BallColor.java
  core/src/main/java/hudson/model/BooleanParameterDefinition.java
  core/src/main/java/hudson/model/Hudson.java
  core/src/main/java/hudson/model/ItemGroupMixIn.java
  core/src/main/java/hudson/model/PasswordParameterDefinition.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/scm/SCMDescriptor.java
  core/src/main/java/hudson/util/AlternativeUiTextProvider.java
  core/src/main/java/hudson/util/Iterators.java
  core/src/main/java/hudson/util/NoClientBindSSLProtocolSocketFactory.java
  core/src/main/java/hudson/util/PackedMap.java
  core/src/main/java/hudson/util/jna/SHELLEXECUTEINFO.java
  core/src/main/java/jenkins/PluginSubtypeMarker.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/tasks/filters/impl/RetainVariablesLocalRule.java
  core/src/main/java/jenkins/util/xml/RestrictiveEntityResolver.java
  core/src/main/java/org/jenkins/ui/icon/IconFormat.java
  core/src/main/java/org/jenkins/ui/icon/IconType.java
  core/src/test/java/hudson/model/StubJob.java
  core/src/test/java/hudson/model/listeners/SCMListenerTest.java
  core/src/test/java/hudson/slaves/ChannelPingerTest.java
  core/src/test/java/hudson/util/RunListTest.java
  core/src/test/java/jenkins/xml/XMLUtilsTest.java
  pom.xml
  test/src/test/java/hudson/cli/DisablePluginCommandTest.java
  test/src/test/java/hudson/model/AbstractItemSecurityTest.java
  test/src/test/java/hudson/model/UpdateCenterCustomTest.java
  test/src/test/java/hudson/model/ViewDescriptorTest.java
  test/src/test/java/hudson/tasks/BatchFileTest.java
  test/src/test/java/hudson/tasks/ShellTest.java
  test/src/test/java/jenkins/security/stapler/DoActionFilterTest.java
  test/src/test/java/lib/layout/SvgIconTest.java
Labels: ready-for-merge, skip-changelog

#5422 [JENKINS-65442] - Improve performance when encoding unicode characters in JSON API + Remove Stapler's Guava dependency
  bom/pom.xml
Labels: dependencies, ready-for-merge, rfe, squash-merge-me

#5468 Remove Guava test library
  bom/pom.xml
  core/pom.xml
  core/src/test/java/hudson/slaves/ChannelPingerTest.java
Labels: dependencies, ready-for-merge, skip-changelog, squash-merge-me

#5486 [JENKINS-65611] Ensure facets are modifiable
  core/src/main/java/hudson/model/Fingerprint.java
  test/src/test/java/hudson/model/FingerprintTest.java
Labels: major-bug, ready-for-merge, regression-fix, squash-merge-me

#5462 Lessen the severity of the unavailable update message
  core/src/main/resources/hudson/PluginManager/_table.css
  core/src/main/resources/hudson/PluginManager/table.properties
  war/src/main/less/plugin-manager-ui.less
Labels: ready-for-merge, rfe

#5489 [JENKINS-65605] Bridge methods are no longer present
  pom.xml
  test/src/test/java/jenkins/bugs/BridgeMethodsTest.java
Labels: ready-for-merge, regression-fix

#5483 Remove usages of deprecated (in Java 9 and above) `Class#newInstance`
  core/src/main/java/hudson/ClassicPluginStrategy.java
  core/src/main/java/hudson/cli/CLICommand.java
  core/src/main/java/hudson/cli/Connection.java
  core/src/main/java/hudson/lifecycle/Lifecycle.java
  core/src/main/java/hudson/model/ComputerSet.java
  core/src/main/java/hudson/model/Descriptor.java
  core/src/main/java/hudson/util/DescribableList.java
  core/src/main/java/hudson/util/PersistedList.java
  core/src/main/java/jenkins/ClassLoaderReflectionToolkit.java
  core/src/main/java/jenkins/model/lazy/LazyBuildMixIn.java
  core/src/main/java/jenkins/util/AntWithFindResourceClassLoader.java
  core/src/test/java/hudson/util/SubClassGeneratorTest.java
  test/src/test/java/hudson/tools/ZipExtractionInstallerTest.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5492 Change old issue references from #... to JENKINS-...
  core/src/main/java/hudson/Util.java
  core/src/main/java/hudson/WebAppMain.java
  core/src/main/java/hudson/model/BallColor.java
  core/src/main/java/hudson/model/Job.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/scm/SCM.java
  core/src/main/java/hudson/security/AuthenticationProcessingFilter2.java
  core/src/main/java/hudson/security/HudsonFilter.java
  core/src/main/java/hudson/security/RememberMeServicesProxy.java
  core/src/main/java/hudson/tasks/BuildTrigger.java
  core/src/main/java/hudson/util/ChartUtil.java
  core/src/main/java/jenkins/model/Jenkins.java
  test/src/test/java/jenkins/security/BasicHeaderProcessorTest.java
Labels: ready-for-merge, skip-changelog

#5488 Stop sharing plugin versions between the WAR and tests
  pom.xml
  test/pom.xml
  war/pom.xml
Labels: dependencies, ready-for-merge, skip-changelog

#5473 Deprecate `LinesStream` in favor of `Stream<String>`
  core/src/main/java/hudson/util/TextFile.java
  core/src/main/java/jenkins/security/s2m/ConfigFile.java
  core/src/main/java/jenkins/util/io/LinesStream.java
Labels: ready-for-merge, skip-changelog

#5450 Remove queue locking requirement when adding new nodes
  core/src/main/java/hudson/model/AbstractCIBase.java
  core/src/main/java/hudson/slaves/NodeProvisioner.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/model/Nodes.java
Labels: ready-for-merge, rfe, squash-merge-me

#5497 [INFRA-2890] Remove unused configuration of `maven-site-plugin`
  core/pom.xml
  pom.xml
  src/site/apt/index.apt
  src/site/resources/jenkins_logo.png
  src/site/site.xml
Labels: ready-for-merge, skip-changelog

#5498 [JENKINS-65657] Update xstream to 1.4.17
  bom/pom.xml
Labels: dependencies, ready-for-merge

#5470 Backporting for LTS 2.289.1
  cli/src/main/java/hudson/cli/CLI.java
  core/src/main/java/hudson/cli/CLIAction.java
  core/src/main/java/hudson/util/io/ZipArchiver.java
  core/src/test/java/hudson/util/io/ZipArchiverTest.java
  pom.xml
  test/src/test/java/hudson/cli/CLIActionTest.java
  test/src/test/java/jenkins/bugs/BridgeMethodsTest.java
  war/src/main/less/modules/side-panel-widgets.less
  war/src/main/webapp/scripts/yui/button/button-debug.js
  war/src/main/webapp/scripts/yui/button/button-min.js
Labels: into-lts

#5506 [JENKINS-65273] fix SSH CLI authentication
  cli/pom.xml
Labels: ready-for-merge, regression-fix

#5500 Remove `-noverify` workaround
  core/pom.xml
  pom.xml
Labels: ready-for-merge, skip-changelog

#5508 [JENKINS-65273] Backport to LTS
  cli/pom.xml
Labels: into-lts

#5499 [JENKINS-65398] terminology update in French for controller.
  core/src/main/resources/hudson/model/Node/help-numExecutors_fr.html
  core/src/main/resources/hudson/model/Slave/help-remoteFS_fr.html
Labels: localization, ready-for-merge, squash-merge-me

#5522 Fix `CatchAndPrintStackTrace`, `CatchFail`, and `EmptyCatch` Error Prone violations in tests
  core/src/test/java/hudson/util/SecretUtilTest.java
  core/src/test/java/jenkins/util/VirtualFileTest.java
  test/src/test/java/hudson/cli/QuietDownCommandTest.java
  test/src/test/java/hudson/model/JobTest.java
  test/src/test/java/hudson/model/QueueTest.java
  test/src/test/java/hudson/model/queue/WideExecutionTest.java
  test/src/test/java/hudson/util/XStream2Security383Test.java
  test/src/test/java/jenkins/security/stapler/CustomRoutingDecisionProviderTest.java
  test/src/test/java/jenkins/security/stapler/DoActionFilterTest.java
  test/src/test/java/jenkins/security/stapler/StaplerAbstractTest.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5461 [JENKINS-64991] Redirect to previous page after login
  core/src/main/java/hudson/security/AuthenticationProcessingFilter2.java
  core/src/main/java/hudson/security/SecurityRealm.java
  core/src/main/java/jenkins/security/AuthenticationSuccessHandler.java
  test/src/test/java/jenkins/bugs/Jenkins64991Test.java
Labels: bug, ready-for-merge, squash-merge-me

#5472 Show implied plugin dependencies
  core/src/main/java/hudson/PluginWrapper.java
  core/src/main/resources/hudson/PluginManager/_table.js
  core/src/main/resources/hudson/PluginManager/installed.jelly
  core/src/main/resources/hudson/PluginManager/installed.properties
Labels: ready-for-merge, rfe, web-ui

#5479 [JENKINS-65585] Fix requestSubmit() usage
  test/src/test/java/jenkins/security/RekeySecretAdminMonitorTest.java
  war/src/main/webapp/scripts/yui/button/button-debug.js
  war/src/main/webapp/scripts/yui/button/button-min.js
Labels: bug, ready-for-merge, regression-fix

#5521 Remove JTidy from core
  bom/pom.xml
  core/pom.xml
Labels: dependencies, developer, ready-for-merge, upgrade-guide-needed

#5529 Use semver range to exclude jetty major versions
  .github/dependabot.yml
Labels: skip-changelog

#5516 Fix redirect link
  core/src/main/resources/hudson/model/Messages.properties
  core/src/main/resources/hudson/model/Messages_bg.properties
  core/src/main/resources/hudson/model/Messages_es.properties
  core/src/main/resources/hudson/model/Messages_fr.properties
  core/src/main/resources/hudson/model/Messages_it.properties
  core/src/main/resources/hudson/model/Messages_lt.properties
  core/src/main/resources/hudson/model/Messages_pt_BR.properties
  core/src/main/resources/hudson/model/Messages_sr.properties
  core/src/main/resources/hudson/model/Messages_zh_TW.properties
Labels: ready-for-merge, skip-changelog

#5525 Reduce usages of repackaged ASM 5
  bom/pom.xml
  core/pom.xml
  core/src/main/java/hudson/util/SubClassGenerator.java
Labels: dependencies, ready-for-merge, skip-changelog, squash-merge-me

#5536 Checkbox missing fill color
  war/src/main/webapp/css/simple-page-forms.css
  war/src/main/webapp/css/simple-page-variables.css
Labels: bug, ready-for-merge, web-ui
