Repository jenkinsci/jenkins, pull requests merged in 2021-10, with the labels that each got.

#5769 Punctuation error
  docs/MAINTAINERS.adoc
Labels: skip-changelog

#5773 Upgrade detached plugins to versions with Guava compatibility fixes
  test/src/test/java/hudson/model/AbstractProjectTest.java
  war/pom.xml
Labels: ready-for-merge, rfe, squash-merge-me, dependencies

#5772 Replaced volatile int with AtomicInt to fix spotbugs
  core/src/main/java/hudson/util/RingBufferLogHandler.java
Labels: ready-for-merge, skip-changelog

#5761 Minor test refactorings
  test/src/test/java/hudson/diagnosis/OldDataMonitorTest.java
  test/src/test/java/hudson/model/JobTest.java
  test/src/test/java/hudson/model/QueueTest.java
  test/src/test/java/hudson/model/UsageStatisticsTest.java
  test/src/test/java/hudson/tasks/BatchFileTest.java
  test/src/test/java/hudson/tasks/ShellTest.java
  test/src/test/java/lib/form/HeteroListTest.java
  test/src/test/java/org/kohsuke/stapler/Security1097Test.java
Labels: ready-for-merge, skip-changelog

#5755 Log the stack trace when `ComputerListener.onOnline` fails
  core/src/main/java/hudson/slaves/SlaveComputer.java
  test/src/test/java/hudson/slaves/SlaveComputerTest.java
Labels: ready-for-merge, rfe

#5774 Suppress some Spotbugs `MS_SHOULD_BE_FINAL`
  core/src/main/java/hudson/ClassicPluginStrategy.java
  core/src/main/java/hudson/model/DownloadService.java
  core/src/main/java/hudson/model/WorkspaceCleanupThread.java
  core/src/main/java/hudson/slaves/CloudRetentionStrategy.java
  core/src/main/java/hudson/tasks/Fingerprinter.java
  core/src/main/java/jenkins/security/SuspiciousRequestFilter.java
  core/src/main/java/jenkins/slaves/DefaultJnlpSlaveReceiver.java
  core/src/main/java/jenkins/slaves/StandardOutputSwapper.java
Labels: ready-for-merge, skip-changelog

#5752 Enable Warnings Next Generation
  Jenkinsfile
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/model/User.java
  core/src/main/java/hudson/slaves/CloudProvisioningListener.java
  core/src/main/java/hudson/slaves/DumbSlave.java
  core/src/main/java/hudson/slaves/NodeProperty.java
  core/src/main/java/jenkins/util/io/CompositeIOException.java
  pom.xml
Labels: ready-for-merge, skip-changelog, squash-merge-me
