Repository jenkinsci/jenkins, pull requests merged in 2021-06, with the labels that each got.

#5540 Winstone 5.18: Update Jetty from 9.4.40.v20210413 to 9.4.41.v20210516
  war/pom.xml
Labels: dependencies, ready-for-merge

#5537 `CycleDetectedException` needs to call `Object#toString()`
  core/src/main/java/hudson/util/CyclicGraphDetector.java
Labels: bug, ready-for-merge

#5510 Fix `BadImport` Error Prone violations
  core/src/main/java/hudson/ExtensionFinder.java
  core/src/main/java/hudson/cli/BuildCommand.java
  core/src/main/java/hudson/cli/ListChangesCommand.java
  core/src/main/java/hudson/model/AbstractBuild.java
  core/src/main/java/hudson/model/DependencyGraph.java
  core/src/main/java/hudson/model/DownloadService.java
  core/src/main/java/hudson/model/Fingerprint.java
  core/src/main/java/hudson/model/FullDuplexHttpChannel.java
  core/src/main/java/hudson/model/Queue.java
  core/src/main/java/hudson/model/ResourceList.java
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/java/hudson/model/UsageStatistics.java
  core/src/main/java/hudson/model/View.java
  core/src/main/java/hudson/model/queue/BackFiller.java
  core/src/main/java/hudson/model/queue/MappingWorksheet.java
  core/src/main/java/hudson/node_monitors/AbstractAsyncNodeMonitorDescriptor.java
  core/src/main/java/hudson/node_monitors/ResponseTimeMonitor.java
  core/src/main/java/hudson/scm/ChangeLogAnnotator.java
  core/src/main/java/hudson/scm/ChangeLogParser.java
  core/src/main/java/hudson/tasks/Fingerprinter.java
  core/src/main/java/hudson/util/ArgumentListBuilder.java
  core/src/main/java/hudson/util/ProcessTree.java
  core/src/main/java/jenkins/PluginSubtypeMarker.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/model/lazy/BuildReferenceMapAdapter.java
  core/src/main/java/jenkins/model/lazy/LazyLoadRunMapEntrySet.java
  core/src/main/java/jenkins/security/UserDetailsCache.java
  core/src/main/java/jenkins/util/xstream/XStreamDOM.java
  core/src/test/java/hudson/util/ConsistentHashTest.java
  core/src/test/java/hudson/util/PackedMapTest.java
  core/src/test/java/jenkins/model/lazy/AbstractLazyLoadRunMapTest.java
  test/src/test/java/hudson/cli/ComputerStateTest.java
  test/src/test/java/hudson/model/NodeTest.java
  test/src/test/java/hudson/model/SlaveTest.java
  test/src/test/java/hudson/scm/ChangeLogSetTest.java
  test/src/test/java/hudson/slaves/EnvironmentVariableNodePropertyTest.java
  test/src/test/java/hudson/tasks/MavenTest.java
  test/src/test/java/hudson/triggers/SCMTriggerTest.java
  test/src/test/java/hudson/util/FormFieldValidatorTest.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5538 Change the word 'number' to 'integer' in number field message
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, rfe, web-ui

#5526 Remove Bytecode Compatibility Transformer
  bom/pom.xml
  core/pom.xml
  core/src/main/java/hudson/ClassicPluginStrategy.java
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/model/AbstractProject.java
  core/src/main/java/hudson/model/Queue.java
Labels: dependencies, developer, ready-for-merge, removed, squash-merge-me, upgrade-guide-needed

#5474 JENKINS-65577 Add admin monitor recommending java 11 for controller
  core/src/main/java/jenkins/monitor/JavaVersionRecommendationAdminMonitor.java
  core/src/main/resources/jenkins/monitor/JavaVersionRecommendationAdminMonitor/message.jelly
  core/src/main/resources/jenkins/monitor/JavaVersionRecommendationAdminMonitor/message.properties
  core/src/main/resources/jenkins/monitor/Messages.properties
Labels: ready-for-merge, rfe, squash-merge-me

#5533 Make `View` a `DescriptorByNameOwner`
  core/src/main/java/hudson/model/View.java
Labels: developer, ready-for-merge

#5541 Replace usage of `com.google.common.collect.HashMultimap` with native Java equivalent
  core/src/main/java/hudson/tasks/LogRotator.java
Labels: ready-for-merge, skip-changelog

#5543 [JENKINS-65751] Do not change fonts when artifacts are as shown as tree
  core/src/main/resources/lib/hudson/artifactList.jelly
Labels: bug, ready-for-merge, web-ui

#5320 Remove of commons-digester from core
  bom/pom.xml
  core/pom.xml
  core/src/main/java/hudson/util/Digester2.java
  core/src/test/java/hudson/util/Digester2Test.java
Labels: dependencies, developer, java, ready-for-merge, removed

#5544 Migrate from `RestartableJenkinsRule` to `JenkinsSessionRule`
  test/src/test/java/hudson/model/AbstractItem2Test.java
  test/src/test/java/hudson/model/RunActionTest.java
  test/src/test/java/hudson/model/UserRestartTest.java
  test/src/test/java/jenkins/install/SetupWizardRestartTest.java
  test/src/test/java/jenkins/security/BasicHeaderApiTokenAuthenticatorTest.java
  test/src/test/java/jenkins/security/Security637Test.java
  test/src/test/java/jenkins/security/apitoken/ApiTokenStatsRestartTest.java
  test/src/test/java/jenkins/security/seed/UserSeedPropertyRestartTest.java
Labels: ready-for-merge, skip-changelog

#5550 [JENKINS-65766] `ClassLoaderReflectionToolkit._findClass` was ignoring `getClassLoadingLock` on `AntClassLoader`
  core/src/main/java/jenkins/ClassLoaderReflectionToolkit.java
Labels: bug, ready-for-merge

#5520 Fix content security policy tests
  test/src/test/java/hudson/model/DirectoryBrowserSupportTest.java
  test/src/test/java/hudson/model/FileParameterValueTest.java
Labels: ready-for-merge, skip-changelog

#5554 Bump parent POM from 1.63 to 1.64
  pom.xml
  src/findbugs/findbugs-excludes.xml
Labels: dependencies, ready-for-merge, skip-changelog

#5548 [JENKINS-65195, JENKINS-64347] Fixes to ProcessTree implementation on Darwin
  core/src/main/java/hudson/util/ProcessTree.java
  core/src/main/java/hudson/util/jna/GNUCLibrary.java
Labels: bug, ready-for-merge

#5564 Upgrade ATH to version that uses https for artifactory
  essentials.yml
Labels: skip-changelog

#5559 Remove StAX from WAR
  bom/pom.xml
  core/pom.xml
Labels: dependencies, ready-for-merge, skip-changelog, squash-merge-me

#5552 Remove duplicate AOP classes in classpath
  core/pom.xml
Labels: dependencies, ready-for-merge, skip-changelog, squash-merge-me

#5553 Prefer `ArrayList` and `ArrayDeque` to `LinkedList`
  core/src/main/java/hudson/ExtensionFinder.java
  core/src/main/java/hudson/model/Job.java
  core/src/main/java/hudson/tools/DownloadFromUrlInstaller.java
  core/src/main/java/hudson/util/CharSpool.java
  core/src/main/java/jenkins/tasks/SimpleBuildStep.java
  core/src/main/java/jenkins/triggers/ReverseBuildTrigger.java
  core/src/main/java/jenkins/util/VirtualFile.java
  core/src/test/java/hudson/model/ParametersActionTest.java
  test/src/test/java/jenkins/security/SecurityContextExecutorServiceTest.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5555 Add X-Frame-Options for ajaxXxx requests
  core/src/main/resources/lib/layout/ajax.jelly
Labels: ready-for-merge, rfe

#5556 Documenting `Computer` REST methods `toggleOffline` & `changeOfflineCause`
  core/src/main/resources/hudson/model/Computer/_api.jelly
Labels: ready-for-merge, rfe

#5514 [JENKINS-60866] Clean up build button column JS
  core/src/main/resources/hudson/views/BuildButtonColumn/column.jelly
  core/src/main/resources/hudson/views/BuildButtonColumn/icon.js
  core/src/main/resources/lib/layout/icon.jelly
  core/src/main/resources/lib/layout/svgIcon.jelly
Labels: ready-for-merge, skip-changelog

#5573 Backporting for 2.289.2
  bom/pom.xml
  core/src/main/java/hudson/security/AuthenticationProcessingFilter2.java
  core/src/main/java/hudson/security/SecurityRealm.java
  core/src/main/java/hudson/util/ProcessTree.java
  core/src/main/java/hudson/util/jna/GNUCLibrary.java
  core/src/main/java/jenkins/ClassLoaderReflectionToolkit.java
  core/src/main/java/jenkins/security/AuthenticationSuccessHandler.java
  core/src/main/resources/lib/hudson/artifactList.jelly
  essentials.yml
  test/src/test/java/jenkins/bugs/Jenkins64991Test.java
  test/src/test/java/jenkins/security/RekeySecretAdminMonitorTest.java
  war/pom.xml
  war/src/main/webapp/scripts/yui/button/button-debug.js
  war/src/main/webapp/scripts/yui/button/button-min.js
Labels: into-lts

#5579 chore: bump ath Docker image to 1.97-pre to fix ATH runs
  essentials.yml
Labels: skip-changelog

#5560 Remove `jna-posix`
  core/pom.xml
  core/src/main/java/hudson/os/PosixAPI.java
  core/src/main/java/hudson/os/PosixException.java
  core/src/main/java/hudson/util/IOUtils.java
  licenseCompleter.groovy
Labels: dependencies, developer, ready-for-merge, squash-merge-me, upgrade-guide-needed

#5565 Implement `InterceptingExecutorService` without Guava
  core/src/main/java/jenkins/util/InterceptingExecutorService.java
Labels: dependencies, developer, ready-for-merge, squash-merge-me

#5575 Remove meaningless @since
  core/src/main/java/jenkins/security/AuthenticationSuccessHandler.java
Labels: ready-for-merge, skip-changelog

#5571 lib/form/RepeatableTest: tables-to-divs
  test/src/test/resources/lib/form/RepeatableTest/RootActionImpl/defaultForField.jelly
  test/src/test/resources/lib/form/RepeatableTest/RootActionImpl/defaultForItems.jelly
  test/src/test/resources/lib/form/RepeatableTest/RootActionImpl/testDropdownList.jelly
  test/src/test/resources/lib/form/RepeatableTest/RootActionImpl/testNested.jelly
  test/src/test/resources/lib/form/RepeatableTest/RootActionImpl/testNestedRadio.jelly
  test/src/test/resources/lib/form/RepeatableTest/RootActionImpl/testNestedRadioTopButton.jelly
  test/src/test/resources/lib/form/RepeatableTest/RootActionImpl/testNestedTopButton.jelly
  test/src/test/resources/lib/form/RepeatableTest/RootActionImpl/testNestedTopButtonInner.jelly
  test/src/test/resources/lib/form/RepeatableTest/RootActionImpl/testNestedTopButtonOuter.jelly
  test/src/test/resources/lib/form/RepeatableTest/RootActionImpl/testRadioBlock.jelly
  test/src/test/resources/lib/form/RepeatableTest/RootActionImpl/testSimple.jelly
  test/src/test/resources/lib/form/RepeatableTest/RootActionImpl/testSimpleWithDeleteButton.jelly
  test/src/test/resources/lib/form/RepeatableTest/RootActionImpl/testSimpleWithDeleteButtonTopButton.jelly
Labels: ready-for-merge, skip-changelog

#5568 Minor Refactoring: Use try with resources in PluginManager
  core/src/main/java/hudson/PluginManager.java
Labels: ready-for-merge, skip-changelog

#5582 Terminology cleanup: Internal and Javadoc changes
  core/src/main/java/hudson/EnvVars.java
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/Launcher.java
  core/src/main/java/hudson/TcpSlaveAgentListener.java
  core/src/main/java/hudson/cli/CLICommand.java
  core/src/main/java/hudson/model/AbstractBuild.java
  core/src/main/java/hudson/model/AbstractCIBase.java
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/model/DirectoryBrowserSupport.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/model/Slave.java
  core/src/main/java/hudson/model/WorkspaceBrowser.java
  core/src/main/java/hudson/security/GlobalSecurityConfiguration.java
  core/src/main/java/hudson/slaves/JNLPLauncher.java
  core/src/main/java/hudson/slaves/SlaveComputer.java
  core/src/main/java/hudson/tools/ToolDescriptor.java
  core/src/main/java/hudson/tools/ToolInstallation.java
  core/src/main/java/jenkins/install/SetupWizard.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/model/MasterBuildConfiguration.java
  core/src/main/java/jenkins/slaves/JnlpSlaveAgentProtocol.java
  core/src/main/java/jenkins/util/io/OnMaster.java
  core/src/main/resources/hudson/model/AbstractBuild/index.jelly
  core/src/test/java/hudson/LauncherTest.java
  test/src/test/java/hudson/bugs/JnlpAccessWithSecuredHudsonTest.java
  test/src/test/java/hudson/cli/CreateNodeCommandTest.java
  test/src/test/java/hudson/cli/GetNodeCommandTest.java
  test/src/test/java/hudson/cli/UpdateNodeCommandTest.java
  test/src/test/java/hudson/model/ComputerConfigDotXmlTest.java
  test/src/test/java/hudson/model/NodeTest.java
  test/src/test/java/hudson/model/UsageStatisticsTest.java
  test/src/test/java/hudson/model/labels/LabelExpressionTest.java
  test/src/test/java/hudson/slaves/EnvironmentVariableNodePropertyTest.java
  test/src/test/java/hudson/slaves/JNLPLauncherTest.java
  test/src/test/java/hudson/slaves/NodeCanTakeTaskTest.java
  test/src/test/java/hudson/slaves/NodeProvisionerTest.java
  test/src/test/java/hudson/slaves/SlaveComputerTest.java
  test/src/test/java/hudson/tasks/EnvVarsInConfigTasksTest.java
  test/src/test/java/jenkins/agents/WebSocketAgentsTest.java
  test/src/test/java/jenkins/model/JenkinsLocationConfigurationTest.java
  test/src/test/java/jenkins/model/JenkinsReloadConfigurationTest.java
  test/src/test/java/jenkins/model/MasterBuildConfigurationTest.java
  test/src/test/java/jenkins/model/NodeListenerTest.java
  test/src/test/java/jenkins/model/UnlabeledLoadStatisticsTest.java
  test/src/test/java/jenkins/security/ClassFilterImplTest.java
  test/src/test/java/jenkins/security/Security218Test.java
  test/src/test/java/jenkins/security/s2m/AdminFilePathFilterTest.java
  test/src/test/java/jenkins/util/JenkinsJVMRealTest.java
  test/src/test/java/jenkins/widgets/BuildTimeTrendTest.java
  test/src/test/resources/hudson/model/node.xml
Labels: internal, skip-changelog

#5496 [JENKINS-37694] Display artifacts of a running build
  core/src/main/resources/lib/hudson/artifactList.jelly
  core/src/main/resources/lib/hudson/artifactList.properties
Labels: ready-for-merge, rfe

#5574 Fix `ChainingConstructorIgnoresParameter` Error Prone violation
  core/src/main/java/org/acegisecurity/userdetails/User.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5563 FreeBSD support in `ProcessTree`
  core/src/main/java/hudson/util/ProcessTree.java
Labels: ready-for-merge, rfe, squash-merge-me

#5390 Use system properties and declared some suggested static properties final
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/Plugin.java
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/diagnosis/HudsonHomeDiskUsageChecker.java
  core/src/main/java/hudson/logging/LogRecorderManager.java
  core/src/main/java/hudson/model/AbstractItem.java
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/model/FileParameterValue.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/model/User.java
  core/src/main/java/hudson/scm/SCMRevisionState.java
  core/src/main/java/hudson/search/Search.java
  core/src/main/java/hudson/security/GlobalSecurityConfiguration.java
  core/src/main/java/hudson/util/ChartUtil.java
  core/src/main/java/hudson/util/ColorPalette.java
  core/src/main/java/hudson/util/io/ArchiverFactory.java
  core/src/main/java/jenkins/install/SetupWizard.java
  core/src/main/java/jenkins/model/IdStrategy.java
  core/src/main/java/jenkins/model/StandardArtifactManager.java
  core/src/main/java/jenkins/tools/GlobalToolConfiguration.java
  core/src/main/java/jenkins/util/xstream/XStreamDOM.java
Labels: ready-for-merge, skip-changelog

#5589 Upgrade Winstone 5.19 which include Jetty 9.4.42.v20210604
  war/pom.xml
Labels: dependencies, java, ready-for-merge

#5590 Remove unused resources
  core/src/main/resources/hudson/model/AgentSlave/config.jelly
  core/src/main/resources/hudson/model/AgentSlave/config_bg.properties
  core/src/main/resources/hudson/model/AgentSlave/config_da.properties
  core/src/main/resources/hudson/model/AgentSlave/config_de.properties
  core/src/main/resources/hudson/model/AgentSlave/config_es.properties
  core/src/main/resources/hudson/model/AgentSlave/config_fr.properties
  core/src/main/resources/hudson/model/AgentSlave/config_it.properties
  core/src/main/resources/hudson/model/AgentSlave/config_ja.properties
  core/src/main/resources/hudson/model/AgentSlave/config_pt_BR.properties
  core/src/main/resources/hudson/model/AgentSlave/config_sr.properties
  core/src/main/resources/hudson/model/AgentSlave/config_tr.properties
  core/src/main/resources/hudson/model/AgentSlave/config_zh_TW.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Scheduled/config.jelly
  core/src/main/resources/hudson/slaves/RetentionStrategy/Scheduled/config_bg.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Scheduled/config_da.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Scheduled/config_de.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Scheduled/config_es.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Scheduled/config_fr.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Scheduled/config_it.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Scheduled/config_ja.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Scheduled/config_pt_BR.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Scheduled/config_ru.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Scheduled/config_sr.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Scheduled/config_tr.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Scheduled/config_zh_TW.properties
Labels: ready-for-merge, skip-changelog

#5591 Fix comma splice
  core/src/main/resources/jenkins/monitor/JavaVersionRecommendationAdminMonitor/message.properties
Labels: ready-for-merge, skip-changelog
