Repository jenkinsci/jenkins, pull requests merged in 2021-12, with the labels that each got.

#5991 Enable `RequireThis` Checkstyle check
  pom.xml
Labels: skip-changelog

#5977 Enable `SuperFinalize` Checkstyle check
  core/src/main/java/hudson/util/AtomicFileWriter.java
  pom.xml
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5927 Clean up `ClassLoaderReflectionToolkit`
  core/src/main/java/jenkins/ClassLoaderReflectionToolkit.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5980 Remove `libpam4j`
  bom/pom.xml
  core/pom.xml
  core/src/main/java/hudson/util/jna/GNUCLibrary.java
Labels: ready-for-merge, removed

#5992 Migrate from Apache Commons `StringUtils#join` to Java Platform `String#join`
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/TcpSlaveAgentListener.java
  core/src/main/java/hudson/logging/LogRecorder.java
  core/src/main/java/hudson/model/ChoiceParameterDefinition.java
  core/src/main/java/hudson/model/Items.java
  core/src/main/java/hudson/model/View.java
  core/src/main/java/jenkins/model/queue/CompositeCauseOfBlockage.java
  core/src/main/java/jenkins/tasks/filters/impl/RetainVariablesLocalRule.java
  test/src/test/java/jenkins/AgentProtocolTest.java
Labels: ready-for-merge, skip-changelog

#5996 Prevent the expansion of Guava usages
  core/src/main/java/hudson/util/Iterators.java
  pom.xml
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6001 Extract `bridge-method-injector` version to a property
  core/pom.xml
  pom.xml
Labels: skip-changelog

#6003 Fix typo in default-whitelist.txt
  core/src/main/resources/jenkins/security/stapler/default-whitelist.txt
Labels: skip-changelog

#6005 Amend #6003
  core/src/main/resources/jenkins/security/stapler/default-whitelist.txt
Labels: skip-changelog

#5951 Fix `PublicConstructorForAbstractClass` Error Prone violations
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/Launcher.java
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/console/ConsoleAnnotationDescriptor.java
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/model/FullDuplexHttpChannel.java
  core/src/main/java/hudson/model/Label.java
  core/src/main/java/hudson/model/ParameterDefinition.java
  core/src/main/java/hudson/model/Project.java
  core/src/main/java/hudson/model/Slave.java
  core/src/main/java/hudson/model/labels/LabelExpression.java
  core/src/main/java/hudson/node_monitors/AbstractDiskSpaceMonitor.java
  core/src/main/java/hudson/slaves/AbstractCloudSlave.java
  core/src/main/java/hudson/slaves/ComputerLauncherFilter.java
  core/src/main/java/hudson/tasks/CommandInterpreter.java
  core/src/main/java/hudson/tools/AbstractCommandInstaller.java
  core/src/main/java/hudson/tools/DownloadFromUrlInstaller.java
  core/src/main/java/hudson/tools/ToolInstallation.java
  core/src/main/java/hudson/util/FormFieldValidator.java
  core/src/main/java/hudson/util/XStream2.java
  core/src/main/java/jenkins/security/RSAConfidentialKey.java
  core/src/main/java/jenkins/util/InterceptingExecutorService.java
  core/src/main/java/jenkins/util/MarkFindingOutputStream.java
  core/src/main/java/jenkins/util/groovy/AbstractGroovyViewModule.java
  core/src/main/java/org/acegisecurity/AcegiSecurityException.java
  core/src/main/java/org/acegisecurity/AuthenticationException.java
  core/src/main/java/org/acegisecurity/providers/AbstractAuthenticationToken.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5953 Fix `BadAnnotationImplementation` Error Prone violation
  core/src/main/java/hudson/cli/declarative/MethodBinder.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5962 Enable `CustomImportOrder` and `UnusedImports` Checkstyle checks
  core/src/main/java/hudson/logging/LogRecorder.java
  core/src/main/java/hudson/model/DirectoryBrowserSupport.java
  core/src/main/java/hudson/model/TimeZoneProperty.java
  core/src/main/java/hudson/util/XStream2.java
  core/src/main/java/jenkins/SoloFilePathFilter.java
  core/src/main/java/jenkins/model/Nodes.java
  core/src/main/java/jenkins/security/SuspiciousRequestFilter.java
  core/src/main/java/jenkins/security/s2m/RunningBuildFilePathFilter.java
  core/src/main/java/jenkins/views/Header.java
  core/src/main/java/jenkins/views/PartialHeader.java
  core/src/main/java/org/jenkins/ui/icon/IconSet.java
  pom.xml
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5968 Enable Javadoc-related Checkstyle checks
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/ProxyConfiguration.java
  core/src/main/java/hudson/WebAppMain.java
  core/src/main/java/hudson/XmlFile.java
  core/src/main/java/hudson/logging/LogRecorder.java
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/model/EnvironmentContributingAction.java
  core/src/main/java/hudson/model/ItemGroup.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/model/View.java
  core/src/main/java/hudson/model/queue/Latch.java
  core/src/main/java/hudson/security/SecurityRealm.java
  core/src/main/java/hudson/triggers/Trigger.java
  core/src/main/java/hudson/util/KeyedDataStorage.java
  core/src/main/java/hudson/util/jna/RegistryKey.java
  pom.xml
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5973 Minor POM cleanup
  core/pom.xml
  pom.xml
  test/pom.xml
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5990 Bump parent POM from 1.67 to 1.69
  pom.xml
  test/pom.xml
Labels: ready-for-merge, skip-changelog, squash-merge-me, dependencies, java

#6004 Don't enable form element path in unit tests by default
  core/src/main/java/jenkins/formelementpath/FormElementPathPageDecorator.java
Labels: ready-for-merge, bug

#6013 Break lines at 240 columns
  core/src/main/java/hudson/cli/DisablePluginCommand.java
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/model/Executor.java
  core/src/main/java/hudson/model/Fingerprint.java
  core/src/main/java/hudson/model/Item.java
  core/src/main/java/hudson/model/ItemGroup.java
  core/src/main/java/hudson/model/ItemGroupMixIn.java
  core/src/main/java/hudson/model/ManagementLink.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/scm/SCM.java
  core/src/main/java/hudson/slaves/DumbSlave.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/model/ParameterizedJobMixIn.java
  core/src/main/java/jenkins/model/lazy/LazyBuildMixIn.java
  core/src/main/java/jenkins/slaves/JnlpAgentReceiver.java
  core/src/main/java/jenkins/util/Timer.java
  core/src/main/java/jenkins/websocket/WebSockets.java
  core/src/main/java/org/acegisecurity/providers/dao/AbstractUserDetailsAuthenticationProvider.java
  core/src/test/java/hudson/slaves/ComputerLauncherTest.java
  core/src/test/java/hudson/util/XStream2Test.java
  pom.xml
  test/src/test/java/hudson/security/ExtendedReadPermissionTest.java
  test/src/test/java/hudson/tools/InstallerTranslatorTest.java
  test/src/test/java/lib/form/PasswordTest.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6010 Improving logging from `AbstractCloudSlave._terminate`
  core/src/main/java/hudson/slaves/AbstractCloudSlave.java
  core/src/main/java/hudson/slaves/SlaveComputer.java
Labels: ready-for-merge, rfe

#6000 [JENKINS-21224] Utility `Listeners.notify`
  core/src/main/java/hudson/model/AbstractCIBase.java
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/model/listeners/ItemListener.java
  core/src/main/java/hudson/slaves/SlaveComputer.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/util/Listeners.java
Labels: developer

#5952 Fix `ThrowsUncheckedException` Error Prone violations in tests
  core/src/test/java/hudson/PluginManagerTest.java
  test/src/test/java/hudson/model/ItemGroupMixInTest.java
  test/src/test/java/hudson/model/MyViewsPropertyTest.java
  test/src/test/java/jenkins/AgentProtocolTest.java
  test/src/test/java/jenkins/install/InstallStateTest.java
  test/src/test/java/jenkins/model/JenkinsTest.java
  test/src/test/java/jenkins/slaves/OldRemotingAgentTest.java
  test/src/test/java/jenkins/slaves/RemotingVersionInfoTest.java
  test/src/test/java/org/kohsuke/stapler/MockStaplerRequestBuilder.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5949 [JENKINS-67154] Fix appearance of table tooltips
  war/src/main/less/base/style.less
  war/src/main/less/modules/tooltips.less
Labels: ready-for-merge, bug

#6014 Align Guice and ASM dependencies
  bom/pom.xml
  core/pom.xml
Labels: ready-for-merge, developer

#6012 Enable `VariableDeclarationUsageDistance` Checkstyle check
  core/src/test/java/hudson/FilePathTest.java
  core/src/test/java/hudson/util/RobustReflectionConverterTest.java
  pom.xml
  test/src/test/java/hudson/model/AutoCompletionCandidatesTest.java
  test/src/test/java/hudson/model/ProjectTest.java
  test/src/test/java/hudson/tasks/BuildTriggerTest.java
  test/src/test/java/hudson/tools/InstallerTranslatorTest.java
  test/src/test/java/jenkins/security/BasicHeaderProcessorTest.java
  test/src/test/java/jenkins/security/RedactSecretJsonInErrorMessageSanitizerHtmlTest.java
  test/src/test/java/lib/form/PasswordTest.java
Labels: ready-for-merge, skip-changelog

#6016 Removed unused ByteBuffer (moved to stapler)
  core/src/main/java/hudson/util/ByteBuffer.java
Labels: ready-for-merge, skip-changelog

#6015 Prevent new SpotBugs violations from being introduced
  cli/src/main/java/hudson/cli/FullDuplexHttpStream.java
  core/pom.xml
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/Plugin.java
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/Proc.java
  core/src/main/java/hudson/WebAppMain.java
  core/src/main/java/hudson/console/ConsoleNote.java
  core/src/main/java/hudson/diagnosis/HudsonHomeDiskUsageChecker.java
  core/src/main/java/hudson/logging/LogRecorderManager.java
  core/src/main/java/hudson/model/AbstractCIBase.java
  core/src/main/java/hudson/model/AbstractItem.java
  core/src/main/java/hudson/model/Actionable.java
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/model/FileParameterValue.java
  core/src/main/java/hudson/model/Job.java
  core/src/main/java/hudson/model/LoadStatistics.java
  core/src/main/java/hudson/model/Node.java
  core/src/main/java/hudson/model/PermalinkProjectAction.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/model/UsageStatistics.java
  core/src/main/java/hudson/model/User.java
  core/src/main/java/hudson/model/queue/WorkUnitContext.java
  core/src/main/java/hudson/os/SU.java
  core/src/main/java/hudson/search/Search.java
  core/src/main/java/hudson/security/TokenBasedRememberMeServices2.java
  core/src/main/java/hudson/security/csrf/DefaultCrumbIssuer.java
  core/src/main/java/hudson/security/csrf/GlobalCrumbIssuerConfiguration.java
  core/src/main/java/hudson/slaves/CloudSlaveRetentionStrategy.java
  core/src/main/java/hudson/slaves/NodeProvisioner.java
  core/src/main/java/hudson/tasks/BuildTrigger.java
  core/src/main/java/hudson/triggers/SCMTrigger.java
  core/src/main/java/hudson/triggers/SlowTriggerAdminMonitor.java
  core/src/main/java/hudson/triggers/Trigger.java
  core/src/main/java/hudson/util/CompressedFile.java
  core/src/main/java/hudson/util/ProcessTree.java
  core/src/main/java/hudson/util/Secret.java
  core/src/main/java/hudson/util/XStream2.java
  core/src/main/java/jenkins/SoloFilePathFilter.java
  core/src/main/java/jenkins/formelementpath/FormElementPathPageDecorator.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/model/StandardArtifactManager.java
  core/src/main/java/jenkins/model/item_category/ItemCategory.java
  core/src/main/java/jenkins/scm/RunWithSCM.java
  core/src/main/java/jenkins/security/BasicHeaderRealPasswordAuthenticator.java
  core/src/main/java/jenkins/security/ResourceDomainRootAction.java
  core/src/main/java/jenkins/security/apitoken/ApiTokenStore.java
  core/src/main/java/jenkins/security/s2m/CallableDirectionChecker.java
  core/src/main/java/jenkins/security/s2m/DefaultFilePathFilter.java
  core/src/main/java/jenkins/security/seed/UserSeedProperty.java
  core/src/main/java/jenkins/security/stapler/StaplerDispatchValidator.java
  core/src/main/java/jenkins/security/stapler/StaticRoutingDecisionProvider.java
  core/src/main/java/jenkins/security/stapler/TypedFilter.java
  core/src/main/java/jenkins/slaves/EncryptedSlaveAgentJnlpFile.java
  core/src/main/java/jenkins/util/FullDuplexHttpService.java
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, skip-changelog

#6017 Bump MINA SSHD from 2.7.0 to 2.8.0
  cli/pom.xml
  cli/src/main/java/hudson/cli/SSHCLI.java
Labels: ready-for-merge, skip-changelog, dependencies, java

#6018 `RingBufferLogHandler.records` could leak records
  core/src/main/java/hudson/util/RingBufferLogHandler.java
  core/src/test/java/hudson/logging/LogRecorderTest.java
Labels: ready-for-merge, bug

#6019 Use `Listeners.notify` in more places
  core/src/main/java/hudson/model/Queue.java
  core/src/main/java/hudson/model/listeners/RunListener.java
  core/src/main/java/hudson/model/listeners/SCMPollListener.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/model/NodeListener.java
  core/src/main/java/jenkins/security/seed/UserSeedChangeListener.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6021 Fix some SpotBugs violations
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/TcpSlaveAgentListener.java
  core/src/main/java/hudson/diagnosis/MemoryUsageMonitor.java
  core/src/main/java/hudson/model/Queue.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/model/queue/CauseOfBlockage.java
  core/src/main/java/hudson/security/AuthenticationProcessingFilter2.java
  core/src/main/java/hudson/tasks/LogRotator.java
  core/src/main/java/hudson/triggers/SlowTriggerAdminMonitor.java
  core/src/main/java/hudson/util/RemotingDiagnostics.java
  core/src/main/java/jenkins/FilePathFilterAggregator.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/model/lazy/LazyBuildMixIn.java
  core/src/main/java/jenkins/security/NonSerializableSecurityContext.java
  core/src/main/java/jenkins/security/s2m/AdminWhitelistRule.java
  core/src/main/java/jenkins/slaves/StandardOutputSwapper.java
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, skip-changelog

#6022 Fix `IC_INIT_CIRCULARITY` SpotBugs violation
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/model/View.java
  core/src/main/java/hudson/slaves/Cloud.java
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, skip-changelog

#6026 Skip symlink tests on Windows
  core/src/test/java/hudson/FilePathTest.java
  core/src/test/java/hudson/LauncherTest.java
  core/src/test/java/hudson/UtilTest.java
  core/src/test/java/hudson/util/AtomicFileWriterTest.java
  core/src/test/java/hudson/util/io/TarArchiverTest.java
  core/src/test/java/jenkins/util/VirtualFileTest.java
  core/src/test/java/jenkins/util/io/PathRemoverTest.java
Labels: ready-for-merge, skip-changelog

#6031 [JENKINS-67332] Pull up `Telemetry.buildComponentInformation` for use in `SlaveToMasterFileCallableUsage`
  core/src/main/java/jenkins/telemetry/Telemetry.java
  core/src/main/java/jenkins/telemetry/impl/SlaveToMasterFileCallableUsage.java
  core/src/main/java/jenkins/telemetry/impl/StaplerDispatches.java
Labels: ready-for-merge, skip-changelog

#5888 `CallableRejectionConfig` just threw an error rather than persisting anything
  core/src/main/java/jenkins/security/s2m/ConfigFile.java
Labels: ready-for-merge, bug

#5794 [JENKINS-65084] fix filter for unavailable updates #Hacktoberfest
  core/src/main/resources/hudson/PluginManager/_table.js
Labels: ready-for-merge, web-ui, bug

#5950 Fix `CatchingUnchecked` Error Prone violations
  core/src/main/java/hudson/ExtensionFinder.java
  core/src/main/java/hudson/ExtensionList.java
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/Util.java
  core/src/main/java/hudson/WebAppMain.java
  core/src/main/java/hudson/lifecycle/ExitLifecycle.java
  core/src/main/java/hudson/lifecycle/SolarisSMFLifecycle.java
  core/src/main/java/hudson/lifecycle/UnixLifecycle.java
  core/src/main/java/hudson/lifecycle/WindowsServiceLifecycle.java
  core/src/main/java/hudson/model/AbstractProject.java
  core/src/main/java/hudson/model/Actionable.java
  core/src/main/java/hudson/model/Executor.java
  core/src/main/java/hudson/model/Project.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/java/hudson/scm/ChangeLogSet.java
  core/src/main/java/hudson/slaves/SlaveComputer.java
  core/src/main/java/hudson/util/FormValidation.java
  core/src/main/java/jenkins/I18n.java
  core/src/main/java/jenkins/JenkinsHttpSessionListener.java
  core/src/main/java/jenkins/MetaLocaleDrivenResourceProvider.java
  core/src/main/java/jenkins/cli/StopBuildsCommand.java
  core/src/main/java/jenkins/install/InstallUtil.java
  core/src/main/java/jenkins/install/SetupWizard.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/model/RunIdMigrator.java
  core/src/main/java/jenkins/security/ResourceDomainRootAction.java
  core/src/main/java/jenkins/security/s2m/FilePathRuleConfig.java
  core/src/main/java/jenkins/telemetry/Telemetry.java
  core/src/test/java/jenkins/util/TimerTest.java
  test/src/test/java/lib/form/ValidateButtonTest.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5970 `URLClassLoader` support for `PluginFirstClassLoader`
  core/src/main/java/hudson/ClassicPluginStrategy.java
  core/src/main/java/hudson/PluginFirstClassLoader2.java
  core/src/main/java/hudson/util/CompoundEnumeration.java
  core/src/test/java/hudson/util/CompoundEnumerationTest.java
Labels: ready-for-merge, squash-merge-me, developer

#6023 Fix some equals-related SpotBugs violations
  core/src/main/java/hudson/Launcher.java
  core/src/main/java/hudson/Main.java
  core/src/main/java/hudson/cli/BuildCommand.java
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/java/hudson/model/ViewJob.java
  core/src/main/java/hudson/triggers/Trigger.java
  core/src/main/java/hudson/util/ProcessTree.java
  core/src/main/java/hudson/util/StreamResource.java
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, skip-changelog

#6035 Ignore some tests on Windows
  core/src/test/java/hudson/model/LoadStatisticsTest.java
  test/src/test/java/hudson/PluginManagerTest.java
  test/src/test/java/jenkins/security/ResourceDomainTest.java
  test/src/test/java/jenkins/security/stapler/JenkinsSupportAnnotationsTest.java
Labels: ready-for-merge, skip-changelog

#6037 Fix `IS_FIELD_NOT_GUARDED` SpotBugs violation
  core/src/main/java/hudson/model/ListView.java
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, skip-changelog

#6039 Clarify how the config.xml API works
  core/src/main/resources/hudson/model/AbstractItem/_api.jelly
Labels: ready-for-merge, skip-changelog

#6044 `RingBufferLogHandler.getView` needs to be a live `List` for use from `Jenkins.logRecords`
  core/src/main/java/hudson/util/RingBufferLogHandler.java
  test/src/test/java/jenkins/model/JenkinsLogRecordsTest.java
Labels: ready-for-merge, skip-changelog

#6040 [JENKINS-21224] Cannot use `Listeners.notify` in `ItemListener.fireOnCreated` due to `matrix-auth` tricks
  core/src/main/java/hudson/model/AbstractCIBase.java
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/model/Queue.java
  core/src/main/java/hudson/model/listeners/ItemListener.java
  core/src/main/java/hudson/model/listeners/RunListener.java
  core/src/main/java/hudson/model/listeners/SCMPollListener.java
  core/src/main/java/hudson/slaves/SlaveComputer.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/model/NodeListener.java
  core/src/main/java/jenkins/security/seed/UserSeedChangeListener.java
  core/src/main/java/jenkins/util/Listeners.java
Labels: regression-fix, ready-for-merge, squash-merge-me

#6041 Reduce usages of Ant
  core/src/main/java/hudson/Util.java
  core/src/main/java/hudson/model/AbstractItem.java
  core/src/main/java/hudson/model/View.java
  core/src/main/java/hudson/slaves/ComputerLauncher.java
  core/src/main/java/jenkins/security/seed/UserSeedChangeListener.java
  core/src/test/java/hudson/PluginManagerTest.java
  test/src/test/java/hudson/PluginManagerTest.java
  test/src/test/java/hudson/cli/GroovyshCommandTest.java
  test/src/test/java/hudson/tasks/EnvVarsInConfigTasksTest.java
  test/src/test/java/jenkins/install/SetupWizardTest.java
  test/src/test/java/jenkins/model/NodeListenerTest.java
Labels: ready-for-merge, skip-changelog

#6033 Improve FilePath API and Javadoc around validation
  core/src/main/java/hudson/FilePath.java
Labels: ready-for-merge, developer

#6025 Fix `RV_RETURN_VALUE_IGNORED_BAD_PRACTICE` SpotBugs violations
  core/src/main/java/hudson/ClassicPluginStrategy.java
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/Main.java
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/PluginWrapper.java
  core/src/main/java/hudson/WebAppMain.java
  core/src/main/java/hudson/XmlFile.java
  core/src/main/java/hudson/init/impl/InitialUserContent.java
  core/src/main/java/hudson/lifecycle/Lifecycle.java
  core/src/main/java/hudson/lifecycle/WindowsInstallerLink.java
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/model/DownloadService.java
  core/src/main/java/hudson/model/FileParameterValue.java
  core/src/main/java/hudson/model/ItemGroupMixIn.java
  core/src/main/java/hudson/model/Job.java
  core/src/main/java/hudson/model/Queue.java
  core/src/main/java/hudson/model/RunMap.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/java/hudson/util/CompressedFile.java
  core/src/main/java/hudson/util/RemotingDiagnostics.java
  core/src/main/java/hudson/util/TextFile.java
  core/src/main/java/hudson/util/io/ReopenableRotatingFileOutputStream.java
  core/src/main/java/hudson/util/io/RewindableRotatingFileOutputStream.java
  core/src/main/java/jenkins/diagnosis/HsErrPidFile.java
  core/src/main/java/jenkins/fingerprints/FileFingerprintStorage.java
  core/src/main/java/jenkins/install/InstallUtil.java
  core/src/main/java/jenkins/management/AsynchronousAdministrativeMonitor.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/util/io/FileBoolean.java
  core/src/test/java/hudson/PluginManagerTest.java
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5916 Modernise the appearance of the plugin manager
  .editorconfig
  core/src/main/resources/hudson/PluginManager/_table.css
  core/src/main/resources/hudson/PluginManager/_table.js
  core/src/main/resources/hudson/PluginManager/advanced.jelly
  core/src/main/resources/hudson/PluginManager/available.jelly
  core/src/main/resources/hudson/PluginManager/installed.jelly
  core/src/main/resources/hudson/PluginManager/search.gif
  core/src/main/resources/hudson/PluginManager/table.jelly
  core/src/main/resources/hudson/widgets/HistoryWidget/index.jelly
  core/src/main/resources/jenkins/views/JenkinsHeader/headerContent.jelly
  core/src/main/resources/lib/hudson/newFromList/form.jelly
  core/src/main/resources/lib/layout/app-bar.jelly
  core/src/main/resources/lib/layout/layout.jelly
  test/src/test/java/hudson/PluginManagerInstalledGUITest.java
  war/src/main/js/plugin-manager-ui.js
  war/src/main/js/templates/plugin-manager/available.hbs
  war/src/main/less/abstracts/theme.less
  war/src/main/less/base-styles-v2.less
  war/src/main/less/base/spacing.less
  war/src/main/less/base/style.less
  war/src/main/less/base/typography.less
  war/src/main/less/base/visibility-utils.less
  war/src/main/less/modules/app-bar.less
  war/src/main/less/modules/buttons.less
  war/src/main/less/modules/form.less
  war/src/main/less/modules/page-header.less
  war/src/main/less/modules/table.less
  war/src/main/less/pages/plugin-manager.less
  war/src/main/less/plugin-manager-ui.less
  war/src/main/resources/images/ionicons/close-circle-outline.svg
  war/src/main/resources/images/ionicons/downgrade-circle-outline.svg
  war/src/main/resources/images/ionicons/help-circle-outline.svg
  war/src/main/resources/images/ionicons/search-outline.svg
  war/webpack.config.js
Labels: ready-for-merge, web-ui, rfe

#6030 Release class loader when a plugin fails to load
  core/src/main/java/hudson/PluginManager.java
Labels: ready-for-merge, bug

#6034 Release detached plugin class loaders on shutdown
  core/src/main/java/hudson/PluginManager.java
Labels: ready-for-merge, bug, squash-merge-me

#6038 Use update site provided file size for better guessing
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/model/UpdateSite.java
Labels: ready-for-merge, rfe

#6053 Bump ATH
  essentials.yml
Labels: skip-changelog

#6052 Fix `XXE_SAXPARSER` SpotBugs violations
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/XmlFile.java
  core/src/test/java/hudson/PluginManagerTest.java
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, skip-changelog

#6054 Bump `jenkins-test-harness` from 1666.vd1360abbfe9e to 1670.v5a5dbf551c41
  test/pom.xml
Labels: skip-changelog

#5945 Add nullability annotations to parameter definitions
  core/src/main/java/hudson/model/BooleanParameterDefinition.java
  core/src/main/java/hudson/model/ChoiceParameterDefinition.java
  core/src/main/java/hudson/model/FileParameterDefinition.java
  core/src/main/java/hudson/model/PasswordParameterDefinition.java
  core/src/main/java/hudson/model/RunParameterDefinition.java
  core/src/main/java/hudson/model/SimpleParameterDefinition.java
  core/src/main/java/hudson/model/StringParameterDefinition.java
  core/src/main/java/hudson/model/TextParameterDefinition.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5997 translate "NewView" to ru
  core/src/main/resources/jenkins/model/Messages_ru.properties
Labels: ready-for-merge, localization

#5939 [JENKINS-65237] Bump Groovy from 2.4.12 to 2.4.21
  .github/dependabot.yml
  bom/pom.xml
Labels: ready-for-merge, rfe, squash-merge-me, dependencies, java

#6029 Fix various test bugs seen when running on Windows
  test/src/test/java/hudson/PluginManagerTest.java
  test/src/test/java/hudson/cli/BuildCommandTest.java
  test/src/test/java/hudson/cli/DisablePluginCommandTest.java
  test/src/test/java/hudson/cli/RunRangeCommand2Test.java
  test/src/test/java/hudson/model/AbstractItemTest.java
  test/src/test/java/hudson/model/JobQueueTest.java
  test/src/test/java/hudson/model/JobTest.java
  test/src/test/java/hudson/model/ProjectTest.java
  test/src/test/java/hudson/model/RunMapTest.java
  test/src/test/java/hudson/tasks/BuildTriggerTest.java
  test/src/test/java/hudson/util/ProcessTreeTest.java
  test/src/test/java/jenkins/cli/StopBuildsCommandTest.java
  test/src/test/java/jenkins/security/Security2455Test.java
  test/src/test/java/jenkins/security/stapler/Security914Test.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6047 Fix `IS2_INCONSISTENT_SYNC` SpotBugs violations
  core/src/main/java/hudson/model/Fingerprint.java
  core/src/main/java/hudson/model/View.java
  core/src/main/java/hudson/security/csrf/DefaultCrumbIssuer.java
  core/src/main/java/hudson/slaves/SimpleScheduledRetentionStrategy.java
  core/src/main/java/hudson/tasks/Fingerprinter.java
  core/src/main/java/hudson/tools/ToolInstallation.java
  core/src/main/java/hudson/util/ProcessTree.java
  core/src/main/java/hudson/util/SequentialExecutionQueue.java
  core/src/main/java/jenkins/model/RunIdMigrator.java
  core/src/main/java/jenkins/security/apitoken/ApiTokenStats.java
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6048 Bump Apache Commons Validator from 1.6 to 1.7
  core/src/main/java/jenkins/org/apache/commons/validator/routines/DomainValidator.java
  core/src/main/java/jenkins/org/apache/commons/validator/routines/InetAddressValidator.java
  core/src/main/java/jenkins/org/apache/commons/validator/routines/RegexValidator.java
  core/src/main/java/jenkins/org/apache/commons/validator/routines/UrlValidator.java
  core/src/test/java/jenkins/org/apache/commons/validator/ResultPair.java
  core/src/test/java/jenkins/org/apache/commons/validator/routines/DomainValidatorTest.java
  core/src/test/java/jenkins/org/apache/commons/validator/routines/InetAddressValidatorTest.java
  core/src/test/java/jenkins/org/apache/commons/validator/routines/RegexValidatorTest.java
  core/src/test/java/jenkins/org/apache/commons/validator/routines/UrlValidatorTest.java
Labels: ready-for-merge, squash-merge-me, dependencies, java

#5358 [JENKINS-65113] Add issue tracker metadata support
  core/src/main/java/hudson/PluginWrapper.java
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/resources/hudson/PluginManager/installed.jelly
  core/src/main/resources/hudson/PluginManager/installed.properties
Labels: ready-for-merge, web-ui, rfe, squash-merge-me

#6051 Only require one approval for minor changes
  docs/MAINTAINERS.adoc
Labels: ready-for-merge, skip-changelog

#6061 Clarify that FilePath telemetry collects component versions now
  core/src/main/resources/jenkins/telemetry/impl/SlaveToMasterFileCallableUsage/description.jelly
Labels: ready-for-merge, skip-changelog

#6011 Translate some parameters to ru
  core/src/main/resources/hudson/model/BooleanParameterDefinition/help-boolean-default_ru.html
  core/src/main/resources/hudson/model/RunParameterDefinition/config_ru.properties
  war/src/main/webapp/help/parameter/boolean_ru.html
  war/src/main/webapp/help/parameter/choice-choices_ru.html
  war/src/main/webapp/help/parameter/description_ru.html
  war/src/main/webapp/help/parameter/name_ru.html
  war/src/main/webapp/help/parameter/run-filter_ru.html
  war/src/main/webapp/help/parameter/run-project_ru.html
Labels: ready-for-merge, localization

#6060 Simplify JTH assertions
  test/src/test/java/hudson/LauncherTest.java
  test/src/test/java/hudson/ProcStarterTest.java
  test/src/test/java/hudson/cli/ConsoleCommandTest.java
  test/src/test/java/hudson/cli/DeleteBuildsCommandTest.java
  test/src/test/java/hudson/cli/RunRangeCommand2Test.java
  test/src/test/java/hudson/cli/RunRangeCommandTest.java
  test/src/test/java/hudson/cli/SetBuildDescriptionCommandTest.java
  test/src/test/java/hudson/cli/SetBuildDisplayNameCommandTest.java
  test/src/test/java/hudson/diagnosis/OldDataMonitorTest.java
  test/src/test/java/hudson/model/AbortedFreeStyleBuildTest.java
  test/src/test/java/hudson/model/AbstractBuildTest.java
  test/src/test/java/hudson/model/AbstractItemTest.java
  test/src/test/java/hudson/model/AbstractProjectTest.java
  test/src/test/java/hudson/model/BuildExecutionTest.java
  test/src/test/java/hudson/model/DirectoryBrowserSupportTest.java
  test/src/test/java/hudson/model/EnvironmentContributorTest.java
  test/src/test/java/hudson/model/FreeStyleProjectTest.java
  test/src/test/java/hudson/model/FreestyleJobPublisherTest.java
  test/src/test/java/hudson/model/ItemsTest.java
  test/src/test/java/hudson/model/JobTest.java
  test/src/test/java/hudson/model/ParametersTest.java
  test/src/test/java/hudson/model/QueueTest.java
  test/src/test/java/hudson/model/RSSTest.java
  test/src/test/java/hudson/model/RunMapTest.java
  test/src/test/java/hudson/model/RunParameterDefinitionTest.java
  test/src/test/java/hudson/model/RunTest.java
  test/src/test/java/hudson/model/WorkspaceCleanupThreadTest.java
  test/src/test/java/hudson/model/labels/LabelExpressionTest.java
  test/src/test/java/hudson/model/queue/WideExecutionTest.java
  test/src/test/java/hudson/scm/AbstractScmTagActionTest.java
  test/src/test/java/hudson/scm/ScmTest.java
  test/src/test/java/hudson/slaves/EnvironmentVariableNodePropertyTest.java
  test/src/test/java/hudson/tasks/ArtifactArchiverTest.java
  test/src/test/java/hudson/tasks/BatchFileTest.java
  test/src/test/java/hudson/tasks/BuildTriggerTest.java
  test/src/test/java/hudson/tasks/EnvVarsInConfigTasksTest.java
  test/src/test/java/hudson/tasks/FingerprinterTest.java
  test/src/test/java/hudson/tasks/MavenTest.java
  test/src/test/java/hudson/tasks/ShellTest.java
  test/src/test/java/hudson/util/ProcessTreeTest.java
  test/src/test/java/hudson/widgets/HistoryWidgetTest.java
  test/src/test/java/jenkins/model/PeepholePermalinkTest.java
  test/src/test/java/jenkins/security/ClassFilterImplTest.java
  test/src/test/java/jenkins/tasks/SimpleBuildWrapperTest.java
  test/src/test/java/jenkins/tasks/filters/impl/RetainVariablesLocalRuleTest.java
  test/src/test/java/jenkins/triggers/ReverseBuildTriggerTest.java
  test/src/test/java/jenkins/widgets/BuildTimeTrendTest.java
  test/src/test/java/lib/form/ApplyButtonTest.java
Labels: ready-for-merge, skip-changelog

#6066 Bump Stapler from 1593.v0e838714faae to 1612.v2a13b906bf3a
  bom/pom.xml
  cli/pom.xml
  core/pom.xml
Labels: ready-for-merge, bug

#6067 Ship JCIP annotations in WAR
  core/pom.xml
Labels: ready-for-merge, skip-changelog

#6069 Skip resource-intensive tests on Windows CI builds
  test/src/test/java/hudson/model/FreeStyleProjectTest.java
  test/src/test/java/hudson/model/JobTest.java
  test/src/test/java/hudson/slaves/NodeProvisionerTest.java
  test/src/test/java/hudson/slaves/SlaveComputerTest.java
  test/src/test/java/jenkins/widgets/BuildTimeTrendTest.java
Labels: ready-for-merge, skip-changelog

#6059 [JENKINS-67372] Restore support for symbolic links in the Jenkins home directory
  core/src/main/java/hudson/ClassicPluginStrategy.java
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/Util.java
  core/src/main/java/hudson/WebAppMain.java
  core/src/main/java/hudson/XmlFile.java
  core/src/main/java/hudson/init/impl/InitialUserContent.java
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/model/ItemGroupMixIn.java
  core/src/main/java/hudson/model/Job.java
  core/src/main/java/hudson/model/RunMap.java
  core/src/main/java/hudson/util/TextFile.java
  core/src/main/java/jenkins/fingerprints/FileFingerprintStorage.java
  core/src/main/java/jenkins/management/AsynchronousAdministrativeMonitor.java
  core/src/main/java/jenkins/util/io/FileBoolean.java
  core/src/test/java/hudson/UtilTest.java
Labels: regression-fix, ready-for-merge, major-bug, squash-merge-me

#6078 [JENKINS-67401] Update contributing guide
  CONTRIBUTING.md
Labels: ready-for-merge, skip-changelog

#6076 Bump `jenkins-test-harness` from 1670.v5a5dbf551c41 to 1674.v3b8b1441e939
  test/pom.xml
  test/src/test/java/hudson/cli/ComputerStateTest.java
  test/src/test/java/hudson/cli/HelpCommandTest.java
  test/src/test/java/hudson/console/ConsoleAnnotatorTest.java
  test/src/test/java/hudson/console/HyperlinkNoteTest.java
  test/src/test/java/hudson/logging/LogRecorderManagerTest.java
  test/src/test/java/hudson/model/DirectoryBrowserSupportTest.java
  test/src/test/java/hudson/model/ParametersTest.java
  test/src/test/java/hudson/model/ProjectTest.java
  test/src/test/java/hudson/model/QueueTest.java
  test/src/test/java/hudson/model/ViewDescriptorTest.java
  test/src/test/java/hudson/security/LoginTest.java
  test/src/test/java/hudson/util/AlternativeUiTextProviderTest.java
  test/src/test/java/jenkins/model/JenkinsManagePermissionTest.java
  test/src/test/java/jenkins/model/JenkinsTest.java
  test/src/test/java/jenkins/security/ApiTokenPropertyTest.java
  test/src/test/java/jenkins/security/stapler/StaplerDispatchValidatorTest.java
Labels: ready-for-merge, skip-changelog

#5905 Add missing SVG for parameterized jobs
  core/src/main/java/org/jenkins/ui/icon/IconSet.java
  war/src/main/webapp/images/24x24/document-properties.gif
  war/src/main/webapp/images/24x24/document-properties.png
  war/src/main/webapp/images/svgs/document-properties.svg
Labels: ready-for-merge, web-ui, rfe

#5884 [JENKINS-67173] Deprecate `SlaveToMasterFileCallable`, log warning
  core/src/main/java/jenkins/SlaveToMasterFileCallable.java
Labels: ready-for-merge, developer

#6086 Switch ATH from Java 8 to Java 11
  Jenkinsfile
  essentials.yml
Labels: ready-for-merge, skip-changelog

#6063 Miscellaneous test cleanup
  core/src/test/java/hudson/UtilTest.java
  test/src/test/java/hudson/cli/CLITest.java
  test/src/test/java/hudson/cli/ConsoleCommandTest.java
  test/src/test/java/hudson/model/JobTest.java
  test/src/test/java/hudson/model/QueueTest.java
  test/src/test/java/hudson/model/RunMapTest.java
  test/src/test/java/hudson/slaves/NodeCanTakeTaskTest.java
  test/src/test/java/hudson/tasks/ArtifactArchiverTest.java
  test/src/test/java/jenkins/cli/StopBuildsCommandTest.java
Labels: ready-for-merge, skip-changelog

#6070 Backporting for 2.319.2
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/model/Nodes.java
  core/src/main/java/jenkins/telemetry/Telemetry.java
  core/src/main/java/jenkins/telemetry/impl/SlaveToMasterFileCallableUsage.java
  core/src/main/java/jenkins/telemetry/impl/StaplerDispatches.java
  core/src/main/resources/jenkins/telemetry/impl/SlaveToMasterFileCallableUsage/description.jelly
  core/src/test/java/jenkins/telemetry/impl/SlaveToMasterFileCallableUsageTest.java
Labels: into-lts

#6024 Restore Windows CI runs
  Jenkinsfile
Labels: ready-for-merge, skip-changelog

#6088 More miscellaneous test cleanup
  test/src/test/java/hudson/cli/ConsoleCommandTest.java
  test/src/test/java/hudson/cli/ReloadJobCommandTest.java
  test/src/test/java/hudson/cli/SetBuildDescriptionCommandTest.java
  test/src/test/java/hudson/model/RunParameterDefinitionTest.java
  test/src/test/java/hudson/tasks/ArtifactArchiverTest.java
  test/src/test/java/hudson/tasks/LogRotatorTest.java
Labels: ready-for-merge, skip-changelog

#6077 Include `shortName` in relevant `PluginWrapper.dependencyErrors`
  core/src/main/java/hudson/PluginWrapper.java
  core/src/main/resources/hudson/Messages.properties
  core/src/test/java/hudson/PluginWrapperTest.java
Labels: ready-for-merge, rfe, squash-merge-me

#6049 Triage some SpotBugs violations
  core/src/main/java/hudson/ExtensionList.java
  core/src/main/java/hudson/WebAppMain.java
  core/src/main/java/hudson/console/ConsoleNote.java
  core/src/main/java/hudson/model/AbstractItem.java
  core/src/main/java/hudson/model/AutoCompletionCandidates.java
  core/src/main/java/hudson/model/Cause.java
  core/src/main/java/hudson/model/DirectoryBrowserSupport.java
  core/src/main/java/hudson/model/FreeStyleProject.java
  core/src/main/java/hudson/model/Queue.java
  core/src/main/java/hudson/model/ResourceController.java
  core/src/main/java/hudson/model/StringParameterDefinition.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/node_monitors/ClockMonitor.java
  core/src/main/java/hudson/node_monitors/SwapSpaceMonitor.java
  core/src/main/java/hudson/node_monitors/TemporarySpaceMonitor.java
  core/src/main/java/hudson/security/ACL.java
  core/src/main/java/hudson/security/FullControlOnceLoggedInAuthorizationStrategy.java
  core/src/main/java/hudson/security/LegacySecurityRealm.java
  core/src/main/java/hudson/slaves/JNLPLauncher.java
  core/src/main/java/hudson/tasks/Maven.java
  core/src/main/java/hudson/triggers/SCMTrigger.java
  core/src/main/java/hudson/util/ProcessTree.java
  core/src/main/java/hudson/util/RemotingDiagnostics.java
  core/src/main/java/hudson/util/jna/Advapi32.java
  core/src/main/java/hudson/util/jna/Options.java
  core/src/main/java/jenkins/fingerprints/FileFingerprintStorage.java
  core/src/main/java/jenkins/install/SetupWizard.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/model/PeepholePermalink.java
  core/src/main/java/jenkins/slaves/NioChannelSelector.java
  core/src/main/java/jenkins/util/DirectedGraph.java
  core/src/main/java/jenkins/util/JSONSignatureValidator.java
  core/src/main/java/jenkins/util/groovy/GroovyHookScript.java
  core/src/main/java/jenkins/util/io/PathRemover.java
  core/src/main/java/jenkins/util/xml/XMLUtils.java
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6050 Fix `DM_DEFAULT_ENCODING` SpotBugs violations
  cli/src/main/java/hudson/cli/CLIConnectionFactory.java
  cli/src/main/java/hudson/cli/PrivateKeyProvider.java
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/Proc.java
  core/src/main/java/hudson/WebAppMain.java
  core/src/main/java/hudson/cli/CLICommand.java
  core/src/main/java/hudson/console/AnnotatedLargeText.java
  core/src/main/java/hudson/console/ConsoleAnnotationOutputStream.java
  core/src/main/java/hudson/console/ConsoleNote.java
  core/src/main/java/hudson/model/AbstractBuild.java
  core/src/main/java/hudson/model/FileParameterValue.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/model/UsageStatistics.java
  core/src/main/java/hudson/scm/SCM.java
  core/src/main/java/hudson/security/HudsonAuthenticationEntryPoint.java
  core/src/main/java/hudson/security/csrf/DefaultCrumbIssuer.java
  core/src/main/java/hudson/util/BootFailure.java
  core/src/main/java/hudson/util/CompressedFile.java
  core/src/main/java/hudson/util/ConsistentHash.java
  core/src/main/java/hudson/util/IOUtils.java
  core/src/main/java/hudson/util/LogTaskListener.java
  core/src/main/java/hudson/util/ProcessTree.java
  core/src/main/java/hudson/util/Scrambler.java
  core/src/main/java/hudson/util/Secret.java
  core/src/main/java/jenkins/security/DefaultConfidentialStore.java
  core/src/main/java/jenkins/slaves/restarter/UnixSlaveRestarter.java
  core/src/main/java/jenkins/util/JSONSignatureValidator.java
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6097 Miscellaneous test cleanup
  test/src/test/java/hudson/cli/ConsoleCommandTest.java
  test/src/test/java/hudson/cli/DeleteBuildsCommandTest.java
  test/src/test/java/hudson/cli/RunRangeCommand2Test.java
  test/src/test/java/hudson/model/ExecutorTest.java
  test/src/test/java/hudson/model/LabelLoadStatisticsQueueLengthTest.java
  test/src/test/java/hudson/model/QueueTest.java
  test/src/test/java/hudson/tasks/MavenTest.java
  test/src/test/java/hudson/triggers/SCMTriggerTest.java
Labels: ready-for-merge, skip-changelog

#6102 Bump ATH
  essentials.yml
Labels: skip-changelog

#6091 Display JUnit test results as they appear
  Jenkinsfile
Labels: skip-changelog

#6062 Clean-up / improvements
  core/src/main/java/hudson/model/AbstractBuild.java
  core/src/main/java/hudson/model/ManagementLink.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/util/NoClientBindProtocolSocketFactory.java
  core/src/main/java/hudson/util/NoClientBindSSLProtocolSocketFactory.java
  core/src/main/java/org/jenkins/ui/icon/WeatherIcon.java
Labels: ready-for-merge, skip-changelog

#6095 Ensure links in help files open in new windows
  core/src/main/resources/hudson/slaves/JNLPLauncher/help-vmargs.html
  core/src/main/resources/hudson/slaves/JNLPLauncher/help-vmargs_bg.html
  core/src/main/resources/hudson/slaves/JNLPLauncher/help-vmargs_fr.html
  core/src/main/resources/hudson/slaves/JNLPLauncher/help-vmargs_it.html
  core/src/main/resources/hudson/slaves/JNLPLauncher/help-vmargs_ja.html
  core/src/main/resources/hudson/tasks/BatchFile/config.properties
  core/src/main/resources/hudson/tasks/BatchFile/config_bg.properties
  core/src/main/resources/hudson/tasks/BatchFile/config_da.properties
  core/src/main/resources/hudson/tasks/BatchFile/config_de.properties
  core/src/main/resources/hudson/tasks/BatchFile/config_es.properties
  core/src/main/resources/hudson/tasks/BatchFile/config_fr.properties
  core/src/main/resources/hudson/tasks/BatchFile/config_it.properties
  core/src/main/resources/hudson/tasks/BatchFile/config_ja.properties
  core/src/main/resources/hudson/tasks/BatchFile/config_pt_BR.properties
  core/src/main/resources/hudson/tasks/BatchFile/config_sr.properties
  core/src/main/resources/hudson/tasks/BatchFile/config_zh_TW.properties
  core/src/main/resources/hudson/tasks/Maven/help.properties
  core/src/main/resources/hudson/tasks/Maven/help_bg.properties
  core/src/main/resources/hudson/tasks/Maven/help_de.properties
  core/src/main/resources/hudson/tasks/Maven/help_fr.properties
  core/src/main/resources/hudson/tasks/Maven/help_it.properties
  core/src/main/resources/hudson/tasks/Maven/help_ja.properties
  core/src/main/resources/hudson/tasks/Maven/help_pt_BR.properties
  core/src/main/resources/hudson/tasks/Maven/help_ru.properties
  core/src/main/resources/hudson/tasks/Maven/help_sr.properties
  core/src/main/resources/hudson/tasks/Maven/help_tr.properties
  core/src/main/resources/hudson/tasks/Maven/help_zh_TW.properties
  core/src/main/resources/hudson/tasks/Shell/config.properties
  core/src/main/resources/hudson/tasks/Shell/config_da.properties
  core/src/main/resources/hudson/tasks/Shell/config_de.properties
  core/src/main/resources/hudson/tasks/Shell/config_es.properties
  core/src/main/resources/hudson/tasks/Shell/config_fr.properties
  core/src/main/resources/hudson/tasks/Shell/config_it.properties
  core/src/main/resources/hudson/tasks/Shell/config_ja.properties
  core/src/main/resources/hudson/tasks/Shell/config_nl.properties
  core/src/main/resources/hudson/tasks/Shell/config_pt_BR.properties
  core/src/main/resources/hudson/tasks/Shell/config_ru.properties
  core/src/main/resources/hudson/tasks/Shell/config_sr.properties
  core/src/main/resources/hudson/tasks/Shell/config_tr.properties
  core/src/main/resources/hudson/tasks/Shell/config_zh_TW.properties
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, rfe

#6096 Make env-vars.html nicer and actually localizable
  core/src/main/resources/hudson/model/EnvironmentContributor/EnvVarsHtml/index.groovy
  core/src/main/resources/hudson/model/EnvironmentContributor/EnvVarsHtml/index.properties
  core/src/main/resources/hudson/model/EnvironmentContributor/EnvVarsHtml/index_de.properties
  core/src/main/resources/hudson/model/EnvironmentContributor/EnvVarsHtml/index_fr.properties
  core/src/main/resources/hudson/model/EnvironmentContributor/EnvVarsHtml/index_it.properties
  core/src/main/resources/hudson/model/EnvironmentContributor/EnvVarsHtml/index_ja.properties
  core/src/main/resources/hudson/model/EnvironmentContributor/EnvVarsHtml/index_nl.properties
  core/src/main/resources/hudson/model/EnvironmentContributor/EnvVarsHtml/index_sr.properties
  core/src/main/resources/hudson/model/EnvironmentContributor/EnvVarsHtml/index_zh_TW.properties
Labels: ready-for-merge, web-ui, skip-changelog, rfe

#6100 Use `Files.readSymbolicLink` where possible
  core/src/main/java/jenkins/slaves/restarter/UnixSlaveRestarter.java
Labels: ready-for-merge, skip-changelog

#6104 Clean up `Jenkinsfile`
  Jenkinsfile
Labels: ready-for-merge, skip-changelog

#6099 Spotbugs fixes for `LI_LAZY_INIT_STATIC`, `NP_LOAD_OF_KNOWN_NULL_VALUE`, and `UWF_UNWRITTEN_PUBLIC_OR_PROTECTED_FIELD`
  core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java
  core/src/main/java/hudson/util/ProcessTree.java
  core/src/main/java/jenkins/security/MasterToSlaveCallable.java
  core/src/main/java/jenkins/security/apitoken/LegacyApiTokenAdministrativeMonitor.java
  core/src/main/java/jenkins/util/JSONSignatureValidator.java
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, skip-changelog

#6106 EOL `BackFiller`
  core/src/main/java/hudson/model/queue/BackFiller.java
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, removed

#6107 Fix `RV_RETURN_VALUE_IGNORED` SpotBugs violations
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/triggers/SCMTrigger.java
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, skip-changelog

#6108 Fix `RV_RETURN_VALUE_IGNORED_BAD_PRACTICE` SpotBugs violations
  core/src/main/java/jenkins/agents/WebSocketAgents.java
  core/src/main/java/jenkins/slaves/restarter/JnlpSlaveRestarterInstaller.java
  core/src/main/java/jenkins/util/AtmostOneTaskExecutor.java
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, skip-changelog

#6109 Fix `RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE` and `RCN_REDUNDANT_NULLCHECK_OF_NULL_VALUE` SpotBugs violations
  core/src/main/java/hudson/tasks/Fingerprinter.java
  core/src/main/java/jenkins/util/JSONSignatureValidator.java
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, skip-changelog

#6110 Suppress `MS_CANNOT_BE_FINAL` SpotBugs violations
  core/src/main/java/hudson/triggers/Trigger.java
  core/src/main/java/jenkins/model/Jenkins.java
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, skip-changelog

#6111 Remove JNDI support
  core/src/main/java/hudson/WebAppMain.java
  war/pom.xml
Labels: ready-for-merge, upgrade-guide-needed, removed

#6112 Remove classes which got moved to Stapler a long time ago
  core/src/main/java/hudson/util/CharSpool.java
  core/src/main/java/hudson/util/LineEndNormalizingWriter.java
Labels: ready-for-merge, skip-changelog

#6113 Ban `jline.internal` package
  core/src/main/java/hudson/model/Item.java
  pom.xml
Labels: ready-for-merge, skip-changelog

#6127 Update ATH
  essentials.yml
Labels: skip-changelog

#6121 Suppress `SE_INNER_CLASS` SpotBugs violations
  core/src/main/java/hudson/util/ProcessTree.java
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, skip-changelog

#6055 Modernise the About Jenkins page
  core/src/main/resources/hudson/AboutJenkins/index.jelly
  core/src/main/resources/hudson/AboutJenkins/sidepanel.jelly
  core/src/main/resources/lib/hudson/thirdPartyLicenses.jelly
  war/src/main/js/section-to-tabs.js
  war/src/main/less/abstracts/theme.less
  war/src/main/less/base-styles-v2.less
  war/src/main/less/modules/table.less
  war/src/main/less/modules/tabs.less
  war/src/main/less/pages/about.less
  war/webpack.config.js
Labels: ready-for-merge, web-ui, rfe, squash-merge-me

#6124 Suppress `URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD` SpotBugs violations
  core/src/main/java/hudson/model/Queue.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/search/Search.java
  core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java
  core/src/main/java/hudson/triggers/SCMTrigger.java
  core/src/main/java/jenkins/model/ModelObjectWithContextMenu.java
  core/src/main/java/jenkins/util/groovy/AbstractGroovyViewModule.java
  core/src/main/java/jenkins/widgets/HistoryPageFilter.java
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, skip-changelog

#6122 Fix `NP_BOOLEAN_RETURN_NULL` SpotBugs violations
  core/src/main/java/hudson/logging/LogRecorder.java
  core/src/main/java/hudson/security/SidACL.java
  core/src/main/java/hudson/security/SparseACL.java
  core/src/main/java/jenkins/YesNoMaybe.java
  core/src/main/java/jenkins/security/stapler/StaplerDispatchValidator.java
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, skip-changelog

#6125 Fix `EQ_GETCLASS_AND_CLASS_CONSTANT` SpotBugs violations
  core/src/main/java/hudson/model/BooleanParameterDefinition.java
  core/src/main/java/hudson/model/ChoiceParameterDefinition.java
  core/src/main/java/hudson/model/FileParameterDefinition.java
  core/src/main/java/hudson/model/PasswordParameterDefinition.java
  core/src/main/java/hudson/model/RunParameterDefinition.java
  core/src/main/java/hudson/model/StringParameterDefinition.java
  core/src/main/java/hudson/model/TextParameterDefinition.java
  core/src/main/java/hudson/util/NoClientBindProtocolSocketFactory.java
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, skip-changelog

#6123 Suppress `ST_WRITE_TO_STATIC_FROM_INSTANCE_METHOD` SpotBugs violations
  core/src/main/java/hudson/slaves/SlaveComputer.java
  core/src/main/java/hudson/tasks/ArtifactArchiver.java
  core/src/main/java/jenkins/security/QueueItemAuthenticatorMonitor.java
  core/src/main/java/jenkins/security/UserDetailsCache.java
  core/src/main/java/jenkins/slaves/NioChannelSelector.java
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, skip-changelog

#6130 Suppress `NP_NONNULL_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR` SpotBugs violation
  core/src/main/java/jenkins/util/SystemProperties.java
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, skip-changelog

#6131 Suppress `NP_UNWRITTEN_PUBLIC_OR_PROTECTED_FIELD` SpotBugs violation
  core/src/main/java/jenkins/security/apitoken/LegacyApiTokenAdministrativeMonitor.java
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, skip-changelog

#6115 Add SortPom to build
  bom/pom.xml
  cli/pom.xml
  core/pom.xml
  pom.xml
  test/pom.xml
  war/pom.xml
Labels: ready-for-merge, skip-changelog

#6129 Fix `LI_LAZY_INIT_UPDATE_STATIC` SpotBugs violation
  core/src/main/java/jenkins/security/UserDetailsCache.java
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, skip-changelog

#6136 Remove dubious warning suppressions
  core/src/main/java/hudson/security/BasicAuthenticationFilter.java
  core/src/main/java/hudson/security/FederatedLoginService.java
  core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java
  core/src/main/java/jenkins/PluginSubtypeMarker.java
  core/src/main/java/jenkins/util/TreeString.java
  core/src/main/java/jenkins/util/TreeStringBuilder.java
  core/src/test/java/jenkins/util/TreeStringBuilderTest.java
Labels: ready-for-merge, skip-changelog

#6137 `ParametersTest` flaked on Windows
  test/src/test/java/hudson/model/ParametersTest.java
Labels: ready-for-merge, skip-changelog

#6140 Fixups for #6015 and #6023
  core/src/main/java/hudson/search/Search.java
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, skip-changelog

#6142 Fix `DMI_RANDOM_USED_ONLY_ONCE` SpotBugs violations
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/slaves/EncryptedSlaveAgentJnlpFile.java
Labels: ready-for-merge, skip-changelog
