Repository jenkinsci/jenkins, pull requests merged in 2021-04, with the labels that each got.

#5377 [JENKINS-56934] fix the 'new view' link to correctly work with folders
  core/src/main/java/jenkins/model/NewViewLink.java
  core/src/test/java/jenkins/model/NewViewLinkTest.java
Labels: bug, ready-for-merge

#5398 Fix Java11 telemetry test broken after end of its sendings (MissingClassTelemetryTest)
  test/src/test/java/jenkins/telemetry/MissingClassTelemetryTest.java
Labels: skip-changelog

#5373 Bump mailer from 1.33 to 1.34
  test/pom.xml
Labels: ready-for-merge, skip-changelog

#5391 [JENKINS-65288] Bring back support for stapler.jelly.trace
  core/src/main/resources/hudson/model/UpdateCenter/index.jelly
  core/src/main/resources/lib/form/advanced/advanced.js
  core/src/main/resources/lib/form/hetero-list/hetero-list.js
  core/src/main/resources/lib/form/repeatable/repeatable.js
  core/src/main/resources/lib/form/select/select.js
  core/src/main/resources/lib/hudson/progressiveText.jelly
  core/src/main/resources/lib/hudson/projectViewNested.js
  core/src/main/resources/lib/layout/ajax.jelly
  test/src/test/java/hudson/model/FreeStyleProjectTest.java
  test/src/test/java/hudson/security/SecurityRealmTest.java
  test/src/test/java/hudson/tasks/MavenTest.java
  test/src/test/java/lib/layout/AjaxTest.java
  war/src/main/webapp/scripts/hudson-behavior.js
  war/src/main/webapp/scripts/sortable.js
Labels: developer, ready-for-merge, squash-merge-me

#5392 Improve design of last-unstable SVG icon
  war/src/main/webapp/images/build-status/build-status-sprite.svg
Labels: ready-for-merge, rfe, web-ui

#5393 Fixing deprecation link in Util.isAbsoluteUri
  core/src/main/java/hudson/Util.java
Labels: ready-for-merge, skip-changelog

#5396 Do not shorten "number" to "#"
  core/src/main/resources/hudson/model/Messages.properties
  core/src/main/resources/hudson/slaves/DumbSlave/configure-entries.jelly
  core/src/main/resources/jenkins/model/Jenkins/MasterComputer/configure.jelly
  core/src/main/resources/jenkins/model/Messages.properties
Labels: ready-for-merge, rfe, skip-changelog, web-ui

#5399 Merge back security tests into corresponding main test classes
  test/src/test/java/hudson/model/ComputerConfigDotXmlSEC1721Test.java
  test/src/test/java/hudson/model/ComputerConfigDotXmlTest.java
  test/src/test/java/hudson/model/ViewSEC1871Test.java
  test/src/test/java/hudson/model/ViewTest.java
Labels: ready-for-merge, skip-changelog

#5385 Update handlebars minimum version
  test/src/test/java/jenkins/model/AssetManagerTest.java
  war/package.json
  war/pom.xml
  war/yarn.lock
Labels: dependencies, developer, ready-for-merge

#5324 Update commons-beanutils to 1.9.4, adapt Stapler
  .github/dependabot.yml
  bom/pom.xml
  test/src/test/java/org/kohsuke/stapler/beanutils/BasicTagWithObjectProperty.java
  test/src/test/java/org/kohsuke/stapler/beanutils/BeanUtilsTagLibrary.java
  test/src/test/java/org/kohsuke/stapler/beanutils/DynaTagWithStringProperty.java
  test/src/test/java/org/kohsuke/stapler/beanutils/TagTest.java
  test/src/test/resources/org/kohsuke/stapler/beanutils/TagTest/RootActionImpl/_included.jelly
  test/src/test/resources/org/kohsuke/stapler/beanutils/TagTest/RootActionImpl/groovyCallingJellyBuilderJellyThenInclude.groovy
  test/src/test/resources/org/kohsuke/stapler/beanutils/TagTest/RootActionImpl/groovyCallingJellyBuilderJellyThenTagWithObjectProperty.groovy
  test/src/test/resources/org/kohsuke/stapler/beanutils/TagTest/RootActionImpl/groovyCallingJellyBuilderJellyThenTagWithStringProperty.groovy
  test/src/test/resources/org/kohsuke/stapler/beanutils/TagTest/RootActionImpl/groovyLibInclude.groovy
  test/src/test/resources/org/kohsuke/stapler/beanutils/TagTest/RootActionImpl/groovyLibWithClassInclude.groovy
  test/src/test/resources/org/kohsuke/stapler/beanutils/TagTest/RootActionImpl/groovyLibWithItInclude.groovy
  test/src/test/resources/org/kohsuke/stapler/beanutils/TagTest/RootActionImpl/groovyNamespaceInclude.groovy
  test/src/test/resources/org/kohsuke/stapler/beanutils/TagTest/RootActionImpl/groovyNamespaceWithClassInclude.groovy
  test/src/test/resources/org/kohsuke/stapler/beanutils/TagTest/RootActionImpl/groovyNamespaceWithItInclude.groovy
  test/src/test/resources/org/kohsuke/stapler/beanutils/TagTest/RootActionImpl/groovyViewWithReallyStaticTag.groovy
  test/src/test/resources/org/kohsuke/stapler/beanutils/TagTest/RootActionImpl/groovyViewWithTagLibTag.groovy
  test/src/test/resources/org/kohsuke/stapler/beanutils/TagTest/RootActionImpl/jellyDefineTagLib.jelly
  test/src/test/resources/org/kohsuke/stapler/beanutils/TagTest/RootActionImpl/jellyStInclude.jelly
  test/src/test/resources/org/kohsuke/stapler/beanutils/TagTest/RootActionImpl/jellyStIncludeClass.jelly
  test/src/test/resources/org/kohsuke/stapler/beanutils/TagTest/RootActionImpl/jellyStIncludeClassByName.jelly
  test/src/test/resources/org/kohsuke/stapler/beanutils/TagTest/RootActionImpl/jellyStIncludeIt.jelly
  test/src/test/resources/org/kohsuke/stapler/beanutils/TagTest/RootActionImpl/jellyViewWithReallyStaticTag.jelly
  test/src/test/resources/org/kohsuke/stapler/beanutils/TagTest/RootActionImpl/jellyViewWithTagLibTag.jelly
  test/src/test/resources/org/kohsuke/stapler/beanutils/TagTest/RootActionImpl/jellyWithMyTagLibClassName.jelly
  test/src/test/resources/org/kohsuke/stapler/beanutils/TagTest/lib/taglib
  test/src/test/resources/org/kohsuke/stapler/beanutils/TagTest/lib/thisTagHasClass.jelly
Labels: developer, internal, ready-for-merge

#5408 [JENKINS-65336] Fix load statistics graph type value
  core/src/main/resources/hudson/model/LoadStatistics/resources.js
Labels: bug, ready-for-merge, regression-fix

#5388 Update login_tr.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/index_tr.properties
  core/src/main/resources/jenkins/model/Jenkins/login_tr.properties
Labels: localization, ready-for-merge, skip-changelog

#5389 fixed some deprecation warnings
  core/src/main/java/hudson/node_monitors/NodeMonitorUpdater.java
  core/src/test/java/jenkins/util/VirtualFileTest.java
  test/src/test/java/hudson/cli/CLIActionTest.java
  test/src/test/java/hudson/cli/CLIEnvVarTest.java
  test/src/test/java/hudson/cli/CancelQuietDownCommandTest.java
  test/src/test/java/hudson/cli/CopyJobCommandTest.java
  test/src/test/java/hudson/model/ComputerConfigDotXmlTest.java
  test/src/test/java/hudson/model/ComputerTest.java
  test/src/test/java/hudson/model/ExecutorTest.java
  test/src/test/java/hudson/model/FingerprintTest.java
  test/src/test/java/hudson/model/FreestyleJobPublisherTest.java
  test/src/test/java/hudson/model/ListViewTest.java
  test/src/test/java/hudson/model/MyViewsPropertyTest.java
  test/src/test/java/hudson/model/NodeTest.java
  test/src/test/java/hudson/tasks/BuildTriggerTest.java
  test/src/test/java/hudson/util/BootFailureTest.java
  test/src/test/java/hudson/util/FormValidationSecurity1893Test.java
  test/src/test/java/jenkins/security/ApiCrumbExclusionTest.java
  test/src/test/java/jenkins/security/ApiTokenPropertyTest.java
  test/src/test/java/jenkins/security/ClassFilterImplTest.java
  test/src/test/java/jenkins/security/LastGrantedAuthoritiesPropertyTest.java
  test/src/test/java/jenkins/widgets/HistoryPageFilterCaseSensitiveSearchTest.java
  test/src/test/java/lib/form/ApplyButtonTest.java
Labels: ready-for-merge, skip-changelog

#5395 [JENKINS-65291] Update recommendations to be more specific
  core/src/main/resources/jenkins/diagnostics/ControllerExecutorsAgents/message.properties
  core/src/main/resources/jenkins/diagnostics/ControllerExecutorsNoAgents/message.properties
Labels: ready-for-merge, skip-changelog

#5402 [JENKINS-65308] Improve performance of Jenkins#trimLabels()
  core/src/main/java/hudson/model/Label.java
  test/src/test/java/hudson/model/labels/LabelAtomTest.java
Labels: ready-for-merge, rfe

#5407 Merge back further security tests into the appropriate main test classes
  test/src/test/java/hudson/model/CauseTest.java
  test/src/test/java/hudson/model/UpstreamCauseSEC1901Test.java
  test/src/test/java/hudson/security/csrf/DefaultCrumbIssuerSEC1491Test.java
  test/src/test/java/hudson/security/csrf/DefaultCrumbIssuerSEC1704Test.java
  test/src/test/java/hudson/security/csrf/DefaultCrumbIssuerSEC626Test.java
  test/src/test/java/hudson/security/csrf/DefaultCrumbIssuerTest.java
  test/src/test/java/lib/form/ExpandableTextboxSEC1498Test.java
  test/src/test/java/lib/form/ExpandableTextboxTest.java
  test/src/test/java/lib/form/ValidateButtonSEC1327Test.java
  test/src/test/java/lib/form/ValidateButtonTest.java
  test/src/test/resources/lib/form/ExpandableTextboxTest/XssProperty/config-details.jelly
  test/src/test/resources/lib/form/ValidateButtonTest/ValidateProperty/config.jelly
Labels: ready-for-merge, skip-changelog

#5403 Ignore jetty 10.x and jetty 11.x updates
  .github/dependabot.yml
Labels: ready-for-merge, skip-changelog

#5414 Update at-since annotations up to 2.288
  core/src/main/java/jenkins/UserAgentURLConnectionDecorator.java
Labels: skip-changelog

#5415 2.277.3 backporting
  test/src/test/java/jenkins/telemetry/MissingClassTelemetryTest.java
  war/pom.xml
Labels: into-lts

#5405 [JENKINS-53462] Stop using deprecated submit events
  war/src/main/webapp/scripts/yui/button/button-debug.js
  war/src/main/webapp/scripts/yui/button/button-min.js
Labels: bug, ready-for-merge

#5411 [JENKINS-65327] File parameters no longer overwrite previous files
  core/src/main/java/hudson/model/FileParameterValue.java
Labels: bug, ready-for-merge

#5418 Reduce usages of com.google.common.collect in tests
  core/src/test/java/jenkins/util/VirtualFileTest.java
  core/src/test/java/jenkins/widgets/HistoryPageFilterTest.java
  test/src/test/java/hudson/cli/CLIActionTest.java
  test/src/test/java/hudson/cli/CLITest.java
  test/src/test/java/hudson/model/AbstractProjectTest.java
  test/src/test/java/hudson/security/TokenBasedRememberMeServices2Test.java
  test/src/test/java/hudson/tasks/FingerprinterTest.java
  test/src/test/java/hudson/util/ProcessTreeTest.java
  test/src/test/java/jenkins/ClassPathTest.java
  test/src/test/java/jenkins/triggers/ReverseBuildTriggerTest.java
  test/src/test/java/jenkins/widgets/HistoryPageFilterCaseSensitiveSearchTest.java
  test/src/test/java/lib/layout/IconTest.java
Labels: ready-for-merge, skip-changelog

#5416 Fix typo in Turkish translation of Configuration
  core/src/main/resources/jenkins/management/Messages_tr.properties
Labels: localization, ready-for-merge, skip-changelog

#5421 Reduce usages of com.google.common.base
  core/src/main/java/hudson/diagnosis/OldDataMonitor.java
  core/src/main/java/hudson/security/HudsonAuthenticationEntryPoint.java
  core/src/main/java/hudson/tasks/LogRotator.java
  core/src/main/java/hudson/triggers/SCMTrigger.java
  core/src/main/java/jenkins/install/InstallUtil.java
  test/src/test/java/hudson/model/UsageStatisticsTest.java
  test/src/test/java/hudson/model/UserPropertyTest.java
  test/src/test/java/hudson/util/ArgumentListBuilder2Test.java
Labels: internal, ready-for-merge, skip-changelog

#5428 Ignore Dependabot updates for japicmp-maven-plugin
  .github/dependabot.yml
Labels: dependencies, ready-for-merge, skip-changelog

#5412 [JENKINS-65308] Reimplement Jenkins#trimLabels()
  core/src/main/java/hudson/model/Label.java
  core/src/main/java/jenkins/model/Jenkins.java
Labels: ready-for-merge, rfe

#5424 Improve slow trigger UI, logging, and tests
  core/src/main/java/hudson/triggers/SlowTriggerAdminMonitor.java
  core/src/main/java/hudson/triggers/Trigger.java
  core/src/main/resources/hudson/triggers/SlowTriggerAdminMonitor/message.groovy
  core/src/main/resources/hudson/triggers/SlowTriggerAdminMonitor/message.properties
  core/src/main/resources/hudson/triggers/SlowTriggerAdminMonitor/message_it.properties
  test/src/test/java/jenkins/triggers/TriggerTest.java
Labels: ready-for-merge, rfe, squash-merge-me

#5429 Format POM files
  cli/pom.xml
  core/pom.xml
  pom.xml
  test/pom.xml
  war/pom.xml
Labels: ready-for-merge, skip-changelog

#5431 Fix form validation message for command tool installers
  core/src/main/java/hudson/tools/AbstractCommandInstaller.java
Labels: bug, ready-for-merge, skip-changelog

#5426 Adapt to current jenkins-test-harness
  test/pom.xml
  test/src/test/java/hudson/security/csrf/CrumbExclusionTest.java
  test/src/test/java/hudson/util/RobustReflectionConverterTest.java
  test/src/test/java/jenkins/security/SuspiciousRequestFilterTest.java
  test/src/test/java/jenkins/security/apitoken/ApiTokenTestHelper.java
  test/src/test/java/jenkins/security/apitoken/LegacyApiTokenAdministrativeMonitorTest.java
Labels: dependencies, ready-for-merge, skip-changelog

#5432 Update Jira references from HUDSON to JENKINS
  bom/pom.xml
  core/pom.xml
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/WebAppMain.java
  core/src/main/java/hudson/lifecycle/UnixLifecycle.java
  core/src/main/java/hudson/model/AbstractBuild.java
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/model/Job.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/scm/SCM.java
  core/src/main/java/hudson/scm/SCMDescriptor.java
  core/src/main/java/hudson/scm/SCMRevisionState.java
  core/src/main/java/hudson/security/AuthorizationStrategy.java
  core/src/main/java/hudson/security/ContainerAuthentication.java
  core/src/main/java/hudson/security/HudsonFilter.java
  core/src/main/java/hudson/security/csrf/CrumbFilter.java
  core/src/main/java/hudson/slaves/SlaveComputer.java
  core/src/main/java/hudson/util/QueryParameterMap.java
  core/src/main/java/hudson/util/XStream2.java
  core/src/main/java/hudson/util/jna/GNUCLibrary.java
  core/src/test/java/hudson/UtilTest.java
  core/src/test/java/hudson/scheduler/CronTabDayOfWeekLocaleTest.java
  core/src/test/java/hudson/scheduler/CronTabTest.java
  core/src/test/java/hudson/util/XStream2Test.java
  war/src/main/webapp/WEB-INF/web.xml
  war/src/main/webapp/scripts/prototype.js
Labels: ready-for-merge, skip-changelog

#5419 Use declaring class as qualifier
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/cli/DeleteJobCommand.java
  core/src/main/java/hudson/cli/ReloadJobCommand.java
  core/src/main/java/hudson/model/AbstractProject.java
  core/src/main/java/hudson/model/Api.java
  core/src/main/java/hudson/model/Fingerprint.java
  core/src/main/java/hudson/model/FingerprintCleanupThread.java
  core/src/main/java/hudson/model/Hudson.java
  core/src/main/java/hudson/security/SecurityRealm.java
  core/src/main/java/hudson/slaves/NodeProperty.java
  core/src/main/java/jenkins/model/GlobalProjectNamingStrategyConfiguration.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/slaves/restarter/JnlpSlaveRestarterInstaller.java
  core/src/test/java/hudson/model/JobTest.java
  core/src/test/java/hudson/util/FileChannelWriterTest.java
  test/src/test/java/hudson/CustomPluginManagerTest.java
  test/src/test/java/hudson/ProcTest.java
  test/src/test/java/hudson/cli/AddJobToViewCommandTest.java
  test/src/test/java/hudson/cli/BuildCommandTest.java
  test/src/test/java/hudson/cli/ConsoleCommandTest.java
  test/src/test/java/hudson/cli/DeleteBuildsCommandTest.java
  test/src/test/java/hudson/cli/DeleteJobCommandTest.java
  test/src/test/java/hudson/cli/ListJobsCommandTest.java
  test/src/test/java/hudson/cli/ReloadJobCommandTest.java
  test/src/test/java/hudson/cli/RemoveJobFromViewCommandTest.java
  test/src/test/java/hudson/cli/RunRangeCommand2Test.java
  test/src/test/java/hudson/cli/RunRangeCommandTest.java
  test/src/test/java/hudson/cli/SetBuildDescriptionCommandTest.java
  test/src/test/java/hudson/cli/ViewManipulationTestBase.java
  test/src/test/java/hudson/model/AbstractProjectTest.java
  test/src/test/java/hudson/model/MyViewTest.java
  test/src/test/java/hudson/model/NodeTest.java
  test/src/test/java/hudson/model/ProjectTest.java
  test/src/test/java/hudson/model/QueueTest.java
  test/src/test/java/hudson/model/ViewTest.java
  test/src/test/java/hudson/model/labels/LabelExpressionTest.java
  test/src/test/java/hudson/model/queue/MaintainCanTakeStrengtheningTest.java
  test/src/test/java/hudson/security/ACLTest.java
  test/src/test/java/jenkins/model/JenkinsTest.java
  test/src/test/java/jenkins/security/UserDetailsCacheTest.java
  test/src/test/java/lib/form/ComboBoxTest.java
  test/src/test/java/lib/form/PasswordTest.java
  test/src/test/java/lib/layout/AjaxTest.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5440 Exclude Winstone upgrades from dependabot
  .github/dependabot.yml
Labels: skip-changelog

#5437 Winstone 5.17: Update Jetty from 9.4.39.v20210325 to 9.4.40.v20210413
  war/pom.xml
Labels: dependencies, ready-for-merge, rfe, squash-merge-me

#5442 Add link to LTS release checklist in MAINTAINERS doc
  docs/MAINTAINERS.adoc
Labels: ready-for-merge, skip-changelog

#5435 [JENKINS-52356] Support ZIP64 in ZipArchiver
  core/src/main/java/hudson/util/io/ZipArchiver.java
  core/src/test/java/hudson/util/io/ZipArchiverTest.java
Labels: bug, ready-for-merge, squash-merge-me

#5441 Backporting for LTS 2.277.4
  bom/pom.xml
  core/src/main/java/jenkins/model/NewViewLink.java
  core/src/main/resources/hudson/model/LoadStatistics/resources.js
  core/src/test/java/jenkins/model/NewViewLinkTest.java
  war/src/main/less/base/yui-compatibility.less
Labels: into-lts

#5427 [JENKINS-65386] added some examples on how to archive multiple artifacts
  core/src/main/resources/hudson/tasks/ArtifactArchiver/help-artifacts.html
  core/src/main/resources/hudson/tasks/ArtifactArchiver/help.html
Labels: rfe, skip-changelog, squash-merge-me

#5444 Remove instance-identity from ALWAYS_READABLE_PATHS
  core/src/main/java/jenkins/model/Jenkins.java
Labels: ready-for-merge, skip-changelog

#5448 [JENKINS-65190] The build history layout is out of bounds if set long buildName
  war/src/main/less/modules/side-panel-widgets.less
Labels: bug, ready-for-merge

#5164 Replaced synchronized String Object with Object
  core/src/main/java/hudson/model/Computer.java
Labels: internal, ready-for-merge, skip-changelog, squash-merge-me
