Repository jenkinsci/jenkins, pull requests merged in 2021-03, with the labels that each got.

#5313 Use native Java functionality rather than Guava's Lists#newArrayList, Maps#newHashMap, and Sets#newHashSet where possible
  core/src/main/java/hudson/ClassicPluginStrategy.java
  core/src/main/java/hudson/ExtensionFinder.java
  core/src/main/java/hudson/ExtensionList.java
  core/src/main/java/hudson/ProxyConfiguration.java
  core/src/main/java/hudson/model/ParametersAction.java
  core/src/main/java/jenkins/ExtensionComponentSet.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/scm/SCMCheckoutStrategyDescriptor.java
  core/src/test/java/hudson/EnvVarsTest.java
Labels: internal, ready-for-merge, skip-changelog

#5317 Upgrade to winstone 5.15 to include Jetty 9.4.38.v20210224
  war/pom.xml
Labels: bug, ready-for-merge, regression-fix

#5312 Replace usages of deprecated jenkins.widgets.HistoryPageFilter.add(java.util.List) with non-deprecated jenkins.widgets.HistoryPageFilter.add(Iterable)
  core/src/test/java/jenkins/widgets/HistoryPageFilterTest.java
Labels: ready-for-merge, skip-changelog

#5311 Downgrade recently-upgraded detached plugins
  war/pom.xml
Labels: ready-for-merge, rfe

#5138 [JENKINS-64510] Necessary pieces to get TCP agent reconnect working.
  core/src/main/java/jenkins/slaves/DefaultJnlpSlaveReceiver.java
Labels: bug, ready-for-merge

#5315 Update jetty-maven-plugin to match winstone
  war/pom.xml
Labels: ready-for-merge, skip-changelog

#5054 Log a message about the interrupted exception at this level
  core/src/main/java/hudson/util/ProcessTree.java
Labels: ready-for-merge, skip-changelog

#5314 Clean up JUnit assertions
  core/src/test/java/hudson/LauncherTest.java
  core/src/test/java/hudson/UtilTest.java
  core/src/test/java/hudson/model/AbstractItemTest.java
  core/src/test/java/hudson/model/RunTest.java
  core/src/test/java/hudson/search/SearchTest.java
  core/src/test/java/hudson/util/PackedMapTest.java
  core/src/test/java/hudson/util/RobustReflectionConverterTest.java
  core/src/test/java/org/acegisecurity/util/FieldUtilsTest.java
  test/src/test/java/hudson/PluginManagerTest.java
  test/src/test/java/hudson/init/InitMilestoneTest.java
  test/src/test/java/hudson/logging/LogRecorderManagerTest.java
  test/src/test/java/hudson/model/CauseTest.java
  test/src/test/java/hudson/model/DirectoryBrowserSupportTest.java
  test/src/test/java/hudson/model/ExecutorTest.java
  test/src/test/java/hudson/model/FreestyleJobPublisherTest.java
  test/src/test/java/hudson/model/ListViewTest.java
  test/src/test/java/hudson/model/ParametersAction2Test.java
  test/src/test/java/hudson/model/ProjectTest.java
  test/src/test/java/hudson/model/QueueTest.java
  test/src/test/java/hudson/model/ViewDescriptorTest.java
  test/src/test/java/hudson/model/ViewTest.java
  test/src/test/java/hudson/model/labels/LabelExpressionTest.java
  test/src/test/java/hudson/security/PermissionGroupTest.java
  test/src/test/java/hudson/security/SecurityRealmTest.java
  test/src/test/java/hudson/tasks/FingerprinterTest.java
  test/src/test/java/hudson/tasks/UserAvatarResolverTest.java
  test/src/test/java/hudson/tools/ToolLocationTest.java
  test/src/test/java/hudson/triggers/SCMTriggerTest.java
  test/src/test/java/hudson/util/FormFieldValidatorTest.java
  test/src/test/java/jenkins/model/JenkinsTest.java
  test/src/test/java/jenkins/security/FrameOptionsPageDecoratorTest.java
  test/src/test/java/jenkins/security/Security177Test.java
  test/src/test/java/jenkins/security/SpySecurityListener.java
  test/src/test/java/jenkins/security/stapler/Security914Test.java
  test/src/test/java/lib/form/OptionTest.java
Labels: internal, ready-for-merge, skip-changelog

#5327 Delete SSH-specific scenarios from CLITest
  pom.xml
  test/pom.xml
  test/src/test/java/hudson/cli/CLITest.java
  war/pom.xml
Labels: skip-changelog

#5332 Stable 2.277 winstone 5.15
  war/pom.xml
Labels: into-lts

#5322 Migrate from Guava's com.google.common.util.concurrent.SettableFuture to Java 8's java.util.concurrent.CompletableFuture
  core/src/main/java/jenkins/util/AtmostOneTaskExecutor.java
Labels: ready-for-merge, skip-changelog

#5316 [JENKINS-64972] Help-buttons are not working when they are at the top of draggable div
  core/src/main/resources/lib/form/hetero-list.jelly
  war/src/main/less/base/style.less
Labels: bug, ready-for-merge, regression-fix

#5330 Bump sshd from 3.0.1 to 3.0.3
  war/pom.xml
Labels: dependencies, java, ready-for-merge, skip-changelog

#5340 Migrate from com.google.common.base.Function to java.util.function.Consumer in hudson.model.listeners.ItemListener
  core/src/main/java/hudson/model/listeners/ItemListener.java
Labels: ready-for-merge, skip-changelog

#5333 [JENKINS-65017] Prevent bugs in form validation from messing up the entire page
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: bug, ready-for-merge

#5078 Indicate in configuration which admin monitors are security-related
  core/src/main/resources/hudson/PluginManager/_table.css
  core/src/main/resources/jenkins/management/AdministrativeMonitorsConfiguration/config.groovy
  war/src/main/less/base-styles-v2.less
  war/src/main/less/modules/badges.less
Labels: ready-for-merge, rfe

#5334 Add Japanese translations for New Job screen
  core/src/main/resources/hudson/model/View/newJob_ja.properties
Labels: localization, ready-for-merge, rfe

#5326 Be quiet if Queue.save gets ClosedByInterruptException
  core/src/main/java/hudson/model/Queue.java
Labels: bug, ready-for-merge

#5242 Bump antisamy-markup-formatter from 1.0 to 2.1
  test/pom.xml
Labels: internal, ready-for-merge, skip-changelog, squash-merge-me

#5305 [JENKINS-64931] no need to synchronize on Queue as queue is using a Lock and this under certain conditions can generate a deadlock. look at the dump attached to the issue JENKINS-64931
  core/src/main/java/hudson/model/queue/FutureImpl.java
Labels: bug, ready-for-merge

#5235 replaced MS_SHOULD_BE_FINAL general spotbugs exclude with individual excludes
  core/src/main/java/hudson/ClassicPluginStrategy.java
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/Plugin.java
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/Proc.java
  core/src/main/java/hudson/Util.java
  core/src/main/java/hudson/console/ConsoleNote.java
  core/src/main/java/hudson/diagnosis/HudsonHomeDiskUsageChecker.java
  core/src/main/java/hudson/logging/LogRecorderManager.java
  core/src/main/java/hudson/model/AbstractCIBase.java
  core/src/main/java/hudson/model/AbstractItem.java
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/model/FileParameterValue.java
  core/src/main/java/hudson/model/LoadStatistics.java
  core/src/main/java/hudson/model/Node.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/model/UsageStatistics.java
  core/src/main/java/hudson/model/User.java
  core/src/main/java/hudson/scm/SCMRevisionState.java
  core/src/main/java/hudson/search/Search.java
  core/src/main/java/hudson/security/GlobalSecurityConfiguration.java
  core/src/main/java/hudson/security/TokenBasedRememberMeServices2.java
  core/src/main/java/hudson/security/csrf/DefaultCrumbIssuer.java
  core/src/main/java/hudson/security/csrf/GlobalCrumbIssuerConfiguration.java
  core/src/main/java/hudson/slaves/CloudSlaveRetentionStrategy.java
  core/src/main/java/hudson/slaves/NodeProvisioner.java
  core/src/main/java/hudson/tasks/_maven/Maven3MojoNote.java
  core/src/main/java/hudson/tasks/_maven/MavenErrorNote.java
  core/src/main/java/hudson/tasks/_maven/MavenMojoNote.java
  core/src/main/java/hudson/tasks/_maven/MavenWarningNote.java
  core/src/main/java/hudson/triggers/SCMTrigger.java
  core/src/main/java/hudson/triggers/SlowTriggerAdminMonitor.java
  core/src/main/java/hudson/triggers/Trigger.java
  core/src/main/java/hudson/util/ChartUtil.java
  core/src/main/java/hudson/util/ColorPalette.java
  core/src/main/java/hudson/util/Secret.java
  core/src/main/java/hudson/util/io/ArchiverFactory.java
  core/src/main/java/jenkins/install/SetupWizard.java
  core/src/main/java/jenkins/model/IdStrategy.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/model/StandardArtifactManager.java
  core/src/main/java/jenkins/model/item_category/ItemCategory.java
  core/src/main/java/jenkins/security/BasicHeaderRealPasswordAuthenticator.java
  core/src/main/java/jenkins/security/ResourceDomainRootAction.java
  core/src/main/java/jenkins/security/s2m/CallableDirectionChecker.java
  core/src/main/java/jenkins/security/s2m/DefaultFilePathFilter.java
  core/src/main/java/jenkins/security/seed/UserSeedProperty.java
  core/src/main/java/jenkins/security/stapler/StaplerDispatchValidator.java
  core/src/main/java/jenkins/security/stapler/StaticRoutingDecisionProvider.java
  core/src/main/java/jenkins/security/stapler/TypedFilter.java
  core/src/main/java/jenkins/tools/GlobalToolConfiguration.java
  core/src/main/java/jenkins/util/FullDuplexHttpService.java
  core/src/main/java/jenkins/util/xstream/XStreamDOM.java
  src/findbugs/findbugs-excludes.xml
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5343 Bump Node.js from 14.15.1 to 14.16.0
  war/pom.xml
Labels: ready-for-merge, skip-changelog

#5065 Initial new icons
  core/src/main/java/org/jenkins/ui/icon/BuildStatusIcon.java
  core/src/main/java/org/jenkins/ui/icon/Icon.java
  core/src/main/java/org/jenkins/ui/icon/IconFormat.java
  core/src/main/java/org/jenkins/ui/icon/IconSet.java
  core/src/main/java/org/jenkins/ui/icon/WeatherIcon.java
  core/src/main/resources/hudson/AboutJenkins/index.jelly
  core/src/main/resources/hudson/model/UpdateCenter/CompleteBatchJob/Pending/status.jelly
  core/src/main/resources/hudson/model/UpdateCenter/CompleteBatchJob/Running/status.jelly
  core/src/main/resources/hudson/model/UpdateCenter/DownloadJob/Installing/status.jelly
  core/src/main/resources/hudson/model/UpdateCenter/DownloadJob/Pending/status.jelly
  core/src/main/resources/hudson/model/UpdateCenter/DownloadJob/Skipped/status.jelly
  core/src/main/resources/hudson/model/UpdateCenter/RestartJenkinsJob/Pending/status.jelly
  core/src/main/resources/hudson/model/UpdateCenter/RestartJenkinsJob/Running/status.jelly
  core/src/main/resources/hudson/model/UpdateCenter/body.jelly
  core/src/main/resources/jenkins/model/Jenkins/manage.jelly
  core/src/main/resources/lib/layout/breadcrumbs.js
  core/src/main/resources/lib/layout/icon.jelly
  test/src/test/java/lib/layout/IconTest.java
  test/src/test/resources/lib/layout/IconTest/TestBallColorTd/index.jelly
  test/src/test/resources/lib/layout/IconTest/TestIcons/index.jelly
  test/src/test/resources/lib/layout/IconTest/TestTasks/index.jelly
  war/src/main/less/abstracts/theme.less
  war/src/main/less/base/style.less
  war/src/main/less/base/yui-compatibility.less
  war/src/main/less/modules/icons.less
  war/src/main/less/modules/manage-jenkins.less
  war/src/main/webapp/images/build-status/build-status-sprite.svg
  war/src/main/webapp/images/build-status/weather-sprite.svg
  war/src/main/webapp/images/material-icons/computer-24px.svg
  war/src/main/webapp/images/material-icons/view_headline-24px.svg
  war/src/main/webapp/images/svgs/clipboard-list-solid.svg
Labels: major-rfe, plugin-api-changes, ready-for-merge, upgrade-guide-needed, web-ui

#5341 Accept negative numbers in INPUT.number
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: bug, ready-for-merge

#5342 Use versions from parent POM where possible
  cli/pom.xml
  core/pom.xml
  pom.xml
  test/pom.xml
  war/pom.xml
Labels: ready-for-merge, skip-changelog

#5206 Bump sshd-core to 2.6.0 and update tests
  cli/pom.xml
  cli/src/main/java/hudson/cli/PrivateKeyProvider.java
  cli/src/test/java/hudson/cli/PrivateKeyProviderTest.java
  cli/src/test/resources/hudson/cli/blank
  cli/src/test/resources/hudson/cli/openssh-multiple-keys
  cli/src/test/resources/hudson/cli/openssh-pkcs8
  cli/src/test/resources/hudson/cli/openssh-rfc4716
  cli/src/test/resources/hudson/cli/openssh-unsuported
Labels: dependencies, java, ready-for-merge, rfe

#5355 Fix build issues
  cli/src/main/java/hudson/cli/PrivateKeyProvider.java
  pom.xml
Labels: skip-changelog

#5338 Remove bundled Ant and Javadoc plugins
  test/src/test/resources/hudson/ClassicPluginStrategyTest/testDisabledDependencyClassLoader.zip
  war/pom.xml
Labels: ready-for-merge, rfe, upgrade-guide-needed

#5354 Icon typo fixes (used non transparent gif by accident)
  core/src/main/java/org/jenkins/ui/icon/IconSet.java
Labels: bug, ready-for-merge, regression-fix

#5356 Fix sort order
  core/src/main/resources/jenkins/split-plugins.txt
Labels: skip-changelog

#5357 Test cleanup
  core/src/test/java/hudson/FilePathTest.java
  core/src/test/java/hudson/XmlFileTest.java
  core/src/test/java/hudson/model/ActionableTest.java
  core/src/test/java/hudson/model/ChoiceParameterDefinitionTest.java
  core/src/test/java/hudson/model/ComputerTest.java
  core/src/test/java/hudson/model/UserIdMapperTest.java
  core/src/test/java/hudson/tasks/BuildStepCompatibilityLayerTest.java
  core/src/test/java/hudson/util/FileChannelWriterTest.java
  core/src/test/java/hudson/util/IsOverriddenTest.java
  core/src/test/java/hudson/util/SecretTest.java
  core/src/test/java/jenkins/ResilientJsonObjectTest.java
  core/src/test/java/jenkins/model/lazy/AbstractLazyLoadRunMapTest.java
  core/src/test/java/jenkins/util/JenkinsJVMTest.java
  core/src/test/java/jenkins/util/ResourceBundleUtilTest.java
  test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java
  test/src/test/java/hudson/console/ConsoleLogFilterTest.java
  test/src/test/java/hudson/model/AbstractProjectTest.java
  test/src/test/java/hudson/model/ComputerConfigDotXmlTest.java
  test/src/test/java/hudson/model/DescriptorTest.java
  test/src/test/java/hudson/model/QueueTest.java
  test/src/test/java/hudson/model/labels/LabelAtomSecurity1986Test.java
  test/src/test/java/hudson/security/HudsonPrivateSecurityRealmTest.java
  test/src/test/java/hudson/security/PermissionGroupTest.java
  test/src/test/java/hudson/slaves/PingThreadTest.java
  test/src/test/java/jenkins/model/JenkinsSystemReadAndManagePermissionTest.java
  test/src/test/java/jenkins/security/UserDetailsCacheTest.java
Labels: ready-for-merge, skip-changelog

#5347 Update bundled bouncycastle-api plugin to 2.20.
  war/pom.xml
Labels: ready-for-merge, rfe

#5360 Use xstream 1.4.16
  bom/pom.xml
Labels: dependencies, ready-for-merge, rfe

#5359 Ensure that plugins are sorted by name
  core/src/main/java/hudson/model/UpdateSite.java
  test/src/test/java/hudson/model/UpdateSiteTest.java
  test/src/test/resources/plugins/available-update-center.json
Labels: bug, ready-for-merge

#5366 Bump matrix-auth from 2.6.5 to 2.6.6
  pom.xml
Labels: ready-for-merge, rfe

#4623 Default to POST form validation
  core/src/main/resources/lib/form/combobox.jelly
  core/src/main/resources/lib/form/number.jelly
  core/src/main/resources/lib/form/password.jelly
  core/src/main/resources/lib/form/select.jelly
  core/src/main/resources/lib/form/textarea.jelly
  core/src/main/resources/lib/form/textbox.jelly
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, rfe

#5367 JENKINS-62006 Fix a classloading issue while executing ProcessTree.get()
  core/src/main/java/jenkins/agents/AgentComputerUtil.java
Labels: bug, ready-for-merge

#5364 Update at-since annotations up to 2.284
  core/src/main/java/hudson/model/BooleanParameterDefinition.java
  core/src/main/java/hudson/model/FileParameterDefinition.java
  core/src/main/java/hudson/model/ParameterDefinition.java
  core/src/main/java/hudson/model/StringParameterDefinition.java
  core/src/main/java/hudson/model/TextParameterDefinition.java
  core/src/main/java/org/jenkins/ui/icon/Icon.java
  core/src/main/java/org/jenkins/ui/icon/IconFormat.java
Labels: internal, ready-for-merge, skip-changelog

#5362 Bump mailer from 1.32.1 to 1.33
  test/pom.xml
  test/src/test/resources/hudson/model/UsageStatisticsTest/jobs.json
Labels: ready-for-merge, skip-changelog

#5371 2.277.2 backporting
  core/src/main/java/hudson/model/queue/FutureImpl.java
  core/src/main/java/jenkins/agents/AgentComputerUtil.java
  core/src/main/java/jenkins/management/AdministrativeMonitorsApi.java
  core/src/main/resources/jenkins/management/AdministrativeMonitorsDecorator/footer.jelly
  core/src/main/resources/lib/form/hetero-list.jelly
  essentials.yml
  war/src/main/less/base/style.less
Labels: into-lts

#5368 Add a Jenkins User-Agent header to outgoing HTTP requests
  core/src/main/java/jenkins/UserAgentURLConnectionDecorator.java
Labels: ready-for-merge, rfe, upgrade-guide-needed

#5376 Refactored multiple assertion tests into parameterized ones
  cli/src/test/java/hudson/cli/HexDumpTest.java
Labels: ready-for-merge, skip-changelog

#5375 fix non compilable code on eclipse compiler
  core/src/main/java/hudson/DescriptorExtensionList.java
Labels: internal, ready-for-merge, skip-changelog

#5337 Add a couple of admin monitors for executors on the controller
  core/src/main/java/jenkins/diagnostics/ControllerExecutorsAgents.java
  core/src/main/java/jenkins/diagnostics/ControllerExecutorsNoAgents.java
  core/src/main/resources/jenkins/diagnostics/ControllerExecutorsAgents/message.jelly
  core/src/main/resources/jenkins/diagnostics/ControllerExecutorsAgents/message.properties
  core/src/main/resources/jenkins/diagnostics/ControllerExecutorsNoAgents/message.jelly
  core/src/main/resources/jenkins/diagnostics/ControllerExecutorsNoAgents/message.properties
  core/src/main/resources/jenkins/diagnostics/Messages.properties
  test/src/test/java/jenkins/diagnostics/ControllerExecutorsAgentsTest.java
  test/src/test/java/jenkins/diagnostics/ControllerExecutorsNoAgentsTest.java
Labels: ready-for-merge, rfe

#5192 [JENKINS-63855] Support 'min' and 'max' values in the <f:number> tag
  core/src/main/resources/lib/form/number.jelly
  test/src/test/java/lib/form/NumberTest.java
  test/src/test/resources/lib/form/NumberTest/MaxValidation/index.jelly
  test/src/test/resources/lib/form/NumberTest/MinAndMaxValidation/index.jelly
  test/src/test/resources/lib/form/NumberTest/MinValidation/index.jelly
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: developer, ready-for-merge, rfe

#5379 [JENKINS-65021] Disabled dropdown items no longer look disabled
  war/src/main/less/base/yui-compatibility.less
Labels: bug, ready-for-merge, regression-fix

#5380 Winstone 5.16 which includes Jetty 9.4.39.v20210325
  war/pom.xml
Labels: dependencies, java, ready-for-merge

#5370 [JENKINS-36707] Add `CI` environment variable
  core/src/main/java/jenkins/model/CoreEnvironmentContributor.java
  core/src/main/resources/jenkins/model/CoreEnvironmentContributor/buildEnv.groovy
  core/src/main/resources/jenkins/model/CoreEnvironmentContributor/buildEnv.properties
Labels: ready-for-merge, rfe

#5365 [JENKINS-65172] Better support for remote platform-plugins.json
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/java/jenkins/install/SetupWizard.java
  test/src/test/java/jenkins/install/SetupWizardTest.java
Labels: ready-for-merge, rfe
