Repository jenkinsci/jenkins, pull requests merged in 2021-11, with the labels that each got.

#5865 [JENKINS-66993] Do not register `AntClassLoader` as parallel-capable
  core/src/main/java/hudson/PluginFirstClassLoader.java
  core/src/main/java/jenkins/util/AntClassLoader.java
Labels: regression-fix, ready-for-merge

#5842 Modernise the 'New view' and 'New node' pages
  core/src/main/resources/hudson/model/ComputerSet/new.jelly
  core/src/main/resources/jenkins/model/Jenkins/newView.jelly
  core/src/main/resources/jenkins/model/Jenkins/newView.properties
  core/src/main/resources/lib/form/advanced.jelly
  core/src/main/resources/lib/form/dropdownList.jelly
  core/src/main/resources/lib/form/entry.jelly
  core/src/main/resources/lib/form/form.jelly
  core/src/main/resources/lib/form/helpLink.jelly
  core/src/main/resources/lib/form/hetero-list.jelly
  core/src/main/resources/lib/form/number.jelly
  core/src/main/resources/lib/form/section.jelly
  core/src/main/resources/lib/form/section_.css
  core/src/main/resources/lib/form/textbox.jelly
  core/src/main/resources/lib/hudson/newFromList/form.jelly
  core/src/main/resources/lib/hudson/newFromList/form.properties
  core/src/main/resources/lib/hudson/newFromList/validation.js
  test/src/test/java/hudson/model/HelpLinkTest.java
  test/src/test/java/hudson/model/ParametersTest.java
  test/src/test/java/lib/form/AdvancedButtonTest.java
  test/src/test/java/lib/form/HeteroListTest.java
  war/src/main/js/widgets/config/tabbar.less
  war/src/main/less/abstracts/theme.less
  war/src/main/less/base/style.less
  war/src/main/less/base/yui-compatibility.less
  war/src/main/less/modules/app-bar.less
  war/src/main/less/modules/form.less
  war/src/main/less/modules/section.less
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, web-ui, rfe

#5872 Add a documentation for the attributes of `buildLink`
  core/src/main/resources/lib/hudson/buildLink.jelly
Labels: ready-for-merge, skip-changelog

#5515 [JENKINS-60866] Advanced button, build health, confirmation link, URI encoding monitor
  core/src/main/resources/jenkins/diagnostics/URICheckEncodingMonitor/adjunct.js
  core/src/main/resources/jenkins/diagnostics/URICheckEncodingMonitor/message.jelly
  core/src/main/resources/lib/form/advanced.jelly
  core/src/main/resources/lib/form/advanced/advanced.js
  core/src/main/resources/lib/form/validateButton.jelly
  core/src/main/resources/lib/form/validateButton/adjunct.js
  core/src/main/resources/lib/hudson/buildHealth.jelly
  core/src/main/resources/lib/layout/confirmationLink.jelly
  core/src/main/resources/lib/layout/confirmationLink/adjunct.js
  test/src/test/java/hudson/model/ManagementLinkTest.java
  test/src/test/java/lib/layout/ConfirmationLinkTest.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5801 [JENKINS-66845] Fix "User Defined Time Zone" configuration field to correctly show corresponding user's timezone value #Hacktoberfest
  core/src/main/java/hudson/model/TimeZoneProperty.java
Labels: ready-for-merge, bug, hacktoberfest-accepted

#5845 Remove java webstart warning from agent page
  core/src/main/resources/hudson/slaves/JNLPLauncher/main.jelly
  core/src/main/resources/hudson/slaves/JNLPLauncher/main_it.properties
Labels: ready-for-merge, skip-changelog

#5852 [JENKINS-66718] Un-inlining script in BuildTimelineWidget/control.jelly
  core/src/main/resources/hudson/model/BuildTimelineWidget/build-timeline-widget.js
  core/src/main/resources/hudson/model/BuildTimelineWidget/control.jelly
Labels: ready-for-merge, skip-changelog

#5864 [JENKINS-67002] protect Jenkins against bad RestartListeners
  core/src/main/java/jenkins/model/Jenkins.java
Labels: ready-for-merge, bug

#5875 Fix missing project hyperlink in build history
  core/src/main/resources/hudson/widgets/HistoryWidget/entry.jelly
Labels: ready-for-merge, web-ui, bug

#5878 Use vectorized sprite on rage
  core/src/main/resources/jenkins/model/Jenkins/oops.jelly
  war/src/main/webapp/images/rage.png
  war/src/main/webapp/images/rage.svg
Labels: ready-for-merge, web-ui, skip-changelog

#5857 `surefire.runOrder=alphabetical` for reproducibility
  pom.xml
Labels: ready-for-merge, skip-changelog

#5856 Unfork `AntClassLoader`
  core/src/main/java/jenkins/util/AntClassLoader.java
Labels: ready-for-merge, developer

#5850 [JENKINS-66749] Missing spaces in upstream/downstream project view
  core/src/main/resources/lib/hudson/buildCaption.jelly
  core/src/main/resources/lib/hudson/jobLink.jelly
  war/src/main/less/base/style.less
Labels: ready-for-merge, web-ui, bug

#5871 Use CSS animation for console progress
  core/src/main/resources/hudson/model/Run/console.jelly
  core/src/main/resources/hudson/model/TaskAction/log.jelly
  core/src/main/resources/hudson/slaves/SlaveComputer/log.jelly
  core/src/main/resources/jenkins/management/AsynchronousAdministrativeMonitor/log.groovy
  core/src/main/resources/lib/layout/progressAnimation.jelly
  war/src/main/less/base-styles-v2.less
  war/src/main/less/modules/progress-animation.less
Labels: ready-for-merge, web-ui, rfe

#5881 [JENKINS-67061] Fix overload in ConfigDirectory
  core/src/main/java/jenkins/security/s2m/ConfigDirectory.java
Labels: regression-fix, ready-for-merge, bug

#5892 `AbstractBuild` should implement `getParentExecutable` better
  core/src/main/java/hudson/model/AbstractBuild.java
Labels: ready-for-merge, skip-changelog

#5887 Add a gap between icon and text in build links
  core/src/main/resources/lib/hudson/buildLink.jelly
Labels: ready-for-merge, bug

#5524 Stop bundling unnecessary copy of ASM 5
  core/pom.xml
Labels: ready-for-merge, upgrade-guide-needed, squash-merge-me, dependencies

#5896 Remove unused `jenkins.util.io.LinesStream`
  core/src/main/java/hudson/util/TextFile.java
  core/src/main/java/jenkins/security/s2m/ConfigFile.java
  core/src/main/java/jenkins/util/io/LinesStream.java
Labels: ready-for-merge, skip-changelog

#5894 Fix typo in `ClassicPluginStrategy`
  core/src/main/java/hudson/ClassicPluginStrategy.java
Labels: ready-for-merge, skip-changelog

#5879 Add computer offline sprite override
  core/src/main/java/hudson/model/Computer.java
Labels: ready-for-merge, skip-changelog

#5898 Bump `bouncycastle-api` from 2.20 to 2.25
  war/pom.xml
Labels: ready-for-merge, rfe, dependencies

#5889 Improve artifact list readability in dark theme
  war/src/main/less/base/yui-compatibility.less
Labels: ready-for-merge, web-ui, rfe

#5862 feat: Add ability to upload a plugin via URL [JENKINS-4814]
  core/src/main/java/hudson/PluginManager.java
  core/src/main/resources/hudson/Messages.properties
  core/src/main/resources/hudson/PluginManager/advanced.jelly
  core/src/main/resources/hudson/PluginManager/advanced.properties
  core/src/main/resources/hudson/PluginManager/advanced_bg.properties
  core/src/main/resources/hudson/PluginManager/advanced_da.properties
  core/src/main/resources/hudson/PluginManager/advanced_de.properties
  core/src/main/resources/hudson/PluginManager/advanced_es.properties
  core/src/main/resources/hudson/PluginManager/advanced_fi.properties
  core/src/main/resources/hudson/PluginManager/advanced_fr.properties
  core/src/main/resources/hudson/PluginManager/advanced_hu.properties
  core/src/main/resources/hudson/PluginManager/advanced_it.properties
  core/src/main/resources/hudson/PluginManager/advanced_ja.properties
  core/src/main/resources/hudson/PluginManager/advanced_ko.properties
  core/src/main/resources/hudson/PluginManager/advanced_lv.properties
  core/src/main/resources/hudson/PluginManager/advanced_nb_NO.properties
  core/src/main/resources/hudson/PluginManager/advanced_nl.properties
  core/src/main/resources/hudson/PluginManager/advanced_pl.properties
  core/src/main/resources/hudson/PluginManager/advanced_pt_BR.properties
  core/src/main/resources/hudson/PluginManager/advanced_pt_PT.properties
  core/src/main/resources/hudson/PluginManager/advanced_ru.properties
  core/src/main/resources/hudson/PluginManager/advanced_sr.properties
  core/src/main/resources/hudson/PluginManager/advanced_sv_SE.properties
  core/src/main/resources/hudson/PluginManager/advanced_tr.properties
  core/src/main/resources/hudson/PluginManager/advanced_zh_TW.properties
  test/src/test/java/hudson/PluginManagerTest.java
Labels: ready-for-merge, rfe, squash-merge-me

#5870 Avoid false positives in plugin search (installed tab)
  core/src/main/resources/hudson/PluginManager/_table.js
Labels: ready-for-merge, bug

#5893 JENKINS-67071 Adjust class for section header change
  core/src/main/resources/lib/form/section_.js
  war/src/main/js/config-scrollspy.less
  war/src/main/js/widgets/config/model/ConfigTableMetaData.js
  war/src/test/js/widgets/config/freestyle-config-scrollspy.html
  war/src/test/js/widgets/config/freestyle-config-scrollspy_bg.html
  war/src/test/js/widgets/config/freestyle-config-tabbed.html
  war/src/test/js/widgets/config/freestyle-config-tabbed_bg.html
Labels: ready-for-merge, skip-changelog

#5835 Hacktoberfest [JENKINS-66730] Un-inlining AsynchPeople/index.jelly
  core/src/main/resources/hudson/model/View/AsynchPeople/index.jelly
  core/src/main/resources/hudson/model/View/AsynchPeople/people-resources.js
Labels: ready-for-merge, skip-changelog, squash-merge-me, hacktoberfest-accepted

#5900 [JENKINS-67063] Revert canonicalization of entries when untarring
  core/src/main/java/hudson/FilePath.java
Labels: regression-fix, ready-for-merge, bug, alternative

#5902 Store plain `ArrayList` for `InterruptedBuildAction.causes`
  core/src/main/java/jenkins/model/InterruptedBuildAction.java
Labels: ready-for-merge, skip-changelog

#5895 Clean up usages of `ClassLoaderReflectionToolkit`
  core/src/main/java/hudson/ClassicPluginStrategy.java
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/jenkins/ClassLoaderReflectionToolkit.java
Labels: ready-for-merge, skip-changelog

#5777 Remove unused image assets
  core/src/main/resources/lib/layout/breadcrumb.gif
  core/src/main/resources/lib/layout/html.jelly
  core/src/main/resources/lib/layout/layout.jelly
  core/src/main/resources/lib/layout/menu_down_arrow.png
  core/src/main/resources/lib/layout/menu_down_arrow2.png
  core/src/main/resources/lib/layout/menu_right_arrow.png
  core/src/main/resources/lib/layout/menu_right_arrow2.png
  core/src/main/resources/lib/layout/pageHeader.jelly
  war/src/main/less/base/style.less
  war/src/main/webapp/css/simple-page.theme.css
  war/src/main/webapp/images/atom-license.txt
  war/src/main/webapp/images/atom.gif
  war/src/main/webapp/images/bottom-sticker-top-edge.png
  war/src/main/webapp/images/headshot.png
  war/src/main/webapp/images/jenkins-header-logo-v2.svg
  war/src/main/webapp/images/jenkins-redbg.png
  war/src/main/webapp/images/jenkins.png
  war/src/main/webapp/images/jenkins.svg
  war/src/main/webapp/images/mask-icon.svg
  war/src/main/webapp/images/svgs/headless.svg
  war/src/main/webapp/images/title.xcf
  war/src/main/webapp/images/topbar.png
  war/src/main/webapp/images/topbar.svg
Labels: ready-for-merge, web-ui, rfe

#5858 Upgrade Guice from 4.0 to latest
  .github/dependabot.yml
  bom/pom.xml
  core/src/main/java/jenkins/ProxyInjector.java
Labels: ready-for-merge, squash-merge-me, dependencies, java

#5907 [JENKINS-67105] Upgrade to 2.320 gives "Failed to deserialize response" error
  core/src/main/resources/jenkins/security/whitelisted-classes.txt
  test/src/test/java/jenkins/security/Jenkins67105Test.java
Labels: regression-fix, ready-for-merge, squash-merge-me

#5911 Fix typo in Specific Build Discarder description
  core/src/main/resources/jenkins/model/SimpleGlobalBuildDiscarderStrategy/config.properties
Labels: skip-changelog, bug

#5882 [JENKINS-67099] Make trim labels more selective when we're operating on selected nodes
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/model/Nodes.java
Labels: ready-for-merge, rfe

#5908 Fix filtering in update tab of plugin manager
  core/src/main/resources/hudson/PluginManager/table.jelly
Labels: regression-fix, ready-for-merge, bug

#5906 [JENKINS-66969] Fix ongoing first build from disappearing from build history
  core/src/main/resources/hudson/widgets/HistoryWidget/index.jelly
  war/src/main/js/filter-build-history.js
  war/src/main/less/modules/side-panel-widgets.less
Labels: regression-fix, ready-for-merge

#5917 JENKINS-67109 Fix maven installations
  core/src/main/resources/lib/form/entry.jelly
Labels: regression-fix, ready-for-merge

#5920 Backporting for LTS 2.319.1
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/PluginFirstClassLoader.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/security/s2m/ConfigDirectory.java
  core/src/main/java/jenkins/util/AntClassLoader.java
  core/src/main/resources/hudson/widgets/HistoryWidget/entry.jelly
  core/src/main/resources/hudson/widgets/HistoryWidget/index.jelly
  war/src/main/js/filter-build-history.js
  war/src/main/less/modules/side-panel-widgets.less
Labels: into-lts

#5919 [JENKINS-67033] Missing icon in dashboard view
  core/src/main/java/jenkins/management/ConfigureLink.java
Labels: ready-for-merge, bug

#5924 split the index of javadoc
  pom.xml
Labels: ready-for-merge, skip-changelog, developer

#5930 Sprinkle some `@NonNull` annotations in `ListBoxModel`
  core/src/main/java/hudson/util/ListBoxModel.java
Labels: ready-for-merge, skip-changelog

#5936 Update at-since Javadoc up to 2.319
  core/src/main/java/hudson/PluginWrapper.java
  core/src/main/java/hudson/model/ExecutorListener.java
  core/src/main/java/hudson/model/Queue.java
  core/src/main/java/hudson/util/XStream2.java
  core/src/main/java/jenkins/security/s2m/MasterKillSwitchConfiguration.java
  core/src/main/java/jenkins/security/s2m/RunningBuildFilePathFilter.java
Labels: ready-for-merge, internal, skip-changelog

#5931 Register `UberClassLoader` as parallel-capable
  core/src/main/java/hudson/PluginManager.java
Labels: ready-for-merge, developer

#5944 Fix typo in autocomplete-debug.js
  war/src/main/webapp/scripts/yui/autocomplete/autocomplete-debug.js
Labels: skip-changelog

#5938 Update 2.TODO documentation
  core/src/main/java/hudson/model/User.java
  core/src/main/java/hudson/triggers/Trigger.java
  core/src/main/java/hudson/util/ChartUtil.java
  core/src/main/java/jenkins/ClassLoaderReflectionToolkit.java
  core/src/main/java/jenkins/tools/GlobalToolConfiguration.java
  core/src/main/java/jenkins/util/xstream/XStreamDOM.java
  core/src/main/resources/lib/form/combobox.jelly
  core/src/main/resources/lib/form/number.jelly
  core/src/main/resources/lib/form/select.jelly
  core/src/main/resources/lib/form/textarea.jelly
  core/src/main/resources/lib/form/textbox.jelly
Labels: skip-changelog

#5947 Bump ATH
  essentials.yml
Labels: skip-changelog

#5890 Record an informative stack trace & telemetry whenever `FilePath` agent-to-controller access is permitted
  core/src/main/java/jenkins/security/s2m/DefaultFilePathFilter.java
  core/src/main/java/jenkins/telemetry/impl/SlaveToMasterFileCallableUsage.java
  core/src/main/resources/jenkins/telemetry/impl/SlaveToMasterFileCallableUsage/description.jelly
  test/src/test/java/jenkins/security/s2m/AdminFilePathFilterTest.java
Labels: ready-for-merge, rfe

#5943 Update at-since Javadoc up to 2.319 (#5936)
  core/src/main/java/hudson/PluginWrapper.java
  core/src/main/java/hudson/model/ExecutorListener.java
  core/src/main/java/hudson/model/Queue.java
  core/src/main/java/hudson/util/XStream2.java
  core/src/main/java/jenkins/security/s2m/MasterKillSwitchConfiguration.java
  core/src/main/java/jenkins/security/s2m/RunningBuildFilePathFilter.java
  essentials.yml
Labels: internal, into-lts

#5934 Warn in `Queue.init` if items scheduled during startup will be clobbered
  core/src/main/java/hudson/model/Queue.java
Labels: ready-for-merge, skip-changelog

#5891 Supply a `SlaveComputer` context for both channels associated with a `maven-plugin` build
  core/src/main/java/hudson/slaves/Channels.java
  core/src/main/java/jenkins/security/ChannelConfigurator.java
Labels: ready-for-merge, skip-changelog

#5932 [JENKINS-67188] Deadlock loading `TaskListener` vs. `StreamTaskListener`
  core/src/main/java/hudson/model/NullTaskListener.java
  core/src/main/java/hudson/model/TaskListener.java
Labels: ready-for-merge, bug

#5940 Include `symbol-annotation` in core BOM
  bom/pom.xml
  core/pom.xml
  test/pom.xml
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5958 [JENKINS-67033] Missing icon in dashboard view (#5919)
  core/src/main/java/jenkins/management/ConfigureLink.java
Labels: bug, into-lts

#5959 [JENKINS-67188] Deadlock loading `TaskListener` vs. `StreamTaskListener` (#5932)
  core/src/main/java/hudson/model/NullTaskListener.java
  core/src/main/java/hudson/model/TaskListener.java
Labels: bug, into-lts

#5926 Inline form element path
  core/src/main/java/jenkins/formelementpath/FormElementPathPageDecorator.java
  core/src/main/resources/jenkins/formelementpath/FormElementPathPageDecorator/footer.jelly
  core/src/main/resources/jenkins/formelementpath/form-element-path.js
  core/src/main/resources/lib/form/repeatable/repeatable.js
Labels: ready-for-merge, rfe, developer

#4538 JENKINS-61278 JCasC support for managing log recorders
  core/src/main/java/hudson/logging/LogRecorder.java
  core/src/main/java/hudson/logging/LogRecorderManager.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/resources/hudson/logging/LogRecorder/configure.jelly
  core/src/main/resources/hudson/logging/LogRecorderManager/index.jelly
  core/src/test/java/hudson/logging/LogRecorderTest.java
  test/src/test/java/hudson/logging/LogRecorderManagerTest.java
Labels: ready-for-merge, rfe, squash-merge-me

#5946 [JENKINS-67193] "View as plain text" from polling log is behind top bar
  core/src/main/resources/lib/layout/rightspace.jelly
Labels: ready-for-merge, bug

#5942 `Stream`/`Spliterator` support for `RunList`
  core/src/main/java/hudson/model/AbstractProject.java
  core/src/main/java/hudson/util/RunList.java
  core/src/main/java/jenkins/model/lazy/AbstractLazyLoadRunMap.java
  core/src/main/java/jenkins/model/lazy/LazyLoadRunMapEntrySet.java
  test/src/test/java/hudson/model/RunMapTest.java
Labels: ready-for-merge, squash-merge-me, developer

#5909 [JEP-234] Customizable header proposal
  core/src/main/java/jenkins/views/FullHeader.java
  core/src/main/java/jenkins/views/Header.java
  core/src/main/java/jenkins/views/JenkinsHeader.java
  core/src/main/java/jenkins/views/PartialHeader.java
  core/src/main/resources/jenkins/views/JenkinsHeader/headerContent.jelly
  core/src/main/resources/lib/layout/pageHeader.jelly
Labels: needs-more-reviews, ready-for-merge, rfe, squash-merge-me, developer

#5955 [JENKINS-67225] replace "default value" with "Set by Default"
  core/src/main/resources/hudson/model/BooleanParameterDefinition/config.jelly
  core/src/main/resources/hudson/model/BooleanParameterDefinition/config_da.properties
  core/src/main/resources/hudson/model/BooleanParameterDefinition/config_de.properties
  core/src/main/resources/hudson/model/BooleanParameterDefinition/config_es.properties
  core/src/main/resources/hudson/model/BooleanParameterDefinition/config_fr.properties
  core/src/main/resources/hudson/model/BooleanParameterDefinition/config_it.properties
  core/src/main/resources/hudson/model/BooleanParameterDefinition/config_ja.properties
  core/src/main/resources/hudson/model/BooleanParameterDefinition/config_pl.properties
  core/src/main/resources/hudson/model/BooleanParameterDefinition/config_pt_BR.properties
  core/src/main/resources/hudson/model/BooleanParameterDefinition/config_ru.properties
  core/src/main/resources/hudson/model/BooleanParameterDefinition/config_sr.properties
  core/src/main/resources/hudson/model/BooleanParameterDefinition/config_zh_TW.properties
Labels: ready-for-merge, web-ui

#5957 [JENKINS-67226] Deduplicate RPCRequest oids and proxy objects
  core/src/main/java/jenkins/telemetry/impl/SlaveToMasterFileCallableUsage.java
  core/src/test/java/jenkins/telemetry/impl/SlaveToMasterFileCallableUsageTest.java
Labels: ready-for-merge, skip-changelog

#5963 Enable `DefaultComesLast` Checkstyle check
  core/src/main/java/hudson/util/LineEndingConversion.java
  pom.xml
Labels: skip-changelog

#5956 [JENKINS-67229] Backport agent-to-controller file access telemetry
  core/src/main/java/jenkins/security/s2m/DefaultFilePathFilter.java
  core/src/main/java/jenkins/telemetry/impl/SlaveToMasterFileCallableUsage.java
  core/src/main/resources/jenkins/telemetry/impl/SlaveToMasterFileCallableUsage/description.jelly
  test/src/test/java/jenkins/security/s2m/AdminFilePathFilterTest.java
Labels: into-lts

#5967 Enable `MissingDeprecated` Checkstyle check
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/PluginWrapper.java
  core/src/main/java/hudson/model/ListView.java
  core/src/main/java/hudson/model/Slave.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/java/hudson/model/User.java
  core/src/main/java/hudson/model/queue/Tasks.java
  core/src/main/java/hudson/slaves/JNLPLauncher.java
  core/src/main/java/hudson/util/RingBufferLogHandler.java
  core/src/main/java/jenkins/ClassLoaderReflectionToolkit.java
  core/src/main/java/jenkins/install/InstallState.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/security/ApiTokenProperty.java
  core/src/main/java/jenkins/slaves/JnlpSlaveAgentProtocol.java
  core/src/main/java/jenkins/triggers/ReverseBuildTrigger.java
  pom.xml
  test/src/test/java/hudson/cli/DisablePluginCommandTest.java
  test/src/test/java/hudson/diagnosis/OldDataMonitorTest.java
Labels: ready-for-merge, skip-changelog

#5983 [JENKINS-67227] Integrate remoting 4.11.2
  pom.xml
Labels: ready-for-merge, bug

#5975 Removed LargeText which was moved a long time ago to stapler
  core/src/main/java/hudson/model/LargeText.java
Labels: ready-for-merge, skip-changelog

#5960 Remove `sorcerer`
  pom.xml
Labels: ready-for-merge, skip-changelog

#5771 Replaced deprecated CaseInsensitiveComparator with java built in
  test/src/test/resources/hudson/cli/testview-foo.xml
  test/src/test/resources/hudson/cli/view.xml
  test/src/test/resources/hudson/model/ListViewTest/migrateStatusFilter/config.xml
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5984 [JENKINS-67227] Integrate remoting 4.11.2
  pom.xml
Labels: into-lts

#5964 Enable `PackageDeclaration` Checkstyle check
  pom.xml
  test/src/test/java/jenkins/CoreJellyTest.java
  test/src/test/java/jenkins/CorePropertiesTest.java
Labels: skip-changelog

#5969 Enable `LineLength` Checkstyle check
  core/src/main/java/hudson/model/UsageStatistics.java
  core/src/main/java/jenkins/slaves/JnlpAgentReceiver.java
  core/src/main/java/jenkins/views/PartialHeader.java
  core/src/test/java/hudson/slaves/ComputerLauncherTest.java
  core/src/test/java/hudson/util/ArgumentListBuilderTest.java
  core/src/test/java/jenkins/model/RunIdMigratorTest.java
  pom.xml
  test/src/test/java/hudson/console/AnnotatedLargeTextTest.java
  test/src/test/java/hudson/model/ApiTest.java
  test/src/test/java/hudson/model/UsageStatisticsTest.java
  test/src/test/java/hudson/security/WhoAmITest.java
  test/src/test/java/jenkins/install/SetupWizardTest.java
Labels: skip-changelog, squash-merge-me

#5961 Enable `ArrayTrailingComma` Checkstyle check
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/TcpSlaveAgentListener.java
  core/src/main/java/hudson/scheduler/CronTab.java
  core/src/main/java/hudson/slaves/NodeProvisioner.java
  core/src/main/java/jenkins/security/stapler/StaplerFilteredActionListener.java
  core/src/test/java/hudson/UtilTest.java
  pom.xml
  test/src/test/java/hudson/security/csrf/DefaultCrumbIssuerTest.java
  test/src/test/java/hudson/tasks/FingerprinterTest.java
  test/src/test/java/hudson/util/ArgumentListBuilder2Test.java
  test/src/test/java/jenkins/model/JenkinsTest.java
  test/src/test/java/jenkins/security/stapler/GetterMethodFilterTest.java
Labels: skip-changelog

#5966 Enable `MissingSwitchDefault` Checkstyle check
  cli/src/main/java/hudson/util/QuotedStringTokenizer.java
  core/src/main/java/hudson/cli/ListChangesCommand.java
  core/src/main/java/hudson/console/ConsoleAnnotator.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/util/jna/RegistryKey.java
  core/src/main/java/jenkins/tasks/filters/impl/RetainVariablesLocalRule.java
  core/src/main/java/jenkins/util/JSONSignatureValidator.java
  core/src/main/java/org/jenkins/ui/icon/IconType.java
  pom.xml
Labels: skip-changelog

#5423 Deprecate FingerprintStorage#getFileFingerprintStorage
  core/src/main/java/hudson/model/Fingerprint.java
  core/src/main/java/hudson/model/FingerprintCleanupThread.java
  core/src/main/java/jenkins/fingerprints/FingerprintStorage.java
  test/src/test/java/jenkins/fingerprints/FingerprintStorageTest.java
Labels: ready-for-merge, squash-merge-me, developer

#5738 Fix `UnusedException` Error Prone violations
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/WebAppMain.java
  core/src/main/java/hudson/cli/ConsoleCommand.java
  core/src/main/java/hudson/cli/DisablePluginCommand.java
  core/src/main/java/hudson/model/AbstractProject.java
  core/src/main/java/hudson/model/Descriptor.java
  core/src/main/java/hudson/model/Fingerprint.java
  core/src/main/java/hudson/model/Job.java
  core/src/main/java/hudson/model/ResourceController.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/slaves/ComputerLauncher.java
  core/src/main/java/hudson/util/ChunkedInputStream.java
  core/src/main/java/hudson/util/ReflectionUtils.java
  core/src/main/java/jenkins/install/InstallUtil.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/mvn/FilePathGlobalSettingsProvider.java
  core/src/main/java/jenkins/mvn/FilePathSettingsProvider.java
  core/src/main/java/jenkins/mvn/SettingsPathHelper.java
  core/src/main/java/jenkins/security/apitoken/ApiTokenStore.java
  core/src/main/java/jenkins/util/TimeDuration.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5965 Enable `SuperClone` Checkstyle check
  core/src/main/java/hudson/util/ArgumentListBuilder.java
  pom.xml
Labels: ready-for-merge, skip-changelog

#5978 Remove `JNADoublyLoaded`
  core/src/main/java/hudson/WebAppMain.java
  core/src/main/java/hudson/util/JNADoublyLoaded.java
  core/src/main/resources/hudson/util/JNADoublyLoaded/index.jelly
  core/src/main/resources/hudson/util/JNADoublyLoaded/index.properties
  core/src/main/resources/hudson/util/JNADoublyLoaded/index_bg.properties
  core/src/main/resources/hudson/util/JNADoublyLoaded/index_da.properties
  core/src/main/resources/hudson/util/JNADoublyLoaded/index_de.properties
  core/src/main/resources/hudson/util/JNADoublyLoaded/index_es.properties
  core/src/main/resources/hudson/util/JNADoublyLoaded/index_it.properties
  core/src/main/resources/hudson/util/JNADoublyLoaded/index_ja.properties
  core/src/main/resources/hudson/util/JNADoublyLoaded/index_pt_BR.properties
  core/src/main/resources/hudson/util/JNADoublyLoaded/index_sr.properties
  core/src/main/resources/hudson/util/JNADoublyLoaded/index_zh_TW.properties
Labels: ready-for-merge, removed

#5988 Move Ant tests from core
  test/src/test/java/hudson/tasks/EnvVarsInConfigTasksTest.java
  test/src/test/java/hudson/tools/ToolLocationNodePropertyTest.java
Labels: ready-for-merge, skip-changelog
