Repository jenkinsci/jenkins, pull requests merged in 2021-01, with the labels that each got.

#5082 [JENKINS-58101] Cache blockage reasons when considering parked executors
  core/src/main/java/hudson/model/Queue.java
Labels: ready-for-merge, rfe

#5149 Update parent pom to 1.62
  pom.xml
Labels: ready-for-merge, skip-changelog

#5147 Minor spotbugs issues
  core/src/test/java/hudson/util/ConsistentHashTest.java
  core/src/test/java/hudson/util/SecretTest.java
  core/src/test/java/jenkins/util/xstream/XStreamDOMTest.java
Labels: ready-for-merge, skip-changelog

#5146 Replaced deprecated IOUtils.LINE_SEPARATOR with System.lineSeparator()
  core/src/main/java/hudson/Functions.java
  core/src/test/java/hudson/FunctionsTest.java
Labels: ready-for-merge, skip-changelog

#5145 [JENKINS-64439] "positive-number" field validator accepts non valid java numbers
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: bug, ready-for-merge

#5110 [JENKINS-64423, JENKINS-46618] Resolve all core caused startup Illegal reflective access warnings
  core/src/main/java/hudson/ExtensionFinder.java
  core/src/main/java/hudson/PluginFirstClassLoader.java
  core/src/main/java/jenkins/ClassLoaderReflectionToolkit.java
  core/src/main/java/jenkins/model/AssetManager.java
  core/src/main/java/jenkins/util/AntClassLoader.java
  core/src/main/java/jenkins/util/AntWithFindResourceClassLoader.java
Labels: ready-for-merge, skip-changelog

#5153 Add system property to override inbound TCP agent address
  core/src/main/java/hudson/slaves/JNLPLauncher.java
  core/src/main/resources/hudson/slaves/SlaveComputer/jenkins-agent.jnlp.jelly
  test/pom.xml
  test/src/test/java/hudson/slaves/AgentInboundUrlTest.java
Labels: ready-for-merge, rfe

#5148 Added small part with tips for IntelliJ settings to the Contrubuting.md
  CONTRIBUTING.md
Labels: skip-changelog

#5161 Ignore guava in dependabot
  .github/dependabot.yml
Labels: skip-changelog

#5156 EOL dependency on Maven Integration
  test/pom.xml
  test/src/test/java/hudson/CustomPluginManagerTest.java
  test/src/test/java/hudson/PluginManagerTest.java
  test/src/test/java/hudson/bugs/seasar/Operation2174Test.java
  test/src/test/java/hudson/cli/ListJobsCommandTest.java
  test/src/test/java/hudson/model/GetEnvironmentOutsideBuildTest.java
  test/src/test/java/hudson/model/HelpLinkTest.java
  test/src/test/java/hudson/model/JobPropertyTest.java
  test/src/test/java/hudson/model/NodeTest.java
  test/src/test/java/hudson/model/UpdateSiteTest.java
  test/src/test/java/hudson/tasks/BuildTriggerTest.java
  test/src/test/java/hudson/tasks/EnvVarsInConfigTasksTest.java
  test/src/test/java/hudson/tools/ToolLocationNodePropertyTest.java
  test/src/test/java/hudson/util/FormFieldValidatorTest.java
  test/src/test/java/jenkins/model/JenkinsBuildsAndWorkspacesDirectoriesTest.java
  test/src/test/java/jenkins/slaves/OldRemotingAgentTest.java
  test/src/test/java/jenkins/tasks/SimpleBuildWrapperTest.java
  test/src/test/java/lib/hudson/ListScmBrowsersTest.java
  test/src/test/resources/hudson/model/UsageStatisticsTest/jobs.json
  test/src/test/resources/plugins/htmlpublisher-update-center.json
  test/src/test/resources/plugins/tasks.jpi
Labels: internal, ready-for-merge, skip-changelog

#5168 Factor out XMLUnit version into property
  core/pom.xml
Labels: ready-for-merge, skip-changelog

#5178 Ignore security test that fails in CI
  core/src/test/java/jenkins/util/VirtualFileTest.java
Labels: skip-changelog

#5169 Remove unused script-security dependency
  test/pom.xml
Labels: ready-for-merge, skip-changelog

#5170 Fixed some deprecated warnings of mockito methods and minor cleanup
  core/src/test/java/hudson/cli/handlers/ViewOptionHandlerTest.java
  core/src/test/java/hudson/slaves/ChannelPingerTest.java
  core/src/test/java/jenkins/model/CoreEnvironmentContributorTest.java
  test/src/test/java/hudson/model/ComputerConfigDotXmlTest.java
  test/src/test/java/hudson/util/XStream2Security383Test.java
Labels: ready-for-merge, skip-changelog

#5183 Ignore old servlet api in dependabot
  .github/dependabot.yml
Labels: skip-changelog

#5182 Fix tests on newer java versions
  core/src/test/java/hudson/FunctionsTest.java
  core/src/test/java/jenkins/plugins/DetachedPluginsUtilTest.java
Labels: ready-for-merge, skip-changelog

#5154 Log if no class paths was found for plugin
  core/src/main/java/hudson/ClassicPluginStrategy.java
Labels: ready-for-merge, skip-changelog

#5021 [JENKINS-28022] Make descriptions copy-able without zero-width spaces
  war/src/main/less/base/style.less
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, rfe, web-ui

#5185 Bump Mailer from 1.23 to 1.32.1
  test/pom.xml
Labels: dependencies, ready-for-merge, skip-changelog

#5187 [JENKINS-64621] Fix zip regression
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/model/DirectoryBrowserSupport.java
  core/src/main/java/hudson/util/io/ArchiverFactory.java
  core/src/main/java/hudson/util/io/ZipArchiver.java
  core/src/main/java/jenkins/util/VirtualFile.java
  core/src/test/java/jenkins/util/VirtualFileTest.java
  test/src/test/java/hudson/model/DirectoryBrowserSupportTest.java
Labels: regression-fix

#5188 [JENKINS-64632] File handle leak correction
  core/src/main/java/hudson/model/DirectoryBrowserSupport.java
Labels: regression-fix

#5191 [JENKINS-64655] Provide default implementation for external storage
  core/src/main/java/jenkins/util/VirtualFile.java
Labels: regression-fix

#5196 List the ATH 1.80 SHA1 in the athRevision
  essentials.yml
Labels: skip-changelog

#5193 LTS backport SECURITY-1452 regression fixes
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/model/DirectoryBrowserSupport.java
  core/src/main/java/hudson/util/io/ArchiverFactory.java
  core/src/main/java/hudson/util/io/ZipArchiver.java
  core/src/main/java/jenkins/util/VirtualFile.java
  core/src/test/java/jenkins/util/VirtualFileTest.java
  essentials.yml
  test/src/test/java/hudson/model/DirectoryBrowserSupportTest.java
Labels: into-lts

#5189 Bump JUnit plugin from 1.29 to 1.48
  test/pom.xml
Labels: ready-for-merge, skip-changelog

#5177 [JENKINS-64291] Fix drag & drop issues replacing the drag & drop library
  core/src/main/resources/lib/form/dragdrop/dragdrop.js
  core/src/main/resources/lib/form/hetero-list/hetero-list.js
  core/src/main/resources/lib/form/repeatable/repeatable.js
  core/src/main/resources/lib/layout/layout.jelly
  war/package.json
  war/src/main/js/sortable-drag-drop.js
  war/src/main/js/util/page.js
  war/src/main/js/widgets/config/tabbar.js
  war/src/main/js/widgets/config/tabbar.less
  war/src/main/less/base/style.less
  war/webpack.config.js
  war/yarn.lock
Labels: ready-for-merge, web-ui

#5190 [JENKINS-64670] Improve performance in file fingerprint creation
  core/src/main/java/jenkins/fingerprints/FileFingerprintStorage.java
Labels: ready-for-merge, rfe, squash-merge-me

#5199 Ignore dependabot for jakarta.servlet.jsp.jstl
  .github/dependabot.yml
Labels: skip-changelog

#5202 Ignore dependabot updates for jfreechart and jansi
  .github/dependabot.yml
Labels: skip-changelog

#5195 [JENKINS-64429] Fix registerValidator breaking error messages
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: bug, ready-for-merge

#5198 Improve performance when saving Fingerprints to disk
  core/src/main/java/jenkins/fingerprints/FileFingerprintStorage.java
Labels: ready-for-merge, rfe

#5176 Improvements to the accessibility and color palette for job config and new item forms
  war/src/main/js/widgets/add/addform.less
  war/src/main/js/widgets/config/tabbar.less
Labels: ready-for-merge, rfe, web-ui

#5207 Rename API endpoint to avoid URL collisions
  core/src/main/java/jenkins/management/AdministrativeMonitorsApi.java
  core/src/main/resources/jenkins/management/AdministrativeMonitorsDecorator/footer.jelly
Labels: ready-for-merge, skip-changelog

#5205 Minor cleanups to Fingerprint writing codepaths
  core/src/main/java/hudson/model/Fingerprint.java
  core/src/main/java/hudson/util/AtomicFileWriter.java
  core/src/main/java/hudson/util/FileChannelWriter.java
Labels: ready-for-merge, skip-changelog

#5215 Backporting for LTS 2.263.4
  core/src/main/java/jenkins/fingerprints/FileFingerprintStorage.java
  core/src/main/resources/hudson/model/AllView/noJob.groovy
  core/src/main/resources/hudson/model/AllView/noJob.properties
  war/src/main/js/widgets/config/tabbar.less
Labels: into-lts

#5217 Ignore guice in dependabot
  .github/dependabot.yml
Labels: skip-changelog

#5226 Dependabot: Ignore Servlet API
  .github/dependabot.yml
Labels: skip-changelog
