Repository jenkinsci/jenkins, pull requests merged in 2021-09, with the labels that each got.

#5684 Fix typo in menu-debug.js
  war/src/main/webapp/scripts/yui/menu/menu-debug.js
Labels: ready-for-merge, skip-changelog

#5678 Added a few missing @NonNull annotations
  core/src/main/java/jenkins/scm/DefaultSCMCheckoutStrategyImpl.java
  core/src/main/java/jenkins/slaves/EncryptedSlaveAgentJnlpFile.java
  test/src/test/java/hudson/triggers/SCMTriggerTest.java
Labels: ready-for-merge, skip-changelog

#5680 Use try with resources where spotbugs suggests
  core/src/main/java/hudson/console/ConsoleNote.java
  core/src/main/java/hudson/os/SU.java
  core/src/main/java/jenkins/slaves/DefaultJnlpSlaveReceiver.java
Labels: ready-for-merge, skip-changelog

#5694 Fix agent-to-controller security killswitch UI
  core/src/main/java/jenkins/security/s2m/MasterKillSwitchConfiguration.java
Labels: regression-fix, ready-for-merge, bug

#5686 Clean up `PluginFirstClassLoader` and `PluginManager`
  core/src/main/java/hudson/PluginFirstClassLoader.java
  core/src/main/java/hudson/PluginManager.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5701 Replace some anonymous classes with lambdas
  core/src/main/java/hudson/BulkChange.java
  core/src/main/java/hudson/ClassicPluginStrategy.java
  core/src/main/java/hudson/ExtensionFinder.java
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/model/AbstractProject.java
  core/src/main/java/hudson/model/BooleanParameterValue.java
  core/src/main/java/hudson/model/DependencyGraph.java
  core/src/main/java/hudson/model/FileParameterValue.java
  core/src/main/java/hudson/model/ItemGroupMixIn.java
  core/src/main/java/hudson/model/PasswordParameterValue.java
  core/src/main/java/hudson/model/RunMap.java
  core/src/main/java/hudson/model/Saveable.java
  core/src/main/java/hudson/model/StringParameterValue.java
  core/src/main/java/hudson/model/View.java
  core/src/main/java/hudson/model/queue/QueueSorter.java
  core/src/main/java/hudson/security/Permission.java
  core/src/main/java/hudson/util/FileVisitor.java
  core/src/main/java/hudson/util/TableNestChecker.java
  core/src/main/java/hudson/util/VariableResolver.java
  core/src/main/java/hudson/views/MyViewsTabBar.java
  core/src/main/java/hudson/views/ViewsTabBar.java
  core/src/main/java/jenkins/model/Nodes.java
  core/src/main/java/jenkins/security/s2m/ConfigDirectory.java
  core/src/main/java/jenkins/security/s2m/FilePathRuleConfig.java
  core/src/main/java/jenkins/security/s2m/OpMatcher.java
  core/src/main/java/jenkins/util/groovy/GroovyHookScript.java
  test/src/test/java/hudson/cli/AddJobToViewCommandTest.java
  test/src/test/java/hudson/cli/CreateViewCommandTest.java
  test/src/test/java/hudson/cli/DeleteViewCommandTest.java
  test/src/test/java/hudson/cli/RemoveJobFromViewCommandTest.java
  test/src/test/java/hudson/cli/UpdateViewCommandTest.java
  test/src/test/java/hudson/cli/ViewManipulationTestBase.java
Labels: ready-for-merge, skip-changelog

#5697 Graphs now scale correctly for high-DPI screens
  core/src/main/java/hudson/util/Graph.java
  core/src/main/resources/hudson/model/LoadStatistics/main.jelly
  core/src/main/resources/hudson/model/LoadStatistics/resources.js
  core/src/main/resources/jenkins/model/Jenkins/systemInfo.jelly
Labels: ready-for-merge, web-ui, rfe

#5699 [JENKINS-23784] - Register `DependencyClassLoader` in the default plugin strategy as parallel-capable
  core/src/main/java/hudson/ClassicPluginStrategy.java
Labels: ready-for-merge, rfe, squash-merge-me

#5704 Fix bug in TextparameterDefinition
  core/src/main/java/hudson/model/TextParameterDefinition.java
Labels: ready-for-merge, bug

#5689 Bump `json-lib` from 2.4-jenkins-2 to 2.4-jenkins-3
  bom/pom.xml
Labels: ready-for-merge, skip-changelog, dependencies

#5712 Work around jnr/jnr-ffi#269
  core/pom.xml
Labels: ready-for-merge, skip-changelog

#5698 Revive support for `URLClassLoader` in `ClassicPluginStrategy`
  core/src/main/java/hudson/ClassicPluginStrategy.java
  core/src/main/java/jenkins/ClassLoaderReflectionToolkit.java
  core/src/main/java/jenkins/util/AntClassLoader.java
  core/src/main/java/jenkins/util/JenkinsClassLoader.java
  core/src/main/java/jenkins/util/URLClassLoader2.java
Labels: ready-for-merge, internal, squash-merge-me

#5708 Minor code cleanup
  core/src/main/java/hudson/Proc.java
  core/src/main/java/hudson/model/ParameterValue.java
  core/src/main/java/hudson/model/StringParameterValue.java
  core/src/main/java/hudson/slaves/ChannelPinger.java
  core/src/main/java/hudson/tasks/BuildTrigger.java
  core/src/main/java/jenkins/util/InterceptingExecutorService.java
  core/src/main/java/jenkins/util/TreeStringBuilder.java
  core/src/test/java/jenkins/util/TreeStringBuilderTest.java
  test/src/test/java/hudson/model/DependencyGraphTest.java
  test/src/test/java/hudson/model/ParametersAction2Test.java
  test/src/test/java/hudson/model/ProjectTest.java
  test/src/test/java/hudson/tasks/EnvVarsInConfigTasksTest.java
  test/src/test/java/jenkins/model/BuiltInNodeMigrationRestartTest.java
  test/src/test/java/lib/form/HeteroListTest.java
Labels: ready-for-merge, skip-changelog

#5713 Prevent Junit 4 tests from being skipped due to jupiter engine
  Jenkinsfile
  core/src/test/java/jenkins/Junit4TestsRanTest.java
  test/src/test/java/jenkins/Junit4TestsRanTest.java
Labels: ready-for-merge, skip-changelog

#5700 [JENKINS-65928] Job trend page shows previous icons
  core/src/main/java/jenkins/widgets/BuildTimeTrend.java
  core/src/main/resources/hudson/model/Job/buildTimeTrend_resources.js
Labels: ready-for-merge, web-ui, bug

#5724 Consistently use `issues.jenkins.io` for issue links
  CONTRIBUTING.md
  core/src/main/java/hudson/PluginWrapper.java
  core/src/main/java/hudson/Proc.java
  core/src/main/java/hudson/Util.java
  core/src/main/java/hudson/WebAppMain.java
  core/src/main/java/hudson/model/FileParameterValue.java
  core/src/main/java/hudson/model/Fingerprint.java
  core/src/main/java/hudson/model/Node.java
  core/src/main/java/hudson/model/ParametersAction.java
  core/src/main/java/hudson/model/Queue.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/model/User.java
  core/src/main/java/hudson/slaves/JNLPLauncher.java
  core/src/main/java/hudson/util/ArgumentListBuilder.java
  core/src/main/java/hudson/util/ClassLoaderSanityThreadFactory.java
  core/src/main/java/hudson/util/FileChannelWriter.java
  core/src/main/java/hudson/util/RingBufferLogHandler.java
  core/src/main/java/hudson/util/XStream2.java
  core/src/main/java/jenkins/fingerprints/FileFingerprintStorage.java
  core/src/main/java/jenkins/model/item_category/ItemCategory.java
  core/src/main/resources/jenkins/security/whitelisted-classes.txt
  docs/MAINTAINERS.adoc
  pom.xml
  war/src/main/webapp/WEB-INF/ibm-web-bnd.xmi
  war/src/main/webapp/WEB-INF/sun-web.xml
  war/src/main/webapp/scripts/yui/button/button-debug.js
Labels: ready-for-merge, skip-changelog

#5716 [JENKINS-61212] Update Tyrus (WebSocket client) to 2.0.1
  cli/pom.xml
Labels: ready-for-merge, dependencies, java

#5721 Bump jnr-posix + exclusion removal
  bom/pom.xml
  core/pom.xml
Labels: ready-for-merge, skip-changelog, dependencies, java

#5711 [JENKINS-66563] add a supported API for a plugin to insert jars into its classpath
  core/src/main/java/hudson/PluginWrapper.java
  core/src/test/java/hudson/PluginWrapperTest.java
Labels: ready-for-merge, squash-merge-me, developer

#5723 [JENKINS-66470] Register view-related permission groups and permissions prior to the execution of JCasC
  core/src/main/java/hudson/model/View.java
Labels: regression-fix, ready-for-merge, squash-merge-me

#5731 Adding `@deprecated` messages for `Fingerprinter.recordBuildArtifacts`
  core/src/main/java/hudson/tasks/Fingerprinter.java
Labels: skip-changelog

#5728 tidy up clicommand javadoc
  core/src/main/java/hudson/cli/CLICommand.java
Labels: ready-for-merge, skip-changelog

#5561 Remove Akuma
  bom/pom.xml
  core/pom.xml
  core/src/main/java/hudson/lifecycle/UnixLifecycle.java
  core/src/main/java/jenkins/diagnosis/HsErrPidList.java
  core/src/main/java/jenkins/slaves/restarter/UnixSlaveRestarter.java
  core/src/main/java/jenkins/util/JavaVMArguments.java
Labels: ready-for-merge, internal, squash-merge-me, dependencies

#5734 Prefer `assertThrows` to try/fail
  core/src/test/java/jenkins/model/lazy/AbstractLazyLoadRunMapTest.java
  test/src/test/java/hudson/AbstractItemSecurity1114Test.java
  test/src/test/java/hudson/FilePathTest.java
  test/src/test/java/hudson/PluginManagerTest.java
  test/src/test/java/hudson/model/AbstractItemTest.java
  test/src/test/java/hudson/model/AbstractProjectTest.java
  test/src/test/java/hudson/model/BuildAuthorizationTokenTest.java
  test/src/test/java/hudson/model/ComputerConfigDotXmlTest.java
  test/src/test/java/hudson/model/ComputerTest.java
  test/src/test/java/hudson/model/DescriptorTest.java
  test/src/test/java/hudson/model/FreeStyleProjectTest.java
  test/src/test/java/hudson/model/ItemGroupMixInTest.java
  test/src/test/java/hudson/model/ListViewTest.java
  test/src/test/java/hudson/model/ProjectTest.java
  test/src/test/java/hudson/model/UserTest.java
  test/src/test/java/hudson/model/ViewTest.java
  test/src/test/java/hudson/model/labels/LabelAtomSecurity1986Test.java
  test/src/test/java/hudson/security/ACLTest.java
  test/src/test/java/hudson/security/AccessDeniedException3Test.java
  test/src/test/java/hudson/security/SecurityRealmSecurity2371Test.java
  test/src/test/java/hudson/slaves/NodeCanTakeTaskTest.java
  test/src/test/java/hudson/slaves/PingThreadTest.java
  test/src/test/java/hudson/util/ProcessTreeTest.java
  test/src/test/java/jenkins/model/JenkinsBuildsAndWorkspacesDirectoriesTest.java
  test/src/test/java/jenkins/model/JenkinsTest.java
  test/src/test/java/jenkins/model/NodesTest.java
  test/src/test/java/jenkins/security/s2m/DefaultFilePathFilterTest.java
  test/src/test/java/jenkins/security/seed/UserSeedPropertyTest.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5717 Remove redundant 'continue' from conditional branches
  cli/src/main/java/hudson/util/QuotedStringTokenizer.java
Labels: ready-for-merge, skip-changelog

#5737 Fix `UnnecessarilyFullyQualified` Error Prone violations
  core/src/main/java/hudson/Util.java
  core/src/main/java/hudson/WebAppMain.java
  core/src/main/java/hudson/cli/GroovyshCommand.java
  core/src/main/java/hudson/model/AbstractProject.java
  core/src/main/java/hudson/model/Executor.java
  core/src/main/java/hudson/security/SecurityRealm.java
  core/src/main/java/hudson/tasks/ArtifactArchiver.java
  core/src/main/java/hudson/triggers/Trigger.java
  core/src/main/java/hudson/util/DOSToUnixPathHelper.java
  core/src/main/java/hudson/util/DirScanner.java
  core/src/main/java/hudson/util/NoOverlapCategoryAxis.java
  core/src/main/java/hudson/util/ProcessTree.java
  core/src/main/java/hudson/util/RobustReflectionConverter.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/model/ParameterizedJobMixIn.java
  core/src/main/java/jenkins/plugins/DetachedPluginsUtil.java
  core/src/main/java/jenkins/security/ConfidentialStore.java
  core/src/main/java/jenkins/slaves/StandardOutputSwapper.java
  core/src/main/java/jenkins/triggers/SCMTriggerItem.java
  core/src/test/java/hudson/PluginWrapperTest.java
  core/src/test/java/jenkins/triggers/SCMTriggerItemTest.java
  test/src/test/java/hudson/bugs/JnlpAccessWithSecuredHudsonTest.java
  test/src/test/java/hudson/cli/CLIActionTest.java
  test/src/test/java/hudson/model/DownloadServiceTest.java
  test/src/test/java/hudson/model/TimeZonePropertyTest.java
  test/src/test/java/hudson/model/queue/MaintainCanTakeStrengtheningTest.java
  test/src/test/java/hudson/security/HudsonPrivateSecurityRealmTest.java
  test/src/test/java/hudson/slaves/AgentInboundUrlTest.java
  test/src/test/java/hudson/slaves/JNLPLauncherTest.java
  test/src/test/java/jenkins/security/stapler/GetterMethodFilterTest.java
Labels: skip-changelog

#5729 Towards 2.303.2
  bom/pom.xml
  core/src/main/java/hudson/model/TextParameterDefinition.java
  core/src/main/java/hudson/model/View.java
  core/src/test/java/hudson/util/RobustReflectionConverterTest.java
  war/pom.xml
Labels: into-lts

#5741 Change freenode to libera
  docs/MAINTAINERS.adoc
Labels: skip-changelog

#5733 Introduce `Queue.Executable.getParentExecutable`
  core/src/main/java/hudson/model/Queue.java
Labels: ready-for-merge, skip-changelog

#5715 Attempt to fix SlaveComputerTest.startupShouldFailOnErrorOnlineListener
  test/src/test/java/hudson/slaves/SlaveComputerTest.java
Labels: internal, skip-changelog

#5693 Modernise Manage Jenkins screen
  core/src/main/resources/jenkins/model/Jenkins/manage.jelly
  test/src/test/java/hudson/model/ManagementLinkTest.java
  war/src/main/less/base-styles-v2.less
  war/src/main/less/base/layout-commons.less
  war/src/main/less/modules/app-bar.less
  war/src/main/less/modules/manage-jenkins.less
  war/src/main/less/modules/section.less
Labels: ready-for-merge, web-ui, rfe, squash-merge-me

#5739 JENKINS-66659 Show new icons in build history
  core/src/main/java/jenkins/widgets/BuildListTable.java
  core/src/main/java/jenkins/widgets/BuildTimeTrend.java
  core/src/main/resources/hudson/model/Job/buildTimeTrend_resources.js
  core/src/main/resources/lib/hudson/buildListTable.jelly
Labels: ready-for-merge, web-ui, rfe

#5736 💣 Remove powermock
  core/pom.xml
  core/src/main/java/jenkins/security/ClassFilterImpl.java
  core/src/test/java/hudson/FilePathTest.java
  core/src/test/java/hudson/FunctionsTest.java
  core/src/test/java/hudson/cli/ListJobsCommandTest.java
  core/src/test/java/hudson/cli/handlers/ViewOptionHandlerTest.java
  core/src/test/java/hudson/logging/LogRecorderTest.java
  core/src/test/java/hudson/model/JobTest.java
  core/src/test/java/hudson/model/ParametersActionTest.java
  core/src/test/java/hudson/model/RunTest.java
  core/src/test/java/hudson/model/StubJob.java
  core/src/test/java/hudson/model/ViewTest.java
  core/src/test/java/hudson/slaves/ChannelPingerTest.java
  core/src/test/java/hudson/slaves/DelegatingComputerLauncherTest.java
  core/src/test/java/hudson/util/RunListTest.java
  core/src/test/java/jenkins/model/CoreEnvironmentContributorTest.java
  core/src/test/java/jenkins/model/JDKNameTest.java
  core/src/test/java/jenkins/model/JenkinsGetRootUrlTest.java
  core/src/test/java/jenkins/model/JenkinsLocationConfigurationTest.java
  core/src/test/java/jenkins/security/apitoken/ApiTokenStatsTest.java
  core/src/test/java/jenkins/triggers/SCMTriggerItemTest.java
  pom.xml
  test/pom.xml
  test/src/test/java/hudson/model/queue/LoadPredictorTest.java
  test/src/test/java/jenkins/install/InstallUtilTest.java
Labels: ready-for-merge, skip-changelog

#5749 Removed unused `show-pom-version.rb`
  Dockerfile
  show-pom-version.rb
Labels: ready-for-merge, skip-changelog

#5750 Exclude two generated classes from spotbugs
  src/findbugs/findbugs-excludes.xml
Labels: ready-for-merge, skip-changelog

#5751 Refactored `InitializeSVGS()` to fix Spotbugs error `WMI_WRONG_MAP_ITERATOR` and added test
  core/src/main/java/org/jenkins/ui/icon/IconSet.java
  core/src/test/java/org/jenkins/ui/icon/IconSetTest.java
Labels: ready-for-merge, skip-changelog

#5679 Minor spotbugs fixes in respect to null checks
  core/src/main/java/hudson/model/TaskListener.java
  core/src/main/java/hudson/slaves/JNLPLauncher.java
  core/src/main/java/hudson/tasks/Maven.java
  core/src/main/java/jenkins/model/Jenkins.java
Labels: ready-for-merge

#5692 Revamp build history search bar
  core/src/main/java/org/jenkins/ui/icon/IconSet.java
  core/src/main/resources/hudson/logging/LogRecorderManager/feeds.jelly
  core/src/main/resources/hudson/widgets/HistoryWidget/entry.jelly
  core/src/main/resources/hudson/widgets/HistoryWidget/index.jelly
  core/src/main/resources/hudson/widgets/HistoryWidget/index.properties
  core/src/main/resources/lib/hudson/editableDescription.jelly
  core/src/main/resources/lib/hudson/rssBar.jelly
  war/src/main/js/filter-build-history.js
  war/src/main/less/abstracts/theme.less
  war/src/main/less/base-styles-v2.less
  war/src/main/less/base/style.less
  war/src/main/less/modules/form.less
  war/src/main/less/modules/side-panel-widgets.less
  war/src/main/webapp/images/16x16/find.png
  war/src/main/webapp/images/16x16/go_down.png
  war/src/main/webapp/images/16x16/go_top.png
  war/src/main/webapp/images/16x16/go_up.png
  war/src/main/webapp/images/svgs/go-down.svg
  war/src/main/webapp/images/svgs/go-top.svg
  war/src/main/webapp/images/svgs/go-up.svg
  war/src/main/webapp/scripts/hudson-behavior.js
  war/webpack.config.js
Labels: ready-for-merge, web-ui, rfe, squash-merge-me

#5753 Fix typo in ProcessTree.java
  core/src/main/java/hudson/util/ProcessTree.java
Labels: ready-for-merge, skip-changelog

#5720 [JENKINS-33596] Delete more of `UDPBroadcastThread` & `DNSMultiCast`
  core/src/main/java/hudson/DNSMultiCast.java
  core/src/main/java/hudson/UDPBroadcastThread.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/util/SystemProperties.java
  test/pom.xml
  test/src/test/java/hudson/security/csrf/CrumbExclusionTest.java
  test/src/test/java/jenkins/security/SuspiciousRequestFilterTest.java
Labels: ready-for-merge, skip-changelog

#5746 Renamed exclude file and set spotbugs default to medium
  cli/pom.xml
  core/pom.xml
  pom.xml
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, skip-changelog, squash-merge-me

#5756 Lower 'reasonable' number of icons (fix master build)
  core/src/test/java/org/jenkins/ui/icon/IconSetTest.java
Labels: skip-changelog
