Repository jenkinsci/jenkins, pull requests merged in 2021-07, with the labels that each got.

#5604 Restore `wstx-asl-3.2.9.jar` to WAR
  bom/pom.xml
  core/pom.xml
Labels: dependencies, ready-for-merge, regression-fix

#5600 Fix up comments for SECURITY-2371
  core/src/main/java/hudson/security/AuthenticationProcessingFilter2.java
  core/src/main/java/hudson/security/SecurityRealm.java
Labels: ready-for-merge, skip-changelog

#5566 Removing `SubClassGenerator`
  core/src/main/java/hudson/util/SubClassGenerator.java
  core/src/test/java/hudson/util/SubClassGeneratorTest.java
Labels: dependencies, ready-for-merge, removed, squash-merge-me

#5602 Exception test modernization / clean up
  core/src/main/java/hudson/ClassicPluginStrategy.java
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/Launcher.java
  core/src/main/java/hudson/WebAppMain.java
  core/src/main/java/hudson/diagnosis/MemoryUsageMonitor.java
  core/src/main/java/hudson/diagnosis/OldDataMonitor.java
  core/src/main/java/hudson/init/TaskMethodFinder.java
  core/src/main/java/hudson/init/impl/InstallUncaughtExceptionHandler.java
  core/src/main/java/hudson/model/BuildTimelineWidget.java
  core/src/main/java/hudson/model/Executor.java
  core/src/main/java/hudson/model/Fingerprint.java
  core/src/main/java/hudson/model/Job.java
  core/src/main/java/hudson/model/PageDecorator.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/model/Slave.java
  core/src/main/java/hudson/model/TreeView.java
  core/src/main/java/hudson/model/queue/MappingWorksheet.java
  core/src/main/java/hudson/node_monitors/AbstractNodeMonitorDescriptor.java
  core/src/main/java/hudson/node_monitors/ResponseTimeMonitor.java
  core/src/main/java/hudson/scm/ChangeLogSet.java
  core/src/main/java/hudson/security/BasicAuthenticationFilter.java
  core/src/main/java/hudson/util/ChunkedInputStream.java
  core/src/main/java/hudson/util/FormFieldValidator.java
  core/src/main/java/hudson/util/ProcessTree.java
  core/src/main/java/hudson/util/SecretRewriter.java
  core/src/main/java/jenkins/fingerprints/FingerprintStorage.java
  core/src/main/java/jenkins/model/identity/IdentityRootAction.java
  core/src/main/java/jenkins/util/JSONSignatureValidator.java
  core/src/main/java/jenkins/util/ResourceBundleUtil.java
  core/src/test/java/hudson/FilePathTest.java
  core/src/test/java/hudson/PluginManagerTest.java
  core/src/test/java/hudson/PluginWrapperTest.java
  core/src/test/java/hudson/UtilTest.java
  core/src/test/java/hudson/XmlFileTest.java
  core/src/test/java/hudson/model/ItemsTest.java
  core/src/test/java/hudson/model/UpdateCenterTest.java
  core/src/test/java/hudson/scheduler/CronTabTest.java
  core/src/test/java/jenkins/RemotingJarSignatureTest.java
  core/src/test/java/jenkins/util/JenkinsJVMTest.java
  core/src/test/java/jenkins/util/VirtualFileTest.java
Labels: ready-for-merge, skip-changelog

#5603 Remove `hudson.model.TreeView`
  core/src/main/java/hudson/model/TreeView.java
  core/src/main/resources/hudson/model/TreeView/ajaxRows.jelly
  core/src/main/resources/hudson/model/TreeView/main.jelly
  core/src/main/resources/hudson/model/TreeView/newView.jelly
  core/src/main/resources/hudson/model/TreeView/newViewDetail.jelly
  core/src/main/resources/hudson/model/TreeView/sidepanel2.jelly
  core/src/main/resources/hudson/model/TreeView/sidepanel2_bg.properties
  core/src/main/resources/hudson/model/TreeView/sidepanel2_da.properties
  core/src/main/resources/hudson/model/TreeView/sidepanel2_de.properties
  core/src/main/resources/hudson/model/TreeView/sidepanel2_es.properties
  core/src/main/resources/hudson/model/TreeView/sidepanel2_fr.properties
  core/src/main/resources/hudson/model/TreeView/sidepanel2_it.properties
  core/src/main/resources/hudson/model/TreeView/sidepanel2_ja.properties
  core/src/main/resources/hudson/model/TreeView/sidepanel2_pt_BR.properties
  core/src/main/resources/hudson/model/TreeView/sidepanel2_sr.properties
  core/src/main/resources/hudson/model/TreeView/sidepanel2_zh_TW.properties
  test/src/test/java/hudson/cli/UpdateViewCommandTest.java
Labels: ready-for-merge, removed, squash-merge-me

#5586 `AccessControlled` calls on `ACL.SYSTEM2` can bypass `getACL`
  core/src/main/java/hudson/model/AbstractItem.java
  core/src/main/java/hudson/model/Hudson.java
  core/src/main/java/hudson/security/ACL.java
  core/src/main/java/hudson/security/AccessControlled.java
  test/src/test/java/hudson/model/MyViewsPropertyTest.java
  test/src/test/java/hudson/security/ACLTest.java
Labels: ready-for-merge, rfe

#5622 Backporting for LTS 2.289.3
  war/src/main/less/modules/icons.less
Labels: into-lts

#5619 Exception tests modernized
  core/src/test/java/hudson/FilePathTest.java
  core/src/test/java/hudson/cli/ListJobsCommandTest.java
  core/src/test/java/hudson/cli/handlers/ViewOptionHandlerTest.java
  core/src/test/java/hudson/model/AbstractItemTest.java
  core/src/test/java/hudson/model/RunParameterValueTest.java
  core/src/test/java/hudson/util/AtomicFileWriterTest.java
  core/src/test/java/hudson/util/ConsistentHashTest.java
  core/src/test/java/hudson/util/CyclicGraphDetectorTest.java
  core/src/test/java/hudson/util/RetrierTest.java
  core/src/test/java/hudson/util/RobustReflectionConverterTest.java
  core/src/test/java/hudson/util/XStream2Test.java
  core/src/test/java/jenkins/model/RunIdMigratorTest.java
  core/src/test/java/jenkins/model/lazy/AbstractLazyLoadRunMapTest.java
  core/src/test/java/jenkins/util/TimerTest.java
  core/src/test/java/jenkins/util/io/PathRemoverTest.java
  core/src/test/java/jenkins/xml/XMLUtilsTest.java
Labels: ready-for-merge, skip-changelog

#5606 Remove native `chmod(2)` and `stat(2)` support
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/Util.java
  core/src/main/java/hudson/util/IOUtils.java
Labels: ready-for-merge, removed, squash-merge-me

#5609 Remove explicit dependency on ASM
  bom/pom.xml
  core/pom.xml
Labels: dependencies, ready-for-merge, skip-changelog, squash-merge-me

#5621 [JENKINS-66139] Avoid polluting the log if usage stats cannot be sent
  core/src/main/java/hudson/model/UsageStatistics.java
  core/src/main/resources/hudson/model/UsageStatistics/footer.jelly
Labels: ready-for-merge, rfe

#5599 Allow consumers of `XmlFile` to disable `fsync(2)`
  core/src/main/java/hudson/XmlFile.java
Labels: developer, ready-for-merge, squash-merge-me

#5613 [JENKINS-66094]Use Path.startsWith() for subdirectory check when unzipping
  core/src/main/java/hudson/FilePath.java
  test/src/test/java/hudson/FilePathTest.java
  test/src/test/resources/hudson/FilePathTest/ZipSlipSamePathPrefix/evil-win.zip
  test/src/test/resources/hudson/FilePathTest/ZipSlipSamePathPrefix/evil.zip
Labels: bug, ready-for-merge

#5617 Remove unnecessary differences from upstream `AntClassLoader`
  core/src/main/java/hudson/PluginFirstClassLoader.java
  core/src/main/java/jenkins/util/AntClassLoader.java
  core/src/main/java/jenkins/util/AntWithFindResourceClassLoader.java
Labels: ready-for-merge, skip-changelog

#5628 [JENKINS-66177] Ability to disable Java 11 monitor
  core/src/main/java/jenkins/monitor/JavaVersionRecommendationAdminMonitor.java
Labels: ready-for-merge, rfe

#5634 [JENKINS-65923] Accessibility issue - Images lacking "alt" text
  core/src/main/resources/lib/layout/icon.jelly
Labels: ready-for-merge, regression-fix

#5635 Make `AntClassLoader` multi-release JAR aware when it deals with `java.util.jar.JarFile`
  core/src/main/java/jenkins/util/AntClassLoader.java
Labels: developer, ready-for-merge

#5642 Update `access-modifier` 1.22 → 1.24
  bom/pom.xml
  pom.xml
Labels: ready-for-merge, skip-changelog

#5611 Shorter plugin label descriptions
  core/src/main/resources/hudson/model/Messages.properties
Labels: ready-for-merge, skip-changelog
