Repository jenkinsci/jenkins, pull requests merged in 2022-08, with the labels that each got.

#6952 Bump ATH revision from 1.113 to 1.115
  essentials.yml
Labels: ready-for-merge, skip-changelog

#6575 Add `SetContextClassLoader` utility class
  core/src/main/java/jenkins/util/SetContextClassLoader.java
  test/src/test/java/jenkins/util/SetContextClassLoaderTest.java
Labels: ready-for-merge, squash-merge-me, developer

#6902 [JENKINS-68801] - Fix for Functions#extractPluginNameFromIconSrc
  core/src/main/java/hudson/Functions.java
  core/src/test/java/hudson/FunctionsTest.java
Labels: ready-for-merge, web-ui, bug, squash-merge-me, security-approved

#6801 [JENKINS-68694] Winstone 6.1: Upgrade Jetty from 9.4.46.v20220331 to 10.0.11
  .github/dependabot.yml
  .idea/encodings.xml
  bom/pom.xml
  core/pom.xml
  pom.xml
  src/spotbugs/spotbugs-excludes.xml
  test/src/test/java/hudson/security/csrf/CrumbExclusionTest.java
  test/src/test/java/jenkins/security/SuspiciousRequestFilterTest.java
  war/pom.xml
  websocket/jetty10/pom.xml
  websocket/jetty10/src/main/java/jenkins/websocket/Jetty10Provider.java
Labels: ready-for-merge, rfe, squash-merge-me, removed, dependencies, java

#6960 Update remoting from 4.13.2 to 4.13.3 for LTS 2.346.3
  pom.xml
Labels: into-lts

#6956 [JENKINS-69202] Computer status icon is misleading
  core/src/main/resources/hudson/model/Computer/sidepanel.jelly
Labels: ready-for-merge, web-ui, rfe

#6897 [JENKINS-60866] Add CSP/inline JS rule to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready-for-merge, skip-changelog

#6965 [JENKINS-68926] update handlebars
  renovate.json
  war/package.json
  war/yarn.lock
Labels: ready-for-merge, skip-changelog, squash-merge-me, dependencies, javascript

#6971 [JENKINS-69210] Unable to rebuild a job triggered by polling
  core/src/main/java/hudson/triggers/SCMTrigger.java
Labels: regression-fix, ready-for-merge

#6962 [JENKINS-69232] Drop down select input is out of style with other drop down select input
  core/src/main/resources/lib/form/enum.jelly
Labels: ready-for-merge, web-ui, skip-changelog, security-approved

#6957 [JENKINS-69211] There is no space between the line and the button
  core/src/main/resources/hudson/PluginManager/advanced.jelly
Labels: ready-for-merge, web-ui, skip-changelog

#6961 [JENKINS-69230] There is no space between the form and the button
  war/src/main/less/form/reorderable-list.less
Labels: ready-for-merge, bug

#6930 [JENKINS-68957] Job configuration page SCM radio buttons have an odd selection animation
  core/src/main/resources/lib/form/radioBlock/radioBlock.js
Labels: ready-for-merge, bug, security-approved

#6969 [JENKINS-69254] Drop down select input is out of style with other drop down select input
  core/src/main/resources/hudson/tools/ToolLocationNodeProperty/config.jelly
Labels: ready-for-merge, web-ui, skip-changelog, security-approved

#6963 [JENKINS-69240] Version select input is out of style with other drop down select input
  core/src/main/resources/hudson/tools/DownloadFromUrlInstaller/config.jelly
Labels: ready-for-merge, web-ui, bug, security-approved

#6972 [JENKINS-69269] There is no space between the text and the button
  core/src/main/resources/lib/form/block.jelly
Labels: ready-for-merge, web-ui, skip-changelog

#6978 Upgrade Winstone from 6.1 to 6.2
  war/pom.xml
  websocket/jetty10/pom.xml
Labels: ready-for-merge, dependencies, java

#6799 Update buttons to use new classes on the dashboard
  core/src/main/resources/hudson/logging/LogRecorderManager/feeds.jelly
  core/src/main/resources/jenkins/security/ApiTokenProperty/config.jelly
  core/src/main/resources/lib/hudson/editableDescription.jelly
  core/src/main/resources/lib/hudson/iconSize.jelly
  core/src/main/resources/lib/hudson/rssBar.jelly
  core/src/main/resources/lib/layout/copyButton.jelly
  war/src/main/less/abstracts/colors.less
  war/src/main/less/abstracts/mixins.less
  war/src/main/less/abstracts/theme.less
  war/src/main/less/base/style.less
  war/src/main/less/modules/buttons-deprecated.less
  war/src/main/less/modules/buttons-temp.less
  war/src/main/less/modules/buttons.less
  war/src/main/less/modules/icon-size.less
  war/src/main/less/pages/dashboard.less
  war/src/main/less/simple-page.less
  war/src/main/less/styles.less
Labels: ready-for-merge, rfe, security-approved

#6907 Remove hierarchy-related sidebar links
  core/src/main/java/hudson/model/AbstractBuild.java
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/resources/hudson/PluginManager/sidepanel.groovy
  core/src/main/resources/hudson/PluginWrapper/uninstall.groovy
  core/src/main/resources/hudson/logging/LogRecorder/sidepanel.jelly
  core/src/main/resources/hudson/logging/LogRecorderManager/all.jelly
  core/src/main/resources/hudson/logging/LogRecorderManager/sidepanel.jelly
  core/src/main/resources/hudson/model/AbstractBuild/tasks.jelly
  core/src/main/resources/hudson/model/AbstractProject/sidepanel.jelly
  core/src/main/resources/hudson/model/Computer/sidepanel.jelly
  core/src/main/resources/hudson/model/ComputerSet/sidepanel.jelly
  core/src/main/resources/hudson/model/Fingerprint/index.jelly
  core/src/main/resources/hudson/model/Label/sidepanel.jelly
  core/src/main/resources/hudson/model/NoFingerprintMatch/index.jelly
  core/src/main/resources/hudson/model/UpdateCenter/sidepanel.jelly
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/index.groovy
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/sidepanel.jelly
  core/src/main/resources/jenkins/management/ShutdownLink/index.groovy
  core/src/main/resources/jenkins/model/GlobalCloudConfiguration/index.groovy
  core/src/main/resources/jenkins/model/Jenkins/configure.jelly
  core/src/main/resources/jenkins/tools/GlobalToolConfiguration/index.groovy
  core/src/main/resources/lib/layout/layout.jelly
  test/src/test/java/hudson/model/RSSTest.java
  war/src/main/less/base/layout-commons.less
Labels: ready-for-merge, web-ui, removed, security-approved

#6982 `PluginManager#whichPlugin` does not work for `JenkinsRule`
  core/src/main/java/hudson/PluginManager.java
  test/src/test/java/hudson/PluginManagerWhichTest.java
Labels: ready-for-merge, developer

#6985 Add configuration for `comment-ops`
  .github/comment-ops.yml
Labels: ready-for-merge, skip-changelog

#6976 [JENKINS-69276] No focus state on checkboxes
  war/src/main/less/form/checkbox.less
Labels: regression-fix, ready-for-merge, web-ui

#6981 Replaced several attribute calls with single Files.readAttributes call
  core/src/main/java/hudson/util/io/TarArchiver.java
  core/src/main/java/hudson/util/io/ZipArchiver.java
Labels: ready-for-merge, skip-changelog

#6980 Replaced some deprecated methods with suggested alternatives
  core/src/main/java/hudson/model/AbstractItem.java
  core/src/main/java/hudson/triggers/SCMTrigger.java
  test/src/test/java/hudson/model/FingerprintTest.java
  test/src/test/java/hudson/model/ProjectTest.java
Labels: ready-for-merge, skip-changelog

#6996 [JENKINS-69344] Fix version number on About Jenkins page
  war/src/main/less/pages/about.less
Labels: ready-for-merge, skip-changelog

#6998 Update Maven Jellydoc and Stapler plugins
  bom/pom.xml
  pom.xml
Labels: ready-for-merge, skip-changelog, dependencies, java

#6994 [JENKINS-69341] Text and logo exceed sidepanel in "About Jenkins" view
  war/src/main/less/pages/about.less
Labels: ready-for-merge, skip-changelog

#7011 Remove redundant `project.build.sourceEncoding` property
  pom.xml
Labels: ready-for-merge, skip-changelog

#6987 Deprecate AdministrativeError
  core/src/main/java/hudson/util/AdministrativeError.java
Labels: ready-for-merge, developer

#7007 fix: Make wrench symbol themeable
  war/src/main/resources/images/symbols/build.svg
Labels: ready-for-merge, skip-changelog

#7014 JENKINS-69370 Fix inbound agent connection
  core/src/main/java/jenkins/model/Jenkins.java
Labels: regression-fix, ready-for-merge

#6993 First backporting for LTS 2.361.1
  .github/dependabot.yml
  .idea/encodings.xml
  bom/pom.xml
  core/pom.xml
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/triggers/SCMTrigger.java
  core/src/main/resources/hudson/PluginManager/advanced.jelly
  core/src/main/resources/hudson/tools/DownloadFromUrlInstaller/config.jelly
  core/src/main/resources/lib/form/filter-menu-button/filter-menu-button.js
  core/src/main/resources/lib/form/radioBlock/radioBlock.js
  core/src/main/resources/lib/test/bar.jelly
  core/src/test/java/hudson/FunctionsTest.java
  pom.xml
  src/spotbugs/spotbugs-excludes.xml
  test/src/test/java/hudson/security/csrf/CrumbExclusionTest.java
  test/src/test/java/jenkins/security/SuspiciousRequestFilterTest.java
  war/pom.xml
  war/src/main/js/templates/plugin-manager/available.hbs
  war/src/main/less/form/reorderable-list.less
  websocket/jetty10/pom.xml
  websocket/jetty10/src/main/java/jenkins/websocket/Jetty10Provider.java
Labels: into-lts

#7018 Add renovate schema URL
  renovate.json
Labels: skip-changelog

#6999 [JENKINS-69320] Resize behavior of Execute Shell build steps is broken
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: regression-fix, ready-for-merge, web-ui

#7001 [JENKINS-68484] Users views icon is misleading
  core/src/main/java/hudson/model/MyViewsProperty.java
  war/src/main/resources/images/symbols/browsers.svg
Labels: ready-for-merge, skip-changelog

#7006 Change icon for 'People' task on user profiles
  core/src/main/resources/hudson/model/User/sidepanel.jelly
Labels: ready-for-merge, web-ui, skip-changelog, rfe

#7024 chore: Exclude bootstrap from renovate
  renovate.json
Labels: ready-for-merge, skip-changelog

#7023 Remove `junit-bom` from managed dependencies
  pom.xml
Labels: ready-for-merge, skip-changelog

#7027 [JENKINS-67624] `FileAlreadyExistsException` on startup
  core/src/main/java/hudson/Util.java
Labels: regression-fix, ready-for-merge

#7035 Ignore git-blame for prettier reformat
  .git-blame-ignore-revs
Labels: skip-changelog

#7034 Upgrade Stapler from 1711.v5b_1b_03f0fcf2 to 1711.1713.vc400cfb_5597a_
  bom/pom.xml
Labels: squash-merge-me, developer, into-lts

#7013 [JENKINS-69373] Baseline is too long in manage plugins.
  core/src/main/resources/hudson/PluginManager/advanced.jelly
Labels: ready-for-merge, skip-changelog

#7017 [JENKINS-69398] Missing focus state for selected radio buttons
  war/src/main/less/form/radio.less
Labels: ready-for-merge, bug, squash-merge-me

#7043 [JENKINS-69250] Searchbar is only present when using Jenkins header
  core/src/main/resources/jenkins/views/JenkinsHeader/headerContent.jelly
  core/src/main/resources/lib/layout/layout.jelly
Labels: regression-fix, ready-for-merge

#6768 feat: Add support for Apple touch bar icons
  core/src/main/java/hudson/security/ChainedServletFilter.java
  core/src/main/java/jenkins/security/ResourceDomainFilter.java
  core/src/main/resources/lib/layout/layout.jelly
  war/src/main/webapp/apple-touch-icon.png
  war/src/main/webapp/favicon.svg
  war/src/main/webapp/mask-icon.svg
Labels: ready-for-merge, rfe, squash-merge-me

#6870 [JENKINS-60866] Extract inline JS from update center
  core/src/main/resources/hudson/model/UpdateCenter/body.jelly
  core/src/main/resources/hudson/model/UpdateCenter/update-center.js
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6928 [JENKINS-69145] bouncing build number element on mouse hover
  war/src/main/less/modules/breadcrumbs.less
Labels: regression-fix, ready-for-merge, squash-merge-me

#6988 [JENKINS-68805] Fix test to actually demonstrate the problem
  core/src/test/java/org/jenkins/ui/icon/IconSetJenkins68805Test.java
  core/src/test/java/org/jenkins/ui/icon/IconSetTest.java
Labels: ready-for-merge, skip-changelog, squash-merge-me, alternative
