Repository jenkinsci/jenkins, pull requests merged in 2022-12, with the labels that each got.

#7465 Update core components to latest versions
  bom/pom.xml
  pom.xml
  test/pom.xml
  war/pom.xml
Labels: ready-for-merge, skip-changelog

#7458 Clean up `executable.Main#getHomeDir`
  war/src/main/java/executable/Main.java
Labels: ready-for-merge, skip-changelog

#7464 [JENKINS-70178] Improve tooltip performance
  war/src/main/js/components/tooltips/index.js
Labels: regression-fix, ready-for-merge, web-ui, security-approved

#7476 De-flake `QueueTest#persistenceBlockedItem`
  test/src/test/java/hudson/model/QueueTest.java
Labels: ready-for-merge, skip-changelog

#7485 Decline to cache a likely incorrect computation
  core/src/main/java/jenkins/model/Jenkins.java
Labels: ready-for-merge, skip-changelog

#7483 Make plugin installation tests less fragile
  test/pom.xml
  test/src/test/java/hudson/PluginManagerTest.java
  test/src/test/java/hudson/model/UpdateSiteTest.java
  test/src/test/java/jenkins/security/stapler/Security914Test.java
  test/src/test/resources/plugins/credentials.hpi
  test/src/test/resources/plugins/upload-test-update-center.json
Labels: ready-for-merge, skip-changelog

#7470 [JENKINS-70199] Add distributed builds telemetry
  core/src/main/java/jenkins/telemetry/impl/DistributedBuilds.java
  core/src/main/resources/jenkins/telemetry/impl/DistributedBuilds/description.jelly
Labels: ready-for-merge, rfe

#7482 Add Java 19 to `Jenkinsfile`
  Jenkinsfile
Labels: skip-changelog

#7498 Fix diacritic in Catalan translation
  core/src/main/resources/hudson/PluginManager/table_ca.properties
Labels: ready-for-merge, skip-changelog

#7501 De-flake `NodeProvisionerTest#baselineSlaveUsage`
  test/src/test/java/hudson/slaves/NodeProvisionerTest.java
Labels: ready-for-merge, skip-changelog

#7503 Keep ATH images up to date with renovate
  renovate.json
Labels: skip-changelog

#7477 [JENKINS-68692] Upgrade Guice from 5.0.1 to 5.1.0
  .github/dependabot.yml
  bom/pom.xml
  core/src/main/java/hudson/ExtensionFinder.java
Labels: ready-for-merge, rfe, dependencies, java

#7505 Remove Dependabot exclusion for log4j:log4j
  .github/dependabot.yml
Labels: skip-changelog

#7506 Update LTS line in Dependabot configuration
  .github/dependabot.yml
Labels: skip-changelog

#7507 Keep gitpods Dockerfile up to date with renovate
  .github/dependabot.yml
  renovate.json
Labels: skip-changelog

#7508 Provide native Java 11 HTTP client versions of `FormValidation#URLCheck` methods
  core/src/main/java/hudson/ProxyConfiguration.java
  core/src/main/java/hudson/util/FormValidation.java
  core/src/test/java/hudson/util/FormValidationTest.java
Labels: ready-for-merge, developer

#7514 [JENKINS-70206] Lazy initialization of `JnlpSlaveAgentProtocol4`
  core/src/main/java/jenkins/slaves/JnlpSlaveAgentProtocol4.java
Labels: ready-for-merge, bug

#7517 Backporting for LTS 2.375.2
  core/src/main/java/jenkins/telemetry/impl/DistributedBuilds.java
  core/src/main/java/jenkins/websocket/WebSockets.java
  core/src/main/resources/jenkins/telemetry/impl/DistributedBuilds/description.jelly
  pom.xml
  war/pom.xml
  war/src/main/js/section-to-sidebar-items.js
  war/src/main/less/styles.less
  websocket/jetty10/src/main/java/jenkins/websocket/Jetty10Provider.java
  websocket/jetty9/src/main/java/jenkins/websocket/Jetty9Provider.java
  websocket/spi/src/main/java/jenkins/websocket/Provider.java
Labels: into-lts

#7519 De-flake `ProjectTest#testUnrestrictedJobNoLabelByCloudNoQueue`
  test/src/test/java/hudson/model/ProjectTest.java
Labels: ready-for-merge, skip-changelog

#7314 Add search bar for top level settings in Manage Jenkins
  core/src/main/resources/hudson/model/ManageJenkinsAction/index.jelly
  core/src/main/resources/lib/layout/search-bar.jelly
  war/src/main/js/app.js
  war/src/main/js/components/search-bar/index.js
  war/src/main/js/pages/manage-jenkins/index.js
  war/src/main/js/util/keyboard.js
  war/src/main/js/util/security.js
  war/src/main/less/abstracts/theme.less
  war/src/main/less/form/search-bar.less
  war/src/main/less/modules/side-panel-tasks.less
  war/webpack.config.js
Labels: ready-for-merge, rfe, hacktoberfest-accepted, security-approved

#7521 Better null safety for `createProject`
  core/src/main/java/hudson/model/ItemGroupMixIn.java
  core/src/main/java/jenkins/model/Jenkins.java
Labels: ready-for-merge, skip-changelog

#7526 Upgrade Remoting from 3077.vd69cf116da_6f to 3085.vc4c6977c075a
  pom.xml
Labels: ready-for-merge, bug

#7524 [JENKINS-70240] fix for non http based URLs in PluginManager.doCheckUpdateSiteUrl
  core/src/main/java/hudson/PluginManager.java
  core/src/main/resources/hudson/Messages.properties
  core/src/main/resources/hudson/Messages_pt_BR.properties
  core/src/main/resources/hudson/Messages_zh_TW.properties
  core/src/test/java/hudson/PluginManagerTest.java
Labels: ready-for-merge, bug

#7528 Move MAINTAINERS.adoc at the root folder
  CONTRIBUTING.adoc
  MAINTAINERS.adoc
  README.adoc
Labels: skip-changelog

#7523 [JENKINS-23152] More robust handling of build number collisions
  core/src/main/java/jenkins/model/lazy/LazyBuildMixIn.java
Labels: ready-for-merge, rfe

#7535 Run `yarn dedupe`
  war/yarn.lock
Labels: skip-changelog

#6659 Expose `org.jenkins.ui.symbol.Symbol`
  core/src/main/java/org/jenkins/ui/icon/IconSet.java
  core/src/main/java/org/jenkins/ui/symbol/Symbol.java
  core/src/main/java/org/jenkins/ui/symbol/SymbolRequest.java
  core/src/test/java/org/jenkins/ui/icon/IconSetTest.java
  core/src/test/java/org/jenkins/ui/symbol/SymbolTest.java
  core/src/test/resources/images/symbols/science.path.xml
  core/src/test/resources/images/symbols/science.svg
  test/pom.xml
  test/src/test/java/org/jenkins/ui/symbol/SymbolJenkinsTest.java
Labels: ready-for-merge, web-ui, rfe, security-approved

#7531 Clean up `ath.sh`
  ath.sh
Labels: skip-changelog

#7539 JENKINS-70169 Restore link to last breadcrumb
  core/src/main/resources/lib/layout/breadcrumb.jelly
  core/src/main/resources/lib/layout/breadcrumbBar.jelly
Labels: regression-fix, ready-for-merge

#7536 Upgrade `cloudbees-folder` from 6.795.v3e23d3c6f194 to 6.800.v71307ca_b_986b
  test/pom.xml
Labels: ready-for-merge, skip-changelog

#7540 Replaced unnecessary unicode escape sequences in tests
  test/src/test/java/hudson/model/AbstractProjectTest.java
  test/src/test/java/hudson/model/DirectoryBrowserSupportTest.java
  test/src/test/java/hudson/model/UserIdMigratorTest.java
Labels: ready-for-merge, skip-changelog

#7256 De-duplicate file-based logging implementations
  pom.xml
  war/pom.xml
  war/src/main/java/executable/LogFileOutputStream.java
  war/src/main/java/executable/Main.java
Labels: ready-for-merge, rfe, upgrade-guide-needed

#7543 Fix URICheckEncodingMonitor NPE
  core/src/main/java/jenkins/diagnostics/URICheckEncodingMonitor.java
  test/src/test/java/jenkins/diagnostics/URICheckEncodingMonitorTest.java
Labels: skip-changelog

#7427 [JENKINS-70121] Align Build Executor Status collapsed content with build queue design pattern
  core/src/main/resources/lib/layout/pane.jelly
Labels: ready-for-merge, web-ui, rfe

#7416 Removed browser specific border-radius in `layout-mixins.less`
  war/src/main/js/widgets/layout-mixins.less
Labels: ready-for-merge, web-ui, skip-changelog

#7542 Replaced some deprecated presetData annotations with the suggested replacement
  test/src/test/java/hudson/cli/CLIActionTest.java
  test/src/test/java/hudson/security/csrf/DefaultCrumbIssuerTest.java
  test/src/test/java/lib/layout/AjaxTest.java
  test/src/test/java/lib/layout/LayoutTest.java
Labels: ready-for-merge, skip-changelog

#7541 Replaced anonymous types with lambdas in tests
  test/src/test/java/hudson/bugs/DateConversionTest.java
  test/src/test/java/hudson/cli/CLIActionTest.java
  test/src/test/java/hudson/cli/QuietDownCommandTest.java
  test/src/test/java/hudson/cli/WaitNodeOfflineCommandTest.java
  test/src/test/java/hudson/diagnosis/OldDataMonitorTest.java
  test/src/test/java/hudson/model/DescriptorTest.java
  test/src/test/java/hudson/model/JobTest.java
  test/src/test/java/hudson/model/QueueTest.java
  test/src/test/java/hudson/model/ViewJobTest.java
  test/src/test/java/hudson/model/labels/LabelExpressionTest.java
  test/src/test/java/hudson/search/SearchTest.java
  test/src/test/java/hudson/tasks/ShellTest.java
  test/src/test/java/jenkins/model/ContextMenuTest.java
  test/src/test/java/jenkins/model/ExtensionTypeHierarchyTest.java
  test/src/test/java/jenkins/model/JenkinsFutureDependencyGraphTest.java
  test/src/test/java/jenkins/security/Security380Test.java
  test/src/test/java/jenkins/security/SecurityContextExecutorServiceTest.java
Labels: ready-for-merge, skip-changelog

#7173 Update the design of the 'Advanced' button
  core/src/main/resources/hudson/tools/ToolInstallation/global.jelly
  core/src/main/resources/jenkins/security/ApiTokenProperty/config.jelly
  core/src/main/resources/jenkins/tasks/filters/EnvVarsFilterGlobalConfiguration/config.jelly
  core/src/main/resources/lib/form/advanced.jelly
  core/src/main/resources/lib/form/advanced/advanced.js
  core/src/main/resources/lib/form/confirm.js
  test/src/test/java/hudson/model/ProjectTest.java
  test/src/test/java/lib/form/AdvancedButtonTest.java
  test/src/test/java/lib/form/HeteroListTest.java
  war/src/main/less/form/layout.less
  war/src/main/less/modules/buttons.less
Labels: ready-for-merge, web-ui, rfe, security-approved

#7487 [JENKINS-70169] Add missing breadcrumb items in `resources/jenkins`
  core/src/main/resources/jenkins/model/Jenkins/MasterComputer/configure.jelly
  core/src/main/resources/jenkins/model/Jenkins/_restart.jelly
  core/src/main/resources/jenkins/model/Jenkins/_safeRestart.jelly
  core/src/main/resources/jenkins/model/Jenkins/fingerprintCheck.jelly
  core/src/main/resources/jenkins/model/Jenkins/legend.jelly
  core/src/main/resources/jenkins/model/Jenkins/newView.jelly
  core/src/main/resources/jenkins/model/Jenkins/projectRelationship-help.jelly
  core/src/main/resources/jenkins/model/Jenkins/projectRelationship.jelly
  core/src/main/resources/jenkins/security/apitoken/LegacyApiTokenAdministrativeMonitor/manage.jelly
Labels: ready-for-merge, web-ui, rfe

#7425 [JENKINS-70117] Align is not same between th and td
  war/src/main/less/modules/table.less
Labels: ready-for-merge, bug

#7492 [JENKINS-70169] Add missing breadcrumb items in `resources/hudson/model/User`
  core/src/main/resources/hudson/model/User/builds.jelly
  core/src/main/resources/hudson/model/User/configure.jelly
  core/src/main/resources/hudson/model/User/delete.jelly
  core/src/main/resources/hudson/model/User/index.jelly
Labels: ready-for-merge, web-ui, rfe

#7494 [JENKINS-70169] Add missing breadcrumb items in `resources/hudson/model/Abstract*`
  core/src/main/resources/hudson/model/AbstractBuild/changes.jelly
  core/src/main/resources/hudson/model/AbstractBuild/index.jelly
  core/src/main/resources/hudson/model/AbstractItem/confirm-rename.jelly
  core/src/main/resources/hudson/model/AbstractItem/delete.jelly
  core/src/main/resources/hudson/model/AbstractItem/noWorkspace.jelly
  core/src/main/resources/hudson/model/AbstractModelObject/editDescription.jelly
  core/src/main/resources/hudson/model/AbstractProject/changes.jelly
  core/src/main/resources/hudson/model/AbstractProject/wipeOutWorkspaceBlocked.jelly
Labels: ready-for-merge, web-ui, rfe

#7493 [JENKINS-70169] Add missing breadcrumb items in `resources/hudson/model/View`
  core/src/main/resources/hudson/model/View/AsynchPeople/index.jelly
  core/src/main/resources/hudson/model/View/builds.jelly
  core/src/main/resources/hudson/model/View/configure.jelly
  core/src/main/resources/hudson/model/View/delete.jelly
  core/src/main/resources/hudson/model/View/index.jelly
Labels: ready-for-merge, web-ui, rfe

#7488 [JENKINS-70169] Add missing breadcrumb items in `resources/hudson/slaves`
  core/src/main/resources/hudson/slaves/Cloud/index.jelly
  core/src/main/resources/hudson/slaves/SlaveComputer/already-launched.jelly
  core/src/main/resources/hudson/slaves/SlaveComputer/disconnect.jelly
  core/src/main/resources/hudson/slaves/SlaveComputer/log.jelly
  core/src/main/resources/hudson/slaves/SlaveComputer/systemInfo.jelly
  core/src/main/resources/hudson/slaves/SlaveComputer/threadDump.jelly
Labels: ready-for-merge, web-ui, rfe

#7491 [JENKINS-70169] Add missing breadcrumb items in `resources/hudson/model/Run`
  core/src/main/resources/hudson/model/Run/artifacts-index.jelly
  core/src/main/resources/hudson/model/Run/configure.jelly
  core/src/main/resources/hudson/model/Run/confirmDelete.jelly
  core/src/main/resources/hudson/model/Run/console.jelly
  core/src/main/resources/hudson/model/Run/delete-retry.jelly
Labels: ready-for-merge, web-ui, rfe

#7490 [JENKINS-70169] Add missing breadcrumb items in `resources/hudson/logging`
  core/src/main/resources/hudson/logging/LogRecorder/configure.jelly
  core/src/main/resources/hudson/logging/LogRecorder/delete.jelly
  core/src/main/resources/hudson/logging/LogRecorder/index.jelly
  core/src/main/resources/hudson/logging/LogRecorderManager/index.jelly
  core/src/main/resources/hudson/logging/LogRecorderManager/levels.jelly
  core/src/main/resources/hudson/logging/LogRecorderManager/new.jelly
Labels: ready-for-merge, web-ui, rfe

#7475 fix letter-spacing
  war/src/main/less/styles.less
Labels: regression-fix, ready-for-merge

#7549 Remove Java 7 Spotbugs suppression
  war/src/main/java/executable/Main.java
Labels: ready-for-merge, skip-changelog

#7552 Replaced deprecated `impersonate2` with `as2` in Tests
  test/src/test/java/hudson/model/DependencyGraphTest.java
  test/src/test/java/hudson/model/NodeTest.java
Labels: ready-for-merge, skip-changelog

#7495 [JENKINS-70169] Add missing breadcrumb items in `resources/hudson/model/Computer*`
  core/src/main/resources/hudson/model/Computer/builds.jelly
  core/src/main/resources/hudson/model/Computer/configure.jelly
  core/src/main/resources/hudson/model/Computer/delete.jelly
  core/src/main/resources/hudson/model/Computer/index.jelly
  core/src/main/resources/hudson/model/Computer/load-statistics.jelly
  core/src/main/resources/hudson/model/Computer/markOffline.jelly
  core/src/main/resources/hudson/model/Computer/setOfflineCause.jelly
  core/src/main/resources/hudson/model/ComputerSet/configure.jelly
  core/src/main/resources/hudson/model/ComputerSet/index.jelly
  core/src/main/resources/hudson/model/ComputerSet/new.jelly
Labels: ready-for-merge, web-ui, rfe

#7373 Add tabs to System Information page
  core/src/main/resources/hudson/model/LoadStatistics/main.jelly
  core/src/main/resources/hudson/model/LoadStatistics/resources.js
  core/src/main/resources/jenkins/model/Jenkins/systemInfo.jelly
  core/src/main/resources/lib/layout/tabPane.jelly
  war/src/main/js/pages/manage-jenkins/system-information/index.js
  war/webpack.config.js
Labels: ready-for-merge, web-ui, rfe, security-approved
