Repository jenkinsci/jenkins, pull requests merged in 2022-01, with the labels that each got.

#6144 Fix `NP_NULL_ON_SOME_PATH` SpotBugs violations
  core/src/main/java/hudson/triggers/SCMTrigger.java
  core/src/main/java/hudson/triggers/Trigger.java
Labels: ready-for-merge, skip-changelog

#6145 Removed unused class which got moved to stapler a long time ago
  core/src/main/java/hudson/util/WriterOutputStream.java
Labels: ready-for-merge, skip-changelog

#6148 Fill in some deprecation TODOs
  core/src/main/java/hudson/Util.java
  core/src/main/java/hudson/model/Fingerprint.java
  core/src/main/java/jenkins/fingerprints/FingerprintStorage.java
Labels: ready-for-merge, skip-changelog

#6143 Fix `LG_LOST_LOGGER_DUE_TO_WEAK_REFERENCE` SpotBugs violations
  core/src/main/java/hudson/WebAppMain.java
  core/src/main/java/hudson/logging/LogRecorderManager.java
  core/src/main/resources/hudson/logging/Messages.properties
  test/src/test/java/hudson/logging/LogRecorderManagerTest.java
Labels: ready-for-merge, bug, squash-merge-me

#6147 Consistent indentation with spaces rather than tabs
  cli/src/main/java/hudson/cli/CLI.java
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/Launcher.java
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/PluginWrapper.java
  core/src/main/java/hudson/WebAppMain.java
  core/src/main/java/hudson/model/AbstractBuild.java
  core/src/main/java/hudson/model/AbstractProject.java
  core/src/main/java/hudson/model/AperiodicWork.java
  core/src/main/java/hudson/model/PaneStatusProperties.java
  core/src/main/java/hudson/model/ParametersDefinitionProperty.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/triggers/SCMTrigger.java
  core/src/main/java/hudson/util/ProcessTree.java
  core/src/main/java/jenkins/install/InstallUtil.java
  core/src/test/java/hudson/UtilTest.java
  core/src/test/java/hudson/tasks/_maven/Maven3MojoNoteTest.java
  core/src/test/java/hudson/util/RunListTest.java
  pom.xml
  test/src/test/java/hudson/PluginManagerTest.java
  test/src/test/java/hudson/model/AbstractBuildTest.java
  test/src/test/java/hudson/model/HelpLinkTest.java
  test/src/test/java/hudson/slaves/EnvironmentVariableNodePropertyTest.java
  test/src/test/java/hudson/tasks/MavenTest.java
  test/src/test/java/jenkins/model/JenkinsBuildsAndWorkspacesDirectoriesTest.java
Labels: ready-for-merge, skip-changelog

#6146 Use SVG icons for agent context menu and executor status
  core/src/main/java/hudson/model/View.java
  core/src/main/java/hudson/slaves/SlaveComputer.java
  core/src/main/java/jenkins/model/ModelObjectWithContextMenu.java
  core/src/main/java/org/jenkins/ui/icon/Icon.java
  core/src/main/java/org/jenkins/ui/icon/IconType.java
  core/src/main/resources/lib/hudson/executors.jelly
Labels: ready-for-merge, web-ui, rfe

#6133 Fix a `SE_BAD_FIELD` SpotBugs violation in `Job`
  core/src/main/java/hudson/model/Job.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6135 Fix `RV_RETURN_VALUE_IGNORED_BAD_PRACTICE` SpotBugs violations
  core/src/main/java/hudson/WebAppMain.java
  core/src/main/java/hudson/util/CompressedFile.java
  core/src/main/java/jenkins/util/ProgressiveRendering.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6141 Fix remaining `MS_SHOULD_BE_FINAL` SpotBugs violations
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/model/item_category/ItemCategory.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6134 Mark `PollingResult` as `SerializableOnlyOverRemoting`
  core/src/main/java/hudson/scm/PollingResult.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6155 Update caniuse db
  war/yarn.lock
Labels: ready-for-merge, skip-changelog

#6157 Generalize compatibility warning for compatibleSince
  core/src/main/resources/hudson/Messages.properties
Labels: ready-for-merge, skip-changelog

#6154 Remove `UG_SYNC_SET_UNSYNC_GET` SpotBugs exclusions
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, skip-changelog

#6162 [JENKINS-67515] Fix vertical icon alignment for build status in M and S icon sizes
  war/src/main/less/base/layout-commons.less
  war/src/main/less/base/style.less
  war/src/main/less/modules/icons.less
  war/src/main/less/modules/table.less
Labels: ready-for-merge, bug

#6164 [JENKINS-67470] Extend shading of Tyrus WebSocket client
  cli/pom.xml
Labels: ready-for-merge, bug

#6166 Do not use `javax.mail` for `doCheckAdminAddress`
  core/src/main/java/jenkins/model/JenkinsLocationConfiguration.java
  core/src/main/resources/jenkins/model/Messages.properties
Labels: ready-for-merge, skip-changelog

#6161 Begin migration to Jakarta Annotations
  bom/pom.xml
  core/src/main/java/hudson/ExtensionFinder.java
  core/src/main/java/hudson/model/PersistentDescriptor.java
  core/src/main/java/hudson/triggers/SCMTrigger.java
Labels: ready-for-merge, developer

#6150 Use explicit character set in tests
  cli/src/test/java/hudson/cli/PlainCLIProtocolTest.java
  core/src/test/java/hudson/FilePathTest.java
  core/src/test/java/hudson/LauncherTest.java
  core/src/test/java/hudson/PluginManagerTest.java
  core/src/test/java/hudson/UtilTest.java
  core/src/test/java/hudson/cli/ListJobsCommandTest.java
  core/src/test/java/hudson/slaves/ComputerLauncherTest.java
  core/src/test/java/hudson/util/SecretRewriterTest.java
  core/src/test/java/hudson/util/SecretTest.java
  core/src/test/java/hudson/util/io/RewindableRotatingFileOutputStreamTest.java
  core/src/test/java/jenkins/org/apache/commons/validator/routines/DomainValidatorTest.java
  core/src/test/java/jenkins/security/CryptoConfidentialKeyTest.java
  core/src/test/java/jenkins/security/DefaultConfidentialStoreTest.java
  core/src/test/java/jenkins/util/io/PathRemoverTest.java
  test/src/test/java/hudson/LauncherTest.java
  test/src/test/java/hudson/PluginManagerTest.java
  test/src/test/java/hudson/ProcTest.java
  test/src/test/java/hudson/XMLFileTest.java
  test/src/test/java/hudson/cli/BuildCommandTest.java
  test/src/test/java/hudson/cli/CLIActionTest.java
  test/src/test/java/hudson/cli/CLIEnvVarTest.java
  test/src/test/java/hudson/cli/CLITest.java
  test/src/test/java/hudson/cli/GetJobCommandTest.java
  test/src/test/java/hudson/cli/GroovyshCommandTest.java
  test/src/test/java/hudson/cli/ReloadConfigurationCommandTest.java
  test/src/test/java/hudson/console/AnnotatedLargeTextTest.java
  test/src/test/java/hudson/console/ConsoleLogFilterTest.java
  test/src/test/java/hudson/model/AbstractProjectTest.java
  test/src/test/java/hudson/model/CauseTest.java
  test/src/test/java/hudson/model/FingerprintCleanupThreadTest.java
  test/src/test/java/hudson/model/FreeStyleProjectTest.java
  test/src/test/java/hudson/model/ItemGroupMixInTest.java
  test/src/test/java/hudson/model/JobTest.java
  test/src/test/java/hudson/model/UpdateSiteTest.java
  test/src/test/java/hudson/model/listeners/ItemListenerTest.java
  test/src/test/java/hudson/security/TokenBasedRememberMeServices2Test.java
  test/src/test/java/hudson/triggers/TriggerStartTest.java
  test/src/test/java/hudson/triggers/TriggerTest.java
  test/src/test/java/hudson/util/ArgumentListBuilder2Test.java
  test/src/test/java/hudson/util/RobustReflectionConverterTest.java
  test/src/test/java/jenkins/agents/WebSocketAgentsTest.java
  test/src/test/java/jenkins/install/SetupWizardTest.java
  test/src/test/java/jenkins/model/JenkinsReloadConfigurationTest.java
  test/src/test/java/jenkins/model/NodeListenerTest.java
  test/src/test/java/jenkins/security/RekeySecretAdminMonitorTest.java
  test/src/test/java/jenkins/tasks/SimpleBuildWrapperTest.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6098 Fix more `DM_DEFAULT_ENCODING` SpotBugs violations
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/cli/CLICommand.java
  core/src/main/java/hudson/cli/GroovyCommand.java
  core/src/main/java/hudson/cli/GroovyshCommand.java
  core/src/main/java/hudson/cli/ListChangesCommand.java
  core/src/main/java/hudson/lifecycle/WindowsServiceLifecycle.java
  core/src/main/java/hudson/model/StreamBuildListener.java
  core/src/main/java/hudson/os/SU.java
  core/src/main/java/hudson/util/StreamTaskListener.java
  core/src/main/java/jenkins/diagnosis/HsErrPidList.java
  core/src/main/java/jenkins/slaves/DefaultJnlpSlaveReceiver.java
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6128 Stop spamming logs when retrieving AdminWhitelistRule
  core/src/main/java/jenkins/security/s2m/AdminWhitelistRule.java
Labels: ready-for-merge, skip-changelog

#6171 Documentation is no longer in the wiki, so rephrase label
  core/src/main/resources/jenkins/install/pluginSetupWizard.properties
  core/src/main/resources/jenkins/install/pluginSetupWizard_fr.properties
  core/src/main/resources/jenkins/install/pluginSetupWizard_it.properties
  core/src/main/resources/jenkins/install/pluginSetupWizard_lt.properties
  core/src/main/resources/jenkins/install/pluginSetupWizard_pl.properties
  core/src/main/resources/jenkins/install/pluginSetupWizard_sr.properties
  core/src/main/resources/jenkins/install/pluginSetupWizard_zh_CN.properties
Labels: ready-for-merge, skip-changelog

#6175 `LazyBuildMixInTest#newRunningBuildRelationFromPrevious` flaked on Windows
  test/src/test/java/jenkins/model/lazy/LazyBuildMixInTest.java
Labels: ready-for-merge, skip-changelog

#6172 [JENKINS-67198] Increase width of forms
  core/src/main/resources/hudson/model/Job/configure.jelly
  war/src/main/js/widgets/config/tabbar.less
  war/src/main/less/abstracts/theme.less
Labels: regression-fix, ready-for-merge, web-ui, bug

#6151 Unify labels in plugin manager
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/java/jenkins/plugins/DetachedPluginsUtil.java
  core/src/main/java/jenkins/util/PluginLabelUtil.java
  core/src/main/resources/hudson/model/Messages.properties
  core/src/main/resources/hudson/model/Messages_bg.properties
  core/src/main/resources/hudson/model/Messages_de.properties
  core/src/main/resources/hudson/model/Messages_es.properties
  core/src/main/resources/hudson/model/Messages_it.properties
  core/src/main/resources/hudson/model/Messages_lt.properties
  core/src/main/resources/hudson/model/Messages_sr.properties
  core/src/main/resources/jenkins/canonical-labels.txt
  core/src/test/java/jenkins/util/PluginLabelUtilTest.java
Labels: ready-for-merge, web-ui, rfe

#6165 Detach JavaMail
  bom/pom.xml
  core/pom.xml
  core/src/main/resources/jenkins/split-plugin-cycles.txt
  core/src/main/resources/jenkins/split-plugins.txt
  test/pom.xml
  war/pom.xml
Labels: ready-for-merge, developer, dependencies, java

#6195 Revert "Bump `jenkins-test-harness` (#6173)"
  test/pom.xml
Labels: ready-for-merge, skip-changelog

#6190 Fix Javadoc of SCM#requiresWorkspaceForPolling
  core/src/main/java/hudson/scm/SCM.java
Labels: skip-changelog

#6187 Backporting for LTS 2.319.3
  cli/pom.xml
  essentials.yml
Labels: into-lts

#6185 Merge back BuildAuthorizationTokenSEC2558Test
  test/src/test/java/hudson/model/BuildAuthorizationTokenSEC2558Test.java
  test/src/test/java/hudson/model/BuildAuthorizationTokenTest.java
Labels: ready-for-merge, skip-changelog

#6179 Nullability annotations
  core/src/main/java/hudson/model/Label.java
  core/src/main/java/hudson/model/labels/LabelAtom.java
  core/src/main/java/hudson/model/labels/LabelExpression.java
  core/src/main/java/jenkins/model/Jenkins.java
Labels: ready-for-merge, internal, skip-changelog

#6196 Fix UtilTest#createDirectoriesInRoot() on mac
  core/src/test/java/hudson/UtilTest.java
Labels: ready-for-merge, skip-changelog

#6189 Confirm that UMOMNEE2 is translated to UMOMNEE in legacy API
  test/src/test/java/hudson/model/UserTest.java
Labels: ready-for-merge, skip-changelog

#6199 Fix progress bar location
  core/src/main/resources/lib/hudson/buildCaption.jelly
  war/src/main/less/base/style.less
Labels: regression-fix, ready-for-merge

#6191 Prevent one redirect in `AsynchPeople`
  core/src/main/java/hudson/model/View.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6203 JENKINS-56057 Support update site warnings with Configuration as Code
  core/src/main/java/jenkins/security/UpdateSiteWarningsConfiguration.java
Labels: ready-for-merge, rfe, squash-merge-me

#6204 Add test to confirm bundled plugins don't have active warnings
  test/src/test/java/jenkins/install/LoadDetachedPluginsTest.java
  test/src/test/resources/jenkins/install/LoadDetachedPluginsTest/noUpdateSiteWarnings/config.xml
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6205 Remove `publish-over-ssh` from setup wizard suggestions
  core/src/main/resources/jenkins/install/platform-plugins.json
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6206 [JENKINS-67662] Do not show wrong feature name in tooltips
  core/src/main/resources/lib/form/entry.jelly
Labels: ready-for-merge, bug, squash-merge-me

#6212 deflake Security400Test#ensureDoStopStillReachable
  test/src/test/java/jenkins/security/stapler/Security400Test.java
Labels: ready-for-merge, internal, skip-changelog

#6217 Clean up imports
  core/src/main/java/hudson/model/Descriptor.java
  core/src/main/java/hudson/model/RunMap.java
  core/src/main/java/hudson/util/FormValidation.java
  pom.xml
  test/src/test/java/hudson/util/BootFailureTest.java
  test/src/test/java/jenkins/model/JenkinsLocationConfigurationTest.java
  test/src/test/java/lib/form/RowSetTest.java
Labels: skip-changelog, squash-merge-me

#6221 leave link to JENKINS-67681
  test/src/test/java/hudson/model/FreeStyleProjectTest.java
Labels: ready-for-merge, internal, skip-changelog

#6209 EOL support for JRuby
  core/src/main/java/hudson/util/XStream2.java
  core/src/main/resources/jenkins/security/whitelisted-classes.txt
Labels: ready-for-merge, upgrade-guide-needed, squash-merge-me, removed

#6184 [JENKINS-67496] Drag & drop is messed up, drag placeholders always have tiny size
  war/src/main/js/sortable-drag-drop.js
Labels: regression-fix, ready-for-merge, bug

#6227 Exclude newer versions of `tyrus-standalone-client-jdk` that require Java 11
  .github/dependabot.yml
Labels: skip-changelog

#6193 JENKINS-67635 consider agent label expressions when applying trimLabels
  core/src/main/java/jenkins/model/Jenkins.java
  test/src/test/java/hudson/slaves/NodeProvisionerTest.java
Labels: regression-fix, ready-for-merge

#6225 [JENKINS-67627] Have expandable text boxes expand into multiple lines
  test/src/test/java/lib/form/ExpandableTextboxTest.java
  test/src/test/resources/lib/form/ExpandableTextboxTest/ExpandableTextBoxProperty/config-details.jelly
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, bug, alternative

#6224 [JEP-7] Comment updates after removing JRuby support
  core/src/main/java/hudson/util/LogTaskListener.java
  core/src/main/java/hudson/util/StreamTaskListener.java
  core/src/main/resources/hudson/model/Api/index.jelly
  test/src/test/java/hudson/util/LogTaskListenerTest.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6228 Notify `systemd(1)` about start-up completion and other service status changes
  core/src/main/java/hudson/WebAppMain.java
  core/src/main/java/hudson/lifecycle/Lifecycle.java
  core/src/main/java/hudson/lifecycle/SystemdLifecycle.java
  core/src/main/java/jenkins/model/Jenkins.java
Labels: ready-for-merge, rfe, squash-merge-me
