Repository jenkinsci/jenkins, pull requests merged in 2022-11, with the labels that each got.

#7328 Clean up usages of `Callable#getChannelOrFail` and `Callable#getOpenChannelOrFail`
  core/src/main/java/hudson/slaves/SlaveComputer.java
  core/src/main/java/jenkins/security/MasterToSlaveCallable.java
  test/pom.xml
  test/src/test/java/jenkins/slaves/OldRemotingAgentTest.java
Labels: ready-for-merge, skip-changelog

#7329 Fix nested link Javadoc warning
  core/src/main/java/hudson/model/Actionable.java
Labels: ready-for-merge, skip-changelog

#7330 Remove unused metrics profile
  pom.xml
Labels: ready-for-merge, skip-changelog

#7335 Removed unused `UnbufferedBase64InputStream`
  core/src/main/java/hudson/util/UnbufferedBase64InputStream.java
Labels: ready-for-merge, removed

#7337 Run `yarn dedupe`
  war/yarn.lock
Labels: ready-for-merge, skip-changelog

#7303 Allow detached plugin location to be overridden
  core/src/main/java/hudson/PluginManager.java
Labels: ready-for-merge, developer

#7324 Update more bundled plugins
  war/pom.xml
Labels: ready-for-merge, dependencies, java

#7253 Translate JVM crash report page into French
  core/src/main/resources/jenkins/diagnosis/HsErrPidList/description_fr.properties
  core/src/main/resources/jenkins/diagnosis/HsErrPidList/index_fr.properties
  core/src/main/resources/jenkins/diagnosis/HsErrPidList/message_fr.properties
Labels: ready-for-merge, localization, hacktoberfest-accepted

#7340 Increase minimum required Remoting version from 4.2.1 to 4.7
  pom.xml
  test/pom.xml
Labels: ready-for-merge, rfe, upgrade-guide-needed

#7351 Update terminology in usage statistics page
  core/src/main/resources/hudson/model/UsageStatistics/help-usageStatisticsCollected.jelly
Labels: ready-for-merge, skip-changelog

#7350 [JENKINS-70023] Fix Gravatar error on profile page
  core/src/main/resources/hudson/model/User/index.jelly
Labels: regression-fix, ready-for-merge, web-ui

#7349 Remove obsolete browser-specific CSS animation properties in `pluginSetupWizard.less`
  war/src/main/less/pluginSetupWizard.less
Labels: ready-for-merge, web-ui, skip-changelog

#7348 [JENKINS-69587] Fix console view bouncing when new entries appear
  war/src/main/js/section-to-sidebar-items.js
  war/src/main/less/styles.less
Labels: regression-fix, ready-for-merge, web-ui

#7342 [JENKINS-70044] Add telemetry for activation of optional permissions
  core/src/main/java/jenkins/telemetry/impl/OptionalPermissions.java
  core/src/main/resources/jenkins/telemetry/impl/OptionalPermissions/description.jelly
Labels: ready-for-merge, rfe

#7346 [JENKINS-69517] Make 'focus-visible' frame less excessive
  war/src/main/less/abstracts/mixins.less
Labels: ready-for-merge, web-ui, bug

#7363 Implemented test in `ProcTest` for windows
  test/src/test/java/hudson/ProcTest.java
Labels: ready-for-merge, skip-changelog

#7361 Replaced `stylelint-formatter.js` with direct parameter
  war/package.json
  war/stylelint-formatter.js
Labels: ready-for-merge, skip-changelog

#7352 Update Manage Nodes page to use app bar and remove sidebar from New Node page
  core/src/main/resources/hudson/model/ComputerSet/_new.jelly
  core/src/main/resources/hudson/model/ComputerSet/index.jelly
  core/src/main/resources/hudson/model/ComputerSet/new.jelly
  core/src/main/resources/hudson/model/ComputerSet/sidepanel.jelly
  war/src/main/less/base/display.less
  war/src/main/less/styles.less
  war/src/main/resources/images/symbols/refresh.svg
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, web-ui, rfe, security-approved

#7229 fix: change icon to symbol
  .idea/encodings.xml
  core/src/main/resources/lib/hudson/editTypeIcon.jelly
Labels: ready-for-merge, web-ui, rfe, hacktoberfest-accepted, security-approved

#7372 Enable dependabot for gitpod Dockerfile
  .github/dependabot.yml
  .gitpod/Dockerfile
Labels: skip-changelog

#7369 Backporting for LTS 2.361.4 LTS
  core/src/main/java/hudson/model/AbstractProject.java
  core/src/main/java/hudson/model/Queue.java
  test/src/test/java/hudson/model/QueueTest.java
Labels: regression-fix, into-lts

#7341 Update more bundled plugins
  war/pom.xml
Labels: ready-for-merge, dependencies, java

#7366 Fix button padding in admin monitor
  core/src/main/resources/jenkins/management/AdministrativeMonitorsDecorator/resources.css
Labels: regression-fix, ready-for-merge, web-ui

#7358 Backporting for LTS 2.375.1
  core/src/main/java/jenkins/telemetry/impl/OptionalPermissions.java
  core/src/main/resources/hudson/model/User/index.jelly
  core/src/main/resources/jenkins/telemetry/impl/OptionalPermissions/description.jelly
  pom.xml
Labels: into-lts

#7371 Removed obsolete browser workarounds for @keyframes in `pluginSetupWizard.less`
  war/src/main/less/pluginSetupWizard.less
Labels: ready-for-merge, skip-changelog

#7364 Label destructive 'Dismiss' buttons red
  core/src/main/resources/hudson/diagnosis/HudsonHomeDiskUsageMonitor/message.jelly
  core/src/main/resources/hudson/diagnosis/OldDataMonitor/message.jelly
  core/src/main/resources/hudson/diagnosis/ReverseProxySetupMonitor/message.jelly
  core/src/main/resources/hudson/diagnosis/TooManyJobsButNoView/message.jelly
  core/src/main/resources/hudson/node_monitors/MonitorMarkedNodeOffline/message.jelly
  core/src/main/resources/jenkins/diagnostics/ControllerExecutorsAgents/message.jelly
  core/src/main/resources/jenkins/diagnostics/ControllerExecutorsNoAgents/message.jelly
  core/src/main/resources/jenkins/diagnostics/RootUrlNotSetMonitor/message.jelly
  core/src/main/resources/jenkins/diagnostics/SecurityIsOffMonitor/message.jelly
  core/src/main/resources/jenkins/model/BuiltInNodeMigration/message.jelly
  core/src/main/resources/jenkins/security/RekeySecretAdminMonitor/message.groovy
  core/src/main/resources/jenkins/security/ResourceDomainRecommendation/message.groovy
  core/src/main/resources/jenkins/security/apitoken/ApiTokenPropertyDisabledDefaultAdministrativeMonitor/message.jelly
  core/src/main/resources/jenkins/security/apitoken/ApiTokenPropertyEnabledNewLegacyAdministrativeMonitor/message.jelly
  core/src/main/resources/jenkins/security/csrf/CSRFAdministrativeMonitor/message.jelly
Labels: ready-for-merge, web-ui, rfe

#7385 Update bundled script-security and junit versions
  war/pom.xml
Labels: ready-for-merge, dependencies

#7380 De-flake `TelemetryTest`
  test/src/test/java/jenkins/telemetry/TelemetryTest.java
Labels: ready-for-merge, skip-changelog

#7379 De-flake `CancelQuietDownCommandTest`
  test/src/test/java/hudson/cli/CancelQuietDownCommandTest.java
  test/src/test/java/hudson/cli/OnlineNodeCommandTest.java
Labels: ready-for-merge, skip-changelog

#7390 Ban spring-framework-bom 6.x onwards
  .github/dependabot.yml
Labels: skip-changelog

#7400 Remove unused .zip files from test resources
  test/src/test/resources/hudson/security/HudsonPrivateSecurityRealmTest/dataCompatibilityWith1_282.zip
  test/src/test/resources/hudson/tasks/maven-test-failure.zip
  test/src/test/resources/jenkins/security/Security2455Test/symlink.tar
  test/src/test/resources/jenkins/security/Security2455Test/testRemoteLocalUnzip/file.zip
  test/src/test/resources/jenkins/security/Security2455Test/unzipRemoteTest/file.zip
Labels: ready-for-merge, skip-changelog

#7374 Removed obsolete browser workarounds for `user-select` in `layout-mixins.less`
  war/src/main/js/widgets/layout-mixins.less
Labels: ready-for-merge, web-ui, skip-changelog

#7378 Synchronize agent protocol access
  core/src/main/java/hudson/security/GlobalSecurityConfiguration.java
  core/src/main/java/jenkins/model/Jenkins.java
Labels: ready-for-merge, bug

#7399 [JENKINS-70036] Weird animation artifacts in admin monitor popup
  core/src/main/resources/jenkins/management/AdministrativeMonitorsDecorator/resources.css
  core/src/main/resources/jenkins/management/AdministrativeMonitorsDecorator/resources.js
Labels: regression-fix, ready-for-merge, web-ui

#7367 Add plugin URL to 'systemInfo' view
  core/src/main/resources/jenkins/model/Jenkins/systemInfo.jelly
Labels: ready-for-merge, web-ui, rfe, security-approved

#7398 Introduce a high-level HTTP client API
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/ProxyConfiguration.java
  core/src/main/java/hudson/tools/ZipExtractionInstaller.java
  core/src/main/java/jenkins/UserAgentURLConnectionDecorator.java
  core/src/main/java/jenkins/telemetry/Telemetry.java
  test/src/test/java/jenkins/telemetry/TelemetryTest.java
Labels: ready-for-merge, developer

#7413 Remove deprecated Multijob plugin from setup wizard
  core/src/main/resources/jenkins/install/platform-plugins.json
Labels: ready-for-merge, rfe

#7376 [JENKINS-64151] Set a default file size rotation of AsyncPeriodicWork…
  core/src/main/java/hudson/model/AsyncAperiodicWork.java
  core/src/main/java/hudson/model/AsyncPeriodicWork.java
Labels: ready-for-merge, rfe

#7312 Remove Commons HttpClient 3.x
  bom/pom.xml
  core/pom.xml
  core/src/main/java/hudson/util/NoClientBindProtocolSocketFactory.java
  core/src/main/java/hudson/util/NoClientBindSSLProtocolSocketFactory.java
Labels: ready-for-merge, upgrade-guide-needed, removed, dependencies, java

#7412 [JENKINS-70103] `WeakHashMap` broken for looking up Jetty `Session` in WebSocket response
  core/src/main/java/jenkins/websocket/WebSockets.java
  websocket/jetty10/src/main/java/jenkins/websocket/Jetty10Provider.java
  websocket/jetty9/src/main/java/jenkins/websocket/Jetty9Provider.java
  websocket/spi/src/main/java/jenkins/websocket/Provider.java
Labels: ready-for-merge, bug

#7414 Remove WMI Windows Agents plugin from setup wizard
  core/src/main/resources/jenkins/install/platform-plugins.json
Labels: ready-for-merge, rfe

#7403 [JENKINS-70099] Make expand button same style with the input box
  war/src/main/less/base/style.less
Labels: ready-for-merge, web-ui, skip-changelog

#7435 Ban Spring Security 6.x and newer from Dependabot
  .github/dependabot.yml
Labels: skip-changelog

#7434 Use setup-java action to cache maven dependencies
  .github/workflows/publish-release-artifact.yml
Labels: skip-changelog

#7397 Stop using `infra.runATH`
  Jenkinsfile
  ath.sh
  essentials.yml
Labels: skip-changelog

#7429 chore(windows/jdk17): provide an aci agent for windows with jdk17
  Jenkinsfile
Labels: skip-changelog

#7438 Stop using `infra.runATH` (backport)
  Jenkinsfile
  ath.sh
  essentials.yml
Labels: into-lts

#7437 Remove unnecessary SpotBugs exclusions
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/cli/declarative/CLIRegisterer.java
  core/src/main/java/hudson/model/AbstractItem.java
  core/src/main/java/hudson/model/Executor.java
  core/src/main/java/hudson/model/ItemGroupMixIn.java
  core/src/main/java/hudson/model/Queue.java
  core/src/main/java/hudson/model/ResourceController.java
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/java/hudson/triggers/SafeTimerTask.java
  core/src/main/java/hudson/util/InterceptingProxy.java
  core/src/main/java/hudson/util/RobustReflectionConverter.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/model/Nodes.java
  core/src/main/java/jenkins/model/PeepholePermalink.java
  core/src/main/java/jenkins/model/TransientActionFactory.java
  core/src/main/java/jenkins/scm/RunWithSCM.java
  core/src/main/java/jenkins/security/ImpersonatingExecutorService.java
  core/src/main/java/jenkins/security/ImpersonatingScheduledExecutorService.java
  core/src/main/java/jenkins/security/SecurityContextExecutorService.java
  core/src/main/java/jenkins/util/AtmostOneTaskExecutor.java
  core/src/main/java/jenkins/util/ContextResettingExecutorService.java
  core/src/main/java/jenkins/util/ProgressiveRendering.java
  core/src/main/java/jenkins/util/io/PathRemover.java
  core/src/main/java/org/acegisecurity/providers/dao/AbstractUserDetailsAuthenticationProvider.java
  core/src/spotbugs/excludesFilter.xml
  war/src/main/java/executable/Main.java
Labels: ready-for-merge, skip-changelog

#7417 Set `SameSite=Lax` on screenResultion cookie
  core/src/main/resources/hudson/model/View/screen-resolution.js
Labels: ready-for-merge, web-ui

#7444 Fix typo in menu-debug.js
  war/src/main/webapp/scripts/yui/menu/menu-debug.js
Labels: skip-changelog

#6408 Replace YUI tooltips with Tippy.js
  core/src/main/java/org/jenkins/ui/icon/IconSet.java
  core/src/main/resources/hudson/model/Run/KeepLogBuildBadge/badge.jelly
  core/src/main/resources/hudson/scm/AbstractScmTagAction/badge.jelly
  core/src/main/resources/hudson/views/BuildButtonColumn/column.jelly
  core/src/main/resources/hudson/widgets/HistoryWidget/entry.jelly
  core/src/main/resources/jenkins/widgets/HistoryPageFilter/queue-items.jelly
  core/src/main/resources/lib/form/repeatableDeleteButton.jelly
  core/src/main/resources/lib/hudson/buildHealth.jelly
  core/src/main/resources/lib/hudson/queue.jelly
  core/src/main/resources/lib/layout/helpIcon.jelly
  core/src/main/resources/lib/layout/icon.jelly
  core/src/main/resources/lib/layout/svgIcon.jelly
  core/src/test/java/org/jenkins/ui/icon/IconSetJenkins68805Test.java
  core/src/test/java/org/jenkins/ui/icon/IconSetTest.java
  test/src/test/java/hudson/model/QueueTest.java
  test/src/test/java/hudson/model/RunTest.java
  test/src/test/java/hudson/scm/AbstractScmTagActionTest.java
  test/src/test/java/jenkins/security/Security2776Test.java
  test/src/test/java/jenkins/security/Security2779Test.java
  test/src/test/java/jenkins/security/Security2780Test.java
  test/src/test/java/lib/form/RepeatableTest.java
  test/src/test/java/lib/layout/SvgIconTest.java
  war/package.json
  war/src/main/js/app.js
  war/src/main/js/components/tooltips/index.js
  war/src/main/less/abstracts/theme.less
  war/src/main/less/base/layout-commons.less
  war/src/main/less/modules/table.less
  war/src/main/less/modules/tooltips.less
  war/src/main/webapp/scripts/hudson-behavior.js
  war/src/main/webapp/scripts/prototype.js
  war/yarn.lock
Labels: ready-for-merge, web-ui, rfe, squash-merge-me, security-approved

#7042 [JENKINS-68194] Delete `.disabled` file when uninstalling a plugin
  core/src/main/java/hudson/PluginWrapper.java
  test/src/test/java/hudson/PluginManagerTest.java
Labels: ready-for-merge, bug

#7449 De-flake `UserRestartTest`
  core/src/main/java/hudson/model/User.java
  test/src/test/java/hudson/model/UserRestartTest.java
Labels: ready-for-merge, skip-changelog

#7450 Increase timeout for `FreeStyleProjectTest#buildStabilityReports`
  test/src/test/java/hudson/model/FreeStyleProjectTest.java
Labels: ready-for-merge, skip-changelog

#7451 Remove test-only agent protocol definitions
  test/src/test/java/jenkins/AgentProtocolTest.java
  test/src/test/java/jenkins/TestJnlpSlaveAgentProtocol.java
  test/src/test/java/jenkins/TestJnlpSlaveAgentProtocol2.java
  test/src/test/java/jenkins/TestJnlpSlaveAgentProtocol3.java
  test/src/test/resources/jenkins/AgentProtocolTest/config.xml
Labels: ready-for-merge, skip-changelog

#7426 [JENKINS-70116] Use ionicons in 'threadDump' view for agents
  core/src/main/resources/jenkins/model/Jenkins/threadDump.jelly
Labels: ready-for-merge, web-ui, skip-changelog

#7445 De-flake `TelemetryTest`
  test/src/test/java/jenkins/telemetry/TelemetryTest.java
Labels: skip-changelog
