Repository jenkinsci/jenkins, pull requests merged in 2022-03, with the labels that each got.

#6318 Ignore Checkstyle 10.0 and later
  .github/dependabot.yml
  cli/src/main/java/hudson/cli/PlainCLIProtocol.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6324 Fix typo in datasource-debug.js
  war/src/main/webapp/scripts/yui/datasource/datasource-debug.js
Labels: skip-changelog

#6323 Remove JNR
  bom/pom.xml
  core/pom.xml
  core/src/main/java/hudson/os/PosixAPI.java
  core/src/main/java/hudson/os/PosixException.java
  core/src/main/java/hudson/util/jna/GNUCLibrary.java
  core/src/test/java/hudson/FilePathTest.java
Labels: ready-for-merge, upgrade-guide-needed, squash-merge-me, removed

#6325 Add annotations as documented
  core/src/main/java/hudson/model/LabelFinder.java
  core/src/main/java/hudson/model/LoadBalancer.java
  test/src/test/java/hudson/model/NodeTest.java
Labels: ready-for-merge, skip-changelog

#6315 [JENKINS-66446] Adjust class loading behavior of `JnlpSlaveRestarterInstaller`
  core/src/main/java/jenkins/slaves/restarter/JnlpSlaveRestarterInstaller.java
  test/src/test/java/jenkins/slaves/restarter/JnlpSlaveRestarterInstallerTest.java
Labels: ready-for-merge, bug, squash-merge-me

#6285 `node` tag is updated to say `built-in` instead of `builtin`
  core/src/main/resources/lib/hudson/node.jelly
Labels: ready-for-merge, skip-changelog

#6326 Apply Perltidy to `translation-tool.pl`
  .perltidyrc
  translation-tool.pl
Labels: ready-for-merge, skip-changelog

#6328 Bugfix/orphan pt_BR properties
  core/src/main/resources/hudson/slaves/JNLPLauncher/help_pt_BR.properties
  core/src/main/resources/jenkins/diagnostics/ControllerExecutorsAgents/message_pt_BR.properties
  core/src/main/resources/jenkins/diagnostics/ControllerExecutorsNoAgents/message_pt_BR.properties
  core/src/main/resources/jenkins/install/SetupWizard/authenticate-security-token_pt_BR.properties
  core/src/main/resources/jenkins/model/BuiltInNodeMigration/message_pt_BR.properties
  core/src/main/resources/jenkins/security/apitoken/LegacyApiTokenAdministrativeMonitor/message_pt_BR.properties
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6331 Update javadoc @since for API additions
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/lifecycle/Lifecycle.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/java/hudson/util/Protector.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/model/ModelObjectWithContextMenu.java
  core/src/main/java/jenkins/telemetry/Telemetry.java
  core/src/main/java/jenkins/util/Listeners.java
  core/src/main/java/jenkins/views/Header.java
Labels: ready-for-merge, skip-changelog

#6333 [JENKINS-41218] Use systemd for Linux installers
  core/src/main/java/hudson/WebAppMain.java
  core/src/main/java/hudson/lifecycle/Lifecycle.java
  core/src/main/java/hudson/lifecycle/SystemdLifecycle.java
  core/src/main/java/jenkins/model/Jenkins.java
Labels: ready-for-merge, upgrade-guide-needed, into-lts

#6317 Refactor `translation-tool.pl`
  translation-tool.pl
Labels: ready-for-merge, squash-merge-me, developer

#6229 Use modern icons in workspace view of a job
  core/src/main/java/hudson/model/DirectoryBrowserSupport.java
  core/src/main/java/org/jenkins/ui/icon/IconSet.java
  core/src/main/resources/hudson/model/DirectoryBrowserSupport/dir.jelly
  core/src/main/resources/hudson/model/Run/artifacts-index.jelly
  core/src/main/resources/lib/hudson/artifactList.jelly
  war/src/main/webapp/images/16x16/folder-error.gif
  war/src/main/webapp/images/16x16/folder-error.png
  war/src/main/webapp/images/16x16/text-error.gif
  war/src/main/webapp/images/16x16/text-error.png
  war/src/main/webapp/images/16x16/text.gif
  war/src/main/webapp/images/16x16/text.png
Labels: ready-for-merge, web-ui, rfe

#6291 Replace "unavailable" ionicon with a fixed size
  core/src/main/java/org/jenkins/ui/icon/IconSet.java
Labels: ready-for-merge, bug

#6341 JENKINS-67858 Place ionicons at the same height as their associated text
  war/src/main/less/base/style.less
Labels: regression-fix, ready-for-merge, bug, squash-merge-me

#6342 Stop overemphasizing console logs
  war/src/main/less/base/style.less
Labels: regression-fix, ready-for-merge, squash-merge-me

#6340 [JENKINS-67965] Fix checkbox focus state
  war/src/main/less/form/checkbox.less
Labels: ready-for-merge, bug

#6153 [JENKINS-59964] redirect to setOfflineCause
  core/src/main/resources/hudson/model/Computer/markOffline.jelly
Labels: ready-for-merge, web-ui, rfe

#6346 Update Brazilian Portuguese translations
  core/src/main/resources/hudson/Messages_pt_BR.properties
  core/src/main/resources/hudson/PluginManager/advanced_pt_BR.properties
  core/src/main/resources/hudson/PluginManager/available_pt_BR.properties
  core/src/main/resources/hudson/PluginManager/check_pt_BR.properties
  core/src/main/resources/hudson/PluginManager/index_pt_BR.properties
  core/src/main/resources/hudson/PluginManager/installed_pt_BR.properties
  core/src/main/resources/hudson/PluginManager/table_pt_BR.properties
  core/src/main/resources/hudson/cli/CLIAction/index_pt_BR.properties
  core/src/main/resources/hudson/cli/Messages_pt_BR.properties
  core/src/main/resources/hudson/diagnosis/OldDataMonitor/manage_pt_BR.properties
  core/src/main/resources/hudson/logging/Messages_pt_BR.properties
  core/src/main/resources/hudson/model/AbstractItem/noWorkspace_pt_BR.properties
  core/src/main/resources/hudson/model/BuildAuthorizationToken/config_pt_BR.properties
  core/src/main/resources/hudson/model/Computer/builds_pt_BR.properties
  core/src/main/resources/hudson/model/Computer/delete_pt_BR.properties
  core/src/main/resources/hudson/model/ComputerSet/index_pt_BR.properties
  core/src/main/resources/hudson/model/ComputerSet/new_pt_BR.properties
  core/src/main/resources/hudson/model/ComputerSet/sidepanel_pt_BR.properties
  core/src/main/resources/hudson/model/DirectoryBrowserSupport/dir_pt_BR.properties
  core/src/main/resources/hudson/model/FileParameterValue/value_pt_BR.properties
  core/src/main/resources/hudson/model/Job/buildTimeTrend_pt_BR.properties
  core/src/main/resources/hudson/model/Job/configure_pt_BR.properties
  core/src/main/resources/hudson/model/LoadStatistics/main_pt_BR.properties
  core/src/main/resources/hudson/model/Messages_pt_BR.properties
  core/src/main/resources/hudson/model/Run/delete_pt_BR.properties
  core/src/main/resources/hudson/model/StringParameterDefinition/config_pt_BR.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message_pt_BR.properties
  core/src/main/resources/hudson/model/User/index_pt_BR.properties
  core/src/main/resources/hudson/model/View/AsynchPeople/index_pt_BR.properties
  core/src/main/resources/hudson/model/View/configure_pt_BR.properties
  core/src/main/resources/hudson/model/View/delete_pt_BR.properties
  core/src/main/resources/hudson/model/View/newJob_pt_BR.properties
  core/src/main/resources/hudson/node_monitors/MonitorMarkedNodeOffline/message_pt_BR.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/signup_pt_BR.properties
  core/src/main/resources/hudson/tools/Messages_pt_BR.properties
  core/src/main/resources/hudson/triggers/Messages_pt_BR.properties
  core/src/main/resources/hudson/views/Messages_pt_BR.properties
  core/src/main/resources/hudson/views/WeatherColumn/columnHeader_pt_BR.properties
  core/src/main/resources/jenkins/security/Messages_pt_BR.properties
  core/src/main/resources/jenkins/triggers/Messages_pt_BR.properties
  core/src/main/resources/jenkins/triggers/ReverseBuildTrigger/config_pt_BR.properties
  core/src/main/resources/lib/hudson/artifactList_pt_BR.properties
  core/src/main/resources/lib/hudson/buildCaption_pt_BR.properties
  core/src/main/resources/lib/hudson/buildListTable_pt_BR.properties
  core/src/main/resources/lib/hudson/executors_pt_BR.properties
  core/src/main/resources/lib/hudson/iconSize_pt_BR.properties
  core/src/main/resources/lib/hudson/newFromList/form_pt_BR.properties
  core/src/main/resources/lib/hudson/node_pt_BR.properties
  core/src/main/resources/lib/hudson/queue_pt_BR.properties
  core/src/main/resources/lib/hudson/scriptConsole_pt_BR.properties
  core/src/main/resources/lib/layout/layout_pt_BR.properties
  core/src/main/resources/lib/layout/main-panel_pt_BR.properties
Labels: ready-for-merge, skip-changelog, localization

#6334 [JENKINS-67602] Skip corrupted fingerprint files
  core/src/main/java/hudson/model/Fingerprint.java
Labels: ready-for-merge, bug, squash-merge-me

#6344 Don't cut off letters on the changeset view
  war/src/main/less/base/layout-commons.less
Labels: ready-for-merge, web-ui, bug

#6332 Search for `@since` only in specific source files
  core/src/main/resources/lib/layout/svgIcon.jelly
  update-since-todo.sh
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6345 Deprecate `PosixException` in favor of `IOException`
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/os/PosixException.java
  core/src/main/java/hudson/util/IOUtils.java
  core/src/main/java/hudson/util/io/TarArchiver.java
  core/src/main/java/jenkins/util/VirtualFile.java
Labels: ready-for-merge, squash-merge-me, developer

#6343 Improve appearance of the changeset box (regression in 2.335)
  war/src/main/less/base/style.less
Labels: regression-fix, ready-for-merge, bug

#6356 [JENKINS-67992] Add `Add-Opens` entry to `MANIFEST.MF`
  war/pom.xml
Labels: ready-for-merge, rfe, squash-merge-me

#5928 Update winstone to 5.24
  war/pom.xml
Labels: ready-for-merge, dependencies

#6359 [JENKINS-67995] `SystemdLifecycle` logging "Operation not permitted" calling `sd_notify(3)` during startup
  core/src/main/java/hudson/lifecycle/SystemdLifecycle.java
Labels: regression-fix, ready-for-merge, squash-merge-me

#6335 Minor improvements in fixing deprecation warnings and removed obsolete throws
  test/src/test/java/jenkins/security/BasicHeaderApiTokenAuthenticatorTest.java
  test/src/test/java/jenkins/security/BasicHeaderProcessorTest.java
  test/src/test/java/jenkins/security/ResourceDomainTest.java
  test/src/test/java/jenkins/security/Security218Test.java
  test/src/test/java/jenkins/security/Security380Test.java
  test/src/test/java/jenkins/security/Security857Test.java
  test/src/test/java/jenkins/security/SecurityContextExecutorServiceTest.java
  test/src/test/java/jenkins/security/UserDetailsCacheTest.java
  test/src/test/java/jenkins/security/apitoken/ApiTokenPropertyConfigurationTest.java
  test/src/test/java/jenkins/security/seed/UserSeedChangeListenerTest.java
  test/src/test/java/jenkins/security/seed/UserSeedPropertyTest.java
  test/src/test/java/jenkins/security/stapler/DoActionFilterTest.java
  test/src/test/java/jenkins/security/stapler/DynamicTest.java
  test/src/test/java/jenkins/security/stapler/GetterMethodFilterTest.java
  test/src/test/java/jenkins/security/stapler/StaticRoutingDecisionProvider2Test.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6357 Sort dependencies
  bom/pom.xml
  cli/pom.xml
  core/pom.xml
  pom.xml
  test/pom.xml
  war/pom.xml
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6365 Remove `-Dfile.encoding=UTF-8` from Surefire JVM arguments
  test/pom.xml
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6362 Miscellaneous code cleanup
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/tasks/Shell.java
  core/src/main/java/hudson/util/PackedMap.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/model/lazy/LazyLoadRunMapEntrySet.java
  core/src/test/java/hudson/ChannelRule.java
  core/src/test/java/hudson/util/ConsistentHashTest.java
  core/src/test/java/jenkins/org/apache/commons/validator/routines/DomainValidatorTest.java
  core/src/test/java/jenkins/org/apache/commons/validator/routines/UrlValidatorTest.java
  test/src/test/java/hudson/model/QueueTest.java
  test/src/test/java/hudson/model/ViewTest.java
  test/src/test/java/hudson/security/LoginTest.java
  test/src/test/java/lib/form/RowVisibilityGroupTest.java
  test/src/test/java/lib/layout/RenderOnDemandTest.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6366 Remove unneeded Javadoc workarounds
  pom.xml
Labels: ready-for-merge, skip-changelog

#6360 Add russian localization for Java 11 monitor
  core/src/main/resources/jenkins/monitor/JavaVersionRecommendationAdminMonitor/message_ru.properties
Labels: ready-for-merge, localization, squash-merge-me

#6367 Remove `japicmp`
  .github/dependabot.yml
  Jenkinsfile
  core/pom.xml
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6369 Remove obsolete workaround for SUREFIRE-1588
  test/pom.xml
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6370 Restore original method signature of `CLICommand#getClientCharset`
  core/src/main/java/hudson/cli/CLICommand.java
  core/src/main/java/hudson/cli/GroovyshCommand.java
  core/src/main/java/hudson/cli/ListChangesCommand.java
  core/src/test/java/hudson/cli/ListJobsCommandTest.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6350 JENKINS-67953 Unavailable plugin label is not themeable
  war/src/main/less/abstracts/theme.less
  war/src/main/less/pages/plugin-manager.less
Labels: ready-for-merge, rfe

#6351 [JENKINS-67713] Align Polling Log "View as plain text" link with sidepanel
  core/src/main/resources/hudson/triggers/SCMTrigger/BuildAction/index.jelly
  core/src/main/resources/lib/hudson/actions.jelly
  core/src/main/resources/lib/layout/rightspace.jelly
Labels: ready-for-merge, web-ui, bug

#6373 Assumptions in `XStream2EncodingTest` are not correctly implemented
  core/src/test/java/hudson/util/XStream2EncodingTest.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6374 Remove `NodeListTest`
  core/src/test/java/hudson/slaves/NodeListTest.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6375 Remove redundant profile
  pom.xml
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6363 Don't overflow on longer build names
  war/src/main/less/base/layout-commons.less
Labels: ready-for-merge, skip-changelog

#6377 Document <l:progressAnimation> tag
  core/src/main/resources/lib/layout/progressAnimation.jelly
Labels: ready-for-merge, skip-changelog

#6378 Eliminate mocks from `ViewTest`
  test/src/test/java/hudson/model/ViewTest.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6084 [JENKINS-67396] Update link and breadcrumb dropdowns
  core/src/main/java/hudson/console/ModelHyperlinkNote.java
  core/src/main/java/jenkins/model/ModelObjectWithContextMenu.java
  core/src/main/resources/hudson/model/Cause/UpstreamCause/description.properties
  core/src/main/resources/hudson/model/Cause/UpstreamCause/description_bg.properties
  core/src/main/resources/hudson/model/Cause/UpstreamCause/description_cs.properties
  core/src/main/resources/hudson/model/Cause/UpstreamCause/description_da.properties
  core/src/main/resources/hudson/model/Cause/UpstreamCause/description_de.properties
  core/src/main/resources/hudson/model/Cause/UpstreamCause/description_es.properties
  core/src/main/resources/hudson/model/Cause/UpstreamCause/description_fi.properties
  core/src/main/resources/hudson/model/Cause/UpstreamCause/description_fr.properties
  core/src/main/resources/hudson/model/Cause/UpstreamCause/description_it.properties
  core/src/main/resources/hudson/model/Cause/UpstreamCause/description_ja.properties
  core/src/main/resources/hudson/model/Cause/UpstreamCause/description_lv.properties
  core/src/main/resources/hudson/model/Cause/UpstreamCause/description_nl.properties
  core/src/main/resources/hudson/model/Cause/UpstreamCause/description_pl.properties
  core/src/main/resources/hudson/model/Cause/UpstreamCause/description_pt_BR.properties
  core/src/main/resources/hudson/model/Cause/UpstreamCause/description_ru.properties
  core/src/main/resources/hudson/model/Cause/UpstreamCause/description_sk.properties
  core/src/main/resources/hudson/model/Cause/UpstreamCause/description_sr.properties
  core/src/main/resources/hudson/model/Cause/UpstreamCause/description_sv_SE.properties
  core/src/main/resources/hudson/model/Cause/UpstreamCause/description_uk.properties
  core/src/main/resources/hudson/model/Cause/UpstreamCause/description_zh_TW.properties
  core/src/main/resources/hudson/views/BuildButtonColumn/column.jelly
  core/src/main/resources/hudson/views/LastFailureColumn/column.jelly
  core/src/main/resources/hudson/views/LastSuccessColumn/column.jelly
  core/src/main/resources/hudson/widgets/HistoryWidget/entry.jelly
  core/src/main/resources/jenkins/views/JenkinsHeader/headerContent.jelly
  core/src/main/resources/lib/form/breadcrumb-config-outline/init.js
  core/src/main/resources/lib/hudson/buildListTable.jelly
  core/src/main/resources/lib/hudson/executors.jelly
  core/src/main/resources/lib/layout/breadcrumb.jelly
  core/src/main/resources/lib/layout/breadcrumbBar.jelly
  core/src/main/resources/lib/layout/breadcrumbs.css
  core/src/main/resources/lib/layout/breadcrumbs.js
  core/src/main/resources/lib/layout/layout.jelly
  war/src/main/js/util/page.js
  war/src/main/less/base-styles-v2.less
  war/src/main/less/base/layout-commons.less
  war/src/main/less/base/style.less
  war/src/main/less/modules/breadcrumbs.less
  war/src/main/less/modules/page-header.less
  war/src/main/less/modules/side-panel-widgets.less
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, web-ui, rfe, squash-merge-me

#6383 Stop serializing locks in `NodeProvisionerTest`
  test/src/test/java/hudson/slaves/NodeProvisionerTest.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6384 Support Java 17 in `Security637Test`
  test/src/test/java/jenkins/security/Security637Test.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6382 Fix bad encoding of security warnings in French
  core/src/main/resources/jenkins/security/UpdateSiteWarningsMonitor/message_fr.properties
Labels: ready-for-merge, bug, squash-merge-me

#6337 Add getter for temp offline cause of nodes for plugins
  core/src/main/java/hudson/model/Node.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6385 [JENKINS-67602] Recover from fingerprint corruption earlier
  core/src/main/java/hudson/model/Fingerprint.java
  core/src/main/java/jenkins/fingerprints/FileFingerprintStorage.java
Labels: ready-for-merge, skip-changelog, bug, squash-merge-me

#6364 Add Java 17 to build/test matrix
  Jenkinsfile
  core/pom.xml
  pom.xml
  test/pom.xml
Labels: ready-for-merge, rfe, squash-merge-me

#6394 Add more Korean translation (improve)
  core/src/main/resources/jenkins/model/Messages_ko.properties
  core/src/main/resources/jenkins/security/UpdateSiteWarningsMonitor/message_ko.properties
Labels: ready-for-merge, localization, rfe, squash-merge-me

#6396 Fill in `@since todo` annotations for the past releases
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/Util.java
  core/src/main/java/hudson/logging/LogRecorder.java
  core/src/main/java/hudson/logging/LogRecorderManager.java
  core/src/main/java/hudson/model/Node.java
  core/src/main/java/jenkins/ClassLoaderReflectionToolkit.java
  core/src/main/java/jenkins/model/ModelObjectWithContextMenu.java
Labels: ready-for-merge, skip-changelog

#6400 [JENKINS-67967] "View build information" is not readonly
  core/src/main/resources/hudson/model/Run/configure.jelly
Labels: ready-for-merge, rfe, bug

#5836 [JENKINS-65928-2] Job trend page use previous icon color for trend graph
  core/src/main/java/hudson/model/Job.java
  core/src/main/java/hudson/util/ColorPalette.java
  core/src/test/java/hudson/model/BallColorTest.java
Labels: ready-for-merge, web-ui, rfe

#6403 Don't show delete build button if build is marked to be kept
  core/src/main/resources/hudson/model/Run/delete.jelly
Labels: ready-for-merge, rfe

#6406 Use Eclipse Temurin, not AdoptOpenJDK in publish artifact action
  .github/workflows/publish-release-artifact.yml
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6397 Update appearance of help button component
  core/src/main/resources/hudson/logging/LogRecorder/configure.jelly
  core/src/main/resources/hudson/logging/LogRecorderManager/index.jelly
  core/src/main/resources/hudson/logging/LogRecorderManager/levels.jelly
  core/src/main/resources/jenkins/model/Jenkins/projectRelationship.jelly
  core/src/main/resources/lib/form/helpLink.jelly
  core/src/main/resources/lib/hudson/help.jelly
  core/src/main/resources/lib/layout/icon.jelly
  war/src/main/less/form/layout.less
  war/src/main/less/modules/app-bar.less
  war/src/main/resources/images/symbols/help-circle.svg
Labels: ready-for-merge, web-ui

#6410 Update SCM URLs
  pom.xml
Labels: skip-changelog, squash-merge-me

#6392 Remove `java.util.concurrent` from `--add-opens` list
  core/pom.xml
  test/pom.xml
  war/pom.xml
Labels: ready-for-merge, skip-changelog

#6395 JENKINS-68137 - Enable custom icon symbols for plugins
  core/src/main/java/hudson/Functions.java
  core/src/main/java/org/jenkins/ui/icon/IconSet.java
  core/src/main/resources/lib/hudson/actions.jelly
  core/src/main/resources/lib/hudson/ballColorTd.jelly
  core/src/main/resources/lib/layout/icon.jelly
  core/src/test/java/hudson/FunctionsTest.java
  core/src/test/java/org/jenkins/ui/icon/IconSetTest.java
  test/src/test/java/lib/layout/IconTest.java
Labels: ready-for-merge, web-ui, rfe

#6101 [JENKINS-67237] BuildTrigger waits until the dependency graph has been updated
  core/src/main/java/hudson/tasks/BuildTrigger.java
  core/src/main/java/jenkins/model/Jenkins.java
  test/src/test/java/jenkins/model/JenkinsFutureDependencyGraphTest.java
Labels: ready-for-merge, bug

#6413 Adds PR labels definitions to contribution guide
  CONTRIBUTING.md
  docs/MAINTAINERS.adoc
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6419 Remove mention of how to parse with Python < 2.6
  core/src/main/resources/hudson/model/Api/index.jelly
Labels: ready-for-merge, skip-changelog
