Repository jenkinsci/jenkins, pull requests merged in 2022-10, with the labels that each got.

#7161 Update ATH docker image to 5439.vb_929a_7e53585
  essentials.yml
Labels: ready-for-merge, skip-changelog, dependencies

#7199 De-flake `AbstractItem2Test`
  test/src/test/java/hudson/model/AbstractItem2Test.java
Labels: ready-for-merge, skip-changelog, hacktoberfest-accepted

#7207 Update ATH docker image to 5450.v1cfec809d04b
  essentials.yml
Labels: ready-for-merge, skip-changelog, dependencies

#7206 Migrate `NodeProvisionerTest` to `RealJenkinsRule`
  test/src/test/java/hudson/slaves/NodeProvisionerTest.java
Labels: ready-for-merge, skip-changelog, hacktoberfest-accepted

#7185 Improve error message when running on unsupported Java version
  war/src/main/java/executable/Main.java
  war/src/test/java/executable/MainTest.java
Labels: ready-for-merge, rfe

#7182 Use 'jenkins-button' for session termination
  core/src/main/resources/jenkins/security/seed/UserSeedProperty/config.jelly
Labels: ready-for-merge, web-ui, rfe, security-approved

#7121 [JENKINS-69537] Collapsing build history widget throws error
  core/src/main/resources/hudson/widgets/HistoryWidget/index.jelly
  war/src/main/js/filter-build-history.js
Labels: ready-for-merge, web-ui, skip-changelog, security-approved

#6886 [JENKINS-69032] Plugin manager update site URL can be saved empty
  core/src/main/java/hudson/PluginManager.java
  core/src/main/resources/hudson/Messages.properties
  core/src/main/resources/hudson/Messages_zh_TW.properties
  core/src/main/resources/hudson/PluginManager/_updateSite.js
  core/src/main/resources/hudson/PluginManager/advanced.jelly
  core/src/main/resources/hudson/PluginManager/advanced_zh_TW.properties
Labels: ready-for-merge, web-ui, rfe, security-approved

#7196 [JENKINS-69602] Model link chevron is not in center in user build cause on main build page
  war/src/main/less/modules/breadcrumbs.less
Labels: ready-for-merge, web-ui, skip-changelog, hacktoberfest-accepted

#7183 Replace plugin manager's 'Check now' button with 'jenkins-button'
  core/src/main/resources/hudson/PluginManager/check.jelly
Labels: ready-for-merge, web-ui, rfe, security-approved

#7210 Consolidate node provisioning tests
  test/src/test/java/hudson/model/QueueTest.java
  test/src/test/java/hudson/slaves/NodeProvisionerTest.java
Labels: ready-for-merge, skip-changelog

#7216 Improve `OldDataMonitor` icon
  core/src/main/java/hudson/diagnosis/OldDataMonitor.java
  war/src/main/resources/images/symbols/trash-bin.svg
Labels: ready-for-merge, web-ui, rfe, hacktoberfest-accepted

#7219 Do not rerun failing tests
  test/pom.xml
Labels: ready-for-merge, skip-changelog

#7218 Add "Testing done" section to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready-for-merge, skip-changelog

#7195 Ping asynchronously in `Jetty10Provider`
  websocket/jetty10/src/main/java/jenkins/websocket/Jetty10Provider.java
Labels: regression-fix, ready-for-merge, hacktoberfest-accepted

#7217 Improve log record icon
  core/src/main/java/jenkins/management/SystemLogLink.java
  core/src/main/resources/hudson/logging/LogRecorder/sidepanel.jelly
  war/src/main/resources/images/symbols/journal.svg
Labels: ready-for-merge, web-ui, rfe, hacktoberfest-accepted

#7220 Retry build on agent error
  Jenkinsfile
Labels: ready-for-merge, skip-changelog

#7239 Fill in since annotations
  core/src/main/java/hudson/model/AbstractBuild.java
  core/src/main/java/jenkins/model/ProjectNamingStrategy.java
  core/src/main/java/jenkins/triggers/TriggeredItem.java
  core/src/main/resources/lib/layout/search-bar.jelly
Labels: ready-for-merge, skip-changelog

#7246 Document missing options
  war/src/main/java/executable/Main.java
Labels: ready-for-merge, rfe, hacktoberfest-accepted

#7247 Run `yarn dedupe`
  war/yarn.lock
Labels: skip-changelog

#7205 [JENKINS-69714] Use new jenkins-table for slow trigger admin monitor
  core/src/main/resources/hudson/triggers/SlowTriggerAdminMonitor/message.groovy
Labels: ready-for-merge, web-ui, rfe, hacktoberfest-accepted

#7248 Replace HTML character references with Unicode in `.properties` files
  core/src/main/resources/hudson/model/AbstractProject/wipeOutWorkspaceBlocked_fr.properties
  core/src/main/resources/hudson/model/Messages_da.properties
  core/src/main/resources/hudson/model/Messages_de.properties
  core/src/main/resources/hudson/model/Messages_fr.properties
  core/src/main/resources/hudson/model/Messages_ja.properties
  core/src/main/resources/hudson/scm/Messages_fr.properties
  core/src/main/resources/hudson/slaves/DumbSlave/newInstanceDetail.properties
  core/src/main/resources/hudson/slaves/DumbSlave/newInstanceDetail_bg.properties
  core/src/main/resources/hudson/slaves/DumbSlave/newInstanceDetail_pl.properties
  core/src/main/resources/hudson/slaves/DumbSlave/newInstanceDetail_pt_BR.properties
  core/src/main/resources/hudson/slaves/DumbSlave/newInstanceDetail_sr.properties
  core/src/main/resources/hudson/tasks/Maven/help_pt_BR.properties
  core/src/main/resources/hudson/tasks/Maven/help_tr.properties
  core/src/main/resources/jenkins/model/Messages_da.properties
  core/src/main/resources/jenkins/model/Messages_fr.properties
  core/src/main/resources/jenkins/model/Messages_ja.properties
Labels: ready-for-merge, skip-changelog, localization

#7250 Correctly encode pound sign in `sortable.js`
  war/src/main/webapp/scripts/sortable.js
Labels: regression-fix, ready-for-merge, web-ui

#7251 Add debug logs to `NodeProvisionerTest`
  test/src/test/java/hudson/slaves/NodeProvisionerTest.java
Labels: ready-for-merge, skip-changelog

#6951 Allow Formchecker to check more than 1 thing at a time
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, rfe, squash-merge-me, security-approved

#7257 Backporting for 2.361.3
  core/src/main/java/hudson/console/ModelHyperlinkNote.java
  core/src/main/java/hudson/model/AbstractCIBase.java
  core/src/main/java/jenkins/model/Jenkins.java
  war/src/main/less/modules/table.less
Labels: into-lts

#7249 Fix corrupted Brazilian Portuguese translations
  core/src/main/resources/hudson/diagnosis/HudsonHomeDiskUsageMonitor/index_pt_BR.properties
  core/src/main/resources/hudson/diagnosis/MemoryUsageMonitor/index_pt_BR.properties
  core/src/main/resources/hudson/model/AbstractProject/configure-common_pt_BR.properties
  core/src/main/resources/hudson/tasks/Fingerprinter/help-targets_pt_BR.html
Labels: ready-for-merge, skip-changelog, localization

#7092 Remove view-configuration checkbox overflow
  war/src/main/less/base/style.less
Labels: ready-for-merge, web-ui, skip-changelog

#7191 Use a jenkins-button at project creation page
  core/src/main/resources/hudson/model/ListView/newJobButtonBar.jelly
  core/src/main/resources/hudson/model/View/newJobButtonBar.jelly
  war/src/main/less/modules/buttons.less
Labels: ready-for-merge, web-ui, skip-changelog, security-approved

#7252 Use `InboundAgentRule` in `ResponseTimeMonitorTest#doNotDisconnectBeforeLaunched`
  test/src/test/java/hudson/node_monitors/ResponseTimeMonitorTest.java
Labels: ready-for-merge, skip-changelog

#7091 Clarify safe restart won't wait for Pipeline jobs
  core/src/main/resources/jenkins/model/Jenkins/_api.jelly
  core/src/main/resources/jenkins/model/Jenkins/_safeRestart.jelly
Labels: ready-for-merge, rfe

#7238 [JENKINS-68100] Support updating @Deprecated and @RestrictedSince TODOS
  update-since-todo.py
Labels: ready-for-merge, skip-changelog, hacktoberfest-accepted

#7242 Minor refactoring - replaced deprecated methods around `dumbSlave()`
  test/src/test/java/hudson/model/FreeStyleProjectTest.java
  test/src/test/java/hudson/model/labels/LabelExpressionTest.java
Labels: ready-for-merge, skip-changelog

#7261 Wait for inbound agent to go offline in tests
  test/pom.xml
  test/src/test/java/hudson/bugs/JnlpAccessWithSecuredHudsonTest.java
  test/src/test/java/hudson/slaves/JNLPLauncherRealTest.java
  test/src/test/java/jenkins/agents/WebSocketAgentsTest.java
  test/src/test/java/jenkins/security/Security218Test.java
  test/src/test/java/jenkins/slaves/restarter/JnlpSlaveRestarterInstallerTest.java
Labels: ready-for-merge, skip-changelog

#7264 Address `set-output` deprecation
  .github/workflows/publish-release-artifact.yml
Labels: ready-for-merge, skip-changelog

#7235 [JENKINS-69812] Make help button and dropdown list button be aligned
  war/src/main/less/form/layout.less
Labels: regression-fix, ready-for-merge, web-ui

#7269 UserProperty could be null (quality warning)
  core/src/main/java/hudson/model/User.java
Labels: ready-for-merge, skip-changelog

#7270 Unable to serialize `AtomicBoolean` on Java 17
  core/src/main/java/hudson/util/XStream2.java
  core/src/main/java/jenkins/util/xstream/AtomicBooleanConverter.java
  core/src/test/java/jenkins/util/xstream/AtomicBooleanFieldsTest.java
Labels: ready-for-merge, bug

#7140 [JENKINS-69637] Fix ClassCastException when param list is empty
  core/src/main/java/hudson/model/ParametersDefinitionProperty.java
  test/src/test/java/hudson/model/ParametersTest.java
Labels: ready-for-merge, bug

#7208 [JENKINS-65124] Update weather icons
  core/src/main/java/org/jenkins/ui/icon/IconSet.java
  core/src/main/resources/jenkins/model/Jenkins/legend.jelly
  core/src/main/resources/jenkins/model/Jenkins/legend.properties
  core/src/main/resources/lib/hudson/buildHealth.jelly
  war/src/main/less/abstracts/theme.less
  war/src/main/less/base/style.less
  war/src/main/less/modules/icons.less
  war/src/main/less/modules/table.less
  war/src/main/less/pages/icon-legend.less
  war/src/main/less/styles.less
  war/src/main/resources/images/symbols/weather-icon-health-00to19.svg
  war/src/main/resources/images/symbols/weather-icon-health-20to39.svg
  war/src/main/resources/images/symbols/weather-icon-health-40to59.svg
  war/src/main/resources/images/symbols/weather-icon-health-60to79.svg
  war/src/main/resources/images/symbols/weather-icon-health-80plus.svg
  war/src/main/webapp/images/build-status/build-status-sprite.svg
Labels: ready-for-merge, web-ui, major-rfe, hacktoberfest-accepted, security-approved

#7049 Update the design of notifications
  core/src/main/java/hudson/util/FormApply.java
  core/src/main/resources/lib/layout/layout.jelly
  war/src/main/js/app.js
  war/src/main/js/components/notifications/index.js
  war/src/main/js/util/symbols.js
  war/src/main/less/abstracts/theme.less
  war/src/main/less/base/style.less
  war/src/main/less/modules/notifications.less
  war/src/main/less/styles.less
  war/src/main/webapp/scripts/hudson-behavior.js
  war/webpack.config.js
Labels: ready-for-merge, web-ui, rfe, security-approved

#7271 Small terminology update
  core/src/main/resources/jenkins/model/Jenkins/systemInfo.properties
Labels: ready-for-merge, skip-changelog

#7283 Upgrade ATH from 5450.v1cfec809d04b to 5458.v911b_2f0818ee
  essentials.yml
Labels: ready-for-merge, skip-changelog, dependencies, java

#7155 [JENKINS-69689] Table columns shadow is overlapping with other button shadow
  war/src/main/less/modules/table.less
Labels: ready-for-merge, web-ui, bug

#7184 Use a destructive button for deleting API tokens
  core/src/main/resources/jenkins/security/ApiTokenProperty/config.jelly
Labels: ready-for-merge, web-ui, skip-changelog, hacktoberfest-accepted, security-approved

#6912 Improve breadcrumb bar accessibility
  core/src/main/resources/hudson/model/Job/configure.jelly
  core/src/main/resources/lib/layout/breadcrumb.jelly
  core/src/main/resources/lib/layout/breadcrumbBar.jelly
  core/src/main/resources/lib/layout/layout.jelly
  test/src/test/java/hudson/model/HudsonTest.java
  war/src/main/js/util/page.js
  war/src/main/less/abstracts/theme.less
  war/src/main/less/base/layout-commons.less
  war/src/main/less/base/style.less
  war/src/main/less/modules/breadcrumbs.less
  war/src/main/less/modules/page-footer.less
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, web-ui, major-rfe, squash-merge-me, security-approved

#7197 Update design of Manage Users page
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/_entryForm.jelly
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/_entryFormPage.jelly
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/_entryFormPage/resources.css
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/index.jelly
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/sidepanel.jelly
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/sidepanel_bg.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/sidepanel_da.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/sidepanel_de.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/sidepanel_es.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/sidepanel_fr.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/sidepanel_hu.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/sidepanel_it.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/sidepanel_ja.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/sidepanel_ko.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/sidepanel_nb_NO.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/sidepanel_nl.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/sidepanel_pl.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/sidepanel_pt_BR.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/sidepanel_pt_PT.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/sidepanel_ru.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/sidepanel_sk.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/sidepanel_sr.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/sidepanel_sv_SE.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/sidepanel_tr.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/sidepanel_uk.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/sidepanel_zh_TW.properties
  war/src/main/less/abstracts/theme.less
  war/src/main/less/base/layout-commons.less
  war/src/main/less/base/spacing.less
Labels: ready-for-merge, web-ui, rfe, hacktoberfest-accepted, security-approved

#7281 Do not print at `INFO` every time `AsyncPeriodicWork` starts/stops
  core/src/main/java/hudson/model/AsyncAperiodicWork.java
  core/src/main/java/hudson/model/AsyncPeriodicWork.java
Labels: ready-for-merge, rfe

#7275 Update bundled script-security and workflow-support plugins
  war/pom.xml
Labels: ready-for-merge, dependencies, java

#7277 Align HTTP keep-alive timeout with Jetty default
  pom.xml
Labels: ready-for-merge, bug, upgrade-guide-needed, removed

#7289 Use `setText` rather than `type` in `ViewDescriptorTest`
  test/src/test/java/hudson/model/ViewDescriptorTest.java
Labels: ready-for-merge, skip-changelog

#7291 Loosen assertion in `NodeProvisionerTest` to account for conservative estimation in production code
  test/src/test/java/hudson/slaves/NodeProvisionerTest.java
Labels: ready-for-merge, skip-changelog

#7292 Ignore `BuildKeepsRunningWhenFaultySubTasksTest`
  test/src/test/java/hudson/model/queue/BuildKeepsRunningWhenFaultySubTasksTest.java
Labels: ready-for-merge, skip-changelog

#7278 Remove optional block scrolling
  core/src/main/resources/lib/form/repeatable/repeatable.js
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, web-ui, skip-changelog, hacktoberfest-accepted, security-approved

#7243 Removed deprecated ApiTokenTestHelper
  test/src/test/java/hudson/bugs/JnlpAccessWithSecuredHudsonTest.java
  test/src/test/java/hudson/cli/CLIActionTest.java
  test/src/test/java/hudson/cli/CLIEnvVarTest.java
  test/src/test/java/hudson/diagnosis/HudsonHomeDiskUsageMonitorTest.java
  test/src/test/java/hudson/model/ItemsTest.java
  test/src/test/java/hudson/model/JobTest.java
  test/src/test/java/hudson/model/PasswordParameterDefinitionTest.java
  test/src/test/java/hudson/model/QueueTest.java
  test/src/test/java/hudson/model/UserTest.java
  test/src/test/java/hudson/security/HudsonPrivateSecurityRealmTest.java
  test/src/test/java/hudson/security/LoginTest.java
  test/src/test/java/jenkins/model/JenkinsTest.java
  test/src/test/java/jenkins/security/ApiTokenPropertyTest.java
  test/src/test/java/jenkins/security/BasicHeaderProcessorTest.java
  test/src/test/java/jenkins/security/apitoken/ApiTokenTestHelper.java
  test/src/test/java/lib/form/PasswordTest.java
Labels: ready-for-merge, skip-changelog

#7273 [JENKINS-69850]: Queue.maintain() does no longer trigger an infinite recursive loop after loading a queue from xml
  core/src/main/java/hudson/model/AbstractProject.java
  core/src/main/java/hudson/model/Queue.java
  test/src/test/java/hudson/model/QueueTest.java
Labels: regression-fix, ready-for-merge

#7304 Improve negative tests in `CronTabTest` and `LabelExpressionTest`
  core/src/test/java/hudson/scheduler/CronTabTest.java
  test/src/test/java/hudson/model/labels/LabelExpressionTest.java
Labels: skip-changelog

#7310 Fix a small typo and some grammar mistakes
  core/src/main/resources/hudson/PluginManager/table_pt_BR.properties
Labels: ready-for-merge, skip-changelog

#7307 Update Node.js from 16.x to 18.x
  renovate.json
  war/pom.xml
Labels: ready-for-merge, dependencies

#7203 Update submit buttons to use `.jenkins-button` classes
  core/src/main/resources/hudson/model/AbstractItem/delete.jelly
  core/src/main/resources/hudson/model/Computer/delete.jelly
  core/src/main/resources/hudson/model/ComputerSet/_new.jelly
  core/src/main/resources/hudson/model/Run/confirmDelete.jelly
  core/src/main/resources/hudson/model/Run/logKeep.jelly
  core/src/main/resources/hudson/model/View/delete.jelly
  core/src/main/resources/jenkins/management/ShutdownLink/index.groovy
  core/src/main/resources/jenkins/model/Jenkins/MasterComputer/configure.jelly
  core/src/main/resources/lib/form/apply.jelly
  core/src/main/resources/lib/form/apply/apply.js
  core/src/main/resources/lib/form/bottomButtonBar.jelly
  core/src/main/resources/lib/form/submit.jelly
  core/src/main/resources/lib/hudson/newFromList/form.jelly
  core/src/main/resources/lib/hudson/project/makeDisabled.jelly
  war/src/main/less/modules/buttons.less
  war/src/main/less/pages/manage-jenkins.less
Labels: ready-for-merge, web-ui, rfe, hacktoberfest-accepted, security-approved

#7293 [JENKINS-68652] Update ANTLR2 to ANTLR4
  bom/pom.xml
  core/pom.xml
  core/src/main/antlr4/hudson/model/labels/LabelExpressionLexer.g4
  core/src/main/antlr4/hudson/model/labels/LabelExpressionParser.g4
  core/src/main/antlr4/hudson/scheduler/CrontabLexer.g4
  core/src/main/antlr4/hudson/scheduler/CrontabParser.g4
  core/src/main/grammar/crontab.g
  core/src/main/grammar/labelExpr.g
  core/src/main/java/antlr/ANTLRException.java
  core/src/main/java/hudson/model/AbstractProject.java
  core/src/main/java/hudson/model/Label.java
  core/src/main/java/hudson/model/labels/LabelExpression.java
  core/src/main/java/hudson/scheduler/BaseParser.java
  core/src/main/java/hudson/scheduler/CronTab.java
  core/src/main/java/hudson/scheduler/CronTabList.java
  core/src/main/java/hudson/slaves/SimpleScheduledRetentionStrategy.java
  core/src/main/java/hudson/triggers/SCMTrigger.java
  core/src/main/java/hudson/triggers/TimerTrigger.java
  core/src/main/java/hudson/triggers/Trigger.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/util/antlr/JenkinsANTLRErrorListener.java
  core/src/test/java/hudson/scheduler/CronTabEventualityTest.java
  core/src/test/java/hudson/scheduler/CronTabTest.java
  core/src/test/java/hudson/triggers/TimerTriggerTest.java
  pom.xml
  src/spotbugs/spotbugs-excludes.xml
  test/src/test/java/hudson/model/ProjectTest.java
  test/src/test/java/hudson/model/labels/LabelExpressionTest.java
  test/src/test/java/hudson/triggers/TriggerTest.java
  test/src/test/java/jenkins/triggers/TriggerTest.java
  war/pom.xml
Labels: ready-for-merge, rfe, hacktoberfest-accepted

#7315 Update eps1lon/actions-label-merge-conflict to v2.1.0
  .github/workflows/label-conflicting-pr.yml
Labels: skip-changelog

#7171 Prefer `inbound` as symbol for `JNLPLauncher`
  core/src/main/java/hudson/slaves/JNLPLauncher.java
Labels: ready-for-merge, bug
