Repository jenkinsci/jenkins, pull requests merged in 2022-04, with the labels that each got.

#6425 Additional backporting for LTS 2.332.2
  pom.xml
Labels: into-lts

#6402 [JENKINS-64299] Fix medium load statistics time series
  core/src/main/java/hudson/model/MultiStageTimeSeries.java
Labels: regression-fix, ready-for-merge, bug

#6428 Use major version of GitHub Actions
  .github/workflows/changelog.yml
  .github/workflows/publish-release-artifact.yml
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6422 Upgrade Spring Framework from 5.3.16 to 5.3.18
  bom/pom.xml
Labels: ready-for-merge, rfe, dependencies, java

#6433 Fix typo in dragdrop-debug.js
  war/src/main/webapp/scripts/yui/dragdrop/dragdrop-debug.js
Labels: skip-changelog

#6432 Upgrade build toolchain
  CONTRIBUTING.md
  core/pom.xml
  pom.xml
  src/spotbugs/spotbugs-excludes.xml
  test/pom.xml
  test/src/test/java/jenkins/model/JenkinsLogRecordsTest.java
  war/pom.xml
Labels: ready-for-merge, skip-changelog, squash-merge-me, dependencies, java

#5417 Use `f:dropdownDescriptorSelector` for `securityRealm` & `authorizationStrategy`
  core/src/main/java/hudson/model/Descriptor.java
  core/src/main/java/hudson/security/GlobalSecurityConfiguration.java
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/index.groovy
  core/src/main/resources/lib/form/dropdownDescriptorSelector.jelly
  essentials.yml
  war/src/main/less/form/layout.less
Labels: ready-for-merge, web-ui, rfe

#6438 Enable unit test to work on non-EN locales
  core/src/test/java/hudson/PluginManagerTest.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6116 Removed legacy hudson update site logic
  core/src/main/java/hudson/model/UpdateSite.java
  test/src/test/java/hudson/model/UpdateSiteTest.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#4579 [JENKINS-50211] Reject connections from agents with unsupported Remoting versions
  core/src/main/java/hudson/slaves/SlaveComputer.java
  test/pom.xml
  test/src/test/java/hudson/slaves/SlaveComputerTest.java
  test/src/test/java/jenkins/slaves/UnsupportedRemotingAgentEscapeHatchTest.java
  test/src/test/java/jenkins/slaves/UnsupportedRemotingAgentTest.java
Labels: rfe, upgrade-guide-needed, squash-merge-me

#6435 [JENKINS-68188] Preview feature of <f:textarea> isn't disabled when readOnlyMode is set
  core/src/main/resources/lib/form/textarea.jelly
Labels: ready-for-merge, bug

#6447 Revert "[JENKINS-67237] `BuildTrigger` waits until the dependency graph has been updated (#6101)"
  core/src/main/java/hudson/tasks/BuildTrigger.java
  core/src/main/java/jenkins/model/Jenkins.java
  test/src/test/java/jenkins/model/JenkinsFutureDependencyGraphTest.java
Labels: regression-fix, ready-for-merge, major-bug, squash-merge-me

#6405 [JENKINS-68121] Line under the "URL Copy" is out of place
  war/src/main/less/modules/section.less
Labels: ready-for-merge, web-ui, skip-changelog, bug

#6448 Add some nullability annotations
  core/src/main/java/hudson/console/UrlAnnotator.java
  core/src/main/java/hudson/model/AbstractBuild.java
  core/src/main/java/hudson/model/AbstractItem.java
  core/src/main/java/hudson/model/AbstractProject.java
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/model/Node.java
  core/src/main/java/hudson/model/ParameterDefinition.java
  core/src/main/java/hudson/model/ParametersDefinitionProperty.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/model/Slave.java
  core/src/main/java/hudson/model/TopLevelItemDescriptor.java
  core/src/main/java/hudson/model/View.java
  core/src/main/java/hudson/model/ViewDescriptor.java
  core/src/main/java/hudson/slaves/DumbSlave.java
  core/src/main/java/hudson/tasks/BuildTrigger.java
  core/src/main/java/hudson/tasks/Shell.java
  core/src/main/java/hudson/triggers/SCMTrigger.java
  core/src/main/java/hudson/triggers/TimerTrigger.java
  core/src/main/java/jenkins/model/ProjectNamingStrategy.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6303 [JENKINS-67846] Icon alignment of build status is wrong
  core/src/main/resources/lib/hudson/buildLink.jelly
Labels: regression-fix, ready-for-merge, squash-merge-me

#6449 [JENKINS-68122] Avoid deadlock involving `RingBufferLogHandler.LogRecordRef` class loading (III)
  core/src/main/java/hudson/util/RingBufferLogHandler.java
Labels: regression-fix, ready-for-merge, major-bug

#6451 Remove calls to fireBottomStickerAdjustEvent
  war/src/main/js/config-scrollspy.js
  war/src/main/js/config-tabbar.js
  war/src/main/js/widgets/config/model/ConfigTableMetaData.js
  war/src/test/js/widgets/config/tabbar.spec.js
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6452 [JENKINS-68055] retain label expressions when trimming labels
  core/src/main/java/jenkins/model/Jenkins.java
  test/src/test/java/jenkins/model/JenkinsTest.java
Labels: regression-fix, ready-for-merge, squash-merge-me

#6453 Improve queue restart tests
  test/src/test/java/hudson/model/QueueCrashTest.java
  test/src/test/java/hudson/model/QueueRestartTest.java
  test/src/test/resources/hudson/model/QueueRestartTest/quietDown/init.groovy.d/quietDown.groovy
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6456 Stop builds in the order supplied
  core/src/main/java/jenkins/cli/StopBuildsCommand.java
Labels: ready-for-merge, bug, squash-merge-me

#6255 [JENKINS-67744] make agent availability help more flexible
  core/src/main/resources/hudson/model/Computer/configure.jelly
  core/src/main/resources/hudson/model/ComputerSet/_new.jelly
  core/src/main/resources/hudson/model/Slave/help-retentionStrategy.jelly
  core/src/main/resources/hudson/model/Slave/help-retentionStrategy_bg.properties
  core/src/main/resources/hudson/model/Slave/help-retentionStrategy_de.properties
  core/src/main/resources/hudson/model/Slave/help-retentionStrategy_fr.properties
  core/src/main/resources/hudson/model/Slave/help-retentionStrategy_it.properties
  core/src/main/resources/hudson/model/Slave/help-retentionStrategy_ja.properties
  core/src/main/resources/hudson/model/Slave/help-retentionStrategy_nl.properties
  core/src/main/resources/hudson/model/Slave/help-retentionStrategy_zh_TW.properties
  core/src/main/resources/hudson/slaves/DumbSlave/configure-entries.jelly
  core/src/main/resources/hudson/slaves/Messages_nl.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Always/help.jelly
  core/src/main/resources/hudson/slaves/RetentionStrategy/Always/help.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Always/help_bg.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Always/help_de.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Always/help_fr.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Always/help_it.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Always/help_ja.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Always/help_nl.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Always/help_zh_TW.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Demand/help.jelly
  core/src/main/resources/hudson/slaves/RetentionStrategy/Demand/help.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Demand/help_bg.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Demand/help_de.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Demand/help_fr.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Demand/help_it.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Demand/help_ja.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Demand/help_nl.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Demand/help_zh_TW.properties
  core/src/main/resources/hudson/slaves/SimpleScheduledRetentionStrategy/help.jelly
  core/src/main/resources/hudson/slaves/SimpleScheduledRetentionStrategy/help.properties
  core/src/main/resources/hudson/slaves/SimpleScheduledRetentionStrategy/help_bg.properties
  core/src/main/resources/hudson/slaves/SimpleScheduledRetentionStrategy/help_de.properties
  core/src/main/resources/hudson/slaves/SimpleScheduledRetentionStrategy/help_fr.properties
  core/src/main/resources/hudson/slaves/SimpleScheduledRetentionStrategy/help_it.properties
Labels: ready-for-merge, rfe

#6458 Rewrite `update-since-todo.sh` in Python
  update-since-todo.py
  update-since-todo.sh
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6462 Rename master to built-in in German localisation
  core/src/main/resources/jenkins/model/Messages_de.properties
Labels: ready-for-merge, localization, squash-merge-me

#6461 [JENKINS-67962]The giant "No builds" message is shown even with a pending build
  core/src/main/resources/hudson/widgets/HistoryWidget/index.jelly
Labels: ready-for-merge, bug

#6468 Remove `html.jelly` in favor of `layout.jelly`
  core/src/main/resources/lib/layout/html.jelly
Labels: ready-for-merge, developer

#6464 Use `f:dropdownDescriptorSelector` for agent launcher
  core/src/main/resources/hudson/model/Slave/help-launcher.jelly
  core/src/main/resources/hudson/slaves/DumbSlave/configure-entries.jelly
Labels: ready-for-merge, rfe, squash-merge-me

#6457 Align shutdown banner, starvation and add a sidepanel to the plugin uninstallation view
  core/src/main/resources/hudson/PluginWrapper/uninstall.groovy
  core/src/main/resources/hudson/PluginWrapper/uninstall_it.properties
  core/src/main/resources/hudson/PluginWrapper/uninstall_ja.properties
  core/src/main/resources/hudson/PluginWrapper/uninstall_lt.properties
  core/src/main/resources/hudson/PluginWrapper/uninstall_zh_TW.properties
  core/src/main/resources/hudson/cli/CLIAction/command.jelly
  core/src/main/resources/lib/hudson/queue.jelly
  war/src/main/less/base/style.less
Labels: ready-for-merge, rfe, squash-merge-me

#6455 Add "copy to clipboard" button to the script console output
  core/src/main/resources/lib/hudson/scriptConsole.jelly
  core/src/main/resources/lib/hudson/scriptConsole.properties
Labels: ready-for-merge, rfe, squash-merge-me

#6477 Update domain for issues.jenkins.io in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: skip-changelog

#6222 Revert [JENKINS-24513] Add access control for builds admin monitor
  core/src/main/java/jenkins/security/QueueItemAuthenticatorMonitor.java
  core/src/main/resources/jenkins/install/platform-plugins.json
  core/src/main/resources/jenkins/security/Messages.properties
  core/src/main/resources/jenkins/security/QueueItemAuthenticatorMonitor/message.groovy
  core/src/main/resources/jenkins/security/QueueItemAuthenticatorMonitor/message.properties
Labels: ready-for-merge, rfe, squash-merge-me

#6442 Use the `jenkins-input` class in more locations
  core/src/main/resources/hudson/PluginManager/advanced.jelly
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/Details/config.jelly
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/_entryForm.jelly
  core/src/main/resources/jenkins/install/SetupWizard/setupWizardFirstUser.jelly
  war/src/main/less/base-styles-v2.less
  war/src/main/less/pages/setupWizardFirstUser.less
Labels: ready-for-merge, rfe, squash-merge-me

#6465 Russian misspelling correction
  core/src/main/resources/jenkins/model/Jenkins/_safeRestart_ru.properties
Labels: ready-for-merge, skip-changelog, localization, squash-merge-me

#6469 Remove `msie.js`, `svgxuse.min.js` and CSS custom properties polyfill
  core/src/main/resources/lib/layout/layout.jelly
  war/package.json
  war/postcss.config.js
  war/src/main/less/base/style.less
  war/src/main/less/modules/badges.less
  war/src/main/less/modules/progress-animation.less
  war/src/main/less/modules/section.less
  war/src/main/webapp/scripts/svgxuse.min.js
  war/yarn.lock
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6470 Remove `ui-refresh-overrides.less` and UI refresh toggle
  core/src/main/java/hudson/Functions.java
  core/src/main/resources/lib/layout/layout.jelly
  war/src/main/less/abstracts/theme.less
  war/src/main/less/ui-refresh-overrides.less
  war/webpack.config.js
Labels: ready-for-merge, squash-merge-me, removed

#6471 Remove invalid repeatable CSS
  war/src/main/less/form/reorderable-list.less
Labels: ready-for-merge, skip-changelog

#6467 Rename `base-styles-v2.less` to `styles.less`
  core/src/main/resources/lib/layout/layout.jelly
  war/src/main/less/styles.less
  war/webpack.config.js
Labels: ready-for-merge, skip-changelog

#6478 Exchange issue tracker URL on PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready-for-merge, skip-changelog

#6484 [JENKINS-67933] Move plugin manager search bar back to middle
  core/src/main/resources/hudson/PluginManager/available.jelly
  core/src/main/resources/hudson/PluginManager/installed.jelly
  core/src/main/resources/hudson/PluginManager/table.jelly
  war/src/main/js/plugin-manager-ui.js
Labels: regression-fix, ready-for-merge, squash-merge-me

#6483 [JENKINS-68260] Allow filtering updates by plugin ID
  core/src/main/resources/hudson/PluginManager/table.jelly
Labels: regression-fix, ready-for-merge

#6476 [JENKINS-67849] Correct icon resolution for remote icons
  core/src/main/java/hudson/Functions.java
Labels: regression-fix, ready-for-merge

#6479 [JENKINS-68103] Fix build progress bar not taking the user to console output
  war/src/main/less/modules/breadcrumbs.less
Labels: regression-fix, ready-for-merge, squash-merge-me

#6480 [JENKINS-68276] Upgrade bundled Jackson 2 API plugin from 2.12.0 to 2.13.2.20220328-273.v11d70a_b_a_1a_52
  war/pom.xml
Labels: ready-for-merge, squash-merge-me, dependencies, java

#6482 [JENKINS-68270] Fix third party weather icons in table view
  core/src/main/resources/lib/hudson/ballColorTd.jelly
  test/src/test/java/lib/layout/IconTest.java
Labels: regression-fix, ready-for-merge

#6475 [JENKINS-51913] Prevent `archiveArtifacts` from displaying a stack trace when no artifacts are found
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/tasks/ArtifactArchiver.java
  test/src/test/java/hudson/tasks/ArtifactArchiverTest.java
Labels: ready-for-merge, bug

#6481 [JENKINS-68129] Fix dropdown chevrons not separating links and overflowing
  war/src/main/less/modules/breadcrumbs.less
  war/src/main/less/modules/page-header.less
  war/src/main/less/modules/table.less
Labels: regression-fix, ready-for-merge, squash-merge-me

#6046 Miscellaneous code cleanup
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/java/hudson/security/UnwrapSecurityExceptionFilter.java
Labels: ready-for-merge, skip-changelog

#6276 Add dropdown to user cause trigger
  core/src/main/resources/hudson/model/Cause/UserCause/description.properties
  core/src/main/resources/hudson/model/Cause/UserCause/description_bg.properties
  core/src/main/resources/hudson/model/Cause/UserCause/description_da.properties
  core/src/main/resources/hudson/model/Cause/UserCause/description_de.properties
  core/src/main/resources/hudson/model/Cause/UserCause/description_es.properties
  core/src/main/resources/hudson/model/Cause/UserCause/description_fr.properties
  core/src/main/resources/hudson/model/Cause/UserCause/description_it.properties
  core/src/main/resources/hudson/model/Cause/UserCause/description_ja.properties
  core/src/main/resources/hudson/model/Cause/UserCause/description_ko.properties
  core/src/main/resources/hudson/model/Cause/UserCause/description_nl.properties
  core/src/main/resources/hudson/model/Cause/UserCause/description_pl.properties
  core/src/main/resources/hudson/model/Cause/UserCause/description_pt_BR.properties
  core/src/main/resources/hudson/model/Cause/UserCause/description_ru.properties
  core/src/main/resources/hudson/model/Cause/UserCause/description_sl.properties
  core/src/main/resources/hudson/model/Cause/UserCause/description_sr.properties
  core/src/main/resources/hudson/model/Cause/UserCause/description_sv_SE.properties
  core/src/main/resources/hudson/model/Cause/UserCause/description_zh_TW.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_bg.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_ca.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_cs.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_da.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_de.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_el.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_es.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_fi.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_fr.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_he.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_hu.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_it.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_ja.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_ko.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_lt.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_lv.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_nb_NO.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_nl.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_pl.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_pt_BR.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_pt_PT.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_ru.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_sk.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_sl.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_sr.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_sv_SE.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_tr.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_uk.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_zh_TW.properties
Labels: ready-for-merge, rfe, squash-merge-me

#6092 Announce forthcoming requirement of Java 11
  core/src/main/java/jenkins/monitor/JavaVersionRecommendationAdminMonitor.java
  core/src/main/resources/jenkins/monitor/JavaVersionRecommendationAdminMonitor/message.jelly
  core/src/main/resources/jenkins/monitor/JavaVersionRecommendationAdminMonitor/message.properties
Labels: ready-for-merge, skip-changelog, rfe

#6486 [JENKINS-68277] Fix not being able to disable a plugin when dependent plugins are disabled
  war/src/main/less/pages/plugin-manager.less
Labels: regression-fix, ready-for-merge, squash-merge-me

#5748 Replaced usage of deprecated static field `DESCRIPTOR` and added `NoExternalUse`
  core/src/main/java/hudson/node_monitors/TemporarySpaceMonitor.java
  core/src/main/java/hudson/slaves/JNLPLauncher.java
  core/src/main/java/hudson/tasks/ArtifactArchiver.java
  core/src/main/java/hudson/tasks/Maven.java
Labels: ready-for-merge, skip-changelog

#6202 JENKINS-61985 Support 'myView' with configuration as code
  core/src/main/java/hudson/model/MyViewsProperty.java
Labels: ready-for-merge, rfe, squash-merge-me

#6473 [JENKINS-68284] Modernise log recorder pages
  core/src/main/java/hudson/logging/LogRecorder.java
  core/src/main/java/hudson/logging/LogRecorderManager.java
  core/src/main/resources/hudson/logging/LogRecorder/configure.jelly
  core/src/main/resources/hudson/logging/LogRecorder/configure.properties
  core/src/main/resources/hudson/logging/LogRecorder/delete.jelly
  core/src/main/resources/hudson/logging/LogRecorder/delete.properties
  core/src/main/resources/hudson/logging/LogRecorder/delete_bg.properties
  core/src/main/resources/hudson/logging/LogRecorder/delete_es.properties
  core/src/main/resources/hudson/logging/LogRecorderManager/levels.jelly
  core/src/main/resources/hudson/logging/LogRecorderManager/new.jelly
  core/src/main/resources/hudson/logging/Messages.properties
  core/src/main/resources/lib/form/textbox.jelly
  test/src/test/java/hudson/logging/LogRecorderManagerTest.java
Labels: ready-for-merge, rfe

#5825 Enable JaCoCo code coverage
  Jenkinsfile
  cli/pom.xml
  core/pom.xml
  coverage/pom.xml
  pom.xml
  test/pom.xml
Labels: ready-for-merge, skip-changelog, squash-merge-me

#4688 [JENKINS-62024] Add quick filter box for dropdown lists in hetero-list
  core/src/main/resources/lib/form/filter-menu-button/filter-menu-button.js
  core/src/main/resources/lib/form/hetero-list/hetero-list.js
Labels: ready-for-merge, rfe

#6472 Backporting for LTS 2.332.3
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/lifecycle/Lifecycle.java
  core/src/main/java/hudson/slaves/SlaveComputer.java
  core/src/main/java/hudson/util/RingBufferLogHandler.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/org/jenkins/ui/icon/IconSet.java
  core/src/main/resources/hudson/PluginManager/table.jelly
  core/src/main/resources/hudson/model/Run/configure.jelly
  core/src/main/resources/jenkins/security/UpdateSiteWarningsMonitor/message_fr.properties
  core/src/main/resources/lib/hudson/logRecords.jelly
  core/src/test/java/hudson/FunctionsTest.java
  test/src/test/java/jenkins/model/JenkinsTest.java
  war/pom.xml
  war/src/main/webapp/images/16x16/computer-flash.gif
  war/src/main/webapp/images/24x24/computer-flash.gif
  war/src/main/webapp/images/32x32/computer-flash.gif
  war/src/main/webapp/images/48x48/computer-flash.gif
Labels: into-lts

#6490 Emphasize Jenkins project in idea
  .gitignore
  .idea/.name
  .idea/icon.svg
Labels: ready-for-merge, skip-changelog

#6380 [JENKINS-68031] Jenkins 2.0 style config form bottom border is cut off
  war/src/main/js/widgets/config/tabbar.less
Labels: regression-fix, ready-for-merge

#6492 Restore incrementals publishing
  Jenkinsfile
  coverage/pom.xml
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6495 Remove pointless `JAVA_OPTS` variable
  Jenkinsfile
Labels: ready-for-merge, skip-changelog

#5743 [JENKINS-68293] Login and signup page refresh
  core/src/main/resources/hudson/lifecycle/WindowsInstallerLink/_restart.jelly
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/signup.jelly
  core/src/main/resources/hudson/util/HudsonIsLoading/index.jelly
  core/src/main/resources/hudson/util/HudsonIsRestarting/index.jelly
  core/src/main/resources/jenkins/model/DefaultSimplePageDecorator/simple-head.jelly
  core/src/main/resources/jenkins/model/DefaultSimplePageDecorator/simple-header.jelly
  core/src/main/resources/jenkins/model/Jenkins/login.jelly
  war/src/main/less/base/style.less
  war/src/main/less/form/input.less
  war/src/main/less/simple-page.less
  war/src/main/webapp/css/signup.css
  war/src/main/webapp/css/simple-page-forms.css
  war/src/main/webapp/css/simple-page-variables.css
  war/src/main/webapp/css/simple-page.css
  war/webpack.config.js
Labels: ready-for-merge, web-ui, rfe

#6494 Remove custom `MAVEN_OPTS` in favor of `.mvn/jvm.config`
  Jenkinsfile
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6500 [JENKINS-68291] Plugin Manager 'Installed' tab filter is not reset when clicking input "X" button
  core/src/main/resources/hudson/PluginManager/_table.js
Labels: regression-fix, ready-for-merge, squash-merge-me

#6509 Remove unnecessary padding around 'Build after other projects are built' radios
  core/src/main/resources/jenkins/triggers/ReverseBuildTrigger/config.jelly
Labels: ready-for-merge, rfe

#6513 Clean up `Jenkinsfile`
  Jenkinsfile
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6502 Fixes for Brazilian Portuguese translations
  core/src/main/resources/hudson/cli/Messages_pt_BR.properties
  core/src/main/resources/hudson/logging/LogRecorder/configure_pt_BR.properties
  core/src/main/resources/hudson/logging/LogRecorder/delete_pt_BR.properties
  core/src/main/resources/hudson/logging/LogRecorderManager/levels_pt_BR.properties
  core/src/main/resources/hudson/logging/LogRecorderManager/new_pt_BR.properties
  core/src/main/resources/hudson/logging/LogRecorderManager/sidepanel_pt_BR.properties
  core/src/main/resources/hudson/logging/Messages_pt_BR.properties
Labels: ready-for-merge, localization, squash-merge-me

#6450 [JENKINS-67237] BuildTrigger waits until the dependency graph has been updated - 2nd attempt
  core/src/main/java/hudson/tasks/BuildTrigger.java
  core/src/main/java/jenkins/model/Jenkins.java
  test/src/test/java/jenkins/model/JenkinsFutureDependencyGraphTest.java
  test/src/test/java/jenkins/triggers/ReverseBuildTriggerAfterRestartTest.java
Labels: ready-for-merge, skip-changelog, bug

#6516 Bugfix/deprecated keys pt br
  core/src/main/resources/hudson/cli/Messages_pt_BR.properties
  core/src/main/resources/hudson/logging/LogRecorder/configure_pt_BR.properties
  core/src/main/resources/hudson/logging/LogRecorderManager/sidepanel_pt_BR.properties
  core/src/main/resources/hudson/model/DirectoryBrowserSupport/dir_pt_BR.properties
  core/src/main/resources/hudson/triggers/SCMTrigger/BuildAction/index_pt_BR.properties
  core/src/main/resources/jenkins/diagnostics/ControllerExecutorsNoAgents/message_pt_BR.properties
  core/src/main/resources/jenkins/security/Messages_pt_BR.properties
  core/src/main/resources/lib/hudson/node_pt_BR.properties
Labels: ready-for-merge, localization, squash-merge-me

#6519 [JENKINS-68338] Credentials popup does not work in SSH Build Agents (regression in 2.344)
  core/src/main/resources/hudson/model/Slave/help-launcher.jelly
  core/src/main/resources/hudson/slaves/DumbSlave/configure-entries.jelly
Labels: regression-fix, squash-merge-me

#6521 Update search input clear button to respect user's theme
  war/src/main/less/form/search.less
Labels: ready-for-merge, web-ui, rfe, squash-merge-me
