Repository jenkinsci/jenkins, pull requests merged in 2022-09, with the labels that each got.

#6923 [JENKINS-69114] When executor widgets refreshes the down chevron of the build number gets misplaced
  core/src/main/resources/lib/hudson/executors.jelly
Labels: ready-for-merge, web-ui, bug, security-approved

#6966 [JENKINS-68952] Wrong location of email form validation on setup wizard
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/_entryForm.jelly
Labels: ready-for-merge, web-ui, rfe, security-approved

#6989 [JENKINS-68805] Reset cached attributes with ampersand as well
  core/src/main/java/org/jenkins/ui/icon/IconSet.java
  core/src/test/java/org/jenkins/ui/icon/IconSetJenkins68805Test.java
Labels: ready-for-merge, bug, alternative

#7029 [JENKINS-69417] Users views icon is misleading
  core/src/main/java/hudson/model/MyViewsProperty.java
Labels: ready-for-merge, skip-changelog

#7050 Remove inline SVG of 'concealed' field
  core/src/main/resources/lib/form/password.jelly
  core/src/main/resources/lib/form/secretTextarea.jelly
Labels: ready-for-merge, skip-changelog, security-approved

#7045 Fix Plugin Manager selection controller buttons appearance
  core/src/main/resources/hudson/PluginManager/table.jelly
  core/src/main/resources/lib/layout/rowSelectionController.jelly
  war/src/main/less/modules/row-selection-controller.less
Labels: ready-for-merge, skip-changelog

#7032 [JENKINS-69438] Filter drop select input is out of style with other components
  core/src/main/resources/hudson/model/RunParameterDefinition/config.jelly
Labels: ready-for-merge, skip-changelog

#7063 Second backporting for LTS 2.361.1
  core/src/main/resources/jenkins/views/JenkinsHeader/headerContent.jelly
  core/src/main/resources/lib/layout/layout.jelly
  war/src/main/less/form/checkbox.less
Labels: into-lts

#7053 Better diagnostic when a connection gets EOFException
  core/src/main/java/hudson/TcpSlaveAgentListener.java
Labels: ready-for-merge, rfe

#7058 Delete dead code to invoke `maven-stapler-plugin`
  core/pom.xml
Labels: ready-for-merge, skip-changelog

#7059 Fill in recent 'since' annotations
  core/src/main/java/jenkins/util/SetContextClassLoader.java
  war/src/main/java/executable/Main.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#7060 Run 'publish-release-artifact' GH action on Java 11
  .github/workflows/publish-release-artifact.yml
Labels: ready-for-merge, skip-changelog

#7061 EOL `maven-assembly-plugin`
  assembly-src.xml
  pom.xml
Labels: ready-for-merge, removed

#7062 Remove unnecessary workaround for JDK-8186464
  core/src/test/java/hudson/util/io/ZipArchiverTest.java
Labels: ready-for-merge, skip-changelog

#7064 Ignore git folder in prettier checks
  war/.prettierignore
Labels: skip-changelog

#7057 Allow `yarn.lint.skip` to be set by `-Pquick-build`
  war/pom.xml
Labels: skip-changelog

#7010 [JENKINS-69359] Code Mirror textbox autosizing is broken
  core/src/main/resources/lib/form/textarea/textarea.js
Labels: regression-fix, ready-for-merge, squash-merge-me, security-approved

#7052 Replace static icon references with symbol API
  core/src/main/resources/hudson/model/AllView/noJob.groovy
  core/src/main/resources/hudson/util/JenkinsReloadFailed/index.groovy
  core/src/main/resources/jenkins/views/JenkinsHeader/headerContent.jelly
  core/src/main/resources/lib/layout/helpIcon.jelly
Labels: ready-for-merge, web-ui, rfe

#7055 Remove inline CSS of setup wizard
  core/src/main/resources/jenkins/install/SetupWizard/setupWizardConfigureInstance.jelly
  war/src/main/less/pages/setupWizardConfigureInstance.less
  war/src/main/less/styles.less
Labels: ready-for-merge, skip-changelog

#7065 Clean up `HistoryPageFilter` tests
  core/src/test/java/jenkins/widgets/HistoryPageFilterTest.java
  test/src/test/java/jenkins/widgets/HistoryPageFilterCaseSensitiveSearchTest.java
Labels: ready-for-merge, skip-changelog

#7066 Make `TaskListener#_error` private
  core/src/main/java/hudson/model/TaskListener.java
Labels: ready-for-merge, skip-changelog

#7067 Use `Runtime#version` where possible
  core/src/main/java/jenkins/util/java/JavaUtils.java
  test/src/test/java/jenkins/model/JenkinsLogRecordsTest.java
  test/src/test/java/jenkins/security/Security637Test.java
Labels: ready-for-merge, skip-changelog

#6598 [JENKINS-68602] parent name for ProjectNamingStrategy
  core/src/main/java/hudson/model/AbstractItem.java
  core/src/main/java/hudson/model/ItemGroupMixIn.java
  core/src/main/java/hudson/model/Job.java
  core/src/main/java/hudson/model/View.java
  core/src/main/java/jenkins/model/ProjectNamingStrategy.java
Labels: ready-for-merge, squash-merge-me, developer, security-approved

#7076 [JENKINS-69543] Fix thread safety in websockets handling.
  websocket/jetty10/src/main/java/jenkins/websocket/Jetty10Provider.java
  websocket/jetty9/src/main/java/jenkins/websocket/Jetty9Provider.java
Labels: ready-for-merge, bug

#7070 Remove .jelly from editorconfig rules
  .editorconfig
Labels: ready-for-merge, internal, skip-changelog

#7086 Document at-since for Util#fullEncode
  core/src/main/java/hudson/Util.java
Labels: ready-for-merge, skip-changelog

#7071 [JENKINS-15604] Trigger form validation when saving CodeMirror field
  core/src/main/resources/lib/form/textarea/textarea.js
  test/src/test/java/hudson/util/FormFieldValidatorTest.java
  test/src/test/resources/hudson/util/FormFieldValidatorTest/CodeMirrorStep/config.jelly
Labels: ready-for-merge, bug

#7089 Deprecate `AntClassLoader`
  core/src/main/java/hudson/PluginFirstClassLoader.java
  core/src/main/java/jenkins/util/AntClassLoader.java
Labels: ready-for-merge, skip-changelog

#7099 Update ATH Docker image
  essentials.yml
Labels: skip-changelog

#7100 Dutch translation improvements
  core/src/main/resources/jenkins/model/Jenkins/legend_nl.properties
  core/src/main/resources/lib/hudson/rssBar_nl.properties
  core/src/main/resources/lib/layout/layout_nl.properties
Labels: ready-for-merge, localization

#7041 [JENKINS-68712] updateCenter successfully installs nothing where there's nothing to install
  core/src/main/resources/hudson/PluginManager/available.jelly
  core/src/main/resources/hudson/PluginManager/table.jelly
Labels: ready-for-merge, web-ui, bug, security-approved

#7096 Keep Jelly samples as-is
  core/src/main/resources/lib/form/repeatableProperty.jelly
  core/src/main/resources/lib/form/secretTextarea.jelly
  core/src/main/resources/lib/layout/svgIcon.jelly
Labels: ready-for-merge, skip-changelog

#7095 Document Jelly deprecations properly
  core/src/main/resources/hudson/model/AbstractItem/delete.jelly
  core/src/main/resources/hudson/model/AbstractProject/makeDisabled.jelly
  core/src/main/resources/lib/hudson/project/config-upstream-pseudo-trigger.jelly
  core/src/main/resources/lib/hudson/rssBar-with-iconSize.jelly
Labels: ready-for-merge, skip-changelog

#7026 Enable Dependabot security updates on LTS line
  .github/dependabot.yml
Labels: ready-for-merge, skip-changelog

#7108 Revert "[JENKINS-68712] updateCenter successfully installs nothing where there's nothing to install"
  core/src/main/resources/hudson/PluginManager/available.jelly
  core/src/main/resources/hudson/PluginManager/table.jelly
Labels: skip-changelog

#6970 [JENKINS-69257] Model link chevron is not in center in user build cause
  core/src/main/java/hudson/console/ModelHyperlinkNote.java
Labels: regression-fix, ready-for-merge, web-ui, skip-changelog

#7028 Remove managed, provided dependency on log4j 1.2.17
  bom/pom.xml
Labels: ready-for-merge, developer

#6702 [JENKINS-67864] Table columns get wider and smaller if you click on buttons
  war/src/main/less/modules/table.less
Labels: regression-fix, ready-for-merge, web-ui, security-approved

#7087 [JENKINS-69534] Fix a race condition that causes file descriptor leaks when cloud agents are created
  core/src/main/java/hudson/model/AbstractCIBase.java
  core/src/main/java/jenkins/model/Jenkins.java
Labels: ready-for-merge, bug

#7074 Add search bar component
  core/src/main/resources/hudson/PluginManager/_table.js
  core/src/main/resources/hudson/PluginManager/available.jelly
  core/src/main/resources/hudson/PluginManager/installed.jelly
  core/src/main/resources/hudson/PluginManager/table.jelly
  core/src/main/resources/hudson/widgets/HistoryWidget/index.jelly
  core/src/main/resources/lib/layout/search-bar.jelly
  war/src/main/js/keyboard-shortcuts.js
  war/src/main/js/plugin-manager-ui.js
  war/src/main/less/form/search-bar.less
  war/src/main/less/form/search.less
  war/src/main/less/pages/plugin-manager.less
  war/src/main/less/styles.less
  war/src/main/resources/images/symbols/search-shortcut.svg
Labels: ready-for-merge, web-ui, rfe, security-approved

#7054 [JENKINS-69461] Setup wizard URL and password field use old form design
  core/src/main/resources/jenkins/install/SetupWizard/authenticate-security-token.jelly
  core/src/main/resources/jenkins/install/SetupWizard/setupWizardConfigureInstance.jelly
  war/src/main/js/templates/firstUserPanel.hbs
  war/src/main/js/templates/welcomePanel.hbs
  war/src/main/less/pages/setupWizardConfigureInstance.less
  war/src/main/less/pluginSetupWizard.less
Labels: ready-for-merge, web-ui, skip-changelog, security-approved

#6859 [JENKINS-60866] Remove inline JS from primary 'my views' name check (fake hidden form element)
  core/src/main/resources/hudson/model/MyViewsProperty/config.jelly
Labels: ready-for-merge, skip-changelog, alternative

#7098 Use ionicons in header
  core/src/main/resources/hudson/model/AllView/noJob.groovy
  core/src/main/resources/jenkins/management/AdministrativeMonitorsDecorator/footer.jelly
  core/src/main/resources/jenkins/views/JenkinsHeader/headerContent.jelly
  war/src/main/resources/images/symbols/link.svg
  war/src/main/resources/images/symbols/log-out.svg
  war/src/main/resources/images/symbols/notifications.svg
  war/src/main/resources/images/symbols/shield-warning.svg
Labels: ready-for-merge, web-ui, rfe

#7110 Let the CI pass the appropriate forkCount
  Jenkinsfile
  core/pom.xml
  test/pom.xml
Labels: ready-for-merge, skip-changelog

#7118 Remove unneeded SUREFIRE-1226 workaround
  pom.xml
Labels: skip-changelog

#7114 Prefer `assertThrows` to try/fail
  core/src/test/java/hudson/util/RobustCollectionConverterTest.java
  core/src/test/java/hudson/util/RobustMapConverterTest.java
  core/src/test/java/hudson/util/RobustReflectionConverterTest.java
  core/src/test/java/jenkins/model/Security2424Test.java
  test/src/test/java/hudson/cli/ComputerStateTest.java
  test/src/test/java/hudson/diagnosis/HudsonHomeDiskUsageMonitorTest.java
  test/src/test/java/hudson/diagnosis/TooManyJobsButNoViewTest.java
  test/src/test/java/hudson/model/FingerprintTest.java
  test/src/test/java/hudson/model/FreeStyleProjectTest.java
  test/src/test/java/hudson/model/SlaveTest.java
  test/src/test/java/hudson/model/labels/LabelExpressionTest.java
  test/src/test/java/hudson/security/csrf/DefaultCrumbIssuerTest.java
  test/src/test/java/jenkins/model/NodesTest.java
  test/src/test/java/jenkins/security/ApiTokenPropertyTest.java
  test/src/test/java/jenkins/security/BasicHeaderProcessorTest.java
  test/src/test/java/jenkins/security/Security218Test.java
  test/src/test/java/jenkins/security/apitoken/ApiTokenStatsRestartTest.java
  test/src/test/java/jenkins/security/apitoken/ApiTokenStatsTest.java
  test/src/test/java/org/kohsuke/stapler/Security1097Test.java
Labels: ready-for-merge, skip-changelog

#7094 Remove usages of deprecated Apache Commons HttpClient 3.x library
  core/src/main/java/hudson/ProxyConfiguration.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#6829 [JENKINS-68981] Export `hudson.model.Run#isInProgress`
  core/src/main/java/hudson/model/Run.java
Labels: ready-for-merge, developer

#7117 [JENKINS-69624] [JENKINS-69638] Winstone 6.4: Upgrade Jetty from 10.0.11 to 10.0.12
  war/pom.xml
  websocket/jetty10/pom.xml
Labels: ready-for-merge, rfe, dependencies, java

#7126 Miscellaneous test cleanup
  core/src/test/java/hudson/cli/handlers/ViewOptionHandlerTest.java
  core/src/test/java/hudson/model/FingerprintTest.java
  core/src/test/java/hudson/util/IteratorsTest.java
  core/src/test/java/hudson/util/RobustCollectionConverterTest.java
  core/src/test/java/hudson/util/RobustMapConverterTest.java
  core/src/test/java/hudson/util/RobustReflectionConverterTest.java
  test/src/test/java/hudson/CustomPluginManagerTest.java
  test/src/test/java/hudson/core/PluginManagerOverrideTest.java
  test/src/test/java/hudson/model/AbstractBuildTest.java
  test/src/test/java/hudson/model/CauseTest.java
  test/src/test/java/hudson/model/ItemsTest.java
  test/src/test/java/hudson/model/JobQueueTest.java
  test/src/test/java/hudson/model/NodeTest.java
  test/src/test/java/hudson/model/ProjectTest.java
  test/src/test/java/hudson/model/QueueTest.java
  test/src/test/java/hudson/model/UpdateCenter2Test.java
  test/src/test/java/hudson/model/ViewTest.java
  test/src/test/java/hudson/slaves/SlaveComputerTest.java
  test/src/test/java/hudson/tasks/CommandInterpreterTest.java
  test/src/test/java/hudson/util/SecretCompatTest.java
  test/src/test/java/jenkins/model/ExtensionTypeHierarchyTest.java
  test/src/test/java/jenkins/model/ParameterizedJobMixInTest.java
  test/src/test/java/lib/form/ExpandableTextboxTest.java
  test/src/test/java/lib/form/RepeatablePropertyTest.java
Labels: ready-for-merge, skip-changelog

#7119 Don't escape special chars in Jelly doc
  core/src/main/resources/hudson/model/AbstractItem/delete.jelly
  core/src/main/resources/hudson/model/AbstractProject/makeDisabled.jelly
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/_entryForm.jelly
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/_entryFormPage.jelly
  core/src/main/resources/lib/form/breadcrumb-config-outline.jelly
  core/src/main/resources/lib/form/checkbox.jelly
  core/src/main/resources/lib/form/class-entry.jelly
  core/src/main/resources/lib/form/combobox.jelly
  core/src/main/resources/lib/form/descriptorList.jelly
  core/src/main/resources/lib/form/dropdownDescriptorSelector.jelly
  core/src/main/resources/lib/form/dropdownList.jelly
  core/src/main/resources/lib/form/dropdownListBlock.jelly
  core/src/main/resources/lib/form/editableComboBox.jelly
  core/src/main/resources/lib/form/editableComboBoxValue.jelly
  core/src/main/resources/lib/form/entry.jelly
  core/src/main/resources/lib/form/enum.jelly
  core/src/main/resources/lib/form/enumSet.jelly
  core/src/main/resources/lib/form/expandableTextbox.jelly
  core/src/main/resources/lib/form/form.jelly
  core/src/main/resources/lib/form/helpLink.jelly
  core/src/main/resources/lib/form/hetero-list.jelly
  core/src/main/resources/lib/form/invisibleEntry.jelly
  core/src/main/resources/lib/form/number.jelly
  core/src/main/resources/lib/form/option.jelly
  core/src/main/resources/lib/form/optionalBlock.jelly
  core/src/main/resources/lib/form/optionalProperty.jelly
  core/src/main/resources/lib/form/password.jelly
  core/src/main/resources/lib/form/prepareDatabinding.jelly
  core/src/main/resources/lib/form/radio.jelly
  core/src/main/resources/lib/form/radioBlock.jelly
  core/src/main/resources/lib/form/readOnlyTextbox.jelly
  core/src/main/resources/lib/form/repeatable.jelly
  core/src/main/resources/lib/form/repeatableDeleteButton.jelly
  core/src/main/resources/lib/form/repeatableHeteroProperty.jelly
  core/src/main/resources/lib/form/repeatableProperty.jelly
  core/src/main/resources/lib/form/section.jelly
  core/src/main/resources/lib/form/select.jelly
  core/src/main/resources/lib/form/slave-mode.jelly
  core/src/main/resources/lib/form/submit.jelly
  core/src/main/resources/lib/form/textarea.jelly
  core/src/main/resources/lib/form/textbox.jelly
  core/src/main/resources/lib/form/toggleSwitch.jelly
  core/src/main/resources/lib/hudson/newFromList/form.jelly
  core/src/main/resources/lib/hudson/project/config-publishers.jelly
  core/src/main/resources/lib/hudson/queue.jelly
  core/src/main/resources/lib/hudson/rssBar-with-iconSize.jelly
  core/src/main/resources/lib/layout/breadcrumb.jelly
  core/src/main/resources/lib/layout/breadcrumbBar.jelly
  core/src/main/resources/lib/layout/header.jelly
  core/src/main/resources/lib/layout/layout.jelly
  core/src/main/resources/lib/layout/pane.jelly
  core/src/main/resources/lib/layout/progressAnimation.jelly
  core/src/main/resources/lib/layout/svgIcon.jelly
  core/src/main/resources/lib/layout/task.jelly
Labels: ready-for-merge, skip-changelog

#7120 Feat: First Backporting for LTS 2.361.2
  core/src/main/java/hudson/Util.java
  core/src/main/java/org/jenkins/ui/icon/IconSet.java
  core/src/main/resources/hudson/PluginManager/table.jelly
  core/src/main/resources/lib/layout/rowSelectionController.jelly
  core/src/test/java/org/jenkins/ui/icon/IconSetJenkins68805Test.java
  core/src/test/java/org/jenkins/ui/icon/IconSetTest.java
  war/src/main/less/modules/row-selection-controller.less
  war/src/main/webapp/scripts/hudson-behavior.js
  websocket/jetty10/src/main/java/jenkins/websocket/Jetty10Provider.java
  websocket/jetty9/src/main/java/jenkins/websocket/Jetty9Provider.java
Labels: into-lts

#7138 Remove custom arguments from Maven Release Plugin configuration
  pom.xml
Labels: regression-fix, ready-for-merge

#7143 Ignore `HudsonPrivateSecurityRealmSEC2566Test.noTimingDifferenceForInternalSecurityRealm`
  test/src/test/java/hudson/security/HudsonPrivateSecurityRealmSEC2566Test.java
Labels: skip-changelog

#7144 De-flake `ProjectTest#testScheduleBuild2`
  test/src/test/java/hudson/model/ProjectTest.java
Labels: ready-for-merge, skip-changelog

#7145 Skip remaining `NodeProvisionerTest` tests on Windows CI runs
  test/src/test/java/hudson/slaves/NodeProvisionerTest.java
Labels: ready-for-merge, skip-changelog

#7151 De-flake `InitMilestoneTest`
  test/src/test/java/hudson/init/InitMilestoneTest.java
Labels: ready-for-merge, skip-changelog

#7147 De-flake `BuildCommandTest#executorsAliveOnParameterWithNullDefaultValue`
  test/src/test/java/hudson/cli/BuildCommandTest.java
Labels: ready-for-merge, skip-changelog

#7146 Increase timeout for `ManagementLinkTest#links`
  test/src/test/java/hudson/model/ManagementLinkTest.java
Labels: ready-for-merge, skip-changelog

#7142 Revise curl example for inbound agent
  core/src/main/resources/hudson/slaves/JNLPLauncher/main.jelly
Labels: ready-for-merge, skip-changelog

#7150 De-flake `DefaultCrumbIssuerTest`
  test/src/test/java/hudson/security/csrf/DefaultCrumbIssuerTest.java
Labels: ready-for-merge, skip-changelog

#7148 De-flake `NodeProvisionerRule`-based tests
  test/src/test/java/hudson/model/QueueTest.java
  test/src/test/java/hudson/slaves/NodeProvisionerTest.java
Labels: ready-for-merge, skip-changelog

#7153 Docs on linting
  CONTRIBUTING.md
Labels: ready-for-merge, skip-changelog

#7154 Rerun failing tests twice instead of four times
  test/pom.xml
Labels: skip-changelog

#7134 [JENKINS-69650] Fix test reporting of Security2779Test
  test/src/test/java/jenkins/security/Security2779Test.java
Labels: ready-for-merge, skip-changelog

#7160 De-flake BuildCommandTest
  test/src/test/java/hudson/cli/BuildCommandTest.java
Labels: skip-changelog

#7164 Revert "Bump junit from 1119.1121.vc43d0fc45561 to 1143.v8d9a_e3355270"
  test/pom.xml
Labels: skip-changelog

#7166 Improve `InitMilestoneTest` error message
  test/src/test/java/hudson/init/InitMilestoneTest.java
Labels: skip-changelog

#7124 Added individual suppression to spotbugs false positives
  core/src/main/java/jenkins/install/SetupWizard.java
  core/src/main/java/jenkins/security/ApiTokenProperty.java
  core/src/main/java/jenkins/security/apitoken/ApiTokenStore.java
  src/spotbugs/spotbugs-excludes.xml
Labels: ready-for-merge, skip-changelog, security-approved

#6236 [JENKINS-67681] `ProcessTree$Windows#killAll` is slow on Windows
  bom/pom.xml
  test/src/test/java/hudson/model/FreeStyleProjectTest.java
Labels: ready-for-merge, rfe

#7163 De-flake `ResponseTimeMonitorTest`
  test/src/test/java/hudson/node_monitors/ResponseTimeMonitorTest.java
Labels: skip-changelog

#7167 [JENKINS-69666] Core Release: Staging not working anymore
  pom.xml
Labels: into-lts

#7152 [JENKINS-69676] Status filter dropdown icon is out of style with other
  core/src/main/resources/hudson/views/StatusFilter/config.jelly
Labels: ready-for-merge, web-ui, skip-changelog

#7131 Introduced `TriggeredItem` to better abstract `getTriggers`
  core/src/main/java/hudson/triggers/Trigger.java
  core/src/main/java/jenkins/model/ParameterizedJobMixIn.java
  core/src/main/java/jenkins/triggers/TriggeredItem.java
Labels: ready-for-merge, developer

#7128 GitHub Workflows security hardening
  .github/workflows/changelog.yml
  .github/workflows/publish-release-artifact.yml
Labels: ready-for-merge, skip-changelog, security-approved

#7168 De-flake `BuildKeepsRunningWhenFaultySubTasksTest`
  test/src/test/java/hudson/model/queue/BuildKeepsRunningWhenFaultySubTasksTest.java
Labels: ready-for-merge, skip-changelog

#7174 De-flake `OfflineNodeCommandTest`
  test/src/test/java/hudson/cli/OfflineNodeCommandTest.java
Labels: skip-changelog

#7149 De-flake `PingThreadTest`
  test/src/test/java/hudson/slaves/PingThreadTest.java
Labels: ready-for-merge, skip-changelog

#7186 More informative error message when `ViewDescriptorTest` fails
  test/src/test/java/hudson/model/ViewDescriptorTest.java
Labels: ready-for-merge, skip-changelog

#7170 De-flake `RepeatableTest`
  test/src/test/java/lib/form/RepeatableTest.java
Labels: ready-for-merge, skip-changelog

#7188 Relax assertion in `InitMilestoneTest`
  test/src/test/java/hudson/init/InitMilestoneTest.java
Labels: ready-for-merge, skip-changelog

#7175 Upgrade bundled Instance Identity plugin from 3.1 to 116.vf8f487400980
  war/pom.xml
Labels: ready-for-merge, dependencies, java
