Repository jenkinsci/jenkins, pull requests merged in 2023-09, with the labels that each got.

#8453 [JENKINS-71950] List plugins in deterministic order
  core/src/main/java/hudson/init/InitStrategy.java
Labels: ready-for-merge, rfe

#8447 Upgrade to winstone 6.13 which upgrades to Jetty 10.0.16
  pom.xml
  war/pom.xml
Labels: ready-for-merge, dependencies

#8446 Turkish localization fixes for the new job page
  core/src/main/resources/hudson/model/Messages_tr.properties
  core/src/main/resources/hudson/model/View/newJobButtonBar_tr.properties
  core/src/main/resources/hudson/model/View/newJob_tr.properties
Labels: ready-for-merge, localization

#8448 Label parsing robustness fix
  core/src/main/java/hudson/model/Slave.java
  test/src/test/java/jenkins/model/NodesRestartTest.java
Labels: regression-fix, ready-for-merge, major-bug

#8457 Backporting for LTS 2.414.2
  core/src/main/java/hudson/console/PlainTextConsoleOutputStream.java
  core/src/main/java/hudson/model/DirectoryBrowserSupport.java
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/signup.jelly
  core/src/main/resources/jenkins/model/DefaultSimplePageDecorator/simple-header.jelly
  core/src/main/resources/jenkins/model/Jenkins/login.jelly
  test/src/test/java/hudson/console/AnnotatedLargeTextTest.java
  war/src/main/scss/abstracts/theme.scss
Labels: into-lts

#8460 [JENKINS-71958] Update scriptConsole_tr.properties
  core/src/main/resources/lib/hudson/scriptConsole_tr.properties
Labels: skip-changelog

#8467 Avoid usage of Guava from `ProcessTree`
  core/src/main/java/hudson/util/ProcessTree.java
Labels: ready-for-merge, skip-changelog

#8469 update badge documentation
  core/src/main/java/jenkins/management/Badge.java
  core/src/main/resources/lib/layout/task.jelly
Labels: ready-for-merge, skip-changelog

#8462 Make branding overridable in signin/login page
  core/src/main/java/jenkins/model/SimplePageDecorator.java
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/signup.jelly
  core/src/main/resources/jenkins/model/Jenkins/login.jelly
  core/src/main/resources/jenkins/model/SimplePageDecorator/simple-branding.jelly
  core/src/main/resources/jenkins/model/SimplePageDecorator/simple-head.jelly
  core/src/main/resources/jenkins/model/SimplePageDecorator/simple-header.jelly
  core/src/main/resources/jenkins/model/SimplePageDecorator/simple-header_fr.properties
  core/src/main/resources/jenkins/model/SimplePageDecorator/simple-header_it.properties
  core/src/main/resources/jenkins/model/SimplePageDecorator/simple-header_ja.properties
  core/src/main/resources/jenkins/model/SimplePageDecorator/simple-header_pl.properties
  core/src/main/resources/jenkins/model/SimplePageDecorator/simple-header_pt_BR.properties
  core/src/main/resources/jenkins/model/SimplePageDecorator/simple-header_tr.properties
  core/src/main/resources/jenkins/model/SimplePageDecorator/simple-header_zh_TW.properties
Labels: ready-for-merge, web-ui, developer

#8381 Move Node monitoring option to app bar
  core/src/main/resources/hudson/model/ComputerSet/configure.jelly
  core/src/main/resources/hudson/model/ComputerSet/configure.properties
  core/src/main/resources/hudson/model/ComputerSet/index.jelly
  core/src/main/resources/hudson/model/ComputerSet/sidepanel.jelly
  test/src/test/java/hudson/model/ComputerSetTest.java
Labels: ready-for-merge, web-ui, rfe, security-approved, ath-successful, pct-successful

#8427 Add test for SECURITY-3135
  test/src/test/java/jenkins/security/Security3135Test.java
  test/src/test/resources/jenkins/security/Security3135Test/ViewHolder/index.jelly
Labels: ready-for-merge, skip-changelog

#8472 Prevent scrolling for textarea preview
  core/src/main/resources/lib/form/textarea/textarea.js
Labels: ready-for-merge, skip-changelog

#8471 [JENKINS-71983] allow symbols in MenuItem#withIconClass
  core/src/main/java/jenkins/model/ModelObjectWithContextMenu.java
Labels: ready-for-merge, bug

#8481 `StringIndexOutOfBoundsException` in `AbstractItem.getUrl`
  core/src/main/java/hudson/model/AbstractItem.java
  test/src/test/java/jenkins/widgets/BuildListTableTest.java
Labels: ready-for-merge, skip-changelog

#8484 Increase minimum required Remoting version from 4.7 to 4.13
  pom.xml
  test/pom.xml
Labels: ready-for-merge, rfe

#8486 Migrate from deprecated finalization API to Java 9+ API
  core/src/main/java/hudson/util/AtomicFileWriter.java
  core/src/main/java/hudson/util/FileChannelWriter.java
  core/src/test/java/hudson/util/AtomicFileWriterTest.java
  test/src/test/java/hudson/util/AtomicFileWriterTest.java
Labels: ready-for-merge, skip-changelog

#8487 Remove usages of deprecated `ThreadDeath`
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/model/listeners/SaveableListener.java
Labels: ready-for-merge, skip-changelog

#8488 Remove finalization from `RegistryKey`
  core/src/main/java/hudson/util/jna/RegistryKey.java
Labels: ready-for-merge, skip-changelog

#8489 LogRecorder programmatic deletion support
  core/src/main/java/hudson/logging/LogRecorder.java
  test/src/test/java/hudson/logging/LogRecorderManagerTest.java
Labels: ready-for-merge, developer

#8490 [JENKINS-72016] Define a thread pool for `ProxyConfiguration`’s `HttpClient`
  core/src/main/java/hudson/ProxyConfiguration.java
  test/src/test/java/hudson/ProxyConfigurationTest.java
Labels: ready-for-merge, bug

#8493 [JENKINS-71880] fix notification in breadcrumb
  war/src/main/js/components/dropdowns/jumplists.js
Labels: regression-fix, ready-for-merge

#8497 Add the 'alt' attribute to the logo in the README.md
  README.md
Labels: ready-for-merge, skip-changelog, squash-merge-me

#8501 [chore] Remove useless TODO
  core/src/main/java/org/acegisecurity/Authentication.java
Labels: ready-for-merge, skip-changelog

#8504 Use functionality from `XStream2` where possible
  core/src/main/java/jenkins/install/InstallUtil.java
  core/src/test/java/hudson/util/RobustReflectionConverterTest.java
  test/src/test/java/jenkins/security/ClassFilterImplTest.java
Labels: ready-for-merge, skip-changelog

#8506 Fix typo in container-debug.js
  war/src/main/webapp/scripts/yui/container/container-debug.js
Labels: ready-for-merge, skip-changelog

#8474 fix signup autofocus
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/signup.jelly
Labels: regression-fix, ready-for-merge

#8512 Ignore `ProxyConfigurationTest.httpClientExecutor`
  test/src/test/java/hudson/ProxyConfigurationTest.java
Labels: skip-changelog

#8509 Explicit log levels
  core/src/main/resources/hudson/logging/LogRecorderManager/all.jelly
Labels: ready-for-merge, skip-changelog

#8514 fix(typo): adjust typos in pt br translation of plugin setup wizard
  core/src/main/resources/jenkins/install/pluginSetupWizard_pt_BR.properties
Labels: skip-changelog

#8510 Turkish localizations for the clouds page
  core/src/main/resources/jenkins/agents/CloudSet/index_tr.properties
  core/src/main/resources/jenkins/agents/Messages_tr.properties
  core/src/main/resources/jenkins/model/Messages_tr.properties
Labels: skip-changelog

#8496 [JENKINS-71866] Allow to use alternate values for "Build with Parameters" and the "Build" button on the parameters page
  core/src/main/java/hudson/model/ParametersDefinitionProperty.java
  core/src/main/java/jenkins/model/ParameterizedJobMixIn.java
  core/src/main/resources/hudson/model/Messages.properties
  core/src/main/resources/hudson/model/Messages_bg.properties
  core/src/main/resources/hudson/model/Messages_da.properties
  core/src/main/resources/hudson/model/Messages_es.properties
  core/src/main/resources/hudson/model/Messages_et.properties
  core/src/main/resources/hudson/model/Messages_it.properties
  core/src/main/resources/hudson/model/Messages_ja.properties
  core/src/main/resources/hudson/model/Messages_ko.properties
  core/src/main/resources/hudson/model/Messages_nl.properties
  core/src/main/resources/hudson/model/Messages_pl.properties
  core/src/main/resources/hudson/model/Messages_pt_BR.properties
  core/src/main/resources/hudson/model/Messages_ru.properties
  core/src/main/resources/hudson/model/Messages_sk.properties
  core/src/main/resources/hudson/model/Messages_sr.properties
  core/src/main/resources/hudson/model/Messages_sv_SE.properties
  core/src/main/resources/hudson/model/Messages_tr.properties
  core/src/main/resources/hudson/model/Messages_zh_TW.properties
  core/src/main/resources/hudson/model/ParametersDefinitionProperty/index.jelly
  core/src/main/resources/hudson/model/ParametersDefinitionProperty/index_bg.properties
  core/src/main/resources/hudson/model/ParametersDefinitionProperty/index_da.properties
  core/src/main/resources/hudson/model/ParametersDefinitionProperty/index_de.properties
  core/src/main/resources/hudson/model/ParametersDefinitionProperty/index_es.properties
  core/src/main/resources/hudson/model/ParametersDefinitionProperty/index_et.properties
  core/src/main/resources/hudson/model/ParametersDefinitionProperty/index_fr.properties
  core/src/main/resources/hudson/model/ParametersDefinitionProperty/index_it.properties
  core/src/main/resources/hudson/model/ParametersDefinitionProperty/index_ja.properties
  core/src/main/resources/hudson/model/ParametersDefinitionProperty/index_ko.properties
  core/src/main/resources/hudson/model/ParametersDefinitionProperty/index_nl.properties
  core/src/main/resources/hudson/model/ParametersDefinitionProperty/index_pl.properties
  core/src/main/resources/hudson/model/ParametersDefinitionProperty/index_pt_BR.properties
  core/src/main/resources/hudson/model/ParametersDefinitionProperty/index_ru.properties
  core/src/main/resources/hudson/model/ParametersDefinitionProperty/index_sk.properties
  core/src/main/resources/hudson/model/ParametersDefinitionProperty/index_sr.properties
  core/src/main/resources/hudson/model/ParametersDefinitionProperty/index_sv_SE.properties
  core/src/main/resources/hudson/model/ParametersDefinitionProperty/index_tr.properties
  core/src/main/resources/hudson/model/ParametersDefinitionProperty/index_zh_TW.properties
Labels: ready-for-merge, rfe

#8520 Fix compilation error with `maven.compiler.release=21`
  core/src/main/java/hudson/tasks/Publisher.java
Labels: ready-for-merge, skip-changelog

#8519 Turkish localization for "Build with Parameters" link
  core/src/main/resources/hudson/model/Messages_tr.properties
  core/src/main/resources/jenkins/model/Messages_tr.properties
Labels: ready-for-merge, skip-changelog

#8491 [JENKINS-72018] Form entries in .repeated-chunk using .show-if-not-only CSS class are not hidden when they are alone
  war/src/main/scss/form/_reorderable-list.scss
Labels: regression-fix, ready-for-merge, bug, squash-merge-me

#8485 [JENKINS-71890] Model links in build history views and administrative monitors no longer work
  war/src/main/js/components/dropdowns/jumplists.js
Labels: regression-fix, ready-for-merge, bug

#8513 Logging XmlFile write to help track race conditions during tests.
  core/src/main/java/hudson/XmlFile.java
Labels: ready-for-merge, skip-changelog

#8511 Add data-bound setters for View
  core/src/main/java/hudson/model/View.java
  core/src/main/resources/hudson/model/View/configure.jelly
  test/src/test/java/hudson/model/ViewDescriptorTest.java
  test/src/test/java/hudson/model/ViewTest.java
Labels: ready-for-merge, bug, developer

#8473 Use `isEmpty()` and simplified assertions in Test
  test/src/test/java/hudson/PluginManagerTest.java
  test/src/test/java/hudson/cli/ReloadConfigurationCommandTest.java
  test/src/test/java/hudson/model/FingerprintCleanupThreadTest.java
  test/src/test/java/hudson/model/HelpLinkTest.java
  test/src/test/java/hudson/model/JobTest.java
  test/src/test/java/hudson/model/LabelLoadStatisticsQueueLengthTest.java
  test/src/test/java/hudson/node_monitors/ClockMonitorDescriptorTest.java
  test/src/test/java/lib/hudson/ListScmBrowsersTest.java
Labels: ready-for-merge, skip-changelog

#8482 [JEP-237] introduce FIPS property
  core/src/main/java/jenkins/security/FIPS140.java
Labels: ready-for-merge, developer

#8503 Remove KXML2 library
  bom/pom.xml
  core/pom.xml
  test/src/test/java/jenkins/ClassPathTest.java
Labels: ready-for-merge, removed, pct-successful

#8532 Tweak changelog entry placeholder
  .github/PULL_REQUEST_TEMPLATE.md
Labels: skip-changelog

#8530 Fill in since annotations
  core/src/main/java/hudson/logging/LogRecorder.java
  core/src/main/java/hudson/util/HudsonIsRestarting.java
  core/src/main/java/jenkins/cli/SafeRestartCommand.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/model/ModelObjectWithContextMenu.java
  core/src/main/resources/lib/form/submit.jelly
  core/src/main/resources/lib/layout/delete.jelly
Labels: skip-changelog

#8529 [JENKINS-72067] High memory usage from `XStream2.AssociatedConverterImpl`
  core/src/main/java/hudson/util/XStream2.java
Labels: regression-fix, ready-for-merge

#8528 Avoid saving disabled status when deleting a project
  core/src/main/java/hudson/model/AbstractProject.java
Labels: ready-for-merge, rfe

#8526 Automate Java version recommendation administrative monitor
  core/src/main/java/jenkins/monitor/JavaVersionRecommendationAdminMonitor.java
  core/src/main/resources/jenkins/monitor/JavaVersionRecommendationAdminMonitor/description.jelly
  core/src/main/resources/jenkins/monitor/JavaVersionRecommendationAdminMonitor/description.properties
  core/src/main/resources/jenkins/monitor/JavaVersionRecommendationAdminMonitor/description_pt_BR.properties
  core/src/main/resources/jenkins/monitor/JavaVersionRecommendationAdminMonitor/description_ru.properties
  core/src/main/resources/jenkins/monitor/JavaVersionRecommendationAdminMonitor/description_zh_TW.properties
  core/src/main/resources/jenkins/monitor/JavaVersionRecommendationAdminMonitor/message.jelly
  core/src/main/resources/jenkins/monitor/JavaVersionRecommendationAdminMonitor/message.properties
  core/src/main/resources/jenkins/monitor/JavaVersionRecommendationAdminMonitor/message_pt_BR.properties
  core/src/main/resources/jenkins/monitor/JavaVersionRecommendationAdminMonitor/message_ru.properties
  war/src/main/java/executable/Main.java
Labels: ready-for-merge, rfe
