Repository jenkinsci/jenkins, pull requests merged in 2023-10, with the labels that each got.

#7781 [JENKINS-70906] Remove prototype from core
  core/src/main/java/jenkins/model/experimentalflags/RemovePrototypeUserExperimentalFlag.java
  core/src/main/resources/jenkins/security/apitoken/LegacyApiTokenAdministrativeMonitor/resources.js
  core/src/main/resources/lib/layout/layout.jelly
  test/src/test/java/hudson/ExceptionTest.java
  test/src/test/resources/hudson/ExceptionTest/RootActionImpl/ajaxError.jelly
  test/src/test/resources/lib/form/JSON.js
  war/.eslintignore
  war/.prettierignore
  war/src/main/js/util/jenkins.js
  war/src/main/webapp/scripts/hudson-behavior.js
  war/src/main/webapp/scripts/prototype.js
Labels: ready-for-merge, major-rfe, squash-merge-me

#8543 Warn users of old Java version 18 months before end of life
  core/src/main/java/jenkins/monitor/JavaVersionRecommendationAdminMonitor.java
  core/src/main/resources/jenkins/monitor/JavaVersionRecommendationAdminMonitor/description.jelly
  core/src/main/resources/jenkins/monitor/JavaVersionRecommendationAdminMonitor/description.properties
  core/src/main/resources/jenkins/monitor/JavaVersionRecommendationAdminMonitor/description_pt_BR.properties
  core/src/main/resources/jenkins/monitor/JavaVersionRecommendationAdminMonitor/description_ru.properties
  core/src/main/resources/jenkins/monitor/JavaVersionRecommendationAdminMonitor/description_zh_TW.properties
Labels: skip-changelog

#8549 Fix encoding of Brazilian Portuguese localization
  core/src/main/resources/jenkins/monitor/JavaVersionRecommendationAdminMonitor/description_pt_BR.properties
Labels: skip-changelog

#8553 Tweak changelog guidance in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: skip-changelog

#8539 add gitter link
  README.md
Labels: hacktoberfest, skip-changelog

#8531 Allow location of `queue.xml` to be overridden
  core/src/main/java/hudson/model/Queue.java
Labels: ready-for-merge, skip-changelog

#8542 Backporting for 2.414.3
  bom/pom.xml
  core/src/main/java/hudson/ProxyConfiguration.java
  core/src/main/java/hudson/util/XStream2.java
  core/src/main/java/jenkins/telemetry/impl/SecurityConfiguration.java
  core/src/main/resources/jenkins/telemetry/impl/SecurityConfiguration/description.jelly
  test/src/test/java/hudson/ProxyConfigurationTest.java
  war/src/main/js/components/dropdowns/jumplists.js
Labels: into-lts

#8483 [JEP-237] Disable usage stats in fips mode
  core/src/main/java/hudson/model/UsageStatistics.java
  core/src/main/resources/hudson/model/UsageStatistics/global.groovy
  core/src/main/resources/hudson/model/UsageStatistics/global.properties
  core/src/main/resources/hudson/model/UsageStatistics/help-usageStatisticsCollected.jelly
Labels: ready-for-merge, rfe

#8422 [JENKINS-71252][JENKINS-70793] Multiple form validation fixes
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: regression-fix, ready-for-merge, bug

#8393 [JENKINS-71971][JEP-237] FIPS-140 compliant version of HudsonPrivateSecurityRealm
  core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java
  core/src/main/java/hudson/security/PasswordHashEncoder.java
  core/src/test/java/hudson/security/HudsonPrivateSecurityRealmTest.java
  test/src/test/java/hudson/security/HudsonPrivateSecurityRealmFIPSTest.java
  test/src/test/java/hudson/security/HudsonPrivateSecurityRealmTest.java
Labels: ready-for-merge, squash-merge-me, security-approved, fips

#7056 [JENKINS-41516] Add script console listener (alternative/extended proposal)
  core/src/main/java/hudson/cli/GroovyCommand.java
  core/src/main/java/hudson/cli/GroovyshCommand.java
  core/src/main/java/hudson/util/RemotingDiagnostics.java
  core/src/main/java/jenkins/util/DefaultScriptListener.java
  core/src/main/java/jenkins/util/ScriptListener.java
  core/src/main/java/jenkins/util/groovy/GroovyHookScript.java
  test/src/test/java/jenkins/model/ScriptListenerTest.java
Labels: ready-for-merge, squash-merge-me, developer

#8563 Merge back test for 2023-09-20 release
  test/src/test/java/hudson/PluginManagerSecurity3072Test.java
  test/src/test/java/hudson/PluginManagerTest.java
  test/src/test/java/jenkins/model/JenkinsSecurity3073Test.java
  test/src/test/java/jenkins/model/JenkinsTest.java
Labels: ready-for-merge, skip-changelog

#8574 Fix tests that the PR build did not run on Windows
  test/src/test/java/jenkins/model/ScriptListenerTest.java
Labels: regression-fix, skip-changelog

#8554 Actually adjust copy button logic to new API
  core/src/main/resources/lib/layout/copyButton/copyButton.js
Labels: ready-for-merge, skip-changelog, hacktoberfest-accepted, security-approved

#8564 [JENKINS-71937] Fix deprecated `Slave` constructor
  core/src/main/java/hudson/model/Slave.java
Labels: regression-fix, ready-for-merge

#8571 Update Node.js from 18.x to 20.x
  .github/renovate.json
  CONTRIBUTING.md
  war/pom.xml
Labels: skip-changelog

#8557 [JENKINS-72114] Fix serialization of `HudsonPrivateSecurityRealm.UserDetailsImpl`
  core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java
Labels: ready-for-merge, developer, security-approved

#8573 Add note that general usage statistics submission is disabled with FIPS
  core/src/main/resources/hudson/model/UsageStatistics/global.groovy
  core/src/main/resources/hudson/model/UsageStatistics/global.properties
Labels: ready-for-merge, skip-changelog

#8572 Link to jenkins.io/redirect URL, not directly into docs
  core/src/main/resources/hudson/model/UsageStatistics/global.properties
Labels: skip-changelog

#8569 [JENKINS-72028] at ` test/src/test/java/hudson/` replace deprecated `URL()`
  test/src/test/java/hudson/TcpSlaveAgentListenerTest.java
  test/src/test/java/hudson/diagnosis/HudsonHomeDiskUsageMonitorTest.java
  test/src/test/java/hudson/jobs/CreateItemTest.java
  test/src/test/java/hudson/markup/MarkupFormatterTest.java
  test/src/test/java/hudson/model/AbstractProjectTest.java
  test/src/test/java/hudson/model/DirectlyModifiableViewTest.java
  test/src/test/java/hudson/model/HudsonTest.java
  test/src/test/java/hudson/model/ItemsTest.java
  test/src/test/java/hudson/model/ProjectTest.java
  test/src/test/java/hudson/model/QueueTest.java
  test/src/test/java/hudson/model/UpdateCenterTest.java
  test/src/test/java/hudson/model/UpdateSiteTest.java
  test/src/test/java/hudson/model/UserRestartTest.java
  test/src/test/java/hudson/security/HudsonPrivateSecurityRealmTest.java
  test/src/test/java/hudson/security/csrf/DefaultCrumbIssuerTest.java
  test/src/test/java/hudson/util/RobustReflectionConverterTest.java
Labels: ready-for-merge, hacktoberfest, skip-changelog, squash-merge-me, java, tests

#8570 [JENKINS-72028] at `test/src/test/java/jenkins/` replace deprecated `URL()`
  test/src/test/java/jenkins/model/AssetManagerTest.java
  test/src/test/java/jenkins/model/JenkinsTest.java
  test/src/test/java/jenkins/security/ApiTokenPropertyTest.java
  test/src/test/java/jenkins/security/BasicHeaderApiTokenAuthenticatorTest.java
  test/src/test/java/jenkins/security/ResourceDomainTest.java
  test/src/test/java/jenkins/security/Security2761Test.java
  test/src/test/java/jenkins/security/Security637Test.java
  test/src/test/java/jenkins/security/apitoken/ApiTokenStatsRestartTest.java
  test/src/test/java/jenkins/security/apitoken/ApiTokenStatsTest.java
  test/src/test/java/jenkins/security/seed/UserSeedChangeListenerTest.java
  test/src/test/java/jenkins/security/seed/UserSeedPropertyRestartTest.java
  test/src/test/java/jenkins/security/seed/UserSeedPropertyTest.java
  test/src/test/java/jenkins/security/stapler/Security400Test.java
  test/src/test/java/jenkins/security/stapler/Security914Test.java
Labels: ready-for-merge, skip-changelog, hacktoberfest-accepted

#8577 [JENKINS-72141] French translation
  core/src/main/resources/hudson/model/Messages_fr.properties
  core/src/main/resources/jenkins/model/Jenkins/login.jelly
  core/src/main/resources/jenkins/model/Jenkins/login_fr.properties
  core/src/main/resources/jenkins/model/Messages_fr.properties
  core/src/main/resources/lib/hudson/executors_fr.properties
Labels: ready-for-merge, localization, hacktoberfest-accepted

#8587 [JENKINS-72156] Upgrade to Winstone 6.14 which contains an upgrade to Jetty 10.0.17
  pom.xml
  war/pom.xml
Labels: ready-for-merge, rfe, developer

#8565 [JENKINS-72028] replace deprecated `URL()` at `core/src/main/java/hudson/`
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/Main.java
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/TcpSlaveAgentListener.java
  core/src/main/java/hudson/cli/InstallPluginCommand.java
  core/src/main/java/hudson/model/DownloadService.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/java/hudson/tools/ZipExtractionInstaller.java
Labels: ready-for-merge, hacktoberfest, skip-changelog, squash-merge-me, hacktoberfest-accepted, java

#8568 [JENKINS-72028] replace deprecated `URL()` at `core/src/main/java/jenkins/`
  core/src/main/java/jenkins/install/SetupWizard.java
  core/src/main/java/jenkins/security/ResourceDomainConfiguration.java
Labels: ready-for-merge, skip-changelog, hacktoberfest-accepted

#8578 [JENKINS-72143] French translation
  core/src/main/resources/hudson/Messages_fr.properties
Labels: ready-for-merge, hacktoberfest, localization

#8588 Restrict helper classes in `ScriptListener` for internal use
  core/src/main/java/jenkins/util/ScriptListener.java
Labels: ready-for-merge, skip-changelog

#8492 [JENKINS-72020] Restore ability to reorder clouds
  core/src/main/java/jenkins/agents/CloudSet.java
  core/src/main/resources/jenkins/agents/CloudSet/index.jelly
  core/src/main/resources/jenkins/agents/CloudSet/index.properties
  war/src/main/js/pages/cloud-set/index.js
  war/src/main/js/pages/cloud-set/index.scss
  war/src/main/js/sortable-drag-drop.js
  war/webpack.config.js
Labels: regression-fix, ready-for-merge, web-ui, security-approved

#8598 Stop testing Java 19 on stable-2.414 branch
  Jenkinsfile
Labels: into-lts

#8603 Remove unnecessary `<dependencyManagement>` entry
  test/pom.xml
Labels: skip-changelog

#8592 [JENKINS-72156] Backport Upgrade to Winstone 6.14 which contains an upgrade to Jetty 10.0.17
  pom.xml
  war/pom.xml
Labels: into-lts

#8589 [JENKINS-72111] Allow `Lifecycle` to load implementations from plugins
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/lifecycle/Lifecycle.java
  test/src/test/java/hudson/lifecycle/LifecycleTest.java
  test/src/test/resources/plugins/custom-lifecycle.hpi
Labels: ready-for-merge, developer

#8544 [JENKINS-72107] Introduce `Loadable` interface
  core/src/main/java/hudson/Plugin.java
  core/src/main/java/hudson/logging/LogRecorder.java
  core/src/main/java/hudson/model/AbstractItem.java
  core/src/main/java/hudson/model/Descriptor.java
  core/src/main/java/hudson/model/PersistentDescriptor.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/model/User.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/model/Loadable.java
Labels: ready-for-merge, developer

#8594 [JENKINS-72148] Add missing fr properties for win32errors
  core/src/main/resources/hudson/win32errors_fr.properties
Labels: ready-for-merge, hacktoberfest, localization

#8586 [JENKINS-72148] Add missing fr properties in hudson directory
  core/src/main/resources/hudson/PluginManager/PluginCycleDependenciesMonitor/description_fr.properties
  core/src/main/resources/hudson/PluginManager/PluginCycleDependenciesMonitor/message_fr.properties
  core/src/main/resources/hudson/PluginManager/PluginDeprecationMonitor/description_fr.properties
  core/src/main/resources/hudson/PluginManager/PluginDeprecationMonitor/message_fr.properties
  core/src/main/resources/hudson/PluginManager/PluginUpdateMonitor/description_fr.properties
  core/src/main/resources/hudson/PluginManager/PluginUpdateMonitor/message_fr.properties
  core/src/main/resources/hudson/PluginWrapper/PluginWrapperAdministrativeMonitor/description_fr.properties
  core/src/main/resources/hudson/PluginWrapper/PluginWrapperAdministrativeMonitor/message_fr.properties
  core/src/main/resources/hudson/PluginWrapper/uninstall_fr.properties
  core/src/main/resources/hudson/cli/Messages_fr.properties
  core/src/main/resources/hudson/diagnosis/HudsonHomeDiskUsageMonitor/description_fr.properties
  core/src/main/resources/hudson/diagnosis/NullIdDescriptorMonitor/description_fr.properties
  core/src/main/resources/hudson/diagnosis/NullIdDescriptorMonitor/message_fr.properties
  core/src/main/resources/hudson/diagnosis/OldDataMonitor/description_fr.properties
  core/src/main/resources/hudson/diagnosis/ReverseProxySetupMonitor/description_fr.properties
  core/src/main/resources/hudson/diagnosis/TooManyJobsButNoView/description_fr.properties
  core/src/main/resources/hudson/init/impl/Messages_fr.properties
  core/src/main/resources/hudson/markup/EscapedMarkupFormatter/config_fr.properties
  core/src/main/resources/hudson/markup/Messages_fr.properties
  core/src/main/resources/hudson/model/Cause/RemoteCause/description_fr.properties
  core/src/main/resources/hudson/model/Computer/markOffline_fr.properties
  core/src/main/resources/hudson/model/Computer/setOfflineCause_fr.properties
  core/src/main/resources/hudson/model/Job/requirePOST_fr.properties
  core/src/main/resources/hudson/model/PasswordParameterValue/value_fr.properties
  core/src/main/resources/hudson/model/Run/delete-retry_fr.properties
  core/src/main/resources/hudson/model/TimeZoneProperty/config_fr.properties
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/description_fr.properties
  core/src/main/resources/hudson/model/View/main_fr.properties
  core/src/main/resources/hudson/model/View/newJobButtonBar_fr.properties
  core/src/main/resources/hudson/model/queue/CauseOfBlockage/BecauseLabelIsBusy/summary_fr.properties
  core/src/main/resources/hudson/model/queue/CauseOfBlockage/BecauseLabelIsOffline/summary_fr.properties
  core/src/main/resources/hudson/model/queue/CauseOfBlockage/BecauseNodeIsBusy/summary_fr.properties
  core/src/main/resources/hudson/model/queue/CauseOfBlockage/BecauseNodeIsOffline/summary_fr.properties
  core/src/main/resources/hudson/model/queue/Messages_fr.properties
  core/src/main/resources/hudson/node_monitors/MonitorMarkedNodeOffline/description_fr.properties
  core/src/main/resources/hudson/security/FederatedLoginService/UnclaimedIdentityException/error_fr.properties
  core/src/main/resources/hudson/security/csrf/CrumbFilter/retry_fr.properties
  core/src/main/resources/hudson/security/csrf/Messages_fr.properties
  core/src/main/resources/hudson/slaves/Cloud/configure_fr.properties
  core/src/main/resources/hudson/slaves/Cloud/index_fr.properties
  core/src/main/resources/hudson/slaves/Cloud/sidepanel_fr.properties
  core/src/main/resources/hudson/slaves/DumbSlave/newInstanceDetail_fr.properties
  core/src/main/resources/hudson/slaves/JNLPLauncher/help_fr.properties
  core/src/main/resources/hudson/slaves/SlaveComputer/threadDump_fr.properties
  core/src/main/resources/hudson/tasks/Fingerprinter/help-defaultExcludes_fr.properties
  core/src/main/resources/hudson/triggers/SCMTrigger/AdministrativeMonitorImpl/description_fr.properties
  core/src/main/resources/hudson/triggers/SCMTrigger/AdministrativeMonitorImpl/message_fr.properties
  core/src/main/resources/hudson/triggers/SlowTriggerAdminMonitor/description_fr.properties
  core/src/main/resources/hudson/triggers/SlowTriggerAdminMonitor/message_fr.properties
  core/src/main/resources/hudson/util/DoubleLaunchChecker/description_fr.properties
  core/src/main/resources/hudson/util/IncompatibleVMDetected/index_fr.properties
  core/src/main/resources/hudson/util/InsufficientPermissionDetected/index_fr.properties
  core/src/main/resources/hudson/util/JenkinsReloadFailed/index_fr.properties
  core/src/main/resources/hudson/util/NoHomeDir/index_fr.properties
  core/src/main/resources/hudson/views/BuildButtonColumn/column_fr.properties
  core/src/main/resources/lib/form/secretTextarea_fr.properties
  core/src/main/resources/lib/hudson/projectView_fr.properties
Labels: ready-for-merge, hacktoberfest, localization

#8596 Add telemetry for Jenkins uptime
  core/src/main/java/jenkins/telemetry/impl/Uptime.java
  core/src/main/resources/jenkins/telemetry/impl/Uptime/description.jelly
Labels: ready-for-merge, rfe

#8602 [JENKINS-72170] fix nested hetero-list entries with mixture of inputs and buttons
  war/src/main/js/components/dropdowns/hetero-list.js
Labels: regression-fix, ready-for-merge

#8612 [JEP-237] Do not support shortening of HMAC code on FIPS mode
  core/src/main/java/jenkins/security/HMACConfidentialKey.java
  core/src/test/java/jenkins/security/HMACConfidentialKeyTest.java
  test/src/test/java/hudson/security/HMACConfidentialKeyFIPSTest.java
Labels: ready-for-merge, rfe, fips

#8606 [JENKINS-72179] Show description of boolean build parameter values
  core/src/main/resources/hudson/model/BooleanParameterValue/value.jelly
Labels: regression-fix, ready-for-merge

#8622 [JENKINS-72181] Restore flushed output for 'groovy' CLI command
  core/src/main/java/hudson/cli/GroovyCommand.java
  test/src/test/java/jenkins/model/ScriptListenerTest.java
Labels: regression-fix, ready-for-merge, bug

#8534 Diagnostics for `QuietDownCommandTest.quietDownShouldSuccessWithBlockPlusNonExpiredTimeoutAndRunningExecutor`
  test/src/test/java/hudson/cli/QuietDownCommandTest.java
Labels: ready-for-merge, skip-changelog

#8628 Rename Hudson to Jenkins in JavaDoc
  core/src/main/java/hudson/model/Descriptor.java
Labels: ready-for-merge, skip-changelog

#8621 Test of `JNLP4-connect-proxy` connection protocol
  test/src/test/java/jenkins/agents/JnlpProtocol4ProxyHandlerTest.java
Labels: skip-changelog

#8637 [JENKINS-72203] Revert jenkinsci/jenkins#8565
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/Main.java
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/TcpSlaveAgentListener.java
  core/src/main/java/hudson/cli/InstallPluginCommand.java
  core/src/main/java/hudson/model/DownloadService.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/java/hudson/tools/ZipExtractionInstaller.java
Labels: regression-fix

#8631 Turkish localization fixes for login and users management pages
  core/src/main/resources/hudson/model/User/sidepanel_tr.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/_entryForm_tr.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/addUser_tr.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/index_tr.properties
  core/src/main/resources/hudson/security/Messages_tr.properties
  core/src/main/resources/jenkins/management/Messages_tr.properties
  core/src/main/resources/jenkins/model/Jenkins/login_tr.properties
Labels: ready-for-merge, localization

#8630 Fix issues with help texts under security configuration
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/help-useSecurity.html
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/help-useSecurity_bg.html
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/help-useSecurity_de.html
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/help-useSecurity_fr.html
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/help-useSecurity_it.html
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/help-useSecurity_ja.html
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/help-useSecurity_pt_BR.html
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/help-useSecurity_ru.html
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/help-useSecurity_tr.html
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/help-useSecurity_zh_TW.html
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/index.groovy
Labels: ready-for-merge, localization, rfe

#8659 Update dependabot branch for LTS 2.426.x
  .github/dependabot.yml
Labels: skip-changelog

#8651 Turkish localization fixes for build page
  core/src/main/resources/hudson/model/AbstractBuild/tasks_tr.properties
  core/src/main/resources/hudson/model/Cause/UserIdCause/description_tr.properties
  core/src/main/resources/hudson/model/Run/configure_tr.properties
  core/src/main/resources/hudson/model/Run/confirmDelete_tr.properties
  core/src/main/resources/hudson/model/Run/delete_tr.properties
  core/src/main/resources/hudson/scm/SCM/project-changes_tr.properties
  core/src/main/resources/lib/hudson/project/console-link_tr.properties
Labels: ready-for-merge, localization

#8646 More helpful error message for `ExtensionList.lookupSingleton`
  core/src/main/java/hudson/ExtensionList.java
Labels: ready-for-merge, skip-changelog

#8633 [JENKINS-72222] Fix inconsistent wording between login page and security configuration
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/help-disableRememberMe.html
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/index.properties
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/index_tr.properties
Labels: ready-for-merge, bug

#8613 [JENKINS-72189] fix drag&drop handle for existing repeatables
  core/src/main/resources/lib/form/repeatable.jelly
Labels: regression-fix, ready-for-merge, ath-successful

#8658 Backporting for 2.426.1
  core/src/main/java/hudson/model/Slave.java
  core/src/main/java/jenkins/agents/CloudSet.java
  core/src/main/java/jenkins/telemetry/impl/Uptime.java
  core/src/main/resources/hudson/model/BooleanParameterValue/value.jelly
  core/src/main/resources/jenkins/agents/CloudSet/index.jelly
  core/src/main/resources/jenkins/agents/CloudSet/index.properties
  core/src/main/resources/jenkins/telemetry/impl/Uptime/description.jelly
  pom.xml
  war/pom.xml
  war/src/main/js/components/dropdowns/hetero-list.js
  war/src/main/js/pages/cloud-set/index.js
  war/src/main/js/pages/cloud-set/index.scss
  war/src/main/js/sortable-drag-drop.js
  war/src/main/webapp/scripts/hudson-behavior.js
  war/webpack.config.js
Labels: into-lts
