Repository jenkinsci/jenkins, pull requests merged in 2023-05, with the labels that each got.

#7906 JENKINS-70927 Remove unused projectViewNested
  core/src/main/resources/lib/hudson/projectView.jelly
  core/src/main/resources/lib/hudson/projectViewNested.jelly
  core/src/main/resources/lib/hudson/projectViewNested.js
Labels: ready-for-merge, web-ui, removed

#7904 JENKINS-70926 Remove Prototype Ajax.Request usage from project/configurable.jelly
  core/src/main/resources/lib/hudson/project/configurable.jelly
Labels: ready-for-merge, skip-changelog

#7899 JENKINS-70919 Remove Prototype Ajax.Request usage from UserSeedProperty
  core/src/main/resources/jenkins/security/seed/UserSeedProperty/resources.js
Labels: ready-for-merge, skip-changelog

#7870 [JENKINS-71115] Builds filter field doesn't use full width on sub 970px windows
  war/src/main/scss/form/search-bar.scss
Labels: regression-fix, ready-for-merge, web-ui

#7836 [JENKINS-70805] Remove `!important` from styles in `<pre>`
  war/src/main/scss/base/style.scss
  war/src/main/scss/form/codemirror.scss
Labels: ready-for-merge, web-ui, rfe

#7101 Remove WebSocket support for Jetty 9
  .idea/encodings.xml
  pom.xml
  war/pom.xml
  websocket/jetty9/pom.xml
  websocket/jetty9/src/main/java/jenkins/websocket/Jetty9Provider.java
Labels: ready-for-merge, removed

#7920 Drop reliance on GH-specific darkmode logic
  README.md
Labels: skip-changelog

#7895 JENKINS-70915 Remove Prototype Ajax.Request usage from BuildButtonColumn
  core/src/main/resources/hudson/views/BuildButtonColumn/icon.js
Labels: ready-for-merge, skip-changelog

#7896 JENKINS-70916 Remove Prototype Ajax.Request usage from AdministrativeMonitorsDecorator
  core/src/main/resources/jenkins/management/AdministrativeMonitorsDecorator/resources.js
Labels: ready-for-merge, skip-changelog

#7897 JENKINS-70918 Remove Prototype Ajax.Request usages from ApiTokenProperty
  core/src/main/resources/jenkins/security/ApiTokenProperty/resources.js
Labels: ready-for-merge, skip-changelog

#7898 JENKINS-70917 Remove Prototype Ajax.Request usage from LegacyApiTokenAdministrativeMonitor
  core/src/main/resources/jenkins/security/apitoken/LegacyApiTokenAdministrativeMonitor/resources.js
Labels: ready-for-merge, skip-changelog

#7900 JENKINS-70920 Remove Prototype Ajax.Request usage from combobox.js
  core/src/main/resources/lib/form/combobox/combobox.js
Labels: ready-for-merge, skip-changelog

#7903 JENKINS-70925 Remove Prototype Ajax.Request usage from progressive-text.js
  core/src/main/resources/lib/hudson/progressive-text.js
Labels: ready-for-merge, skip-changelog

#7894 JENKINS-70913 Remove Prototype Ajax.Request usage from UpdateCenter
  core/src/main/resources/hudson/model/UpdateCenter/update-center.js
Labels: ready-for-merge, skip-changelog

#7919 Fix Launchable test result collection
  Jenkinsfile
Labels: skip-changelog

#7935 [Jenkinsfile] Add source directory when recording coverage results
  Jenkinsfile
Labels: skip-changelog

#7770 Move plugins refresh button to app bar
  core/src/main/resources/hudson/PluginManager/_table.js
  core/src/main/resources/hudson/PluginManager/available.jelly
  core/src/main/resources/hudson/PluginManager/check.jelly
  core/src/main/resources/hudson/PluginManager/table.jelly
  test/src/test/java/hudson/PluginManagerCheckUpdateCenterTest.java
  test/src/test/java/hudson/PluginManagerTest.java
  test/src/test/java/hudson/PluginManagerUtil.java
  war/.eslintrc.js
  war/src/main/js/plugin-manager-ui.js
Labels: ready-for-merge, web-ui, rfe

#7915 Improve WebSocket `Provider` interface
  core/src/main/java/jenkins/websocket/WebSocketSession.java
  websocket/jetty10/src/main/java/jenkins/websocket/Jetty10Provider.java
  websocket/spi/src/main/java/jenkins/websocket/Provider.java
Labels: ready-for-merge, skip-changelog

#7916 Compile WebSocket SPI against more recent version of Servlet API
  .github/dependabot.yml
  core/pom.xml
  websocket/spi/pom.xml
Labels: ready-for-merge, skip-changelog

#7925 Deleting unused `ConfidentialStore.TEST`
  core/src/main/java/jenkins/security/ConfidentialStore.java
Labels: ready-for-merge, skip-changelog

#7929 [JENKINS-71190] Remove Prototype.js usages from `sortable.js`
  war/src/main/webapp/scripts/sortable.js
Labels: ready-for-merge, skip-changelog

#7928 [JENKINS-70945] [JENKINS-70967] Remove Prototype.js usages from `radioBlock.js`
  core/src/main/resources/lib/form/radioBlock/radioBlock.js
Labels: ready-for-merge, skip-changelog

#7933 Format `behavior.js`
  war/.prettierignore
  war/src/main/webapp/scripts/behavior.js
Labels: skip-changelog

#7931 Revert "[JENKINS-71089] Fix `hasHeader` attribute for `f:hetero-list`"
  core/src/main/resources/lib/form/hetero-list.jelly
Labels: regression-fix, ready-for-merge

#7924 [JENKINS-71182] Correct Unicode behavior of `XML_1_1`
  core/src/main/java/hudson/util/PrettyPrintWriter.java
  core/src/main/java/hudson/util/XStream2.java
  core/src/test/java/hudson/util/XStream2Test.java
Labels: regression-fix, ready-for-merge

#7930 [JENKINS-70940] [JENKINS-70963] Remove Prototype.js usages from `advanced.js`
  core/src/main/resources/lib/form/advanced/advanced.js
Labels: ready-for-merge, skip-changelog

#7940 Remove Prototype from `filter-build-history.js`
  war/src/main/js/filter-build-history.js
Labels: ready-for-merge, skip-changelog

#7943 Remove Prototype from various form elements
  core/src/main/resources/lib/form/apply/apply.js
  core/src/main/resources/lib/form/confirm.js
  core/src/main/resources/lib/form/hetero-list/hetero-list.js
  core/src/main/resources/lib/form/repeatable/repeatable.js
  core/src/main/resources/lib/form/select/select.js
  core/src/main/resources/lib/form/textarea/textarea.js
Labels: ready-for-merge, skip-changelog

#7941 Remove Prototype from `_table.js`
  core/src/main/resources/hudson/PluginManager/_table.js
Labels: ready-for-merge, skip-changelog

#7944 Remove Prototype from miscellaneous files
  core/src/main/resources/hudson/PluginManager/installed.jelly
  core/src/main/resources/hudson/model/View/AsynchPeople/people-resources.js
  core/src/main/resources/jenkins/security/ApiTokenProperty/resources.js
  core/src/main/resources/jenkins/security/apitoken/LegacyApiTokenAdministrativeMonitor/resources.js
  core/src/main/resources/jenkins/security/seed/UserSeedProperty/resources.js
  core/src/main/resources/lib/hudson/build-caption.js
  core/src/main/resources/lib/hudson/progressive-text.js
Labels: ready-for-merge, skip-changelog

#7934 [JENKINS-70972] [JENKINS-70973] [JENKINS-70974] Reduce usages of Prot…
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, skip-changelog

#7922 [JENKINS-71177] modal with title for legend
  core/src/main/resources/jenkins/model/Jenkins/_legend.jelly
  core/src/main/resources/jenkins/model/Jenkins/_legend_de.properties
  core/src/main/resources/lib/hudson/rssBar.jelly
  core/src/main/resources/lib/hudson/rssBar.properties
  war/src/main/js/components/modals/index.js
  war/src/main/js/pages/dashboard/index.js
  war/src/main/scss/modules/modals.scss
Labels: ready-for-merge, web-ui, rfe

#7872 Revamp the sign in and register pages
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/signup.jelly
  core/src/main/resources/jenkins/model/DefaultSimplePageDecorator/simple-head.jelly
  core/src/main/resources/jenkins/model/DefaultSimplePageDecorator/simple-header.jelly
  core/src/main/resources/jenkins/model/Jenkins/login.jelly
  war/src/main/js/pages/register/index.js
  war/src/main/js/util/i18n.js
  war/src/main/scss/form/input.scss
  war/src/main/scss/pages/sign-in-register.scss
  war/src/main/scss/simple-page.scss
  war/src/main/webapp/css/signup.css
  war/webpack.config.js
Labels: ready-for-merge, web-ui, major-rfe, security-approved

#7949 JENKINS-70922 Remove Prototype Ajax.Request usage from select.js
  core/src/main/resources/lib/form/select/select.js
  war/.eslintrc.js
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, skip-changelog

#7948 Add a user experimental flag to run Jenkins without Prototype.js
  core/src/main/java/jenkins/model/experimentalflags/RemovePrototypeUserExperimentalFlag.java
  core/src/main/resources/hudson/PluginManager/installed.jelly
  core/src/main/resources/jenkins/security/apitoken/LegacyApiTokenAdministrativeMonitor/resources.js
  core/src/main/resources/lib/form/repeatable/repeatable.js
  core/src/main/resources/lib/layout/layout.jelly
  test/src/test/resources/lib/form/JSON.js
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, developer

#7957 Remove Roboto font
  core/src/main/resources/hudson/AboutJenkins/index.jelly
  war/.eslintignore
  war/.gitignore
  war/.prettierignore
  war/src/main/fonts/google-fonts/roboto/LICENSE.txt
  war/src/main/fonts/google-fonts/roboto/css/roboto.css
  war/src/main/fonts/google-fonts/roboto/fonts/roboto-v15-greek_latin-ext_latin_vietnamese_cyrillic_greek-ext_cyrillic-ext-300.eot
  war/src/main/fonts/google-fonts/roboto/fonts/roboto-v15-greek_latin-ext_latin_vietnamese_cyrillic_greek-ext_cyrillic-ext-300.svg
  war/src/main/fonts/google-fonts/roboto/fonts/roboto-v15-greek_latin-ext_latin_vietnamese_cyrillic_greek-ext_cyrillic-ext-300.ttf
  war/src/main/fonts/google-fonts/roboto/fonts/roboto-v15-greek_latin-ext_latin_vietnamese_cyrillic_greek-ext_cyrillic-ext-300.woff
  war/src/main/fonts/google-fonts/roboto/fonts/roboto-v15-greek_latin-ext_latin_vietnamese_cyrillic_greek-ext_cyrillic-ext-300.woff2
  war/src/main/fonts/google-fonts/roboto/fonts/roboto-v15-greek_latin-ext_latin_vietnamese_cyrillic_greek-ext_cyrillic-ext-500.eot
  war/src/main/fonts/google-fonts/roboto/fonts/roboto-v15-greek_latin-ext_latin_vietnamese_cyrillic_greek-ext_cyrillic-ext-500.svg
  war/src/main/fonts/google-fonts/roboto/fonts/roboto-v15-greek_latin-ext_latin_vietnamese_cyrillic_greek-ext_cyrillic-ext-500.ttf
  war/src/main/fonts/google-fonts/roboto/fonts/roboto-v15-greek_latin-ext_latin_vietnamese_cyrillic_greek-ext_cyrillic-ext-500.woff
  war/src/main/fonts/google-fonts/roboto/fonts/roboto-v15-greek_latin-ext_latin_vietnamese_cyrillic_greek-ext_cyrillic-ext-500.woff2
  war/src/main/fonts/google-fonts/roboto/fonts/roboto-v15-greek_latin-ext_latin_vietnamese_cyrillic_greek-ext_cyrillic-ext-700.eot
  war/src/main/fonts/google-fonts/roboto/fonts/roboto-v15-greek_latin-ext_latin_vietnamese_cyrillic_greek-ext_cyrillic-ext-700.svg
  war/src/main/fonts/google-fonts/roboto/fonts/roboto-v15-greek_latin-ext_latin_vietnamese_cyrillic_greek-ext_cyrillic-ext-700.ttf
  war/src/main/fonts/google-fonts/roboto/fonts/roboto-v15-greek_latin-ext_latin_vietnamese_cyrillic_greek-ext_cyrillic-ext-700.woff
  war/src/main/fonts/google-fonts/roboto/fonts/roboto-v15-greek_latin-ext_latin_vietnamese_cyrillic_greek-ext_cyrillic-ext-700.woff2
  war/src/main/fonts/google-fonts/roboto/fonts/roboto-v15-greek_latin-ext_latin_vietnamese_cyrillic_greek-ext_cyrillic-ext-900.eot
  war/src/main/fonts/google-fonts/roboto/fonts/roboto-v15-greek_latin-ext_latin_vietnamese_cyrillic_greek-ext_cyrillic-ext-900.svg
  war/src/main/fonts/google-fonts/roboto/fonts/roboto-v15-greek_latin-ext_latin_vietnamese_cyrillic_greek-ext_cyrillic-ext-900.ttf
  war/src/main/fonts/google-fonts/roboto/fonts/roboto-v15-greek_latin-ext_latin_vietnamese_cyrillic_greek-ext_cyrillic-ext-900.woff
  war/src/main/fonts/google-fonts/roboto/fonts/roboto-v15-greek_latin-ext_latin_vietnamese_cyrillic_greek-ext_cyrillic-ext-900.woff2
  war/src/main/fonts/google-fonts/roboto/fonts/roboto-v15-greek_latin-ext_latin_vietnamese_cyrillic_greek-ext_cyrillic-ext-regular.eot
  war/src/main/fonts/google-fonts/roboto/fonts/roboto-v15-greek_latin-ext_latin_vietnamese_cyrillic_greek-ext_cyrillic-ext-regular.svg
  war/src/main/fonts/google-fonts/roboto/fonts/roboto-v15-greek_latin-ext_latin_vietnamese_cyrillic_greek-ext_cyrillic-ext-regular.ttf
  war/src/main/fonts/google-fonts/roboto/fonts/roboto-v15-greek_latin-ext_latin_vietnamese_cyrillic_greek-ext_cyrillic-ext-regular.woff
  war/src/main/fonts/google-fonts/roboto/fonts/roboto-v15-greek_latin-ext_latin_vietnamese_cyrillic_greek-ext_cyrillic-ext-regular.woff2
  war/src/main/scss/pluginSetupWizard.less
Labels: ready-for-merge, skip-changelog

#7952 [JENKINS-70907] Remove Prototype `Ajax.Updater` usage from `URICheckEncodingMonitor`
  core/src/main/resources/jenkins/diagnostics/URICheckEncodingMonitor/adjunct.js
Labels: ready-for-merge, skip-changelog

#7954 [JENKINS-70910] Remove `Prototype.Browser` usages from `hudson-behavior.js`
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, skip-changelog

#7955 [JENKINS-70947] Remove Prototype $ usage from `section_.js`
  core/src/main/resources/lib/form/section.jelly
  core/src/main/resources/lib/form/section_.js
Labels: ready-for-merge, skip-changelog

#7959 [JENKINS-71020] Remove Prototype usages from `buildTimeTrend_resources.js`
  core/src/main/resources/hudson/model/Job/buildTimeTrend_resources.js
  core/src/main/resources/lib/form/hetero-list/hetero-list.js
  war/.eslintrc.js
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, skip-changelog

#7958 Remove icomoon
  core/src/main/resources/jenkins/install/SetupWizard/authenticate-security-token.jelly
  war/.eslintignore
  war/.gitignore
  war/.prettierignore
  war/src/main/fonts/icomoon/css/icomoon.css
  war/src/main/fonts/icomoon/fonts/icomoon.eot
  war/src/main/fonts/icomoon/fonts/icomoon.svg
  war/src/main/fonts/icomoon/fonts/icomoon.ttf
  war/src/main/fonts/icomoon/fonts/icomoon.woff
  war/src/main/js/templates/welcomePanel.hbs
  war/src/main/scss/pluginSetupWizard.less
Labels: ready-for-merge, skip-changelog

#7972 Support clouds without a `config.jelly`
  core/src/main/resources/hudson/slaves/Cloud/configure.jelly
Labels: ready-for-merge, bug

#7966 Better assertion in `jenkins.model.lazy.Build`
  core/src/test/java/jenkins/model/lazy/Build.java
Labels: ready-for-merge, skip-changelog

#7956 Make the skip link visible
  core/src/main/resources/lib/layout/layout.jelly
  core/src/main/resources/lib/layout/main-panel.jelly
  war/src/main/scss/base/style.scss
  war/src/main/scss/modules/skip-link.scss
  war/src/main/scss/styles.scss
Labels: ready-for-merge, bug

#7946 Tidy up Plugins' Updates jelly
  core/src/main/resources/hudson/PluginManager/available.jelly
  core/src/main/resources/hudson/PluginManager/index.jelly
  core/src/main/resources/hudson/PluginManager/updates.jelly
  core/src/main/resources/hudson/PluginManager/updates.properties
  core/src/main/resources/hudson/PluginManager/updates_bg.properties
  core/src/main/resources/hudson/PluginManager/updates_ca.properties
  core/src/main/resources/hudson/PluginManager/updates_cs.properties
  core/src/main/resources/hudson/PluginManager/updates_da.properties
  core/src/main/resources/hudson/PluginManager/updates_de.properties
  core/src/main/resources/hudson/PluginManager/updates_es.properties
  core/src/main/resources/hudson/PluginManager/updates_es_AR.properties
  core/src/main/resources/hudson/PluginManager/updates_et.properties
  core/src/main/resources/hudson/PluginManager/updates_fi.properties
  core/src/main/resources/hudson/PluginManager/updates_fr.properties
  core/src/main/resources/hudson/PluginManager/updates_he.properties
  core/src/main/resources/hudson/PluginManager/updates_hu.properties
  core/src/main/resources/hudson/PluginManager/updates_it.properties
  core/src/main/resources/hudson/PluginManager/updates_ja.properties
  core/src/main/resources/hudson/PluginManager/updates_ko.properties
  core/src/main/resources/hudson/PluginManager/updates_lt.properties
  core/src/main/resources/hudson/PluginManager/updates_lv.properties
  core/src/main/resources/hudson/PluginManager/updates_nb_NO.properties
  core/src/main/resources/hudson/PluginManager/updates_nl.properties
  core/src/main/resources/hudson/PluginManager/updates_pl.properties
  core/src/main/resources/hudson/PluginManager/updates_pt_BR.properties
  core/src/main/resources/hudson/PluginManager/updates_pt_PT.properties
  core/src/main/resources/hudson/PluginManager/updates_ro.properties
  core/src/main/resources/hudson/PluginManager/updates_ru.properties
  core/src/main/resources/hudson/PluginManager/updates_sk.properties
  core/src/main/resources/hudson/PluginManager/updates_sr.properties
  core/src/main/resources/hudson/PluginManager/updates_sv_SE.properties
  core/src/main/resources/hudson/PluginManager/updates_tr.properties
  core/src/main/resources/hudson/PluginManager/updates_uk.properties
  core/src/main/resources/hudson/PluginManager/updates_zh_TW.properties
Labels: ready-for-merge, skip-changelog

#7962 Adjust form label padding
  core/src/main/resources/lib/form/textarea.jelly
  core/src/main/resources/lib/form/textarea/textarea.js
  war/src/main/scss/base/style.scss
  war/src/main/scss/form/layout.scss
  war/src/main/scss/form/textarea.scss
  war/src/main/scss/styles.scss
Labels: ready-for-merge, web-ui, rfe

#7951 [JENKINS-70931] Remove Prototype `Ajax.Request` usages from `hudson-behavior.js`
  test/src/test/java/hudson/tools/ZipExtractionInstallerTest.java
  war/.eslintrc.js
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, skip-changelog, security-approved

#7960 Remove fontawesome from setup wizard
  core/src/main/resources/hudson/AboutJenkins/index.jelly
  war/package.json
  war/src/main/fonts/font-awesome/css/LICENSE.txt
  war/src/main/fonts/font-awesome/css/font-awesome.css
  war/src/main/fonts/font-awesome/css/font-awesome.min.css
  war/src/main/fonts/font-awesome/fonts/FontAwesome.otf
  war/src/main/fonts/font-awesome/fonts/LICENSE.txt
  war/src/main/fonts/font-awesome/fonts/fontawesome-webfont.eot
  war/src/main/fonts/font-awesome/fonts/fontawesome-webfont.svg
  war/src/main/fonts/font-awesome/fonts/fontawesome-webfont.ttf
  war/src/main/fonts/font-awesome/fonts/fontawesome-webfont.woff
  war/src/main/fonts/font-awesome/fonts/fontawesome-webfont.woff2
  war/src/main/scss/pluginSetupWizard.less
  war/webpack.config.js
  war/yarn.lock
Labels: ready-for-merge, skip-changelog

#7975 Disable spotless groovy formatting
  pom.xml
Labels: ready-for-merge, skip-changelog

#7967 More useful logging in `Trigger`
  core/src/main/java/hudson/triggers/Trigger.java
Labels: ready-for-merge, skip-changelog

#7986 Fix delayedCheck for GET
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, skip-changelog

#7961 Convert `pluginSetupWizard.less` to SCSS
  .gitattributes
  .github/renovate.json
  war/.eslintignore
  war/.gitignore
  war/.prettierignore
  war/.stylelintrc.js
  war/package.json
  war/src/main/scss/_bootstrap.scss
  war/src/main/scss/pluginSetupWizard.scss
  war/src/main/webapp/bootstrap/config.json
  war/src/main/webapp/bootstrap/css/bootstrap-theme.css
  war/src/main/webapp/bootstrap/css/bootstrap-theme.min.css
  war/src/main/webapp/bootstrap/css/bootstrap.css
  war/src/main/webapp/bootstrap/css/bootstrap.min.css
  war/webpack.config.js
  war/yarn.lock
Labels: ready-for-merge, skip-changelog

#7994 Fix compiler warning for intentionally bad type in test
  core/src/test/java/jenkins/model/lazy/AbstractLazyLoadRunMapTest.java
Labels: skip-changelog

#7926 Introduce `jenkins.model.queue.QueueItem` interface
  core/src/main/java/hudson/model/Queue.java
  core/src/main/java/hudson/widgets/BuildHistoryWidget.java
  core/src/main/java/jenkins/model/queue/QueueItem.java
  core/src/main/java/jenkins/widgets/HistoryPageEntry.java
  core/src/main/java/jenkins/widgets/HistoryPageFilter.java
  core/src/main/resources/lib/hudson/queue.jelly
  core/src/test/java/hudson/model/MockItem.java
  core/src/test/java/jenkins/widgets/HistoryPageFilterTest.java
Labels: ready-for-merge, developer

#7976 Refinements to `AssociatedConverterImpl.cache`
  core/src/main/java/hudson/util/XStream2.java
Labels: ready-for-merge, rfe

#7993 Make Jenkins compile in Eclipse out of the box
  core/pom.xml
  core/src/test/java/hudson/model/RunTest.java
Labels: ready-for-merge, skip-changelog

#7990 Move to Guice 6
  .github/dependabot.yml
  bom/pom.xml
Labels: ready-for-merge, rfe, dependencies, java

#8003 Backporting to 2.401.1
  core/src/main/java/hudson/util/PrettyPrintWriter.java
  core/src/main/java/hudson/util/XStream2.java
  core/src/main/resources/hudson/model/DirectoryBrowserSupport/dir.jelly
  core/src/test/java/hudson/util/XStream2Test.java
  war/src/main/less/form/search-bar.less
Labels: into-lts

#8005 Replace hourglass tango icon with ionicon
  core/src/main/java/org/jenkins/ui/icon/IconSet.java
  core/src/main/resources/lib/hudson/executors.jelly
  core/src/main/resources/lib/hudson/queue.jelly
  war/src/main/resources/images/symbols/hourglass.svg
Labels: ready-for-merge, web-ui, skip-changelog

#8014 Remove use of Launchable shared library functionality
  Jenkinsfile
Labels: skip-changelog

#7982 [JENKINS-70922] Remove Prototype `Ajax.Request` usage from `select.js`
  core/src/main/resources/lib/form/select/select.js
Labels: ready-for-merge, skip-changelog

#8016 Collect Launchable test results on Windows
  Jenkinsfile
Labels: skip-changelog

#8018 Remove Prototype usages in `BehaviorTest`
  test/src/test/java/scripts/BehaviorTest.java
Labels: skip-changelog

#8008 Deprecate `Form.findMatchingInput` Prototype extension in favor of a new non-Prototype replacement
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, developer

#7892 Introduced utility `HttpServletFilter`
  core/src/main/java/hudson/util/PluginServletFilter.java
  core/src/main/java/jenkins/security/ResourceDomainFilter.java
  core/src/main/java/jenkins/telemetry/impl/UserLanguages.java
  core/src/main/java/jenkins/util/HttpServletFilter.java
Labels: ready-for-merge, developer

#7984 `AbstractItem#doReload` should not be calling `SaveableListener#fireOnChange`
  core/src/main/java/hudson/model/AbstractItem.java
  test/src/test/java/hudson/model/AbstractItemTest.java
Labels: ready-for-merge, developer

#7999 Broken `toArray` implementations in `BuildReferenceMapAdapter`
  core/src/main/java/jenkins/model/lazy/BuildReferenceMapAdapter.java
  core/src/test/java/jenkins/model/lazy/AbstractLazyLoadRunMapTest.java
Labels: ready-for-merge, bug

#8013 Make padding consistent and reduce padding on mobile
  war/src/main/scss/abstracts/theme.scss
  war/src/main/scss/base/breakpoints.scss
  war/src/main/scss/base/layout-commons.scss
  war/src/main/scss/base/style.scss
  war/src/main/scss/modules/app-bar.scss
  war/src/main/scss/modules/side-panel-tasks.scss
  war/src/main/scss/modules/side-panel-widgets.scss
  war/src/main/scss/modules/tabs.scss
  war/src/main/scss/pages/dashboard.scss
Labels: ready-for-merge, web-ui, skip-changelog

#8015 Replace disconnect and system info symbols for agents
  core/src/main/resources/hudson/slaves/SlaveComputer/sidepanel2.jelly
  war/src/main/resources/images/symbols/disconnect.svg
  war/src/main/resources/images/symbols/information-circle.svg
Labels: ready-for-merge, web-ui, rfe

#7997 Unrestrict `UserSeedChangeListener`
  core/src/main/java/jenkins/security/seed/UserSeedChangeListener.java
Labels: ready-for-merge, developer

#8006 Fixing file leaks in tests (preadapting to proposed `TemporaryDirectoryAllocator.dispose` change)
  test/src/test/java/hudson/LauncherTest.java
  test/src/test/java/hudson/model/DirectoryBrowserSupportTest.java
  test/src/test/java/hudson/model/QueueTest.java
Labels: ready-for-merge, skip-changelog

#8021 Extraneous `waitOnline` calls with `InboundAgentRule`
  test/src/test/java/hudson/bugs/JnlpAccessWithSecuredHudsonTest.java
  test/src/test/java/hudson/slaves/JNLPLauncherRealTest.java
  test/src/test/java/jenkins/agents/WebSocketAgentsTest.java
  test/src/test/java/jenkins/security/Security218Test.java
  test/src/test/java/jenkins/slaves/restarter/JnlpSlaveRestarterInstallerTest.java
Labels: ready-for-merge, skip-changelog

#8024 Address javadoc warning and setup quality gates
  Jenkinsfile
  core/src/main/java/jenkins/model/GlobalCloudConfiguration.java
Labels: skip-changelog

#8020 Implement Launchable subsetting
  Jenkinsfile
Labels: skip-changelog

#8026 Shift quality gates for javadoc warnings from 'new' to 'total
  Jenkinsfile
Labels: skip-changelog

#8027 Remove Launchable prototype code from LTS branch
  Jenkinsfile
Labels: into-lts

#7942 [JENKINS-71200] Fix elements property overload in ListView
  core/src/main/java/hudson/model/ListView.java
  core/src/main/resources/hudson/model/ListView/configure-entries.jelly
  test/src/test/java/hudson/model/ListViewTest.java
Labels: ready-for-merge, bug

#8040 Update hamcrest imports
  test/src/test/java/jenkins/bugs/Jenkins64991Test.java
Labels: skip-changelog

#8041 Revert hamcrest updates and related changes in 5db5ceb, 6d2f930, 6d2f930
  core/pom.xml
  pom.xml
  test/pom.xml
  test/src/test/java/jenkins/bugs/Jenkins64991Test.java
Labels: skip-changelog

#7989 Minor footer appearance tweaks
  core/src/main/resources/lib/layout/layout.jelly
  core/src/main/resources/lib/layout/overflowButton.jelly
  war/src/main/js/components/dropdowns/index.js
  war/src/main/js/components/dropdowns/overflow-button.js
  war/src/main/js/components/tooltips/index.js
  war/src/main/resources/images/symbols/external.svg
  war/src/main/scss/modules/buttons.scss
  war/src/main/scss/modules/dropdowns.scss
  war/src/main/scss/modules/page-footer.scss
Labels: ready-for-merge, web-ui, rfe

#8012 Run ESLint on internal scripts
  war/.eslintignore
  war/.eslintrc.js
  war/src/main/webapp/scripts/behavior.js
  war/src/main/webapp/scripts/hudson-behavior.js
  war/src/main/webapp/scripts/sortable.js
Labels: ready-for-merge, skip-changelog

#8045 [JENKINS-71153] Remove top level error icons
  core/src/main/resources/hudson/model/AbstractItem/noWorkspace.jelly
  core/src/main/resources/hudson/model/AbstractProject/wipeOutWorkspaceBlocked.jelly
  core/src/main/resources/hudson/util/AWTProblem/index.jelly
  core/src/main/resources/hudson/util/HudsonFailedToLoad/index.jelly
  core/src/main/resources/hudson/util/IncompatibleAntVersionDetected/index.jelly
  core/src/main/resources/hudson/util/IncompatibleServletVersionDetected/index.jelly
  core/src/main/resources/hudson/util/IncompatibleVMDetected/index.jelly
  core/src/main/resources/hudson/util/InsufficientPermissionDetected/index.jelly
  core/src/main/resources/hudson/util/NoHomeDir/index.jelly
  core/src/main/resources/hudson/util/NoTempDir/index.jelly
  core/src/main/resources/jenkins/model/Jenkins/configureExecutors.jelly
Labels: ready-for-merge, web-ui, skip-changelog

#7913 Warn when operating system end of life is approaching
  core/src/main/java/jenkins/monitor/OperatingSystemEndOfLifeAdminMonitor.java
  core/src/main/resources/jenkins/monitor/OperatingSystemEndOfLifeAdminMonitor/description.jelly
  core/src/main/resources/jenkins/monitor/OperatingSystemEndOfLifeAdminMonitor/description.properties
  core/src/main/resources/jenkins/monitor/OperatingSystemEndOfLifeAdminMonitor/end-of-life-data.json
  core/src/main/resources/jenkins/monitor/OperatingSystemEndOfLifeAdminMonitor/message.jelly
  core/src/main/resources/jenkins/monitor/OperatingSystemEndOfLifeAdminMonitor/message.properties
  core/src/test/java/jenkins/monitor/OperatingSystemEndOfLifeAdminMonitorTest.java
  core/src/test/resources/jenkins/monitor/os-release-alma-8
  core/src/test/resources/jenkins/monitor/os-release-alpine-3.14
  core/src/test/resources/jenkins/monitor/os-release-alpine-3.15
  core/src/test/resources/jenkins/monitor/os-release-alpine-3.16
  core/src/test/resources/jenkins/monitor/os-release-alpine-3.17
  core/src/test/resources/jenkins/monitor/os-release-alpine-3.18
  core/src/test/resources/jenkins/monitor/os-release-centos-7
  core/src/test/resources/jenkins/monitor/os-release-debian-10
  core/src/test/resources/jenkins/monitor/os-release-fedora-36
  core/src/test/resources/jenkins/monitor/os-release-fedora-37
  core/src/test/resources/jenkins/monitor/os-release-oracle-7
  core/src/test/resources/jenkins/monitor/os-release-oracle-8
  core/src/test/resources/jenkins/monitor/os-release-redhat-7
  core/src/test/resources/jenkins/monitor/os-release-redhat-8
  core/src/test/resources/jenkins/monitor/os-release-rocky-8
  core/src/test/resources/jenkins/monitor/os-release-scientific-7
  core/src/test/resources/jenkins/monitor/os-release-ubuntu-18.04
Labels: rfe, squash-merge-me

#7921 Guidance for new contributors
  .github/config.yml
  .github/images/jenkins-welcome.svg
Labels: skip-changelog

#8034 Add a test case for SystemPropertiesTest.java
  test/src/test/java/jenkins/util/SystemPropertiesTest.java
Labels: ready-for-merge, skip-changelog, squash-merge-me, tests

#8035 Add a test case for I18nTest.java
  test/src/test/java/jenkins/I18nTest.java
Labels: ready-for-merge, skip-changelog, squash-merge-me, tests

#8036 new test case in SCMCheckoutStrategyTest.java
  test/src/test/java/jenkins/scm/SCMCheckoutStrategyTest.java
Labels: ready-for-merge, skip-changelog, squash-merge-me, tests

#8052 [JENKINS-71345] Remove 'undefined' from system dropdown menu
  core/src/main/java/hudson/model/ManageJenkinsAction.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/jenkins/management/Badge.java
  core/src/main/java/jenkins/management/PluginsLink.java
  core/src/main/java/jenkins/model/ModelObjectWithContextMenu.java
  core/src/main/resources/hudson/PluginManager/sidepanel.jelly
  core/src/main/resources/hudson/model/ManageJenkinsAction/index.jelly
  core/src/main/resources/lib/layout/breadcrumbs.js
  core/src/main/resources/lib/layout/task.jelly
  war/src/main/less/base/yui-compatibility.less
  war/src/main/less/modules/side-panel-tasks.less
Labels: bug, into-lts

#8053 Make Cloud#reconfigure public as it is necessary for downstream implementations
  core/src/main/java/hudson/slaves/Cloud.java
Labels: ready-for-merge, developer

#7998 Lazy-load-friendly `Job.getEstimatedDurationCandidates`
  core/src/main/java/hudson/model/AbstractProject.java
  core/src/main/java/hudson/model/Job.java
  core/src/main/java/jenkins/model/lazy/LazyBuildMixIn.java
  test/src/test/java/hudson/model/JobTest.java
  test/src/test/java/hudson/model/RunMapTest.java
  test/src/test/java/jenkins/model/lazy/LazyBuildMixInTest.java
Labels: ready-for-merge, bug

#7717 Use jenkins-button for Repeatable buttons
  core/src/main/resources/lib/form/repeatable.jelly
  core/src/main/resources/lib/form/repeatable/repeatable.js
Labels: ready-for-merge, web-ui, rfe, security-approved

#7992 [JENKINS-71244] Avoid relative link in update center
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/resources/hudson/model/Messages.properties
  core/src/main/resources/hudson/model/Messages_bg.properties
  core/src/main/resources/hudson/model/Messages_de.properties
  core/src/main/resources/hudson/model/Messages_es.properties
  core/src/main/resources/hudson/model/Messages_fr.properties
  core/src/main/resources/hudson/model/Messages_it.properties
  core/src/main/resources/hudson/model/Messages_ja.properties
  core/src/main/resources/hudson/model/Messages_lt.properties
  core/src/main/resources/hudson/model/Messages_pt_BR.properties
  core/src/main/resources/hudson/model/Messages_sr.properties
  core/src/main/resources/hudson/model/Messages_zh_TW.properties
Labels: ready-for-merge, bug

#8058 Remove Bootstrap usages from the New Item page
  core/src/main/resources/hudson/model/View/newJob.jelly
  war/src/main/js/widgets/add/addform.scss
Labels: ready-for-merge, skip-changelog

#8074 Update URL to LTS backporting toolkit
  docs/MAINTAINERS.adoc
Labels: skip-changelog

#8073 Upgrade parent POM from 1.97 to 1.98
  core/pom.xml
  pom.xml
  test/pom.xml
Labels: skip-changelog, into-lts
