Repository jenkinsci/jenkins, pull requests merged in 2023-12, with the labels that each got.

#8724 Upgrade bundled plugins
  war/pom.xml
Labels: ready-for-merge, skip-changelog, dependencies, java

#8740 make displayname of HistoryWidget configurable for alternate text
  core/src/main/java/hudson/widgets/HistoryWidget.java
  core/src/main/resources/hudson/widgets/HistoryWidget/index.properties
Labels: ready-for-merge, rfe

#8689 do not specify anti-aliasing
  war/src/main/scss/base/_core.scss
Labels: ready-for-merge, web-ui, rfe

#8735 Add `ExtensionList.lookupFirst` convenience method.
  core/src/main/java/hudson/ExtensionList.java
  test/src/test/java/lib/form/OptionTest.java
Labels: ready-for-merge, developer

#8700 [JENKINS-72343] Accept all 2xx and 3xx status codes to validate proxy in HTTP Proxy Configuration
  core/src/main/java/hudson/ProxyConfiguration.java
  core/src/main/resources/hudson/Messages.properties
  core/src/main/resources/hudson/Messages_bg.properties
  core/src/main/resources/hudson/Messages_de.properties
  core/src/main/resources/hudson/Messages_es.properties
  core/src/main/resources/hudson/Messages_fr.properties
  core/src/main/resources/hudson/Messages_it.properties
  core/src/main/resources/hudson/Messages_ja.properties
  core/src/main/resources/hudson/Messages_pt_BR.properties
  core/src/main/resources/hudson/Messages_ru.properties
  core/src/main/resources/hudson/Messages_sr.properties
  core/src/main/resources/hudson/Messages_zh_TW.properties
Labels: ready-for-merge, rfe

#8756 Ssh Command modified in PrivateKeyProvider.java File in cil module
  cli/src/test/java/hudson/cli/PrivateKeyProviderTest.java
Labels: skip-changelog

#8754 Avoid `CLICommandInvoker.authorizedTo` in `QuietDownCommandTest`
  test/src/test/java/hudson/cli/QuietDownCommandTest.java
Labels: ready-for-merge, skip-changelog

#8736 Class loading deadlock between `PermalinkProjectAction.Permalink` & `PeepholePermalink`
  core/src/main/java/hudson/model/Job.java
  core/src/main/java/hudson/model/PermalinkProjectAction.java
  core/src/main/java/jenkins/model/PeepholePermalink.java
  core/src/test/java/jenkins/model/PeepholePermalinkTest.java
Labels: ready-for-merge, bug

#8773 Print deprecation warning when using `-jnlpUrl`
  core/src/main/java/hudson/slaves/SlaveComputer.java
  pom.xml
Labels: ready-for-merge, rfe, upgrade-guide-needed

#8762 Simplifying `JNLPLauncher`
  core/src/main/java/hudson/model/Slave.java
  core/src/main/java/hudson/slaves/JNLPLauncher.java
  core/src/main/java/jenkins/slaves/RemotingWorkDirSettings.java
  core/src/main/resources/hudson/slaves/JNLPLauncher/config.jelly
  core/src/main/resources/hudson/slaves/JNLPLauncher/config.properties
  core/src/main/resources/hudson/slaves/JNLPLauncher/main.jelly
  core/src/main/resources/hudson/slaves/JNLPLauncher/main.properties
  core/src/main/resources/hudson/slaves/JNLPLauncher/main_bg.properties
  core/src/main/resources/hudson/slaves/JNLPLauncher/main_de.properties
  core/src/main/resources/hudson/slaves/JNLPLauncher/main_es.properties
  core/src/main/resources/hudson/slaves/JNLPLauncher/main_it.properties
  core/src/main/resources/hudson/slaves/JNLPLauncher/main_pt_BR.properties
  core/src/main/resources/hudson/slaves/JNLPLauncher/main_sr.properties
  core/src/main/resources/hudson/slaves/Messages.properties
  core/src/main/resources/hudson/slaves/Messages_pt_BR.properties
  core/src/main/resources/hudson/slaves/Messages_ru.properties
  test/src/test/java/hudson/slaves/JNLPLauncherRealTest.java
  test/src/test/java/hudson/slaves/JNLPLauncherTest.java
  test/src/test/java/hudson/tools/InstallerTranslatorTest.java
Labels: ready-for-merge, rfe, developer

#7635 [JENKINS-60866][JENKINS-71051][JENKINS-71048] Un-inline 'Build Now' JS
  core/src/main/resources/lib/hudson/project/configurable.jelly
  core/src/main/resources/lib/hudson/project/configurable/configurable.js
  core/src/main/resources/lib/layout/task.jelly
  core/src/main/resources/lib/layout/task/task.js
Labels: ready-for-merge, developer

#8725 show node monitors on agent page
  core/src/main/java/hudson/model/Computer.java
  core/src/main/resources/hudson/model/Computer/index.jelly
  war/src/main/scss/components/_table.scss
Labels: ready-for-merge, rfe, security-approved, needs-ath-build

#8745 Avoid file locks in `LauncherTest.remotable`
  test/src/test/java/hudson/LauncherTest.java
Labels: ready-for-merge, skip-changelog

#8763 [JENKINS-72443] Do not show copy option without visible items
  core/src/main/resources/hudson/model/View/newJob.jelly
  test/src/test/java/jenkins/model/NewJobCopyFromTest.java
Labels: ready-for-merge, web-ui, bug

#8765 [JENKINS-72288] fix nested job link in mobile view
  core/src/main/resources/lib/hudson/projectView.jelly
Labels: ready-for-merge, web-ui, bug, security-approved

#8771 [JENKINS-72157] ensure uptime is independent of system clock
  core/src/main/java/jenkins/model/Uptime.java
Labels: ready-for-merge, rfe

#8777 Logging improvements to `Run` related classes
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/model/RunMap.java
  core/src/main/java/jenkins/model/lazy/AbstractLazyLoadRunMap.java
Labels: ready-for-merge, skip-changelog, developer

#8776 [JENKINS-72449] Specify that no fallback to the default locale should be used when looking up a resource bundle via `I18n` action.
  core/src/main/java/jenkins/util/ResourceBundleUtil.java
  test/src/test/java/jenkins/util/ResourceBundleUtilTest.java
Labels: bug

#8785 EOL `Global-Mask-Classes`
  core/src/main/java/hudson/ClassicPluginStrategy.java
  core/src/main/java/hudson/util/MaskingClassLoader.java
Labels: ready-for-merge, removed

#8719 [JENKINS-72371] rework node monitor configuration
  core/src/main/java/hudson/model/ComputerSet.java
  core/src/main/java/hudson/node_monitors/AbstractNodeMonitorDescriptor.java
  core/src/main/java/hudson/node_monitors/ArchitectureMonitor.java
  core/src/main/java/hudson/node_monitors/ClockMonitor.java
  core/src/main/java/hudson/node_monitors/NodeMonitor.java
  core/src/main/java/hudson/node_monitors/ResponseTimeMonitor.java
  core/src/main/java/hudson/node_monitors/SwapSpaceMonitor.java
  core/src/main/resources/hudson/model/ComputerSet/configure.jelly
  core/src/main/resources/hudson/model/ComputerSet/configure.properties
  core/src/main/resources/hudson/node_monitors/ArchitectureMonitor/help.html
  core/src/main/resources/hudson/node_monitors/ClockMonitor/help.html
  core/src/main/resources/hudson/node_monitors/NodeMonitor/configure.jelly
  core/src/main/resources/hudson/node_monitors/NodeMonitor/help-ignored.html
  core/src/main/resources/hudson/node_monitors/ResponseTimeMonitor/help.html
  core/src/main/resources/hudson/node_monitors/SwapSpaceMonitor/help.html
Labels: ready-for-merge, rfe, security-approved, ath-successful

#8761 Restyle widget panes
  war/src/main/scss/abstracts/_theme.scss
  war/src/main/scss/base/_style.scss
  war/src/main/scss/components/_panes-and-bigtable.scss
  war/src/main/scss/components/_side-panel-widgets.scss
Labels: ready-for-merge, web-ui, rfe, security-approved

#8787 Add telemetry for basic Java system properties
  core/src/main/java/jenkins/telemetry/impl/JavaSystemProperties.java
  core/src/main/resources/hudson/model/UsageStatistics/help-usageStatisticsCollected.jelly
  core/src/main/resources/jenkins/telemetry/impl/JavaSystemProperties/description.jelly
  core/src/main/resources/jenkins/telemetry/impl/JavaSystemProperties/description.properties
Labels: ready-for-merge, rfe, squash-merge-me

#8269 [JENKINS-71578] allow making sidepanel sticky
  core/src/main/resources/hudson/PluginManager/sidepanel.jelly
  core/src/main/resources/hudson/model/Job/configure.jelly
  core/src/main/resources/lib/layout/layout.jelly
  core/src/main/resources/lib/layout/side-panel.jelly
  war/src/main/js/section-to-sidebar-items.js
Labels: ready-for-merge, web-ui, developer

#8394 Use Jenkins modal for 'Apply' button failures
  core/src/main/resources/jenkins/model/Jenkins/oops.properties
  core/src/main/resources/lib/form/apply/apply.js
  test/src/test/java/hudson/model/ViewTest.java
  test/src/test/java/jenkins/security/StackTraceSuppressionTest.java
Labels: ready-for-merge, web-ui, rfe, security-approved, ath-successful

#8780 Update the appearance of the stop button
  core/src/main/resources/hudson/widgets/HistoryWidget/entry.jelly
  core/src/main/resources/lib/hudson/buildCaption.jelly
  core/src/main/resources/lib/hudson/buildCaption.properties
  core/src/main/resources/lib/hudson/executors.properties
  core/src/main/resources/lib/layout/stopButton.jelly
  test/src/test/java/jenkins/security/Security2278Test.java
  war/src/main/scss/components/_buttons.scss
Labels: ready-for-merge, web-ui, rfe, security-approved, ath-successful

#8790 Fix import used for Javadoc
  core/src/main/java/hudson/cli/declarative/CLIMethod.java
Labels: ready-for-merge, skip-changelog

#8795 Update Freestyle project description
  core/src/main/resources/hudson/model/Messages.properties
  core/src/main/resources/hudson/model/Messages_bg.properties
  core/src/main/resources/hudson/model/Messages_ca.properties
  core/src/main/resources/hudson/model/Messages_cs.properties
  core/src/main/resources/hudson/model/Messages_da.properties
  core/src/main/resources/hudson/model/Messages_de.properties
  core/src/main/resources/hudson/model/Messages_es.properties
  core/src/main/resources/hudson/model/Messages_et.properties
  core/src/main/resources/hudson/model/Messages_fi.properties
  core/src/main/resources/hudson/model/Messages_fr.properties
  core/src/main/resources/hudson/model/Messages_it.properties
  core/src/main/resources/hudson/model/Messages_ja.properties
  core/src/main/resources/hudson/model/Messages_ko.properties
  core/src/main/resources/hudson/model/Messages_lt.properties
  core/src/main/resources/hudson/model/Messages_nb_NO.properties
  core/src/main/resources/hudson/model/Messages_nl.properties
  core/src/main/resources/hudson/model/Messages_pl.properties
  core/src/main/resources/hudson/model/Messages_pt_BR.properties
  core/src/main/resources/hudson/model/Messages_pt_PT.properties
  core/src/main/resources/hudson/model/Messages_ro.properties
  core/src/main/resources/hudson/model/Messages_ru.properties
  core/src/main/resources/hudson/model/Messages_sv_SE.properties
  core/src/main/resources/hudson/model/Messages_tr.properties
  core/src/main/resources/hudson/model/Messages_uk.properties
  core/src/main/resources/hudson/model/Messages_zh_TW.properties
Labels: ready-for-merge, skip-changelog, squash-merge-me

#8758 [JENKINS-64356] Add test for missing `legacyIds` when creating jobs via REST API or CLI
  test/src/test/java/jenkins/model/RunIdMigratorTest.java
Labels: ready-for-merge, tests

#8797 Remove last usages of .bigtable
  core/src/main/resources/hudson/triggers/SCMTrigger/DescriptorImpl/index.jelly
  core/src/main/resources/jenkins/diagnosis/HsErrPidList/index.jelly
Labels: ready-for-merge, web-ui, skip-changelog

#8793 Restore JCasC compatibility for `JNLPLauncher.tunnel`
  core/src/main/java/hudson/slaves/JNLPLauncher.java
Labels: ready-for-merge, bug

#8800 [JENKINS-71965] fix timezone in build history
  core/src/main/java/hudson/Functions.java
  core/src/main/resources/hudson/widgets/HistoryWidget/entry.jelly
Labels: ready-for-merge, bug

#8717 [JENKINS-72370][JENKINS-11889] fix SimpleScheduledRetentionStrategy with inbound agents
  core/src/main/java/hudson/slaves/SimpleScheduledRetentionStrategy.java
Labels: ready-for-merge, bug
