Repository jenkinsci/jenkins, pull requests merged in 2023-07, with the labels that each got.

#8221 [JENKINS-71553] Add history widget factory for job not implementing `Queue.Task`
  core/src/main/java/hudson/widgets/HistoryWidget.java
Labels: regression-fix, ready-for-merge

#8218 Revert inlining 'since' tags in stapler documentation
  core/src/main/resources/lib/form/submit.jelly
  core/src/main/resources/lib/hudson/propertyTable.jelly
  core/src/main/resources/lib/layout/breadcrumb.jelly
  core/src/main/resources/lib/layout/icon.jelly
  core/src/main/resources/lib/layout/layout.jelly
  core/src/main/resources/lib/layout/svgIcon.jelly
  core/src/main/resources/lib/layout/task.jelly
Labels: documentation

#8158 Ensure that consumers of `Executors#startBlockingBuild` stop the blocking build
  test/src/test/java/hudson/model/ComputerSetTest.java
  test/src/test/java/hudson/model/ComputerTest.java
  test/src/test/java/hudson/model/ExecutorTest.java
Labels: ready-for-merge, skip-changelog

#8223 Update textarea.js
  core/src/main/resources/lib/form/textarea/textarea.js
Labels: skip-changelog

#8210 Update legacyapitoken revoke button style matching 'jenkins-button's
  core/src/main/resources/jenkins/security/apitoken/LegacyApiTokenAdministrativeMonitor/manage.jelly
  test/src/test/java/jenkins/security/apitoken/LegacyApiTokenAdministrativeMonitorTest.java
Labels: ready-for-merge, web-ui, rfe, security-approved

#8153 Replace similar OS EoL tests with `@ParameterizedTests`
  core/src/test/java/jenkins/monitor/OperatingSystemEndOfLifeAdminMonitorTest.java
Labels: ready-for-merge, tests

#8231 Adapt maven-license-plugin changes
  pom.xml
  war/pom.xml
Labels: skip-changelog, dependencies, java

#8220 Read end of life data file less often
  core/src/main/java/jenkins/monitor/OperatingSystemEndOfLifeAdminMonitor.java
Labels: ready-for-merge, skip-changelog

#7355 [JENKINS-70059] Improve Safe Restart interface and user information
  core/src/main/java/hudson/util/HudsonIsRestarting.java
  core/src/main/java/jenkins/cli/SafeRestartCommand.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/resources/hudson/cli/Messages.properties
  core/src/main/resources/hudson/cli/Messages_de.properties
  core/src/main/resources/hudson/util/HudsonIsRestarting/index.jelly
  core/src/main/resources/hudson/util/HudsonIsRestarting/index_de.properties
  core/src/main/resources/jenkins/model/Jenkins/_safeRestart.jelly
  core/src/main/resources/jenkins/model/Jenkins/_safeRestart.properties
  core/src/main/resources/jenkins/model/Jenkins/_safeRestart_bg.properties
  core/src/main/resources/jenkins/model/Jenkins/_safeRestart_da.properties
  core/src/main/resources/jenkins/model/Jenkins/_safeRestart_de.properties
  core/src/main/resources/jenkins/model/Jenkins/_safeRestart_es.properties
  core/src/main/resources/jenkins/model/Jenkins/_safeRestart_fr.properties
  core/src/main/resources/jenkins/model/Jenkins/_safeRestart_it.properties
  core/src/main/resources/jenkins/model/Jenkins/_safeRestart_ja.properties
  core/src/main/resources/jenkins/model/Jenkins/_safeRestart_lt.properties
  core/src/main/resources/jenkins/model/Jenkins/_safeRestart_lv.properties
  core/src/main/resources/jenkins/model/Jenkins/_safeRestart_pt_BR.properties
  core/src/main/resources/jenkins/model/Jenkins/_safeRestart_ru.properties
  core/src/main/resources/jenkins/model/Jenkins/_safeRestart_sr.properties
  core/src/main/resources/jenkins/model/Jenkins/_safeRestart_zh_TW.properties
  core/src/main/resources/lib/layout/main-panel.jelly
  core/src/main/resources/lib/layout/main-panel.properties
  core/src/main/resources/lib/layout/main-panel_de.properties
  war/src/main/scss/base/style.scss
  war/src/main/scss/simple-page.scss
Labels: ready-for-merge, web-ui, major-rfe, security-approved

#7893 [JENKINS-71034] [JENKINS-71035] [JENKINS-71036] [JENKINS-71037] Improve CSP compatibility
  core/src/main/resources/hudson/model/Run/_delete-retry.js
  core/src/main/resources/hudson/model/Run/delete-retry.jelly
  core/src/main/resources/hudson/model/UpdateCenter/CompleteBatchJob/Failure/status.jelly
  core/src/main/resources/hudson/model/UpdateCenter/DownloadJob/Failure/status.jelly
  core/src/main/resources/hudson/model/UpdateCenter/_download-failure.js
  core/src/main/resources/hudson/model/UpdateCenter/index.jelly
  core/src/main/resources/hudson/model/UpdateCenter/update-center.js
  core/src/main/resources/hudson/tasks/BuildTrigger/config.jelly
Labels: ready-for-merge, web-ui, security-approved

#8025 Move the 'Update' and 'Install' buttons to the app bar
  core/src/main/resources/hudson/PluginManager/_table.js
  core/src/main/resources/hudson/PluginManager/available.jelly
  core/src/main/resources/hudson/PluginManager/updates.jelly
  core/src/main/resources/lib/layout/overflowButton.jelly
  war/src/main/js/plugin-manager-ui.js
  war/src/main/scss/abstracts/mixins.scss
  war/src/main/scss/modules/buttons.scss
Labels: ready-for-merge, web-ui, rfe, security-approved, ath-successful

#8248 Adapt stapler-maven-plugin changes
  core/pom.xml
  pom.xml
Labels: dependencies, java

#8233 `LazyBuildMixIn.getEstimatedDurationCandidates` duplication
  core/src/main/java/jenkins/model/lazy/LazyBuildMixIn.java
  test/src/test/java/hudson/model/SimpleJobTest.java
Labels: ready-for-merge, bug

#8247 Backporting for LTS 2.401.3
  core/src/main/resources/jenkins/model/Jenkins/threadDump.jelly
  war/src/main/webapp/help/system-config/homeDirectory.html
Labels: into-lts

#8226 Inline taglib documentation site
  .github/renovate.json
  core/src/site/markdown/index.md
  core/src/site/site.xml
  war/.prettierignore
Labels: skip-changelog

#8257 Link directly to changelog in weekly template
  .github/release-drafter.yml
Labels: skip-changelog

#8235 Noting purpose of the `META-INF/upgrade` pseudo-package
  core/src/main/resources/META-INF/upgrade/README.md
Labels: skip-changelog

#8263 Flake in `QueueTest.pendingsConsistenceAfterErrorDuringMaintain`
  test/src/test/java/hudson/model/QueueTest.java
Labels: skip-changelog

#8258 Remove Rebuilder Plugin from setup wizard options
  core/src/main/resources/jenkins/install/platform-plugins.json
Labels: ready-for-merge, rfe

#8261 Flake in `QuietDownCommandTest.quietDownShouldSuccessWithBlockPlusNonExpiredTimeoutAndRunningExecutor`
  test/src/test/java/hudson/cli/CancelQuietDownCommandTest.java
  test/src/test/java/hudson/cli/OfflineNodeCommandTest.java
  test/src/test/java/hudson/cli/OnlineNodeCommandTest.java
  test/src/test/java/hudson/cli/QuietDownCommandTest.java
Labels: ready-for-merge, skip-changelog

#7641 Remove deprecated `DIR_SEPARATOR` and `LINE_SEPARATOR`
  core/src/main/java/hudson/util/IOUtils.java
  core/src/main/resources/META-INF/upgrade/IOUtils.hint
Labels: ready-for-merge, upgrade-guide-needed, removed

#8270 Remove Rebuilder Plugin from setup wizard options (LTS backport)
  core/src/main/resources/jenkins/install/platform-plugins.json
Labels: into-lts

#8086 Tidy up the Parameters page
  core/src/main/resources/hudson/model/ParametersAction/index.jelly
Labels: ready-for-merge, web-ui, skip-changelog, security-approved

#8219 Small tweaks to theme.scss
  war/src/main/scss/abstracts/theme.scss
  war/src/main/scss/form/reorderable-list.scss
  war/src/main/scss/modules/buttons-deprecated.scss
  war/src/main/scss/modules/buttons.scss
  war/src/main/scss/modules/icons.scss
  war/src/main/scss/pages/plugin-manager.scss
Labels: ready-for-merge, skip-changelog

#8129 Add last build status to job page
  core/src/main/resources/hudson/model/AbstractBuild/index.jelly
  core/src/main/resources/hudson/model/Job/index.jelly
  core/src/main/resources/lib/hudson/build-caption.js
  core/src/main/resources/lib/hudson/buildCaption.jelly
  test/src/test/java/jenkins/bugs/Jenkins64991Test.java
  war/src/main/scss/base/layout-commons.scss
  war/src/main/scss/base/typography.scss
  war/src/main/scss/modules/app-bar.scss
Labels: ready-for-merge, web-ui, rfe, security-approved, ath-successful

#8282 Post LTS pre-releases to discourse and dev mailing list
  .github/workflows/announce-lts-rc.yml
Labels: ready-for-merge, skip-changelog

#8280 `ReverseProxySetupMonitor` changed from POST to GET
  core/src/main/resources/hudson/diagnosis/ReverseProxySetupMonitor/resources.js
Labels: ready-for-merge, skip-changelog

#8278 Add missing `application/x-www-form-urlencoded` header
  core/src/main/resources/jenkins/security/ApiTokenProperty/resources.js
  core/src/main/resources/lib/form/textarea/textarea.js
  core/src/main/resources/lib/hudson/progressive-text.js
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, skip-changelog

#8273 [JENKINS-71366] Set sandbox allow-same-origin in DEFAULT_CSP_VALUE.
  core/src/main/java/hudson/model/DirectoryBrowserSupport.java
Labels: ready-for-merge, rfe, security-approved

#8259 Flake in `ExecutorTest.disconnectCause`
  test/src/test/java/hudson/model/ExecutorTest.java
Labels: ready-for-merge, skip-changelog

#8283 Add logging for agent usage by job
  core/src/main/java/hudson/slaves/SlaveComputer.java
Labels: ready-for-merge, rfe

#8302 Update dependabot branch for LTS 2.414.x
  .github/dependabot.yml
Labels: skip-changelog

#8293 [JENKINS-71698] Only disable plugin manager button if none are selected
  war/src/main/js/plugin-manager-ui.js
Labels: ready-for-merge, bug

#8306 Label LTS PRs automatically
  .github/workflows/label-lts-prs.yaml
Labels: skip-changelog

#8288 [JENKINS-71186] - Improve socket creation on TcpSlaveAgentListener
  core/src/main/java/hudson/TcpSlaveAgentListener.java
Labels: ready-for-merge, bug, security-approved

#8300 Remove invalid Japanese mailing list URL
  core/src/main/resources/jenkins/model/Jenkins/noPrincipal.properties
  core/src/main/resources/jenkins/model/Jenkins/noPrincipal_bg.properties
  core/src/main/resources/jenkins/model/Jenkins/noPrincipal_da.properties
  core/src/main/resources/jenkins/model/Jenkins/noPrincipal_es.properties
  core/src/main/resources/jenkins/model/Jenkins/noPrincipal_it.properties
  core/src/main/resources/jenkins/model/Jenkins/noPrincipal_ja.properties
  core/src/main/resources/jenkins/model/Jenkins/noPrincipal_lt.properties
  core/src/main/resources/jenkins/model/Jenkins/noPrincipal_pt_BR.properties
  core/src/main/resources/jenkins/model/Jenkins/noPrincipal_sr.properties
  core/src/main/resources/jenkins/model/Jenkins/noPrincipal_zh_TW.properties
Labels: ready-for-merge, skip-changelog

#8301 Backport 2.414.1
  .github/workflows/announce-lts-rc.yml
  .github/workflows/label-lts-prs.yaml
  core/src/main/java/hudson/AbstractMarkupText.java
  core/src/main/resources/jenkins/install/platform-plugins.json
  test/src/test/java/jenkins/security/Security3188Test.java
  war/src/main/js/plugin-manager-ui.js
Labels: into-lts

#8307 `replaceDescription` is not robust
  core/src/main/resources/lib/hudson/editable-description.js
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, skip-changelog

#8180 Move 'expandableTextbox' to a jenkins-button
  core/src/main/resources/lib/form/expandableTextbox.jelly
  core/src/main/resources/lib/form/expandableTextbox/expandableTextbox.js
  test/src/test/java/lib/form/ExpandableTextboxTest.java
  war/src/main/scss/base/style.scss
Labels: ready-for-merge, web-ui, rfe, security-approved, ath-successful

#8193 Remove `java.desktop/com.sun.beans.introspect` from `Add-Opens`
  core/pom.xml
  test/pom.xml
  war/pom.xml
Labels: ready-for-merge, rfe

#8211 [JENKINS-71052] CSP compatibility: SetupWizard/wizard-ui.jelly
  core/src/main/resources/jenkins/install/SetupWizard/_wizard-ui.js
  core/src/main/resources/jenkins/install/SetupWizard/wizard-ui.jelly
Labels: ready-for-merge, web-ui, rfe, squash-merge-me, alternative, security-approved

#8265 [JENKINS-71054] Remove the treeview option for artifactList
  core/src/main/java/hudson/model/Run.java
  core/src/main/resources/lib/hudson/artifactList.jelly
Labels: ready-for-merge, upgrade-guide-needed, removed

#8299 Simpler `Jenkins.getComputers`
  core/src/main/java/jenkins/model/Jenkins.java
  test/src/test/java/jenkins/model/JenkinsTest.java
Labels: ready-for-merge, rfe
