Repository jenkinsci/jenkins, pull requests merged in 2023-11, with the labels that each got.

#8674 [JENKINS-70994] Upgrade bundled SnakeYAML plugin from 1.33-95.va_b_a_e3e47b_fa_4 to 2.2-111.vc6598e30cc65
  war/pom.xml
Labels: skip-changelog, dependencies, java

#8672 Finish French translations for Update Center
  core/src/main/resources/hudson/util/HudsonIsRestarting/index_fr.properties
Labels: ready-for-merge, skip-changelog

#8666 [JENKINS-72266] Upgrade Winstone from 6.14 to 6.16 (upgrade Jetty from 10.0.17 to 10.0.18
  pom.xml
  war/pom.xml
Labels: ready-for-merge, rfe, dependencies, java

#8661 [JENKINS-72252] Warn 12 months and 3 months before end of Java support
  core/src/main/java/jenkins/monitor/JavaVersionRecommendationAdminMonitor.java
Labels: rfe

#8677 Complete french translation for Confirm Rename view
  core/src/main/resources/hudson/model/AbstractItem/confirm-rename_fr.properties
Labels: ready-for-merge, skip-changelog

#8675 Log `Error`s from `SlaveComputer._connect`
  core/src/main/java/hudson/slaves/SlaveComputer.java
Labels: ready-for-merge, rfe

#6869 [JENKINS-60866][JENKINS-71797] Remove timeline widget
  bom/pom.xml
  core/pom.xml
  core/src/main/java/hudson/model/BuildTimelineWidget.java
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/model/Job.java
  core/src/main/java/hudson/model/View.java
  core/src/main/resources/hudson/model/BuildTimelineWidget/build-timeline-widget.js
  core/src/main/resources/hudson/model/BuildTimelineWidget/control.jelly
  core/src/main/resources/hudson/model/Computer/builds.jelly
  core/src/main/resources/hudson/model/Job/buildTimeTrend.jelly
  core/src/main/resources/hudson/model/User/builds.jelly
  core/src/main/resources/hudson/model/View/builds.jelly
  test/src/test/java/jenkins/widgets/BuildListTableTest.java
Labels: ready-for-merge, rfe, removed, ath-successful

#8679 Deleted long deprecated and unused `UserProperties`
  core/src/main/java/hudson/model/UserProperties.java
Labels: ready-for-merge, removed

#8640 Temporary memory leak in `FutureImpl.executors`
  core/src/main/java/hudson/model/queue/FutureImpl.java
  core/src/main/java/hudson/model/queue/WorkUnitContext.java
  test/src/test/java/hudson/model/ComputerTest.java
Labels: ready-for-merge, bug

#8639 Stop recommending `-jnlpUrl`
  core/src/main/java/hudson/slaves/JNLPLauncher.java
  core/src/main/resources/hudson/slaves/JNLPLauncher/main.jelly
  src/checkstyle/checkstyle-configuration.xml
Labels: ready-for-merge, rfe, security-approved

#8686 Backporting for 2.426.1 - part 2
  war/pom.xml
Labels: into-lts

#8684 Update French translation for Save button and add one for Apply
  core/src/main/resources/hudson/model/Job/configure_fr.properties
Labels: ready-for-merge, skip-changelog

#8685 French translations for plugin manager
  core/src/main/resources/hudson/PluginManager/installed_fr.properties
  core/src/main/resources/hudson/PluginManager/updates_fr.properties
  core/src/main/resources/hudson/util/HudsonIsRestarting/index_fr.properties
Labels: ready-for-merge, skip-changelog

#8645 Pull up `AbstractFolder.delete` logic into `AbstractItem`
  core/src/main/java/hudson/model/AbstractItem.java
Labels: ready-for-merge, skip-changelog

#8629 [JENKINS-64816] prepare for support of node monitors by JCasC
  core/src/main/java/hudson/node_monitors/ArchitectureMonitor.java
  core/src/main/java/hudson/node_monitors/ClockMonitor.java
  core/src/main/java/hudson/node_monitors/DiskSpaceMonitor.java
  core/src/main/java/hudson/node_monitors/NodeMonitor.java
  core/src/main/java/hudson/node_monitors/ResponseTimeMonitor.java
  core/src/main/java/hudson/node_monitors/SwapSpaceMonitor.java
  core/src/main/java/hudson/node_monitors/TemporarySpaceMonitor.java
Labels: ready-for-merge, rfe

#8618 [JENKINS-72159] deactivate MarkedOffline monitor when agents are online
  core/src/main/java/hudson/node_monitors/NodeMonitorUpdater.java
Labels: ready-for-merge, web-ui, rfe, security-approved

#8321 [JENKINS-71715] Allow plugins with alternate build log visualizations to handle console links from core and other plugins
  core/src/main/java/hudson/Functions.java
  core/src/main/java/jenkins/appearance/AppearanceGlobalConfiguration.java
  core/src/main/java/jenkins/console/ConsoleUrlProvider.java
  core/src/main/java/jenkins/console/ConsoleUrlProviderGlobalConfiguration.java
  core/src/main/java/jenkins/console/ConsoleUrlProviderUserProperty.java
  core/src/main/java/jenkins/console/DefaultConsoleUrlProvider.java
  core/src/main/java/jenkins/widgets/BuildListTable.java
  core/src/main/java/jenkins/widgets/BuildTimeTrend.java
  core/src/main/resources/hudson/model/AbstractBuild/changes.jelly
  core/src/main/resources/hudson/model/AbstractBuild/index.jelly
  core/src/main/resources/hudson/model/Job/buildTimeTrend_resources.js
  core/src/main/resources/hudson/widgets/HistoryWidget/entry.jelly
  core/src/main/resources/jenkins/console/ConsoleUrlProviderGlobalConfiguration/config.jelly
  core/src/main/resources/jenkins/console/ConsoleUrlProviderGlobalConfiguration/config.properties
  core/src/main/resources/jenkins/console/ConsoleUrlProviderUserProperty/config.jelly
  core/src/main/resources/jenkins/console/ConsoleUrlProviderUserProperty/config.properties
  core/src/main/resources/jenkins/console/Messages.properties
  core/src/main/resources/lib/hudson/buildProgressBar.jelly
  core/src/main/resources/lib/hudson/project/console-link.jelly
  test/src/test/java/jenkins/console/ConsoleUrlProviderTest.java
Labels: ready-for-merge, web-ui, developer

#8313 [JENKINS-71726] [JENKINS-71727] remove inline javascript
  core/src/main/java/hudson/Util.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/security/HudsonAuthenticationEntryPoint.java
  war/src/main/webapp/scripts/redirect.js
Labels: ready-for-merge, skip-changelog, security-approved

#8707 Use secondary text color for build history descriptions rather than lowering opacity
  war/src/main/scss/base/_style.scss
Labels: ready-for-merge, skip-changelog

#8714 Refuse to load the Jenkins test harness in production
  core/src/main/java/hudson/ClassicPluginStrategy.java
Labels: ready-for-merge, rfe

#8701 improve dialog form handling
  war/src/main/js/components/dialogs/index.js
Labels: ready-for-merge, skip-changelog, security-approved, ath-successful

#8593 [JENKINS-72009, JENKINS-72200, JENKINS-24947] various fixes and improvements around disk space monitoring
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/node_monitors/AbstractAsyncNodeMonitorDescriptor.java
  core/src/main/java/hudson/node_monitors/AbstractDiskSpaceMonitor.java
  core/src/main/java/hudson/node_monitors/DiskSpaceMonitor.java
  core/src/main/java/hudson/node_monitors/DiskSpaceMonitorDescriptor.java
  core/src/main/java/hudson/node_monitors/DiskSpaceMonitorNodeProperty.java
  core/src/main/java/hudson/node_monitors/TemporarySpaceMonitor.java
  core/src/main/resources/hudson/model/ComputerSet/configure.jelly
  core/src/main/resources/hudson/model/ComputerSet/index.jelly
  core/src/main/resources/hudson/node_monitors/AbstractDiskSpaceMonitor/config.jelly
  core/src/main/resources/hudson/node_monitors/AbstractDiskSpaceMonitor/help-freeSpaceThreshold.html
  core/src/main/resources/hudson/node_monitors/AbstractDiskSpaceMonitor/help-freeSpaceWarningThreshold.html
  core/src/main/resources/hudson/node_monitors/DiskSpaceMonitor/column.jelly
  core/src/main/resources/hudson/node_monitors/DiskSpaceMonitor/help.html
  core/src/main/resources/hudson/node_monitors/DiskSpaceMonitorNodeProperty/config.jelly
  core/src/main/resources/hudson/node_monitors/DiskSpaceMonitorNodeProperty/config_de.properties
  core/src/main/resources/hudson/node_monitors/DiskSpaceMonitorNodeProperty/help-freeDiskSpaceThreshold.html
  core/src/main/resources/hudson/node_monitors/DiskSpaceMonitorNodeProperty/help-freeDiskSpaceWarningThreshold.html
  core/src/main/resources/hudson/node_monitors/DiskSpaceMonitorNodeProperty/help-freeTempSpaceThreshold.html
  core/src/main/resources/hudson/node_monitors/DiskSpaceMonitorNodeProperty/help-freeTempSpaceWarningThreshold.html
  core/src/main/resources/hudson/node_monitors/Messages.properties
  core/src/main/resources/hudson/node_monitors/Messages_bg.properties
  core/src/main/resources/hudson/node_monitors/Messages_cs.properties
  core/src/main/resources/hudson/node_monitors/Messages_da.properties
  core/src/main/resources/hudson/node_monitors/Messages_de.properties
  core/src/main/resources/hudson/node_monitors/Messages_es.properties
  core/src/main/resources/hudson/node_monitors/Messages_fr.properties
  core/src/main/resources/hudson/node_monitors/Messages_it.properties
  core/src/main/resources/hudson/node_monitors/Messages_ja.properties
  core/src/main/resources/hudson/node_monitors/Messages_nl.properties
  core/src/main/resources/hudson/node_monitors/Messages_pt_BR.properties
  core/src/main/resources/hudson/node_monitors/Messages_ru.properties
  core/src/main/resources/hudson/node_monitors/Messages_sr.properties
  core/src/main/resources/hudson/node_monitors/Messages_sv_SE.properties
  core/src/main/resources/hudson/node_monitors/Messages_zh_TW.properties
  core/src/main/resources/hudson/node_monitors/TemporarySpaceMonitor/column.jelly
  core/src/main/resources/hudson/node_monitors/TemporarySpaceMonitor/help.html
  core/src/test/java/hudson/FunctionsTest.java
  test/src/test/java/hudson/model/ComputerSetTest.java
  test/src/test/java/hudson/node_monitors/DiskSpaceMonitorDescriptorTest.java
Labels: ready-for-merge, web-ui, rfe, security-approved

#8694 Added validation of FIPS password length
  core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java
  core/src/main/resources/hudson/security/Messages.properties
Labels: ready-for-merge, rfe, fips

#8718 Remove reference to timeline widget in build history
  core/src/main/resources/hudson/model/Job/buildTimeTrend_resources.js
  core/src/main/resources/lib/hudson/buildListTable.jelly
Labels: ready-for-merge, skip-changelog, security-approved

#8505 [JENKINS-71737] fix redirect when submitting cloud changes
  core/src/main/java/hudson/slaves/Cloud.java
  core/src/main/java/jenkins/agents/CloudSet.java
  core/src/main/resources/hudson/slaves/Cloud/configure.jelly
Labels: regression-fix, ready-for-merge, alternative
