Repository jenkinsci/jenkins, pull requests merged in 2023-02, with the labels that each got.

#7596 [JENKINS-70531] Apply timeout on WebSocket write operations
  core/src/main/java/jenkins/agents/WebSocketAgents.java
  pom.xml
Labels: ready-for-merge, bug

#7614 `t:progressiveText` should tolerate 5xx HTTP errors
  core/src/main/resources/lib/hudson/progressive-text.js
  war/src/main/webapp/scripts/loading.js
Labels: ready-for-merge, rfe

#7618 [JENKINS-70533] Skip submitting telemetry when exception is thrown
  core/src/main/java/jenkins/telemetry/Telemetry.java
  test/src/test/java/jenkins/telemetry/TelemetryTest.java
Labels: ready-for-merge, bug

#7619 [JENKINS-60866] Un-inline setup wizard root URL js
  core/src/main/resources/jenkins/install/SetupWizard/setInitialRootUrlFieldValue.js
  core/src/main/resources/jenkins/install/SetupWizard/setupWizardConfigureInstance.jelly
Labels: ready-for-merge, skip-changelog, security-approved

#7622 Messaging tweaks for `InstallUncaughtExceptionHandler`
  core/src/main/java/hudson/init/impl/InstallUncaughtExceptionHandler.java
Labels: ready-for-merge, skip-changelog

#7623 Update bundled Apache Mina-sshd plugins
  war/pom.xml
Labels: ready-for-merge, bug

#7634 Use 'one-column' design for fingerprint view
  core/src/main/resources/hudson/model/Fingerprint/index.jelly
Labels: ready-for-merge, web-ui, skip-changelog

#7632 Upgrade Winstone from 6.7 to 6.10
  pom.xml
  war/pom.xml
Labels: ready-for-merge, dependencies, java

#7608 Fix computer links in some cases
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/resources/hudson/model/ComputerSet/index.jelly
  test/src/test/java/hudson/model/RSSTest.java
Labels: ready-for-merge, web-ui, bug

#7606 Updating the descriptions for the escape/encode functions
  core/src/main/java/hudson/Functions.java
Labels: ready-for-merge, skip-changelog

#7639 Fixed minor deprecation from `IOUtils` in Tests
  test/src/test/java/hudson/console/HyperlinkNoteTest.java
  test/src/test/java/hudson/model/ListViewTest.java
Labels: ready-for-merge, skip-changelog

#7642 Fix broken issueManagement URL
  pom.xml
Labels: ready-for-merge, skip-changelog

#7627 [JENKINS-70191] Broken resize behavior on About Jenkins (regression in 2.340)
  war/src/main/less/pages/about.less
Labels: regression-fix, ready-for-merge

#7631 [JENKINS-70139] booleanRadio uses non-unique ID (regression in 2.335)
  core/src/main/resources/lib/form/repeatable/repeatable.js
Labels: ready-for-merge, bug, security-approved

#7589 [JENKINS-70438] Newer build displayed when filtering the builds in Build History Widget even if the build name didn't match
  war/src/main/js/filter-build-history.js
Labels: ready-for-merge, web-ui, bug, security-approved

#7644 Correct tag declaring required arguments in Jelly
  core/src/main/resources/lib/hudson/buildHealth.jelly
  core/src/main/resources/lib/hudson/buildRangeLink.jelly
  core/src/main/resources/lib/hudson/editTypeIcon.jelly
  core/src/main/resources/lib/hudson/progressiveText.jelly
  core/src/main/resources/lib/layout/css.jelly
  core/src/main/resources/lib/layout/js.jelly
  core/src/main/resources/lib/layout/pageHeader.jelly
Labels: ready-for-merge, developer

#7649 Use artifact caching proxy for Jenkins Core builds
  Jenkinsfile
  ath.sh
Labels: ready-for-merge, skip-changelog

#7651 Update plugins after 2023-02-15 security advisory
  war/pom.xml
Labels: ready-for-merge, rfe, developer, dependencies, java

#7663 Fix typo in element-debug.js
  war/src/main/webapp/scripts/yui/element/element-debug.js
Labels: skip-changelog

#7625 Added copy to clipboard button to agent launch snippets
  core/src/main/resources/hudson/slaves/JNLPLauncher/main.jelly
Labels: rfe, squash-merge-me, security-approved

#7662 Turkish localization updates
  core/src/main/resources/hudson/model/AbstractItem/confirm-rename_tr.properties
  core/src/main/resources/hudson/model/AbstractProject/sidepanel_tr.properties
  core/src/main/resources/hudson/model/Messages_tr.properties
  core/src/main/resources/hudson/model/View/AsynchPeople/index_tr.properties
  core/src/main/resources/hudson/model/View/builds_tr.properties
  core/src/main/resources/hudson/scm/Messages_tr.properties
  core/src/main/resources/hudson/widgets/HistoryWidget/index_tr.properties
  core/src/main/resources/jenkins/model/Jenkins/legend_tr.properties
  core/src/main/resources/jenkins/model/RenameAction/action_tr.properties
  core/src/main/resources/lib/hudson/editableDescription_tr.properties
  core/src/main/resources/lib/hudson/project/configurable_tr.properties
  core/src/main/resources/lib/hudson/queue_tr.properties
  core/src/main/resources/lib/hudson/rssBar_tr.properties
  core/src/main/resources/lib/layout/layout_tr.properties
Labels: ready-for-merge, localization

#7653 [JENKINS-70599] restore installNecessaryPlugins redirect destination
  core/src/main/java/hudson/PluginManager.java
  test/src/test/java/hudson/PluginManagerTest.java
Labels: regression-fix, ready-for-merge, squash-merge-me

#7668 [JENKINS-70662] Disable browser form validation from submit button
  core/src/main/resources/lib/form/submit.jelly
Labels: regression-fix, ready-for-merge

#7665 [JENKINS-21052] Warn user that the copy button requires HTTPS
  core/src/main/resources/lib/layout/copyButton/copyButton.js
Labels: ready-for-merge, rfe
