Repository jenkinsci/jenkins, pull requests merged in 2023-06, with the labels that each got.

#8076 Don't show arrow next to restart checkbox if OS doesn't support it
  core/src/main/resources/hudson/model/UpdateCenter/body.jelly
Labels: ready-for-merge, web-ui, bug

#8082 [JENKINS-71394] Fedora 38 should not show EOL warning until 2024
  core/src/main/resources/jenkins/monitor/OperatingSystemEndOfLifeAdminMonitor/end-of-life-data.json
Labels: bug

#8065 Move from `javax.inject` to `jakarta.inject`
  core/src/main/java/hudson/ExtensionFinder.java
  core/src/main/java/hudson/security/FullControlOnceLoggedInAuthorizationStrategy.java
  core/src/main/java/jenkins/install/InstallStateFilter.java
  core/src/main/java/jenkins/install/InstallUtil.java
  core/src/main/java/jenkins/model/GlobalConfiguration.java
  test/src/test/java/hudson/ExtensionFinderTest.java
  test/src/test/java/jenkins/bugs/Jenkins19124Test.java
  test/src/test/java/lib/form/TextAreaTest.java
Labels: ready-for-merge, developer

#8084 Remove font-size from html selector
  war/src/main/scss/styles.scss
Labels: ready-for-merge, skip-changelog

#8068 Trying to deflake `DeleteBuildsCommandTest.deleteBuildsShouldSuccessEvenTheBuildIsRunning`
  test/src/test/java/hudson/cli/DeleteBuildsCommandTest.java
Labels: skip-changelog

#8100 [JENKINS-71383] Confluence Publisher plugin space check not working (regression in 2.406)
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: regression-fix, ready-for-merge

#8098 Remove usages of `IOUtils#toByteArray`
  cli/src/main/java/hudson/cli/PlainCLIProtocol.java
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/model/FileParameterValue.java
  core/src/main/java/hudson/model/Slave.java
  core/src/main/java/hudson/util/ProcessTree.java
  core/src/main/java/jenkins/security/DefaultConfidentialStore.java
  test/src/test/java/hudson/model/DirectoryBrowserSupportTest.java
Labels: ready-for-merge, skip-changelog

#8085 Remove Bootstrap from pane.jelly
  core/src/main/resources/lib/layout/pane.jelly
  war/src/main/scss/base/style.scss
  war/src/main/scss/modules/side-panel-widgets.scss
Labels: ready-for-merge, skip-changelog, security-approved

#8109 Fix 'since' updater path in MAINTAINERS.adoc
  docs/MAINTAINERS.adoc
Labels: skip-changelog

#8114 [JENKINS-71153] Remove top-level fingerprint icon
  core/src/main/resources/hudson/tasks/Fingerprinter/FingerprintAction/index.jelly
Labels: ready-for-merge, web-ui, skip-changelog

#8106 Remove dependency on spotless shared-resources
  pom.xml
Labels: ready-for-merge, skip-changelog

#7995 Improve sign in/register screens appearance on mobile
  war/src/main/scss/base/core.scss
  war/src/main/scss/base/layout-commons.scss
  war/src/main/scss/base/style.scss
  war/src/main/scss/pages/sign-in-register.scss
  war/src/main/scss/simple-page.scss
  war/src/main/scss/styles.scss
Labels: ready-for-merge, web-ui, rfe

#8115 [JENKINS-71406] Flake in `NodeCanTakeTaskTest.becauseNodeIsBusy`
  test/src/test/java/hudson/slaves/NodeCanTakeTaskTest.java
Labels: skip-changelog

#8116 Use GH 'tasklist' syntax for tasklists
  .github/PULL_REQUEST_TEMPLATE.md
Labels: skip-changelog

#8119 Remove nested list from GitHub tasklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: skip-changelog

#8121 Upgrade Guice from 5.1.0 to 6.0.0
  .github/dependabot.yml
  bom/pom.xml
  core/src/main/java/hudson/ExtensionFinder.java
  core/src/main/java/hudson/security/FullControlOnceLoggedInAuthorizationStrategy.java
  core/src/main/java/jenkins/install/InstallStateFilter.java
  core/src/main/java/jenkins/install/InstallUtil.java
  core/src/main/java/jenkins/model/GlobalConfiguration.java
  test/src/test/java/hudson/ExtensionFinderTest.java
  test/src/test/java/jenkins/bugs/Jenkins19124Test.java
  test/src/test/java/lib/form/TextAreaTest.java
Labels: skip-changelog, into-lts

#8118 Backport end of life warning to stable-2.401
  core/src/main/java/jenkins/monitor/OperatingSystemEndOfLifeAdminMonitor.java
  core/src/main/resources/jenkins/monitor/OperatingSystemEndOfLifeAdminMonitor/description.jelly
  core/src/main/resources/jenkins/monitor/OperatingSystemEndOfLifeAdminMonitor/description.properties
  core/src/main/resources/jenkins/monitor/OperatingSystemEndOfLifeAdminMonitor/end-of-life-data.json
  core/src/main/resources/jenkins/monitor/OperatingSystemEndOfLifeAdminMonitor/message.jelly
  core/src/main/resources/jenkins/monitor/OperatingSystemEndOfLifeAdminMonitor/message.properties
  core/src/test/java/jenkins/monitor/OperatingSystemEndOfLifeAdminMonitorTest.java
  core/src/test/resources/jenkins/monitor/os-release-alma-8
  core/src/test/resources/jenkins/monitor/os-release-alpine-3.14
  core/src/test/resources/jenkins/monitor/os-release-alpine-3.15
  core/src/test/resources/jenkins/monitor/os-release-alpine-3.16
  core/src/test/resources/jenkins/monitor/os-release-alpine-3.17
  core/src/test/resources/jenkins/monitor/os-release-alpine-3.18
  core/src/test/resources/jenkins/monitor/os-release-centos-7
  core/src/test/resources/jenkins/monitor/os-release-debian-10
  core/src/test/resources/jenkins/monitor/os-release-fedora-36
  core/src/test/resources/jenkins/monitor/os-release-fedora-37
  core/src/test/resources/jenkins/monitor/os-release-oracle-7
  core/src/test/resources/jenkins/monitor/os-release-oracle-8
  core/src/test/resources/jenkins/monitor/os-release-redhat-7
  core/src/test/resources/jenkins/monitor/os-release-redhat-8
  core/src/test/resources/jenkins/monitor/os-release-rocky-8
  core/src/test/resources/jenkins/monitor/os-release-scientific-7
  core/src/test/resources/jenkins/monitor/os-release-ubuntu-18.04
Labels: rfe, into-lts

#8139 Fix failing builds
  war/yarn.lock
Labels: skip-changelog

#8126 Deprecate `hudson.util.IOUtils#skip`
  core/src/main/java/hudson/console/ConsoleNote.java
  core/src/main/java/hudson/util/IOUtils.java
Labels: ready-for-merge, skip-changelog

#8134 Update bundled plugins
  war/pom.xml
Labels: ready-for-merge, dependencies, java

#8142 Forward compatibility for Commons IO 2.13.0 in `hudson.Util#loadFile`
  core/src/main/java/hudson/Util.java
  core/src/test/java/hudson/UtilTest.java
  core/src/test/resources/hudson/foo-0x81-bar.txt
  core/src/test/resources/hudson/internationalization-iso-8859-1.txt
  core/src/test/resources/hudson/internationalization-utf-8.txt
  core/src/test/resources/hudson/internationalization-windows-1252.txt
Labels: ready-for-merge, skip-changelog

#8146 Remove usages of `org.apache.commons.io.output.ByteArrayOutputStream`
  core/src/main/java/hudson/console/AnnotatedLargeText.java
  core/src/main/java/hudson/console/ConsoleNote.java
  core/src/main/java/hudson/lifecycle/WindowsInstallerLink.java
  core/src/main/java/hudson/lifecycle/WindowsServiceLifecycle.java
  core/src/main/java/hudson/model/UsageStatistics.java
  core/src/main/java/hudson/util/HeadBufferingStream.java
  core/src/spotbugs/excludesFilter.xml
Labels: ready-for-merge, skip-changelog

#8145 Remove usages of `org.apache.commons.io.input.NullInputStream`
  core/src/main/java/hudson/Launcher.java
  core/src/main/java/hudson/Proc.java
  core/src/test/java/jenkins/util/VirtualFileTest.java
Labels: ready-for-merge, skip-changelog

#8144 Remove usages of `org.apache.commons.io.output.NullOutputStream`
  core/src/main/java/hudson/ClassicPluginStrategy.java
  core/src/main/java/hudson/Launcher.java
  core/src/main/java/hudson/TcpSlaveAgentListener.java
  core/src/main/java/hudson/Util.java
  core/src/main/java/jenkins/util/JSONSignatureValidator.java
  core/src/test/java/hudson/slaves/ComputerLauncherTest.java
  test/src/test/java/hudson/cli/CLIActionTest.java
Labels: ready-for-merge, skip-changelog

#8143 Fix link from `/threadDump` to agent
  core/src/main/resources/jenkins/model/Jenkins/threadDump.jelly
Labels: ready-for-merge, skip-changelog

#8155 De-flake `hudson.FilePathTest#archiveBug`
  core/src/test/java/hudson/FilePathTest.java
Labels: skip-changelog

#8161 Remove incorrect text from JENKINS_HOME help page
  war/src/main/webapp/help/system-config/homeDirectory.html
Labels: documentation

#8087 Update the Log Recorders interface
  core/src/main/resources/hudson/logging/LogRecorder/configure.jelly
  core/src/main/resources/hudson/logging/LogRecorder/index.jelly
  core/src/main/resources/hudson/logging/LogRecorder/index.properties
  core/src/main/resources/hudson/logging/LogRecorder/index_bg.properties
  core/src/main/resources/hudson/logging/LogRecorder/index_da.properties
  core/src/main/resources/hudson/logging/LogRecorder/index_de.properties
  core/src/main/resources/hudson/logging/LogRecorder/index_es.properties
  core/src/main/resources/hudson/logging/LogRecorder/index_fr.properties
  core/src/main/resources/hudson/logging/LogRecorder/index_it.properties
  core/src/main/resources/hudson/logging/LogRecorder/index_ja.properties
  core/src/main/resources/hudson/logging/LogRecorder/index_lv.properties
  core/src/main/resources/hudson/logging/LogRecorder/index_nl.properties
  core/src/main/resources/hudson/logging/LogRecorder/index_pl.properties
  core/src/main/resources/hudson/logging/LogRecorder/index_pt_BR.properties
  core/src/main/resources/hudson/logging/LogRecorder/index_ru.properties
  core/src/main/resources/hudson/logging/LogRecorder/index_sr.properties
  core/src/main/resources/hudson/logging/LogRecorder/index_zh_TW.properties
  core/src/main/resources/hudson/logging/LogRecorder/sidepanel.jelly
  core/src/main/resources/hudson/logging/LogRecorder/sidepanel.properties
  core/src/main/resources/hudson/logging/LogRecorder/sidepanel_bg.properties
  core/src/main/resources/hudson/logging/LogRecorder/sidepanel_de.properties
  core/src/main/resources/hudson/logging/LogRecorder/sidepanel_it.properties
  core/src/main/resources/hudson/logging/LogRecorder/sidepanel_ja.properties
  core/src/main/resources/hudson/logging/LogRecorder/sidepanel_pl.properties
  core/src/main/resources/hudson/logging/LogRecorder/sidepanel_pt_BR.properties
  core/src/main/resources/hudson/logging/LogRecorder/sidepanel_sr.properties
  core/src/main/resources/hudson/logging/LogRecorderManager/all.jelly
  core/src/main/resources/hudson/logging/LogRecorderManager/feeds.jelly
  core/src/main/resources/hudson/logging/LogRecorderManager/feeds.properties
  core/src/main/resources/hudson/logging/LogRecorderManager/index.jelly
  core/src/main/resources/hudson/logging/LogRecorderManager/levels.jelly
  core/src/main/resources/hudson/logging/LogRecorderManager/new.jelly
  core/src/main/resources/hudson/logging/LogRecorderManager/sidepanel.jelly
  core/src/main/resources/hudson/logging/LogRecorderManager/sidepanel_da.properties
  core/src/main/resources/hudson/logging/LogRecorderManager/sidepanel_de.properties
  core/src/main/resources/hudson/logging/LogRecorderManager/sidepanel_es.properties
  core/src/main/resources/hudson/logging/LogRecorderManager/sidepanel_fr.properties
  core/src/main/resources/hudson/logging/LogRecorderManager/sidepanel_hu.properties
  core/src/main/resources/hudson/logging/LogRecorderManager/sidepanel_it.properties
  core/src/main/resources/hudson/logging/LogRecorderManager/sidepanel_ja.properties
  core/src/main/resources/hudson/logging/LogRecorderManager/sidepanel_ko.properties
  core/src/main/resources/hudson/logging/LogRecorderManager/sidepanel_lt.properties
  core/src/main/resources/hudson/logging/LogRecorderManager/sidepanel_lv.properties
  core/src/main/resources/hudson/logging/LogRecorderManager/sidepanel_nl.properties
  core/src/main/resources/hudson/logging/LogRecorderManager/sidepanel_pl.properties
  core/src/main/resources/hudson/logging/LogRecorderManager/sidepanel_pt_BR.properties
  core/src/main/resources/hudson/logging/LogRecorderManager/sidepanel_pt_PT.properties
  core/src/main/resources/hudson/logging/LogRecorderManager/sidepanel_ru.properties
  core/src/main/resources/hudson/logging/LogRecorderManager/sidepanel_sr.properties
  core/src/main/resources/hudson/logging/LogRecorderManager/sidepanel_zh_TW.properties
  core/src/main/resources/lib/form/submit.jelly
  war/src/main/js/components/dropdowns/utils.js
  war/src/main/scss/modules/dropdowns.scss
Labels: ready-for-merge, web-ui, rfe

#8147 JENKINS-71246 Remove animations on login page causing high CPU usage in some cases
  war/src/main/scss/pages/sign-in-register.scss
Labels: regression-fix, ready-for-merge, web-ui

#8163 Fix a typo in DomainValidator's docs
  core/src/main/java/jenkins/org/apache/commons/validator/routines/DomainValidator.java
Labels: skip-changelog

#8170 Run ATH tests on Java 17
  Jenkinsfile
  ath.sh
Labels: skip-changelog

#8164 Use CSS variables for logger colours
  war/src/main/scss/base/style.scss
Labels: ready-for-merge, rfe

#8174 Stop shipping `metainf-services` in the WAR
  websocket/jetty10/pom.xml
Labels: ready-for-merge, skip-changelog

#8039 [JENKINS-71040] [JENKINS-71041] Improve CSP compatibility
  core/src/main/resources/jenkins/security/ApiTokenProperty/config.jelly
  core/src/main/resources/jenkins/security/ApiTokenProperty/resources.css
  core/src/main/resources/jenkins/security/ApiTokenProperty/resources.js
  core/src/main/resources/jenkins/security/apitoken/LegacyApiTokenAdministrativeMonitor/manage.jelly
  core/src/main/resources/jenkins/security/apitoken/LegacyApiTokenAdministrativeMonitor/resources.js
Labels: ready-for-merge, web-ui, security-approved

#8173 Upgrade Winstone from 6.11 to 6.12
  pom.xml
Labels: ready-for-merge, rfe

#8149 Reenable media feature range notation Stylelint check
  war/.stylelintrc.js
  war/package.json
  war/postcss.config.js
  war/src/main/scss/base/layout-commons.scss
  war/src/main/scss/base/style.scss
  war/src/main/scss/base/visibility-utils.scss
  war/src/main/scss/modules/section.scss
  war/src/main/scss/modules/side-panel-widgets.scss
  war/src/main/scss/pages/sign-in-register.scss
  war/src/main/scss/pluginSetupWizard.scss
  war/yarn.lock
Labels: ready-for-merge, skip-changelog

#8148 [JENKINS-14749] Errors in `styles.css`
  test/src/test/java/jenkins/bugs/Jenkins14749Test.java
  war/src/main/scss/modules/side-panel-tasks.scss
Labels: ready-for-merge, skip-changelog

#7912 [JENKINS-71038] CSP compatibility: PluginManager/installed.jelly
  core/src/main/resources/hudson/PluginManager/_installed.js
  core/src/main/resources/hudson/PluginManager/installed.jelly
Labels: ready-for-merge, web-ui, security-approved

#8206 Temporarily disable selective ATH tests
  Jenkinsfile
Labels: skip-changelog

#8132 Add Russian localization for CLI
  cli/src/main/resources/hudson/cli/client/Messages_ru.properties
Labels: ready-for-merge, localization

#8186 Display a notice when there are no logs available
  core/src/main/resources/hudson/logging/LogRecorder/index.jelly
  core/src/main/resources/lib/layout/notice.jelly
  war/src/main/scss/modules/notice.scss
  war/src/main/scss/styles.scss
Labels: ready-for-merge, web-ui, rfe, security-approved

#8195 Clean up Stylelint configuration
  war/.stylelintrc.js
Labels: skip-changelog

#8209 Fill in todo annotations
  core/src/main/java/hudson/model/Job.java
  core/src/main/java/jenkins/model/ModelObjectWithContextMenu.java
  core/src/main/java/jenkins/model/lazy/LazyBuildMixIn.java
  core/src/main/java/jenkins/model/queue/QueueItem.java
  core/src/main/java/jenkins/util/HttpServletFilter.java
  core/src/main/java/jenkins/widgets/HasWidgets.java
  core/src/main/java/jenkins/widgets/WidgetFactory.java
Labels: ready-for-merge, skip-changelog

#8199 Select Java 17 in ath.sh
  ath.sh
Labels: skip-changelog

#8212 Revert "Temporarily disable selective ATH tests"
  Jenkinsfile
Labels: skip-changelog

#8205 Non-varargs call of varargs method with inexact argument type for last parameter
  core/src/main/java/hudson/cli/DisablePluginCommand.java
Labels: ready-for-merge, skip-changelog

#8179 update buttons for password and secretTextarea
  core/src/main/resources/lib/form/password.jelly
  core/src/main/resources/lib/form/password/password.css
  core/src/main/resources/lib/form/secretTextarea.jelly
  core/src/main/resources/lib/form/secretTextarea/secret.css
  test/src/test/java/hudson/model/PasswordParameterDefinitionTest.java
  test/src/test/java/lib/form/SecretTextareaTest.java
Labels: ready-for-merge, web-ui, rfe, security-approved
