Repository jenkinsci/jenkins, pull requests merged in 2023-01, with the labels that each got.

#6995 [JENKINS-69339] badge icon for Management links
  core/src/main/java/hudson/diagnosis/OldDataMonitor.java
  core/src/main/java/hudson/model/AdministrativeMonitor.java
  core/src/main/java/hudson/model/ManagementLink.java
  core/src/main/java/jenkins/management/Badge.java
  core/src/main/java/jenkins/management/PluginsLink.java
  core/src/main/resources/hudson/diagnosis/Messages.properties
  core/src/main/resources/hudson/diagnosis/Messages_de.properties
  core/src/main/resources/hudson/model/ManageJenkinsAction/index.jelly
  core/src/main/resources/hudson/model/ManageJenkinsAction/index.properties
  core/src/main/resources/hudson/model/ManageJenkinsAction/index_pt_BR.properties
  core/src/main/resources/hudson/model/ManageJenkinsAction/index_zh_TW.properties
  core/src/main/resources/jenkins/management/Messages.properties
  core/src/main/resources/jenkins/management/Messages_de.properties
  core/src/main/resources/jenkins/management/Messages_pt_BR.properties
  core/src/main/resources/jenkins/management/Messages_zh_TW.properties
  war/src/main/less/modules/section.less
Labels: ready-for-merge, web-ui, rfe, security-approved

#6843 Hide potentially sensitive values (system properties and environment variables) by default
  core/src/main/resources/jenkins/model/Jenkins/systemInfo.jelly
  core/src/main/resources/jenkins/slaves/systemInfo/EnvVarsSlaveInfo/systemInfo.jelly
  core/src/main/resources/jenkins/slaves/systemInfo/SystemPropertySlaveInfo/systemInfo.jelly
  core/src/main/resources/lib/hudson/property-table.css
  core/src/main/resources/lib/hudson/property-table.js
  core/src/main/resources/lib/hudson/propertyTable.jelly
  core/src/main/resources/lib/hudson/propertyTable.properties
  war/src/main/resources/images/symbols/eye-off-outline.svg
Labels: ready-for-merge, web-ui, rfe, squash-merge-me

#6511 Allow formatted markup for node descriptions
  core/src/main/java/hudson/slaves/SlaveComputer.java
  core/src/main/resources/hudson/model/AbstractModelObject/descriptionForm.jelly
  core/src/main/resources/hudson/model/Computer/index-top.jelly
  core/src/main/resources/hudson/model/Computer/index.jelly
  core/src/main/resources/hudson/slaves/DumbSlave/configure-entries.jelly
  core/src/main/resources/hudson/slaves/SlaveComputer/systemInfo.jelly
  core/src/main/resources/jenkins/model/Jenkins/MasterComputer/index-top.jelly
  core/src/main/resources/jenkins/model/Jenkins/MasterComputer/index-top.properties
  core/src/main/resources/lib/hudson/editable-description.js
  core/src/main/resources/lib/hudson/editableDescription.jelly
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, web-ui, rfe, squash-merge-me, security-approved

#7559 Make system info button text selectable in firefox
  core/src/main/resources/lib/hudson/property-table.css
  core/src/main/resources/lib/hudson/property-table.js
Labels: ready-for-merge, skip-changelog

#7555 [JENKINS-70112] Don't prompt the user that changes may not have been saved after apply clicked
  core/src/main/resources/lib/form/confirm.js
Labels: regression-fix, ready-for-merge, web-ui

#7556 [JENKINS-70128] Revert "Label destructive 'Dismiss' buttons red"
  core/src/main/resources/hudson/diagnosis/HudsonHomeDiskUsageMonitor/message.jelly
  core/src/main/resources/hudson/diagnosis/OldDataMonitor/message.jelly
  core/src/main/resources/hudson/diagnosis/ReverseProxySetupMonitor/message.jelly
  core/src/main/resources/hudson/diagnosis/TooManyJobsButNoView/message.jelly
  core/src/main/resources/hudson/node_monitors/MonitorMarkedNodeOffline/message.jelly
  core/src/main/resources/jenkins/diagnostics/ControllerExecutorsAgents/message.jelly
  core/src/main/resources/jenkins/diagnostics/ControllerExecutorsNoAgents/message.jelly
  core/src/main/resources/jenkins/diagnostics/RootUrlNotSetMonitor/message.jelly
  core/src/main/resources/jenkins/diagnostics/SecurityIsOffMonitor/message.jelly
  core/src/main/resources/jenkins/model/BuiltInNodeMigration/message.jelly
  core/src/main/resources/jenkins/security/RekeySecretAdminMonitor/message.groovy
  core/src/main/resources/jenkins/security/ResourceDomainRecommendation/message.groovy
  core/src/main/resources/jenkins/security/apitoken/ApiTokenPropertyDisabledDefaultAdministrativeMonitor/message.jelly
  core/src/main/resources/jenkins/security/apitoken/ApiTokenPropertyEnabledNewLegacyAdministrativeMonitor/message.jelly
  core/src/main/resources/jenkins/security/csrf/CSRFAdministrativeMonitor/message.jelly
Labels: regression-fix, ready-for-merge, web-ui

#7562 Use morph tag library for f:file
  core/src/main/resources/lib/form/file.jelly
Labels: ready-for-merge, rfe, developer

#7568 [JENKINS-70301] Do not report implied dependencies for WMI Windows Agents plugin
  core/src/main/resources/jenkins/split-plugin-cycles.txt
  core/src/main/resources/jenkins/split-plugins.txt
  war/pom.xml
Labels: ready-for-merge, rfe

#7285 Replace EOL actions/upload-release-asset with softprops/action-gh-release
  .github/workflows/publish-release-artifact.yml
Labels: skip-changelog

#7496 [JENKINS-70169] Add missing breadcrumb items in various `resources/hudson` locations
  core/src/main/resources/hudson/cli/CLIAction/command.jelly
  core/src/main/resources/hudson/cli/CLIAction/index.jelly
  core/src/main/resources/hudson/diagnosis/OldDataMonitor/manage.jelly
  core/src/main/resources/hudson/lifecycle/WindowsInstallerLink/index.jelly
  core/src/main/resources/hudson/model/DirectoryBrowserSupport/dir.jelly
  core/src/main/resources/hudson/model/Job/buildTimeTrend.jelly
  core/src/main/resources/hudson/model/Job/index.jelly
  core/src/main/resources/hudson/model/Label/index.jelly
  core/src/main/resources/hudson/model/Label/load-statistics.jelly
  core/src/main/resources/hudson/model/ManageJenkinsAction/index.jelly
  core/src/main/resources/hudson/model/MyViewsProperty/newView.jelly
  core/src/main/resources/hudson/model/labels/LabelAtom/configure.jelly
  core/src/main/resources/hudson/security/SecurityRealm/signup.jelly
Labels: ready-for-merge, web-ui, rfe

#7550 Update Node.js requirement in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: ready-for-merge, skip-changelog

#7584 Use hashes for third party action
  .github/workflows/publish-release-artifact.yml
Labels: internal, skip-changelog

#7401 [JENKINS-70052] Delete button in delete build has not enough padding
  core/src/main/resources/hudson/model/Run/confirmDelete.jelly
Labels: ready-for-merge, web-ui

#7583 Improve apple touch bar appearance
  core/src/main/resources/lib/layout/layout.jelly
Labels: ready-for-merge, web-ui, skip-changelog

#7580 [JENKINS-70414] Missing agent-side `Channel.close` from `PingThread.onDead`
  core/src/main/java/hudson/slaves/ChannelPinger.java
Labels: ready-for-merge, bug

#7585 Fill in todo annotations
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/ProxyConfiguration.java
  core/src/main/java/hudson/model/ManagementLink.java
  core/src/main/java/hudson/util/FormValidation.java
  core/src/main/java/jenkins/management/Badge.java
  core/src/main/java/jenkins/util/ErrorLoggingExecutorService.java
  core/src/main/java/org/jenkins/ui/symbol/Symbol.java
  core/src/main/java/org/jenkins/ui/symbol/SymbolRequest.java
  core/src/main/resources/lib/form/file.jelly
  core/src/main/resources/lib/form/submit.jelly
  core/src/main/resources/lib/layout/tabPane.jelly
Labels: skip-changelog

#7362 [JENKINS-62332] Remove plugin update GUI “A newer version than being offered for installation exists…”
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/resources/hudson/Messages.properties
  core/src/main/resources/hudson/Messages_es.properties
  core/src/main/resources/hudson/Messages_pt_BR.properties
  core/src/main/resources/hudson/Messages_zh_TW.properties
  core/src/main/resources/hudson/PluginManager/table.jelly
  core/src/main/resources/hudson/PluginManager/table.properties
  core/src/main/resources/hudson/PluginManager/table_it.properties
  core/src/main/resources/hudson/PluginManager/table_pl.properties
  core/src/main/resources/hudson/PluginManager/table_pt_BR.properties
  core/src/main/resources/hudson/PluginManager/table_zh_TW.properties
  test/src/test/java/hudson/PluginManagerTest.java
  war/src/main/js/templates/plugin-manager/available.hbs
  war/src/main/less/abstracts/theme.less
  war/src/main/less/pages/plugin-manager.less
Labels: ready-for-merge, removed

#7547 [JENKINS-70334] Fix and simplify TcpSlaveAgentListenerRescheduler
  core/src/main/java/hudson/TcpSlaveAgentListener.java
Labels: ready-for-merge, bug

#7590 Backporting for 2.375.3
  core/src/main/resources/jenkins/split-plugin-cycles.txt
  core/src/main/resources/jenkins/split-plugins.txt
  core/src/main/resources/lib/layout/breadcrumb.jelly
  core/src/main/resources/lib/layout/breadcrumbBar.jelly
  war/pom.xml
  war/src/main/less/styles.less
Labels: into-lts

#7597 [JENKINS-70240] Backport to 2.375.x
  core/src/main/java/hudson/PluginManager.java
  core/src/main/resources/hudson/Messages.properties
  core/src/main/resources/hudson/Messages_pt_BR.properties
  core/src/main/resources/hudson/Messages_zh_TW.properties
  core/src/test/java/hudson/PluginManagerTest.java
Labels: into-lts

#7573 Encode cloud name in `Cloud#getUrl`
  core/src/main/java/hudson/slaves/Cloud.java
  test/src/test/java/hudson/slaves/CloudTest.java
Labels: ready-for-merge, bug

#7599 Introduce `SubTask.getOwnerExecutable`
  core/src/main/java/hudson/model/Queue.java
  core/src/main/java/hudson/model/queue/SubTask.java
Labels: ready-for-merge, developer

#7595 Compute agents log directory consistently with other tasks
  core/src/main/java/hudson/model/Computer.java
Labels: ready-for-merge, developer

#7609 copyNames has been removed a long time ago, use showCopyOption instead.
  core/src/main/resources/hudson/model/ComputerSet/new.jelly
Labels: ready-for-merge, skip-changelog
