Repository jenkinsci/jenkins, pull requests merged in 2024-04, with the labels that each got.

#9110 Remove usage of `org.apache.commons.lang.StringUtils`
  core/src/test/java/hudson/util/TextFileTest.java
Labels: ready-for-merge, skip-changelog

#8110 Move `AbstractBuild/index.jelly` to `Run/index.jelly`
  core/src/main/resources/hudson/model/AbstractBuild/details.jelly
  core/src/main/resources/hudson/model/AbstractBuild/index.jelly
  core/src/main/resources/hudson/model/AbstractBuild/main.jelly
  core/src/main/resources/hudson/model/Run/index.jelly
  core/src/main/resources/hudson/model/Run/index.properties
  core/src/main/resources/hudson/model/Run/index_bg.properties
  core/src/main/resources/hudson/model/Run/index_ca.properties
  core/src/main/resources/hudson/model/Run/index_cs.properties
  core/src/main/resources/hudson/model/Run/index_da.properties
  core/src/main/resources/hudson/model/Run/index_de.properties
  core/src/main/resources/hudson/model/Run/index_el.properties
  core/src/main/resources/hudson/model/Run/index_en_GB.properties
  core/src/main/resources/hudson/model/Run/index_es.properties
  core/src/main/resources/hudson/model/Run/index_et.properties
  core/src/main/resources/hudson/model/Run/index_fi.properties
  core/src/main/resources/hudson/model/Run/index_fr.properties
  core/src/main/resources/hudson/model/Run/index_he.properties
  core/src/main/resources/hudson/model/Run/index_hu.properties
  core/src/main/resources/hudson/model/Run/index_it.properties
  core/src/main/resources/hudson/model/Run/index_ja.properties
  core/src/main/resources/hudson/model/Run/index_ko.properties
  core/src/main/resources/hudson/model/Run/index_lt.properties
  core/src/main/resources/hudson/model/Run/index_lv.properties
  core/src/main/resources/hudson/model/Run/index_nb_NO.properties
  core/src/main/resources/hudson/model/Run/index_nl.properties
  core/src/main/resources/hudson/model/Run/index_pl.properties
  core/src/main/resources/hudson/model/Run/index_pt_BR.properties
  core/src/main/resources/hudson/model/Run/index_pt_PT.properties
  core/src/main/resources/hudson/model/Run/index_ro.properties
  core/src/main/resources/hudson/model/Run/index_ru.properties
  core/src/main/resources/hudson/model/Run/index_sk.properties
  core/src/main/resources/hudson/model/Run/index_sl.properties
  core/src/main/resources/hudson/model/Run/index_sr.properties
  core/src/main/resources/hudson/model/Run/index_sv_SE.properties
  core/src/main/resources/hudson/model/Run/index_tr.properties
  core/src/main/resources/hudson/model/Run/index_uk.properties
  core/src/main/resources/hudson/model/Run/index_zh_TW.properties
  core/src/main/resources/jenkins/scm/RunWithSCM/changesets.jelly
Labels: ready-for-merge, skip-changelog

#9106 replace usage of old build status sprite svgs with the new symbol-status svgs
  core/src/main/resources/hudson/PluginManager/updates.jelly
  core/src/main/resources/hudson/model/UpdateCenter/CompleteBatchJob/Failure/status.jelly
  core/src/main/resources/hudson/model/UpdateCenter/CompleteBatchJob/Pending/status.jelly
  core/src/main/resources/hudson/model/UpdateCenter/CompleteBatchJob/Running/status.jelly
  core/src/main/resources/hudson/model/UpdateCenter/CompleteBatchJob/Success/status.jelly
  core/src/main/resources/hudson/model/UpdateCenter/DownloadJob/Failure/status.jelly
  core/src/main/resources/hudson/model/UpdateCenter/DownloadJob/Installing/status.jelly
  core/src/main/resources/hudson/model/UpdateCenter/DownloadJob/Pending/status.jelly
  core/src/main/resources/hudson/model/UpdateCenter/DownloadJob/Skipped/status.jelly
  core/src/main/resources/hudson/model/UpdateCenter/DownloadJob/Success/status.jelly
  core/src/main/resources/hudson/model/UpdateCenter/DownloadJob/SuccessButRequiresRestart/status.groovy
  core/src/main/resources/hudson/model/UpdateCenter/RestartJenkinsJob/Canceled/status.jelly
  core/src/main/resources/hudson/model/UpdateCenter/RestartJenkinsJob/Failure/status.jelly
  core/src/main/resources/hudson/model/UpdateCenter/RestartJenkinsJob/Pending/status.jelly
  core/src/main/resources/hudson/model/UpdateCenter/RestartJenkinsJob/Running/status.jelly
  core/src/main/resources/hudson/model/UpdateCenter/body.jelly
  core/src/main/resources/jenkins/widgets/HistoryPageFilter/queue-items.jelly
Labels: ready-for-merge, skip-changelog

#9105 use symbol for keep build forever badge
  core/src/main/resources/hudson/model/Run/KeepLogBuildBadge/badge.jelly
  test/src/test/java/hudson/model/RunTest.java
Labels: ready-for-merge, skip-changelog

#9120 Add /manage to uninstall plugin redirect to preserve breadcrumb
  core/src/main/java/hudson/PluginWrapper.java
Labels: ready-for-merge, skip-changelog

#9115 Refresh the style of alerts
  war/src/main/scss/abstracts/_theme.scss
  war/src/main/scss/base/_style.scss
  war/src/main/scss/components/_alert.scss
  war/src/main/scss/components/_index.scss
Labels: ready-for-merge, web-ui, rfe

#9113 chore: backporting 2.440.3
  bom/pom.xml
  cli/pom.xml
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/slaves/SlaveComputer.java
  core/src/test/java/hudson/model/ComputerTest.java
  war/pom.xml
Labels: into-lts

#9111 Refresh the 'New item' page
  core/src/main/resources/hudson/model/View/newJob.jelly
  core/src/main/resources/hudson/model/View/newJob.properties
  test/src/test/java/hudson/model/ViewTest.java
  war/src/main/js/add-item.js
  war/src/main/js/widgets/add/addform.scss
Labels: ready-for-merge, web-ui, rfe, security-approved

#9125 ci: Set tests check to pending when maven build starts
  Jenkinsfile
Labels: skip-changelog

#9133 [JENKINS-70246] Unexpectedly wide sidepanel
  war/src/main/scss/base/_layout-commons.scss
Labels: ready-for-merge, web-ui, bug

#9136 Remove dead JS code
  war/.eslintrc.js
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, skip-changelog

#9149 Update license file path in README
  README.md
Labels: internal, skip-changelog

#9142 [JEP-235] Remove leftover unused resources
  core/src/main/resources/jenkins/security/s2m/AdminCallableMonitor/description.jelly
  core/src/main/resources/jenkins/security/s2m/AdminCallableMonitor/description.properties
  core/src/main/resources/jenkins/security/s2m/AdminCallableMonitor/description_fr.properties
  core/src/main/resources/jenkins/security/s2m/AdminCallableMonitor/description_pt_BR.properties
  core/src/main/resources/jenkins/security/s2m/MasterKillSwitchWarning/description.jelly
  core/src/main/resources/jenkins/security/s2m/MasterKillSwitchWarning/description.properties
  core/src/main/resources/jenkins/security/s2m/MasterKillSwitchWarning/description_fr.properties
  core/src/main/resources/jenkins/security/s2m/MasterKillSwitchWarning/description_pt_BR.properties
Labels: ready-for-merge, skip-changelog

#9151 Fix formatting
  .github/release-drafter.yml
Labels: skip-changelog, bug

#9143 Remove table usage from buildCaption.jelly
  core/src/main/resources/lib/hudson/buildCaption.jelly
  war/src/main/scss/pages/_build.scss
  war/src/main/scss/pages/_index.scss
Labels: ready-for-merge, skip-changelog

#9157 [JENKINS-72998] call refresh on the Extension providers again
  core/src/main/java/hudson/ExtensionFinder.java
  core/src/main/java/jenkins/model/Jenkins.java
Labels: ready-for-merge, bug

#9155 Fix badges appearance
  core/src/main/resources/lib/layout/badge.jelly
  war/src/main/scss/abstracts/_theme.scss
  war/src/main/scss/components/_badges.scss
Labels: regression-fix, ready-for-merge, web-ui

#9127 [JENKINS-72947] Support symbols in `TopLevelItemDescriptor#getIconClassName()`
  core/src/main/java/hudson/model/FreeStyleProject.java
  core/src/main/java/hudson/model/View.java
  test/src/test/java/hudson/model/ViewTest.java
  war/src/main/js/add-item.js
  war/src/main/resources/images/symbols/freestyle-project.svg
Labels: ready-for-merge, web-ui, rfe

#9083 [JENKINS-65829] Fix WorkspaceCleanupThread to consider suffixed works…
  core/src/main/java/hudson/model/WorkspaceCleanupThread.java
  test/src/test/java/hudson/model/WorkspaceCleanupThreadTest.java
Labels: ready-for-merge, bug

#9167 [JENKINS-73007] Create-item button no longer disabled when duplicate name present
  war/src/main/js/add-item.js
Labels: regression-fix, ready-for-merge

#9162 Set Locale.ROOT when use String.toLowerCase
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/model/AutoCompletionCandidates.java
  core/src/main/java/hudson/search/FixedSet.java
  core/src/main/java/jenkins/security/BasicHeaderProcessor.java
Labels: ready-for-merge, skip-changelog

#9178 Remove duplicate words in Javadoc and test comments
  core/src/main/java/hudson/model/Label.java
  core/src/main/java/hudson/util/StackedAreaRenderer2.java
  test/src/test/java/hudson/model/UserTest.java
Labels: skip-changelog

#9182 [JENKINS-73046] Remove ASM from core
  bom/pom.xml
  core/pom.xml
Labels: ready-for-merge, removed

#9153 Migrate to ESLint 9.1.1
  core/src/main/resources/hudson/model/UpdateCenter/_download-failure.js
  eslint.config.cjs
  war/.eslintignore
  war/.eslintrc.js
  war/package.json
  war/postcss.config.js
  war/src/main/js/add-item.js
  war/src/main/js/filter-build-history.js
  war/src/main/js/pluginSetupWizardGui.js
  war/src/main/js/util/behavior-shim.js
  war/src/main/webapp/scripts/behavior.js
  war/src/main/webapp/scripts/hudson-behavior.js
  war/src/main/webapp/scripts/sortable.js
  war/webpack.config.js
  war/yarn.lock
Labels: ready-for-merge, skip-changelog

#9185 Fix phrasing error in Polish translation of install wizard
  core/src/main/resources/jenkins/install/pluginSetupWizard_pl.properties
Labels: ready-for-merge, bug

#9196 Log explanation for denial from `MappingWorksheet`
  core/src/main/java/hudson/model/queue/MappingWorksheet.java
Labels: skip-changelog

#9191 Update restart banner to align with updated banners
  war/src/main/scss/simple-page.scss
Labels: ready-for-merge, rfe

#9197 Flake in `GNUCLibraryTest`
  core/src/test/java/hudson/util/jna/GNUCLibraryTest.java
Labels: ready-for-merge, skip-changelog

#9204 Backporting for 2.452.1
  bom/pom.xml
  core/src/main/java/hudson/ExtensionFinder.java
  core/src/main/java/hudson/slaves/JNLPLauncher.java
  core/src/main/java/jenkins/model/Jenkins.java
  test/src/test/java/hudson/slaves/JNLPLauncherTest.java
Labels: into-lts

#9205 Update dependabot stable branch
  .github/dependabot.yml
Labels: skip-changelog

#9209 Do not reuse `WebClient` in `StaplerAbstractTest`
  test/src/test/java/jenkins/security/stapler/DoActionFilterTest.java
  test/src/test/java/jenkins/security/stapler/StaplerAbstractTest.java
Labels: ready-for-merge, skip-changelog

#9215 Set `Locale.ROOT` when use `String.toLowerCase`
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/model/AutoCompletionCandidates.java
  core/src/main/java/hudson/search/FixedSet.java
  core/src/main/java/jenkins/security/BasicHeaderProcessor.java
Labels: into-lts
