Repository jenkinsci/jenkins, pull requests merged in 2024-03, with the labels that each got.

#9003 Remove usages of `StringUtils#join`
  core/src/main/resources/hudson/tasks/ArtifactArchiver/help-defaultExcludes.groovy
  core/src/main/resources/hudson/tasks/Fingerprinter/help-defaultExcludes.groovy
Labels: ready-for-merge, skip-changelog

#8999 Reduce usage of `StringUtils`
  cli/src/main/java/hudson/cli/CLI.java
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/model/DirectoryBrowserSupport.java
  core/src/main/java/hudson/model/TopLevelItemDescriptor.java
  core/src/main/java/hudson/model/User.java
  core/src/main/java/hudson/model/View.java
  core/src/main/java/hudson/model/ViewDescriptor.java
  core/src/main/java/hudson/security/SecurityRealm.java
  core/src/main/java/hudson/tasks/BuildTrigger.java
  core/src/main/java/hudson/tasks/Maven.java
  core/src/main/java/hudson/triggers/SCMTrigger.java
  core/src/main/java/hudson/util/io/ZipArchiver.java
  core/src/main/java/jenkins/install/InstallState.java
  core/src/main/java/jenkins/install/InstallUtil.java
  core/src/main/java/jenkins/model/AssetManager.java
  core/src/main/java/jenkins/model/ProjectNamingStrategy.java
  core/src/main/java/jenkins/security/ApiTokenProperty.java
  core/src/main/java/jenkins/security/apitoken/ApiTokenStore.java
  core/src/main/java/jenkins/tasks/filters/impl/RetainVariablesLocalRule.java
  core/src/main/java/jenkins/triggers/ReverseBuildTrigger.java
  core/src/main/java/jenkins/util/SystemProperties.java
  core/src/main/java/jenkins/util/TreeString.java
  core/src/main/java/jenkins/util/VirtualFile.java
  core/src/main/java/org/jenkins/ui/symbol/Symbol.java
  test/src/test/java/jenkins/diagnostics/RootUrlNotSetMonitorTest.java
Labels: ready-for-merge, skip-changelog

#8997 Stop shipping `commons-lang3`
  core/pom.xml
Labels: ready-for-merge, skip-changelog

#8984 [JENKINS-72759] fix handling of readonly for select without parent div
  core/src/main/resources/lib/form/select/select.js
Labels: regression-fix, ready-for-merge

#9002 Further reduce usages of `StringUtils`
  core/src/main/java/hudson/model/Descriptor.java
  core/src/main/java/hudson/util/FormValidation.java
  core/src/test/java/hudson/PluginWrapperTest.java
  test/src/test/java/hudson/cli/DisablePluginCommandTest.java
  test/src/test/java/hudson/security/HudsonPrivateSecurityRealmTest.java
  test/src/test/java/jenkins/security/apitoken/LegacyApiTokenAdministrativeMonitorTest.java
  test/src/test/java/org/kohsuke/stapler/BindTest.java
Labels: ready-for-merge, skip-changelog

#8986 Use `ABORTED` from `Run.reload`
  core/src/main/java/hudson/model/Run.java
Labels: ready-for-merge, rfe

#8884 Replace pipeline-stage-view with graph-view in the setup wizard
  core/src/main/resources/jenkins/install/platform-plugins.json
Labels: skip-changelog

#9001 Remove usages of `ArrayUtils`
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/util/MultipartFormDataParser.java
  core/src/main/java/hudson/util/Protector.java
  core/src/main/java/jenkins/security/ResourceDomainRootAction.java
Labels: ready-for-merge, skip-changelog

#8998 Upgrade `org.apache.commons:commons-compress` from 1.25.0 to 1.26.0 on `stable-2.440`
  bom/pom.xml
  core/pom.xml
Labels: skip-changelog, into-lts

#9005 Update Messages_es.properties, minor fixes in spanish translations
  core/src/main/resources/hudson/model/Messages_es.properties
Labels: ready-for-merge, skip-changelog

#9009 [JENKINS-72799] Apply `SlaveComputer.decorate` also to `openLogFile`
  core/src/main/java/hudson/slaves/SlaveComputer.java
Labels: ready-for-merge, bug

#8979 `Nodes` persistence cleanup, APIs to control loading
  core/src/main/java/hudson/model/Node.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/model/NodeListener.java
  core/src/main/java/jenkins/model/Nodes.java
  test/src/test/java/jenkins/model/NodesTest.java
  test/src/test/resources/jenkins/model/NodesTest/vetoLoad/nodes/one-node/config.xml
Labels: ready-for-merge, developer

#8960 Add copy-to-clipboard button to the build console output
  core/src/main/resources/hudson/model/Run/console.jelly
  core/src/main/resources/hudson/model/Run/console.properties
  core/src/main/resources/lib/layout/copyButton.jelly
  core/src/main/resources/lib/layout/copyButton/copyButton.js
Labels: ready-for-merge, rfe, security-approved

#8860 [JENKINS-72540] FilePath.copyRecursiveTo() copying now also if local and remote have incompatible character sets at binary level
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/util/io/ArchiverFactory.java
  core/src/main/java/hudson/util/io/TarArchiver.java
  core/src/main/java/hudson/util/io/ZipArchiver.java
Labels: ready-for-merge, rfe

#8825 Adds support of sessionId for External-Job-Monitor
  core/src/main/java/hudson/Main.java
Labels: ready-for-merge, rfe, security-approved

#9012 [JENKINS-72796] stable context classloader for Computer.threadPoolForRemoting
  core/src/main/java/hudson/model/Computer.java
  core/src/test/java/hudson/model/ComputerTest.java
Labels: ready-for-merge, bug

#9014 Backporting for LTS 2.440.2
  core/src/main/resources/hudson/model/Job/buildTimeTrend.jelly
  core/src/main/resources/hudson/model/Job/buildTimeTrend_resources.js
  core/src/main/resources/lib/hudson/buildListTable.jelly
  pom.xml
  war/pom.xml
  war/src/main/js/components/tooltips/index.js
Labels: into-lts

#9022 Update bundled trilead-api to 2.84.86.vf9c960e9b_458
  war/pom.xml
Labels: ready-for-merge, dependencies

#9026 [JENKINS-65911] Correct JNA method signature for `fcntl(2)`
  core/src/main/java/hudson/util/jna/GNUCLibrary.java
  core/src/test/java/hudson/util/jna/GNUCLibraryTest.java
Labels: ready-for-merge, bug

#9025 [JENKINS-72833] Do not attempt to self-`exec` on systems without `libc`
  core/src/main/java/hudson/lifecycle/Lifecycle.java
  core/src/main/java/hudson/lifecycle/UnixLifecycle.java
  core/src/main/java/jenkins/util/JavaVMArguments.java
Labels: ready-for-merge, bug

#9019 `Job.fastUpdateNextBuildNumber`
  core/src/main/java/hudson/model/Job.java
Labels: ready-for-merge, skip-changelog

#9013 `Lifecycle.supportsDynamicLoad`
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/lifecycle/Lifecycle.java
  core/src/main/resources/hudson/Messages.properties
Labels: ready-for-merge, skip-changelog

#8985 Link to individual releases' changelog pages
  .github/release-drafter.yml
Labels: ready-for-merge, skip-changelog

#9034 Remove lingering reference to `maven-makepkgs-plugin`
  pom.xml
Labels: ready-for-merge, skip-changelog

#9039 Improve description of "Plain text" markup formatter
  core/src/main/resources/hudson/markup/EscapedMarkupFormatter/config.properties
Labels: ready-for-merge, skip-changelog

#9038 Add help text for Markup Formatter setting
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/help-markupFormatter.html
  core/src/main/resources/jenkins/model/Jenkins/help-markupFormatter.html
  core/src/main/resources/jenkins/model/Jenkins/help-markupFormatter_bg.html
  core/src/main/resources/jenkins/model/Jenkins/help-markupFormatter_it.html
  core/src/main/resources/jenkins/model/Jenkins/help-markupFormatter_ja.html
  core/src/main/resources/jenkins/model/Jenkins/help-markupFormatter_zh_TW.html
Labels: ready-for-merge, skip-changelog, squash-merge-me

#9037 Remove unnecessary `<pluginManagement>` entries
  pom.xml
Labels: ready-for-merge, skip-changelog

#8823 [JENKINS-69191] new icon for agent not accepting tasks and computer icon legend
  core/src/main/java/hudson/model/Computer.java
  core/src/main/resources/hudson/model/ComputerSet/_legend.jelly
  core/src/main/resources/hudson/model/ComputerSet/_legend.properties
  core/src/main/resources/hudson/model/ComputerSet/index.jelly
  war/src/main/js/pages/computer-set/index.js
  war/src/main/resources/images/symbols/computer-not-accepting.svg
  war/webpack.config.js
Labels: ready-for-merge, web-ui, rfe, security-approved

#9020 `QueueIdStrategy`
  core/src/main/java/hudson/model/Queue.java
  core/src/main/java/jenkins/model/queue/QueueIdStrategy.java
  core/src/test/java/hudson/model/QueueTest.java
  test/src/test/java/hudson/model/QueueTest.java
  test/src/test/java/jenkins/model/ParameterizedJobMixInTest.java
Labels: ready-for-merge, skip-changelog

#9056 Remove duplicated words in Javadoc comments
  core/src/main/java/jenkins/slaves/RemotingWorkDirSettings.java
  war/src/main/webapp/scripts/yui/dragdrop/dragdrop-debug.js
  war/src/main/webapp/scripts/yui/editor/editor-debug.js
  war/src/main/webapp/scripts/yui/editor/simpleeditor-debug.js
  war/src/main/webapp/scripts/yui/menu/menu-debug.js
  war/src/main/webapp/scripts/yui/yahoo/yahoo-debug.js
Labels: skip-changelog

#9059 Minor improvements to readability within tests
  test/src/test/java/hudson/model/AbstractProjectTest.java
  test/src/test/java/hudson/model/ViewTest.java
  test/src/test/java/jenkins/model/JenkinsReloadConfigurationTest.java
  test/src/test/java/jenkins/telemetry/TelemetryTest.java
Labels: ready-for-merge, skip-changelog

#9062 Translate description of "Plain text" markup formatter to Turkish
  core/src/main/resources/hudson/markup/EscapedMarkupFormatter/config_tr.properties
Labels: skip-changelog

#9050 `RunListener.allowLoad` + `AbstractLazyLoadRunMap.recognizeNumber`
  core/src/main/java/hudson/model/RunMap.java
  core/src/main/java/hudson/model/ViewJob.java
  core/src/main/java/hudson/model/listeners/RunListener.java
  core/src/main/java/jenkins/model/lazy/AbstractLazyLoadRunMap.java
  core/src/main/java/jenkins/model/lazy/LazyBuildMixIn.java
  core/src/test/java/jenkins/model/lazy/FakeMap.java
Labels: ready-for-merge, skip-changelog

#9053 Follow-up fixes to `Nodes` refactoring
  core/src/main/java/hudson/model/Queue.java
  core/src/main/java/jenkins/model/Nodes.java
Labels: ready-for-merge, skip-changelog

#9063 Removed unneeded exclusions of core dependency in `war`
  war/pom.xml
Labels: ready-for-merge, skip-changelog

#9067 Translate appearance link to Turkish
  core/src/main/resources/jenkins/appearance/AppearanceGlobalConfiguration/index_tr.properties
  core/src/main/resources/jenkins/appearance/Messages_tr.properties
Labels: rfe

#9072 Use Collection.isEmpty() to test if collections are empty
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/cli/DisablePluginCommand.java
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/java/hudson/util/ProcessTree.java
  core/src/main/java/jenkins/security/stapler/DoActionFilter.java
  core/src/main/java/jenkins/security/stapler/TypedFilter.java
  core/src/main/java/jenkins/widgets/HistoryPageFilter.java
Labels: ready-for-merge, skip-changelog

#9071 Set current object to be the administrative monitor itself when loading its description view
  core/src/main/resources/jenkins/management/AdministrativeMonitorsConfiguration/config.groovy
Labels: ready-for-merge, squash-merge-me, developer

#9066 Translate freestyle project description to Turkish
  core/src/main/resources/hudson/model/Messages_tr.properties
Labels: skip-changelog

#9077 Fill in since todos
  cli/src/main/java/hudson/cli/CLIConnectionFactory.java
  core/src/main/java/hudson/lifecycle/Lifecycle.java
  core/src/main/java/hudson/model/ItemGroup.java
  core/src/main/java/hudson/model/RunMap.java
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/java/hudson/security/AbstractPasswordBasedSecurityRealm.java
  core/src/main/java/hudson/util/io/ArchiverFactory.java
  core/src/main/java/jenkins/websocket/WebSockets.java
  core/src/main/resources/lib/layout/badge.jelly
  core/src/main/resources/lib/layout/copyButton.jelly
Labels: ready-for-merge, skip-changelog

#9091 Upgrade bundled plugins
  war/pom.xml
Labels: skip-changelog

#9084 Remove usage of `org.apache.commons.lang.Validate`
  core/src/main/java/hudson/slaves/Cloud.java
Labels: ready-for-merge, skip-changelog

#9089 Bump Mina to 2.12.1 in the CLI
  cli/pom.xml
Labels: dependencies, java

#9102 Introduce a property for Mina SSHD API plugin version
  war/pom.xml
Labels: skip-changelog

#9085 Deprecate `Util#RFC822_DATETIME_FORMATTER`
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/Util.java
Labels: ready-for-merge, skip-changelog

#9092 Remove JENKINS-24380 unmigrate functionality
  core/src/main/java/jenkins/model/RunIdMigrator.java
  core/src/test/java/jenkins/model/RunIdMigratorTest.java
Labels: ready-for-merge, skip-changelog

#9094 Replace usages of `org.apache.commons.lang.StringEscapeUtils` with Guava
  core/src/main/java/hudson/console/ConsoleAnnotationOutputStream.java
  core/src/main/java/hudson/console/PlainTextConsoleOutputStream.java
  core/src/main/java/jenkins/util/SourceCodeEscapers.java
  core/src/test/java/jenkins/util/SourceCodeEscapersTest.java
Labels: ready-for-merge, skip-changelog

#9099 Fix breadcrumb title in `DirectoryBrowserSupport`
  core/src/main/resources/hudson/model/DirectoryBrowserSupport/dir.jelly
Labels: ready-for-merge, bug

#9088 Deprecate `hudson.Util#XS_DATETIME_FORMATTER`
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/Util.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/jenkins/widgets/BuildListTable.java
Labels: ready-for-merge, skip-changelog
