Repository jenkinsci/jenkins, pull requests merged in 2024-09, with the labels that each got.

#9667 [JENKINS-73695] BUG: Dashboard shows white space on certain width space >900px
  core/src/main/resources/lib/hudson/projectView.jelly
  war/src/main/scss/abstracts/_theme.scss
  war/src/main/scss/base/_layout-commons.scss
Labels: ready-for-merge, web-ui, bug

#9687 Disable newly-added flaky test
  test/src/test/java/hudson/cli/CLIActionTest.java
Labels: skip-changelog

#9701 pass the docker group to the container so it can run docker tests
  ath.sh
Labels: skip-changelog

#9463 Disable dependents toggle in plugin manager with system read
  core/src/main/resources/hudson/PluginManager/_table.js
  core/src/main/resources/hudson/PluginManager/installed.jelly
Labels: ready-for-merge, bug, security-approved

#9673 Introduce `ComputerListener#onIdle`
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/slaves/ComputerListener.java
Labels: ready-for-merge, developer

#9645 Add `WithConsoleUrl` interface
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/model/Queue.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/jenkins/console/ConsoleUrlProvider.java
  core/src/main/java/jenkins/console/WithConsoleUrl.java
  test/src/test/java/jenkins/console/ConsoleUrlProviderTest.java
Labels: ready-for-merge, skip-changelog, developer

#9152 [JENKINS-72988] validate displayname against items in the same ItemGroup
  core/src/main/java/hudson/model/TopLevelItemDescriptor.java
  core/src/main/java/jenkins/model/Jenkins.java
  test/src/test/java/jenkins/model/JenkinsTest.java
Labels: ready-for-merge, bug

#9702 fix(i18n): correct typo in Spanish translation for 'Preparation'
  core/src/main/resources/hudson/model/UpdateCenter/ConnectionCheckJob/row_es.properties
Labels: ready-for-merge, skip-changelog

#9709 [JENKINS-73709] Build without forking the compiler
  pom.xml
Labels: ready-for-merge, skip-changelog, full-test

#9717 Build tests without forking the compiler
  test/pom.xml
Labels: skip-changelog

#9674 Introduce `HistoricalBuild` interface
  core/src/main/java/hudson/model/Job.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/widgets/BuildHistoryWidget.java
  core/src/main/java/hudson/widgets/HistoryWidget.java
  core/src/main/java/jenkins/model/HistoricalBuild.java
  core/src/main/java/jenkins/widgets/HistoryPageEntry.java
  core/src/main/java/jenkins/widgets/HistoryPageFilter.java
  core/src/main/resources/hudson/widgets/BuildHistoryWidget/entries.jelly
  core/src/main/resources/hudson/widgets/HistoryWidget/entry.jelly
  core/src/main/resources/lib/hudson/buildProgressBar.jelly
Labels: ready-for-merge, skip-changelog, developer

#7240 Automate the since updater
  .github/workflows/run-since-updater.yml
  update-since-todo.py
Labels: skip-changelog

#9707 Update appearance of 'Jenkins is starting' pages
  core/src/main/resources/hudson/lifecycle/WindowsInstallerLink/_restart.jelly
  core/src/main/resources/hudson/lifecycle/WindowsInstallerLink/_restart.properties
  core/src/main/resources/hudson/util/HudsonIsLoading/index.jelly
  core/src/main/resources/hudson/util/HudsonIsLoading/index.properties
  core/src/main/resources/hudson/util/HudsonIsLoading/index_bg.properties
  core/src/main/resources/hudson/util/HudsonIsLoading/index_cs.properties
  core/src/main/resources/hudson/util/HudsonIsLoading/index_da.properties
  core/src/main/resources/hudson/util/HudsonIsLoading/index_de.properties
  core/src/main/resources/hudson/util/HudsonIsLoading/index_es.properties
  core/src/main/resources/hudson/util/HudsonIsLoading/index_fr.properties
  core/src/main/resources/hudson/util/HudsonIsLoading/index_it.properties
  core/src/main/resources/hudson/util/HudsonIsLoading/index_ja.properties
  core/src/main/resources/hudson/util/HudsonIsLoading/index_ko.properties
  core/src/main/resources/hudson/util/HudsonIsLoading/index_lt.properties
  core/src/main/resources/hudson/util/HudsonIsLoading/index_lv.properties
  core/src/main/resources/hudson/util/HudsonIsLoading/index_nl.properties
  core/src/main/resources/hudson/util/HudsonIsLoading/index_pl.properties
  core/src/main/resources/hudson/util/HudsonIsLoading/index_pt_BR.properties
  core/src/main/resources/hudson/util/HudsonIsLoading/index_ru.properties
  core/src/main/resources/hudson/util/HudsonIsLoading/index_sr.properties
  core/src/main/resources/hudson/util/HudsonIsLoading/index_sv_SE.properties
  core/src/main/resources/hudson/util/HudsonIsLoading/index_tr.properties
  core/src/main/resources/hudson/util/HudsonIsLoading/index_zh_TW.properties
  core/src/main/resources/hudson/util/HudsonIsRestarting/index.jelly
  core/src/main/resources/hudson/util/HudsonIsRestarting/index.properties
  core/src/main/resources/hudson/util/HudsonIsRestarting/index_bg.properties
  core/src/main/resources/hudson/util/HudsonIsRestarting/index_da.properties
  core/src/main/resources/hudson/util/HudsonIsRestarting/index_de.properties
  core/src/main/resources/hudson/util/HudsonIsRestarting/index_es.properties
  core/src/main/resources/hudson/util/HudsonIsRestarting/index_fr.properties
  core/src/main/resources/hudson/util/HudsonIsRestarting/index_it.properties
  core/src/main/resources/hudson/util/HudsonIsRestarting/index_ja.properties
  core/src/main/resources/hudson/util/HudsonIsRestarting/index_nb_NO.properties
  core/src/main/resources/hudson/util/HudsonIsRestarting/index_nl.properties
  core/src/main/resources/hudson/util/HudsonIsRestarting/index_pt_BR.properties
  core/src/main/resources/hudson/util/HudsonIsRestarting/index_ru.properties
  core/src/main/resources/hudson/util/HudsonIsRestarting/index_sr.properties
  core/src/main/resources/hudson/util/HudsonIsRestarting/index_sv_SE.properties
  core/src/main/resources/hudson/util/HudsonIsRestarting/index_uk.properties
  core/src/main/resources/hudson/util/HudsonIsRestarting/index_zh_TW.properties
  war/src/main/scss/components/_spinner.scss
  war/src/main/scss/simple-page.scss
  war/src/main/webapp/css/loading.css
Labels: ready-for-merge, web-ui, rfe

#9653 [JENKINS-73687] Make deserialization of `Map` fields in XML files more robust
  core/src/main/java/hudson/util/RobustMapConverter.java
  core/src/test/java/hudson/util/RobustMapConverterTest.java
Labels: ready-for-merge, bug

#9695 [JENKINS-73695] Prevent unnecessary horizontal scrollbar in Firefox
  war/src/main/scss/components/_table.scss
Labels: regression-fix, ready-for-merge, web-ui, bug

#9724 Use Notice component for views lacking jobs
  core/src/main/resources/hudson/PluginManager/installed.jelly
  core/src/main/resources/hudson/PluginManager/updates.jelly
  core/src/main/resources/hudson/logging/LogRecorder/index.jelly
  core/src/main/resources/hudson/model/View/noJob.jelly
  core/src/main/resources/jenkins/model/Jenkins/systemInfo.jelly
  core/src/main/resources/lib/layout/notice.jelly
  war/src/main/scss/components/_notice.scss
Labels: ready-for-merge, web-ui, rfe, security-approved

#9718 [JENKINS-73744] npm scripts lint:fix do not work
  .babelrc
  .gitignore
  .prettierignore
  .stylelintrc.js
  CONTRIBUTING.md
  eslint.config.cjs
  package.json
  pom.xml
  war/pom.xml
  yarn.lock
Labels: ready-for-merge, web-ui, skip-changelog

#9521 Refine content and appearance of the user account screen
  core/src/main/java/hudson/model/TimeZoneProperty.java
  core/src/main/java/hudson/model/UserPropertyDescriptor.java
  core/src/main/java/jenkins/console/ConsoleUrlProviderUserProperty.java
  core/src/main/resources/hudson/model/Messages.properties
  core/src/main/resources/hudson/model/TimeZoneProperty/config.jelly
  core/src/main/resources/hudson/model/TimeZoneProperty/config.properties
  core/src/main/resources/hudson/model/TimeZoneProperty/config_fr.properties
  core/src/main/resources/hudson/model/TimeZoneProperty/config_it.properties
  core/src/main/resources/hudson/model/TimeZoneProperty/config_ja.properties
  core/src/main/resources/hudson/model/TimeZoneProperty/config_pt_BR.properties
  core/src/main/resources/hudson/model/TimeZoneProperty/config_sv_SE.properties
  core/src/main/resources/hudson/model/TimeZoneProperty/config_zh_TW.properties
  core/src/main/resources/hudson/model/TimeZoneProperty/help-timeZoneName.html
  core/src/main/resources/hudson/model/TimeZoneProperty/help-timeZoneName_ja.html
  core/src/main/resources/hudson/model/TimeZoneProperty/help-timeZoneName_sv_SE.html
  core/src/main/resources/hudson/model/userproperty/UserPropertyCategoryAccountAction/index.jelly
  core/src/main/resources/hudson/model/userproperty/UserPropertyCategoryAccountAction/index.properties
  core/src/main/resources/jenkins/console/ConsoleUrlProviderUserProperty/config.jelly
  core/src/main/resources/jenkins/console/ConsoleUrlProviderUserProperty/config.properties
  core/src/main/resources/jenkins/console/ConsoleUrlProviderUserProperty/config_sv_SE.properties
  core/src/main/resources/jenkins/console/Messages.properties
  core/src/main/resources/lib/form/section.jelly
  war/src/main/scss/components/_section.scss
  war/src/main/webapp/help/user/description.html
  war/src/main/webapp/help/user/description_bg.html
  war/src/main/webapp/help/user/description_de.html
  war/src/main/webapp/help/user/description_fr.html
  war/src/main/webapp/help/user/description_it.html
  war/src/main/webapp/help/user/description_ja.html
  war/src/main/webapp/help/user/description_nl.html
  war/src/main/webapp/help/user/description_pt_BR.html
  war/src/main/webapp/help/user/description_ru.html
  war/src/main/webapp/help/user/description_tr.html
  war/src/main/webapp/help/user/description_zh_TW.html
  war/src/main/webapp/help/user/fullName.html
  war/src/main/webapp/help/user/fullName_bg.html
  war/src/main/webapp/help/user/fullName_de.html
  war/src/main/webapp/help/user/fullName_fr.html
  war/src/main/webapp/help/user/fullName_it.html
  war/src/main/webapp/help/user/fullName_ja.html
  war/src/main/webapp/help/user/fullName_nl.html
  war/src/main/webapp/help/user/fullName_pt_BR.html
  war/src/main/webapp/help/user/fullName_ru.html
  war/src/main/webapp/help/user/fullName_tr.html
  war/src/main/webapp/help/user/fullName_zh_TW.html
Labels: ready-for-merge, web-ui, rfe

#9737 [JENKINS-73785] Restore `ContextMenu#from` with `StaplerRequest`/`Response` args
  core/src/main/java/jenkins/model/ModelObjectWithContextMenu.java
Labels: regression-fix, ready-for-merge, bug

#9733 Backporting 2.462.3 LTS
  core/src/main/java/jenkins/model/BackgroundGlobalBuildDiscarder.java
  core/src/main/java/jenkins/security/ResourceDomainRootAction.java
  test/src/test/java/jenkins/security/ResourceDomainTest.java
  war/src/main/scss/components/_row-selection-controller.scss
Labels: into-lts

#9750 Add full stops to user page descriptions
  core/src/main/resources/hudson/model/Messages.properties
  core/src/main/resources/hudson/model/userproperty/UserPropertyCategoryAccountAction/index.properties
Labels: web-ui, skip-changelog

#9763 Follow idiomatic Python coding style
  update-since-todo.py
Labels: skip-changelog

#9757 [JENKINS-73744] Tweaks to Node.js contributing instructions + renovate fix
  .github/renovate.json
  .gitignore
  CONTRIBUTING.md
Labels: skip-changelog

#9761 [JENKINS-71021] Lint failures do not print proper error message in local builds (regression in 2.359)
  pom.xml
Labels: skip-changelog, squash-merge-me
