Repository jenkinsci/jenkins, pull requests merged in 2024-05, with the labels that each got.

#9224 [JENKINS-73093] Update script-security to 1336.vf33a_a_9863911
  test/pom.xml
  war/pom.xml
Labels: bug

#9201 [JENKINS-72744] remove tooltip when widget is refreshed
  war/src/main/js/components/tooltips/index.js
Labels: regression-fix, ready-for-merge

#9239 Enable reproducible builds
  pom.xml
Labels: skip-changelog

#9203 [JENKINS-53958] allow pipeline jobs to run when built-in is offline
  core/src/main/java/hudson/model/Executor.java
Labels: ready-for-merge, rfe

#9232 Upgrade Winstone from 6.18 to 6.19 (remove support for multiple WAR files)
  pom.xml
Labels: ready-for-merge, upgrade-guide-needed, removed

#9233 Translate item type label to Turkish
  core/src/main/resources/hudson/model/View/newJob_tr.properties
Labels: ready-for-merge, skip-changelog

#9245 Add Reproducible Builds badge
  README.md
Labels: skip-changelog

#9249 remove some Java 8 related parts in war pom
  war/pom.xml
Labels: ready-for-merge, skip-changelog

#9202 Remove 'Disable project' button from project view
  core/src/main/resources/lib/hudson/project/makeDisabled.jelly
  test/src/test/java/hudson/model/ProjectTest.java
Labels: ready-for-merge, rfe

#9248 [JENKINS-21605] Further reduce number of recorded upstream causes
  core/src/main/java/hudson/model/Cause.java
  test/src/test/java/hudson/model/CauseTest.java
Labels: ready-for-merge, bug

#9251 Clean up `executable` package
  war/src/main/java/executable/Main.java
  war/src/test/java/executable/MainTest.java
Labels: ready-for-merge, skip-changelog

#9260 Clean up file parameter tests
  core/src/main/java/hudson/model/FileParameterValue.java
  test/src/test/java/hudson/model/FileParameterValuePersistenceTest.java
  test/src/test/java/hudson/model/QueueTest.java
Labels: ready-for-merge, skip-changelog

#9265 Remove unnecessary references in allowed classes list
  core/src/main/resources/jenkins/security/whitelisted-classes.txt
Labels: ready-for-merge, skip-changelog

#9276 Clarify artifacts permission description
  core/src/main/resources/hudson/model/Messages.properties
  core/src/main/resources/hudson/model/Messages_fr.properties
Labels: ready-for-merge

#9263 [JENKINS-73158] avoid jumping layout due to tooltips
  core/src/main/resources/jenkins/widgets/HistoryPageFilter/queue-items.jelly
  core/src/main/resources/lib/hudson/progressBar.jelly
  core/src/main/resources/lib/hudson/queue.jelly
  core/src/main/resources/lib/layout/stopButton.jelly
  war/src/main/js/components/tooltips/index.js
Labels: ready-for-merge, rfe

#9254 [JENKINS-73114] avoid conflicts with css classes from bootstrap
  core/src/main/resources/hudson/PluginManager/PluginCycleDependenciesMonitor/message.jelly
  core/src/main/resources/hudson/PluginManager/PluginDeprecationMonitor/message.jelly
  core/src/main/resources/hudson/PluginManager/PluginUpdateMonitor/message.jelly
  core/src/main/resources/hudson/PluginManager/advanced.jelly
  core/src/main/resources/hudson/PluginManager/installed.jelly
  core/src/main/resources/hudson/PluginManager/updates.jelly
  core/src/main/resources/hudson/PluginWrapper/PluginWrapperAdministrativeMonitor/message.jelly
  core/src/main/resources/hudson/diagnosis/HudsonHomeDiskUsageMonitor/message.jelly
  core/src/main/resources/hudson/diagnosis/NullIdDescriptorMonitor/message.jelly
  core/src/main/resources/hudson/diagnosis/OldDataMonitor/message.jelly
  core/src/main/resources/hudson/diagnosis/ReverseProxySetupMonitor/message.jelly
  core/src/main/resources/hudson/diagnosis/TooManyJobsButNoView/message.jelly
  core/src/main/resources/hudson/logging/LogRecorder/configure.jelly
  core/src/main/resources/hudson/logging/LogRecorderManager/all.jelly
  core/src/main/resources/hudson/model/UpdateCenter/CoreUpdateMonitor/message.jelly
  core/src/main/resources/hudson/node_monitors/MonitorMarkedNodeOffline/message.jelly
  core/src/main/resources/hudson/triggers/SCMTrigger/AdministrativeMonitorImpl/message.jelly
  core/src/main/resources/hudson/triggers/SlowTriggerAdminMonitor/message.groovy
  core/src/main/resources/hudson/util/AdministrativeError/message.jelly
  core/src/main/resources/hudson/util/DoubleLaunchChecker/message.jelly
  core/src/main/resources/jenkins/diagnosis/HsErrPidList/message.jelly
  core/src/main/resources/jenkins/diagnostics/CompletedInitializationMonitor/message.jelly
  core/src/main/resources/jenkins/diagnostics/ControllerExecutorsAgents/message.jelly
  core/src/main/resources/jenkins/diagnostics/ControllerExecutorsNoAgents/message.jelly
  core/src/main/resources/jenkins/diagnostics/RootUrlNotSetMonitor/message.jelly
  core/src/main/resources/jenkins/diagnostics/SecurityIsOffMonitor/message.jelly
  core/src/main/resources/jenkins/install/SetupWizard/authenticate-security-token.jelly
  core/src/main/resources/jenkins/install/pluginSetupWizard.properties
  core/src/main/resources/jenkins/install/pluginSetupWizard_fr.properties
  core/src/main/resources/jenkins/install/pluginSetupWizard_it.properties
  core/src/main/resources/jenkins/install/pluginSetupWizard_lt.properties
  core/src/main/resources/jenkins/install/pluginSetupWizard_pl.properties
  core/src/main/resources/jenkins/install/pluginSetupWizard_pt_BR.properties
  core/src/main/resources/jenkins/install/pluginSetupWizard_sr.properties
  core/src/main/resources/jenkins/install/pluginSetupWizard_sv_SE.properties
  core/src/main/resources/jenkins/install/pluginSetupWizard_zh_CN.properties
  core/src/main/resources/jenkins/install/pluginSetupWizard_zh_TW.properties
  core/src/main/resources/jenkins/management/AdministrativeMonitorsDecorator/resources.css
  core/src/main/resources/jenkins/model/BuiltInNodeMigration/message.jelly
  core/src/main/resources/jenkins/model/Jenkins/EnforceSlaveAgentPortAdministrativeMonitor/message.jelly
  core/src/main/resources/jenkins/model/Jenkins/downgrade.jelly
  core/src/main/resources/jenkins/monitor/JavaVersionRecommendationAdminMonitor/message.jelly
  core/src/main/resources/jenkins/monitor/OperatingSystemEndOfLifeAdminMonitor/message.jelly
  core/src/main/resources/jenkins/security/RekeySecretAdminMonitor/message.groovy
  core/src/main/resources/jenkins/security/ResourceDomainRecommendation/message.groovy
  core/src/main/resources/jenkins/security/UpdateSiteWarningsMonitor/message.groovy
  core/src/main/resources/jenkins/security/apitoken/ApiTokenPropertyDisabledDefaultAdministrativeMonitor/message.jelly
  core/src/main/resources/jenkins/security/apitoken/ApiTokenPropertyEnabledNewLegacyAdministrativeMonitor/message.jelly
  core/src/main/resources/jenkins/security/apitoken/LegacyApiTokenAdministrativeMonitor/message.jelly
  core/src/main/resources/jenkins/security/csrf/CSRFAdministrativeMonitor/message.jelly
  test/src/test/java/hudson/PluginManagerTest.java
  war/src/main/js/templates/plugin-manager/available.hbs
  war/src/main/scss/components/_alert.scss
  war/src/main/scss/pages/_manage-jenkins.scss
  war/src/main/scss/simple-page.scss
Labels: ready-for-merge, bug

#9219 [JENKINS-73090] Handle CR from `LineTransformationOutputStream`
  core/src/main/java/hudson/console/HyperlinkNote.java
  core/src/main/java/hudson/console/LineTransformationOutputStream.java
  core/src/test/java/hudson/console/LineTransformationOutputStreamTest.java
Labels: ready-for-merge, bug

#9277 Ensure `ClassLoader`s have names for debugging
  core/src/main/java/hudson/ClassicPluginStrategy.java
  core/src/main/java/hudson/PluginFirstClassLoader2.java
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/util/MaskingClassLoader.java
  core/src/main/java/jenkins/util/URLClassLoader2.java
  core/src/test/java/hudson/PluginWrapperTest.java
  pom.xml
  war/src/main/java/executable/Main.java
Labels: ready-for-merge, developer

#9223 move the header parts in a taglib
  core/src/main/resources/jenkins/views/JenkinsHeader/headerContent.jelly
  core/src/main/resources/lib/layout/header/login.jelly
  core/src/main/resources/lib/layout/header/logo.jelly
  core/src/main/resources/lib/layout/header/searchbox.jelly
  core/src/main/resources/lib/layout/header/taglib
Labels: ready-for-merge, rfe, developer

#9259 [JENKINS-73170] Upgrade Commons FileUpload from 1.5 to 2.0.0-M2
  bom/pom.xml
  core/pom.xml
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/model/FileParameterDefinition.java
  core/src/main/java/hudson/model/FileParameterValue.java
  core/src/main/java/hudson/util/MultipartFormDataParser.java
  core/src/main/java/jenkins/model/Jenkins.java
  test/src/test/java/hudson/model/FileParameterValuePersistenceTest.java
  test/src/test/java/jenkins/security/Security3030Test.java
Labels: ready-for-merge, rfe, upgrade-guide-needed, security-approved, ath-successful, pct-successful

#9198 [JENKINS-72622] Rename CloudSet query parameter to avoid conflict
  core/src/main/java/jenkins/agents/CloudSet.java
  core/src/main/resources/jenkins/agents/CloudSet/_new.jelly
Labels: ready-for-merge, bug, developer

#9266 [JENKINS-73156] handle svg cleanup of symbols via an xml document
  core/src/main/java/org/jenkins/ui/symbol/Symbol.java
  war/src/main/resources/images/symbols/journal.svg
  war/src/main/resources/images/symbols/lock-closed.svg
  war/src/main/resources/images/symbols/play.svg
  war/src/main/resources/images/symbols/power.svg
  war/src/main/resources/images/symbols/trash-bin.svg
Labels: ready-for-merge, bug

#9268 Clarify state of `{Job,LazyBuildMixIn}#createHistoryWidget()` method.
  core/src/main/java/hudson/model/AbstractProject.java
  core/src/main/java/hudson/model/Job.java
  core/src/main/java/jenkins/model/lazy/LazyBuildMixIn.java
Labels: ready-for-merge, skip-changelog

#9283 [JENKINS-73168] Restore 'No changes' label when there are no changes in a build
  core/src/main/resources/jenkins/scm/RunWithSCM/changesets.jelly
Labels: ready-for-merge, bug

#9286 [JENKINS-73166] Fix PKCS#12 certificate save to credentials
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: regression-fix, ready-for-merge, bug

#9288 Manage the version of `jakarta.servlet-api` consistently with the version of `jakarta.servlet.jsp.jstl-api`
  bom/pom.xml
  core/pom.xml
Labels: skip-changelog

#9169 Add download option to 'Console output', move 'View as plain text' and 'Copy' buttons to app bar
  core/src/main/resources/hudson/model/Run/console.jelly
  core/src/main/resources/hudson/model/Run/console.properties
  core/src/main/resources/lib/hudson/buildCaption.jelly
  core/src/main/resources/lib/hudson/project/console-link.jelly
  core/src/main/resources/lib/layout/copyButton.jelly
Labels: ready-for-merge, web-ui, rfe, security-approved, ath-successful

#9303 [JENKINS-64356] fix legacyIds missing when creating jobs via REST API or CLI
  core/src/main/java/hudson/model/ItemGroupMixIn.java
  test/src/test/java/jenkins/model/RunIdMigratorTest.java
Labels: ready-for-merge, rfe

#9304 [JENKINS-64553] fix ItemListener not called after updating job via REST API or CLI
  core/src/main/java/hudson/model/AbstractItem.java
  test/src/test/java/hudson/model/listeners/ItemListenerTest.java
Labels: ready-for-merge, bug

#9311 [JENKINS-10629] Migrate from Commons Compress to Ant
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/util/io/TarArchiver.java
  test/src/test/java/hudson/tasks/ArtifactArchiverTest.java
Labels: ready-for-merge, skip-changelog

#9312 Replace usages of JZlib with native Java Platform functionality
  bom/pom.xml
  core/src/main/java/hudson/FilePath.java
  core/src/main/java/hudson/console/AnnotatedLargeText.java
  core/src/main/java/hudson/console/ConsoleNote.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/model/UsageStatistics.java
  core/src/main/java/hudson/util/CompressedFile.java
Labels: ready-for-merge, rfe

#9314 Warn Java 11 users of 18 Jun 2024 end of life in weekly
  core/src/main/java/jenkins/monitor/JavaVersionRecommendationAdminMonitor.java
Labels: ready-for-merge, rfe

#9221 Display how many users there are on the 'Users' page
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/index.jelly
  core/src/main/resources/lib/layout/app-bar.jelly
  war/src/main/scss/components/_app-bar.scss
Labels: ready-for-merge, web-ui, rfe, security-approved

#9287 Remove 'Disable project' button from project view
  core/src/main/resources/lib/hudson/project/makeDisabled.jelly
  test/src/test/java/hudson/model/ProjectTest.java
Labels: ready-for-merge, rfe

#9227 [JENKINS-73047] Fix weather icons
  war/src/main/resources/images/symbols/weather-icon-health-00to19.svg
  war/src/main/resources/images/symbols/weather-icon-health-20to39.svg
  war/src/main/resources/images/symbols/weather-icon-health-60to79.svg
Labels: ready-for-merge, web-ui, bug, security-approved

#9317 Remove 'button-with-dropdown' JS
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, skip-changelog

#9323 Retain Java 11 EOL date for LTS lines
  core/src/main/java/jenkins/monitor/JavaVersionRecommendationAdminMonitor.java
Labels: ready-for-merge, rfe
