Repository jenkinsci/jenkins, pull requests merged in 2024-10, with the labels that each got.

#6867 [JENKINS-60866][JENKINS-71515] Use `JSON#parse` to process `codemirror-config` argument
  core/src/main/java/hudson/markup/MarkupFormatter.java
  core/src/main/resources/hudson/tasks/Shell/config.groovy
  core/src/main/resources/lib/form/textarea/textarea.js
Labels: ready-for-merge, squash-merge-me, developer, ath-successful, pct-successful

#9693 [JENKINS-73437] Fix build history no automatic line wrapping
  war/src/main/scss/pages/_job.scss
Labels: ready-for-merge, web-ui, bug, security-approved

#9735 Refine 'Administrative monitors' interface
  core/src/main/resources/jenkins/management/AdministrativeMonitorsConfiguration/config.groovy
  core/src/main/resources/jenkins/management/AdministrativeMonitorsConfiguration/config_it.properties
  core/src/main/resources/jenkins/management/AdministrativeMonitorsConfiguration/config_ru.properties
  core/src/main/resources/jenkins/management/AdministrativeMonitorsConfiguration/config_sv_SE.properties
  core/src/main/resources/jenkins/management/AdministrativeMonitorsConfiguration/config_tr.properties
  war/src/main/scss/abstracts/_theme.scss
  war/src/main/scss/components/_badges.scss
  war/src/main/scss/form/_checkbox.scss
Labels: ready-for-merge, web-ui, rfe, security-approved

#9743 Introduce `SaveableListener#onDeleted`
  core/src/main/java/hudson/logging/LogRecorder.java
  core/src/main/java/hudson/model/AbstractItem.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/model/listeners/SaveableListener.java
  core/src/main/java/jenkins/model/Nodes.java
  test/src/test/java/hudson/logging/LogRecorderManagerTest.java
  test/src/test/java/hudson/model/AbstractItemTest.java
  test/src/test/java/hudson/model/RunTest.java
  test/src/test/java/jenkins/model/NodesTest.java
Labels: ready-for-merge, developer

#9749 Extract interfaces for objects to be used through the executors widget
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/model/ComputerSet.java
  core/src/main/java/hudson/model/Executor.java
  core/src/main/java/hudson/model/Queue.java
  core/src/main/java/hudson/model/queue/SubTask.java
  core/src/main/java/hudson/security/AuthorizationStrategy.java
  core/src/main/java/jenkins/model/DisplayExecutor.java
  core/src/main/java/jenkins/model/IComputer.java
  core/src/main/java/jenkins/model/IDisplayExecutor.java
  core/src/main/java/jenkins/model/IExecutor.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/model/ModelObjectWithContextMenu.java
  core/src/main/java/jenkins/model/queue/ITask.java
  core/src/main/resources/hudson/model/ComputerSet/index.jelly
  core/src/main/resources/lib/hudson/executors.jelly
  test/src/test/java/hudson/model/ComputerSetTest.java
Labels: ready-for-merge, skip-changelog

#9760 [JENKINS-73760] Updates fail due to invalid JSON from HTTP Update Center
  core/src/main/java/hudson/model/UpdateSite.java
  test/src/test/java/hudson/model/UpdateCenterMigrationTest.java
  test/src/test/java/hudson/model/UpdateSiteTest.java
  test/src/test/resources/hudson/model/UpdateCenterMigrationTest/updateCenterMigration/hudson.model.UpdateCenter.xml
Labels: ready-for-merge, bug

#9764 [JENKINS-73801] Nested Views plugin overrides `View#doConfigDotXml(StaplerRequest)`
  core/src/main/java/hudson/model/View.java
Labels: regression-fix, ready-for-merge

#9766 Be more explicit about not being logged in on 404 error page
  core/src/main/resources/jenkins/model/Jenkins/_404.jelly
  core/src/main/resources/jenkins/model/Jenkins/_404.properties
Labels: ready-for-merge, skip-changelog

#9815 `mvn clean` should clean frontend artifacts
  pom.xml
Labels: skip-changelog

#9822 Account for new Maven version requirement
  CONTRIBUTING.md
Labels: skip-changelog

#9797 [JENKINS-73838] Compatibility for `Jenkins#doSafeRestart(StaplerRequest, String)`
  core/src/main/java/jenkins/cli/SafeRestartCommand.java
  core/src/main/java/jenkins/model/Jenkins.java
Labels: regression-fix, ready-for-merge

#9827 Override the outdated managed dependency on `asm` in `guice-parent`
  bom/pom.xml
Labels: ready-for-merge, bug

#9790 [JENKINS-73824] Wait for Pipeline builds to complete before allowing their jobs to be deleted
  core/src/main/java/jenkins/model/queue/ItemDeletion.java
Labels: ready-for-merge, bug

#9830 Backporting for 2.479.1
  bom/pom.xml
  core/src/main/java/hudson/model/UpdateSite.java
  core/src/main/java/hudson/model/View.java
  core/src/main/java/jenkins/cli/SafeRestartCommand.java
  core/src/main/java/jenkins/model/Jenkins.java
  test/src/test/java/hudson/model/UpdateCenterMigrationTest.java
  test/src/test/java/hudson/model/UpdateSiteTest.java
  test/src/test/resources/hudson/model/UpdateCenterMigrationTest/updateCenterMigration/hudson.model.UpdateCenter.xml
  war/src/main/scss/pages/_job.scss
Labels: into-lts

#9835 Fix dropdowns being added multiple times to the same element
  war/src/main/js/components/dropdowns/utils.js
Labels: ready-for-merge, web-ui, skip-changelog

#9727 [JENKINS-63343] Validate element types for collections and maps when deserializing XML files
  core/src/main/java/hudson/util/RobustCollectionConverter.java
  core/src/main/java/hudson/util/RobustMapConverter.java
  core/src/main/java/hudson/util/RobustReflectionConverter.java
  core/src/test/java/hudson/util/RobustCollectionConverterTest.java
  core/src/test/java/hudson/util/RobustMapConverterTest.java
  core/src/test/java/hudson/util/RobustReflectionConverterTest.java
Labels: ready-for-merge, bug

#9810 [JENKINS-73835] Do not allow builds to be deleted while they are still running and ensure build discarders run after builds are fully complete
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/tasks/LogRotator.java
  core/src/main/java/jenkins/model/BackgroundGlobalBuildDiscarder.java
  core/src/main/java/jenkins/model/GlobalBuildDiscarderListener.java
  core/src/main/resources/hudson/model/Run/delete.jelly
  test/src/test/java/hudson/cli/DeleteBuildsCommandTest.java
  test/src/test/java/hudson/model/RunTest.java
  test/src/test/java/hudson/tasks/LogRotatorTest.java
Labels: ready-for-merge, bug

#9852 Correctly iterate `IComputer`s from `ComputerSet/index.jelly`
  core/src/main/resources/hudson/model/ComputerSet/index.jelly
Labels: ready-for-merge, skip-changelog

#9841 Winstone 8.2: Upgrade Jetty from 12.0.13 to Jetty 12.0.14
  pom.xml
  war/pom.xml
Labels: ready-for-merge, rfe

#9858 Backporting for 2.479.1 (part 2)
  bom/pom.xml
  core/src/main/java/jenkins/model/queue/ItemDeletion.java
  war/pom.xml
Labels: into-lts

#9809 Add tests for empty directory in tar and zip archives
  core/src/test/java/hudson/util/io/TarArchiverTest.java
  core/src/test/java/hudson/util/io/ZipArchiverTest.java
Labels: tests

#9739 [JENKINS-72979] Remove trailing space from Windows agent secret file instructions
  core/src/main/resources/hudson/slaves/JNLPLauncher/main.jelly
Labels: ready-for-merge, bug

#9787 [JENKINS-73813] Show a notification when scheduling a build fails
  core/src/main/resources/hudson/views/BuildButtonColumn/column.jelly
  core/src/main/resources/hudson/views/BuildButtonColumn/column.properties
  core/src/main/resources/hudson/views/BuildButtonColumn/icon.js
  core/src/main/resources/lib/hudson/project/configurable.jelly
  core/src/main/resources/lib/hudson/project/configurable.properties
  core/src/main/resources/lib/hudson/project/configurable/configurable.js
  core/src/main/resources/lib/layout/task.jelly
  core/src/main/resources/lib/layout/task/task.js
  src/main/js/components/dropdowns/jumplists.js
Labels: ready-for-merge, web-ui, rfe

#9876 Stop build in `DeleteBuildsCommandTest.deleteBuildsShouldFailIfTheBuildIsRunning` so test can be cleaned up on Windows consistently
  test/src/test/java/hudson/cli/DeleteBuildsCommandTest.java
Labels: skip-changelog, tests

#9875 Backporting for 2.479.1 (part 3)
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/tasks/LogRotator.java
  core/src/main/java/jenkins/model/BackgroundGlobalBuildDiscarder.java
  core/src/main/java/jenkins/model/GlobalBuildDiscarderListener.java
  core/src/main/resources/hudson/model/Run/delete.jelly
  test/src/test/java/hudson/cli/DeleteBuildsCommandTest.java
  test/src/test/java/hudson/model/RunTest.java
  test/src/test/java/hudson/tasks/LogRotatorTest.java
Labels: into-lts

#9885 Migrate `site.xml` to new model
  core/src/site/site.xml
Labels: skip-changelog

#9878 Print Jenkins version on boot
  core/src/main/java/jenkins/model/Jenkins.java
  test/src/test/java/jenkins/model/JenkinsVersionTest.java
Labels: skip-changelog

#9734 Refine content and appearance of the project 'Configure' screen
  core/src/main/resources/lib/form/descriptorList.jelly
  core/src/main/resources/lib/hudson/project/config-buildWrappers.jelly
  core/src/main/resources/lib/hudson/project/config-buildWrappers.properties
  core/src/main/resources/lib/hudson/project/config-builders.jelly
  core/src/main/resources/lib/hudson/project/config-builders.properties
  core/src/main/resources/lib/hudson/project/config-publishers2.jelly
  core/src/main/resources/lib/hudson/project/config-publishers2.properties
  core/src/main/resources/lib/hudson/project/config-scm.jelly
  core/src/main/resources/lib/hudson/project/config-scm.properties
  core/src/main/resources/lib/hudson/project/config-trigger.jelly
  core/src/main/resources/lib/hudson/project/config-trigger.properties
  src/main/js/section-to-sidebar-items.js
  src/main/scss/components/_section.scss
Labels: ready-for-merge, web-ui, rfe, security-approved

#9887 Reduce default size of diagnostic buffer for `FlightRecorderInputStream` from 1MiB to 1KiB
  cli/src/main/java/hudson/cli/FlightRecorderInputStream.java
  test/src/test/java/hudson/cli/PlainCLIProtocolTest.java
Labels: ready-for-merge, skip-changelog

#9728 [JENKINS-73768] Handle base=derived case in Util#isOverridden
  core/src/main/java/hudson/Util.java
  core/src/test/java/hudson/util/IsOverriddenTest.java
Labels: ready-for-merge, skip-changelog

#9462 Use standard dropdowns for combobox
  core/src/main/resources/lib/form/combobox.jelly
  src/main/js/app.js
  src/main/js/components/dropdowns/autocomplete.js
  src/main/js/components/dropdowns/combo-box.js
  src/main/js/components/dropdowns/index.js
  src/main/js/components/dropdowns/utils.js
Labels: ready-for-merge, web-ui, rfe, security-approved

#8351 [JENKINS-71728] Add CSP compatible version of `FormApply#applyResponse`
  core/src/main/java/hudson/model/Descriptor.java
  core/src/main/java/hudson/util/FormApply.java
  war/src/main/webapp/scripts/apply.js
Labels: ready-for-merge, skip-changelog, squash-merge-me, security-approved

#9882 Allow for null to be passed to `doSafeRestart`
  core/src/main/java/jenkins/model/Jenkins.java
Labels: skip-changelog

#9883 Display appropriate GUI that accurately displays offline by design
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/slaves/OfflineCause.java
  core/src/main/java/hudson/slaves/RetentionStrategy.java
  core/src/main/java/hudson/slaves/SimpleScheduledRetentionStrategy.java
  core/src/main/java/jenkins/agents/IOfflineCause.java
  core/src/main/java/jenkins/model/IComputer.java
  core/src/main/java/jenkins/widgets/ExecutorsWidget.java
  core/src/main/resources/hudson/model/ComputerSet/_legend.jelly
  core/src/main/resources/hudson/model/ComputerSet/_legend.properties
  core/src/main/resources/hudson/model/ComputerSet/index.jelly
  core/src/main/resources/hudson/slaves/Messages.properties
  core/src/main/resources/hudson/slaves/OfflineCause/cause.jelly
  core/src/main/resources/jenkins/agents/Messages.properties
  core/src/main/resources/jenkins/agents/Messages_bg.properties
  core/src/main/resources/jenkins/agents/Messages_ca.properties
  core/src/main/resources/jenkins/agents/Messages_cs.properties
  core/src/main/resources/jenkins/agents/Messages_da.properties
  core/src/main/resources/jenkins/agents/Messages_de.properties
  core/src/main/resources/jenkins/agents/Messages_es.properties
  core/src/main/resources/jenkins/agents/Messages_es_AR.properties
  core/src/main/resources/jenkins/agents/Messages_et.properties
  core/src/main/resources/jenkins/agents/Messages_fi.properties
  core/src/main/resources/jenkins/agents/Messages_fr.properties
  core/src/main/resources/jenkins/agents/Messages_he.properties
  core/src/main/resources/jenkins/agents/Messages_hu.properties
  core/src/main/resources/jenkins/agents/Messages_it.properties
  core/src/main/resources/jenkins/agents/Messages_ja.properties
  core/src/main/resources/jenkins/agents/Messages_ko.properties
  core/src/main/resources/jenkins/agents/Messages_lt.properties
  core/src/main/resources/jenkins/agents/Messages_lv.properties
  core/src/main/resources/jenkins/agents/Messages_nb_NO.properties
  core/src/main/resources/jenkins/agents/Messages_nl.properties
  core/src/main/resources/jenkins/agents/Messages_pl.properties
  core/src/main/resources/jenkins/agents/Messages_pt_BR.properties
  core/src/main/resources/jenkins/agents/Messages_pt_PT.properties
  core/src/main/resources/jenkins/agents/Messages_ro.properties
  core/src/main/resources/jenkins/agents/Messages_ru.properties
  core/src/main/resources/jenkins/agents/Messages_sr.properties
  core/src/main/resources/jenkins/agents/Messages_sv_SE.properties
  core/src/main/resources/jenkins/agents/Messages_tr.properties
  core/src/main/resources/jenkins/agents/Messages_uk.properties
  core/src/main/resources/jenkins/agents/Messages_zh_TW.properties
  core/src/main/resources/lib/hudson/executors.jelly
  test/src/test/java/hudson/model/ComputerTest.java
  war/src/main/resources/images/symbols/computer-paused.svg
  war/src/main/resources/images/symbols/pause.svg
Labels: ready-for-merge, rfe

#9907 Backporting for 2.479.1 (part 4)
  bom/pom.xml
  core/src/main/java/jenkins/model/Jenkins.java
Labels: into-lts

#9903 Removing configurability of `Jenkins.agentProtocols`
  core/src/main/java/hudson/TcpSlaveAgentListener.java
  core/src/main/java/hudson/security/GlobalSecurityConfiguration.java
  core/src/main/java/jenkins/AgentProtocol.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/slaves/JnlpSlaveAgentProtocol4.java
  core/src/main/resources/hudson/Messages.properties
  core/src/main/resources/hudson/Messages_bg.properties
  core/src/main/resources/hudson/Messages_de.properties
  core/src/main/resources/hudson/Messages_es.properties
  core/src/main/resources/hudson/Messages_fr.properties
  core/src/main/resources/hudson/Messages_it.properties
  core/src/main/resources/hudson/Messages_pt_BR.properties
  core/src/main/resources/hudson/Messages_sr.properties
  core/src/main/resources/hudson/Messages_sv_SE.properties
  core/src/main/resources/hudson/Messages_zh_TW.properties
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/help-agentProtocol.html
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/help-agentProtocol_bg.html
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/help-agentProtocol_it.html
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/help-agentProtocol_sv_SE.html
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/index.groovy
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/index_it.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol4/description.jelly
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol4/description.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol4/description_bg.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol4/description_de.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol4/description_fr.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol4/description_it.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol4/description_pt_BR.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol4/description_sv_SE.properties
  core/src/main/resources/jenkins/slaves/JnlpSlaveAgentProtocol4/description_zh_TW.properties
  core/src/main/resources/jenkins/slaves/Messages.properties
  core/src/main/resources/jenkins/slaves/Messages_bg.properties
  core/src/main/resources/jenkins/slaves/Messages_de.properties
  core/src/main/resources/jenkins/slaves/Messages_fr.properties
  core/src/main/resources/jenkins/slaves/Messages_it.properties
  core/src/main/resources/jenkins/slaves/Messages_pt_BR.properties
  core/src/main/resources/jenkins/slaves/Messages_sv_SE.properties
  core/src/main/resources/jenkins/slaves/Messages_zh_TW.properties
  test/src/test/java/jenkins/AgentProtocolTest.java
  test/src/test/java/jenkins/agents/JnlpProtocol4ProxyHandlerTest.java
  test/src/test/java/jenkins/model/JenkinsTest.java
  test/src/test/resources/jenkins/AgentProtocolTest/config.xml
Labels: ready-for-merge, rfe, upgrade-guide-needed

#9908 [JENKINS-73845] Fix OperatingSystemEndOfLifeAdminMonitor endOfLifeDate displayed on first warning day
  core/src/main/java/jenkins/monitor/OperatingSystemEndOfLifeAdminMonitor.java
  core/src/test/java/jenkins/monitor/OperatingSystemEndOfLifeAdminMonitorTest.java
Labels: ready-for-merge, bug

#9890 Turkish localization fixes for security configuration
  core/src/main/resources/hudson/diagnosis/ReverseProxySetupMonitor/message_tr.properties
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/index_tr.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/firstUser_tr.properties
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/success_tr.properties
  core/src/main/resources/hudson/security/Messages_tr.properties
  core/src/main/resources/jenkins/install/SetupWizard/setupWizardFirstUser_tr.properties
Labels: ready-for-merge, skip-changelog

#9891 Translate user property categories to Turkish
  core/src/main/resources/hudson/model/AllView/noJob_tr.properties
  core/src/main/resources/hudson/model/userproperty/Messages_tr.properties
  core/src/main/resources/hudson/model/userproperty/UserPropertyCategoryAccountAction/index_tr.properties
  core/src/main/resources/hudson/model/userproperty/UserPropertyCategoryAppearanceAction/index_tr.properties
  core/src/main/resources/hudson/model/userproperty/UserPropertyCategoryExperimentalAction/index_tr.properties
  core/src/main/resources/hudson/model/userproperty/UserPropertyCategoryPreferencesAction/index_tr.properties
  core/src/main/resources/hudson/model/userproperty/UserPropertyCategorySecurityAction/index_tr.properties
  core/src/main/resources/lib/form/helpLink_tr.properties
  core/src/main/resources/lib/form/saveApplyBar_tr.properties
Labels: ready-for-merge, skip-changelog

#9905 When calling Nodes#setNodes, NodeListener methods should be called as required
  core/src/main/java/jenkins/model/Nodes.java
  test/src/test/java/jenkins/model/NodesTest.java
Labels: ready-for-merge, developer

#9909 Add note about environment variable in parameter file.html
  war/src/main/webapp/help/parameter/file.html
Labels: ready-for-merge, skip-changelog

#9906 Add Resource Root URL test for permissions assigned to groups
  test/src/test/java/jenkins/security/ResourceDomainTest.java
Labels: skip-changelog

#9916 Turkish localization fixes for node list page
  core/src/main/resources/hudson/model/Computer/sidepanel_tr.properties
  core/src/main/resources/hudson/model/ComputerSet/index_tr.properties
  core/src/main/resources/hudson/model/ComputerSet/new_tr.properties
  core/src/main/resources/hudson/model/ComputerSet/sidepanel_tr.properties
  core/src/main/resources/hudson/model/Messages_tr.properties
  core/src/main/resources/hudson/node_monitors/Messages_tr.properties
  core/src/main/resources/hudson/slaves/Messages_tr.properties
  core/src/main/resources/hudson/util/Messages_tr.properties
  core/src/main/resources/jenkins/agents/Messages_tr.properties
  core/src/main/resources/lib/hudson/newFromList/form_tr.properties
Labels: ready-for-merge, skip-changelog
