Repository jenkinsci/jenkins, pull requests merged in 2024-08, with the labels that each got.

#9522 Remove an old m2e configuration
  pom.xml
Labels: ready-for-merge, skip-changelog

#9459 Switch to Renovate from Dependabot for remaining dependencies
  .github/dependabot.yml
  .github/renovate.json
  core/pom.xml
  pom.xml
  test/pom.xml
  war/pom.xml
Labels: ready-for-merge, skip-changelog

#9572 Remove Renovate LTS updates
  .github/renovate.json
Labels: skip-changelog

#9582 Format Renovate JSON file
  .github/renovate.json
Labels: skip-changelog

#9567 Remove accidental debug output from test
  test/src/test/java/jenkins/security/Security3430Test.java
Labels: skip-changelog

#9586 Add version comment for renovate
  .github/workflows/publish-release-artifact.yml
Labels: skip-changelog

#9587 Disable renovate updating org.apache.commons:commons-compress
  .github/renovate.json
Labels: skip-changelog

#9520 [JENKINS-73586] Fix New Item page layout if no icon is defined for an item type
  war/src/main/js/add-item.js
  war/src/main/js/widgets/add/addform.scss
Labels: ready-for-merge, bug

#9502 [JENKINS-73495] Clarify the plugin incompatibility message
  core/src/main/resources/hudson/Messages.properties
  core/src/main/resources/hudson/PluginManager/updates.properties
Labels: ready-for-merge, rfe

#9519 [JENKINS-73554] fix jelly exception
  core/src/main/resources/lib/hudson/executors.jelly
Labels: ready-for-merge, bug

#9588 Rerun failing tests once during releases
  test/pom.xml
Labels: skip-changelog, tests

#9511 [JENKINS-73563] create a jenkins-button instead of a yui button in makeButton
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, web-ui, rfe, security-approved, ath-successful

#9491 [JENKINS-73499] Add a warning if there is a risk of exposing credentials through a non-TLS proxy connection
  core/src/main/java/hudson/ProxyConfiguration.java
  core/src/main/resources/hudson/Messages.properties
  core/src/main/resources/hudson/Messages_es.properties
  core/src/main/resources/hudson/Messages_fr.properties
  core/src/main/resources/hudson/Messages_it.properties
Labels: ready-for-merge

#9602 Revert "[JENKINS-73563] create a jenkins-button instead of a yui button in makeButton"
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: skip-changelog

#9603 Fix `jetty:run`
  war/pom.xml
Labels: skip-changelog

#9604 [JENKINS-73563] Create a `jenkins-button` instead of a YUI button in `makeButton`
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: web-ui, rfe

#9610 Tweak pom so that renovate is able to update test harness
  test/pom.xml
Labels: skip-changelog

#9601 Use SLF4J BOM
  bom/pom.xml
Labels: ready-for-merge, skip-changelog

#9613 Fix Spotless
  test/pom.xml
Labels: skip-changelog

#9614 Backporting for 2.462.2
  war/src/main/js/add-item.js
  war/src/main/js/widgets/add/addform.scss
  war/src/main/scss/components/_table.scss
Labels: into-lts

#9594 [JENKINS-73597] Remove `RekeySecretAdminMonitor` and related resources
  core/src/main/java/hudson/util/SecretRewriter.java
  core/src/main/java/jenkins/management/AsynchronousAdministrativeMonitor.java
  core/src/main/java/jenkins/security/RekeySecretAdminMonitor.java
  core/src/main/resources/jenkins/security/Messages.properties
  core/src/main/resources/jenkins/security/Messages_bg.properties
  core/src/main/resources/jenkins/security/Messages_de.properties
  core/src/main/resources/jenkins/security/Messages_it.properties
  core/src/main/resources/jenkins/security/Messages_ja.properties
  core/src/main/resources/jenkins/security/Messages_pt_BR.properties
  core/src/main/resources/jenkins/security/Messages_ru.properties
  core/src/main/resources/jenkins/security/Messages_sr.properties
  core/src/main/resources/jenkins/security/Messages_sv_SE.properties
  core/src/main/resources/jenkins/security/Messages_zh_TW.properties
  core/src/main/resources/jenkins/security/RekeySecretAdminMonitor/description.jelly
  core/src/main/resources/jenkins/security/RekeySecretAdminMonitor/description.properties
  core/src/main/resources/jenkins/security/RekeySecretAdminMonitor/description_fr.properties
  core/src/main/resources/jenkins/security/RekeySecretAdminMonitor/description_pt_BR.properties
  core/src/main/resources/jenkins/security/RekeySecretAdminMonitor/description_ru.properties
  core/src/main/resources/jenkins/security/RekeySecretAdminMonitor/description_sv_SE.properties
  core/src/main/resources/jenkins/security/RekeySecretAdminMonitor/message.groovy
  core/src/main/resources/jenkins/security/RekeySecretAdminMonitor/message.properties
  core/src/main/resources/jenkins/security/RekeySecretAdminMonitor/message_fr.properties
  core/src/main/resources/jenkins/security/RekeySecretAdminMonitor/message_it.properties
  core/src/main/resources/jenkins/security/RekeySecretAdminMonitor/message_pt_BR.properties
  core/src/main/resources/jenkins/security/RekeySecretAdminMonitor/message_ru.properties
  core/src/main/resources/jenkins/security/RekeySecretAdminMonitor/message_sr.properties
  core/src/main/resources/jenkins/security/RekeySecretAdminMonitor/message_sv_SE.properties
  core/src/main/resources/jenkins/security/RekeySecretAdminMonitor/message_zh_TW.properties
  core/src/test/java/hudson/util/SecretRewriterTest.java
  test/src/test/java/jenkins/security/RekeySecretAdminMonitorTest.java
Labels: ready-for-merge, removed

#9615 Updates to `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: documentation

#9625 Remove trailing backslash from 'Keep this build forever' hover text
  core/src/main/resources/hudson/model/Run/KeepLogBuildBadge/badge.jelly
Labels: ready-for-merge, bug

#9629 Update @since javadoc comments for recent API additions
  core/src/main/java/hudson/lifecycle/Lifecycle.java
  core/src/main/java/hudson/model/listeners/ItemListener.java
  core/src/main/java/jenkins/model/queue/ItemDeletion.java
Labels: skip-changelog

#9631 Second backporting for 2.462.2
  bom/pom.xml
  core/src/main/resources/lib/form/secretTextarea.jelly
  core/src/main/resources/lib/form/secretTextarea/secret.css
  core/src/main/resources/lib/form/secretTextarea/secret.js
  test/pom.xml
  test/src/test/java/hudson/util/FormFieldValidatorTest.java
  test/src/test/java/lib/form/SecretTextareaTest.java
  test/src/test/resources/hudson/util/FormFieldValidatorTest/ValidatingDescribable/config.jelly
  war/pom.xml
Labels: into-lts

#9405 JENKINS-68822 added support for removing all builds with LogRotator
  core/src/main/java/hudson/tasks/ArtifactArchiver.java
  core/src/main/java/hudson/tasks/LogRotator.java
  core/src/main/resources/hudson/tasks/LogRotator/config.jelly
  test/src/test/java/hudson/tasks/LogRotatorTest.java
Labels: ready-for-merge, rfe

#9616 Allow plugins to customize number of suggestions in autocomplete
  war/src/main/js/components/autocomplete/index.js
Labels: ready-for-merge, developer

#9643 Turn down log level of `StaplerFilteredActionListener`
  core/src/main/java/jenkins/security/stapler/StaplerFilteredActionListener.java
Labels: skip-changelog, security-approved

#9652 Upgrade `junit` to 1296.vb_f538b_c88630 on LTS
  test/pom.xml
  war/pom.xml
Labels: into-lts

#9641 [JENKINS-73668] fix styling of rowSelectionController dropdown
  war/src/main/scss/components/_row-selection-controller.scss
Labels: regression-fix, ready-for-merge

#9624 [JENKINS-73613] refresh buildhistory widget in all cases
  core/src/main/resources/hudson/widgets/HistoryWidget/index.jelly
  war/src/main/js/pages/project/builds-card.js
Labels: ready-for-merge, bug

#9661 Fix PathRemoverTest timeout in RISC-V devices.
  core/src/test/java/jenkins/util/io/PathRemoverTest.java
Labels: skip-changelog

#9654 [JENKINS-73330] Fix dropdowns and tooltips on HDR displays
  war/src/main/scss/abstracts/_theme.scss
  war/src/main/scss/components/_dropdowns.scss
  war/src/main/scss/components/_tooltips.scss
Labels: regression-fix, ready-for-merge, web-ui

#9649 don't use backdrop for dialogs
  war/src/main/scss/abstracts/_theme.scss
  war/src/main/scss/components/_dialogs.scss
Labels: ready-for-merge, bug

#9658 [JENKINS-73302] Restore margins around setup wizard alert messages
  core/src/main/resources/jenkins/install/pluginSetupWizard.properties
  core/src/main/resources/jenkins/install/pluginSetupWizard_fr.properties
  core/src/main/resources/jenkins/install/pluginSetupWizard_it.properties
  core/src/main/resources/jenkins/install/pluginSetupWizard_lt.properties
  core/src/main/resources/jenkins/install/pluginSetupWizard_pl.properties
  core/src/main/resources/jenkins/install/pluginSetupWizard_pt_BR.properties
  core/src/main/resources/jenkins/install/pluginSetupWizard_sr.properties
  core/src/main/resources/jenkins/install/pluginSetupWizard_sv_SE.properties
  core/src/main/resources/jenkins/install/pluginSetupWizard_zh_CN.properties
  core/src/main/resources/jenkins/install/pluginSetupWizard_zh_TW.properties
Labels: regression-fix, ready-for-merge, web-ui, bug

#9662 Fix error message when creation of item by type is prohibited
  core/src/main/java/hudson/security/ACL.java
Labels: ready-for-merge, skip-changelog

#9663 [JENKINS-73692] Turn off logging from `BackgroundGlobalBuildDiscarder`
  core/src/main/java/jenkins/model/BackgroundGlobalBuildDiscarder.java
Labels: ready-for-merge, bug

#9665 Add -webSocket option by default when creating an inbound agent
  core/src/main/java/hudson/slaves/JNLPLauncher.java
  core/src/main/resources/hudson/slaves/JNLPLauncher/main.properties
Labels: ready-for-merge, rfe

#9150 Add doCheckDisplayNameOrNull to jenkins core
  core/src/main/java/hudson/model/AbstractProject.java
  core/src/main/java/hudson/model/TopLevelItemDescriptor.java
Labels: ready-for-merge, squash-merge-me, developer

#9648 [JENKINS-73669] don't change unrelated checkboxes in rowSelectionCont…
  core/src/main/resources/hudson/PluginManager/updates.jelly
  core/src/main/resources/lib/layout/rowSelectionController.jelly
  war/src/main/js/components/row-selection-controller/index.js
Labels: ready-for-merge, rfe, security-approved
