Repository jenkinsci/jenkins, pull requests merged in 2025-07, with the labels that each got.

#10802 Restore maven-shade-plugin version setting in cli/pom.xml
  cli/pom.xml
Labels: internal, skip-changelog

#10786 [JENKINS-75834] make sure only one instance of the dropdown is visible
  src/main/js/components/dropdowns/templates.js
Labels: ready-for-merge, web-ui, bug

#10804 [JENKINS-75853] - Remove active look of hamburger button
  core/src/main/resources/lib/layout/header/actions.jelly
Labels: ready-for-merge, bug

#10767 More javadoc for RootAction.isPrimary
  core/src/main/java/hudson/model/RootAction.java
Labels: ready-for-merge, skip-changelog

#10806 Refine header, app bar, and side panel alignment
  core/src/main/resources/lib/layout/skeleton/skeleton.css
  src/main/scss/components/_app-bar.scss
  src/main/scss/components/_page-header.scss
  src/main/scss/components/_side-panel-tasks.scss
Labels: ready-for-merge, web-ui, rfe

#10791 [JENKINS-75832] Support actions with Badges in the Hamburger Menu
  core/src/main/resources/lib/layout/dropdowns/item.jelly
  core/src/main/resources/lib/layout/header/actions.jelly
  core/src/main/resources/lib/layout/header/secondaryAction.jelly
  core/src/main/resources/lib/layout/overflowButton.jelly
  core/src/main/resources/lib/layout/task.jelly
  src/main/js/components/dropdowns/utils.js
Labels: regression-fix, ready-for-merge, web-ui

#10808 Backporting for LTS 2.516.1 (part 1)
  core/src/main/resources/jenkins/model/Jenkins/_script.jelly
  core/src/main/resources/lib/hudson/scriptConsole.jelly
  core/src/main/resources/lib/layout/dropdowns/item.jelly
  core/src/main/resources/lib/layout/header/actions.jelly
  core/src/main/resources/lib/layout/header/secondaryAction.jelly
  core/src/main/resources/lib/layout/overflowButton.jelly
  core/src/main/resources/lib/layout/task.jelly
  src/main/js/components/dropdowns/templates.js
  src/main/js/components/dropdowns/utils.js
  src/main/js/components/header/index.js
Labels: into-lts

#10797 Improve Javadoc of `InMemorySecurityRealm`
  test/src/test/java/test/security/realm/InMemorySecurityRealm.java
Labels: ready-for-merge, internal, skip-changelog, squash-merge-me

#10809 Reduce test flakiness
  src/main/scss/abstracts/_theme.scss
  test/src/test/java/hudson/cli/ComputerStateTest.java
  test/src/test/java/hudson/model/QueueTest.java
  test/src/test/java/hudson/model/RunTest.java
Labels: ready-for-merge, skip-changelog

#10824 Replace deprecated Spring Security `AntPathRequestMatcher` with non-deprecated equivalent
  core/src/main/java/hudson/security/AuthenticationProcessingFilter2.java
Labels: ready-for-merge, skip-changelog

#10752 Remove `/extensionList/` URL
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/telemetry/impl/HttpExtensionList.java
  core/src/main/resources/jenkins/telemetry/impl/HttpExtensionList/description.jelly
  core/src/main/resources/jenkins/telemetry/impl/HttpExtensionList/description.properties
Labels: ready-for-merge, rfe, squash-merge-me, removed

#10825 Prepare Mockito to use `-javaagent` for JEP 451
  core/pom.xml
  test/pom.xml
Labels: ready-for-merge, skip-changelog

#10715 [JENKINS-75637] Fix System configuration page no longer having breadcrumb navigation
  core/src/main/resources/jenkins/model/Jenkins/configure.jelly
  core/src/main/resources/lib/form/breadcrumb-config-outline.jelly
  core/src/main/resources/lib/layout/breadcrumb.jelly
  src/main/js/components/dropdowns/autocomplete.js
  src/main/js/components/dropdowns/inpage-jumplist.js
  src/main/js/components/dropdowns/jumplists.js
  src/main/js/components/dropdowns/utils.js
  src/main/scss/base/_core.scss
Labels: ready-for-merge, web-ui, bug

#10851 fix javadoc missing @
  core/src/main/java/hudson/Functions.java
Labels: internal, skip-changelog

#10844 Removing `throws IOException, ServletException` from most `Permission`-related methods in `Functions`; deleting `adminCheck`
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/model/Hudson.java
Labels: ready-for-merge, skip-changelog

#10853 Refine bottom app bar appearance
  core/src/main/resources/lib/form/bottomButtonBar.jelly
  src/main/js/widgets/add/addform.scss
  src/main/scss/abstracts/_theme.scss
  src/main/scss/components/_app-bar.scss
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, web-ui, rfe

#10881 Fix word breaking in pre tags and help classes
  src/main/scss/base/_style.scss
Labels: ready-for-merge, web-ui, bug

#10803 [JENKINS-75851] implement a dropdown indicator
  core/src/main/resources/lib/layout/breadcrumb.jelly
  src/main/js/components/dropdowns/inpage-jumplist.js
  src/main/js/components/dropdowns/jumplists.js
  src/main/js/components/dropdowns/templates.js
  src/main/js/components/header/breadcrumbs-overflow.js
  src/main/scss/components/_breadcrumbs.scss
  src/main/scss/components/_dropdowns.scss
Labels: ready-for-merge, web-ui, internal
