Repository jenkinsci/jenkins, pull requests merged in 2025-10, with the labels that each got.

#11134 Fix French translations
  cli/src/main/resources/hudson/cli/client/Messages_fr.properties
  core/src/main/resources/hudson/PluginManager/updates_fr.properties
  core/src/main/resources/hudson/model/EnvironmentContributor/EnvVarsHtml/index_de.properties
  core/src/main/resources/hudson/model/EnvironmentContributor/EnvVarsHtml/index_fr.properties
  core/src/main/resources/hudson/model/EnvironmentContributor/EnvVarsHtml/index_ja.properties
  core/src/main/resources/hudson/model/EnvironmentContributor/EnvVarsHtml/index_nl.properties
  core/src/main/resources/hudson/model/EnvironmentContributor/EnvVarsHtml/index_sr.properties
  core/src/main/resources/hudson/model/LoadStatistics/main_fr.properties
  core/src/main/resources/hudson/model/Slave/help-retentionStrategy_fr.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Always/help_fr.properties
  core/src/main/resources/hudson/slaves/RetentionStrategy/Demand/help_fr.properties
  core/src/main/resources/hudson/slaves/SimpleScheduledRetentionStrategy/help_fr.properties
  core/src/main/resources/jenkins/model/CoreEnvironmentContributor/buildEnv_fr.properties
  core/src/main/resources/jenkins/security/UpdateSiteWarningsMonitor/message_fr.properties
Labels: skip-changelog, localization

#11135 Don't fail when no @since tags are found in @since updater
  update-since-todo.py
Labels: skip-changelog

#11133 Add `detectOfflineLinks` set to `false` in `maven-javadoc-plugin` configuration
  pom.xml
Labels: skip-changelog, into-lts, skip-artifact-caching-proxy

#11127 Move experimental run sidepanel to overflow
  core/src/main/resources/hudson/model/AbstractBuild/sidepanel.jelly
  core/src/main/resources/hudson/model/AbstractBuild/tasks.jelly
  core/src/main/resources/hudson/model/Run/new-build-page.jelly
  src/main/scss/pages/_build.scss
Labels: ready-for-merge, web-ui, rfe

#11130 Backporting for LTS 2.528.1 RC
  src/main/scss/pluginSetupWizard.scss
  test/src/test/java/hudson/PluginManagerUtil.java
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: into-lts, skip-artifact-caching-proxy

#11153 Reduce test flakiness: Give agent startup more time (10s -> 30s)
  test/src/test/java/hudson/model/ComputerTest.java
Labels: skip-changelog

#11149 Fix javadoc to refer to the correct method
  core/src/main/java/hudson/FilePath.java
Labels: ready-for-merge, skip-changelog, squash-merge-me, documentation

#11154 Prefer using the SHA of third party actions
  .github/workflows/changelog.yml
  .github/workflows/label-conflicting-pr.yml
  .github/workflows/require-changelog-label.yml
  .github/workflows/run-since-updater.yml
Labels: ready-for-merge, skip-changelog

#11158 Replace deprecated 'tibdex/github-app-token' with native GH action
  .github/workflows/changelog.yml
Labels: ready-for-merge, skip-changelog

#8152 Remove unused utility methods checking for Java 8
  core/src/main/java/jenkins/util/java/JavaUtils.java
  core/src/test/java/jenkins/util/java/JavaUtilsTest.java
Labels: skip-changelog, squash-merge-me

#11052 Retry failing Windows builds on non-spot agent
  Jenkinsfile
Labels: skip-changelog, skip-artifact-caching-proxy

#11159 Converted `config.groovy` to `config.jelly` in proxy config and added German localization
  core/src/main/resources/hudson/Messages_de.properties
  core/src/main/resources/hudson/ProxyConfiguration/config.groovy
  core/src/main/resources/hudson/ProxyConfiguration/config.jelly
  core/src/main/resources/hudson/ProxyConfiguration/config_de.properties
Labels: ready-for-merge, localization

#11174 Sanitize launchable build name
  Jenkinsfile
Labels: skip-changelog

#11178 Remove errant ,
  .github/renovate.json
Labels: skip-changelog
