Repository jenkinsci/jenkins, pull requests merged in 2025-02, with the labels that each got.

#10224 Removed obsolete spotbugs exclusion
  core/src/spotbugs/excludesFilter.xml
Labels: ready-for-merge, skip-changelog

#10228 remove commons-codec usage from core
  core/src/main/java/hudson/Util.java
  core/src/main/java/jenkins/security/seed/UserSeedProperty.java
  core/src/main/java/jenkins/telemetry/Telemetry.java
  core/src/main/java/jenkins/util/JSONSignatureValidator.java
  test/src/test/java/jenkins/telemetry/TelemetryTest.java
Labels: ready-for-merge, skip-changelog

#10190 Remove `robust-http-client`
  bom/pom.xml
  core/pom.xml
  core/src/main/java/hudson/ProxyConfiguration.java
Labels: ready-for-merge, skip-changelog, removed

#10235 [JENKINS-58743] Allow to provide a custom path for master key
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/security/DefaultConfidentialStore.java
  core/src/test/java/jenkins/security/DefaultConfidentialStoreTest.java
Labels: ready-for-merge

#10246 Update Plugin count
  README.md
Labels: skip-changelog

#10233 Migrate from deprecated EE 8 methods to non-deprecated equivalents
  core/src/main/java/hudson/Functions.java
  core/src/main/java/jenkins/console/ConsoleUrlProvider.java
  core/src/main/java/jenkins/model/GlobalComputerRetentionCheckIntervalConfiguration.java
  core/src/main/java/jenkins/model/GlobalConfiguration.java
  core/src/main/resources/hudson/PluginManager/available.jelly
  core/src/main/resources/hudson/PluginManager/installed.jelly
  core/src/main/resources/hudson/PluginManager/updates.jelly
  core/src/main/resources/hudson/diagnosis/MemoryUsageMonitor/index.jelly
  core/src/main/resources/hudson/model/AbstractModelObject/descriptionForm.jelly
  core/src/main/resources/hudson/model/AbstractProject/changes.jelly
  core/src/main/resources/hudson/model/AllView/noJob.groovy
  core/src/main/resources/hudson/model/ComputerSet/_new.jelly
  core/src/main/resources/hudson/model/ParametersAction/index.jelly
  core/src/main/resources/hudson/model/ParametersDefinitionProperty/index.jelly
  core/src/main/resources/hudson/model/Run/delete-retry.jelly
  core/src/main/resources/hudson/model/View/index.jelly
  core/src/main/resources/hudson/search/Search/search-failed.jelly
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/index.groovy
  core/src/main/resources/hudson/security/HudsonPrivateSecurityRealm/signup.jelly
  core/src/main/resources/hudson/security/WhoAmI/index.jelly
  core/src/main/resources/hudson/util/HudsonIsLoading/index.jelly
  core/src/main/resources/hudson/util/HudsonIsRestarting/index.jelly
  core/src/main/resources/jenkins/agents/CloudSet/_new.jelly
  core/src/main/resources/jenkins/install/SetupWizard/authenticate-security-token.jelly
  core/src/main/resources/jenkins/model/Jenkins/_404.jelly
  core/src/main/resources/jenkins/model/Jenkins/_404_simple.jelly
  core/src/main/resources/jenkins/model/Jenkins/login.jelly
  core/src/main/resources/jenkins/model/Jenkins/oops.jelly
  core/src/main/resources/jenkins/model/Jenkins/projectRelationship.jelly
  core/src/main/resources/jenkins/security/seed/UserSeedProperty/config.jelly
  core/src/main/resources/lib/form/editableComboBox.jelly
  core/src/main/resources/lib/hudson/scriptConsole.jelly
  core/src/main/resources/lib/layout/breadcrumbBar.jelly
  core/src/main/resources/lib/layout/layout.jelly
  test/src/test/java/jenkins/model/GlobalComputerRetentionCheckIntervalConfigurationTest.java
Labels: ready-for-merge, skip-changelog, squash-merge-me

#10226 Split one test into two in MarkupTextTest
  core/src/test/java/hudson/MarkupTextTest.java
Labels: ready-for-merge, skip-changelog, tests

#10237 Better document `lib.hudson.widget-refresh`
  core/src/main/resources/lib/hudson/widget-refresh.js
Labels: ready-for-merge, skip-changelog

#10239 `CronTab.floor` / `.ceil` should return times at minute granularity
  core/src/main/java/hudson/scheduler/CronTab.java
  core/src/test/java/hudson/scheduler/CronTabTest.java
Labels: ready-for-merge

#10261 [JENKINS-75265] Fix notification for l:task
  core/src/main/resources/lib/layout/task/task.js
Labels: regression-fix, ready-for-merge

#10264 [JENKINS-75280] Live reload resources again
  war/pom.xml
Labels: regression-fix, skip-changelog

#10269 Include trailing slash in `/computer/xxx/` links
  core/src/main/java/hudson/console/ModelHyperlinkNote.java
  core/src/main/java/hudson/model/AbstractBuild.java
  core/src/main/java/hudson/slaves/NodeProperty.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/resources/hudson/model/Job/buildTimeTrend_resources.js
  core/src/main/resources/jenkins/model/Jenkins/threadDump.jelly
  core/src/main/resources/lib/hudson/node.jelly
Labels: skip-changelog

#10208 Remove jQuery from 'New item' page
  src/main/js/add-item.js
Labels: ready-for-merge, web-ui, skip-changelog

#10271 [JENKINS-75255] Tolerate `AccessDeniedException` in `AtomicFileWriter`
  core/src/main/java/hudson/util/AtomicFileWriter.java
Labels: regression-fix, ready-for-merge

#10273 Require a changelog label
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/require-changelog-label.yml
Labels: skip-changelog

#10279 Format require changelog
  .github/workflows/require-changelog-label.yml
Labels: skip-changelog

#10147 Add experimental 'Details' widget for builds
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/jenkins/model/details/Detail.java
  core/src/main/java/jenkins/model/details/DetailFactory.java
  core/src/main/java/jenkins/model/details/DetailGroup.java
  core/src/main/java/jenkins/model/details/DurationDetail.java
  core/src/main/java/jenkins/model/details/GeneralDetailGroup.java
  core/src/main/java/jenkins/model/details/TimestampDetail.java
  core/src/main/resources/hudson/model/Run/new-build-page.jelly
  core/src/main/resources/jenkins/model/details/DurationDetail/detail.jelly
  core/src/main/resources/jenkins/model/details/DurationDetail/detail.properties
  core/src/main/resources/jenkins/model/details/TimestampDetail/detail.jelly
  core/src/main/resources/jenkins/model/details/TimestampDetail/detail.properties
  src/main/js/components/tooltips/index.js
  src/main/scss/components/_cards.scss
  src/main/scss/pages/_build.scss
  war/src/main/resources/images/symbols/timer.svg
Labels: ready-for-merge, web-ui, major-rfe

#10234 [JENKINS-75152] Update hudson.model.Queue for long buildableItem queue cycle acceleration
  core/src/main/java/hudson/model/Queue.java
Labels: ready-for-merge, rfe

#10302 remove tasklists from PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready-for-merge, skip-changelog

#10307 Flakes in `DisconnectNodeCommandTest.disconnectNodeManyShouldSucceedWithCause`
  test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java
Labels: ready-for-merge, skip-changelog

#10311 Update Gitpod Dockerfile to use Java JDK 21 by default
  .gitpod/Dockerfile
Labels: skip-changelog

#10312 [JENKINS-75273] Fix tabs border radius
  src/main/scss/components/_tabs.scss
Labels: ready-for-merge, web-ui, bug

#10331 Revert "[JENKINS-75152] Update hudson.model.Queue for long buildableItem queue cycle acceleration"
  core/src/main/java/hudson/model/Queue.java
Labels: skip-changelog

#10172 Use UpdateSite implementation for connect and preValidate
  core/src/main/java/hudson/model/UpdateCenter.java
  core/src/main/java/hudson/model/UpdateSite.java
Labels: ready-for-merge, rfe

#10338 Fix checkstyle errors
  core/src/main/java/hudson/model/UpdateCenter.java
Labels: skip-changelog
