Repository jenkinsci/jenkins, pull requests merged in 2025-03, with the labels that each got.

#10240 [JENKINS-75232] Prevent dynamic plugin installation from registering the same extension twice in some cases
  core/src/main/java/hudson/ExtensionList.java
  core/src/main/java/jenkins/model/Jenkins.java
  test/pom.xml
  test/src/test/java/hudson/ExtensionListRjrTest.java
  test/src/test/java/hudson/PluginManagerTest.java
  test/src/test/java/hudson/cli/DisablePluginCommandTest.java
  test/src/test/java/hudson/cli/EnablePluginCommandTest.java
  test/src/test/java/jenkins/plugins/dependee/Dependee.java
  test/src/test/java/jenkins/plugins/dependee/DependeeExtensionPoint.java
  test/src/test/java/jenkins/plugins/dynamic_extension_loading/CustomExtensionLoadedViaConstructor.java
  test/src/test/java/jenkins/plugins/dynamic_extension_loading/CustomExtensionLoadedViaListener.java
  test/src/test/java/jenkins/plugins/dynamic_extension_loading/CustomPeriodicWork.java
  test/src/test/java/jenkins/plugins/dynamic_extension_loading/package-info.java
  test/src/test/java/jenkins/plugins/optional_depender/OptionalDepender.java
  test/src/test/java/jenkins/plugins/optional_depender/OptionalDependerExtension.java
  test/src/test/resources/plugins/jenkins-50336.hpi
  test/src/test/resources/plugins/variant.hpi
Labels: ready-for-merge, bug

#10320 feat: Add empty state for no old data
  core/src/main/resources/hudson/diagnosis/OldDataMonitor/manage.jelly
Labels: ready-for-merge, web-ui, rfe

#10326 Remove `/exception` endpoint
  core/src/main/java/jenkins/model/Jenkins.java
  test/src/test/java/jenkins/security/StackTraceSuppressionTest.java
Labels: ready-for-merge, skip-changelog

#10358 [JENKINS-75341] Sort deprecated plugins in alphabetical order
  core/src/main/java/hudson/PluginManager.java
Labels: ready-for-merge, bug

#10252 Add grouping to Command Palette
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/model/Item.java
  core/src/main/java/hudson/model/User.java
  core/src/main/java/hudson/model/View.java
  core/src/main/java/hudson/search/Search.java
  core/src/main/java/hudson/search/SearchItem.java
  core/src/main/java/jenkins/search/SearchGroup.java
  core/src/main/resources/jenkins/search/Messages.properties
  src/main/js/components/command-palette/datasources.js
  src/main/js/components/command-palette/index.js
  src/main/js/components/command-palette/models.js
  src/main/js/components/command-palette/utils.js
  src/main/scss/abstracts/_theme.scss
  src/main/scss/components/_command-palette.scss
  test/src/test/java/hudson/model/AbstractProjectTest.java
Labels: ready-for-merge, web-ui, rfe

#10386 Add some margin below Add/Edit description button
  core/src/main/resources/lib/hudson/editableDescription.jelly
Labels: ready-for-merge, web-ui, rfe

#10251 [JENKINS-72745] "Manage Jenkins" nested context menu can stay open when parent menu closes
  src/main/js/components/dropdowns/utils.js
Labels: ready-for-merge, bug

#10344 [JENKINS-75278] User pages for users with '\' in the user name fail after upgrading to 2.479.1
  pom.xml
  test/pom.xml
  test/src/test/java/hudson/PluginTest.java
  test/src/test/java/hudson/model/DirectoryBrowserSupportTest.java
  war/pom.xml
Labels: ready-for-merge, bug

#10395 Bump `org.kohsuke.stapler:stapler` from 1955.vdb_2736b_480e3 to 1961.vd0a_a_60970a_a_2
  bom/pom.xml
Labels: skip-changelog

#10391 Remove unnecessary SpotBugs suppressions
  core/src/main/java/hudson/Functions.java
  core/src/main/java/hudson/Launcher.java
  core/src/main/java/hudson/PluginManager.java
  core/src/main/java/hudson/ProxyConfiguration.java
  core/src/main/java/hudson/TcpSlaveAgentListener.java
  core/src/main/java/hudson/cli/CLICommand.java
  core/src/main/java/hudson/cli/Connection.java
  core/src/main/java/hudson/cli/CopyJobCommand.java
  core/src/main/java/hudson/cli/CreateJobCommand.java
  core/src/main/java/hudson/cli/SetBuildDescriptionCommand.java
  core/src/main/java/hudson/cli/SetBuildDisplayNameCommand.java
  core/src/main/java/hudson/console/ConsoleNote.java
  core/src/main/java/hudson/lifecycle/WindowsServiceLifecycle.java
  core/src/main/java/hudson/model/AutoCompletionCandidates.java
  core/src/main/java/hudson/model/Computer.java
  core/src/main/java/hudson/model/FileParameterValue.java
  core/src/main/java/hudson/model/Job.java
  core/src/main/java/hudson/model/Run.java
  core/src/main/java/hudson/model/StringParameterValue.java
  core/src/main/java/hudson/model/UsageStatistics.java
  core/src/main/java/hudson/model/User.java
  core/src/main/java/hudson/model/UserIdMapper.java
  core/src/main/java/hudson/os/WindowsUtil.java
  core/src/main/java/hudson/search/Search.java
  core/src/main/java/hudson/security/AccessDeniedException3.java
  core/src/main/java/hudson/security/Permission.java
  core/src/main/java/hudson/slaves/Channels.java
  core/src/main/java/hudson/slaves/JNLPLauncher.java
  core/src/main/java/hudson/slaves/NodeList.java
  core/src/main/java/hudson/slaves/SlaveComputer.java
  core/src/main/java/hudson/tasks/Fingerprinter.java
  core/src/main/java/hudson/tasks/Maven.java
  core/src/main/java/hudson/triggers/Trigger.java
  core/src/main/java/hudson/util/Graph.java
  core/src/main/java/hudson/util/HttpResponses.java
  core/src/main/java/hudson/util/ReflectionUtils.java
  core/src/main/java/hudson/util/TextFile.java
  core/src/main/java/hudson/widgets/HistoryWidget.java
  core/src/main/java/jenkins/model/Jenkins.java
  core/src/main/java/jenkins/security/CryptoConfidentialKey.java
  core/src/main/java/jenkins/security/stapler/StaplerDispatchValidator.java
  core/src/main/java/jenkins/slaves/restarter/WinswSlaveRestarter.java
  core/src/main/java/jenkins/widgets/HistoryPageFilter.java
  core/src/spotbugs/excludesFilter.xml
Labels: ready-for-merge, skip-changelog

#10365 Update interrupted build action summary icon to symbol-close-circle
  core/src/main/resources/jenkins/model/InterruptedBuildAction/summary.groovy
Labels: ready-for-merge, web-ui, rfe

#10392 Simplify compatibility method
  core/src/main/java/hudson/model/Descriptor.java
Labels: ready-for-merge, skip-changelog

#10364 Add Cancel button to the `Edit description` form
  core/src/main/resources/hudson/model/AbstractModelObject/descriptionForm.jelly
  core/src/main/resources/lib/hudson/editable-description.js
  core/src/main/resources/lib/hudson/editableDescription.jelly
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, web-ui, rfe

#10397 Fix Jenkins#updateNode to call NodeListener#onUpdated
  core/src/main/java/hudson/model/Node.java
  core/src/main/java/hudson/model/Slave.java
  core/src/main/java/jenkins/model/Nodes.java
  test/src/test/java/hudson/model/NodeTest.java
  test/src/test/java/jenkins/model/NodeListenerTest.java
Labels: ready-for-merge, developer

#10400 Remove `Job#getDynamic` compatibility layer
  core/src/main/java/hudson/model/Job.java
Labels: ready-for-merge, skip-changelog

#10425 [Fixes JENKINS-75456] De-flake DisconnectNodeCommandTest
  test/src/test/java/hudson/cli/DisconnectNodeCommandTest.java
Labels: ready-for-merge, skip-changelog

#10413 Do not modify keyboard shortcut when User-Agent header is not set
  core/src/main/java/hudson/Functions.java
Labels: ready-for-merge, bug

#10360 Replace shell `global.groovy` with `global.jelly`
  core/src/main/resources/hudson/tasks/Shell/global.groovy
  core/src/main/resources/hudson/tasks/Shell/global.jelly
Labels: ready-for-merge, internal, skip-changelog

#10427 Improve avatars in high contrast mode
  src/main/js/components/command-palette/models.js
  src/main/scss/components/_avatar.scss
  src/main/scss/components/_command-palette.scss
Labels: ready-for-merge, web-ui, skip-changelog

#10431 [JENKINS-75464] fix enable top button
  core/src/main/resources/lib/form/repeatable/repeatable.js
Labels: ready-for-merge, web-ui, bug

#10382 [JENKINS-75378] Adding a CLI command listener
  core/src/main/java/hudson/cli/CLICommand.java
  core/src/main/java/hudson/cli/declarative/CLIRegisterer.java
  core/src/main/java/jenkins/cli/listeners/CLIContext.java
  core/src/main/java/jenkins/cli/listeners/CLIListener.java
  core/src/main/java/jenkins/cli/listeners/DefaultCLIListener.java
  test/src/test/java/jenkins/cli/DefaultCLIListenerTest.java
Labels: ready-for-merge, rfe

#10362 Replaced `config.groovy` with `config.jelly` in GlobalQuietPeriodConfiguration
  core/src/main/resources/jenkins/model/GlobalQuietPeriodConfiguration/config.groovy
  core/src/main/resources/jenkins/model/GlobalQuietPeriodConfiguration/config.jelly
Labels: ready-for-merge, internal, skip-changelog

#10447 Upgrade Winstone/Jetty with Renovate
  .github/renovate.json
Labels: skip-changelog

#10452 Add note about updating `jetty-ee9-maven-plugin`
  war/pom.xml
Labels: skip-changelog

#10428 Improve appearance of tooltips and dropdowns
  src/main/js/components/dropdowns/templates.js
  src/main/js/components/tooltips/index.js
  src/main/scss/abstracts/_mixins.scss
  src/main/scss/abstracts/_theme.scss
  src/main/scss/components/_buttons.scss
  src/main/scss/components/_dropdowns.scss
  src/main/scss/components/_tooltips.scss
  src/main/scss/form/_search-bar.scss
Labels: ready-for-merge, web-ui, skip-changelog
