Repository jenkinsci/jenkins, pull requests merged in 2025-06, with the labels that each got.

#10708 Add 'jenkins-!-text-color-secondary' class
  src/main/scss/abstracts/_colors.scss
Labels: ready-for-merge, web-ui, rfe

#10712 Add copy-to-clipboard button to oops' stacktrace
  core/src/main/resources/jenkins/model/Jenkins/oops.jelly
Labels: ready-for-merge, rfe

#10713 Fix FileChannelWriterTest and VirtualFileTest for JUnit 5
  core/src/test/java/hudson/util/FileChannelWriterTest.java
  core/src/test/java/jenkins/util/VirtualFileTest.java
Labels: ready-for-merge, skip-changelog

#10582 Migrate tests to JUnit5 (test / misc / 4)
  test/src/test/java/benchmarks/BenchmarkTest.java
  test/src/test/java/lib/form/AdvancedButtonTest.java
  test/src/test/java/lib/form/ApplyButtonTest.java
  test/src/test/java/lib/form/BooleanRadioTest.java
  test/src/test/java/lib/form/ComboBoxTest.java
  test/src/test/java/lib/form/DropdownListTest.java
  test/src/test/java/lib/form/EnumSetTest.java
  test/src/test/java/lib/form/EnumTest.java
  test/src/test/java/lib/form/ExpandableTextboxTest.java
  test/src/test/java/lib/form/FormTest.java
  test/src/test/java/lib/form/HeteroListTest.java
  test/src/test/java/lib/form/NumberTest.java
  test/src/test/java/lib/form/OptionTest.java
  test/src/test/java/lib/form/PasswordTest.java
  test/src/test/java/lib/form/RepeatablePropertyTest.java
  test/src/test/java/lib/form/RepeatableTest.java
  test/src/test/java/lib/form/RowSetTest.java
  test/src/test/java/lib/form/RowVisibilityGroupTest.java
  test/src/test/java/lib/form/SecretTextareaTest.java
  test/src/test/java/lib/form/TextAreaTest.java
  test/src/test/java/lib/form/ValidateButtonTest.java
  test/src/test/java/lib/hudson/ListScmBrowsersTest.java
  test/src/test/java/lib/layout/AjaxTest.java
  test/src/test/java/lib/layout/ConfirmationLinkTest.java
  test/src/test/java/lib/layout/IconTest.java
  test/src/test/java/lib/layout/LayoutTest.java
  test/src/test/java/lib/layout/RenderOnDemandTest.java
  test/src/test/java/lib/layout/StopButtonTest.java
  test/src/test/java/lib/layout/SvgIconTest.java
  test/src/test/java/lib/layout/TaskTest.java
  test/src/test/java/lib/layout/UserExperimentalFlagTest.java
  test/src/test/java/org/kohsuke/stapler/Security1097Test.java
  test/src/test/java/org/kohsuke/stapler/beanutils/TagTest.java
  test/src/test/java/scripts/BehaviorTest.java
Labels: ready-for-merge, internal, skip-changelog, tests

#10721 Refine dialogs and Command Palette
  src/main/js/components/dialogs/index.js
  src/main/scss/abstracts/_theme.scss
  src/main/scss/components/_command-palette.scss
  src/main/scss/components/_dialogs.scss
  src/main/scss/pages/_icon-legend.scss
Labels: ready-for-merge, web-ui, rfe, squash-merge-me

#10711 Backporting for LTS 2.504.3
  pom.xml
  war/pom.xml
Labels: into-lts

#10565 [JENKINS-68934] Replace 'Loading' overlay with skeleton outline on Manage Jenkins pages
  core/src/main/resources/hudson/model/Job/configure.jelly
  core/src/main/resources/hudson/model/Run/configure.jelly
  core/src/main/resources/hudson/security/GlobalSecurityConfiguration/index.groovy
  core/src/main/resources/jenkins/appearance/AppearanceGlobalConfiguration/index.jelly
  core/src/main/resources/jenkins/model/Jenkins/configure.jelly
  core/src/main/resources/jenkins/tools/GlobalToolConfiguration/index.groovy
  core/src/main/resources/lib/layout/skeleton.jelly
  core/src/main/resources/lib/layout/skeleton/skeleton.css
  war/src/main/webapp/scripts/hudson-behavior.js
Labels: ready-for-merge, web-ui, bug

#10760 start introducing data-testids for test usage
  core/src/main/resources/hudson/security/SecurityRealm/loginLink.jelly
Labels: ready-for-merge, skip-changelog, developer

#10678 [JENKINS-75683] re-introduce actions for Jenkins with custom action.jelly
  core/src/main/java/hudson/Functions.java
  core/src/main/java/jenkins/views/Header.java
  core/src/main/resources/lib/layout/header/actions.jelly
  core/src/main/resources/lib/layout/header/primaryAction.jelly
  core/src/main/resources/lib/layout/header/secondaryAction.jelly
  core/src/main/resources/lib/layout/task.jelly
  core/src/test/java/hudson/FunctionsTest.java
  src/main/scss/components/_side-panel-tasks.scss
Labels: regression-fix, ready-for-merge, web-ui, bug

#10716 Allow to queue async periodic work
  core/src/main/java/hudson/model/AsyncPeriodicWork.java
  test/src/test/java/hudson/model/AsyncPeriodicWorkTest.java
Labels: ready-for-merge, developer

#10779 Turkish localization fixes for redesigned header
  core/src/main/resources/hudson/security/SecurityRealm/loginLink_tr.properties
  core/src/main/resources/jenkins/model/Jenkins/login_tr.properties
  core/src/main/resources/jenkins/model/navigation/SearchAction/tooltip_tr.properties
  core/src/main/resources/lib/layout/command-palette_tr.properties
  core/src/main/resources/lib/layout/search-bar_tr.properties
Labels: ready-for-merge, skip-changelog
